<?php

use Application\Entity\Db\Formation;
use Application\Entity\Db\FormationInstance;
use Application\Entity\Db\FormationInstanceInscrit;
use Application\Entity\Db\FormationInstanceJournee;

/**
 * @var FormationInstance $instance
 */

/** @var Formation $formation */
$formation = $instance->getFormation();
/** @var FormationInstanceJournee[] $journees */
$journees = $instance->getJournees();
/** @var FormationInstanceInscrit[] $inscrits */
$inscrits = $instance->getInscrits();
?>

<h1 class="page-header">
    Instance de formation
</h1>

<div class="main">
    <div class="row">
        <div class="col-md-8">
            <h2> Formation </h2>
        </div>
        <div class="pull-right">
            <a      href="<?php echo $this->url('formation/editer', ['formation' => $instance->getFormation()->getId()], [], true); ?>"
                    class="btn btn-info action">
                <span class="icon retour"></span>
                Retour à la formation associée
            </a>
            <br/>
            <a      href="<?php echo $this->url('formation', [], [], true); ?>"
                    class="btn btn-info action">
                <span class="icon retour-double"></span>
                Retour à l'index des formations
            </a>
        </div>
    </div>

    <dl class="dl-horizontal">
        <dt> Intitulé</dt>
        <dd> <?php echo $formation->getLibelle(); ?> </dd>
        <dt>Description</dt>
        <dd>
            <?php echo ($formation->getDescription() !== null AND trim($formation->getDescription()) !== "")?$formation->getDescription():"Aucune description"; ?>
        </dd>
    </dl>

    <h2> Instance </h2>

    <div class="row">
        <div class="col-md-8">
            <h3>
                Journée(s) de formation
                <span class="badge"> <?php echo count($journees); ?></span>
            </h3>
        </div>
        <div class="pull-right">
            <?php /** @see \Application\Controller\FormationInstanceController::ajouterJourneeAction() */?>
            <a      href="<?php echo $this->url('formation-instance/ajouter-journee', ['formation-instance' => $instance->getId()], [], true); ?>"
                    class="btn btn-primary action ajax-modal" data-event="modification">
                <span class="icon ajouter"></span>
                Ajouter journée de formation
            </a>
        </div>
    </div>

    <table id="journees" class="datatable table table-condensed">
        <thead>
            <tr>
                <th> Jour </th>
                <th> Début </th>
                <th> Fin </th>
                <th> Salle </th>
                <th style="width:13rem;"> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($journees as $journee) : ?>
            <tr <?php if ($journee->estHistorise()) echo " class='historise' "; ?>>
                <td> <?php echo $journee->getJour(); ?> </td>
                <td> <?php echo $journee->getDebut(); ?> </td>
                <td> <?php echo $journee->getFin(); ?> </td>
                <td> <?php echo $journee->getLieu(); ?></td>
                <td>
                    <?php /** @see \Application\Controller\FormationInstanceController::modifierJourneeAction() */?>
                    <a      href="<?php echo $this->url('formation-instance/modifier-journee', ['journee' => $journee->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification">
                        <span class="icon editer"></span></a>
                    <?php if ($journee->estNonHistorise()) : ?>
                        <?php /** @see \Application\Controller\FormationInstanceController::historiserJourneeAction() */?>
                        <a      href="<?php echo $this->url('formation-instance/historiser-journee', ['journee' => $journee->getId()], [], true); ?>"
                                >
                            <span class="icon historiser"></span></a>
                    <?php else : ?>
                        <?php /** @see \Application\Controller\FormationInstanceController::restaurerJourneeAction() */?>
                        <a      href="<?php echo $this->url('formation-instance/restaurer-journee', ['journee' => $journee->getId()], [], true); ?>"
                                >
                            <span class="icon restaurer"></span></a>
                    <?php endif; ?>
                    <?php /** @see \Application\Controller\FormationInstanceController::supprimerJourneeAction() */?>
                    <a      href="<?php echo $this->url('formation-instance/supprimer-journee', ['journee' => $journee->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification">
                        <span class="icon detruire"></span></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="row">
        <div class="col-md-8">
            <h3> Agent(s) inscrit(s)
                <span class="badge"><?php echo count($inscrits); ?></span>
            </h3>
        </div>
        <div class="pull-right">
            <a      href="<?php echo $this->url('formation-instance/ajouter-agent', ['formation-instance' => $instance->getId()], [], true); ?>"
                    class="btn btn-primary action ajax-modal" data-event="modification">
                <span class="icon ajouter"></span>
                Ajouter un agent
            </a>
        </div>
    </div>

    <table id="agents" class="datatable table table-condensed">
        <thead>
            <tr>
                <th> Dénomination </th>
                <th> Affection principale </th>
                <th> Date d'ajout </th>
                <th style="width:13rem;"> Action </th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($inscrits as $inscrit) : ?>
            <tr <?php if ($inscrit->estHistorise()) echo " class='historise' "; ?>>
                <td> <?php echo $inscrit->getAgent()->getDenomination(); ?> </td>
                <td> <?php echo $inscrit->getAgent()->getAffectationPrincipale()->getStructure()->getLibelleLong(); ?> </td>
                <td> <?php echo $inscrit->getHistoCreation()->format('d/m/Y'); ?> </td>
                <td>
                    <a href="<?php echo $this->url('agent/afficher', ['agent' => $inscrit->getAgent()->getId()], [], true); ?>">
                        <span class="icon agent"></span></a>
                    <span class="icon pdf"></span>
                    <?php if ($inscrit->estNonHistorise()) : ?>
                        <a  href="<?php echo $this->url('formation-instance/historiser-agent', ['inscrit' => $inscrit->getId()], [], true); ?>">
                            <span class="icon historiser"></span></a>
                    <?php else : ?>
                        <a  href="<?php echo $this->url('formation-instance/restaurer-agent', ['inscrit' => $inscrit->getId()], [], true); ?>">
                            <span class="icon restaurer"></span></a>
                    <?php endif; ?>
                    <a  href="<?php echo $this->url('formation-instance/supprimer-agent', ['inscrit' => $inscrit->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                        <span class="icon detruire"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });
    });
</script>