<?php

namespace EntretienProfessionnel\Provider\Observation;

class EntretienProfessionnelObservations {

    const OBSERVATION_AUTORITE = 'OBS_EP_AUTORITE';
    const OBSERVATION_AGENT_ENTRETIEN = 'OBS_EP_AGENT_ENTRETIEN';
    const OBSERVATION_AGENT_FORMATION = 'OBS_EP_AGENT_FORMATION';
    const OBSERVATION_AGENT_PERSPECTIVE = 'OBS_EP_AGENT_PERSPECTIVE';
    const OBSERVATION_AGENT_FINALE = 'OBS_EP_AGENT_FINALE';
}