<?php

use Carriere\Entity\Db\CorrespondanceType;
use Carriere\Provider\Privilege\CorrespondancePrivileges;

/**
 * @see \Carriere\Controller\CorrespondanceTypeController::indexAction()
 * @var CorrespondanceType[] $types
 */

$this->headTitle("Types de correspondance");


$canAfficher = $this->isAllowed(CorrespondancePrivileges::getResourceId(CorrespondancePrivileges::CORRESPONDANCE_AFFICHER));

$canAction = ($canAfficher)
?>

<h1 class="page-header">
    Types de correspondance
</h1>

<div class="col-md-6 alert alert-info" style="margin-top: 1rem;">
    <span class="icon icon-refresh"></span>
    Données synchronisées
</div>

<a href="<?php echo $this->url('correspondance'); ?>"
   class="btn btn-secondary"
>
    <span class="icon icon-lister"></span>
    Accéder aux correspondances
</a>

<table class="table table-condensed table-hover" id="types">
    <thead>
    <tr>
        <th> Code </th>
        <th> Libellé court </th>
        <th> Libellé long </th>
        <?php if ($canAction) : ?>
            <th> Action </th>
        <?php endif ?>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($types as $type) : ?>
        <tr>
            <td>
                <?php echo $type->getCode(); ?>
                <?php if ($type->getDescription() !== null AND trim($type->getDescription()) !== '') : ?>
                    <span class="icon icon-information" title="<?php echo $type->getDescription(); ?>"></span>
                <?php endif; ?>
            </td>
            <td> <?php echo $type->getLibelleCourt(); ?> </td>
            <td> <?php echo $type->getLibelleLong(); ?> </td>
            <?php if ($canAction) : ?>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <a href="<?php echo $this->url('carriere/correspondance-type/afficher', ['type' => $type->getId()], [], true); ?>"
                       class="ajax-modal">
                            <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $('table#types').DataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [3], orderable: false }
            ]
        });
    });
</script>
