<?php

use Application\Provider\Privilege\FicheMetierPrivileges;
use FicheMetier\Entity\Db\FicheMetier;

/**
 * @var FicheMetier $fichemetier
 * @var string $mode
 */

$canEditer = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));

$metier = $fichemetier->getMetier();
$libelle = $metier->getLibelle(true);

?>

<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    <?php echo $libelle; ?>
                </h1>
            </div>
            <div class="col-md-4">
                <?php if ($mode === 'edition-fiche-metier') : ?>
                    <!-- todo check le privilege et l'action -->
                    <?php /** @see FicheMetierController::modifierMetierAction() */ ?>
                    <a class="btn btn-sm btn-primary action ajax-modal" data-event="modification"
                       href="<?php echo $this->url('fiche-metier/modifier-metier', ['fiche-metier' => $fichemetier->getId()], [], true); ?>">
                        <span class="icon icon-editer"></span>
                        Modifier le métier
                    </a>
                <?php endif; ?>
            </div>
        </div>

        <div class="row" style="border-left: 2px gray solid; margin-bottom: 0.5rem;">
            <div class="col-md-8">
                <h3><u>Raison d'être du métier dans l'établissement</u></h3>
                <?php if ($fichemetier->getRaison() !== null) : ?>
                    <?php echo $fichemetier->getRaison(); ?>
                <?php else :?>
                    Aucune raison de fournie
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <?php if ($canEditer AND $mode === 'edition-fiche-metier' ) : ?>
                    <?php /** @see FicheMetierController::modifierRaisonAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier/modifier-raison', ['fiche-metier' => $fichemetier->getId()], [], true); ?>"
                       class="btn btn-sm btn-primary ajax-modal" data-event="modification"
                    >
                <span class="icon icon-editer">
                    Modifier la raison
                </span>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <dl class="row">
            <dt  class="col-md-4"> Domaine </dt>
            <dd  class="col-md-8">
                <?php $domaines = $metier->getDomaines(); ?>
                <?php if (!empty($domaines)) : ?>
                    <?php foreach ($domaines as $domaine) : ?>
                        <?php echo $domaine->getLibelle(); ?>
                    <?php endforeach; ?>
                <?php else : ?>
                    Aucun domaine
                <?php endif; ?>
            </dd>
            <dt class="col-md-4"> Références </dt>
            <dd class="col-md-8">
                <?php
                    $references = $metier->getReferences();
                    $first = true;
                ?>
                <?php if (!empty($references)) : ?>
                    <?php foreach ($references as $reference) : ?>
                        <?php if ($first) : ?>
                            <?php $first = false; ?>
                        <?php else : ?>
                            <br/>
                        <?php endif; ?>
                        <a href="<?php echo $reference->getUrl(); ?>">
                            <?php echo $reference->getTitre(); ?>
                        </a>
                    <?php endforeach; ?>
                <?php else : ?>
                    Aucune référence
                <?php endif; ?>
            </dd>
            <dt class="col-md-4"> Expertise </dt>
            <dd class="col-md-8">
                <?php if ($fichemetier->hasExpertise()) : ?>
                    Sujet à expertise
                <?php else : ?>
                    Non sujet à expertise
                <?php endif; ?>
                <?php if ($mode === 'edition-fiche-metier') : ?>
                    <a
                        <?php /** @see FicheMetierController::changerExpertiseAction() */ ?>
                        href="<?php echo $this->url('fiche-metier-type/changer-expertise', ['fiche' => $fichemetier->getId()], [], true); ?>"
                    >
                        <span class="icon icon-synchroniser"></span>
                    </a>
                <?php endif; ?>
            </dd>
            <dt class="col-md-4"> Niveau </dt>
            <dd class="col-md-8">
                <?php $enveloppe = $metier->getNiveaux(); ?>
                <?php if ($enveloppe !== null) : ?>
                    De <?php echo $enveloppe->getBorneInferieure()->getLibelle(); ?> (<?php echo $enveloppe->getBorneInferieure()->getEtiquette(); ?>)
                    à <?php echo $enveloppe->getBorneSuperieure()->getLibelle(); ?> (<?php echo $enveloppe->getBorneSuperieure()->getEtiquette(); ?>)
                <?php else : ?>
                    Non renseigné
                <?php endif; ?>
            </dd>
        </dl>
    </div>
</div>
