<?php

/**
 * @var Etat[] $etats
 */

use UnicaenEtat\Entity\Db\Etat;


?>

<table id="etats" class="table table-condensed datatable">
    <thead>
        <tr>
            <th> Badge </th>
            <th> Code </th>
            <th> Description </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($etats as $etat) : ?>
        <tr>
            <td> <?php echo $this->etatbadge($etat); ?> </td>
            <td> <?php echo $etat->getCode(); ?> </td>
            <td> <?php echo $etat->getLibelle(); ?> </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    // $(document).ready(function() {
    //     var table_etat = $('table#etats').DataTable({
    //         "paging": false
    //     });

    $(function() {
        $('table#etats').DataTable({
            "paging": false
        });

        $("body").on("creation-etat", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
    $(function() {
        $("body").on("modification-etat", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
    $(function() {
        $("body").on("destruction-etat", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>