<?php

use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\Metier;

/**
 * @var Metier[] $metiers
 * @var FicheMetier $fiche
 */

$canVoir = true;
$canEditer = true;
$canHistoriser = true;
$canDetruire = true;

?>

<table class="datatable table table-condensed" id="metiers">
    <thead>
    <tr>
        <th> Métier </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($metiers as $metier) : ?>
        <?php $fiches = $metier->getFichesMetiers(); ?>
        <tr>
            <td class="metier" id="<?php echo $metier->getId(); ?>">
                <div class="row">
                    <div class="col-md-8">
                        <span title='<?php echo $metier->generateTooltip(); ?>'
                              data-toggle='tooltip' data-html='true'
                        >
                            <?php echo $metier->getLibelle(); ?>
                        </span>
                    </div>
                    <div class="pull-right">#fiche:<?php echo count($fiches); ?></div>
                </div>
                <div class="fiches" id="f<?php echo $metier->getId(); ?>">

                    <a
                        <?php /** @see \Application\Controller\FicheMetierController::ajouterAvecMetierAction() */ ?>
                        href="<?php echo $this->url('fiche-metier-type/ajouter-avec-metier', ['metier' => $metier->getId()], [], true); ?>"
                        class="btn btn-primary action"
                    >
                        <span class="icon ajouter"></span>
                        Ajouter une fiche métier
                    </a>

                    <br/>
                    <br/>

                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th style="width:12rem;"> État </th>
                                <th> Id. </th>
                                <th> Dernière modification </th>
                                <th> Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($metier->getFichesMetiers() as $fiche) : ?>
                            <tr <?php if($fiche->estHistorise()) echo 'class="historise"'; ?>>
                                <td>
                                    <?php if ($canEditer) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\FicheMetierController::changerEtatAction() */?>
                                                href="<?php echo $this->url('fiche-metier-type/changer-etat', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                                                title="Changer l'état de la fiche métier"
                                                class="ajax-modal" data-event="changer-etat"
                                        >
                                            <?php endif; ?>
                                            <?php echo $this->ficheMetierEtat($fiche->getEtat()); ?>
                                            <?php if ($canEditer) : ?>
                                        </a>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php echo $fiche->getId(); ?>
                                </td>
                                <td>
                                    <?php echo $fiche->getHistoModification()->format('d/m/Y à H:i:s'); ?>
                                    par
                                    <?php echo $fiche->getHistoModificateur()->getDisplayName(); ?>
                                </td>
                                <td>
                                    <?php if ($canVoir) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\FicheMetierController::afficherAction() */?>
                                                href="<?php echo $this->url('fiche-metier-type/afficher', ['id' => $fiche->getId()], [], true); ?>"
                                                title="Afficher la fiche métier"
                                                class="ajax-modal"
                                        >
                                            <span class="icon voir"></span></a>
                                    <?php endif; ?>
                                    <?php if ($canVoir) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\FicheMetierController::exporterAction() */?>
                                                href="<?php echo $this->url('fiche-metier-type/exporter', ['id' => $fiche->getId()], [], true); ?>"
                                                title="Exporter en PDF la fiche métier"
                                        >
                                            <span class="icon pdf"></span></a>
                                    <?php endif; ?>
                                    <?php if ($canEditer) : ?>
                                        <a href="<?php echo $this->url('fiche-metier-type/editer', ['id' => $fiche->getId()], [], true); ?>"
                                           title="Modifier la fiche metier">
                                            <span class="icon editer"></span></a>
                                    <?php endif; ?>
                                    <?php if ($canHistoriser) : ?>
                                        <?php if($fiche->estNonHistorise()) :?>
                                            <a href="<?php echo $this->url('fiche-metier-type/historiser', ['id' => $fiche->getId()], [], true); ?>"
                                               title="Historiser la fiche metier">
                                                <span class="icon historiser"></span></a>
                                        <?php else: ?>
                                            <a href="<?php echo $this->url('fiche-metier-type/restaurer', ['id' => $fiche->getId()], [], true); ?>"
                                               title="Restaurer la fiche metier">
                                                <span class="icon restaurer"></span></a>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($canDetruire) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\FicheMetierController::detruireAction() */?>
                                                href="<?php echo $this->url('fiche-metier-type/detruire', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                                                title="Détruire la fiche metier"
                                                class="ajax-modal" data-event="destruction"
                                        >
                                            <span class="icon detruire"></span></a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<style>
    div.fiches {
        border: 1px solid grey;
        background: whitesmoke;
        border-radius: 0.5rem;
        margin:2rem;
        padding:1rem;
    }

    div.fiches table {
        background-color: whitesmoke;
    }

    div.fiches table th{
        background-color: cornflowerblue;
    }
    div.fiches table td{
        /*background-color: whitesmoke;*/
    }
</style>

<script>
    $('div.fiches').hide();

    $('td.metier').click(function() {
        console.log($(this));
        $('div.fiches').hide();
        $(this).children('div.fiches').show();
    })

    let loaded = false;
    $('[data-toggle="tooltip"]').tooltip();

    $(document).ready(function() {
        var table = $('table#metiers').DataTable({
            "paging": false
        });
        let searchParams = new URLSearchParams(window.location.search);
        let param = searchParams.get('search')
        if (param !== null) {
            table.search(param);
            table.draw();
        }
        loaded = true;
    });

    // $(document).on('search.dt', function () {
    //     if (loaded === true) {
    //         let valeur = $('input[aria-controls=metiers]').val();
    //         console.log(valeur);
    //         history.replaceState({}, null, '?search=' + valeur + '#metier');
    //         $('[data-toggle="tooltip"]').tooltip();
    //     }
    // });
</script>