<?php

/**
 * @var FicheMetier[] $fiches
 * @var Domaine[] $domaines
 * @var Domaine $domaineSelect
 */

use Metier\Entity\Db\Domaine;
use Application\Entity\Db\FicheMetier;
use Application\Provider\Privilege\FicheMetierPrivileges;

$canVoir        = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));
$canHistoriser  = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_HISTORISER));
$canEditer      = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));
$canDetruire    = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_DETRUIRE));

?>


<table id="fiches" class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> Domaine </th>
        <th  style="width:8rem;"> État </th>
        <th  style="width:14rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($fiches as $fiche): ?>
        <tr <?php if ($fiche->estHistorise()) echo "class='historise'"; ?> >
            <td>
                <span title='<?php echo $fiche->getMetier()->generateTooltip(); ?>'
                      data-toggle='tooltip' data-html='true'
                >
                    <?php echo $fiche->getMetier()->getLibelle(true); ?>
                </span>
                <?php if ($fiche->hasExpertise() === true) : ?>
                    <span class="label" style="background: lightskyblue;">Expertise</span>
                <?php endif; ?>
            </td>
            <td>
                <ul>
                    <?php foreach ($fiche->getMetier()->getDomaines() as $domaine) : ?>
                        <li>
                            <?php echo $domaine; ?>
                            <?php echo $this->typefonction($domaine); ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td class="cell-etat">
                <?php if ($canEditer) : ?>
                <a
                    <?php /** @see \Application\Controller\FicheMetierController::changerUEtatAction() */?>
                        href="<?php echo $this->url('fiche-metier-type/changer-etat', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                        title="Changer l'état de la fiche métier"
                        class="ajax-modal" data-event="changer-etat"
                >
                    <?php endif; ?>
                    <?php echo $this->etatbadge($fiche->getEtat()); ?>
                    <?php if ($canEditer) : ?>
                </a>
            <?php endif; ?>
            </td>
            <td class="cell-action">
                <?php if ($canVoir) : ?>
                    <a
                        <?php /** @see \Application\Controller\FicheMetierController::afficherAction() */?>
                        href="<?php echo $this->url('fiche-metier-type/afficher', ['id' => $fiche->getId()], [], true); ?>"
                        title="Afficher la fiche métier"
                    >
                        <span class="icon icon-voir"></span></a>
                <?php endif; ?>
                <?php if ($canVoir) : ?>
                    <a
                        <?php /** @see \Application\Controller\FicheMetierController::exporterAction() */?>
                        href="<?php echo $this->url('fiche-metier-type/exporter', ['id' => $fiche->getId()], [], true); ?>"
                        title="Exporter en PDF la fiche métier"
                    >
                        <span class="icon icon-pdf"></span></a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <a href="<?php echo $this->url('fiche-metier-type/editer', ['id' => $fiche->getId()], [], true); ?>"
                       title="Modifier la fiche metier">
                        <span class="icon icon-editer"></span></a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <?php /** @see \Application\Controller\FicheMetierController::dupliquerAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier-type/dupliquer', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                       title="Dupliquer la fiche metier">
                        <span class="icon icon-cloner"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if($fiche->estNonHistorise()) :?>
                        <a href="<?php echo $this->url('fiche-metier-type/historiser', ['id' => $fiche->getId()], [], true); ?>"
                           title="Historiser la fiche metier">
                            <span class="icon icon-historiser"></span></a>
                    <?php else: ?>
                        <a href="<?php echo $this->url('fiche-metier-type/restaurer', ['id' => $fiche->getId()], [], true); ?>"
                           title="Restaurer la fiche metier">
                            <span class="icon icon-restaurer"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <a
                        <?php /** @see \Application\Controller\FicheMetierController::detruireAction() */?>
                        href="<?php echo $this->url('fiche-metier-type/detruire', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                        title="Détruire la fiche metier"
                        class="ajax-modal" data-event="destruction"
                    >
                        <span class="icon icon-retirer"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('table#fiches').DataTable({
            "paging": false
        });
    });
</script>
