<?php

/**
 * @var FicheMetier[] $fiches
 * @var Domaine[] $domaines
 * @var Domaine $domaineSelect
 */

use Metier\Entity\Db\Domaine;
use FicheMetier\Entity\Db\FicheMetier;
use Application\Provider\Privilege\FicheMetierPrivileges;

$canVoir        = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));
$canHistoriser  = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_HISTORISER));
$canEditer      = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));
$canDetruire    = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_DETRUIRE));

?>


<table id="fiches" class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> Domaine </th>
        <th  style="width:8rem;"> État </th>
        <th  class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($fiches as $fiche): ?>
        <tr <?php if ($fiche->estHistorise()) echo "class='historise'"; ?> >
            <td>
                <span title='<?php echo $fiche->getMetier()->generateTooltip(); ?>'
                      data-toggle='tooltip' data-html='true'
                >
                    <?php echo $fiche->getMetier()->getLibelle(true); ?>
                </span>
                <?php if ($fiche->hasExpertise() === true) : ?>
                    <span class="label" style="background: lightskyblue;">Expertise</span>
                <?php endif; ?>
            </td>
            <td>
                <ul>
                    <?php foreach ($fiche->getMetier()->getDomaines() as $domaine) : ?>
                        <li>
                            <?php echo $domaine; ?>
                            <?php echo $this->typefonction($domaine); ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td class="cell-etat">
                <?php if ($canEditer) : ?>
                <a
                    <?php /** @see FicheMetierController::modifierEtatAction() */?>
                        href="<?php echo $this->url('fiche-metier/modifier-etat', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                        title="Changer l'état de la fiche métier"
                        class="ajax-modal" data-event="changer-etat"
                >
                    <?php endif; ?>
                    <?php echo $this->etatbadge($fiche->getEtat()); ?>
                    <?php if ($canEditer) : ?>
                </a>
            <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canVoir) : ?>
                    <a
                        <?php /** @see FicheMetierController::afficherAction() */?>
                        href="<?php echo $this->url('fiche-metier/afficher', ['fiche-metier' => $fiche->getId()], [], true); ?>">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canVoir) : ?>
                    <br/>
                    <a
                        <?php /** @see FicheMetierController::exporterAction() */?>
                        href="<?php echo $this->url('fiche-metier/exporter', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                        title="Exporter en PDF la fiche métier"
                    >
                        <span class="icon icon-pdf"></span>
                        Exporter
                    </a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <br/>
                    <?php /** @see FicheMetierController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier/modifier', ['fiche-metier' => $fiche->getId()], [], true); ?>">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <br/>
                    <?php /** @see FicheMetierController::dupliquerAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier/dupliquer', ['fiche-metier' => $fiche->getId()], [], true); ?>">
                        <span class="icon icon-cloner"></span>
                        Dupliquer
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if($fiche->estNonHistorise()) :?>
                        <?php /** @see FicheMetierController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/historiser', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                           title="Historiser la fiche metier">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else: ?>
                        <?php /** @see FicheMetierController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/restaurer', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                           title="Restaurer la fiche metier">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <br>
                    <a
                        <?php /** @see FicheMetierController::supprimerAction() */?>
                        href="<?php echo $this->url('fiche-metier/supprimer', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                        title="Détruire la fiche metier"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-retirer"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('table#fiches').DataTable({
            "paging": false
        });
    });
</script>
