<?php

/**
 * @var Activite[] $missionsprincipales
 * @var FicheMetier $fichemetier
 * @var string $mode
 */

use Application\Entity\Db\Activite;
use Application\Entity\Db\FicheMetier;

?>

<div class="card info">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6"> <h2> Missions principales </h2> </div>
            <div class="col-md-6">
                <?php if ($mode === 'edition-fiche-metier') : ?>

                    <?php /** @see FicheMetierController::ajouterActiviteExistanteAction() */ ?>
                    <a class="btn btn-primary ajax-modal" style="margin: 0 0.5rem;"
                       data-event="modification"
                    href="<?php echo $this->url('fiche-metier-type/ajouter-activite-existante', ['id' => $fichemetier->getId()], [], true); ?>">
                    <span class="icon selectionner"></span>
                    Ajouter une activité existante
                    </a>

                    <?php /** @see FicheMetierController::ajouterNouvelleActiviteAction() */ ?>
                    <a class="btn btn-primary ajax-modal" style="margin: 0 0.5rem;"
                       href="<?php echo $this->url('fiche-metier-type/ajouter-nouvelle-activite', ['id' => $fichemetier->getId()], [], true); ?>"
                       data-event="modification"
                    >
                        <span class="icon icon-ajouter"></span>
                        Ajouter une nouvelle activité
                    </a>

                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="card-body" style="color:rgb(80,80,80);">
        <?php foreach ($missionsprincipales as $missionprincipale) : ?>
            <?php echo $this->activite($missionprincipale, $mode, ['fichemetier' => $fichemetier]); ?>
        <?php endforeach; ?>
    </div>
</div>