<?php

use Agent\Entity\Db\Agent;
use Application\Provider\Parametre\AgentParametres;
use UnicaenParametre\Entity\Db\Parametre;

/**
 * @see \Agent\View\Helper\AgentOngletViewHelper
 * @var Agent $agent
 * @var Parametre[] $parametres
 * @var string $current
 */

?>

<!-- titre ------------------------------------------------------------------------------------------------------------>

<h1 class="page-header">
    Affiche de l'Agent·e <br>
    <?php echo $agent->getDenomination(true); ?>
</h1>



<!-- onglet ----------------------------------------------------------------------------------------------------------->

<div class="nav nav-tabs" id="nav-tab" role="tablist" style="margin-bottom: .5rem;">
    <?php if (!isset($parametres[AgentParametres::ONGLET_INFORMATIONS]) || $parametres[AgentParametres::ONGLET_INFORMATIONS]->getValeur() !== "false") : ?>
        <?php /** @see \Agent\Controller\AgentController::informationsAction() */ ?>
        <button class="nav-link" id="informations-tab"
                data-bs-toggle="tab" data-bs-target="#informations"
                type="button" role="tab" aria-controls="informations" aria-selected="true"
                onclick="location.href='<?php echo $this->url('agent/informations', ['agent' => $agent->getId()],[], true); ?>'"
        >
            Informations<br>générales
            <br/>
        </button>
    <?php endif; ?>
    <?php if (!isset($parametres[AgentParametres::ONGLET_FICHES]) || $parametres[AgentParametres::ONGLET_FICHES]->getValeur() !== "false") : ?>
        <?php /** @see \Application\Controller\FichePosteController::afficherAgentAction() */ ?>
        <button class="nav-link" id="ficheposte-tab"
                data-bs-toggle="tab" data-bs-target="#ficheposte"
                type="button" role="tab" aria-controls="ficheposte" aria-selected="true"
                onclick="location.href='<?php echo $this->url('fiche-poste/afficher-agent', ['agent' => $agent->getId()],[], true); ?>'"
        >
            Fiches de poste
            <br/>
        </button>
    <?php endif; ?>
    <?php if (!isset($parametres[AgentParametres::ONGLET_ACQUIS]) || $parametres[AgentParametres::ONGLET_ACQUIS]->getValeur() !== "false") : ?>
        <?php /** @see \Agent\Controller\AgentController::acquisAction() */ ?>
        <button class="nav-link" id="acquis-tab"
                data-bs-toggle="tab" data-bs-target="#acquis"
                type="button" role="tab" aria-controls="acquis" aria-selected="true"
                onclick="location.href='<?php echo $this->url('agent/acquis', ['agent' => $agent->getId()],[], true); ?>'"
        >
            Acquis
            <br/>
        </button>
    <?php endif; ?>
    <?php if (!isset($parametres[AgentParametres::ONGLET_MISSIONS]) || $parametres[AgentParametres::ONGLET_MISSIONS]->getValeur() !== "false") : ?>
        <?php /** @see \Agent\Controller\AgentController::missionsSpecifiquesAction() */ ?>
        <button class="nav-link" id="missions-tab"
                data-bs-toggle="tab" data-bs-target="#missions"
                type="button" role="tab" aria-controls="missions" aria-selected="true"
                onclick="location.href='<?php echo $this->url('agent/missions-specifiques', ['agent' => $agent->getId()],[], true); ?>'"
        >
            Missions spécifiques
            <br/>
        </button>
    <?php endif; ?>
    <?php if (!isset($parametres[AgentParametres::ONGLET_PORTFOLIO]) || $parametres[AgentParametres::ONGLET_PORTFOLIO]->getValeur() !== "false") : ?>
        <?php /** @see \Agent\Controller\AgentController::portfolioAction() */ ?>
        <button class="nav-link" id="portfolio-tab"
                data-bs-toggle="tab" data-bs-target="#portfolio"
                type="button" role="tab" aria-controls="portfolio" aria-selected="true"
                onclick="location.href='<?php echo $this->url('agent/portfolio', ['agent' => $agent->getId()],[], true); ?>'"
        >
            Portfolio
            <br/>
        </button>
    <?php endif; ?>
    <?php if (!isset($parametres[AgentParametres::ONGLET_MOBILITES]) || $parametres[AgentParametres::ONGLET_MOBILITES]->getValeur() !== "false") : ?>
        <?php /** @see \Agent\Controller\AgentMobiliteControllerController::afficherAgentAction() */ ?>
        <button class="nav-link" id="mobilite-tab"
                data-bs-toggle="tab" data-bs-target="#mobilite"
                type="button" role="tab" aria-controls="mobilite" aria-selected="true"
                onclick="location.href='<?php echo $this->url('agent/mobilite/afficher-agent', ['agent' => $agent->getId()],[], true); ?>'"
        >
            Déclaration de<br>mobilités
            <br/>
        </button>
    <?php endif; ?>
</div>

<script>
    $('button[aria-controls="<?php echo $current; ?>"]').addClass('active');
</script>
