<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\AgentForceSansObligation;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Provider\Privilege\AgentforcesansobligationPrivileges;

/**
 * @see \EntretienProfessionnel\Controller\AgentForceSansObligationController::indexAction()
 * @var AgentForceSansObligation[] $agentsForcesSansObligation
 * @var Campagne[] $campagnes
 *
 * @var ?Campagne $campagne
 * @var ?Agent $agent
 * @var ?string $forcage
 */

$this->headTitle("Agent·es forcé·es sans obligation d'entretien professionnel");

/** TODO prevoir de changer cela avec les assertions */
$canAfficher = $this->isAllowed(AgentforcesansobligationPrivileges::getResourceId(AgentforcesansobligationPrivileges::AGENTFORCESANSOBLIGATION_AFFICHER));
$canAjouter = $this->isAllowed(AgentforcesansobligationPrivileges::getResourceId(AgentforcesansobligationPrivileges::AGENTFORCESANSOBLIGATION_AJOUTER));
$canModifier = $this->isAllowed(AgentforcesansobligationPrivileges::getResourceId(AgentforcesansobligationPrivileges::AGENTFORCESANSOBLIGATION_MODIFIER));
$canHistoriser = $this->isAllowed(AgentforcesansobligationPrivileges::getResourceId(AgentforcesansobligationPrivileges::AGENTFORCESANSOBLIGATION_HISTORISER));
$canSupprimer = $this->isAllowed(AgentforcesansobligationPrivileges::getResourceId(AgentforcesansobligationPrivileges::AGENTFORCESANSOBLIGATION_SUPPRIMER));
?>

<h1 class="page-header">
    Agent·es forcé·es sans obligation d'entretien professionnel
</h1>

<?php echo $this->partial('partial/filtre', ['campagnes' => $campagnes, 'campagne' => $campagne, 'agent' => $agent, 'forcage' => $forcage]); ?>

<?php if ($canAjouter) : ?>
    <?php /** @see \EntretienProfessionnel\Controller\AgentForceSansObligationController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('entretien-professionnel/agent-force-sans-obligation/ajouter', [], [], true); ?>"
       class="ajax-modal btn btn-primary" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un forçage
    </a>
<?php endif; ?>

<?php if (empty($agentsForcesSansObligation)) : ?>
    <em> Aucun·e agent·e n'est forcé·e sans obligation </em>
<?php else : ?>
    <table class="table table-condensed datatable">
        <thead>
        <tr>
            <th> Agent·e </th>
            <th> Campagne </th>
            <th> Type </th>
            <th> Est justifiée </th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($agentsForcesSansObligation as $agentForceSansObligation) : ?>
            <?php
                $agent = $agentForceSansObligation->getAgent();
                $campagne = $agentForceSansObligation->getCampagne();
             ?>
        <tr class="<?php if ($agentForceSansObligation->estHistorise()) echo " historise "; ?>">
            <td data-order="<?php echo $agent->getNomUsuel()." ".$agent->getPrenom(); ?>">
                <?php echo $agent->getPrenom(); ?>
                <?php echo $agent->getNomUsuel(); ?>
            </td>
            <td data-order="<?php echo $campagne->getAnnee(); ?>">
                <?php echo $campagne->getAnnee(); ?>
            </td>
            <td>
                <?php echo AgentForceSansObligation::FORCAGE_ARRAY[$agentForceSansObligation->getType()]; ?>
            </td>
            <td>
                <?php if ($agentForceSansObligation->getRaison()): ?>
                    <span class="text-success" data-bs-toggle="tooltip" data-bs-html="true" title="<?php echo $agentForceSansObligation->getRaison(); ?>">
                        <span class="icon icon-checked"></span>
                        Oui
                    </span>
                <?php else : ?>
                    <span class="text-danger">
                        <span class="icon icon-unchecked"></span>
                        Non
                    </span>
                <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \EntretienProfessionnel\Controller\AgentForceSansObligationController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('entretien-professionnel/agent-force-sans-obligation/afficher', ['agent-force-sans-obligation' => $agentForceSansObligation->getId()], [], true); ?>"
                       class="ajax-modal">
                            <span class="icon icon-voir"></span>
                            Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \EntretienProfessionnel\Controller\AgentForceSansObligationController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('entretien-professionnel/agent-force-sans-obligation/modifier', ['agent-force-sans-obligation' => $agentForceSansObligation->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($agentForceSansObligation->estNonHistorise()) : ?>
                        <?php /** @see \EntretienProfessionnel\Controller\AgentForceSansObligationController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('entretien-professionnel/agent-force-sans-obligation/historiser', ['agent-force-sans-obligation' => $agentForceSansObligation->getId()], [], true); ?>"
                           >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \EntretienProfessionnel\Controller\AgentForceSansObligationController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('entretien-professionnel/agent-force-sans-obligation/restaurer', ['agent-force-sans-obligation' => $agentForceSansObligation->getId()], [], true); ?>"
                           >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \EntretienProfessionnel\Controller\AgentForceSansObligationController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('entretien-professionnel/agent-force-sans-obligation/supprimer', ['agent-force-sans-obligation' => $agentForceSansObligation->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>

            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<script>

    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $("table.datatable").DataTable( {
            'paging' : false,
            'info' : false,
        });
    });
</script>
