<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentStatut;
use Formation\Entity\Db\Inscription;
use Formation\Provider\Etat\InscriptionEtats;
use Formation\Provider\Etat\SessionEtats;

/**
 * @see \Formation\Controller\InscriptionController::afficherAgentAction()
 * @var Agent $agent
 * @var Inscription[] $inscriptions
 * @var Agent[] $superieurs
 * @var Agent[] $autorites
 */

$agentAffectations = $agent->getAffectationsActifs();
$agentGrades = $agent->getGradesActifs();
$agentStatuts= $agent->getStatutsActifs();

$statuts = AgentStatut::generateStatutsArray($agentStatuts);
?>

<h2> Information à propos de <?php echo $agent->getDenomination(); ?> </h2>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-4"> Dénomination </dt>
            <dd class="col-md-8"> <?php echo $agent->getDenomination(); ?> </dd>
            <dt class="col-md-4"> Affectation·s </dt>
            <dd class="col-m">
                <ul>
                    <?php foreach ($agentAffectations as $agentAffectation) : ?>
                        <li>
                            <?php
                            $structure = $agentAffectation->getStructure();
                            $niveau2 = $structure?$structure->getNiv2():null;
                            ?>
                            <?php if ($structure) : ?>
                                <?php echo $structure->getLibelleLong(); ?>
                                <?php if ($niveau2 AND $niveau2 !== $structure) : ?>
                                    <br/> Rattaché&middot;e à <?php echo $niveau2->getLibelleLong(); ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($agentAffectation->isPrincipale()) : ?>
                                <br/> <em>Affectation principale</em>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>

    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-4"> Statut·s </dt>
            <dd class="col-md-8">
                <ul>
                    <?php foreach ($statuts as $statut) : ?>
                        <li>
                            <?php echo $statut; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
            <dt class="col-md-4"> Informations supplémentaires </dt>
            <dd class="col-md-8">
                <ul>
                    <?php foreach ($agentGrades as $agentGrade) : ?>
                        <?php $grade = $agentGrade->getGrade(); ?>
                        <?php $corps = $agentGrade->getCorps(); ?>
                        <?php $correspondance = $agentGrade->getCorrespondance(); ?>
                        <li>
                            <?php echo ($grade)?$grade->getLibelleLong():"Grade non renseigné"; ?> <br/>
                            <?php echo ($corps)?$corps->getLibelleLong():"Corps non renseigné"; ?> <br/>
                            <?php echo ($correspondance)?$correspondance->getLibelleLong():"Correspondance non renseignée"; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <dl>
            <dt> Supérieur·e·s hiérarchiques direct·e·s</dt>
            <dd>
                <ul>
                    <?php foreach ($superieurs as $superieur) : ?>
                        <li> <?php echo $superieur->getDenomination(); ?></li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl>
            <dt> Autorité·e·s hiérarchiques</dt>
            <dd>
                <ul>
                    <?php foreach ($autorites as $autorite) : ?>
                        <li> <?php echo $autorite->getDenomination(); ?></li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>
</div>

<h2> Liste des inscriptions à des formations du plan de formation </h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th class="col-md-2">
            Année
        </th>
        <th class="col-md-5">
            Formation
        </th>
        <th class="col-md-5">
            Inscription
        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($inscriptions as $inscription) : ?>
        <?php $session = $inscription->getSession(); ?>
        <tr>
            <td>
                <?php echo $session->getAnnee(); ?>
            </td>
            <td>
                <div style="display: flex;  align-items: center;">
                    <div style="padding-right: 1rem;">
                        <?php echo $this->etatinstance($session->getEtatActif(), ['display-categorie' => false]); ?>
                    </div>
                    <div >
                        <?php echo $session->getFormation()->getLibelle(); ?> <br>
                        <?php echo $session->getPeriode(); ?>
                    </div>
                </div>
            </td>
            <td>
                <div style="display: flex;  align-items: center;">
                    <div style="padding-right: 1rem;">
                        <?php echo $this->etatinstance($inscription->getEtatActif(), ['display-categorie' => false]); ?>
                    </div>
                    <div>
                        <?php echo $this->partial('partial/inscription', ['session' => $session, 'inscription' => $inscription], [], true); ?>
                    </div>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


