<?php

use Formation\Entity\Db\Inscription;
use Formation\Provider\Privilege\FormationagentPrivileges;
use Formation\Provider\Privilege\FormationinstancePrivileges;
use Formation\Provider\Privilege\StagiaireexternePrivileges;

/**
 * @see \Formation\Controller\InscriptionController::indexAction()
 * @var Inscription[] $inscriptions
 **/

$this->headTitle("Inscriptions aux formations");

$canVoirIndividu = $this->isAllowed(FormationagentPrivileges::getResourceId(FormationagentPrivileges::FORMATIONAGENT_INDEX)) || $this->isAllowed(StagiaireexternePrivileges::getResourceId(StagiaireexternePrivileges::STAGIAIREEXTERNE_AFFICHER));
$canVoirSession = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_AFFICHER));
$canModifier = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_GERER_INSCRIPTION));
$canHistoriser = $canModifier;
$canSupprimer = $canModifier;
$canTeleverserAttestation = $canModifier;
$canTelechargerAttestation = $canModifier;
$canSupprimerAttestation = $canModifier;

?>

<h1 class='page-header'>
    Inscriptions aux formations
</h1>

<?php echo $this->partial('partial/filtre.phtml'); ?>

<?php /** @see \Formation\Controller\InscriptionController::ajouterAction() */ ?>
<a href="<?php echo $this->url('formation/inscription/ajouter', [], [], true); ?>"
   class="btn btn-primary ajax-modal" data-event="modification">
    <span class="icon icon-ajouter"></span> Ajouter une inscription
</a>

<table class="table table-condensed datatable">
    <thead>
        <tr>
            <th> Session de formation </th>
            <th> Stagiaire </th>
            <th> Documents </th>
            <th> État </th>
            <th class="action"> Action </th>
        </tr>
    </thead>
    <tbody>
            <?php foreach ($inscriptions as $inscription) : ?>
                <?php if ($canSupprimer OR $inscription->estNonHistorise()) : ?>
                    <tr class=" <?php if ($inscription->estHistorise()) echo " historise "; ?> " >
                    <td>
                        <?php echo $inscription->getSession()->getFormation()->getLibelle(); ?>
                        <br>
                        <?php echo $inscription->getSession()->getPeriode(); ?>
                    </td>
                    <td>
                        <?php echo $inscription->getIndividu()->getDenomination(); ?>
                        <br>
                        <?php if ($inscription->getStagiaire()) : ?>
                            <?php echo $inscription->getStagiaire()->getStructure()??"Aucune structure"; ?> <br>
                            Stagiaire externe
                        <?php endif; ?>
                        <?php if ($inscription->getAgent()) : ?>
                            <?php
                                $affectation = $inscription->getAgent()->getAffectationPrincipale();
                                if ($affectation) echo $affectation->getStructure()->getLibelleLong() . "<br>";
                            ?>
                            Agent
                        <?php endif; ?>
                    </td>
                    <td class="action">
                        <?php if ($canTeleverserAttestation) : ?>
                            <?php /** @see \Formation\Controller\InscriptionController::televerserAttestationAction() */ ?>
                            <a href="<?php echo $this->url('formation/inscription/televerser-attestation', ['inscription' => $inscription->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification"
                            >
                                <span class="icon icon-televerser"></span> Téléverser un document
                            </a>
                        <?php endif; ?>
                        <ul>
                            <?php foreach ($inscription->getFichiers() as $attestation) : ?>
                                <li>
                                    <div class="col-md-12">
                                        <div class="col-md-6">
                                            <strong><?php echo $attestation->getNature()->getLibelle(); ?></strong><br>
                                            <?php echo $attestation->getNomOriginal(); ?>
                                        </div>
                                        <div class="col-md-6">
                                            <?php if ($canTelechargerAttestation) : ?>
                                                <?php /** @see \Formation\Controller\InscriptionController::telechargerAttestationAction() */ ?>
                                                <a href="<?php echo $this->url('formation/inscription/telecharger-attestation', ['inscription' => $inscription->getId(), 'attestation' => $attestation->getId()], [], true); ?>">
                                                    <span class="icon icon-televerser"></span> Télécharger
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($canSupprimerAttestation) : ?>
                                                <br>
                                                <?php /** @see \Formation\Controller\InscriptionController::supprimerAttestationAction() */ ?>
                                                <a href="<?php echo $this->url('formation/inscription/supprimer-attestation', ['inscription' => $inscription->getId(), 'attestation' => $attestation->getId()], [], true); ?>">
                                                    <span class="text-danger">
                                                        <span class="icon icon-unchecked"></span> Supprimer
                                                    </span>
                                                </a>
                                            <?php endif; ?>
                                        </div>

                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </td>
                    <td>
                        <?php echo $this->etatinstance($inscription->getEtatActif()); ?>
                    </td>
                    <td class="action">
                        <?php if ($canVoirIndividu) : ?>
                            <?php /** @see \Formation\Controller\AgentController::afficherAction */ ?>
                            <?php /** @see \Formation\Controller\StagiaireExterneController::afficherAction */ ?>
                            <?php $url = ($inscription->isInterne())?
                                $this->url('formation/agent', ['agent' => $inscription->getAgent()->getId()], [], true)
                                :$this->url('stagiaire-externe/afficher', ['stagiaire-externe' => $inscription->getStagiaire()->getId()], [], true); ?>
                            <a href="<?php echo $url; ?>">
                                <span class="icon icon-user"></span> Afficher
                            </a>
                        <?php endif; ?>
                        <?php if ($canVoirSession) : ?>
                            <br>
                            <?php /** @see \Formation\Controller\FormationInstanceController::afficherAction */ ?>
                            <a href="<?php echo $this->url('formation-instance/afficher', ['formation-instance' => $inscription->getSession()->getId()], [], true); ?>">
                                <span class="icon icon-voir"></span> Acceder
                            </a>
                        <?php endif; ?>
                        <?php if ($canVoirSession) : ?>
                            <br>
                            <?php /** @see \Formation\Controller\InscriptionController::modifierAction() */ ?>
                            <a href="<?php echo $this->url('formation/inscription/modifier', ['inscription' => $inscription->getId()], [], true); ?>"
                                class="ajax-modal" data-event="modification">
                                <span class="icon icon-editer"></span> Modifier
                            </a>
                        <?php endif; ?>
                        <?php if ($canHistoriser) : ?>
                            <br>
                            <?php if ($inscription->estNonHistorise()) : ?>
                                <?php /** @see \Formation\Controller\InscriptionController::historiserAction() */ ?>
                                <a href="<?php echo $this->url('formation/inscription/historiser', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url()]], true); ?>">
                                    <span class="icon icon-historiser"></span> Historiser
                                </a>
                            <?php else : ?>
                                <?php /** @see \Formation\Controller\InscriptionController::restaurerAction() */ ?>
                                <a href="<?php echo $this->url('formation/inscription/restaurer', ['inscription' => $inscription->getId()], ['query' => ['retour' => $this->url()]], true); ?>">
                                    <span class="icon icon-restaurer"></span> Restaurer
                                </a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canSupprimer) : ?>
                            <br>
                            <?php /** @see Formation\Controller\InscriptionController::supprimerAction() */ ?>
                            <a href="<?php echo $this->url('formation/inscription/supprimer', ['inscription' => $inscription->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification">
                                <span class="text-danger">
                                    <span class="icon icon-unchecked"></span> Supprimer
                                </span>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endif; ?>
            <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
