<?php

/**
 * @see \Formation\Controller\InscriptionController::inscriptionAction()
 * @var string $title
 * @var bool $ok
 * @var string $message
 */

?>

<?php if ($ok === false) : ?>
    <div class="alert alert-danger">
        <p>
        <span class="text-danger">
            <strong>
            <span class="icon icon-attention"></span>
                L'inscription a échoué
            </strong>
        </span>
        </p>


            <?php echo $message; ?>
        </span>
    </div>
<?php endif; ?>
