<?php

/**
 * @see \Application\Controller\EntretienProfessionnelController::afficherAction()
 * @var EntretienProfessionnel $entretien
 * @var Agent $agent
 * @var FichePoste[] $fichespostes
 * @var FicheMetier[] $fichesmetiers
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\EntretienProfessionnel;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FichePoste;

$this->headTitle('Édition de l\'entretien professionnel');
?>

<h1 class="page-header">
    Affichage de l'entretien professionnel
</h1>

<?php
echo $this->partial('partial/header', ['entretien' => $entretien, 'agent' => $agent, 'fichespostes' => $fichespostes, 'fichesmetiers' => $fichesmetiers], [], true);
?>

    <div class="affichage-autoform">
        Chargment des informations provenant du formulaire ...
    </div>

<script>
    //$( document ).ready(function() {
    var url = <?php
        /**
         * @var Autoform\Entity\Db\Formulaire $formulaire
         * @var string $retour
         */
        $formulaire = $entretien->getFormulaireInstance()->getFormulaire();
        $retour = $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], ['force_canonical' => false], true);
        $url = $this->url('autoform/formulaire/afficher-resultat', ['formulaire' => $formulaire->getId(), 'instance' => $entretien->getFormulaireInstance()->getId()], ['query' => ['retour' => $retour], 'force_canonical' => false], true);
        echo "'".$url."'";
        ?>;
    console.log(url);

    $.ajax({
        type: "GET",
        url: url,
        success:
            function (retour) {
                $("div.affichage-autoform").html(retour);
            }
    });
    //});
</script>


