<?php

/**
 * @var \Application\Entity\Db\EntretienProfessionnel $entretien
 */

$this->headTitle('Édition de l\'entretien professionnel');
?>

            <div class="panel panel-info">
                <div class="panel-heading">
                    Informations sur l'entretien
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt> Responsable</dt>
                        <dd> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </dd>
                        <dt> Date </dt>
                        <dd> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </dd>
                    </dl>

                </div>
            </div>

    <div class="affichage-autoform">
        Chargment des informations provenant du formulaire ...
    </div>

<script>
    //$( document ).ready(function() {
    var url = <?php
        /**
         * @var Autoform\Entity\Db\Formulaire $formulaire
         * @var string $retour
         */
        $formulaire = $entretien->getFormulaireInstance()->getFormulaire();
        $retour = $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], ['force_canonical' => true], true);
        $url = $this->url('autoform/formulaire/afficher-resultat', ['formulaire' => $formulaire->getId(), 'instance' => $entretien->getFormulaireInstance()->getId()], ['query' => ['retour' => $retour], 'force_canonical' => true], true);
        echo "'".$url."'";
        ?>;
    console.log(url);

    $.ajax({
        type: "GET",
        url: url,
        success:
            function (retour) {
                $("div.affichage-autoform").html(retour);
            }
    });
    //});
</script>


