<?php

/**
 * @var Application\Entity\Db\EntretienProfessionnel[] $entretiens
 */

$this->headTitle('Index des entretiens professionnel');

?>

<h1 class="page-header">
    Index des entretiens professionnels
</h1>

<div class="main">

    <a href="<?php echo $this->url('entretien-professionnel/creer', [], [], true); ?>" class="btn btn-primary action">
        <span class="icon ajouter action"></span>
        Créer un entretien professionnel
    </a>

    <h2> Liste des entretiens enregistrés </h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th> Année </th>
                <th> Agent </th>
                <th> Responsable </th>
                <th> Date </th>
                <th> Modifée </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($entretiens as $entretien) : ?>
            <tr>
                <td> <?php echo $entretien->getAnnee(); ?> </td>
                <td> <?php echo $entretien->getPersonnel()->getDisplayName(); ?> </td>
                <td> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </td>
                <td> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </td>
                <td> <?php echo $entretien->getHistoModification()->format('d/m/Y'); ?> </td>
                <td>
                    <a href="<?php echo $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], [], true); ?>">
                        <span class="icon editer"></span></a>
                    <?php if ($entretien->estNonHistorise()) : ?>
                    <a href="<?php echo $this->url('entretien-professionnel/historiser', ['entretien' => $entretien->getId()], [], true); ?>">
                        <span class="icon historiser"></span></a>
                    <?php else : ?>
                        <a href="<?php echo $this->url('entretien-professionnel/restaurer', ['entretien' => $entretien->getId()], [], true); ?>">
                            <span class="icon restaurer"></span></a>
                    <?php endif; ?>
                    <a href="<?php echo $this->url('entretien-professionnel/detruire', ['entretien' => $entretien->getId()], [], true); ?>">
                        <span class="icon detruire"></span></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
