<?php

/**
 * @var \Application\Entity\Db\EntretienProfessionnel $entretien
 */



$this->headTitle('Édition de l\'entretien professionnel');
?>

<h1 class="page-header">
    Entretien professionnel <?php echo $entretien->getAnnee(); ?> <br/>
    <?php echo $entretien->getAgent()->getPrenom(); ?>
    <?php echo $entretien->getAgent()->getNomUsuel(); ?>
</h1>

<div class="main">

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Informations sur l'entretien
                </div>
                <div class="panel-body">
                    <dl>
                        <dt> Année</dt>
                        <dd> <?php echo $entretien->getAnnee(); ?> </dd>
                        <dt> Agent</dt>
                        <dd>
                            <?php echo $entretien->getAgent()->getPrenom(); ?>
                            <?php echo $entretien->getAgent()->getNomUsuel(); ?>
                        </dd>
                        <dt> Responsable</dt>
                        <dd> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </dd>
                    </dl>

                </div>
            </div>
        </div>

        <div class="col-md-6">
            <a href="<?php echo $this->url('entretien-professionnel', [], [], true); ?>" class="btn btn-primary">
                <span class="icon retour"></span>
                Retourner à l'index
            </a>
        </div>
    </div>

    <h2> Formulaire d'entretien  </h2>

    <div class="affichage-autoform">
        Chargment des informations provenant du formulaire ...
    </div>

    <div class="row">
        <div class="col-md-6">
            <h2> Validation de l'agent </h2>

            <?php if ($entretien->getValidationAgent() === null): ?>
                <a
                    <?php /** @see \Application\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                        href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => 'Agent'], [], true); ?>"
                        class="btn btn-success action ajax-modal"
                        data-event="modification"
                >
                    <span class="icon validation-do"></span>
                    Validation de l'agent
                </a>
            <?php else : ?>
                <div class="alert alert-info">
                    Validation <strong>Agent</strong> effectuée.
                    <dl>
                        <dt> Validateur </dt>
                        <dd> <?php echo $entretien->getValidationAgent()->getHistoModificateur()->getDisplayName(); ?> </dd>
                        <dt> Date de la validation </dt>
                        <dd> <?php echo $entretien->getValidationAgent()->getHistoModification()->format('d/m/y'); ?> </dd>
                    </dl>
                </div>

                <a
                    <?php /** @see \Application\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                        href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $entretien->getValidationAgent()->getId()], [], true); ?>"
                        class="btn btn-danger action"
                >
                    <span class="icon validation-undo"></span>
                    Révoquer la validation
                </a>
            <?php endif; ?>
        </div>

        <div class="col-md-6">
            <h2> Validation du responsable </h2>

            <?php if ($entretien->getValidationResponsable() === null): ?>
                <a
                    <?php /** @see \Application\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                        href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => 'Responsable'], [], true); ?>"
                        class="btn btn-success action ajax-modal"
                        data-event="modification"
                >
                    <span class="icon validation-do"></span>
                    Validation du responsable
                </a>
            <?php else : ?>
                <div class="alert alert-info">
                    Validation <strong>Responsable</strong> effectuée.
                    <dl>
                        <dt> Validateur </dt>
                        <dd> <?php echo $entretien->getValidationResponsable()->getHistoModificateur()->getDisplayName(); ?> </dd>
                        <dt> Date de la validation </dt>
                        <dd> <?php echo $entretien->getValidationResponsable()->getHistoModification()->format('d/m/y'); ?> </dd>
                    </dl>
                </div>

                <a
                    <?php /** @see \Application\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                        href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $entretien->getValidationResponsable()->getId()], [], true); ?>"
                        class="btn btn-danger action"
                >
                    <span class="icon validation-undo"></span>
                    Révoquer la validation
                </a>
            <?php endif; ?>
        </div>
    </div>


</div>

<script>
    //$( document ).ready(function() {
    var url = <?php
        /**
         * @var Autoform\Entity\Db\Formulaire $formulaire
         * @var string $retour
         */
        $formulaire = $entretien->getFormulaireInstance()->getFormulaire();
        $retour = $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], ['force_canonical' => false], true);
        $url = $this->url('autoform/formulaire/afficher-formulaire', ['formulaire' => $formulaire->getId(), 'instance' => $entretien->getFormulaireInstance()->getId()], ['query' => ['retour' => $retour], 'force_canonical' => false], true);
        echo "'".$url."'";
        ?>;
    console.log(url);

    $.ajax({
        type: "GET",
        url: url,
        success:
            function (retour) {
                $("div.affichage-autoform").html(retour);
            }
    });

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


