<?php

/**
 * @see \Application\Controller\EntretienProfessionnelController::renseignerAction()
 * @var EntretienProfessionnel $entretien
 * @var Agent $agent
 * @var FichePoste[] $fichespostes
 * @var FicheMetier[] $fichesmetiers
 * @var ParcoursDeFormation $parcours
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\EntretienProfessionnel;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\ParcoursDeFormation;

$this->headTitle('Modification de l\'entretien professionnel');
?>

<h1 class="page-header">
    Entretien professionnel <?php echo $entretien->getAnnee(); ?> <br/>
    <?php echo $entretien->getAgent()->getPrenom(); ?>
    <?php echo $entretien->getAgent()->getNomUsuel(); ?>
</h1>


<h1 class="page-header">
    Affichage de l'entretien professionnel
</h1>

<?php
echo $this->partial('partial/header', ['entretien' => $entretien, 'agent' => $agent, 'fichespostes' => $fichespostes, 'fichesmetiers' => $fichesmetiers], [], true);
?>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">

        <li role="formulaire">
            <a href="#formulaire" aria-controls="formulaire" role="tab" data-toggle="tabz">
                Formulaire
            </a>
        </li>

        <li role="parcours">
            <a href="#parcours" aria-controls="parcours" role="tab" data-toggle="tabz">
                Parcours &nbsp;
            </a>
        </li>

        <li role="avis">
            <a href="#avis" aria-controls="avis" role="tab" data-toggle="tabz" >
                Avis &nbsp;
            </a>
        </li>

        <li role="validation">
            <a href="#validation" aria-controls="validation" role="tab" data-toggle="tabz" >
                Validations
            </a>
        </li>
    </ul>

    <div class="main-with-tab">

        <div class="tab-content">

            <div id="formulaire" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/formulaire', ['entretien' => $entretien]); ?>
            </div>

            <div id="parcours" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/parcours.phtml', ['agent' => $entretien->getAgent(), 'parcours' => $parcours]); ?>
            </div>

            <div id="avis" class="tab-pane " role="tabpanel">
<!--                --><?php //echo $this->partial('partial/listing-metier.phtml', ['metiers' => $metiers, 'droits' => $droits]); ?>
            </div>

            <div id="validation" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/validation', ['entretien' => $entretien]); ?>
            </div>
        </div>
    </div>

</div>


<script>
    $(document).ready(function() {
        $('.datatable').DataTable( {
            // sorting: false,
            // paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "formulaire";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


