<?php

/**
 * @see \Carriere\Controller\GradeController::afficherAgentsAction();
 * @var Grade $grade
 */

use Application\Entity\Db\AgentGrade;
use Carriere\Entity\Db\Grade;

$now = new DateTime();

/** @var  AgentGrade[] $agents */
$agents = $grade->getAgentGrades();
$agents = array_filter($agents, function (AgentGrade $a) { return !$a->isDeleted();});
usort($agents, function(AgentGrade $a, AgentGrade $b) {return $a->getAgent()->getDenomination() > $b->getAgent()->getDenomination();});
?>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-5"> Grade </dt>
            <dd class="col-md-7">[#<?php echo $grade->getId(); ?>] <?php echo $grade->getLibelleLong(); ?></dd>
            <dt class="col-md-5"> #AgentGrade </dt>
            <dd class="col-md-7"> <?php echo count($agents); ?></dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-5"> Date ouverture </dt>
            <dd class="col-md-7"> <?php echo ($grade->getDateDebut())?$grade->getDateDebut()->format('d/m/Y'):"---"; ?>  </dd>
            <dt class="col-md-5"> Date fermeture </dt>
            <dd class="col-md-7"> <?php echo ($grade->getDateFin())?$grade->getDateFin()->format('d/m/Y'):"---"; ?></dd>
        </dl>
    </div>
</div>

<table class="table table-condensed">
    <thead>
        <tr>
            <th> Id </th>
            <th> Agent </th>
            <th> Début </th>
            <th> Fin </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($agents as $agent) : ?>
        <tr <?php if ($agent->estFini($now)) echo 'class="historise"'; ?> >
            <td> <?php echo $agent->getId(); ?> </td>
            <td> <?php echo $agent->getAgent()->getDenomination(); ?> </td>
            <td> <?php echo ($agent->getDateDebut()) ? $agent->getDateDebut()->format('d/m/Y') : "---"; ?> </td>
            <td> <?php echo ($agent->getDateFin()) ? $agent->getDateFin()->format('d/m/Y') : "---"; ?> </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>



