<?php

/**
 * @see \Carriere\Controller\GradeController::afficherAgentsAction();
 * @var Grade $grade
 * @var AgentGrade[] $agentGrades
 * @var Agent[] $agents
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentGrade;
use Application\Provider\Privilege\AgentPrivileges;
use Carriere\Entity\Db\Grade;

$now = new DateTime();

/** @var  AgentGrade[] $agents */
$agents = $grade->getAgentGrades();
$agents = array_filter($agents, function (AgentGrade $a) { return $a->estCommence() && !$a->isDeleted();});
usort($agents, function(AgentGrade $a, AgentGrade $b) {return $a->getAgent()->getDenomination() <=> $b->getAgent()->getDenomination();});

$actifs = 0; $inactifs = 0;
foreach ($agents as $agent) { if ($agent->estFini()) $inactifs++; else $actifs++;}

?>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-5"> Grade </dt>
            <dd class="col-md-7">[#<?php echo $grade->getId(); ?>] <?php echo $grade->getLibelleLong(); ?></dd>
<!--            <dt class="col-md-5"> #Agent </dt>-->
<!--            <dd class="col-md-7"> --><?php //echo count($agents); ?><!--</dd>-->
            <dt class="col-md-5"> #AgentGrade </dt>
            <dd class="col-md-7"> <?php echo $actifs; ?> actifs (<?php echo $inactifs ?> inactifs)</dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-5"> Date ouverture </dt>
            <dd class="col-md-7"> <?php echo ($grade->getDateDebut())?$grade->getDateDebut()->format('d/m/Y'):"---"; ?>  </dd>
            <dt class="col-md-5"> Date fermeture </dt>
            <dd class="col-md-7"> <?php echo ($grade->getDateFin())?$grade->getDateFin()->format('d/m/Y'):"---"; ?></dd>
        </dl>
    </div>
</div>

<label for="actif_only">Conserver les actifs seulement</label>
<input type="checkbox" name="actif_only" id="actif_only" checked>

<table class="table table-condensed">
    <thead>
        <tr>
            <th> Id </th>
            <th> Agent </th>
            <th> Début </th>
            <th> Fin </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($agents as $agent) : ?>
        <tr <?php if ($agent->estFini($now)) echo 'class="historise"'; ?> >
            <td> <?php echo $agent->getId(); ?> </td>
            <td>
                <?php if ($this->isAllowed($agent->getAgent(), AgentPrivileges::AGENT_AFFICHER)) : ?>
                    <a class="linkexterne" id="<?php echo $agent->getAgent()->getId(); ?>" href="">
                        <?php echo $agent->getAgent()->getDenomination(); ?>
                    </a>
                <?php else : ?>
                    <?php echo $agent->getAgent()->getDenomination(); ?>
                <?php endif; ?>
            </td>
            <td> <?php echo ($agent->getDateDebut()) ? $agent->getDateDebut()->format('d/m/Y') : "---"; ?> </td>
            <td> <?php echo ($agent->getDateFin()) ? $agent->getDateFin()->format('d/m/Y') : "---"; ?> </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    $('tr.historise').hide();
    $('#actif_only').on('change', function() {
        let val = $('#actif_only').is(':checked');
        if (val === true) $('tr.historise').hide(); else $('tr.historise').show();
    });

    $('a.linkexterne').on('click',function(e) {
        e.preventDefault();
        $('.modal').modal("hide");
        window.location = 'agent/afficher/' + $(this).attr('id');
    });
</script>


