<?php

/**
 * @see \Carriere\Controller\GradeController::indexAction()
 * @var Grade[] $grades
 */

use Carriere\Entity\Db\Grade;
use Carriere\Provider\Privilege\CorpsPrivileges;
use Carriere\Provider\Privilege\GradePrivileges;

$canLister = $this->isAllowed(GradePrivileges::getResourceId(GradePrivileges::GRADE_LISTER_AGENTS));

$canAction = ($canLister);

$this->headTitle("Liste des grades");
?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Liste des grades
            <span class="badge">
                <?php echo count($grades); ?>
            </span>
        </h1>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
            <span class="icon icon-synchroniser"></span>
            Données synchronisées
        </div>
    </div>
</div>

<table class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th > Libellé </th>
        <th> #Agent/Grade </th>
        <?php if ($canAction) : ?>
            <th> Action </th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach($grades as $grade): ?>
        <tr>
            <td>
                <span
                    title="<?php echo $grade->generateTooltip(); ?>"
                    data-bs-toggle="tooltip" data-bs-html="true"
                >
                <?php echo $grade->getLibelleLong(); ?>
                </span>
            </td>
            <td> <?php echo count($grade->getAgentGrades()); ?> </td>
            <?php if ($canAction) : ?>
            <td class="action">
                    <a
                        <?php /** @see \Carriere\Controller\GradeController::afficherAgentsAction() */ ?>
                        href="<?php echo $this->url('grade/afficher-agents', ['grade' => $grade->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                            <span class="icon users"></span>
                        Lister les agents
                    </a>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('.datatable').DataTable({
            paging: false,
        });
    });
</script>