<?php

use Agent\Entity\Db\Agent;
use Carriere\Entity\Db\Grade;
use Carriere\Provider\Privilege\GradePrivileges;

/**
 * @see \Carriere\Controller\GradeController::indexAction()
 * @var Grade[] $grades ,
 * @var Agent[] $agents
 * @var array $dictionnaire
 *
 * @var bool $avecAgent ,
 */


$canLister = $this->isAllowed(GradePrivileges::getResourceId(GradePrivileges::GRADE_LISTER_AGENTS));


$this->headTitle("Liste des grades");
?>

<h1 class="page-header">
    Liste des grades
    <span class="badge">
        <?php if ($avecAgent) : ?>
            <?php echo count($dictionnaire); ?>
        <?php else : ?>
            <?php echo count($grades); ?>
        <?php endif; ?>
    </span>
</h1>

<div class="col-md-6 alert alert-info" style="margin-top: 1rem;">
    <span class="icon icon-refresh"></span>
    Données synchronisées
    <?php if ($avecAgent) : ?>
        <br>
        <span class="icon icon-information"></span>
        Seuls les grades avec au moins un agent·e sont présentés
    <?php endif; ?>
</div>

<table class="datatable table table-condensed table-hover" id="grades">
    <thead>
    <tr>
        <th class="col-md-9"> Libellé</th>
        <th class="col-md-1"> #Agent/Grade</th>
        <th class="col-md-2"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($grades as $grade) : ?>
        <?php if (!$avecAgent or (isset($dictionnaire[$grade->getId()]) and $dictionnaire[$grade->getId()] !== 0)) : ?>
            <tr>
                <td data-column-id="Libellé">
                    <span title="<?php echo $grade->generateTooltip(); ?>" data-bs-toggle="tooltip" data-bs-html="true">
                        <?php echo $grade->getLibelleLong(); ?>
                    </span>
                </td>
                <td data-column-id="#Agent/Grade">
                    <?php echo $dictionnaire[$grade->getId()]??0; ?>
                </td>
                <td data-column-id="Action">
                    <a
                            <?php /** @see \Carriere\Controller\GradeController::afficherAgentsAction() */ ?>
                            href="<?php echo $this->url('grade/afficher-agents', ['grade' => $grade->getId()], [], true); ?>"
                            class="ajax-modal action secondary" data-event="modification"
                    >
                        <span class="icon icon-users"></span>
                        Lister les agents
                    </a>
                </td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('table#grades').DataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [2], orderable: false}
            ]
        });
    });
</script>