<?php

/**
 * @see \Carriere\Controller\GradeController::indexAction()
 * @var Grade[] $grades
 * @var bool $avecAgent
 */

use Carriere\Entity\Db\Grade;
use Carriere\Provider\Privilege\CorpsPrivileges;
use Carriere\Provider\Privilege\GradePrivileges;

$canLister = $this->isAllowed(GradePrivileges::getResourceId(GradePrivileges::GRADE_LISTER_AGENTS));

$canAction = ($canLister);

$this->headTitle("Liste des grades");
?>

<h1 class="page-header">
    Liste des grades
    <span class="badge">
        <?php echo count($grades); ?>
    </span>
</h1>

<div class="col-md-6 alert alert-info" style="margin-top: 1rem;">
    <span class="icon icon-refresh"></span>
    Données synchronisées
    <?php if ($avecAgent) : ?>
        <br>
        <span class="icon icon-information"></span>
        Seuls les grades avec au moins un agent·e sont présentés
    <?php endif; ?>
</div>

<table class="datatable table table-condensed table-hover" id="grades">
    <thead>
    <tr>
        <th > Libellé </th>
        <th> #Agent/Grade </th>
        <?php if ($canAction) : ?>
            <th> Action </th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach($grades as $grade): ?>
        <tr>
            <td>
                <span
                    title="<?php echo $grade->generateTooltip(); ?>"
                    data-bs-toggle="tooltip" data-bs-html="true"
                >
                <?php echo $grade->getLibelleLong(); ?>
                </span>
            </td>
            <td> <?php echo count($grade->getAgentGrades()); ?> </td>
            <?php if ($canAction) : ?>
            <td class="action">
                    <a
                        <?php /** @see \Carriere\Controller\GradeController::afficherAgentsAction() */ ?>
                        href="<?php echo $this->url('grade/afficher-agents', ['grade' => $grade->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                            <span class="icon icon-users"></span>
                        Lister les agents
                    </a>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('table#grades').DataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [2], orderable: false }
            ]
        });
    });
</script>