<?php

/**
 * @var User $user
 * @var Structure[] $structures
 * @var Structure $structure
 * @var Agent[] $agentsSansFiche
 * @var AgentMissionSpecifique[] $missionsSpecifiques
 * @var FichePoste[] $fichesPostes
 */

use Application\Controller\MesStructuresController;
use Application\Controller\StructureController;
use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentMissionSpecifique;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\FichePostePrivileges;
use Application\Provider\Privilege\StructurePrivileges;
use Utilisateur\Entity\Db\User;

if ($structure !== null) {
    $this->headTitle('Ma structure  : '.$structure->getLibelleCourt());
} else {
$this->headTitle('Ma structure');
}

/** PRIVILEGE */
$canAfficherAgent                   = true;
$canEditerDescription               = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::EDITER_DESCRIPTION));
$canVoirFichePoste                  = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::AFFICHER));
$canExporterFichePoste              = $canVoirFichePoste;
$canEditerFichePoste                = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::EDITER));
$canDetruireFichePoste              = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::DETRUIRE));
//TODO creer les privileges
$canEditerMissionSpecifique         = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::EDITER));
$canDetruireMissionSpecifique       = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::DETRUIRE));


?>

<?php /** TITRE *******************************************************************************************************/ ?>
<h1 class="page-header">
    Ma structure <br>
    <?php if ($structure !== null) : ?>
        <strong> <?php echo $structure->getLibelleCourt(); ?> </strong>
    <?php else : ?>
        <i> Aucune </i>
    <?php endif; ?>
</h1>

<div class="main">

    <?php /** OUTIL DE SELECTION DE STRUCTURE *************************************************************************/ ?>
    <?php if (count($structures) > 1) : ?>
    <form>
        <label for="structure">
            Sélectionner une structure :
        </label>
        <select id="structure">
                <option value="0"> Aucune structure</option>
            <?php foreach ($structures as $structureOption) : ?>
                <option value="<?php echo $structureOption->getId(); ?>"  <?php echo ((($structure)?$structure->getId():0) === $structureOption->getId())?"selected":""?>>
                    <?php echo $structureOption->getLibelleCourt(); ?>
                </option>
            <?php endforeach; ?>
        </select>
    </form>
    <?php endif; ?>

    <?php if ($structure === null) : ?>
        Aucune structure de remontée.
    <?php else : ?>

        <div class="row">

        <?php /** DESCRIPTION *****************************************************************************************/ ?>
        <div class="col-md-8" >
            <div class="row" >

                <div class="col-md-6">
                    <h2>Description</h2>
                </div>
                <div class="pull-right">
                    <br/>

                    <?php if ($canEditerDescription) :?>
                        <?php /** @see StructureController::editerDescriptionAction() */ ?>
                        <a href="<?php echo $this->url('structure/editer-description', ['structure' => $structure->getId()], [], true); ?>"
                           class="btn btn-primary ajax-modal action"
                           data-event="modification"
                        >
                            <span class="icon editer"></span>
                            Modifier la description
                        </a>
                    <?php endif; ?>
                </div>
            </div>

            <?php if ($structure->getDescription() !== null) : ?>
                <?php echo $structure->getDescription(); ?>
            <?php else : ?>
                <div class="alert alert-warning">
                    <span class="icon attention"></span>
                    Aucune description pour la structure <strong><?php echo $structure->getLibelleCourt(); ?></strong>.
                </div>
            <?php endif; ?>
        </div>

        <?php /** GESTIONNAIRES ***************************************************************************************/ ?>
        <div class="col-md-4" >
            <h2>
                Gestionnaires
                <span class="badge"><?php echo count($structure->getGestionnaires()); ?></span>
            </h2>

            <ul>
                <?php foreach ($structure->getGestionnaires() as $gestionnaire) : ?>
                    <li> <?php echo $gestionnaire->getDisplayName(); ?> </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

        <?php /** FICHES DE POSTE *****************************************************************************************/ ?>

        <div >

    <div class="row" >
        <div class="col-md-6" >
        <h2>
            Fiche de postes
            <span class="badge"> <?php echo count($fichesPostes); ?> </span>
        </h2>
        </div>
        <div class="pull-right" >
            <br/>
            <a href="<?php echo $this->url('mes-structures/ajouter-fiche-poste', ['structure' => $structure->getId()], [], true); ?>"
               class="btn btn-primary action"
            >
                <span class="icon ajouter"></span>
                Ajouter une fiche de poste
            </a>
        </div>
    </div>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th class="agent-cell"> Agent </th>
                <th class="libelle-cell"> Poste </th>
                <th> Intitulé </th>
                <th class="action-cell"> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($fichesPostes as $fiche): ?>
                <tr>
                    <td> <?php echo ($fiche->getAgent())?$fiche->getAgent()->getDenomination():"<span class='icon attention' style='color:darkred;'></span> Aucun agent"; ?> </td>
                    <td> <?php echo ($fiche->getPoste())?$fiche->getPoste()->getNumeroPoste():"<span class='icon attention' style='color:darkred;'></span> Aucun poste"; ?> </td>
                    <td>
                        <?php echo ($fiche->getFicheTypeExternePrincipale())?$fiche->getFicheTypeExternePrincipale()->getFicheType()->getMetier()->getLibelle():"<span class='icon attention' style='color:darkred;'></span> Aucun fiche principale"; ?>
                        <?php if($fiche->getLibelle() !== null) : ?>
                            (<?php echo $fiche->getLibelle(); ?>)
                        <?php endif; ?>
                    </td>
                    <td class="action-cell">
                        <?php if ($canVoirFichePoste) : ?>
                            <a href="<?php echo $this->url('fiche-poste/afficher', ['fiche-poste' => $fiche->getId()], ["query" => ["structure" => $structure->getId()]], true); ?>"
                               class="ajax-modal">
                            <span class="icon voir" title="Voir la fiche"></span></a>
                        <?php else : ?>
                            <span class="icon voir" style="color:lightgray;"></span>
                        <?php endif; ?>
                        <?php if ($canExporterFichePoste) : ?>
                            <a href="<?php echo $this->url('fiche-poste/export', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                            >
                                <span class="icon pdf" title="Exporter la fiche"></span></a>
                        <?php else : ?>
                            <span class="icon pdf" style="color:lightgray;"></span>
                        <?php endif; ?>
                        <?php if ($canEditerFichePoste) : ?>
                            <a href="<?php echo $this->url('fiche-poste/editer', ['fiche-poste' => $fiche->getId()], ["query" => ["structure" => $structure->getId()]], true); ?>"
                               class="">
                                <span class="icon editer" title="Éditer la fiche"></span></a>
                        <?php else : ?>
                            <span class="icon editer" style="color:lightgray;"></span>
                        <?php endif; ?>
                        <?php if ($canDetruireFichePoste) : ?>
                            <a href="<?php echo $this->url('fiche-poste/detruire', ['fiche-poste' => $fiche->getId()], ["query" => ["structure" => $structure->getId()]], true); ?>"
                               class="ajax-modal"
                               data-event="modification">
                                <span class="icon detruire" title="Effacer définitivement la fiche"></span></a>
                        <?php else : ?>
                            <span class="icon detruire" style="color:lightgray;"></span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>

    </table>
    </div>

        <?php /** MISSIONS SPECIFIQUE *************************************************************************************/ ?>

        <div>
        <div class="row" >
            <div class="col-md-6" >
                <h2>
                    Missions spécifiques
                    <span class="badge"> <?php echo count($missionsSpecifiques); ?> </span>
                </h2>
            </div>
            <div class="pull-right" >
                <br/>
                <a href="<?php echo $this->url('agent-mission-specifique/ajouter', [], ["query" => ["structure"=>$structure->getId()]], true); ?>"
                   class="btn btn-primary action ajax-modal"
                   data-event="modification"
                >
                    <span class="icon ajouter"></span>
                    Ajouter une mission
                </a>
            </div>
        </div>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th class="agent-cell"> Agent </th>
            <th class="libelle-cell"> Missions </th>
            <th> Période</th>
            <th class="action-cell"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($missionsSpecifiques as $missionSpecifique) : ?>
            <tr>
                <td> <?php echo $missionSpecifique->getAgent()->getDenomination(); ?> </td>
                <td> <?php echo $missionSpecifique->getMission()->getLibelle(); ?> </td>
                <td>
                    <?php
                        $debut = ($missionSpecifique->getDateDebut())?$missionSpecifique->getDateDebut()->format('d/m/Y'):'---';
                        $fin   = ($missionSpecifique->getDateFin())?$missionSpecifique->getDateFin()->format('d/m/Y'):'---';
                    ?>
                    <?php echo $debut; ?> &rarr; <?php echo $fin; ?>
                </td>
                <td class="action-cell">
                    <?php if ($canEditerMissionSpecifique) : ?>
                        <a href="<?php echo $this->url('agent-mission-specifique/editer', ['affectation' => $missionSpecifique->getId()], ["query" => ["structure"=>$structure->getId()]], true); ?>"
                           class="ajax-modal"
                           data-event="modification"
                        >
                            <span class="icon editer" title="Éditer l'affectation"></span></a>
                    <?php else : ?>
                        <span class="icon editer" style="color:lightgray;"></span>
                    <?php endif; ?>
                    <?php if ($canDetruireMissionSpecifique) : ?>
                        <a href="<?php echo $this->url('agent-mission-specifique/detruire', ['affectation' => $missionSpecifique->getId()], ["query" => ["structure"=>$structure->getId()]], true); ?>"
                           class="ajax-modal" data-event="modification">
                            <span class="icon detruire" title="Effacer définitivement l'affectation"></span></a>
                    <?php else : ?>
                        <span class="icon detruire" style="color:lightgray;"></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    </div>

        <h2>
        Agents non liés à une fiche de poste
        <span class="badge"> <?php echo count($agentsSansFiche); ?> </span>
    </h2>

        <table class="table table-condensed">
        <thead>
            <tr>
                <th class="agent-cell"> Agent </th>
                <th></th>
                <th class="action-cell"> Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($agentsSansFiche as $agent)  :?>
                <tr>
                    <td> <?php echo $agent->getDenomination() ; ?> </td>
                    <td></td>
                    <td class="action-cell">
                        <?php if ($canAfficherAgent) : ?>
                            <a href="<?php echo $this->url('agent/afficher', ['id' => $agent->getId()], [], true); ?>"
                               class="ajax-modal"
                            >
                                <span class="icon voir"  title="Afficher l'agent"></span></a>
                        <?php endif; ?>
                        <?php if ($canEditerFichePoste) : ?>
                            <?php /** @see MesStructuresController::ajouterFichePosteAction() */ ?>
                            <a href="<?php echo $this->url('mes-structures/ajouter-fiche-poste', ['structure' => $structure->getId(), 'agent' => $agent->getId()], [], true); ?>">
                                <span class="icon ajouter"      title="Ajouter une fiche de poste"></span></a>
                        <?php else : ?>
                            <span class="icon ajouter"      style="color:lightgray"></span>
                        <?php endif; ?>
                        <?php if ($canEditerFichePoste AND !empty($fichesPostes)) : ?>
                            <?php /** @see MesStructuresController::dupliquerFichePosteAction() */ ?>
                            <a href="<?php echo $this->url('mes-structures/dupliquer-fiche-poste', ['structure' => $structure->getId(), 'agent' => $agent->getId()], [], true); ?>"
                               class="ajax-modal" data-event="duplication"
                            >
                                <span class="icon cloner"       title="Cloner une fiche pour cet&middot;te agent"></span>
                        <?php else : ?>
                            <span class="icon cloner"       style="color:lightgray"></span>
                        <?php endif; ?>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>


<style>
    th.agent-cell {
      width:25rem;
    }
    th.libelle-cell {
        width:25rem;
    }
    th.action-cell {
        width:10rem;
    }
    td.action-cell {
        text-align: right;
    }

    h2 {
        color: #3c6c8b;
        text-decoration: none;
    }

</style>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function() {
        $("body").on("duplication", function (event) {
            let content = event.div.html();
            let match_regex = content.match(/#[0-9]*/g)[0];
            let id = match_regex.split('#')[1];
            event.div.modal('hide');
            console.log("fiche-de-poste: " + id);
            window.location.href = '../fiche-poste/editer/' + id + '?structure=' + <?php echo ($structure)?$structure->getId():0; ?>
        });
    });

    $(function() {
      $('select#structure').change(function() {
          let id = $('select#structure option:selected').val();
          console.log("structure: " + id);
          window.location.href = './' + id;
      });
   });
</script>

