<?php

namespace EntretienProfessionnel\Provider\Parametre;

class EntretienProfessionnelParametres {

    const TYPE = 'ENTRETIEN_PROFESSIONNEL';

    const CAMPAGNE_BLOCAGE_STRICT_MODIFICATION = 'CAMPAGNE_BLOCAGE_STRICT_MODIFICATION';
    const CAMPAGNE_BLOCAGE_STRICT_VALIDATION = 'CAMPAGNE_BLOCAGE_STRICT_VALIDATION';

    const DELAI_CONVOCATION_AGENT = 'DELAI_CONVOCATION_AGENT';
    const DELAI_ACCEPTATION_AGENT = 'DELAI_ACCEPTATION_AGENT';
    const INTRANET_DOCUMENT = 'INTRANET_DOCUMENT';
    const MAIL_LISTE_BIATS = 'MAIL_LISTE_BIATS';
    const MAIL_LISTE_DAC = 'MAIL_LISTE_DAC';

    const TEMOIN_AFFECTATION = 'TEMOIN_AFFECTATION';
    const TEMOIN_EMPLOITYPE = 'TEMOIN_EMPLOITYPE';
    const TEMOIN_STATUT = 'TEMOIN_STATUT';
    const TEMOIN_GRADE = 'TEMOIN_GRADE';
    const TEMOIN_CORPS = 'TEMOIN_CORPS';

    const OBSERVATION_AGENT_FINAL = 'OBSERVATION_AGENT_FINAL';
    const TEMOIN_CORPS_EXCLUS = 'TEMOIN_CORPS_EXCLUS';
}