<?php

/**
 * @var Corps[] $corps
 * @var bool $canAfficher
 * @var bool $canModifier
 */

use Application\Entity\Db\Corps;

?>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th style="width:70%;"> Libellé</th>
        <th> #Agent/Grade </th>
        <th> Catégorie </th>
        <th> Niveau </th>
        <th style="width:3rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($corps as $corp): ?>
        <tr>
            <td>
                <span
                    title="<?php echo $corp->generateTooltip(); ?>"
                    data-toggle="tooltip" data-html="true"
                >
                <?php echo $corp->getLibelleLong(); ?>
                </span>
            </td>
            <td> <?php echo count($corp->getAgentGrades()); ?> </td>
            <td> <?php echo $corp->getCategorie(); ?> </td>
            <td> <?php if ($corp->getNiveau()) : ?>
                    <span
                            data-toggle="tooltip" data-html="true"
                            title="<?php echo $corp->getNiveau()->getLibelle(); ?> : Niveau <?php echo $corp->getNiveau()->getNiveau(); ?>">
                    <?php echo $corp->getNiveau()->getEtiquette(); ?>
                    </span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canModifier) : ?>
                    <a
                        <?php /** @see \Application\Controller\CorpsController::modifierNiveauAction() */ ?>
                        href="<?php echo $this->url('corps/modifier-niveau', ['corps' => $corp->getId()], ['fragment' => 'corps'], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                                    <span class="icon editer" data-toggle="tooltip" data-html="true"
                                          title="Modifier le niveu du corps"></span></a>
                <?php endif; ?>
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Application\Controller\CorpsController::afficherAgentsAvecCorpsAction() */ ?>
                        href="<?php echo $this->url('corps/afficher-agents-avec-corps', ['corps' => $corp->getId()], ['fragment' => 'corps'], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                                        <span class="icon voir" data-toggle="tooltip" data-html="true"
                                              title="Afficher les agents ayant ce corps"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>