<?php

use Application\Entity\Db\Categorie;

/**
 * @var Categorie[] $categories
 */

$canAjouter = true;
$canModifier = true;
$canHistoriser = true;
$canDetruire = true;
?>

<div class="row">
    <div class="col-md-8">
        <h2>
            Liste des catégories
        </h2>
    </div>
    <div class="pull-right">
        <br/>
        <?php if ($canAjouter) : ?>
            <a
                    <?php /** @see \Application\Controller\CategorieController::ajouterAction() */ ?>
                    href="<?php echo $this->url('categorie/ajouter', [], [], true); ?>"
                    class="btn btn-primary action ajax-modal" data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter une catégorie
            </a>
        <?php endif; ?>
    </div>
</div>

<br/>
<br/>

<table class="datatable table table-condensed">
    <thead>
        <tr>
            <th> Code </th>
            <th> Libelle </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($categories as $categorie) : ?>
        <tr <?php if ($categorie->estHistorise()) echo " class='historise'"; ?>>
            <td>
                <?php echo $categorie->getCode(); ?>
            </td>
            <td>
                <?php echo $categorie->getLibelle(); ?>
            </td>
            <td>
                <?php if ($canModifier) : ?>
                    <a
                            <?php /** @see \Application\Controller\CategorieController::modifierAction() */ ?>
                            href="<?php echo $this->url('categorie/modifier', ['categorie' => $categorie->getId()], [], true); ?>"
                            title="Modification de la catégorie" data-toggle="tooltip" data-html="true"
                            class="ajax-modal" data-event="modification"
                        >
                    <span class="icon editer"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($categorie->estHistorise()) : ?>
                        <a
                            <?php /** @see \Application\Controller\CategorieController::restaurerAction() */ ?>
                                href="<?php echo $this->url('categorie/restaurer', ['categorie' => $categorie->getId()], [], true); ?>"
                                title="Restauration de la catégorie" data-toggle="tooltip" data-html="true"
                        >
                            <span class="icon restaurer"></span></a>
                    <?php else: ?>
                        <a
                            <?php /** @see \Application\Controller\CategorieController::historiserAction() */ ?>
                                href="<?php echo $this->url('categorie/historiser', ['categorie' => $categorie->getId()], [], true); ?>"
                                title="Historisation de la catégorie" data-toggle="tooltip" data-html="true"
                        >
                            <span class="icon historiser"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <a
                        <?php /** @see \Application\Controller\CategorieController::supprimerAction() */ ?>
                            href="<?php echo $this->url('categorie/supprimer', ['categorie' => $categorie->getId()], [], true); ?>"
                            title="Destruction de la catégorie" data-toggle="tooltip" data-html="true"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>