<?php

/**
 * @see \Carriere\Controller\FamilleProfessionnelleController::indexAction()
 * @var FamilleProfessionnelle[] $familles
 * @var Correspondance[] $correspondances
 * @var array $params
 */

use Carriere\Entity\Db\Correspondance;
use Carriere\Entity\Db\FamilleProfessionnelle;
use Carriere\Provider\Privilege\FamilleprofessionnellePrivileges;

$canAfficher = $this->isAllowed(FamilleprofessionnellePrivileges::getResourceId(FamilleprofessionnellePrivileges::FAMILLE_PROFESSIONNELLE_AFFICHER));
$canAjouter = $this->isAllowed(FamilleprofessionnellePrivileges::getResourceId(FamilleprofessionnellePrivileges::FAMILLE_PROFESSIONNELLE_AJOUTER));
$canEditer = $this->isAllowed(FamilleprofessionnellePrivileges::getResourceId(FamilleprofessionnellePrivileges::FAMILLE_PROFESSIONNELLE_MODIFIER));
$canHistoriser = $this->isAllowed(FamilleprofessionnellePrivileges::getResourceId(FamilleprofessionnellePrivileges::FAMILLE_PROFESSIONNELLE_HISTORISER));
$canEffacer = $this->isAllowed(FamilleprofessionnellePrivileges::getResourceId(FamilleprofessionnellePrivileges::FAMILLE_PROFESSIONNELLE_SUPPRIMER));

$this->headTitle("Familles professionnelles");
?>

<h1 class="page-header">
    Familles professionnelles
</h1>

<?php if ($canAjouter) : ?>
    <a
        <?php /** @see \Carriere\Controller\FamilleProfessionnelleController::ajouterAction() */ ?>
            href="<?php echo $this->url('famille-professionnelle/ajouter', [], [], true); ?>"
            class="btn btn-primary ajax-modal"
            data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter une famille professionnelle
    </a>
<?php endif; ?>

<?php echo $this->partial('partial/filtre', ['correspondances' => $correspondances, 'params' => $params]); ?>

<table id="familles" class="table table-condesed">
    <thead>
    <tr>
        <th class="col-md-4"> Libellé</th>
        <th class="col-md-1"> Correspondance</th>
        <th class="col-md-1"> Position</th>
        <th class="col-md-4"> Métiers</th>
        <th class="col-md-2 action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($familles as $famille): ?>
        <tr <?php if ($famille->estHistorise()) echo ' class="historise" '; ?>>
            <td data-column-id="Libellé"> <?php echo $famille->getLibelle(); ?> </td>
            <td data-column-id="Correspondance">
                <?php $correspondance = $famille->getCorrespondance(); ?>
                <?php if ($correspondance): ?>
                    <?php echo $correspondance->getType()->getLibelleCourt()??"Sans correspondance"; ?>
                    <?php echo $correspondance->getLibelleCourt()??$correspondance->getCategorie(); ?>
                <?php else: ?>
                    <span class="missing-data"> Aucune </span>
                <?php endif; ?>
            </td>
            <td data-column-id="Position">
                <?php $position = $famille->getPosition(); ?>
                <?php if ($position) : ?>
                    <?php echo $position; ?>
                <?php else: ?>
                    <span class="missing-data"> Aucune </span>
                <?php endif; ?>
            </td>
            <td>
                Aucune famille associée
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Carriere\Controller\FamilleProfessionnelleController::afficherAction() */ ?>
                            href="<?php echo $this->url('famille-professionnelle/afficher', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                            class="ajax-modal action secondary"
                    >
                        <span class="icon icon-voir"></span>
                        Visualiser
                    </a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <br>
                    <a
                        <?php /** @see \Carriere\Controller\FamilleProfessionnelleController::modifierAction() */ ?>
                            href="<?php echo $this->url('famille-professionnelle/modifier', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                            class="ajax-modal action primary"
                            data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($famille->estNonHistorise()) : ?>
                        <a <?php /** @see \Carriere\Controller\FamilleProfessionnelleController::historiserAction() */ ?>
                                href="<?php echo $this->url('famille-professionnelle/historiser', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                                class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <a <?php /** @see \Carriere\Controller\FamilleProfessionnelleController::restaurerAction() */ ?>
                                href="<?php echo $this->url('famille-professionnelle/restaurer', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                                class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <br>
                    <a
                        <?php /** @see \Carriere\Controller\FamilleProfessionnelleController::supprimerAction() */ ?>
                            href="<?php echo $this->url('famille-professionnelle/supprimer', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                            class="ajax-modal action danger" data-event="modification"
                    >
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('#familles').DataTable({
            autoWidth: false,
            order: [[0, 'asc'], [1, 'asc']],
            columnDefs: [{
                "targets": 4,
                "orderable": false
            }],
            language: {
                url: '/js/datatables_fr.json'
            }
        });
    });
</script>