<?php

/**
 * @var FamilleProfessionnelle[] $familles
 * @var boolean[] $droits
 */

use Application\Entity\Db\FamilleProfessionnelle;

$canAjouter        = $droits["ajouter"];
$canEditer         = $droits["editer"];
$canHistoriser     = $droits["historiser"];
$canEffacer        = $droits["effacer"];

?>

<div class="row">
    <div class="col-md-8">
        <h2>
            Familles professionnelles
        </h2>
    </div>
    <div class="pull-right">
        <br/>
        <?php if ($canAjouter) : ?>
            <a
                <?php /** @see \Application\Controller\FamilleProfessionnelleController::ajouterAction() */?>
                href="<?php echo $this->url('famille-professionnelle/ajouter', [], [], true);?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter une famille professionnelle
            </a>
        <?php endif;?>
    </div>
    <br/>
</div>
<br/>
<table id="familles" class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Libelle </th>
        <th> #domaines </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($familles as $famille): ?>
        <tr <?php if ($famille->estHistorise()) echo ' class="historise" '; ?>>
            <td> <?php echo $famille->getLibelle(); ?> </td>
            <td>
                <?php echo count($famille->getDomaines()); ?>
            </td>
            <td>
                <?php if ($canEditer) : ?>
                    <a
                        <?php /** @see \Application\Controller\FamilleProfessionnelleController::modifierAction() */?>
                        href="<?php echo $this->url('famille-professionnelle/modifier', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon editer" title="Modifier la famille professionnelle"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($famille->estNonHistorise()) : ?>
                        <a  <?php /** @see \Application\Controller\FamilleProfessionnelleController::historiserAction() */ ?>
                            href="<?php echo $this->url('famille-professionnelle/historiser', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser la famille professionnelle"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \Application\Controller\FamilleProfessionnelleController::restaurerAction() */ ?>
                            href="<?php echo $this->url('famille-professionnelle/restaurer', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer la famille professionnelle"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <a
                        <?php /** @see \Application\Controller\FamilleProfessionnelleController::effacerAction() */?>
                        href="<?php echo $this->url('famille-professionnelle/effacer', ['famille-professionnelle' => $famille->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire"  title="Supprimer la famille professionnelle"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('#familles').DataTable( {
            sorting: false,
            paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );
</script>