<?php

use FicheMetier\Entity\Db\ThematiqueType;
use FicheMetier\Provider\Privilege\ThematiquetypePrivileges;

/**
 * @see \FicheMetier\Controller\ThematiqueTypeController::indexAction()
 * @var ThematiqueType[] $thematiquesTypes
 */

$this->headTitle("Type de thématiques");

$canAfficher = $this->isAllowed(ThematiquetypePrivileges::getResourceId(ThematiquetypePrivileges::THEMATIQUETYPE_AFFICHER));
$canAjouter  = $this->isAllowed(ThematiquetypePrivileges::getResourceId(ThematiquetypePrivileges::THEMATIQUETYPE_AJOUTER));
$canModifier = $this->isAllowed(ThematiquetypePrivileges::getResourceId(ThematiquetypePrivileges::THEMATIQUETYPE_MODIFIER));
$canHistoriser = $this->isAllowed(ThematiquetypePrivileges::getResourceId(ThematiquetypePrivileges::THEMATIQUETYPE_HISTORISER));
$canSupprimer = $this->isAllowed(ThematiquetypePrivileges::getResourceId(ThematiquetypePrivileges::THEMATIQUETYPE_SUPPRIMER));

?>

<h1 class="page-header">
    Type de thèmatiques
</h1>

<div>
    <?php /** @see \FicheMetier\Controller\ThematiqueTypeController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('fiche-metier/thematique-type/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un type de thématique
    </a>
</div>

<table class="table table-condensed datatable" id="thematiques">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> Code </th>
        <th> Obligatoire </th>
        <th> Ordre </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($thematiquesTypes as $thematiqueType) : ?>
        <tr>
            <td> <?php echo $thematiqueType->getLibelle(); ?> </td>
            <td> <?php echo $thematiqueType->getCode(); ?> </td>
            <td> <?php echo ($thematiqueType->isObligatoire())?"<span class='text-success'>Oui</span>":"<span class='text-danger'>Non</span>"; ?> </td>
            <td> <?php echo $thematiqueType->getOrdre(); ?></td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \FicheMetier\Controller\ThematiqueTypeController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier/thematique-type/afficher', ['thematique-type' => $thematiqueType->getId()], [], true); ?>"
                       class="ajax-modal action secondary"
                       >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\ThematiqueTypeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier/thematique-type/modifier', ['thematique-type' => $thematiqueType->getId()], [], true); ?>"
                       class="ajax-modal action primary" data-event="modification"
                    >
                        <span class="icon icon-modifier"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($thematiqueType->estNonHistorise()) : ?>
                        <?php /** @see \FicheMetier\Controller\ThematiqueTypeController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/thematique-type/historiser', ['thematique-type' => $thematiqueType->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \FicheMetier\Controller\ThematiqueTypeController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/thematique-type/restaurer', ['thematique-type' => $thematiqueType->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\ThematiqueTypeController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier/thematique-type/supprimer', ['thematique-type' => $thematiqueType->getId()], [], true); ?>"
                       class="ajax-modal action danger" data-event="modification"
                    >
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('table#thematiques').dataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [4], orderable: false }
            ]
        });
    });
</script>