<?php

/**
 * @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::accederAction()
 * @var UserInterface $user
 * @var RoleInterface $role
 *
 *
 * @var EntretienProfessionnel $entretien
 * @var Agent $agent
 * @var FichePoste[] $ficheposte
 * @var FicheMetier[] $fichesmetiers
 * @var ParcoursDeFormation $parcours
 * @var Mail[] $mails
 * @var string[] $documents
 * @var FormulaireInstance $crep
 * @var FormulaireInstance $cref
 *
 * @var Agent[] $superieures
 * @var Agent[] $autorites
 *
 * @var bool $BLOCAGE_COMPTERENDU
 * @var bool $BLOCAGE_VALIDATION
 */

use Application\Entity\Db\Agent;
use Application\Provider\Role\RoleProvider;
use EntretienProfessionnel\Assertion\EntretienProfessionnelAssertion;
use FicheMetier\Entity\Db\FicheMetier;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\ParcoursDeFormation;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Etat\EntretienProfessionnelEtats;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use UnicaenAutoform\Entity\Db\FormulaireInstance;
use UnicaenMail\Entity\Db\Mail;
use UnicaenUtilisateur\Entity\Db\RoleInterface;
use UnicaenUtilisateur\Entity\Db\UserInterface;

$displayParcours = false;
$displayAcquis = false;

$this->headTitle('Modification de l\'entretien professionnel');


$canExporterEP = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_EXPORTER);
$canModifierEP = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_RENSEIGNER);

$now = new DateTime();
$date = $entretien->getMaxSaisiObservation();
$depasseObs = ($date !== null AND $date < $now);

$step = 0;

if ($entretien->isEtatActif(EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_RESPONSABLE)) $step = 1;
if ($entretien->isEtatActif(EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_OBSERVATION) OR $depasseObs) $step = 2;
if ($entretien->isEtatActif(EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_HIERARCHIE))  $step = 3;
if ($entretien->isEtatActif(EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_AGENT))       $step = 4;

?>

<span style="visibility: hidden;">Entretien professionnel #<?php echo $entretien->getId(); ?></span>
<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Entretien professionnel
            <?php if ($entretien->getCampagne()) : ?>
                <?php echo $entretien->getCampagne()->getAnnee(); ?>
            <?php else : ?>
                Sans campagne
            <?php endif; ?>
            <br/>
            <?php echo $agent->getPrenom(); ?>
            <?php echo $agent->getNomUsuel(); ?>
        </h1>
    </div>
    <div class="col-md-4">
    <?php $isAgent                = $entretien->getAgent()->getUtilisateur() === $user; ?>
    <?php if ($isAgent AND (
        $entretien->isEtatActif(EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTER) ||
        $entretien->isEtatActif(EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTATION) )) : ?>
    <?php else : ?>
        <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::retourListeAction() */ ?>
        <a href="<?php echo $this->url('entretien-professionnel/retour-liste', ['entretien-professionnel' => $entretien->getId()], [], true); ?>"
            class="btn btn-secondary">
            <span class="icon icon-retour"></span>
            Retour à la liste des entretiens
        </a>
        <?php if ($canExporterEP) : ?>
            <div class="pull-right">
                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::exporterCrepAction() */?>
                <a href="<?php echo $this->url('entretien-professionnel/exporter-crep', ['entretien' => $entretien->getId()], [], true) ?>" target="_blank"
                   class="btn btn-primary action">
                    <span class="icon icon-pdf"></span>
                    Exporter le CREP
                </a>
                <br/>
                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::exporterCrefAction() */?>
                <a href="<?php echo $this->url('entretien-professionnel/exporter-cref', ['entretien' => $entretien->getId()], [], true) ?>" target="_blank"
                   class="btn btn-primary action">
                    <span class="icon icon-pdf"></span>
                    Exporter le CREF
                </a>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    </div>
</div>


<?php
    echo $this->partial('partial/header', ['entretien' => $entretien, 'agent' => $agent, 'ficheposte' => $ficheposte, 'fichesmetiers' => $fichesmetiers, "documents" => $documents], [], true);
?>


<?php if ($role->getRoleId() === RoleProvider::AGENT) : ?>
    <div class="alert alert-info">
        <strong> <span class="icon icon-information"></span> Modification des compte-rendus. </strong>

        <br>
        En tant qu'Agent ou Agente, vous pouvez modifier le compte-rendu d'entretien professionnel :
        <ul>
            <li> après avoir accepté celui-ci <?php echo ($entretien->isAccepte())?"<span class='icon icon-checked'></span>":"<span class='icon icon-unchecked'></span>"; ?> </li>
            <li> tant que la date d'entretien n'est pas dépassée <?php echo (!$entretien->isDepasse())?"<span class='icon icon-checked'></span>":"<span class='icon icon-unchecked'></span>"; ?> </li>
            <li> tant que le ou la Responsable de l'entretien n'a pas validé celui-ci <?php echo (!$entretien->isValideResponsable())?"<span class='icon icon-checked'></span>":"<span class='icon icon-unchecked'></span>"; ?> </li>
<!--            <li> avoir le droit de renseigner les comptes-rendus --><?php //echo ($canModifierEP)?"<span class='icon icon-checked'></span>":"<span class='icon icon-unchecked'></span>"; ?><!-- </li>-->
        </ul>
    </div>
<?php endif; ?>

<div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="formulaire-tab"
            data-bs-toggle="tab" data-bs-target="#formulaire"
            type="button" role="tab" aria-controls="formulaire" aria-selected="true">
        Compte-rendu <br/> d'entretien professionnel
    </button>
    <button class="nav-link" id="formations-tab"
            data-bs-toggle="tab" data-bs-target="#formations"
            type="button" role="tab" aria-controls="formations" aria-selected="true">
        Compte-rendu <br/> d'entretien de formation
    </button>
    <button class="nav-link" id="validation-tab"
            data-bs-toggle="tab" data-bs-target="#validation"
            type="button" role="tab" aria-controls="validation" aria-selected="true">
        Observations et <br/> validations <span class="badge" style="margin-left:1rem;"><?php echo $step; ?>/4</span>
    </button>
    <button class="nav-link" id="mails-tab"
            data-bs-toggle="tab" data-bs-target="#mails"
            type="button" role="tab" aria-controls="mails" aria-selected="true">
        Courriers <br/> &nbsp;électroniques <span class="badge" style="margin-left:1rem;"><?php echo count($mails); ?></span>
    </button>
</div>


    <div class="tab-content">

    <div id="formulaire" class="tab-pane" >
        <?php if ($BLOCAGE_COMPTERENDU && !EntretienProfessionnelAssertion::isPeriodeCompatible($entretien)) : ?>
            <div class="alert alert-info">
                <strong>
                    <span class="icon icon-information"></span>
                    La campagne n'est pas active !
                </strong>

                <p> Par conséquent, vous ne pouvez plus modifier le compte-rendu d'entretien professionnel.</p>
            </div>
        <?php endif; ?>

        <?php echo $this->partial('partial/crep', ['entretien' => $entretien, 'crep' => $crep, 'fichePoste' => $ficheposte, 'user' => $user, 'role' => $role, 'source' => 'renseignerAction']); ?>
    </div>

    <div id="formations" class="tab-pane">

        <?php if ($BLOCAGE_COMPTERENDU && !EntretienProfessionnelAssertion::isPeriodeCompatible($entretien)) : ?>
            <div class="alert alert-info">
                <strong>
                    <span class="icon icon-information"></span>
                    La campagne n'est pas active !
                </strong>

                <p> Par conséquent, vous ne pouvez plus modifier le compte-rendu d'entretien professionnel.</p>
            </div>
        <?php endif; ?>

        <?php echo $this->partial('partial/cref', ['entretien' => $entretien, 'cref' => $cref, 'parcours' => $parcours??null,  'connectedUser' => $user, 'fiche' => $ficheposte, 'options' => ['modification' => true], 'source' => 'renseignerAction']); ?>
    </div>

<!--            --><?php //if ($displayAcquis === true) : ?>
<!--            <div id="acquis" class="tab-pane">-->
<!--                --><?php //echo $this->partial('partial/acquis.phtml', ['entretien' => $entretien, 'agent' => $agent, 'options' => ['modification' => true], 'source' => 'renseignerAction']); ?>
<!--            </div>-->
<!--            --><?php //endif; ?>

    <div id="validation" class="tab-pane">

        <?php if ($BLOCAGE_VALIDATION && !EntretienProfessionnelAssertion::isPeriodeCompatible($entretien)) : ?>
            <div class="alert alert-info">
                <strong>
                    <span class="icon icon-information"></span>
                    La campagne n'est pas active !
                </strong>

                <p> Par conséquent, vous ne pouvez plus valider l'entretien professionnel.</p>
            </div>
        <?php endif; ?>

        <?php echo $this->partial('partial/validation', ['entretien' => $entretien, 'source' => 'renseignerAction','superieures' => $superieures, 'autorites' => $autorites,'step' => $step]); ?>
    </div>

    <div id="mails" class="tab-pane">

        <br/>
        <div>
            <?php echo $this->mails($mails); ?>
        </div>
    </div>
</div>


<style>
    h3.categorie {
        border-bottom: 1px solid #31708f;
    }
</style>

<script>
    $(function () {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "formulaire";

        $('button').removeClass('active');
        $('button#' + name + '-tab').addClass('active');
        $('div.tab-pane').hide().removeClass('active');
        $('div#' + name).show().addClass('active');

        //$('#' + name + '-tab').tab("show");
        $('button.nav-link').on('click', function (e) {
            let anchor = $(this).attr('aria-controls');
            $('div.tab-pane').hide().removeClass('active');
            $('div#' + anchor).show().addClass('active');
            $('button').removeClass('active');
            $('button#' + anchor + '-tab').addClass('active');
            // console.log(anchor);
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#" + anchor);
        });
    });

    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('.datatable').DataTable( {
            // sorting: false,
            // paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    });
</script>


