<?php

/**
 * @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::accepterEntretienAction()
 * @var EntretienProfessionnel $entretien
 * @var string $token
 * @var bool $depassee
 */

use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;

?>

<?php if ($entretien === null) : ?>
    <div class="alert alert-danger">
        <p> Aucune entretien professionnel de remonté pour le token <?php echo $token; ?> </p>
        <p>
            Le problème peut-être lié au fait que :
            <ul>
                <li> vous avez déjà accepter votre entretien, </li>
                <li> l'entretien est déjà passé, </li>
                <li> l'entretien a été effacé, </li>
            </ul>
        </p>
    </div>
<?php else : ?>

    <?php if ($depassee) : ?>
        <div class="alert alert-warning">
            <p> Le délai d'accepation de l'entretien professionnel est maintenant dépassé. </p>
            <p> Vous pouvez encore accépter celui-ci mais votre responsable d'entretien peut maintenant refuser celui-ci.</p>
        </div>
    <?php endif; ?>

    <div class="alert alert-success">
        <p> Vous venez d'accepter votre entretien professionnel qui se déroule le <?php echo $entretien->getDateEntretien()->format('d/m/Y à H:i'); ?> </p>
        <p> Vous pouvez dorénavant commencer à consulter votre fiche de poste et présaisir votre entretien professionnelle en vous connectant à EMC2 : <a href="<?php echo $this->url('home'); ?>">lien</a>. </p>
    </div>
<?php endif; ?>
