<?php

/**
 * @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::indexAgentAction()
 * @var EntretienProfessionnel\Entity\Db\EntretienProfessionnel[] $entretiens
 * @var string $intranet
 *
 * @var ?Agent $agent
 * @var Campagne[] $campagnesActives
 * @var ?AbstractRole $connectedRole
 * @var ?AbstractUser $connectedUser
 */

use Agent\Entity\Db\Agent;
use Agent\Provider\Role\RoleProvider;
use EntretienProfessionnel\Entity\Db\Campagne;
use UnicaenUtilisateur\Entity\Db\AbstractRole;
use UnicaenUtilisateur\Entity\Db\AbstractUser;

$this->headTitle('Index des entretiens professionnel');

$canAfficherEntretien = true;
?>

<h1 class="page-header">
    Mes entretiens professionnels
</h1>

<?php if ($connectedUser === $agent?->getUtilisateur() AND $connectedRole?->getRoleId() === RoleProvider::ROLE_AGENT) : ?>
    <?php foreach ($campagnesActives as $campagne) : ?>
        <?php echo $this->aideAgentCampagne($agent, $campagne); ?>
    <?php endforeach; ?>
<?php endif; ?>


    <?php echo $this->entretienProfessionnelArray($entretiens,
        [
            'affichages' => ['agent' => false, 'lieu' => false],
            'droits' => ['modifier' => false, 'historiser' => false,  'supprimer' => false, 'sursis' => false],
            'id' => 'mes-entretiens'
        ]
    ); ?>

    <br/>

    <?php if (isset($intranet) AND $intranet!== null AND trim($intranet) !== ''): ?>
    <div class="alert alert-info">
        <span class="icon icon-attention"></span> Vous pouvez retrouver sur l'intranet les documents vous permettant de préparer votre entretien : <?php echo $intranet; ?>.
    </div>
    <?php endif; ?>
