<?php

/**
 * @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::indexAgentAction()
 * @var EntretienProfessionnel\Entity\Db\EntretienProfessionnel[] $entretiens
 */

$this->headTitle('Index des entretiens professionnel');

$canAfficherEntretien = true;
?>

<h1 class="page-header">
    Mes entretiens professionnels
</h1>

    <div class="alert alert-info">
        <span class="icon icon-attention"></span> Seuls les entretiens professionnels validés par le&middot;a supérieur·e hiérarchique direct·e (ou son&middot;a délégué&middot;e) sont visualisables par les agents.
    </div>

    <?php echo $this->entretienProfessionnelArray($entretiens,
        [
            'affichages' => ['agent' => false, 'lieu' => false],
            'droits' => ['modifier' => false, 'historiser' => false,  'supprimer' => false, 'sursis' => false]
        ]
    ); ?>

    <br/>
    <div class="alert alert-info">
        <span class="icon icon-attention"></span> Vous pouvez retrouvez sur l'intranet les documents vous permettant de préparer votre entretien : <?php echo $intranet; ?>.
    </div>
