<?php

/**
 * @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::indexAction()
 * @var Campagne[] $campagnes
 * @var EntretienProfessionnel[] $entretiens
 * @var Etat[] $etats
 *
 * @var array $params
 */

use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use UnicaenEtat\Entity\Db\Etat;

$this->headTitle('Index des entretiens professionnel');


$canVoir        = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AFFICHER));
$canAjouter     = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AJOUTER));
$canModifier    = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_MODIFIER));
$canHistoriser  = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_HISTORISER));
$canDetruire    = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_DETRUIRE));
?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Index des entretiens professionnels
        </h1>
    </div>
    <div class="col-md-3">
        <a href="<?php echo $this->url('entretien-professionnel/campagne', [], [], true); ?>"
           class="btn btn-primary">
            <span class="icon icon-listing"></span>
                Accéder aux campagnes
        </a>
    </div>
</div>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<?php echo $this->partial('partial/filtre', ['etats' => $etats, 'campagnes' => $campagnes, 'params' => $params], [], true); ?>

<?php echo $this->entretienProfessionnelArray($entretiens,
    [
        'affichages' => ['lieu' => false],
        'droits' => []
    ]
); ?>


<style>
    th#etat {
        width:6rem;
        min-width: 6rem;
    }

    th#action {
        width:11rem;
        min-width: 6rem;
    }

    @media (min-width: 0) and (max-width: 768px) {
        th {
            font-size: small;
        }
        td {
            font-size: small;
            background: var(--content-background);
        }
    }

</style>

<script>
    $("body").on("modification", function (event) {
        event.div.modal('hide');
        window.location.reload();
    });
</script>
