<?php

/**
 * @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::indexAction()
 * @var Campagne[] $campagnes
 * @var EntretienProfessionnel[] $entretiens
 * @var Etat[] $etats
 *
 * @var array $params
 */

use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use UnicaenEtat\Entity\Db\Etat;

$this->headTitle('Index des entretiens professionnel');

?>

<h1 class="page-header">
    Index des entretiens professionnels
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">

        <li role="presentation">
            <a href="#campagne" aria-controls="campagne" role="tab" data-toggle="tabz">
                Campagnes
                <span class="badge">
                <?php echo count($campagnes); ?>
            </span>
            </a>
        </li>

        <li role="presentation">
            <a href="#entretien" aria-controls="entretien" role="tab" data-toggle="tabz">
                Entretiens professionnels
                <span class="badge">
                <?php echo count($entretiens); ?>
            </span>
            </a>
        </li>
    </ul>
</div>

<div class="tab-content">

    <!-- CAMPAGNES ------------------------------------------------------------------------------------------------>
    <div id="campagne" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/index-campagne', ['campagnes' => $campagnes]); ?>
    </div>

    <!-- ENTRETIENS ------------------------------------------------------------------------------------------------>
    <div id="entretien" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/index-entretien', ['entretiens' => $entretiens, 'etats' => $etats, 'campagnes' => $campagnes, 'params' => $params]); ?>
    </div>
</div>

<script>

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "campagne";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });
    });

    $("body").on("modification", function (event) {
        event.div.modal('hide');
        window.location.reload();
    });
</script>
