<?php

/**
 * @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::renseignerAction()
 * @var EntretienProfessionnel $entretien
 * @var array $parcours
 * @var Agent $agent
 * @var FichePoste[] $fichespostes
 * @var FicheMetier[] $fichesmetiers
 * @var ParcoursDeFormation $parcours
 * @var User $connectedUser
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\ParcoursDeFormation;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use UnicaenUtilisateur\Entity\Db\User;

$ficheposte = $agent->getFichePosteActif();

$this->headTitle('Modification de l\'entretien professionnel');

$canVoir        = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VOIR);
$canAjouter     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_AJOUTER);
$canModifier    = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_MODIFIER);
$canHistoriser  = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_HISTORISER);
$canDetruire    = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_DETRUIRE);
$canValider     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VALIDER);

$canValiderAgent        = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_AGENT);
$canValiderResponsable  = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_RESPONSABLE);
$canValiderDrh          = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_DRH);

$droits = [
    'afficher' => $canVoir,
    'ajouter' => $canAjouter,
    'modification' => $canModifier,
    'historiser' => $canHistoriser,
    'detruire' => $canDetruire,
    'valider' => $canValider,
];
?>

<span style="visibility: hidden;">Entretien professionnel #<?php echo $entretien->getId(); ?></span>
<h1 class="page-header">
    Entretien professionnel <?php echo $entretien->getAnnee(); ?> <br/>
    <?php echo $entretien->getAgent()->getPrenom(); ?>
    <?php echo $entretien->getAgent()->getNomUsuel(); ?>
</h1>


<h1 class="page-header">
    Affichage de l'entretien professionnel
</h1>

<?php
echo $this->partial('partial/header', ['entretien' => $entretien, 'agent' => $agent, 'fichespostes' => $fichespostes, 'fichesmetiers' => $fichesmetiers], [], true);
?>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <li>
            <a href="#formulaire" aria-controls="formulaire" role="tab" data-toggle="tabz">
                Compte-rendu <br/> d'entretien <br/> professionnel
            </a>
        </li>
        <li>
            <a href="#formations" aria-controls="formations" role="tab" data-toggle="tabz">
                Compte-rendu <br/> d'évaluation <br/> de formation &nbsp;
            </a>
        </li>
        <li>
            <a href="#parcours" aria-controls="parcours" role="tab" data-toggle="tabz">
                Parcours de <br/> formation et <br/> applicatif
            </a>
        </li>
        <li>
            <a href="#acquis" aria-controls="acquis" role="tab" data-toggle="tabz">
                Acquis de <br/> l'agent <br/> &nbsp;
            </a>
        </li>
        <li>
            <a href="#avis" aria-controls="avis" role="tab" data-toggle="tabz" >
                <br/> &nbsp; Observations <br/> &nbsp;
            </a>
        </li>
        <li>
            <a href="#validation" aria-controls="validation" role="tab" data-toggle="tabz" >
                <br/> &nbsp; Validations <br/> &nbsp;
            </a>
        </li>
    </ul>

    <div class="main-with-tab">

        <div class="tab-content">

            <div id="formulaire" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/formulaire', ['entretien' => $entretien, 'fichePoste' => $ficheposte, 'connectedUser' => $connectedUser, 'source' => 'renseignerAction']); ?>
            </div>

            <div id="formations" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/formations.phtml', ['entretien' => $entretien, 'parcours' => $parcours, 'fiche' => $ficheposte, 'options' => ['modification' => true], 'source' => 'renseignerAction']); ?>
            </div>
            <div id="parcours" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/parcours.phtml', ['entretien' => $entretien, 'agent' => $agent, 'parcours' => $parcours, 'fiche' => $ficheposte, 'options' => ['mode' => 'modification', 'modification' => true, 'droits' => $droits], 'source' => 'renseignerAction']); ?>
            </div>
            <div id="acquis" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/acquis.phtml', ['entretien' => $entretien, 'agent' => $agent, 'options' => ['modification' => true], 'source' => 'renseignerAction']); ?>
            </div>

            <div id="avis" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/observation.phtml', ['entretien' => $entretien, 'observation' => $entretien->getObservationActive(), 'droits' => $droits, 'source' => 'renseignerAction']); ?>
            </div>

            <div id="validation" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/validation', ['entretien' => $entretien, 'source' => 'renseignerAction']); ?>
            </div>
        </div>
    </div>

</div>


<script>
    $(document).ready(function() {
        $('.datatable').DataTable( {
            // sorting: false,
            // paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "formulaire";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


