<?php

/**
 * @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::renseignerAction()
 * @var EntretienProfessionnel $entretien
 * @var array $parcours
 * @var Agent $agent
 * @var FichePoste[] $ficheposte
 * @var FicheMetier[] $fichesmetiers
 * @var ParcoursDeFormation $parcours
 * @var User $connectedUser
 * @var Mail[] $mails
 * @var string[] $documents
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\ParcoursDeFormation;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use UnicaenMail\Entity\Db\Mail;
use UnicaenUtilisateur\Entity\Db\User;

$displayParcours = false;
$displayAcquis = false;

$this->headTitle('Modification de l\'entretien professionnel');

$canVoir        = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VOIR);
$canAjouter     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_AJOUTER);
$canModifier    = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_MODIFIER);
$canHistoriser  = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_HISTORISER);
$canDetruire    = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_DETRUIRE);
$canValider     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VALIDER);

$canValiderAgent        = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_AGENT);
$canValiderResponsable  = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_RESPONSABLE);
$canValiderDrh          = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_DRH);

$canExporter = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_EXPORTER);

$droits = [
    'afficher' => $canVoir,
    'ajouter' => $canAjouter,
    'modification' => $canModifier,
    'historiser' => $canHistoriser,
    'detruire' => $canDetruire,
    'valider' => $canValider,
];
?>

<span style="visibility: hidden;">Entretien professionnel #<?php echo $entretien->getId(); ?></span>
<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Entretien professionnel <?php echo $entretien->getAnnee(); ?> <br/>
            <?php echo $agent->getPrenom(); ?>
            <?php echo $agent->getNomUsuel(); ?>
        </h1>
    </div>
    <div class="pull-right">
        <?php if ($canExporter) : ?>
            <a href="" target="_blank"
               class="btn btn-primary action">
                <span class="icon pdf"></span>
                Exporter en PDF
            </a>
        <?php endif; ?>
    </div>
</div>


<?php
echo $this->partial('partial/header', ['entretien' => $entretien, 'agent' => $agent, 'ficheposte' => $ficheposte, 'fichesmetiers' => $fichesmetiers, "documents" => $documents], [], true);
?>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <li>
            <a href="#formulaire" aria-controls="formulaire" role="tab" data-toggle="tabz">
                Compte-rendu <br/> d'entretien <br/> professionnel
            </a>
        </li>
        <li>
            <a href="#formations" aria-controls="formations" role="tab" data-toggle="tabz">
                Compte-rendu d'entretien' <br/> de formation &nbsp;
            </a>
        </li>
        <?php if ($displayParcours === true) : ?>
            <li>
                <a href="#parcours" aria-controls="parcours" role="tab" data-toggle="tabz">
                    Parcours de <br/> formation et <br/> logiciels metiers
                </a>
            </li>
        <?php endif; ?>
        <?php if ($displayAcquis === true) : ?>
        <li>
            <a href="#acquis" aria-controls="acquis" role="tab" data-toggle="tabz">
                Acquis de <br/> l'agent <br/> &nbsp;
            </a>
        </li>
        <?php endif ?>
        <li>
            <a href="#avis" aria-controls="avis" role="tab" data-toggle="tabz" >
                <br/> &nbsp; Observations <br/> &nbsp;
            </a>
        </li>
        <li>
            <a href="#validation" aria-controls="validation" role="tab" data-toggle="tabz" >
                <br/> &nbsp; Validations <br/> &nbsp;
            </a>
        </li>
        <li class="pull-right">
            <a href="#mails" aria-controls="mails" role="tab" data-toggle="tabz" >
                <br/> Mails <br/> &nbsp;
            </a>
        </li>
    </ul>

    <div class="main-with-tab">

        <div class="tab-content">

            <div id="formulaire" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/formulaire', ['entretien' => $entretien, 'fichePoste' => $ficheposte, 'connectedUser' => $connectedUser, 'source' => 'renseignerAction']); ?>
            </div>

            <div id="formations" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/formations.phtml', ['entretien' => $entretien, 'parcours' => $parcours,  'connectedUser' => $connectedUser, 'fiche' => $ficheposte, 'options' => ['modification' => true], 'source' => 'renseignerAction']); ?>
            </div>

            <?php if ($displayParcours === true) : ?>
                <div id="parcours" class="tab-pane " role="tabpanel">
                    <?php echo $this->partial('partial/parcours.phtml', ['entretien' => $entretien, 'agent' => $agent, 'parcours' => $parcours, 'fiche' => $ficheposte, 'options' => ['mode' => 'modification', 'modification' => true, 'droits' => $droits], 'source' => 'renseignerAction']); ?>
                </div>
            <?php endif; ?>
            <?php if ($displayAcquis === true) : ?>
            <div id="acquis" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/acquis.phtml', ['entretien' => $entretien, 'agent' => $agent, 'options' => ['modification' => true], 'source' => 'renseignerAction']); ?>
            </div>
            <?php endif; ?>

            <div id="avis" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/observation.phtml', ['entretien' => $entretien, 'observation' => $entretien->getObservationActive(), 'droits' => $droits, 'source' => 'renseignerAction']); ?>
            </div>

            <div id="validation" class="tab-pane " role="tabpanel">
                <?php echo $this->partial('partial/validation', ['entretien' => $entretien, 'source' => 'renseignerAction']); ?>
            </div>
            <div id="mails" class="tab-pane " role="tabpanel">

                <br/>
                <div>
                    <?php echo $this->mails($mails); ?>
                </div>
            </div>
        </div>
    </div>

</div>

<style>
    h3.categorie {
        border-bottom: 1px solid #31708f;
    }
</style>

<script>
    $(document).ready(function() {
        $('.datatable').DataTable( {
            // sorting: false,
            // paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "formulaire";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


