<?php

namespace Structure\Provider\Parametre;

class StructureParametres {

    const TYPE = 'STRUCTURE';

    const BLOC_GESTIONNAIRE =  'BLOC_GESTIONNAIRE';
    const BLOC_OBSERVATEUR =  'BLOC_OBSERVATEUR';
    const BLOC_CONTACT =  'BLOC_CONTACT';

    const AGENT_TEMOIN_STATUT = 'AGENT_TEMOIN_STATUT';
    const AGENT_TEMOIN_AFFECTATION = 'AGENT_TEMOIN_AFFECTATION';
    const AGENT_TEMOIN_EMPLOITYPE = 'AGENT_TEMOIN_EMPLOITYPE';
    const AGENT_TEMOIN_GRADE = 'AGENT_TEMOIN_GRADE';
    const AGENT_TEMOIN_CORPS = 'AGENT_TEMOIN_CORPS';

}