<?php

/**
 * @see \Autoform\Controller\ValidationController::afficherResultatAction()
 * @var Formulaire $formulaire
// * @var \Autoform\Entity\Db\Validation $validation
 * @var Formulaireinstance $instance
 * @var FormulaireReponse[] $fReponses
 * @var ValidationReponse[] $vReponses
 * @var string $url
 */

use Autoform\Entity\Db\Categorie;
use Autoform\Entity\Db\Champ;
use Autoform\Entity\Db\Formulaire;
use Autoform\Entity\Db\Formulaireinstance;
use Autoform\Entity\Db\FormulaireReponse;
use Autoform\Entity\Db\ValidationReponse;

?>

        <form method="post" action="<?php echo $url; ?>">
        <?php
            /** @var Categorie[] $categories */
            $categories = $formulaire->getCategories();
            $categories = array_filter($categories, function (Categorie $categorie) { return $categorie->estNonHistorise();});
            usort($categories, function (Categorie $a, Categorie $b) { return $a->getOrdre() - $b->getOrdre();});
        ?>

        <?php foreach ($categories as $categorie) : ?>

            <?php
                /** @var Champ[] $champs */
                $champs = $categorie->getChamps();
                $champs = array_filter($champs, function (Champ $champ) { return $champ->estNonHistorise();});
                usort($champs, function (Champ $a, Champ $b) { return $a->getOrdre() - $b->getOrdre();});

                $results = [];
                foreach ($champs as $champ) {
                    if (isset($fReponses[$champ->getId()]) && $fReponses[$champ->getId()]) $results[] = $fReponses[$champ->getId()];
                }
            ?>

            <?php if (!empty($champs) && !empty($results)) : ?>

                <h3> <?php echo $categorie->getLibelle(); ?> </h3>

                <?php foreach ($champs as $champ) : ?>
                    <?php if (isset($fReponses[$champ->getId()])) : ?>
                        <?php
                            $fReponse = isset($fReponses[$champ->getId()])?$fReponses[$champ->getId()]->getReponse():null;
                            $vReponse = isset($vReponses[$champ->getId()])?$vReponses[$champ->getId()]->getValue():null;
                            echo $this->champAsValidation()->render($champ, $fReponse, $vReponse); //$vReponse);
                        ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>

            <input type="submit" class="btn btn-primary" value="Enregistrer votre validation">
        </form>
