<?php

/**
 * @var \Autoform\Entity\Db\Validation[] $validations
 */

use Autoform\Provider\Privilege\ValidationPrivileges;

$canVoirValidation          = $this->isAllowed(ValidationPrivileges::getResourceId(ValidationPrivileges::AFFICHER));
$canEditerValidation        = $this->isAllowed(ValidationPrivileges::getResourceId(ValidationPrivileges::MODIFIER));
$canHistoriserValidation    = $this->isAllowed(ValidationPrivileges::getResourceId(ValidationPrivileges::HISTORISER));
$canDetruireValidation      = $this->isAllowed(ValidationPrivileges::getResourceId(ValidationPrivileges::DETRUIRE));

$this->headTitle('Index des validations');
?>

<h1 class="page-header">
    Index des validations
</h1>

<div class="main">
    <div class="alert alert-info">
        Il existe trois types de validation :
        <ol>
            <li> validation du SUMPPS ; </li>
            <li> validation du médecin ; </li>
            <li> validation de la composante. </li>
        </ol>
    </div>

    <p>
        <?php echo count($validations); ?> validations.
    </p>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th> Type </th>
                <th> Date </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($validations as $validation) : ?>
                <tr>
                    <td> <?php echo $validation->getType(); ?> </td>
                    <td> <?php echo $validation->getHistoModification()->format('d/m/Y à H:i'); ?> </td>
                    <td>
                        <?php if ($canVoirValidation) : ?>
                            <a href="<?php echo $this->url('autoform/validation/afficher-resultat', ['validation' => $validation->getId()],[], true); ?>">
                                <span class="icon voir" title="Examiner la validation"></span></a>
                        <?php else : ?>
                            <span class="icon voir" style="color:lightgray;"></span>
                        <?php endif; ?>

                        <?php if ($canEditerValidation) : ?>
                        <a href="<?php //echo $this->url('autoform/validation/afficher-validation', ['demande' => $validation->getDemande()->getId(), 'validation' => $validation->getId()],[], true); ?>">
                            <span class="icon editer" title="Éditer la validation"></span></a>
                        <?php else : ?>
                            <span class="icon editer" style="color:lightgray;"></span>
                        <?php endif; ?>

                        <?php if ($canVoirValidation) : ?>
                            <a href="<?php ///echo $this->url('autoform/validation/export-pdf', ['demande' => $validation->getDemande()->getId(), 'validation' => $validation->getId()], [], true); ?>">
                                <span class="icon pdf" title="Version PDF"></span></a>
                        <?php endif; ?>

                        <?php if ($canHistoriserValidation) : ?>
                            <?php if ($validation->estNonHistorise()) : ?>
                            <a href="<?php //echo $this->url('autoform/validation/historiser', ['demande' => $validation->getDemande()->getId(), 'validation' => $validation->getId()],[], true); ?>">
                                <span class="icon historiser" title="Historiser la validation"></span></a>
                            <?php else : ?>
                                <a href="<?php //echo $this->url('autoform/validation/restaurer', ['demande' => $validation->getDemande()->getId(), 'validation' => $validation->getId()],[], true); ?>">
                                    <span class="icon restaurer" title="restaurer la validation"></span></a>
                            <?php endif; ?>
                        <?php else : ?>
                            <?php if ($validation->estNonHistorise()) : ?>
                                <span class="icon historiser" style="color:lightgray;"></span>
                            <?php else : ?>
                                <span class="icon restaurer" style="color:lightgray;"></span>
                            <?php endif; ?>
                        <?php endif; ?>

                        <?php if ($canDetruireValidation) : ?>
                            <a href="<?php //echo $this->url('autoform/validation/detruire', ['demande' => $validation->getDemande()->getId(), 'validation' => $validation->getId()],[], true); ?>">
                                <span class="icon detruire" title="Détruire la validation"></span></a>
                        <?php else : ?>
                            <span class="icon detruire" style="color:lightgray;"></span>
                        <?php endif; ?>

                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>