<?php

$navigationHelper = $this->navigation('Laminas\Navigation\Formation');
$env = getenv('APPLICATION_ENV') ?: 'production';

?>

<script>
    function generateAdresse(name, domaine) {
        document.write("<a href=" + "mail" + "to:" + name + "@" + domaine + ">" + name + "@"+ domaine + "</a>");
    }
</script>

<?php echo $this->doctype(); ?>
<html lang="fr" id="mes-formations">
<head>
    <!-- Meta -->
    <meta charset="utf-8">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('description', '')
        ->appendHttpEquiv("X-UA-Compatible", "IE=edge,chrome=1") ?>
    <!-- Title -->
    <?php echo $this->headTitle("Mes formations")->setSeparator(' - ')->setAutoEscape(false) ?>
    <!-- Links -->
    <?php echo $this->headLink(array(
        'rel'   => 'shortcut icon',
        'type'  => 'image/vnd.microsoft.icon',
        'href'  => '//www.unicaen.fr/favicon.ico')) ?>
    <!-- Scripts -->
    <?php echo $this->headScript(); ?>
</head>
<!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>-->
<body class="<?php  echo getenv('APPLICATION_ENV'); ?>">

<!-- HEADER -------------------------------------->

<header>
    <nav id="navbar" class="navbar navbar-dark fixed-top navbar-expand-lg" role="navigation">
        <div class="container-fluid">
            <?php echo $this->appLink("Mes formations") ?>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menuPrincipalNavbar" aria-controls="menuPrincipalNavbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="menuPrincipalNavbar">

                <?php echo $navigationHelper
                    ->menu()
                    ->setUlClass('navbar-nav me-auto')
                    ->setPartial('layout/navigation-formation.phtml');
                ?>

                <div id="connexion" class="navbar-text text-end">
                    <?php echo $this->appConnection(); ?>
                </div>
                <!--<p class="navbar-text navbar-right"><?php /*echo $this->languageSelector(); */?></p>-->
            </div>
        </div>
    </nav>
</header>

<div style="display: flex; flex-wrap: nowrap;">
    <div id="contenu-principal" class="container">
        <?php echo $this->content; ?>
    </div>
</div>

<footer>
    <div>
        <?php $options = $this->navigation('navigation'); ?>
        <div id="comue"></div>

        <div id="menu-footer">
            <?php echo $this->navigation('navigation')->menuPiedDePage('Laminas\Navigation\Formation'); ?>
        </div>
        <img src="/img/republique-francaise-logo.svg" alt="Logo République française" class="footer-logo-republique-francaise" />

        <div id="etablissement"></div>
    </div>
</footer>


<?php echo $this->inlineScript(); ?>

</body>
</html>

<script>
    $(function () {
        $('[data-toggle="popover"]').popover({ html: true});
    });
    $(function () {
        $('[data-bs-toggle="tooltip"]').tooltip({});
    });
</script>