<?php

/**
 * @see ConfigurationController::gererCategorieAction()
 * @var CategoriePrivilege $categorie
 */

use UnicaenPrivilege\Entity\Db\CategoriePrivilege;
use UnicaenPrivilege\Entity\Db\Privilege;
use UnicaenPrivilege\Provider\Privilege\PrivilegePrivileges;

$this->headTitle('Gestion de la catégorie : ' . $categorie->getLibelle());

$canRetour              = $this->isAllowed(PrivilegePrivileges::getResourceId(PrivilegePrivileges::PRIVILEGE_VOIR));
$canEditerCategorie     = $this->isAllowed(PrivilegePrivileges::getResourceId(PrivilegePrivileges::PRIVILEGE_MODIFIER));
$canAjouterPrivilege    = $this->isAllowed(PrivilegePrivileges::getResourceId(PrivilegePrivileges::PRIVILEGE_AJOUTER));
$canEditerPrivilege     = $this->isAllowed(PrivilegePrivileges::getResourceId(PrivilegePrivileges::PRIVILEGE_MODIFIER));
$canDetruirePrivilege   = $this->isAllowed(PrivilegePrivileges::getResourceId(PrivilegePrivileges::PRIVILEGE_SUPPRIMER));
$canProvider            = $this->isAllowed(PrivilegePrivileges::getResourceId(PrivilegePrivileges::PRIVILEGE_VOIR));

?>

<h1 class="page-header">
    Gestion la catégorie <br/>
    <strong><?php echo $categorie; ?></strong>
</h1>

<div class="main">
    <div class="row">
        <div class="col-md-6">
            <?php if ($canRetour) : ?>
            <?php /** @see ConfigurationController::indexConfigurationCategorieAction()*/ ?>
            <a href="<?php echo $this->url('configuration-categorie', [], [], true); ?>" class="btn btn-primary action">
                <span class="icon retour"></span>
                Retour à l'index des catégories
            </a>
            <?php endif;?>

            <?php if ($canEditerCategorie) : ?>
            <?php /** @see ConfigurationController::modifierCategorieAction() */ ?>
            <a href="<?php echo $this->url('configuration-categorie/modifier', ['categorie' => $categorie->getId()], [], true); ?>" class="btn btn-primary action ajax-modal" data-event="modification">
                <span class="icon editer"></span>
                Éditer la catégorie
            </a>
            <?php endif;?>

            <?php if ($canAjouterPrivilege) : ?>
            <?php /** @see ConfigurationController::creerPrivilegeAction() */ ?>
            <a href="<?php echo $this->url('configuration-privilege/creer', ['categorie' => $categorie->getId()], [], true); ?>" class="btn btn-primary action ajax-modal" data-event="modification">
                <span class="icon ajouter"></span>
                Ajouter un privilège
            </a>
            <?php endif;?>

            <?php if ($canProvider) : ?>
                <?php /** @see ConfigurationController::providerAction() */ ?>
                <a href="<?php echo $this->url('configuration-categorie/provider', ['categorie' => $categorie->getId()], [], true); ?>" class="btn btn-primary  action ajax-modal">
                    <span class="icon csv"></span>
                    Générer le provider
                </a>
            <?php endif; ?>
        </div>

        <div class="col-md-6">

        <div class="panel panel-info">
            <div class=" panel-heading">
                <h2>Informations générales</h2>
            </div>
            <div class=" panel-body">
                <dl class="dl-horizontal">
                    <dt> Libellé</dt>
                    <dd> <?php echo $categorie->getLibelle(); ?></dd>
                    <dt> Code </dt>
                    <dd> <?php echo $categorie->getCode(); ?></dd>
                    <dt> Namespace </dt>
                    <dd> <?php echo $categorie->getNamespace(); ?></dd>
                    <dt> Ordre </dt>
                    <dd> <?php echo $categorie->getOrdre(); ?></dd>
                    <dt> #Privilège </dt>
                    <dd> <?php echo count($categorie->getPrivilege()); ?></dd>
                </dl>
            </div>
        </div>
        </div>
    </div>

    <h2>
        Privilèges
        <span class="badge">
            <?php echo count($categorie->getPrivilege()); ?>
        </span>
    </h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th> Libellé </th>
                <th> Code </th>
                <th> Ordre </th>
                <th> set? </th>
                <th> ok? </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php
                $privileges = $categorie->getPrivilege();
                usort($privileges, function(Privilege $a, Privilege $b) { return $a->getOrdre() > $b->getOrdre();} );
            ?>
            <?php foreach ($privileges as $privilege) : ?>
                <tr>
                    <td> <?php echo $privilege->getLibelle(); ?> </td>
                    <td> <?php echo $privilege->getCode(); ?> </td>
                    <td> <?php echo $privilege->getOrdre(); ?> </td>
                    <?php
                    $constant = '\\'.$privilege->getCategorie()->getNamespace().'\\'. $privilege->getCategorie()->getClassname() . '::' . strtoupper($privilege->getCode());
                    $value = defined($constant);
                    $content = ($value === true) ? eval("return ".$constant.";") : null;
                    ?>
                    <td>
                        <?php if ($value === true) : ?>
                            <span class="icon ok" style="color:darkgreen;" title="<?php echo " = '".$constant. "'"; ?>"></span>
                        <?php else : ?>
                            <span class="icon ko" style="color:darkred;" title="<?php echo " != '".$constant. "'"; ?>"></span>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($content === $privilege->getFullCode()) : ?>
                            <span class="icon ok" style="color:darkgreen;" title="<?php echo  " =  '" .$privilege->getFullCode(). "'" ?>"></span>
                        <?php else : ?>
                            <span class="icon ko" style="color:darkred;" title="<?php echo " != '" . $privilege->getFullCode(). "'"; ?>"></span>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if($canEditerPrivilege) : ?>
                            <?php /** @see ConfigurationController::modifierPrivilegeAction() **/ ?>
                            <a href="<?php echo $this->url('configuration-privilege/modifier', ['privilege' => $privilege->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Éditer le privilège [<?php echo htmlentities($privilege->getLibelle()); ?>]"></span></a>
                        <?php else: ?>
                            <span class="icon editer" style="color:lightgrey;"></span>
                        <?php endif; ?>
                        <?php if($canDetruirePrivilege) : ?>
                            <?php /** @see ConfigurationController::detruirePrivilegeAction() **/ ?>
                            <a href="<?php echo $this->url('configuration-privilege/detruire', ['privilege' => $privilege->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon detruire" title="Détruire le privilège [<?php echo htmlentities($privilege->getLibelle()); ?>]"></span></a>
                        <?php else: ?>
                            <span class="icon detruire" style="color:lightgrey;"></span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>