<?php

/**
 * @var ParcoursDeFormation[] $parcours
 * @var boolean[] $droits
 */

use Application\Entity\Db\ParcoursDeFormation;

$canAfficher = true;
$canModifier = true;
?>

<table class="datatable table table-condensed">
    <thead>
        <tr>
            <th> Libellé </th>
            <th> Références </th>
            <th> #Formation </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($parcours as $parcour) : ?>
            <tr <?php if ($parcour->estHistorise()) echo 'class="historise"'; ?>>
                <td>
                    <?php echo $parcour->getLibelle(); ?>
                    <?php if ($parcour->getDescription() !== null and trim($parcour->getDescription()) !== '') : ?>
                        <span class="icon information" title="<?php echo $parcour->getDescription(); ?>"></span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo $parcour->getReference(); ?>
                </td>
                <td>
                    <?php echo count($parcour->getFormations()); ?>
                </td>
                <td>
                    <?php if($canAfficher) : ?>
                        <a
                            <?php /** @see \Application\Controller\ParcoursDeFormationController::afficherAction() */?>
                            href="<?php echo $this->url('parcours-de-formation/afficher', ['parcours-de-formation' => $parcour->getId()], [], true); ?>"
                            class="ajax-modal"
                        >
                            <span class="icon voir" title="Afficher le parcours de formation"></span></a>
                    <?php endif; ?>
                    <?php if($canModifier) : ?>
                        <a
                            <?php /** @see \Application\Controller\ParcoursDeFormationController::modifierAction() */?>
                                href="<?php echo $this->url('parcours-de-formation/modifier', ['parcours-de-formation' => $parcour->getId()], [], true); ?>"
                                class="ajax-modal" data-event="modification"
                        >
                            <span class="icon editer" title="Modifier le parcours de formation"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>

</table>