<?php

/**
 * @see \Carriere\Controller\CorpsController::indexAction()
 * @var Corps[] $corps
 * @var array $repartition <corps_id, number>
 * @var bool $avecAgent
 */

use Agent\Entity\Db\AgentGrade;
use Carriere\Entity\Db\Corps;
use Carriere\Provider\Privilege\CorpsPrivileges;

$this->headTitle("Liste des corps");

$canLister = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_LISTER_AGENTS));
$canModifier = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_MODIFIER));

?>

<h1 class="page-header">
    Liste des corps
    <span class="badge">
        <?php if ($avecAgent) : ?>
            <?php echo count($dictionnaire); ?>
        <?php else : ?>
            <?php echo count($corps); ?>
        <?php endif; ?>
    </span>
</h1>
<div class="col-md-6 alert alert-info" style="margin-top: 1rem;">
    <span class="icon icon-refresh"></span>
    Données synchronisées
    <?php if ($avecAgent) : ?>
        <br>
        <span class="icon icon-information"></span>
        Seuls les corps avec au moins un agent·e sont présentés
    <?php endif; ?>
</div>


<table class="datatable table table-condensed" id="corps">
    <thead>
    <tr>
        <th class="col-md-6"> Libellé</th>
        <th class="col-md-1"> #Agent/Grade</th>
        <th class="col-md-1"> Catégorie</th>
        <th class="col-md-1"> Supérieur = Autorité</th>
        <th class="col-md-1"> Niveaux</th>
        <th class="col-md-2"> Action</th>
    </tr>
    </thead>
    <tbody>

    <?php foreach ($corps as $corp) : ?>
        <?php if (!$avecAgent OR (isset($dictionnaire[$corp->getId()]) and $dictionnaire[$corp->getId()] !== 0)) : ?>
            <tr>
                <td data-column-id="Libellé">
                    <span
                            title="<?php echo $corp->generateTooltip(); ?>"
                            data-bs-toggle="tooltip" data-bs-html="true"
                    >
                    <?php echo $corp->getLibelleLong(); ?>
                    </span>
                </td>
                <td data-column-id="#Agent/Grade">
                    <?php echo $dictionnaire[$corp->getId()]; ?>
                </td>
                <td cladata-column-idss="Catégorie">
                    <?php echo $corp->getCategorie(); ?>
                </td>
                <td data-column-id="Autorité = Supérieur">
                    <?php if ($corp->isSuperieurAsAutorite()) : ?>
                        <span class="text-success">
                            <span class="icon icon-checked"></span> Oui
                        </span>
                    <?php else : ?>
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span> Non
                        </span>
                    <?php endif; ?>
            &nbsp;       <?php if ($canModifier) : ?>
                    <?php /** @see \Carriere\Controller\CorpsController::toggleSuperieurAutoriteAction() */ ?>
                    <br>
                    <a href="<?php echo $this->url('corps/toggle-superieur-autorite', ['corps' => $corp->getId()], [], true); ?>"
                       class="action primary"
                    >
                        <span class="icon icon-refresh"></span>
                        Changer
                    </a>
                    <?php endif; ?>
                </td>
                <td data-column-id="Niveaux">
                        <?php echo $this->niveauEnveloppe($corp->getNiveaux()) ?>
                        <?php if ($canModifier) : ?>
                            <br>
                            <?php if ($corp->getNiveaux()) : ?>
                                <?php /**  @see \Carriere\Controller\CorpsController::modifierNiveauxAction() */ ?>
                                <a href="<?php echo $this->url('corps/modifier-niveaux', ['corps' => $corp->getId()], [], true); ?>"
                                   class="action primary ajax-modal" data-event="modification"
                                >
                                    <span class="icon icon-editer"></span>
                                    Modifier
                                </a>
                            <?php else : ?>
                                <?php /**  @see \Metier\Controller\MetierController::modifierNiveauxAction() */ ?>
                                <a href="<?php echo $this->url('corps/modifier-niveaux', ['corps' => $corp->getId()], [], true); ?>"
                                   class="action primary ajax-modal" data-event="modification"
                                >
                                    <span class="icon icon-ajouter"></span>
                                    Ajouter
                                </a>
                            <?php endif; ?>
                        <?php endif; ?>
                </td>
                <td data-column-id="Action">
                    <?php if ($canLister) : ?>
                        <a
                                <?php /** @see \Carriere\Controller\CorpsController::afficherAgentsAction() */ ?>
                                href="<?php echo $this->url('corps/afficher-agents', ['corps' => $corp->getId()], ['fragment' => 'corps'], true); ?>"
                                class="ajax-modal action secondary" data-event="modification"
                        >
                            <span class="icon icon-users"></span>
                            Lister les agents
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('table#corps').DataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [5], orderable: false}
            ]
        });
    });
</script>