<?php

/**
 * @see \Carriere\Controller\CorpsController::indexAction()
 * @var Corps[] $corps
 */

use Carriere\Entity\Db\Corps;
use Carriere\Provider\Privilege\CorpsPrivileges;

$this->headTitle("Liste des corps");

$canAfficher = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_AFFICHER));
$canModifier = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_MODIFIER));
?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Liste des corps
            <span class="badge">
                <?php echo count($corps); ?>
            </span>
        </h1>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
            <span class="icon icon-synchroniser"></span>
            Synchoniser depuis Octopus
        </div>
    </div>
</div>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th style="width:70%;"> Libellé</th>
        <th> #Agent/Grade </th>
        <th> Catégorie </th>
        <th> Niveaux </th>
        <th style="width:3rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($corps as $corp): ?>
        <tr>
            <td>
                <span
                    title="<?php echo $corp->generateTooltip(); ?>"
                    data-bs-toggle="tooltip" data-bs-html="true"
                >
                <?php echo $corp->getLibelleLong(); ?>
                </span>
            </td>
            <td> <?php echo count($corp->getAgentGrades()); ?> </td>
            <td> <?php echo $corp->getCategorie(); ?> </td>
            <td>
                <?php echo $this->niveauEnveloppe($corp->getNiveaux()) ?>
                <?php if ($canModifier) : ?>
                    <?php if ($corp->getNiveaux()) : ?>
                        <?php /**  @see \Carriere\Controller\CorpsController::modifierNiveauxAction() */ ?>
                        <a href="<?php echo $this->url('corps/modifier-niveaux', ['corps' => $corp->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-editer"></span></a>
                    <?php else : ?>
                        <?php /**  @see \Metier\Controller\MetierController::modifierNiveauxAction() */ ?>
                        <a href="<?php echo $this->url('corps/modifier-niveaux', ['corps' => $corp->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-ajouter"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Carriere\Controller\CorpsController::afficherAgentsAction() */ ?>
                        href="<?php echo $this->url('corps/afficher-agents', ['corps' => $corp->getId()], ['fragment' => 'corps'], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                                        <span class="icon icon-voir" data-bs-toggle="tooltip" data-bs-html="true"
                                              title="Afficher les agents ayant ce corps"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('.datatable').DataTable({
            paging: false,
        });
    });
</script>