<?php

/**
 * @see \FicheMetier\Controller\GraphiqueController::graphiqueApplicationsAction()
 * @see \FicheMetier\Controller\GraphiqueController::graphiqueCompetencesAction()
 * @var string[] $label
 * @var array $values
 * @var Agent $agent
 * @var Niveau[] $niveaux
 */

use Application\Entity\Db\Agent;
use Element\Entity\Db\Niveau;

?>

<!--<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>-->

<?php if ($agent) : ?>
    <?php echo $agent->getDenomination(); ?>
<?php else: ?>
    Aucun agent
<?php endif; ?>
<canvas id="myChart" style=""></canvas>
<script>
    let ctx = document.getElementById('myChart').getContext('2d');
    let myChart = new Chart(ctx, {
        type:"radar",
        data: {
            labels: [<?php foreach ($label as $element) {echo '"'.$element .'",';} ?>
            ],
            datasets: [
                <?php foreach ($values as $value) : ?>
                    {
                        label: "<?php echo $value['title']; ?>",
                        data: [<?php foreach ($value['values'] as $element) {echo $element .',';} ?>],
                        backgroundColor: "rgba(<?php echo $value['color']; ?>,0.1)",
                        borderColor: "rgba(<?php echo $value['color']; ?>,0.8)",
                    },
                <?php endforeach; ?>
            ],
        },
        options: {
            scale: {
                ticks: {
                    min: 0,
                    max: <?php $maxKey = array_key_last($niveaux); echo $maxKey; ?>,
                    stepSize: 1,
                    callback: function(val) {
                        <?php
                            $maxKey = array_key_last($niveaux);
                            $labels = [];
                            for ($key = 0; $key <= $maxKey; $key++) {
                                if (isset($niveaux[$key])) { $labels[] = $niveaux[$key]; } else { $labels[] = ''; }
                            }
                        ?>
                        let niveaux = [<?php echo implode(",",array_map(function ($a) { return "'".$a."'";}, $labels)); ?>];
                        console.log(niveaux);
                        return niveaux[val];
                    },
                },
            },
        },
    });
</script>