<?php

/**
 * @see StructureController::afficherAction()
 * @var Structure $structure
 * @var Structure[] $filles
 * @var AgentMissionSpecifique[] $missions
 */

use Application\Entity\Db\AgentMissionSpecifique;
use Application\Entity\Db\Structure;

$this->headTitle("Affichage de la structure : " . $structure->getLibelleLong());

$canAfficheFichePoste = true;
$canAfficheAffectation = true;
?>

<h1 class="page-header">
    <strong> <?php echo $structure->getLibelleLong(); ?> </strong> <br/>
    <?php echo $structure->getType(); ?>
</h1>

<div class="main">

    <h2>
        Description
    </h2>
    <?php echo $structure->getDescription(); ?>

   <div class="row">
        <div class="col-md-6">
            <h2> Structure mère </h2>
            <?php if ($structure->getParent() !== null) :?>
                <ul>
                    <li>
                        <a href="<?php echo $this->url('structure/afficher', ['structure' => $structure->getParent()->getId()], [] , true); ?> ">
                            <?php echo $structure->getParent()->getLibelleCourt(); ?>
                            -
                            <?php echo $structure->getParent()->getLibelleLong(); ?>
                        </a></li>
                </ul>
            <?php else : ?>
                Aucune structure mère
            <?php endif; ?>
            <h2>
                Structures filles
                <span class="badge">
                    <?php echo count($filles); ?>
                </span>
            </h2>
            <ul>
                <?php foreach ($filles as $enfant) : ?>
                    <li>
                        <a href="<?php echo $this->url('structure/afficher', ['structure' => $enfant->getId()], [] , true); ?> ">
                            <?php echo $enfant->getLibelleCourt(); ?>
                            -
                            <?php echo $enfant->getLibelleLong(); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="col-md-6">
            <h2>
                Gestionnaires
                <span class="badge"><?php echo count($structure->getGestionnaires()); ?></span>
            </h2>
            <ul>
                <?php foreach ($structure->getGestionnaires() as $gestionnaire) : ?>
                    <li> <?php echo $gestionnaire->getDisplayName(); ?> </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <?php echo $this->partial('partial/missions-specifiques', ['structure' => $structure, 'missions' => $missions]); ?>

    <h2>
        Postes
        <span class="badge"><?php echo count($structure->getPostes()); ?></span>
    </h2>

    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Agent </th>
            <th> Poste </th>
            <th> Action </th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($structure->getPostes() as $poste): ?>
            <tr>
                <td> <?php //echo $poste->getFichePoste()->getAgent()->getDenomination(); ?> </td>
                <td> <?php //echo $poste->getFichePoste()->getLibelle(); ?> </td>
                <td>
                    <?php if ($canAfficheFichePoste) : ?>
                    <a <?php /** @see FichePosteController::afficherAction() */ ?>
                        href="<?php //echo $this->url('fiche-poste/afficher', ['fiche-poste' => $poste->getFichePoste()->getId()], [], true); ?>"
                        class="ajax-modal"
                    >
                        <span class="icon voir" title="Voir la fiche de poste"></span>
                    </a>
                    <?php else : ?>
                        <span class="icon voir" style="color:lightgray;"></span>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>



</div>

<script>
    $("body").on("modification", function (event) {
        event.div.modal('hide');
        window.location.reload();
    });
</script>

