<?php

use Application\Provider\Privilege\StructurePrivileges;

$this->headTitle("Index des structures");

/**
 * @var Application\Entity\Db\Structure[] $structures
 */

$canGestionnaire    = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::GESTIONNAIRE));
?>

<h1 class="page-header">
    Index des structures
</h1>

<div class="main">

    <h2>
        Structures ouvertes
        <span class="badge">
            <?php echo count($structures); ?>
        </span>
    </h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th> Code </th>
                <th> Libellé court </th>
                <th> Type </th>
                <th> Gestionnaire </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($structures as $structure) : ?>
                <tr>
                    <td> <?php echo $structure->getCode(); ?> </td>
                    <td>
                        <?php echo $structure->getLibelleCourt(); ?>
                        <?php if ($structure->getLibelleLong()): ?>
                            <sup><span class="icon information" title="<?php echo $structure->getLibelleLong(); ?>"></span></sup>
                        <?php endif; ?>
                    </td>
                    <td> <?php echo $structure->getType(); ?> </td>
                    <td>
                        <?php if (count($structure->getGestionnaires())) : ?>
                            <?php
                            $text = "";
                            foreach ($structure->getGestionnaires() as $gestionnaire) $text .= $gestionnaire->getDisplayName()."\n";
                            ?>
                            <span title="<?php echo $text; ?>">
                                <?php echo count($structure->getGestionnaires()); ?>
                                <i class="fas fa-user"></i>
                            </span>
                        <?php else : ?>
                            <strong style="color:darkred;">Aucun</strong>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($canGestionnaire) : ?>
                            <a
                                    href="<?php echo $this->url('structure/ajouter-gestionnaire', ['structure' => $structure->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    data-event="modification"
                            >
                                <span class="icon ajouter-user"   title="Ajouter un gestionnaire"></span></a>
                            <a
                                    href="<?php echo $this->url('structure/retirer-gestionnaire', ['structure' => $structure->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    data-event="modification"
                            >
                                <span class="icon retirer-user"   title="Retirer un gestionnaire"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

