<?php

/**
 * @var Application\Entity\Db\Structure $structure
 * @var Utilisateur\Entity\Db\User[] $gestionnaires
 */

$this->headTitle("Retirer un gestionnaire")
?>

<?php if ($structure) : ?>
    <form method="post" action="<?php echo $this->url('structure/retirer-gestionnaire', ['structure' => $structure->getId()], [] ,true); ?>">
        <table><tr><td>
            <select id="gestionnaire" name="gestionnaire" style="width:100%;" class="selectpicker" data-live-search="true">
                <option value=""> Sélectionner un gestionnaire ...</option>
                <?php foreach ($gestionnaires as $gestionnaire) : ?>
                    <option value="<?php echo $gestionnaire->getId(); ?>"
                            data-content="<?php echo $gestionnaire->getDisplayName(); ?> &nbsp; <span class='badge badge-success'><?php echo $gestionnaire->getEmail(); ?></span>"
                    >
                        <?php echo $gestionnaire->getDisplayName(); ?>
                        <?php echo $gestionnaire->getEmail(); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </td><td>
            <input type="submit" value="Retirer ce gestionnaire" class="action btn btn-primary">
        </td></tr></table>
    </form>
<?php endif; ?>

<script>
    $('select').selectpicker();
</script>
