<?php

/**
 * @see \Application\Controller\FicheProfilController::ajouterAction()
 * @see \Application\Controller\FicheProfilController::modifierAction()
 * @var string $type (soit 'ajout' ou 'modification')
 * @var Structure $structure
 * @var FichePoste[] $fichespostes
 * @var FicheProfilForm $form
 */

use Application\Entity\Db\FichePoste;
use Application\Entity\Db\Structure;
use Application\Form\FicheProfil\FicheProfilForm;

/**
'contrat'       => $object->getContrat(),
'remuneration'  => $object->getRenumeration(),
 */
?>

<h1 class="page-header"> Profil de recrutement </h1>

<?php echo $this->form()->openTag($form); ?>
<div>
    <h2> Description du profil de recrutement </h2>
    <?php echo $this->formControlGroup($form->get('structure')); ?>
    <?php echo $this->formControlGroup($form->get('structure_id')); ?>
    <?php echo $this->formControlGroup($form->get('ficheposte')); ?>
    <?php echo $this->formControlGroup($form->get('date')); ?>
    <?php echo $this->formControlGroup($form->get('lieu')); ?>
    <?php echo $this->formControlGroup($form->get('vacance_emploi')); ?>
</div>
<div>
    <h2> Description du contexte </h2>
    <?php echo $this->formControlGroup($form->get('contexte')); ?>
    <?php echo $this->formControlGroup($form->get('mission')); ?>
    <?php echo $this->formControlGroup($form->get('niveau')); ?>
    <?php echo $this->formControlGroup($form->get('contraintes')); ?>
</div>
<div>
    <h2> Contrat et rénumération </h2>
    <div id="not_vacance">
        <?php echo $this->formControlGroup($form->get('contrat')); ?>
        <?php echo $this->formControlGroup($form->get('renumeration')); ?>
    </div>
    <div id="is_vacance">
        Ce profil de recrutement est une vacance d'emploi.
    </div>
</div>
<br/>

<?php echo $this->formControlGroup($form->get('creer')); ?>
<?php echo $this->form()->closeTag(); ?>

<?php //echo $this->form($form); ?>

<script>
    $(document).ready(function() {
        tinymce.remove();
        tinymce.init({
            selector: '.tinymce',
            toolbar: 'removeformat | bold italic underline | bullist numlist',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck : true,
            branding: false,
            menu: {},
        });
    });

    function checkVacance() {
        let isChecked = $('input#vacance_emploi').prop('checked');
        // alert(isChecked);
        if (isChecked) {
            $('div#is_vacance').show();
            $('div#not_vacance').hide();
        } else {
            $('div#is_vacance').hide();
            $('div#not_vacance').show();
        }
    }
    $(document).ready(checkVacance);
    $('input#vacance_emploi').on('change', checkVacance);

    $('select').selectpicker();
</script>