<?php

/**
 * @var array $params
 * @var array $etats
 */

use Formation\Entity\Db\Formation;
use UnicaenApp\Form\Element\SearchAndSelect;

?>

<div class="card">
    <div class="card-header bg-default">
        <span class="icon icon-filtrer"></span>
        Filtrage des demandes de stages hors plan de formation
    </div>
    <div class="card-body">
        <form id="filter" method="get" action="<?php echo $this->url(); ?>">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-4">
                                <?php
                                /** @see \Formation\Controller\DemandeExterneController::rechercherAgentAction() */
                                $agentF = new SearchAndSelect('agent', ['label' => "Agent :"]);
                                $agentF
                                    ->setAutocompleteSource($this->url('formation/demande-externe/rechercher-agent'))
                                    ->setSelectionRequired(true)
                                    ->setAttributes([
                                        'id' => 'agent',
                                        'placeholder' => "Nom de l'agent ...",
                                    ]);
                                ?>
                                <?php echo $this->formControlGroup($agentF); ?>
                        </div>
                        <div class="col-md-4">
                            <?php
                            /** @see \Formation\Controller\DemandeExterneController::rechercherOrganismeAction() */
                            $organismeF = new SearchAndSelect('organisme', ['label' => "Organisme :"]);
                            $organismeF
                                ->setAutocompleteSource($this->url('formation/demande-externe/rechercher-organisme'))
                                ->setSelectionRequired(true)
                                ->setAttributes([
                                    'id' => 'organisme',
                                    'placeholder' => "Nom de l'organisme ...",
                                ]);
                            ?>
                            <?php echo $this->formControlGroup($organismeF); ?>
                        </div>
                        <div class="col-md-4">
                            <label for="annee">Année de la demande :  </label>
                            <select id="annee" name="annee" class="selectpicker">
                                <option value="">Peu importe</option>
                                <?php for ($annee = 2022 ; $annee <= Formation::getAnnee() ; $annee++) : ?> <!-- todo nope -->
                                    <option value="<?php echo $annee; ?>"><?php echo $annee; ?>/<?php echo $annee+1; ?></option>
                                <?php endfor; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="etat">État :</label>
                            <select id="etat" name="etat" class="form-control selectpicker show-tick" data-live-search="false">
                                <option value=""> Tous les états </option>
                                <?php foreach($etats as $etat) : ?>
                                    <option
                                            value="<?php echo $etat->getId(); ?>"
                                            data-content='<?php  echo $this->etattype($etat); ?> <?php echo str_replace("'", "&apos;", $etat->getLibelle()); ?>'
                                        <?php if ($etat->getId() == $params['etatId']) echo " selected "; ?>
                                    >
                                        <?php echo $etat->getLibelle(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="historise">Demandes historisées :  </label>
                            <select id="historise" name="historise" class="selectpicker">
                                <option value="">Peu importe</option>
                                <option value="1">Oui</option>
                                <option value="0">Non</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="pull-right">
                        <button type="button" id="filter" class="btn btn-primary filter-action">
                            <span class="icon icon-filtrer" aria-hidden="true"></span> Filtrer
                        </button>
                        <br/>
                        <button type="button" id="reset" class="btn btn-primary filter-action">
                            <span class="icon icon-gommer" aria-hidden="true"></span> R.A.Z.
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    $('button#reset').click(function (e) {
        e.preventDefault();
        window.location = '?';
    });
    $('button#filter').click(function () {
        $('form#filter').submit();
    });

    <?php if ($params['agent'] !== null) :?>
    $('input[name="agent[label]').val(" <?php echo $params['agent']->getDenomination(); ?> ");
    $('input[name="agent[id]').val("<?php echo $params['agent']->getId(); ?>");
    <?php endif; ?>

    <?php if ($params['organisme'] !== null) :?>
    $('input[name="organisme[label]').val(" <?php echo $params['organisme']; ?> ");
    $('input[name="organisme[id]').val("<?php echo $params['organisme']; ?>");
    <?php endif; ?>

    <?php if (isset($params['etat'])) :?>
    $('select#etat option[value=<?php echo $params['etat']->getId(); ?>]').prop('selected', true);
    <?php endif; ?>
    <?php if (isset($params['annee'])) :?>
        $('select#annee option[value=<?php echo $params['annee']; ?>]').prop('selected', true);
    <?php endif; ?>
    <?php if (isset($params['historise'])) :?>
        $('select#historise option[value=<?php echo $params['historise']; ?>]').prop('selected', true);
    <?php endif; ?>
</script>