<?php

/**
 * @var ChampForm $form
 */

use Autoform\Entity\Db\Champ;
use Autoform\Form\Champ\ChampForm;

?>

<?php echo $this->form($form); ?>

<span class="infos" id="<?php echo Champ::TYPE_CUSTOM; ?>">
    <strong>Multiples champs parametrable</strong>
    <br/>
    Le libellé sera utilisé comme entête du champ.
    Les élements sont à renseigner dans la partie option et séparer d'un ';'.
    Les types d'élément connus sont :
    <ul>
        <li> texte court : texte court|Le libellé du texte court ; </li>
        <li> texte long : texte long|Le libellé du texte court ; </li>
        <li> select : select|Le libellé du select|option 1|option 2| ... . </li>
    </ul>
</span>


<script>
    $(document).ready(function() {
        $("span.infos").hide();

        let selected = $('select#type option:selected').val();
        $("span#"+ selected).show();
    });

    $('select#type').change(function() {
        let selected = $('select#type option:selected').val();
        alert("changes !" + selected);

        $("span.infos").hide();
        $("span#"+ selected).show();
    });
</script>