<?php

/**
 * @see \Application\Controller\FichePosteController::modifierRepartitionAction()
 * @var FichePoste $ficheposte
 * @var FicheTypeExterne $fichetype
 * @var Domaine[] $domaines
 * @var array $repartitions
*/
use Metier\Entity\Db\Domaine;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\FicheTypeExterne;

?>

<p>
    Indiquez la répartition entre chaque domaine ? <br/>
    <u>N.B.</u>: la somme des quotités doit être égale à 100%.
</p>

<br/>

<form method="post" action="<?php echo $this->url("fiche-poste/modifier-repartition", ['fiche-poste' => $ficheposte->getId(), 'fiche-type' => $fichetype->getId()], [], true); ?>">
    <table>
    <?php foreach ($domaines as $domaine) : ?>
        <tr>
            <td style="width:40%;">
                <?php echo $domaine->getLibelle(); ?>
                <?php echo $this->typefonction($domaine); ?> :
            </td>
            <td style="width:40%;">
                <select id="<?php echo $domaine->getId(); ?>" name="<?php echo $domaine->getId(); ?>" class="form-control">
                    <?php for($valeur = 0 ; $valeur <= 100; $valeur += 10) : ?>
                        <option value="<?php echo $valeur; ?>" <?php if ($valeur == $repartitions[$domaine->getId()]) echo " selected "; ?>> <?php echo $valeur; ?>% </option>
                    <?php endfor; ?>
                </select>
            </td>
        </tr>
        <?php endforeach; ?>
        <tr><td></td><td>&nbsp;</td></tr>
        <tr><td></td><td>
    <input type="submit" class="btn btn-primary" value="Enregistrer"/>
            </td></tr>
    </table>
</form>

<script>
    $('select').selectpicker();
</script>