<?php

/**
 * @var EntretienProfessionnel $entretien
 * @var Agent $agent
 * @var array $options
 * @var string $source
 */

use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;

$canVoir        = $this->isAllowed($agent, AgentPrivileges::AGENT_ACQUIS_AFFICHER);
$canAjouter     = $this->isAllowed($agent, AgentPrivileges::AGENT_ACQUIS_MODIFIER);
$canModifier    = $this->isAllowed($agent, AgentPrivileges::AGENT_ACQUIS_MODIFIER);
$canHistoriser  = $this->isAllowed($agent, AgentPrivileges::AGENT_ACQUIS_MODIFIER);
$canDetruire    = $this->isAllowed($agent, AgentPrivileges::AGENT_ACQUIS_MODIFIER);
$canValider     = $this->isAllowed($agent, AgentPrivileges::AGENT_ACQUIS_MODIFIER);

$canValiderAgent        = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_AGENT);
$canValiderResponsable  = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_RESPONSABLE);
$canValiderDrh          = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_DRH);
$canRenseigner = ($canValiderDrh OR $canValiderResponsable OR $canValiderAgent);

$droits = [
    'afficher' => $canVoir,
    'ajouter' => $canAjouter,
    'modifier' => $canModifier,
    'historiser' => $canHistoriser,
    'detruire' => $canDetruire,
    'valider' => $canValider,
];

$options = [];
$options['mode'] = 'modification';
$options['modification'] = $canModifier;
$options['droits'] = $droits;
$options['retour'] = $this->url('entretien-professionnel/acceder', ['entretien' => $entretien->getId()], ['fragment' => 'acquis'], true);
$options['actions'] = [
    'afficher' => true, 'ajouter' => $canAjouter, 'modifier' => $canModifier, 'supprimer' => $canDetruire, 'valider' => $canValider
];
?>

<h2 class="page-header-tab"> Acquis de l'agent </h2>


<!-- APPLICATION ------------------------------------------------------------------------------------------------------>
<?php echo $this->applicationBloc($agent->getApplicationDictionnaire(), $agent, ['texte' => true]);?>

<!-- COMPETENCE ------------------------------------------------------------------------------------------------------->
<?php echo $this->competenceBloc($agent->getCompetenceDictionnaire(), $agent, ['texte' => true]);?>

<!-- FORMATION ------------------------------------------------------------------------------------------------------->
<?php echo $this->formationBloc($agent->getFormationDictionnaire(), $agent, $options); ?>
