<?php

/**
 * @var EntretienProfessionnel $entretien
 * @var ParcoursDeFormation $parcours
 * @var User $connectedUser
 * @var array $options
 * @var string $source
 * @var FormulaireInstance $cref
 */

use Application\Entity\Db\ParcoursDeFormation;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use EntretienProfessionnel\Provider\Validation\EntretienProfessionnelValidations;
use UnicaenAuthentification\Service\User;
use UnicaenAutoform\Entity\Db\FormulaireInstance;


$canAfficher = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_AFFICHER);
$canRenseigner = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_RENSEIGNER);

$retour = $this->url('entretien-professionnel/acceder', ['entretien' => $entretien->getId()], ['force_canonical' => false, 'fragment' => 'formation'], true);

$now = new DateTime();
$date = $entretien->getMaxSaisiEntretien();

$validationResponsable = $entretien->getValidationActiveByTypeCode(EntretienProfessionnelValidations::VALIDATION_RESPONSABLE);

$isAgent = $entretien->getAgent()->getUtilisateur() === $connectedUser;
$date_depassee = (($isAgent) AND ($now > $date));
$agent  = $entretien->getAgent();
?>

<h2 class="page-header-tab"> Compte-rendu d'entretien de formation </h2>

<h3> Formations suivies durant la période de la campagne (<?php echo $entretien->getCampagne()->getAnnee(); ?>)</h3>

<?php echo $this->partial("partial/formations-suivies-campagne", ["entretien" => $entretien, 'formations' => $agent->getFormationListe()]); ?>


<?php
    $data = $cref->buildResponseDictionnary();
?>


<?php if ($canRenseigner && $validationResponsable === null) : ?>
    <?php
    /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::accederAction(); */
    $retour = $this->url('entretien-professionnel/acceder', ['entretien' => $entretien->getId()], ['force_canonical' => false, 'fragment' => 'formations'], true);
    /** @see  \UnicaenAutoform\Controller\FormulaireController::afficherFormulaireAction() */
    $url = $this->url('autoform/formulaire/afficher-formulaire', ['formulaire' => $cref->getFormulaire()->getId(), 'instance' => $cref->getId()], ['query' => ['retour' => $retour], 'force_canonical' => false], true);

    echo $this->instanceAsFormulaire()->render($cref, $url, $data);
    ?>
<?php else : ?>
    <?php if ($canAfficher) : ?>
        <?php echo $this->instanceAsText()->render($cref); ?>
    <?php else : ?>
        <div class="alert alert-danger">
            Vous ne pouvez pas saisir le formulaire d'entretien de formation.
        </div>
    <?php endif; ?>
<?php endif; ?>
