<?php

/**
 * @var EntretienProfessionnel $entretien
 * @var User $connectedUser
 * @var array $options
 * @var string $source
 * @var FormulaireInstance $cref
 * @var RoleInterface $role
 */

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Etat\EntretienProfessionnelEtats;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use EntretienProfessionnel\Provider\Validation\EntretienProfessionnelValidations;
use UnicaenAuthentification\Service\User;
use UnicaenAutoform\Entity\Db\FormulaireInstance;
use UnicaenUtilisateur\Entity\Db\RoleInterface;


$canAfficher = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_AFFICHER);
$canRenseigner = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_RENSEIGNER);

$retour = $this->url('entretien-professionnel/acceder', ['entretien' => $entretien->getId()], ['force_canonical' => false, 'fragment' => 'formation'], true);

$now = new DateTime();
$date = $entretien->getMaxSaisiEntretien();

$validationResponsable = $entretien->getValidationActiveByTypeCode(EntretienProfessionnelValidations::VALIDATION_RESPONSABLE);

$isAgent = $entretien->getAgent()->getUtilisateur() === $connectedUser;
$date_depassee = (($isAgent) AND ($now > $date));
$agent  = $entretien->getAgent();
?>

<h2 class="page-header-tab"> Compte-rendu d'entretien de formation </h2>

<h3> Formations suivies durant la période de la campagne (<?php echo $entretien->getCampagne()?$entretien->getCampagne()->getAnnee():"Sans campagne"; ?>)</h3>

<?php
    $data = $cref->buildResponseDictionnary();
?>

<?php if ($this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_REINITIALISER)) : ?>
    <?php if ($entretien->getFormationInstance()->getFormulaire()->getId() !== $entretien->getCampagne()->getFormulaireCREF()->getId()) : ?>
        <div class="alert alert-danger">
            Le formulaire du CREP a changé depuis la création de l'entretien professionnel.

            <br>
            Debug :
            <ul>
                <li>Entretien Id: <?php echo $entretien->getFormationInstance()->getFormulaire()->getId(); ?> Code:<?php echo $entretien->getFormulaireInstance()->getFormulaire()->getCode(); ?></li>
                <li>Campagne Id:<?php echo $entretien->getCampagne()->getFormulaireCREP()->getId(); ?> Code:<?php echo $entretien->getCampagne()->getFormulaireCREP()->getCode(); ?></li>
            </ul>
        </div>
    <?php endif; ?>
    <?php if ($entretien->getFormationInstance()->getHistoModification() > $entretien->getCampagne()->getFormulaireCREF()->getHistoModification()) : ?>
        <div class="alert alert-danger">
            Le formulaire du CREF a été mis à jour depuis la création de l'entretien professionnel.

            <br>
            Debug :
            <ul>
                <li>Entretien Id: <?php echo $entretien->getFormationInstance()->getHistoModification()->format('d/m/Y H:i:s'); ?> </li>
                <li>Campagne Id:<?php echo $entretien->getCampagne()->getFormulaireCREF()->getHistoModification()->format('d/m/Y H:i:s'); ?> </li>
            </ul>
        </div>
    <?php endif; ?>


    <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::reinitialiserAction() */ ?>
    <a href="<?php echo $this->url('entretien-professionnel/reinitialiser',['entretien-professionnel' => $entretien->getId(), 'formulaire' => 'CREF'],[], true); ?>"
       class="btn btn-warning ajax-modal" data-event="modification"
    >
        <span class="icon icon-refresh"></span>
        Remise à zéro et réapplication des copies pour le CREF
    </a>
<?php endif; ?>

<?php if ($canRenseigner) : ?>

    <?php
    /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::accederAction(); */
    $retour = $this->url('entretien-professionnel/acceder', ['entretien' => $entretien->getId()], ['force_canonical' => false, 'fragment' => 'formations'], true);
    /** @see  \UnicaenAutoform\Controller\FormulaireController::afficherFormulaireAction() */
    $url = $this->url('autoform/formulaire/afficher-formulaire', ['formulaire' => $cref->getFormulaire()->getId(), 'instance' => $cref->getId()], ['query' => ['retour' => $retour], 'force_canonical' => false], true);

    echo $this->instanceAsFormulaire()->render($cref, $url, $data, ['validation-floating' => true]);
    ?>
<?php else : ?>
    <?php if ($canAfficher) : ?>
        <?php echo $this->instanceAsText()->render($cref, $entretien->getDateEntretien()); ?>

        <?php if ($role->getRoleId() === Agent::ROLE_AGENT AND  $entretien->isEtatActif(EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTATION)) : ?>
            <div class="alert alert-info">
                <strong>
                    <span class="icon icon-information"></span>
                    Le compte-rendu n'est pas encore disponible.
                </strong>
                <p>
                    Vous ne pouvez pas saisir le formulaire d'entretien de formation,
                    car l'agent·e (<?php echo $entretien->getAgent()->getDenomination(); ?>) n'a pas encore accepté celui-ci.
                </p>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
