<?php

use EntretienProfessionnel\Entity\Db\Campagne;
use UnicaenApp\Form\Element\SearchAndSelect;
use UnicaenEtat\Entity\Db\Etat;

/**
 * @var Etat[] $etats;
 * @var Campagne[] $campagnes
 *
 * @var array $params
 */

?>

<?php
//var_dump($params);
//var_dump($params['structure']->getLibelleLong());
?>

<br/>

<div class="card card-default">
    <div class="card-header">
        <span class="icon icon-filtrer"></span>
        Filtre des entretiens professionnels
    </div>
    <div class="card-body">
        <form method="get" id="filtre" action="<?php echo $this->url(); ?>">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-4">
                            <?php
                            /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::rechercherStructureAction() */
                            $structureF = new SearchAndSelect('structure-filtre', ['label' => "Structure :"]);
                            $structureF
                                ->setAutocompleteSource($this->url('entretien-professionnel/rechercher-structure'))
                                ->setSelectionRequired(true)
                                ->setAttributes([
                                    'id' => 'structure-filtre',
                                    'placeholder' => "Nom de la structure ...",
                                ]);
                            ?>
                            <?php echo $this->formControlGroup($structureF); ?>
                        </div>
                        <div class="col-md-4">
                            <?php
                            /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::rechercherAgentAction() */
                            $agentF = new SearchAndSelect('agent-filtre', ['label' => "Agent :"]);
                            $agentF
                                ->setAutocompleteSource($this->url('entretien-professionnel/rechercher-agent'))
                                ->setSelectionRequired(true)
                                ->setAttributes([
                                    'id' => 'agent-filtre',
                                    'placeholder' => "Nom de l'agent ...",
                                ]);
                            ?>
                            <?php echo $this->formControlGroup($agentF); ?>

                        </div>
                        <div class="col-md-4">
                            <?php
                            /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::rechercherResponsableAction() */
                            $agentF = new SearchAndSelect('responsable-filtre', ['label' => "Responsable :"]);
                            $agentF
                                ->setAutocompleteSource($this->url('entretien-professionnel/rechercher-responsable'))
                                ->setSelectionRequired(true)
                                ->setAttributes([
                                    'id' => 'responsable-filtre',
                                    'placeholder' => "Nom du resposable ...",
                                ]);
                            ?>
                            <?php echo $this->formControlGroup($agentF); ?>
                        </div>
                        <div class="col-md-4">
                            <label for="campagne">Campagne :</label>
                            <select id="campagne" name="campagne" class="form-control selectpicker show-tick" data-live-search="false">
                                <option value=""> Toutes les campagnes </option>
                                <?php foreach($campagnes as $campagne) : ?>
                                    <option value="<?php echo $campagne->getId(); ?>">
                                        <?php echo $campagne->getAnnee(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                        <label for="etat">État :</label>
                        <select id="etat" name="etat" class="form-control selectpicker show-tick" data-live-search="false">
                            <option value=""> Tous les états </option>
                            <?php foreach($etats as $etat) : ?>
                                <option
                                        value="<?php echo $etat->getId(); ?>"
                                        data-content='<?php  echo $this->etatbadge($etat); ?> <?php echo str_replace("'", "", $etat->getLibelle()); ?>'
                                >
                                    <?php echo $etat->getLibelle(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <button class="btn btn-primary action" id="clear">
                        <span class="icon icon-gommer"></span> Remise à zéro
                    </button>

                    <button class="btn btn-primary action" id="filter">
                        <span class="icon icon-filtrer"></span>
                        Filtrer
                    </button>
                    </div>
                </div>
        </form>
    </div>
</div>


<style>
    div.filter {
        background-color: white;
        padding: 0.5rem;
        margin: 0.5rem;
        border-radius: 5px;
    }

    div.filter label {
        margin-left: .25em;
    }
</style>

<script>

    $('button#clear').click(function(e) {
        e.preventDefault();
        window.location.href = 'entretien-professionnel?';
    });


    <?php if ($params['structure-filtre'] !== null) :?>
        $('input[name="structure-filtre[label]"]').val("<?php echo trim($params['structure-filtre']['label']); ?>");
        $('input[name="structure-filtre[id]"]').val("<?php echo $params['structure-filtre']['id']; ?>");
    <?php endif; ?>

    <?php if ($params['agent-filtre'] !== null) :?>
        $('input[name="agent-filtre[label]"]').val("<?php echo trim($params['agent-filtre']['label']); ?>");
        $('input[name="agent-filtre[id]"]').val("<?php echo $params['agent-filtre']['id']; ?>");
    <?php endif; ?>

    <?php if ($params['responsable-filtre'] !== null) :?>
        $('input[name="responsable-filtre[label]"]').val("<?php echo trim($params['responsable-filtre']['label']); ?>");
        $('input[name="responsable-filtre[id]"]').val("<?php echo $params['responsable-filtre']['id']; ?>");
    <?php endif; ?>

    <?php if ($params['campagne'] !== null) : ?>
        $('select#campagne option[value=<?php echo $params['campagne']; ?>]').prop('selected', true);
    <?php endif; ?>
    <?php if ($params['etat'] !== null) : ?>
        $('select#etat option[value=<?php echo $params['etat']; ?>]').prop('selected', true);
    <?php endif; ?>
</script>
