<?php

use EntretienProfessionnel\Entity\Db\Campagne;
use UnicaenApp\Form\Element\SearchAndSelect;
use UnicaenEtat\Entity\Db\EtatType;

/**
 * @var EtatType[] $etats ;
 * @var Campagne[] $campagnes
 *
 * @var array $structuresGroups
 * @var array $params
 */

?>

<?php
//var_dump($params);
//var_dump($params['structure']->getLibelleLong());
?>

<br/>

<div class="card card-default">
    <div class="card-header">
        <span class="icon icon-filtrer"></span>
        Filtre de recherche des entretiens professionnels
    </div>
    <div class="card-body">
        <form method="get" id="filtre" action="<?php echo $this->url(); ?>">
            <div class="row">
                <div class="col-md-10">
                    <div class="row">
                        <div class="col-md-6">
                            <?php
                            /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::rechercherAgentAction() */
                            $agentF = new SearchAndSelect('agent-filtre', ['label' => "Agent :"]);
                            $agentF
                                ->setAutocompleteSource($this->url('entretien-professionnel/rechercher-agent'))
                                ->setSelectionRequired()
                                ->setAttributes([
                                    'id' => 'agent-filtre',
                                    'placeholder' => "Nom ou prénom de l'agent·e (minimum 2 caractères)",
                                ]);
                            ?>
                            <?php echo $this->formControlGroup($agentF); ?>

                        </div>
                        <div class="col-md-6">
                            <?php
                            /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::rechercherResponsableAction() */
                            $agentF = new SearchAndSelect('responsable-filtre', ['label' => "Responsable :"]);
                            $agentF
                                ->setAutocompleteSource($this->url('entretien-professionnel/rechercher-responsable'))
                                ->setSelectionRequired()
                                ->setAttributes([
                                    'id' => 'responsable-filtre',
                                    'placeholder' => "Nom ou prénom du responsable  (minimum 2 caractères)",
                                ]);
                            ?>
                            <?php echo $this->formControlGroup($agentF); ?>
                        </div>
                        <div class="col-md-4">
                            <label for="structure-select"> Structure d'affectation : </label>
                            <select id="structure-select" name="structure-select" class="form-control selectpicker" data-live-search="true">
                                <option value="" disabled  hidden
                                        <?php if (!isset($params['structure-select']) OR $params['structure-select'] === '') { echo " selected " ; } ?>
                                >
                                    Sélectionnez une option
                                </option>
                                <?php foreach ($structuresGroups as $group) : ?>
                                    <optgroup label="<?php echo $group['label']; ?>">
                                        <?php foreach ($group['options'] as $id => $label) : ?>
                                            <option value="<?php echo $id; ?>"
                                                    <?php if (isset($params['structure-select']) AND $params['structure-select'] == $id) echo 'selected'; ?>
                                            >
                                                <?php echo $label; ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </optgroup>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="campagne">Campagne :</label>
                            <select id="campagne" name="campagne" class="form-control selectpicker show-tick"
                                    data-live-search="false">
                                <option value=""> Toutes les campagnes</option>
                                <?php foreach ($campagnes as $campagne) : ?>
                                    <option
                                            value="<?php echo $campagne->getId(); ?>"
                                            data-content='
                                                Campagne <?php echo $campagne->getAnnee(); ?>
                                                <?php if ($campagne->estEnCours()) : ?>
                                                    <span class="text-success">
                                                        <span class="icon icon-checked"></span> En cours
                                                    </span>
                                                <?php endif; ?>
                                            '
                                    >
                                        Campagne <?php echo $campagne->getAnnee(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="etat">État :</label>
                            <select id="etat" name="etat" class="form-control selectpicker show-tick"
                                    data-live-search="false">
                                <option value=""> Tous les états</option>
                                <?php foreach ($etats as $etat) : ?>
                                    <option
                                            value="<?php echo $etat->getId(); ?>"
                                            data-content='<?php echo $this->etattype($etat); ?> <?php echo htmlentities($etat->getLibelle()); ?>'
                                    >
                                        <?php echo $etat->getLibelle(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-primary action" id="filter">
                        <span class="icon icon-filtrer"></span>
                        Filtrer
                    </button>
                    <button class="btn btn-primary action" id="clear">
                        <span class="icon icon-gommer"></span> Remise à zéro
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>


<style>
    div.filter label {
        margin-left: .25em;
    }
</style>

<script>

    $('button#clear').on("click",function (e) {
        e.preventDefault();
        window.location.href = 'entretien-professionnel?';
    });

    <?php if (isset($params['structure-filtre'])) :?>
        $('input[name="structure-filtre[label]"]').val("<?php echo trim($params['structure-filtre']['label']); ?>");
        $('input[name="structure-filtre[id]"]').val("<?php echo $params['structure-filtre']['id']; ?>");
    <?php endif; ?>

    <?php if (isset($params['agent-filtre'])) :?>
        $('input[name="agent-filtre[label]"]').val("<?php echo trim($params['agent-filtre']['label']); ?>");
        $('input[name="agent-filtre[id]"]').val("<?php echo $params['agent-filtre']['id']; ?>");
    <?php endif; ?>

    <?php if (isset($params['responsable-filtre'])) :?>
        $('input[name="responsable-filtre[label]"]').val("<?php echo trim($params['responsable-filtre']['label']); ?>");
        $('input[name="responsable-filtre[id]"]').val("<?php echo $params['responsable-filtre']['id']; ?>");
    <?php endif; ?>

    <?php if (isset($params['campagne'])  && $params['campagne'] !== '') : ?>
        $('select#campagne option[value=<?php echo $params['campagne']; ?>]').prop('selected', true);
    <?php endif; ?>
    <?php if (isset($params['etat']) && $params['etat'] !== '') : ?>
        $('select#etat option[value=<?php echo $params['etat']; ?>]').prop('selected', true);
    <?php endif; ?>
</script>
