<?php

/**
 * @var EntretienProfessionnel $entretien
 * @var FormationElement[] $formations
 * @var Agent $agent
 */

/**
 * @var FormationElement $formationElement
 */

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use Formation\Entity\Db\FormationElement;

$anneeCampagne = $entretien->getCampagne()->getAnnee();

$array = [];
foreach ($formations as $formation) {
    if ($formation->estNonHistorise()) {
        $anneeFormation = explode(" - ", $formation->getCommentaire())[0];
        if ( $anneeFormation===$anneeCampagne ) {
            $array[] = [
                    'entite' => $formation,
                    'conserve' => true,
            ];
        }
    }
}
ksort($array);

?>

<?php if (empty($array)) : ?>
    Aucune formation suivie durant la période de la campagne
<?php else : ?>
    <?php echo $this->formationBloc($array, $agent, ['actions' => ['modifier' => false, 'supprimer' => false], 'display' => ['titre'=>false]]); ?>
<?php endif; ?>

<br/>