    <?php

/**
 * @var EntretienProfessionnel $entretien
 * @var Agent $agent
 * @var FichePoste $ficheposte
 * @var FicheMetier[] $fichesmetiers
 * @var string[] $documents
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\StructurePrivileges;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
    use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;

    $sursis = $entretien->getSursisActif();

$canAfficherInformationMetier = (
        $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_VALIDER_RESPONSABLE))
        OR
        $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_VALIDER_DRH))
);
?>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                À propos de l'agent
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt> Fiche de l'agent </dt>
                    <dd>
                        <a
                            <?php /** @see \Application\Controller\AgentController::afficherAction() */ ?>
                            href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                            target="_blank"
                        >
                            <?php echo $agent->getDenomination(); ?>
                        </a>
                    </dd>
                    <?php if ($canAfficherInformationMetier) : ?>

                        <dt> Fiche(s) de poste</dt>
                        <dd>
                            <?php if ($ficheposte !== null) : ?>
                                <a
                                    <?php /** @see \Application\Controller\FichePosteController::afficherAction() */ ?>
                                    href="<?php echo $this->url('fiche-poste/afficher', ['fiche-poste' => $ficheposte->getId()], [], true); ?>"
                                    target="_blank"
                                >
                                    Fiche de poste #<?php echo $ficheposte->getId();?>
                                </a>
                            <?php else : ?>
                                <span style="color: darkred;"><span class="icon attention"></span> Aucune fiche de poste</span>
                            <?php endif; ?>
                        </dd>
                        <dt> Fiche(s) métier(s)</dt>
                        <dd>
                            <?php if (!empty($fichesmetiers)) : ?>
                                <?php $first = true; foreach ($fichesmetiers as $fichemetier) : ?>
                                    <?php if ($first) $first=false; else echo '<br/>'; ?>
                                    <a
                                        <?php /** @see \Application\Controller\FicheMetierController::afficherAction() */ ?>
                                        href="<?php echo $this->url('fiche-metier-type/afficher', ['id' => $fichemetier->getId()], [], true); ?>"
                                        target="_blank"
                                    >
                                        <?php
                                            $libelle = "Fiche metier #".$fichemetier->getId();
                                            if ($fichemetier->getMetier()) $libelle = $fichemetier->getMetier()->getLibelle();
                                        ?>
                                        <?php echo $libelle; ?>
                                    </a>
                                <?php endforeach; ?>
                            <?php else : ?>
                                <span style="color: darkred;"><span class="icon attention"></span> Aucune fiche métier </span>
                            <?php endif; ?>
                        </dd>

                    <?php endif; ?>

                    <dt> Structure(s) </dt>
                    <dd>
                        <?php
                            $structures = [];
                            foreach ($agent->getAffectationsActifs() as $affectation) {
                                $structure = $affectation->getStructure();
                                $structures[$structure->getId()] = $structure;
                            }
                            usort($structures, function (Structure $a, Structure $b) { return ($a->getLibelleCourt() .' '. $a->getLibelleLong()) < ($b->getLibelleCourt() .' '. $b->getLibelleLong());});
                        ?>
                        <?php foreach ($structures as $structure) : ?>

                            <?php
                                $structureLibelle = "[" .$structure->getLibelleCourt(). "] ". $structure->getLibelleLong();
                                $structureUrl = $this->url("structure/afficher", ['structure' => $structure->getId()], [], true);
                                $canAfficherStructure = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_AFFICHER);
                            ?>
                                <?php if ($canAfficherStructure) : ?>
                                    <a href="<?php echo $structureUrl; ?>" target="_blank" title="Affichage de la structure" data-toggle="tooltip" data-html="true">
                                        <?php echo $structureLibelle; ?>
                                    </a>
                                <?php else : ?>
                                    <?php echo $structureLibelle; ?>
                                <?php endif; ?>
                        <?php endforeach; ?>
                        <br/>
                    </dd>
                </dl>
            </div>
        </div>


    </div>
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Documents utiles
            </div>
            <div class="panel-body">
                <ul>
                    <?php foreach ($documents as $document) : ?>
                        <li> <?php echo $document; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Informations complémentaires
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt> Responsable </dt>
                    <dd> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </dd>
                    <dt> Année </dt>
                    <dd> <?php echo $entretien->getAnnee(); ?> </dd>
                    <dt> Date </dt>
                    <dd> <?php echo $entretien->getDateEntretien()->format('d/m/Y à H:i'); ?> </dd>
                    <?php if ($sursis !== null) : ?>
                        <dt> Sursis </dt>
                        <dd> Jusqu'au <?php echo $sursis->getSursis()->format('d/m/Y'); ?> </dd>
                    <?php endif; ?>
                    <dt> Lieu </dt>
                    <dd> <?php echo $entretien->getLieu(); ?> </dd>
                </dl>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Validation de l'entretien
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>Confirmation</dt>
                    <dd><?php echo ($entretien->getToken() === null) ? '<span class="icon ok" style="color:darkgreen;"></span>' : '<span class="icon sursis" title="Non effectuée"></span> Non effectuée'; ?> </dd>
                    <dt>Responsable d'entretien </dt>
                    <dd>
                        <?php if ($entretien->hasValidationResponsable()) : ?>
                            <div>
                                <div style="display: inline-block; vertical-align: top;">
                                    <span class="icon ok" style="color:darkgreen;"></span>
                                </div>
                                <div style="display: inline-block;">
                                    <?php echo $entretien->getValidationResponsable()->getHistoModificateur()->getDisplayName(); ?>
                                    <br/><?php echo $entretien->getValidationResponsable()->getHistoModification()->format("d/m/Y à H:i"); ?>
                                </div>
                            </div>
                        <?php else : ?>
                            <span class="icon sursis" title="Non effectuée"></span> Non effectuée
                        <?php endif; ?>
                    </dd>
                    <dt>Agent </dt>
                    <dd>
                        <?php if ($entretien->hasValidationAgent()) : ?>
                            <div style="display: inline-block; vertical-align: top;">
                                <span class="icon ok" style="color:darkgreen;"></span>
                            </div>
                            <div style="display: inline-block;">
                                <?php echo $entretien->getValidationAgent()->getHistoModificateur()->getDisplayName(); ?>
                                <br/><?php echo $entretien->getValidationAgent()->getHistoModification()->format("d/m/Y à H:i"); ?>
                            </div>
                        <?php else : ?>
                            <span class="icon sursis" title="Non effectuée"></span> Non effectuée
                        <?php endif; ?>
                    </dd>
                    <dt>Responsable hiérachique </dt>
                    <dd>
                        <?php if ($entretien->hasValidationDRH()) : ?>
                            <div style="display: inline-block; vertical-align: top;">
                                <span class="icon ok" style="color:darkgreen;"></span>
                            </div>
                            <div style="display: inline-block;">
                                <?php echo $entretien->getValidationDRH()->getHistoModificateur()->getDisplayName(); ?>
                                <br/><?php echo $entretien->getValidationDRH()->getHistoModification()->format("d/m/Y à H:i"); ?>
                            </div>
                        <?php else : ?>
                            <span class="icon sursis" title="Non effectuée"></span> Non effectuée
                        <?php endif; ?>
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>