<?php

/**
 * @var EntretienProfessionnel[] $entretiens
 */


use Application\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;

$canVoir        = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AFFICHER));
$canAjouter     = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AJOUTER));
$canModifier    = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_MODIFIER));
$canHistoriser  = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_HISTORISER));
$canDetruire    = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_DETRUIRE));
?>

<?php if (false AND $canAjouter) : ?>
    <a
        <?php /** @see \Application\Controller\EntretienProfessionnelController::creerAction() */ ?>
        href="<?php echo $this->url('entretien-professionnel/creer', [], [], true); ?>"
        class="btn btn-primary action ajax-modal" data-event="modification">
        <span class="icon ajouter action"></span>
        Créer un entretien professionnel
    </a>
<?php endif; ?>

<h2> Liste des entretiens enregistrés </h2>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Année </th>
        <th> Agent </th>
        <th> Responsable </th>
        <th> Date </th>
        <th> Modifée </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($entretiens as $entretien) : ?>
        <tr>
            <td> <?php echo $entretien->getAnnee(); ?> </td>
            <td>
                <?php echo $entretien->getAgent()->getPrenom(); ?>
                <?php echo $entretien->getAgent()->getNomUsuel(); ?>
            </td>
            <td> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </td>
            <td> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </td>
            <td> <?php echo $entretien->getHistoModification()->format('d/m/Y'); ?> </td>
            <td>
                <?php if ($canVoir) : ?>
                    <a
                        <?php /** @see \Application\Controller\EntretienProfessionnelController::afficherAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/afficher', ['entretien' => $entretien->getId()], [], true) ?>"
                        class="ajax-modal"
                    >
                        <span class="icon voir" title="Voir le compte-rendu de l'entretien professionnel"></a>
                <?php endif; ?>

                <?php if ($canVoir) : ?>
                    <a
                        <?php /** @see \Application\Controller\EntretienProfessionnelController::exporterAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/exporter', ['entretien' => $entretien->getId()], [], true) ?>"
                    >
                        <span class="icon pdf" title="Exporter l'entretien professionnel"></a>
                <?php endif; ?>

                <?php if ($canModifier) : ?>
                    <a
                        <?php /** @see \Application\Controller\EntretienProfessionnelController::renseignerAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId()], [], true); ?>"
                    >
                        <span class="icon editer" title="Modifier le compte-rendu de l'entretien professionnel"></span></a>
                <?php endif; ?>

                <?php if ($canHistoriser) : ?>
                    <?php if ($entretien->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \Application\Controller\EntretienProfessionnelController::historiserAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/historiser', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser le compte-rendu de l'entretien professionnel"></span></a>
                    <?php else : ?>
                        <a
                            <?php /** @see \Application\Controller\EntretienProfessionnelController::restaurerAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/restaurer', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer le compte-rendu de l'entretien professionnel"></span></a>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($canDetruire) : ?>
                    <a
                        <?php /** @see \Application\Controller\EntretienProfessionnelController::detruireAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/detruire', ['entretien' => $entretien->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer définitivement le compte-rendu de l'entretien professionnel"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>