<?php

/**
 * @var EntretienProfessionnel[] $entretiens
 * @var Campagne[] $campagnes
 * @var Etat[] $etats
 * @var array $params
 */


use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use UnicaenEtat\Entity\Db\Etat;

$canVoir        = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AFFICHER));
$canAjouter     = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AJOUTER));
$canModifier    = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_MODIFIER));
$canHistoriser  = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_HISTORISER));
$canDetruire    = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_DETRUIRE));
?>

<?php echo $this->portenote('EntretienProfessionnelController::entretiens', '', []); ?>

<?php echo $this->partial('partial/filtre', ['etats' => $etats, 'campagnes' => $campagnes, 'params' => $params], [], true); ?>

<h2> Liste des entretiens enregistrés </h2>

<?php echo $this->entretienProfessionnelArray($entretiens,
    [
        'affichages' => ['lieu' => false],
        'droits' => []
    ]
); ?>


<style>
    th#etat {
        width:6rem;
        min-width: 6rem;
    }

    th#action {
        width:11rem;
        min-width: 6rem;
    }

@media (min-width: 0) and (max-width: 768px) {
        th {
            font-size: small;
        }
        td {
            font-size: small;
            background: var(--content-background);
        }
}

</style>