<?php

use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use Mailing\Model\Db\Mail;
use Mailing\Provider\Privilege\MailingPrivileges;

/**
 * @var EntretienProfessionnel $entretien
 * @var Mail[] $mails
 * @var string $retour
 */

$canAfficherMail  = $this->isAllowed(MailingPrivileges::getResourceId(MailingPrivileges::MAILING_AFFICHER));
$canReEnvoyerMail = $this->isAllowed(MailingPrivileges::getResourceId(MailingPrivileges::MAILING_REENVOI));
?>

<h2 class="page-header-tab">
    Liste des mails liés à l'entretien professionnel
</h2>

<table class="table table-condensed">
    <thead>
        <tr>
            <th> Date d'envoi </th>
            <th> Destinataire </th>
            <th> Sujet </th>
            <th style="width:8rem;"> État </th>
            <th style="width:8rem;"> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($mails as $mail) : ?>
            <tr>
                <td> <?php echo $mail->getDateEnvoi()->format('d/m/Y à H:i:s'); ?> </td>
                <td> <?php echo $mail->getDestinatires(); ?> </td>
                <td> <?php echo $mail->getSujet(); ?> </td>
                <td style="text-align: center;"> <?php echo $this->etatbadge($mail->getStatusEnvoi()); ?> </td>
                <td style="text-align: right;">
                    <?php if($canAfficherMail) : ?>
                        <a <?php /** @see \Mailing\Controller\MailingController::afficherAction() */?>
                            href="<?php echo $this->url('mailing/afficher',  ['id' => $mail->getId()], [], true); ?>"
                            class="ajax-modal"
                            title="Affichage du mail" data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon icon-voir"></span></a>
                    <?php endif; ?>
                    <?php if($canReEnvoyerMail) : ?>
                        <a <?php /** @see \Mailing\Controller\MailingController::reEnvoiAction() */?>
                                href="<?php echo $this->url('mailing/re-envoi',  ['id' => $mail->getId()], ['query' => ['retour' => $retour]], true); ?>"
                                title="Re-envoi du mail" data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon courrier"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
