<?php

/**
 * @var EntretienProfessionnel $entretien
 * @var Observation $observation
 * @var string $source
 */

use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnelConstant;
use EntretienProfessionnel\Entity\Db\Observation;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use EntretienProfessionnel\Provider\Privilege\ObservationPrivileges;

$canAfficherObservation = $this->isAllowed(ObservationPrivileges::getResourceId(ObservationPrivileges::OBSERVATION_AFFICHER));
$canAjouterObservation = $this->isAllowed(ObservationPrivileges::getResourceId(ObservationPrivileges::OBSERVATION_AJOUTER));
$canModifierObservation = $this->isAllowed(ObservationPrivileges::getResourceId(ObservationPrivileges::OBSERVATION_MODIFIER));
$canHistoriserObservation = $this->isAllowed(ObservationPrivileges::getResourceId(ObservationPrivileges::OBSERVATION_HISTORISER));
$canDetruireObservation = $this->isAllowed(ObservationPrivileges::getResourceId(ObservationPrivileges::OBSERVATION_SUPPRIMER));

$validationObservation  = $entretien->getValidationByType(EntretienProfessionnelConstant::VALIDATION_OBSERVATION);
$canValiderObservation  = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_OBSERVATION);

$now = new DateTime();
$date = $entretien->getMaxSaisiObservation();

$date_non_depassee = ($date !== null AND $date >= $now);
$validationResponsable = $entretien->getValidationByType(EntretienProfessionnelConstant::VALIDATION_RESPONSABLE);
$validationHierarchie = $entretien->getValidationByType(EntretienProfessionnelConstant::VALIDATION_DRH);
?>

<!-- HEADER DE L'ONGLET ----------------------------------------------------------------------------------------------->

<h2 class="page-header-tab"> Observations liées à l'entretien professionnel</h2>

<?php if ($validationResponsable === null) : ?>
    <div class="alert alert-danger"> Aucune validation du responsable de l'entretien. Les observations ne peuvent être émises qu'après la validation de celui-ci.</div>
<?php endif; ?>

<?php if ($validationHierarchie !== null) : ?>
    <div class="alert alert-danger"> Une validation du responsable hiérarchique a été faite. Les observations ne peuvent être émises qu'avant la validation de celui-ci.</div>
<?php endif; ?>

<?php if ($date_non_depassee === false) : ?>
    <div class="alert alert-danger"> Date de dépôt des observations dépassée.</div>
<?php endif; ?>


<!-- Observation de l'agent : CONTROLE -------------------------------------------------------------------------------->

<div class="row">
    <div class="col-md-8">
        <h3> Observations de l'agent </h3>
    </div>
    <div class="pull-right">
        <?php if (($validationResponsable !== null) AND ($validationHierarchie === null) AND $date_non_depassee) : ?>
            <?php if ($observation === null) : ?>
                <?php if ($canAjouterObservation) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\ObservationController::ajouterAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/observation/ajouter', ['entretien-professionnel' => $entretien->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal" data-event="modification"
                    >
                        <span class="icon ajouter"> Ajouter une observation </span>
                    </a>
                <?php endif; ?>
            <?php else : ?>
                <?php if ($canModifierObservation) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\ObservationController::modifierAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/observation/modifier', ['observation' => $observation->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="icon editer"> </span>
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriserObservation) : ?>
                    <?php if ($observation->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\ObservationController::historiserAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/observation/historiser', ['observation' => $observation->getId()], [], true); ?>"
                        >
                            <span class="icon historiser"> </span>
                        </a>
                    <?php else : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\ObservationController::restaurerAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/observation/restaurer', ['observation' => $observation->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer"> </span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruireObservation) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\ObservationController::supprimerAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/observation/supprimer', ['observation' => $observation->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire"> </span>
                    </a>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<!-- Observation de l'agent : AFFICHAGE ------------------------------------------------------------------------------->

<?php if ($canAfficherObservation) : ?>
    <dl class="dl-horizontal">
        <dt> Dernière modification </dt>
        <dd>
            <?php if ($observation === null) : ?>
                Aucune observation.
            <?php else: ?>
                <?php echo $observation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $observation->getHistoModification()->format('d/m/Y à H:i:s'); ?>
            <?php endif; ?>
        </dd>
    </dl>

    <?php if ($observation !== null) : ?>
            <div class="entretien-professionnel-observation">
                <h3 class="reponse_categorie"> Observation sur l'entretien </h3>

                <?php if ($observation->getObservationAgentEntretien() !== null) : ?>
                    <div class="reponse_textarea">
                        <?php echo $observation->getObservationAgentEntretien(); ?>
                    </div>
                <?php else : ?>
                    Aucune observation
                <?php endif; ?>
                <h3 class="reponse_categorie"> Observation sur les perspectives </h3>
                <?php if ($observation->getObservationAgentPerspective() !== null) : ?>
                    <div class="reponse_textarea">
                        <?php echo $observation->getObservationAgentPerspective(); ?>
                    </div>
                <?php else : ?>
                    Aucune observation
                <?php endif; ?>
            </div>
    <?php endif; ?>
<?php else : ?>

<div class="alert alert-danger">
    Vous n'êtes pas habilité·e·s à voir cette observation.
</div>

<?php endif; ?>

<?php if ($canValiderObservation AND $validationHierarchie === null AND $date_non_depassee === true) : ?>
    <?php if ($validationObservation !== null) : ?>
        <div class="pull-right">
                <a
                    <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                        href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $validationObservation->getId()], [], true); ?>"
                        class="btn btn-danger action"
                >
                    <span class="icon validation-undo"></span>
                    Révoquer la validation
                </a>
        </div>
    <?php else : ?>
        <div class="pull-right">
            <a
                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                    href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => EntretienProfessionnelConstant::VALIDATION_OBSERVATION], [], true); ?>"
                    class="btn btn-success action ajax-modal"
                    data-event="modification"
            >
                <span class="icon validation-do"></span>
                Valider les observations
            </a>
            <a
                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                    href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => EntretienProfessionnelConstant::VALIDATION_OBSERVATION], [], true); ?>"
                    class="btn btn-success action ajax-modal"
                    data-event="modification"
            >
                <span class="icon validation-do"></span>
                Je ne fais pas d'observation
            </a>
        </div>
    <?php endif; ?>
<?php endif; ?>
