<?php

/**
 * @var Agent $agent
 * @var EntretienProfessionnel $entretien
 * @var ParcoursDeFormation[] $parcours
 * @var FichePoste $ficheposte
 * @var array $options
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\ParcoursDeFormation;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;

$options['retour'] = $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId(), 'agent' => $agent], ['fragment' => 'parcours'], true);

?>

<h2 class="page-header-tab"> Parcours d'entrée dans le métier </h2>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <?php if ($parcours !== null AND !empty($parcours)) : ?>
            <?php
            $arrays = $parcours;
            ksort($arrays);
            foreach ( $arrays as $type => $array) : ?>
                <?php $parcours = $array; ?>
                <?php foreach ($parcours as $parcour) : ?>
                    <?php echo $this->parcoursDeFormation($parcour, $agent, $options); ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php else : ?>
            Aucun parcours de renseigné.
        <?php endif; ?>
    </div>
</div>

<h2 class="page-header-tab">Logiciels métiers</h2>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <?php
        if($ficheposte !== null) : ?>
            <?php echo $this->parcoursApplication($ficheposte, $agent, $options); ?>
        <?php endif; ?>
    </div>
</div>