<?php

/**
 * @var EntretienProfessionnel $entretien
 * @var array $droits
 * @var int $step
 *
 * @var Agent[] $superieures
 * @var Agent[] $autorites
 */

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use EntretienProfessionnel\Provider\Validation\EntretienProfessionnelValidations;

$canValiderAgent        = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_AGENT);
$canValiderObservation  = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_OBSERVATION);
$canValiderResponsable  = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_RESPONSABLE);
$canValiderDrh          = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_DRH);

$now = new DateTime();
$dateOk = ($now > $entretien->getDateEntretien());
$validationResponsable   = $entretien->getValidationByType(EntretienProfessionnelValidations::VALIDATION_RESPONSABLE);
$validationObservation   = $entretien->getValidationByType(EntretienProfessionnelValidations::VALIDATION_OBSERVATION);
$validationHierarchie    = $entretien->getValidationByType(EntretienProfessionnelValidations::VALIDATION_DRH);
$validationAgent         = $entretien->getValidationByType(EntretienProfessionnelValidations::VALIDATION_AGENT);


$now = new DateTime();

$date = $entretien->getMaxSaisiObservation();
$depasse = ($date === null or $date < $now);

?>

<h2 class="page-header-tab"> Validations </h2>

<?php if ($canValiderDrh === null) : ?>
    <div class="alert alert-warning">
        <span class="icon icon-attention"> </span>
        La validation de l'entretien professionnel provoquent un blocage des saisies de celui-ci.
    </div>
<?php endif; ?>

<div>
    <h3 class="categorie"> Validation du responsable de l'entretien professionnel </h3>

    <?php if ($step === 0) : ?>
        <div class="alert alert-info">
            <strong><span class="icon icon-information"></span> Le reponsable de l'entretien (<?php echo $entretien->getResponsable()->getDenomination(); ?>) doit valider l'entretien professionnel.</strong>
            <br/><br/>
            Cette validation :
            <ul>
                <li> fige les compte-rendus d'entretien professionnel et de formation ;</li>
                <li> rend visible les compte-rendus d'entretien professionnel et de formation à l'agent (<?php echo $entretien->getAgent()->getDenomination(); ?>);</li>
                <li> notifie l'agent (<?php echo $entretien->getAgent()->getDenomination(); ?>) que la phase d'observation est ouverte.</li>
            </ul>
        </div>
    <?php endif; ?>

    <?php if ($validationResponsable !== null) : ?>
        <div class="row">
            <div class="col-md-8">
                <div class="alert alert-success">
                    <div class="col-md-5">
                        <strong>Validation effectuée</strong>
                    </div>
                    <div class="col-md-7">
                        <dl class="dl-horizontal">
                            <dt> Validateur </dt>
                            <dd> <?php echo $validationResponsable->getHistoModificateur()->getDisplayName(); ?> </dd>
                            <dt> Date </dt>
                            <dd> <?php echo $validationResponsable->getHistoModification()->format('d/m/y à H:i:s'); ?> </dd>
                        </dl>
                    </div>
                    <br/>
                    <br/>
                </div>
            </div>
            <div class="pull-right">
                <?php if ($canValiderResponsable and $validationObservation === null and $validationHierarchie === null) : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $validationResponsable->getId()], [], true); ?>"
                                class="btn btn-danger action"
                        >
                            <span class="icon validation-undo"></span>
                            Révoquer la validation
                        </a>
                <?php endif; ?>
            </div>
        </div>
    <?php else : ?>
        <?php if ($canValiderResponsable) : ?>
            <a
                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                    href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => EntretienProfessionnelValidations::VALIDATION_RESPONSABLE], [], true); ?>"
                    class="btn btn-success action ajax-modal"
                    data-event="modification"
            >
                <span class="icon validation-do"></span>
                Validation du responsable
            </a>
        <?php endif; ?>
    <?php endif; ?>
</div>

<div>
    <h3 class="categorie"> Expression des observations </h3>

    <?php if ($step === 1) : ?>
        <div class="alert alert-info">
            <strong><span class="icon icon-information"></span> L'agent (<?php echo $entretien->getAgent()->getDenomination(); ?>) peut maintenant exprimer des observations.</strong>
            <br/><br/>
            Une fois les observations faites, en validant l'agent :
            <ul>
                <li> fige ses observations ;</li>
                <li> notifie son responsable d'entretien (<?php echo $entretien->getResponsable()->getDenomination(); ?>) des observations apportées ;</li>
                <li> notifie ses autorités hiérarchiques pour validation auprès d'eux de l'entretien professionnel.</li>
            </ul>
            Ces observations sont facultatives et l'agent peut exprimer le fait de ne pas vouloir faire d'observation.
            <br/><br/>
            <strong><span class="icon icon-information"></span> L'expression d'observations et leur validation n'est possible que durant les 8 jours suivants la validation de l'entretien professionnel par son responsable
                (<?php echo $entretien->getMaxSaisiObservation()->format("d/m/Y à H:i"); ?>).
            </strong>
        </div>
    <?php endif; ?>

    <?php if ($step < 1) : ?>
        <div class="alert alert-warning">
            <strong>
                <span class="icon icon-information"></span>
                Ne sera disponible qu'après la validation du responsable d'entretien professionnel
            </strong>
        </div>
    <?php endif; ?>
    <?php echo $this->partial('partial/observation.phtml', ['entretien' => $entretien, 'observation' => $entretien->getObservationActive(), 'droits' => $droits, 'source' => 'renseignerAction']); ?>

    <?php if ($validationObservation !== null) : ?>
        <div class="row">
            <div class="col-md-8">
                <div class="alert alert-success">
                    <div class="col-md-5">
                        <strong>Observations validées</strong>
                    </div>
                    <div class="col-md-7">
                        <dl class="dl-horizontal">
                            <dt> Validateur </dt>
                            <dd> <?php echo $validationObservation->getHistoModificateur()->getDisplayName(); ?> </dd>
                            <dt> Date </dt>
                            <dd> <?php echo $validationObservation->getHistoModification()->format('d/m/y à H:i:s'); ?> </dd>
                        </dl>
                    </div>
                    <br/>
                    <br/>
                </div>
            </div>
            <div class="pull-right">
                <?php if ($canValiderObservation AND $validationHierarchie === null) : ?>
                    <?php if ($validationObservation !== null) : ?>
                        <div class="pull-right">
                            <a
                                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                                    href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $validationObservation->getId()], [], true); ?>"
                                    class="btn btn-danger action"
                            >
                                <span class="icon validation-undo"></span>
                                Révoquer la validation
                            </a>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    <?php else :?>
    <?php if ($step >= 1) : ?>
        <?php if ($canValiderObservation) : ?>
            <?php if ($entretien->getObservationActive()) : ?>
                <a
                    <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                        href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => EntretienProfessionnelValidations::VALIDATION_OBSERVATION], [], true); ?>"
                        class="btn btn-success action ajax-modal"
                        data-event="modification"
                >
                    <span class="icon validation-do"></span>
                    Valider les observations
                </a>
            <?php else : ?>
                <a
                        <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => EntretienProfessionnelValidations::VALIDATION_OBSERVATION], [], true); ?>"
                            class="btn btn-success action ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon validation-do"></span>
                        Je ne fais pas d'observation
                    </a>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php endif; ?>
</div>


<div>
    <h3 class="categorie"> Validation de l'autorité hiérarchique </h3>

    <?php if ($step === 2) : ?>
        <div class="alert alert-info">
            <strong><span class="icon icon-information"></span> L'autorité hiérarchique de l'agent (<?php echo $entretien->getAgent()->getDenomination(); ?>) peut valider l'entretien professionnel.</strong>
            <br/><br/>
            Une fois cette validation faite :
            <ul>
                <li> notifie l'agent (<?php echo $entretien->getAgent()->getDenomination(); ?>) de la validation.</li>
            </ul>
        </div>
    <?php endif; ?>

    <?php if ($step < 2) : ?>
        <div class="alert alert-warning">
            <strong>
                <span class="icon icon-information"></span>
                Ne sera disponible qu'après la validation des observations ou le dépassement du délai d'expression des observations.
            </strong>
        </div>
    <?php endif; ?>

    <?php if ($validationHierarchie !== null) : ?>
        <div class="row">
            <div class="col-md-8">
                <div class="alert alert-success">
                    <div class="col-md-5">
                        <strong>Validation effectuée</strong>
                    </div>
                    <div class="col-md-7">
                        <dl class="dl-horizontal">
                            <dt> Validateur </dt>
                            <dd> <?php echo $validationHierarchie->getHistoModificateur()->getDisplayName(); ?> </dd>
                            <dt> Date </dt>
                            <dd> <?php echo $validationHierarchie->getHistoModification()->format('d/m/y à H:i:s'); ?> </dd>
                        </dl>
                    </div>
                    <br/>
                    <br/>
                </div>
            </div>
            <div class="pull-right">
                <?php if ($canValiderDrh AND $validationAgent === null) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $validationHierarchie->getId()], [], true); ?>"
                            class="btn btn-danger action"
                    >
                        <span class="icon validation-undo"></span>
                        Révoquer la validation
                    </a>
                <?php endif; ?>
            </div>
        </div>
   <?php else : ?>
        <?php if ($canValiderDrh AND $validationResponsable AND ($validationObservation !== null OR $depasse)) : ?>
            <a
                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                    href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => EntretienProfessionnelValidations::VALIDATION_DRH], [], true); ?>"
                    class="btn btn-success action ajax-modal"
                    data-event="modification"
            >
                <span class="icon validation-do"></span>
                Validation de l'autorité
            </a>
        <?php endif; ?>
    <?php endif; ?>
</div>

<div>
    <h3 class="categorie"> Validation de l'agent </h3>

    <?php if ($step === 3) : ?>
        <div class="alert alert-info">
            <strong>
                <span class="icon icon-information"></span>
                L'agent (<?php echo $entretien->getAgent()->getDenomination(); ?>) peut maintenant valider son entretien professionnel.
            </strong>
            <br/><br/>

            Cette validation :
            <ul>
                <li> clôture l'entretien professionnel ; </li>
                <li> permet l'ouverture des procédures de recours (hors de cette application). </li>
            </ul>
        </div>
    <?php endif; ?>

    <?php if ($step < 3) : ?>
        <div class="alert alert-warning">
            <strong>
                <span class="icon icon-information"></span>
                Ne sera disponible qu'après la validation de l'autorité hiérarchique.
            </strong>
        </div>
    <?php endif; ?>

    <?php if ($validationAgent !== null) : ?>
        <div class="row">
            <div class="col-md-8">
                <div class="alert alert-success">
                    <div class="col-md-5">
                        <strong>Validation effectuée</strong>
                    </div>
                    <div class="col-md-7">
                        <dl class="dl-horizontal">
                            <dt> Validateur </dt>
                            <dd> <?php echo $validationAgent->getHistoModificateur()->getDisplayName(); ?> </dd>
                            <dt> Date </dt>
                            <dd> <?php echo $validationAgent->getHistoModification()->format('d/m/y à H:i:s'); ?> </dd>
                        </dl>
                    </div>
                    <br/>
                    <br/>
                </div>
            </div>
            <div class="pull-right">
                <?php if ($canValiderAgent AND $entretien->getCampagne()->estEnCours()) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $validationAgent->getId()], [], true); ?>"
                            class="btn btn-danger action"
                    >
                        <span class="icon validation-undo"></span>
                        Révoquer la validation
                    </a>
                <?php endif; ?>
            </div>
        </div>
    <?php else : ?>
        <?php if ($validationHierarchie !== null) : ?>
            <a
                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                    href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => EntretienProfessionnelValidations::VALIDATION_AGENT], [], true); ?>"
                    class="btn btn-success action ajax-modal"
                    data-event="modification"
            >
                <span class="icon validation-do"></span>
                Validation de l'agent
            </a>
        <?php endif; ?>
    <?php endif; ?>
</div>