<?php

/**
 * @var EntretienProfessionnel $entretien
 */

use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;

$canValiderAgent        = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_AGENT);
$canValiderResponsable  = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_RESPONSABLE);
$canValiderDrh          = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_VALIDER_DRH);

$now = new DateTime();
$dateOk = ($now > $entretien->getDateEntretien());
?>

<h2> Validations </h2>

<?php echo $this->portenote('EntretienProfessionnelController::renseignerAction()>validations', '', []); ?>

<div>
    <?php if (!$dateOk) : ?>
        <div class="alert alert-info">
            <span class="icon attention"></span> Les validations ne seront possible qu'à partir de la date de l'entretien professionnel.<br/>
            Celui aura lieu le <?php echo $entretien->getDateEntretien()->format('d/m/Y à H:i'); ?>.
        </div>
    <?php endif; ?>

    <h3 class="categorie"> Validation du responsable de l'entretien professionnel </h3>

    <div class="row">
        <?php if ($entretien->hasValidationResponsable()) : ?>
            <div class="col-md-8">
                <div class="row">
                    <div class="alert alert-success">
                        <div class="col-md-6">
                            <strong><u>Validation responsable effectuée.</u></strong>
                        </div>
                        <div class="col-md-6">
                            <dl class="dl-horizontal">
                                <dt> Validateur </dt>
                                <dd> <?php echo $entretien->getValidationResponsable()->getHistoModificateur()->getDisplayName(); ?> </dd>
                                <dt> Date </dt>
                                <dd> <?php echo $entretien->getValidationResponsable()->getHistoModification()->format('d/m/y à H:i:s'); ?> </dd>
                            </dl>
                        </div>
                        <br/>
                        <br/>
                    </div>
                </div>
            </div>
            <div class="pull-right">
                <br/>
                <?php if ($canValiderResponsable && ! $entretien->hasValidationAgent()) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $entretien->getValidationResponsable()->getId()], [], true); ?>"
                            class="btn btn-danger action"
                    >
                        <span class="icon validation-undo"></span>
                        Révoquer la validation
                    </a>
                <?php endif; ?>
            </div>
        <?php else : ?>
            <div class="col-md-8">
                <div class="alert alert-info">
                    <span class="icon attention"></span>
                    La validation du responsable de l'entretien professionnel bloque toutes modifications du formulaires d'entretien professionnel et du parcours de l'agent.
                </div>
            </div>
            <div class="pull-right">
                <br/>
                <?php if ($dateOk AND $canValiderResponsable) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => 'Responsable'], [], true); ?>"
                            class="btn btn-success action ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon validation-do"></span>
                        Validation du responsable
                    </a>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<div>
    <h3 class="categorie"> Validation de l'agent </h3>

    <div class="row">

        <?php if (!$entretien->hasValidationResponsable()) : ?>
            <div class="col-md-8">
                <div class="alert alert-warning">
                    <span class="icon attention"></span>
                    La validation par l'agent n'est possible seulement après celle du reponsable de l'entretien professionnel.
                </div>
            </div>
        <?php else : ?>
            <?php if ($entretien->hasValidationAgent()) : ?>
                <div class="col-md-8">
                    <div class="row">
                        <div class="alert alert-success">
                            <div class="col-md-6">
                                <strong><u>Validation agent effectuée.</u></strong>

                            </div>
                            <div class="col-md-6">
                                <dl class="dl-horizontal">
                                    <dt> Validateur </dt>
                                    <dd> <?php echo $entretien->getValidationAgent()->getHistoModificateur()->getDisplayName(); ?> </dd>
                                    <dt> Date </dt>
                                    <dd> <?php echo $entretien->getValidationAgent()->getHistoModification()->format('d/m/y à H:i:s'); ?> </dd>
                                </dl>
                            </div>
                            <br/>
                            <br/>
                        </div>
                    </div>
                </div>
                <div class="pull-right">
                    <br/>
                    <?php if ($canValiderAgent && ! $entretien->hasValidationDRH()) : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $entretien->getValidationAgent()->getId()], [], true); ?>"
                                class="btn btn-danger action"
                        >
                            <span class="icon validation-undo"></span>
                            Révoquer la validation
                        </a>
                    <?php endif; ?>
                </div>
            <?php else : ?>
                <div class="col-md-8">
                    <div class="alert alert-info">
                        <span class="icon attention"></span>
                        Après cette validation l'agent ne peut plus donner d'observation sur l'entretien professionnel.
                        En cas de problème, l'agent possède 15 jours pour faire la demande d'un recours.
                    </div>
                </div>
                <div class="pull-right">
                    <br/>
                    <?php if ($dateOk AND $canValiderResponsable) : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => 'Agent'], [], true); ?>"
                                class="btn btn-success action ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon validation-do"></span>
                            Validation de l'agent
                        </a>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<div>
    <h3 class="categorie"> Validation de la direction des ressources humaines </h3>

    <div class="row">

        <?php if (!$entretien->hasValidationAgent()) : ?>
            <div class="col-md-8">
                <div class="alert alert-warning">
                    <span class="icon attention"></span>
                    La validation par la direction des ressources humaines n'est possible seulement après celle de l'agent.
                </div>
            </div>
        <?php else : ?>
            <?php if ($entretien->hasValidationDRH()) : ?>
                <div class="col-md-8">
                    <div class="row">
                        <div class="alert alert-success">
                            <div class="col-md-6">
                                <strong><u>Validation DRH effectuée.</u></strong>

                            </div>
                            <div class="col-md-6">
                                <dl class="dl-horizontal">
                                    <dt> Validateur </dt>
                                    <dd> <?php echo $entretien->getValidationDRH()->getHistoModificateur()->getDisplayName(); ?> </dd>
                                    <dt> Date </dt>
                                    <dd> <?php echo $entretien->getValidationDRH()->getHistoModification()->format('d/m/y à H:i:s'); ?> </dd>
                                </dl>
                            </div>
                            <br/>
                            <br/>
                        </div>
                    </div>
                </div>
                <div class="pull-right">
                    <br/>
                    <?php if ($canValiderDrh ) : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::revoquerValidationAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/revoquer-validation', ['validation' => $entretien->getValidationDRH()->getId()], [], true); ?>"
                                class="btn btn-danger action"
                        >
                            <span class="icon validation-undo"></span>
                            Révoquer la validation
                        </a>
                    <?php endif; ?>
                </div>
            <?php else : ?>
                <div class="col-md-8">
                    <div class="alert alert-info">
                        <span class="icon attention"></span>
                        Cette validation va cloturer les démarches associées à l'entretien professionnel de <?php echo $entretien->getAgent()->getDenomination(); ?>.
                    </div>
                </div>
                <div class="pull-right">
                    <br/>
                    <?php if ($dateOk AND $canValiderResponsable) : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::validerElementAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/valider-element', ['entretien' => $entretien->getId(), 'type' => 'DRH'], [], true); ?>"
                                class="btn btn-success action ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon validation-do"></span>
                            Validation de la DRH
                        </a>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<style>
    h3.categorie {
        border-bottom: 1px solid #31708f;
    }
</style>