version: '2'

services:
  preecog:
    container_name: preecog
    build:
      args:
        PHP_VERSION: 7.0
      context: .
      dockerfile: Dockerfile
    ports:
     - "8112:80"
     - "8111:443"
    volumes:
     - .:/app
     - /tmp:/tmp
    working_dir: /app
