version: '2'

services:
  preecog:
    container_name: preecog
    build:
      args:
        PHP_VERSION: 7.0
      context: .
    ports:
      - "8111:80"
      - "443:443"
    volumes:
      - .:/app
      - /tmp:/tmp
    working_dir: /app