version: '2'

services:
  preecog:
    container_name: preecog
    build:
      args:
        PHP_VERSION: 7.3
      context: .
    ports:
      - "8111:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - /tmp:/tmp
    working_dir: /var/www/html