###########################################################################################
#
#                               Image pour le dev.
#
#         Montage des sources attendu dans le volume "/webapp" du container.
#
###########################################################################################

FROM php:7.0-apache

LABEL maintainer="Bertrand GAUTHIER <bertrand.gauthier at unicaen.fr>"

# Mise à niveau de la distrib et installation des packages requis.
RUN apt-get update
RUN apt-get install -y \
        ghostscript \
        git \
        libaio1 \
        libcurl4-openssl-dev \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libldap2-dev \
        libmcrypt-dev \
        libmemcached-dev \
        libssl-dev \
        libxml2-dev \
        make \
        netcat-openbsd \
        ssl-cert \
        subversion \
        unzip \
        vim \
        wget \
        zlib1g-dev
RUN apt-get install -y \
        libpq-dev
RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu && \
    docker-php-ext-configure opcache --enable-opcache && \
    docker-php-ext-install -j$(nproc) \
        curl \
        gd \
        gettext \
        iconv \
        intl \
        ldap \
        mbstring \
        opcache \
        pdo \
        pdo_mysql \
        soap \
        zip
RUN docker-php-ext-install -j$(nproc) \
        pdo_pgsql
RUN rm -rf /var/lib/apt/lists/*

# Installation d'extensions PECL
RUN pear config-set http_proxy "$HTTP_PROXY" && \
    pecl install xdebug && docker-php-ext-enable xdebug && \
    pecl install memcached && docker-php-ext-enable memcached

# Config PHP.
ADD docker/php.conf /usr/local/etc/php/conf.d/webapp.ini
#ADD docker/php-opcache.ini /usr/local/etc/php/conf.d/01-opcache.ini

# Configuration et activation des sites Apache
ADD docker/apache-ports.conf    /etc/apache2/ports.conf
ADD docker/apache-site.conf     /etc/apache2/sites-available/webapp.conf
RUN a2enmod alias rewrite ssl && \
    a2ensite webapp

# Install Composer.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
