<?php

/**
 * @see \Carriere\Controller\CorrespondanceController::afficherAgentsAction();
 * @var Correspondance $correspondance
 * @var Agent[] $agents
 * @var AgentGrade[] $agentGrades
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentGrade;
use Application\Provider\Privilege\AgentPrivileges;
use Carriere\Entity\Db\Correspondance;

$now = new DateTime();

?>

<dl class="row">

</dl>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-4"> Correspondance </dt>
            <dd class="col-md-8">[#<?php echo $correspondance->getId(); ?>] <?php echo $correspondance->getLibelleLong(); ?></dd>
<!--            <dt class="col-md-4"> #Agent </dt>-->
<!--            <dd class="col-md-8"> --><?php //echo count($agents); ?><!--</dd>-->
            <dt class="col-md-4"> #AgentGrade </dt>
            <dd class="col-md-8"> <?php echo count($agentGrades); ?></dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-5"> Date ouverture </dt>
            <dd class="col-md-7"> <?php echo ($correspondance->getDateDebut())?$correspondance->getDateDebut()->format('d/m/Y'):"---"; ?>  </dd>
            <dt class="col-md-5"> Date fermeture </dt>
            <dd class="col-md-7"> <?php echo ($correspondance->getDateFin())?$correspondance->getDateFin()->format('d/m/Y'):"---"; ?></dd>
        </dl>
    </div>
</div>


<table class="table table-condensed">
    <thead>
        <tr>
            <th> Id </th>
            <th> Agent </th>
            <th> Début </th>
            <th> Fin </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($agentGrades  as $agent) : ?>
        <tr <?php if ($agent->estFini($now)) echo 'class="historise"'; ?> >
            <td> <?php echo $agent->getId(); ?> </td>
            <td>
                <?php if ($this->isAllowed($agent->getAgent(), AgentPrivileges::AGENT_AFFICHER)) : ?>
                    <a class="linkexterne" id="<?php echo $agent->getAgent()->getId(); ?>" href="">
                        <?php echo $agent->getAgent()->getDenomination(); ?>
                    </a>
                <?php else : ?>
                    <?php echo $agent->getAgent()->getDenomination(); ?>
                <?php endif; ?>
            </td>
            <td> <?php echo ($agent->getDateDebut()) ? $agent->getDateDebut()->format('d/m/Y') : "---"; ?> </td>
            <td> <?php echo ($agent->getDateFin()) ? $agent->getDateFin()->format('d/m/Y') : "---"; ?> </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>



<script>
    $('a.linkexterne').on('click',function(e) {
        e.preventDefault();
        $('.modal').modal("hide");
        window.location = 'agent/afficher/' + $(this).attr('id');
    });
</script>


