<?php

/**
 * @see \Carriere\Controller\CorrespondanceController::indexAction()
 * @var Correspondance[] $correspondances
 */

use Carriere\Entity\Db\Correspondance;
use Carriere\Provider\Privilege\CorpsPrivileges;

$canAfficher = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_AFFICHER));

$this->headTitle("Liste des correspondances");
?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Liste des correspondances
            <span class="badge">
                <?php echo count($correspondances); ?>
            </span>
        </h1>
    </div>
    <div class="col-md-4">
        <div class="alert alert-info">
            <span class="icon icon-synchroniser"></span>
            Synchoniser depuis Octopus
        </div>
    </div>
</div>

<table class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th style="width:70%;"> Libellé </th>
        <th> #Agent/Grade </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($correspondances as $correspondance): ?>
        <tr>
            <td>
                <span
                    title="<?php echo $correspondance->generateTooltip(); ?>"
                    data-toggle="tooltip" data-html="true"
                >
                <?php echo $correspondance->getLibelleLong(); ?>
                </span>
            </td>
            <td> <?php echo count($correspondance->getAgentGrades()); ?> </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Carriere\Controller\CorrespondanceController::afficherAgentsAction() */ ?>
                        href="<?php echo $this->url('correspondance/afficher-agents', ['correspondance' => $correspondance->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                                        <span class="icon users" data-toggle="tooltip" data-html="true"
                                              title="Afficher les agents ayant cette correpondance"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('.datatable').DataTable({
            paging: false,
        });
    });
</script>