<?php

/**
 * @see \Carriere\Controller\CorrespondanceController::indexAction()
 * @var Correspondance[] $correspondances
 */

use Carriere\Entity\Db\Correspondance;
use Carriere\Provider\Privilege\CorpsPrivileges;

$date = new DateTime();
$correspondances = array_filter($correspondances, function (Correspondance $a) use ($date) { return $a->getDateFermeture() === null OR $a->getDateFermeture() > $date;});

$canAfficher = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_AFFICHER));

$this->headTitle("Liste des correspondances");
?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Liste des correspondances
            <span class="badge">
                <?php echo count($correspondances); ?>
            </span>
        </h1>
    </div>
    <div class="col-md-3">
        <div class="alert alert-info">
            <span class="icon icon-synchroniser"></span>
            Données synchronisées
        </div>
    </div>
</div>

<a href="<?php echo $this->url('carriere/correspondance-type'); ?>"
   class="btn btn-secondary"
>
    <span class="icon icon-lister"></span>
    Accéder aux types de correspondance
</a>

<table class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th style="width:70%;"> Libellé </th>
        <th> Type </th>
        <th> #Agent/Grade </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($correspondances as $correspondance): ?>
        <tr>
            <td>
                <span
                    title="<?php echo $correspondance->generateTooltip(); ?>"
                    data-bs-toggle="tooltip" data-bs-html="true"
                >
                <?php echo $correspondance->getLibelleLong(); ?>
                #
                <?php echo $this->correspondance($correspondance); ?>
                </span>
            </td>
            <td>
                <?php if ($correspondance->getType()) : ?>
                    <span title="<?php echo $correspondance->getType()->getLibelleLong(); ?>">
                        <?php echo $correspondance->getType()->getLibelleCourt(); ?>
                    </span>
                <?php else : ?>
                    Aucun
                <?php endif; ?>
            </td>
            <td> <?php echo count($correspondance->getAgentGrades()); ?> </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Carriere\Controller\CorrespondanceController::afficherAgentsAction() */ ?>
                        href="<?php echo $this->url('correspondance/afficher-agents', ['correspondance' => $correspondance->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                                        <span class="icon users" data-bs-toggle="tooltip" data-bs-html="true"
                                              title="Afficher les agents ayant cette correpondance"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('.datatable').DataTable({
            paging: false,
        });
    });
</script>