<?php


use Agent\Entity\Db\Agent;
use Carriere\Entity\Db\Correspondance;
use Carriere\Provider\Privilege\CorrespondancePrivileges;

/**
 * @see \Carriere\Controller\CorrespondanceController::indexAction()
 * @var Correspondance[] $specialites ,
 * @var Agent[] $agents ,
 * @var array $dictionnaire ,
 * @var bool $avecAgent ,
 */


$date = new DateTime();
$correspondances = array_filter($specialites, function (Correspondance $a) use ($date) {
    return $a->getDateFin() === null or $a->getDateFin() > $date;
});

$canAfficher = $this->isAllowed(CorrespondancePrivileges::getResourceId(CorrespondancePrivileges::CORRESPONDANCE_AFFICHER));
$canLister = $this->isAllowed(CorrespondancePrivileges::getResourceId(CorrespondancePrivileges::CORRESPONDANCE_LISTER_AGENTS));
$canAjouter = $this->isAllowed(CorrespondancePrivileges::getResourceId(CorrespondancePrivileges::CORRESPONDANCE_AJOUTER));
$canModifier = $this->isAllowed(CorrespondancePrivileges::getResourceId(CorrespondancePrivileges::CORRESPONDANCE_MODIFIER));
$canSupprimer = $this->isAllowed(CorrespondancePrivileges::getResourceId(CorrespondancePrivileges::CORRESPONDANCE_SUPPRIMER));

$this->headTitle("Liste des spécialités");
?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Liste des spécialités
            <span class="badge">
                <?php echo count($correspondances); ?>
            </span>
        </h1>
    </div>
    <div class="col-md-3">
        <a href="<?php echo $this->url('carriere/correspondance-type'); ?>"
           class="btn btn-secondary"
        >
            <span class="icon icon-lister"></span>
            Accéder aux types de spécialité
        </a>
    </div>
</div>

<?php if ($canAjouter) : ?>
    <?php /** @see \Carriere\Controller\CorrespondanceController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('correspondance/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter une spécialité
    </a>
<?php endif; ?>

<div class="col-md-6 alert alert-info" style="margin-top: 1rem;">
    <span class="icon icon-refresh"></span>
    Données synchronisées
    <?php if ($avecAgent) : ?>
        <br>
        <span class="icon icon-information"></span>
        Seules les spécialités avec au moins un agent·e sont présentées
    <?php endif; ?>
</div>


<table class="datatable table table-condensed table-hover" id="specialites">
    <thead>
    <tr>
        <th class="col-md-1"> Type</th>
        <th class="col-md-2"> Code</th>
        <th class="col-md-5"> Libellé</th>
        <th class="col-md-1"> #Agent·e</th>
        <th class="col-md-2"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($specialites as $specialite): ?>
        <?php if (!$avecAgent or (isset($dictionnaire[$specialite->getId()]) and $dictionnaire[$specialite->getId()] !== 0)) : ?>
            <tr>
                <td data-column-id="Type">
                    <?php if ($specialite->getType()) : ?>
                        <span title="<?php echo $specialite->getType()->getLibelleLong(); ?>">
                        <code><?php echo $specialite->getType()->getLibelleCourt(); ?></code>
                    </span>
                    <?php else : ?>
                        Aucun
                    <?php endif; ?>
                </td>
                <td data-column-id="Code">
                    <code><?php echo $specialite->getCategorie(); ?></code>
                </td>
                <td data-column-id="Libellé">
                <span
                        title="<?php echo $specialite->generateTooltip(); ?>"
                        data-bs-toggle="tooltip" data-bs-html="true"
                >
                <?php echo $specialite->getLibelleLong(); ?>
                </span>
                </td>
                <td> <?php echo $dictionnaire[$specialite->getId()] ?? 0; ?> </td>
                <td data-column-id="Action">
                    <?php if ($canAfficher) : ?>
                        <a
                                <?php /** @see \Carriere\Controller\CorrespondanceController::afficherAction() */ ?>
                                href="<?php echo $this->url('correspondance/afficher', ['correspondance' => $specialite->getId()], [], true); ?>"
                                class="action secondary ajax-modal"
                        >
                            <span class="icon icon-voir"></span>
                            Afficher
                        </a>
                    <?php endif; ?>
                    <?php if ($canLister) : ?>
                        <br>
                        <a
                                <?php /** @see \Carriere\Controller\CorrespondanceController::afficherAgentsAction() */ ?>
                                href="<?php echo $this->url('correspondance/afficher-agents', ['correspondance' => $specialite->getId()], [], true); ?>"
                                class="action secondary ajax-modal"
                        >
                            <span class="icon icon-users"></span>
                            Lister les agents
                        </a>
                    <?php endif; ?>
                    <?php if ($canModifier) : ?>
                        <br>
                        <?php /** @see \Carriere\Controller\CorrespondanceController::modifierAction() */ ?>
                        <a href="<?php echo $this->url('correspondance/modifier', ['correspondance' => $specialite->getId()], [], true); ?>"
                           class="ajax-modal action primary" data-event="modification">
                            <span class="icon icon-editer"></span>
                            Modifier
                        </a>
                    <?php endif; ?>
                    <?php if ($canSupprimer) : ?>
                        <br>
                        <?php /** @see \Carriere\Controller\CorrespondanceController::supprimerAction() */ ?>
                        <a href="<?php echo $this->url('correspondance/supprimer', ['correspondance' => $specialite->getId()], [], true); ?>"
                           class="ajax-modal action danger" data-event="modification">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('table#specialites').DataTable({
            autoWidth: false,
            stateSave: true,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [4], orderable: false}
            ],
            'order': [[0, 'asc'], [1, 'asc']],
        });
    });
</script>