<?php

use Carriere\Entity\Db\Niveau;
use Carriere\Provider\Privilege\NiveaucarrierePrivileges;

/**
 * @see \Carriere\Controller\NiveauController::indexAction()
 * @var Niveau[] $niveaux
 */

$this->headTitle('Index des niveaux');

$canAfficherNiveau   = $this->isAllowed(NiveaucarrierePrivileges::getResourceId(NiveaucarrierePrivileges::NIVEAUCARRIERE_AFFICHER));
$canAjouterNiveau    = $this->isAllowed(NiveaucarrierePrivileges::getResourceId(NiveaucarrierePrivileges::NIVEAUCARRIERE_AJOUTER));
$canModifierNiveau   = $this->isAllowed(NiveaucarrierePrivileges::getResourceId(NiveaucarrierePrivileges::NIVEAUCARRIERE_MODIFIER));
$canHistoriserNiveau = $this->isAllowed(NiveaucarrierePrivileges::getResourceId(NiveaucarrierePrivileges::NIVEAUCARRIERE_HISTORISER));
$canSupprimerNiveau  = $this->isAllowed(NiveaucarrierePrivileges::getResourceId(NiveaucarrierePrivileges::NIVEAUCARRIERE_SUPPRIMER));

$canAction = ($canAfficherNiveau OR $canAjouterNiveau OR $canModifierNiveau OR $canHistoriserNiveau OR $canSupprimerNiveau);
?>

<h1 class="page-header">
    Index des niveaux
</h1>

<?php if ($canAjouterNiveau) : ?>
    <?php /** @see Carriere\Controller\NiveauController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('niveau/ajouter', [], [], true); ?>"
       class="ajax-modal btn btn-primary" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un niveau
    </a>
<?php endif; ?>

<table class="table table-condensed table-hover" id="niveaux">
    <thead>
        <tr>
            <th> Niveau </th>
            <th> Étiquette </th>
            <th> Libelle </th>
            <th> Catégorie </th>
            <?php if ($canAction) : ?>
                <th> Action </th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($niveaux as $niveau) : ?>
            <tr class=" <?php if ($niveau->estHistorise()) echo " historise "; ?>">
                <td class="col-md-1" data-column-id="Niveau"> <?php echo $niveau->getNiveau(); ?> </td>
                <td class="col-md-2" data-column-id="Étiquette"> <?php echo $niveau->getEtiquette(); ?> </td>
                <td class="col-md-5" data-column-id="Libellé">
                    <?php echo $niveau->getLibelle(); ?>
                    <?php if ($niveau->getDescription()) : ?>
                        <span class="icon icon-information" title="<?php echo $niveau->getDescription(); ?> "
                              data-bs-toggle="tooltip" data-bs-html="true"
                        ></span>
                    <?php endif; ?>
                </td>
                <td  class="col-md-2" data-column-id="Catégorie">
                    <?php if ($niveau->getCategorie()) : ?>
                        <?php echo $niveau->getCategorie()->getLibelle(); ?>
                    <?php else : ?>
                        <span class="missing-data">Aucune catégorie</span>
                    <?php endif; ?>
                </td>
                <?php if ($canAction) : ?>
                    <td class="col-md-2 action" data-column-id="Action">
<!--                    --><?php //if ($canAfficherNiveau) : ?>
<!--                            <span class="icon icon-voir"></span>-->
<!--                            Afficher-->
<!--                    --><?php //endif; ?>
                    <?php if ($canModifierNiveau) : ?>
<!--                        <br/>-->
                        <?php /** @see \Carriere\Controller\NiveauController::modifierAction() */?>
                        <a href="<?php echo $this->url('niveau/modifier', ['niveau' => $niveau->getId()], [], true); ?>"
                           class="action primary ajax-modal" data-event="modification"
                           data-toogle="tooltip" data-bs-html="true" title="Modifier le niveau <?php echo $niveau->getEtiquette(); ?>"
                        >
                            <span class="icon icon-editer"></span>
                            Modifier
                        </a>
                    <?php endif; ?>
                    <?php if ($canHistoriserNiveau) : ?>
                    <br>
                        <?php if($niveau->estNonHistorise()) : ?>
                            <?php /** @see \Carriere\Controller\NiveauController::historiserAction() */?>
                            <a href="<?php echo $this->url('niveau/historiser', ['niveau' => $niveau->getId()], [], true); ?>"
                               class="action warning"
                               data-toogle="tooltip" data-bs-html="true" title="Historiser le niveau <?php echo $niveau->getEtiquette(); ?>"
                            >
                                <span class="icon icon-historiser"></span>
                                Historiser
                            </a>
                        <?php else : ?>
                            <?php /** @see \Element\Controller\NiveauController::restaurerAction() */?>
                            <a href="<?php echo $this->url('niveau/restaurer', ['niveau' => $niveau->getId()], [], true); ?>"
                               class="action warning"
                               data-toogle="tooltip" data-bs-html="true" title="Rstaurer le niveau <?php echo $niveau->getEtiquette(); ?>"
                            >
                                <span class="icon icon-restaurer"></span>
                                Restaurer
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canSupprimerNiveau) : ?>
                        <br/>
                        <?php /** @see \Carriere\Controller\NiveauController::supprimerAction() */?>
                        <a href="<?php echo $this->url('niveau/supprimer', ['niveau' => $niveau->getId()], [], true); ?>"
                           class="action danger ajax-modal" data-event="modification"
                           data-toogle="tooltip" data-bs-html="true" title="Supprimer le niveau <?php echo $niveau->getEtiquette(); ?>"
                        >
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </a>
                    <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $("table#niveaux").DataTable({
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [4], orderable: false }
            ]
        });
    });
</script>