<?php

use Carriere\Entity\Db\Niveau;

/**
 * @see \Carriere\Controller\NiveauController::indexAction()
 * @var Niveau[] $niveaux
 */

$this->headTitle('Index des niveaux');

$canAjouterNiveau = true;
$canModifierNiveau = true;
$canHistoriserNiveau = true;
$canSupprimerNiveau = true;

?>

<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Index des niveaux
        </h1>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterNiveau) : ?>
            <?php /** @see \Element\Controller\NiveauController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('element/niveau/ajouter', [], [], true); ?>"
               class="ajax-modal btn btn-primary" data-event="modification"
            >
                <span class="icon icon-ajouter"></span>
                Ajouter un niveau
            </a>
        <?php endif; ?>
    </div>
</div>

<table class="table table-condensed">
    <thead>
        <tr>
            <th> Niveau </th>
            <th> Étiquette </th>
            <th> Libelle </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($niveaux as $niveau) : ?>
            <tr>
                <td> <?php echo $niveau->getNiveau(); ?> </td>
                <td> <?php echo $niveau->getEtiquette(); ?> </td>
                <td>
                    <?php echo $niveau->getLibelle(); ?>
                    <?php if ($niveau->getDescription()) : ?>
                        <span class="icon information" title="<?php echo $niveau->getDescription(); ?> "
                              data-bs-toggle="tooltip" data-bs-html="true"
                        ></span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($canModifierNiveau) : ?>
                        <?php /** @see \Element\Controller\NiveauController::modifierAction() */?>
                        <a href="<?php echo $this->url('element/niveau/modifier', ['maitrise' => $niveau->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                           data-toogle="tooltip" data-bs-html="true" title="Modifier le niveau <?php echo $niveau->getEtiquette(); ?>"
                        >
                            <span class="icon icon-editer"></span></a>
                    <?php endif; ?>
                    <?php if ($canHistoriserNiveau) : ?>
                        <?php if($niveau->estNonHistorise()) : ?>
                            <?php /** @see \Element\Controller\NiveauController::historiserAction() */?>
                            <a href="<?php echo $this->url('element/niveau/historiser', ['maitrise' => $niveau->getId()], [], true); ?>"
                               data-toogle="tooltip" data-bs-html="true" title="Historiser le niveau <?php echo $niveau->getEtiquette(); ?>"
                            >
                                <span class="icon icon-historiser"></span></a>
                        <?php else : ?>
                            <?php /** @see \Element\Controller\NiveauController::restaurerAction() */?>
                            <a href="<?php echo $this->url('element/niveau/restaurer', ['maitrise' => $niveau->getId()], [], true); ?>"
                               data-toogle="tooltip" data-bs-html="true" title="Rstaurer le niveau <?php echo $niveau->getEtiquette(); ?>"
                            >
                                <span class="icon icon-restaurer"></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canSupprimerNiveau) : ?>
                        <?php /** @see \Element\Controller\NiveauController::supprimerAction() */?>
                        <a href="<?php echo $this->url('element/niveau/supprimer', ['maitrise' => $niveau->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                           data-toogle="tooltip" data-bs-html="true" title="Supprimer le niveau <?php echo $niveau->getEtiquette(); ?>"
                        >
                            <span class="icon icon-retirer"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>