<?php

use UnicaenGlossaire\Entity\Db\Definition;
use UnicaenGlossaire\Provider\Privilege\DefinitionPrivileges;

/**
 * @see \UnicaenGlossaire\Controller\DefinitionController::indexAction()
 * @var Definition[] $definitions
 */

$this->headTitle("Glossaire");

$canAfficher    = $this->isAllowed(DefinitionPrivileges::getResourceId(DefinitionPrivileges::DEFINITION_AFFICHER));
$canAjouter     = $this->isAllowed(DefinitionPrivileges::getResourceId(DefinitionPrivileges::DEFINITION_AJOUTER));
$canModifier    = $this->isAllowed(DefinitionPrivileges::getResourceId(DefinitionPrivileges::DEFINITION_MODIFIER));
$canHistoriser  = $this->isAllowed(DefinitionPrivileges::getResourceId(DefinitionPrivileges::DEFINITION_HISTORISER));
$canSupprimer   = $this->isAllowed(DefinitionPrivileges::getResourceId(DefinitionPrivileges::DEFINITION_SUPPRIMER));
?>

<?php
    /** @see \UnicaenGlossaire\View\Helper\DictionnaireGenerationViewHelper */
    echo $this->dictionnaireGeneration(['historise' => false]);
?>


<div class="row">
    <div class="col-sm-8 col-md-6">
        <h1 class="page-header">
            Glossaire
        </h1>
    </div>
    <div class="pull-right main-button">
        <?php if ($canAjouter) : ?>
            <a  <?php /** @see \UnicaenGlossaire\Controller\DefinitionController::ajouterAction() */?>
                href="<?php echo $this->url('definition/ajouter', [], [], true); ?>"
                class="btn btn-primary action ajax-modal" data-event="modification">
                <span class="icon ajouter"></span> Ajouter une définition
            </a>
        <?php endif; ?>
    </div>
</div>

<dl class="dl-horizontal" id="glossaire">
<?php foreach ($definitions as $definition) : ?>
    <?php if ($definition->estNonHistorise() OR ($definition->estHistorise() AND $canModifier)) : ?>
        <dt class="<?php echo ($definition->estHistorise())?"historise":"";?>">
            <?php echo $definition->getTerme(); ?>
            <span class="control">
                <?php if($canAfficher) : ?>
                    <a  <?php /** @see \UnicaenGlossaire\Controller\DefinitionController::afficherAction() */?>
                            href="<?php echo $this->url('definition/afficher', ['definition' => $definition->getId()], [], true); ?>"
                            class="ajax-modal" >
                        <span class="icon voir"></span></a>
                <?php endif; ?>
                <?php if($canModifier) : ?>
                    <a  <?php /** @see \UnicaenGlossaire\Controller\DefinitionController::modifierAction() */?>
                        href="<?php echo $this->url('definition/modifier', ['definition' => $definition->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                        <span class="icon editer"></span></a>
                <?php endif; ?>
                <?php if($canHistoriser) : ?>
                    <?php if ($definition->estNonHistorise()) : ?>
                        <a  <?php /** @see \UnicaenGlossaire\Controller\DefinitionController::historiserAction() */?>
                                href="<?php echo $this->url('definition/historiser', ['definition' => $definition->getId()], [], true); ?>"
                                >
                            <span class="icon historiser"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \UnicaenGlossaire\Controller\DefinitionController::restaurerAction() */?>
                                href="<?php echo $this->url('definition/restaurer', ['definition' => $definition->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if($canSupprimer) : ?>
                    <a  <?php /** @see \UnicaenGlossaire\Controller\DefinitionController::modifierAction() */?>
                            href="<?php echo $this->url('definition/supprimer', ['definition' => $definition->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification">
                        <span class="icon detruire"></span></a>
                <?php endif; ?>
            </span>
        </dt>
        <dd class="<?php echo ($definition->estHistorise())?"historise":"";?>">
            <?php echo $definition->getDefinition(); ?>
        </dd>
    <?php endif; ?>
<?php endforeach; ?>
</dl>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $("abbr").each(function() {
        $(this).html(display_definition($(this).text()));
    });
</script>