<?php

use Application\Entity\Db\Metier;
use Application\Entity\Db\ParcoursDeFormation;

/**
 * @var ParcoursDeFormation $parcours
 * @var Metier $reference
 */

$nogroup = "ZZZZ";
$formationArray = [];
foreach ($parcours->getFormations() as $formationP) {
    $formation = $formationP->getFormation();
    $groupe = ($formation->getGroupe())?$formation->getGroupe()->getLibelle():$nogroup;
    $formationArray[$groupe][] = $formation;
}

ksort($formationArray);
?>

<?php echo $this->parcoursDeFormation($parcours, null, ['mode' => 'affichage']); ?>
