<?php

/**
 * @see \Application\Controller\ParcoursDeFormationController::indexAction()
 * @var array $parcours ( type:string => ParcoursDeFormation[] )
 * @var ParcoursDeFormation[] $parcoursCategorie
 * @var ParcoursDeFormation[] $parcoursMetier
 * @var ParcoursDeFormation[] $parcoursVide
 */

use Application\Entity\Db\ParcoursDeFormation;

$droits = [];

$typeLabel = [
        ParcoursDeFormation::TYPE_METIER => 'metier',
        ParcoursDeFormation::TYPE_DOMAINE => 'domaine',
        ParcoursDeFormation::TYPE_CATEGORIE => 'categorie',
        null => 'sans',
]
?>

<h1 class="page-header">
    Index des parcours de formation
</h1>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <?php foreach($parcours as $type => $listing) : ?>
            <li>
                <a href="#<?php echo $typeLabel[$type] ?>" aria-controls="<?php echo $typeLabel[$type]; ?>" role="tab" data-toggle="tabz" >
                    Parcours de formation <br/>
                    <?php echo ($type)?:"Sans référence"; ?> &nbsp;
                    <span class="badge">
                    <?php echo count($listing); ?>
                </span>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <div class="main-with-tab">

        <div class="tab-content">

            <?php foreach ($parcours as $type => $listing) : ?>
                <?php $typeLibelle = ($type)?:"Sans référence"; ?>
                <div id="<?php echo $typeLabel[$type]; ?>" class="tab-pane " role="tabpanel">
                    <?php echo $this->partial('partial/index-parcours', ['parcours' => $listing, 'type' => $type, 'droits' => $droits], [], true); ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('.datatable').DataTable( {
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "categorie";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
