<?php

/**
 * @var Form $form
 */

use Application\Entity\Db\ParcoursDeFormation;use Laminas\Form\Form;

?>

<?php echo $this->form($form); ?>

<script>
    $('select#type').parent().hide();

    function selectType() {
        $('select#metier').parent().hide();
        $('select#categorie').parent().hide();
        let type = $('select#type').find(":selected").val();
        if (type === '<?php echo ParcoursDeFormation::TYPE_METIER; ?>') $('select#metier').parent().show();
        if (type === '<?php echo ParcoursDeFormation::TYPE_CATEGORIE; ?>') $('select#categorie').parent().show();
    }

    $(document).ready(function() {
        $('select#metier').parent().hide();
        $('select#categorie').parent().hide();
        let type = $('select#type').find(":selected").val();
        if (type === '<?php echo ParcoursDeFormation::TYPE_METIER; ?>') $('select#metier').parent().show();
        if (type === '<?php echo ParcoursDeFormation::TYPE_CATEGORIE; ?>') $('select#categorie').parent().show();
    });

    $('select#type').change(function(){
        $('select#metier').parent().hide();
        $('select#categorie').parent().hide();
        let type = $('select#type').find(":selected").val();
        if (type === '<?php echo ParcoursDeFormation::TYPE_METIER; ?>') $('select#metier').parent().show();
        if (type === '<?php echo ParcoursDeFormation::TYPE_CATEGORIE; ?>') $('select#categorie').parent().show();
    });

    $(document).ready(function() {
        tinymce.remove();
        tinymce.init({
            selector: '.type2',
            toolbar: 'newdocument undo redo | bold italic underline removeformat | bullist',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck : true,
            branding: false,
            menu: {},
            body_id: 'description',
            setup: function (editor) {
                editor.on("focusout", function () {
                    console.log(tinymce.get('description').getContent());
                    $('textarea').val(tinymce.get('description').getContent());
                });
            }
        });
    });

    $('select').selectpicker();
</script>

<style>
    .form-control {
        height:auto;
    }
</style>