<?php

use Application\Entity\Db\FichePoste;
use FichePoste\Provider\Privilege\FichePostePrivileges;

/**
 * @var FichePoste $fiche
 * @var string $mode
 */

$canEditerExpertise = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_MODIFIER);
$date = new DateTime();

?>

<?php if( $fiche->hasExpertise()) : ?>
    <?php $expertises = $fiche->getCurrentExpertises($date); ?>

    <?php if ($mode === 'edition' OR !empty($expertises)) : ?>
        <div class="card panel-info">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h2> Expertises associées au poste </h2>
                    </div>
                    <div class="col-md-6">
                        <?php if($mode === 'edition' AND $canEditerExpertise) : ?>
                            <a <?php /** @see \Application\Controller\FichePosteController::ajouterExpertiseAction() */?>
                                href="<?php echo $this->url('fiche-poste/ajouter-expertise',['fiche-poste' => $fiche->getId()], [], true); ?>"
                                class="btn btn-primary action ajax-modal pull-right"
                                data-event="modification"
                            >
                                <span class="icon icon-editer"></span>
                                Ajouter une expertise
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <ul>
                    <?php foreach ($expertises as $expertise) : ?>
                        <li>
                            <strong><?php echo $expertise->getLibelle(); ?></strong>
                            <?php if($mode === 'edition' AND $canEditerExpertise) : ?>
                                <a <?php /** @see \Application\Controller\FichePosteController::modifierExpertiseAction() */?>
                                    href="<?php echo $this->url('fiche-poste/modifier-expertise',['expertise' => $expertise->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    data-event="modification"
                                    title="Modifier l'expertise"
                                >
                                    <span class="icon icon-editer"></span></a>
                            <?php endif; ?>
                            <?php if ($expertise->estNonHistorise()) : ?>
                                <?php if($mode === 'edition' AND $canEditerExpertise) : ?>
                                    <a <?php /** @see \Application\Controller\FichePosteController::historiserExpertiseAction() */?>
                                        href="<?php echo $this->url('fiche-poste/historiser-expertise',['expertise' => $expertise->getId()], [], true); ?>"
                                        title="Historiser l'expertise"
                                    >
                                        <span class="icon icon-historiser"></span></a>
                                <?php endif; ?>
                            <?php else : ?>
                                <?php if($mode === 'edition' AND $canEditerExpertise) : ?>
                                    <a <?php /** @see \Application\Controller\FichePosteController::restaurerExpertiseAction() */?>
                                        href="<?php echo $this->url('fiche-poste/restaurer-expertise',['expertise' => $expertise->getId()], [], true); ?>"
                                        title="Restaurer l'expertise"
                                    >
                                        <span class="icon icon-restaurer"></span></a>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if($mode === 'edition' AND $canEditerExpertise) : ?>
                                <a <?php /** @see \Application\Controller\FichePosteController::supprimerExpertiseAction() */?>
                                    href="<?php echo $this->url('fiche-poste/supprimer-expertise',['expertise' => $expertise->getId()], [], true); ?>"
                                    title="Supprimer l'expertise"
                                    class="ajax-modal" data-event="modification"
                                >
                                    <span class="icon icon-unchecked"></span></a>
                            <?php endif; ?>
                            <br/>
                            <div>
                                <?php echo $expertise->getDescription(); ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
