<?php

use Application\Entity\Db\FichePoste;
use FichePoste\Provider\Privilege\FichePostePrivileges;
use FichePoste\Provider\Etat\FichePosteEtats;
use FichePoste\Provider\Validation\FichePosteValidations;

/**
 * @var FichePoste $fiche
 */

$canFichePosteModifierEtat = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_ETAT);
$canFichePosteValiderResponsable = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_VALIDER_RESPONSABLE);
$canFichePosteValiderAgent = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_VALIDER_AGENT);
$canFichePosteValiderDrh = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_VALIDER_DRH);

?>

<div class="row">
    <div class="col-md-6">
        <?php if ($fiche->getAgent() !== null) : ?>
            <h2>Validations associées à la fiche de poste</h2>

            <dl>
                <dt> Validation du responsable</dt>
                <dd>
                    <?php $validationResponsable = $fiche->getValidationActiveByTypeCode(FichePosteValidations::VALIDATION_RESPONSABLE); ?>
                    <?php if ($validationResponsable === null) : ?>
                        Aucune validation
                    <?php else : ?>
                        Validée
                        par <?php echo $validationResponsable->getHistoCreateur()->getDisplayName(); ?>
                        le <?php echo $validationResponsable->getHistoCreation()->format('d/m/Y H:i'); ?>.
                    <?php endif; ?>
                </dd>
                <dt> Validation de l'agent</dt>
                <dd>
                    <?php $validationAgent = $fiche->getValidationActiveByTypeCode(FichePosteValidations::VALIDATION_AGENT); ?>
                    <?php if ($validationAgent === null) : ?>
                        Aucune validation
                    <?php else : ?>
                        Validée
                        par <?php echo $validationAgent->getHistoCreateur()->getDisplayName(); ?>
                        le <?php echo $validationAgent->getHistoCreation()->format('d/m/Y H:i'); ?>.
                    <?php endif; ?>
                </dd>
                <dt> Validation de la Direction des Ressources Humaines</dt>
                <dd>
                    <?php $validationDrh = $fiche->getValidationActiveByTypeCode(FichePosteValidations::VALIDATION_DRH); ?>
                    <?php if ($validationDrh === null) : ?>
                        Aucune validation
                    <?php else : ?>
                        Validée
                        par <?php echo $validationDrh->getHistoCreateur()->getDisplayName(); ?>
                        le <?php echo $validationDrh->getHistoCreation()->format('d/m/Y H:i'); ?>.
                    <?php endif; ?>
                </dd>
            </dl>

            <?php if ($canFichePosteValiderResponsable and $validationAgent === null) : ?>
                <?php if ($validationResponsable === null) : ?>
                    <?php /** @see \FichePoste\Controller\ValidationController::validerResponsableAction() **/ ?>
                    <a href="<?php echo $this->url('fiche-poste/validation/valider-responsable', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                       class="btn btn-success ajax-modal" data-event="modification">
                        <span class="icon icon-checked"></span>
                        Valider la fiche de poste (responsable)
                    </a>
                <?php else : ?>
                    <?php /** @see \FichePoste\Controller\ValidationController::revoquerResponsableAction() */ ?>
                    <a href="<?php echo $this->url('fiche-poste/validation/revoquer-responsable', ['fiche-poste' => $fiche->getId(), 'validation' => $validationResponsable->getId()], [], true); ?>"
                       class="btn btn-danger ajax-modal">
                        <span class="icon icon-unchecked"></span>
                        Révoquer la validation (responsable)
                    </a>
                <?php endif; ?>
            <?php endif; ?>
            <?php if ($canFichePosteValiderAgent and $validationResponsable !== null and $validationDrh === null) : ?>
                <?php if ($validationAgent === null) : ?>
                    <?php /** @see \FichePoste\Controller\ValidationController::validerAgentAction() */ ?>
                    <a href="<?php echo $this->url('fiche-poste/validation/valider-agent', ['fiche-poste' => $fiche->getId(), 'type' => FichePosteValidations::VALIDATION_AGENT], [], true); ?>"
                       class="btn btn-success  ajax-modal" data-event="modification">
                        <span class="icon icon-checked"></span>
                        Valider la fiche de poste (agent)
                    </a>
                <?php else : ?>
                    <?php /** @see \FichePoste\Controller\ValidationController::revoquerAgentAction() */ ?>
                    <a href="<?php echo $this->url('fiche-poste/validation/revoquer-agent', ['fiche-poste' => $fiche->getId(), 'validation' => $validationAgent->getId()], [], true); ?>"
                       class="btn btn-danger ajax-modal">
                        <span class="icon icon-unchecked"></span>
                        Révoquer la validation (agent)
                    </a>
                <?php endif; ?>
            <?php endif; ?>
            <?php if ($canFichePosteValiderDrh and $validationAgent !== null) : ?>
                <?php if ($validationDrh === null) : ?>
                    <?php /** @see \FichePoste\Controller\ValidationController::validerDrhAction() */ ?>
                    <a href="<?php echo $this->url('fiche-poste/validation/valider-drh', ['fiche-poste' => $fiche->getId(), 'type' => FichePosteValidations::VALIDATION_AGENT], [], true); ?>"
                       class="btn btn-success  ajax-modal" data-event="modification">
                        <span class="icon icon-checked"></span>
                        Valider la fiche de poste (DRH)
                    </a>
                <?php else : ?>
                    <?php /** @see \FichePoste\Controller\ValidationController::revoquerDrhAction() */ ?>
                    <a href="<?php echo $this->url('fiche-poste/validation/revoquer-drh', ['fiche-poste' => $fiche->getId(), 'validation' => $validationAgent->getId()], [], true); ?>"
                       class="btn btn-danger ajax-modal">
                        <span class="icon icon-unchecked"></span>
                        Révoquer la validation (DRH)
                    </a>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <?php if ($fiche->getAgent() !== null) : ?>
            <h2>État de la fiche de poste</h2>
            <?php if ($fiche->getEtatActif()) : ?>
                <?php $etattype = $fiche->getEtatActif()->getType(); ?>
                <?php echo $this->etattype($etattype); ?>
                <?php if ($etattype->getCode() === FichePosteEtats::ETAT_CODE_OK) : ?>
                    Validité : <?php echo ($fiche->getFinValidite()) ? $fiche->getFinValidite()->format('d/m/Y') : "En cours"; ?>
                <?php else : ?>
                    La fiche de poste n'est pas encore visée par l'agent·e.
                <?php endif; ?>
                <?php else : ?>
                    Pas d'état pour cette fiche
                <?php endif; ?>

            <br/>
            <?php if ($canFichePosteModifierEtat) : ?>
                <a
                    <?php /** @see \Application\Controller\FichePosteController::changerEtatAction() */ ?>
                        href="<?php echo $this->url('fiche-poste/changer-etat', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                        class="btn btn-primary action ajax-modal"
                        data-event="modification"
                >
                    <span class="icon icon-editer"></span>
                    Changer l'état de la fiche
                </a>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
