<?php

/**
 * @var Formation[] $formations
 * @var boolean[] $droits
 */

use Application\Entity\Db\Formation;

$canAfficher = $droits['afficher'];
$canAjouter = $droits['ajouter'];
$canAjouterInstance = $droits['ajouter'];
$canEditer = $droits['editer'];
$canHistoriser = $droits['historiser'];
$canDetruire = $droits['detruire'];

?>

<div class="row">
    <div class="col-md-8">
        <h2>
            Formations
        </h2>
    </div>
    <div class="col-md-4">
        <?php if ($canAjouter) : ?>
            <br/>


            <a
                <?php /** @see FormationController::ajouterThemeAction() */ ?>
                href="<?php echo $this->url('formation/ajouter', [], [], true); ?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification">
                <span class="icon ajouter"></span>
                Ajouter une formation
            </a>
        <?php endif; ?>
    </div>
</div>

<br/>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> Thème </th>
        <th> Groupe </th>
<!--        <th> Lien </th>-->
        <th> Modification </th>
        <th style="width:9rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($formations as $formation) : ?>
        <tr>
            <td> <?php echo $formation->getLibelle(); ?> </td>
            <td> <?php echo ($formation->getTheme())?$formation->getTheme()->getLibelle():""; ?> </td>
            <td> <?php echo ($formation->getGroupe())?$this->formationGroupe($formation->getGroupe()):""; ?> </td>
<!--            <td>-->
<!--                --><?php //if ($formation->getLien() !== null) : ?>
<!--                    <a href="--><?php //echo $formation->getLien(); ?><!--">-->
<!--                        --><?php //echo $formation->getLien(); ?>
<!--                    </a>-->
<!--                --><?php //endif; ?>
<!--            </td>-->
            <td>
                <small>
                    <?php echo $formation->getHistoModification()->format('d/m/Y à H:i'); ?>
                    <br/>
                    <?php echo $formation->getHistoModificateur()->getDisplayName(); ?>
                </small>
            </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see FormationController::afficherAction() */ ?>
                        href="<?php echo $this->url('formation/afficher', ['formation' => $formation->getId()], [], true); ?>"
                    >
                        <span class="icon voir" title="Afficher la formation"></span></a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <a
                        <?php /** @see FormationController::editerAction() */ ?>
                        href="<?php echo $this->url('formation/editer', ['formation' => $formation->getId()], [], true); ?>"
                    >
                        <span class="icon editer" title="Modifier la formation"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($formation->estNonHistorise()) : ?>
                        <a
                            <?php /** @see FormationController::historiserAction() */ ?>
                            href="<?php echo $this->url('formation/historiser', ['formation' => $formation->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser la formation"></span></a>
                    <?php else : ?>
                        <a
                            <?php /** @see FormationController::restaurerAction() */ ?>
                            href="<?php echo $this->url('formation/restaurer', ['formation' => $formation->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer la formation"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <a
                        <?php /** @see FormationController::detruireAction() */ ?>
                        href="<?php echo $this->url('formation/detruire', ['formation' => $formation->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer la formation"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>