<?php

/**
 * @var Form $form
 */

use Zend\Form\Form;

?>

<?php echo $this->form($form); ?>

<script>
    $('select').selectpicker();

    let macros = [
        {title: 'Date : aujourd\'hui', description: 'Date du jour (dd/mm/yyyy)', content: 'VAR[DATE#aujourdhui]'},
        {title: 'EMC2 : Nom', description: 'Nom de l\'application', content: 'VAR[EMC2#nom]'},
        {title: 'EMC2 : Lien', description: 'Lien vers l\'application', content: 'VAR[EMC2#lien]'},
        {title: 'Campagne : année', description: 'Année de la campagne d\'entretien professionnel', content: 'VAR[CAMPAGNE#annee]'},
        {title: 'Campagne : début', description: 'Date de début de la campagne d\'entretien professionnel', content: 'VAR[CAMPAGNE#debut]'},
        {title: 'Campagne : fin', description: 'Date de fin de la campagne d\'entretien professionnel', content: 'VAR[CAMPAGNE#fin]'},
        {title: 'Entretien : agent', description: 'Agent passant l\'entretien', content: 'VAR[ENTRETIEN#agent]'},
        {title: 'Entretien : responsable', description: 'Responsable faisant passer l\'entretien', content: 'VAR[ENTRETIEN#responsable]'},
        {title: 'Entretien : date', description: 'Date de l\'entretien', content: 'VAR[ENTRETIEN#date]'},
        {title: 'Entretien : heure', description: 'Heure de l\'entretien', content: 'VAR[ENTRETIEN#heure]'},
        {title: 'Entretien : lieu', description: 'Lieu de l\'entretien', content: 'VAR[ENTRETIEN#lieu]'},
    ];

    $(document).ready(function() {
        tinymce.remove();
        tinymce.init({
            selector: '.sujet',
            toolbar: 'newdocument undo redo | template',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists template',
            templates: macros,
            statusbar: true,
            browser_spellcheck: true,
            branding: false,
            menu: {},
            body_id: 'motif',
            setup: function (editor) {
                editor.on("focusout", function () {
                    $('textarea#sujet').val(tinymce.get('sujet').getContent());
                });
            }
        });
        tinymce.init({
            selector: '.corps',
            toolbar: 'newdocument undo redo | bold italic | bullist | template',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists template',
            templates: macros,
            statusbar: true,
            browser_spellcheck: true,
            branding: false,
            menu: {},
            body_id: 'motif',
            setup: function (editor) {
                editor.on("focusout", function () {
                    $('textarea#corps').val(tinymce.get('corps').getContent());
                });
            }
        });
    });
</script>
