<?php

use Formation\Entity\Db\Formateur;

/**
 * @see \Formation\Controller\FormateurController::afficherAction()
 * @var Formateur $formateur
 */

$this->headTitle("Affichage du formateur [".$formateur->getDenomination()."]");

?>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-6"> Type </dt>
            <dd class="col-md-6">
                <?php if ($formateur->getType()) : ?>
                    <?php echo Formateur::TYPES[$formateur->getType()]; ?>
                <?php else : ?>
                    <span class="text-warning">
                        <span class="icon icon-attention"></span>
                        Aucun type connu
                    </span>
                <?php endif; ?>
            </dd>
            <dt class="col-md-6"> Dénomination </dt>
            <?php if ($formateur->getDenomination()) : ?>
                <?php echo $formateur->getDenomination(); ?>
            <?php else : ?>
                <span class="text-warning">
                        <span class="icon icon-attention"></span>
                        Aucune dénomination
                    </span>
            <?php endif; ?>
            <dt class="col-md-6"> Adresse électronique </dt>
            <?php if ($formateur->getEmail()) : ?>
                <?php echo $formateur->getEmail(); ?>
            <?php else : ?>
                <span class="text-warning">
                        <span class="icon icon-attention"></span>
                        Aucune adresse électronique connue
                    </span>
            <?php endif; ?>
            <?php if ($formateur->getAttachement() !== null) : ?>
                <dt class="col-md-6"> Attachement </dt>
                <dd class="col-md-6"> <?php echo $formateur->getAttachement(); ?> </dd>
            <?php endif; ?>
        </dl>
    </div>
    <div class="col-md-6">
        <dl>
            <dt> Session·s <span class="badge"><?php echo count($formateur->getSessions()); ?></span></dt>
            <dd>
                <ul>
                <?php foreach ($formateur->getSessions() as $session) : ?>
                    <li>
                        <?php echo $session->getFormation()->getLibelle(); ?>
                        (<?php echo $session->getPeriode(); ?>)
                    </li>
                <?php endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>
</div>
