<?php

use Formation\Entity\Db\Formateur;
use Formation\Entity\Db\Session;
use Formation\Provider\Privilege\FormationinstancePrivileges;

/**
 * @see \Formation\Controller\FormateurController::mesSessionsAction()
 * @var Formateur $formateur
 * @var Session[] $sessionsActives
 * @var Session[] $sessionsInactives
 */

$this->headTitle('Mes sessions');

?>

<h1 class="page-header">
    Mes sessions
</h1>

<h2> Sessions de formation active </h2>

<?php if (empty($sessionsActives)) : ?>
    <em> Aucune session de formations</em>
<?php else : ?>
    <table class="table table-condensed" id="actives">
        <thead>
        <tr>
            <th class="libelle"> Libellé</th>
            <th class="periode"> Période</th>
            <th class="etat"> État</th>
            <th class="action"> Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($sessionsActives as $session): ?>
            <?php //todo >>> $canSessionAfficher = $this->isAllowed($session, FormationinstancePrivileges::FORMATIONINSTANCE_AFFICHER); ?>
            <?php $canSessionAfficher = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_AFFICHER)); ?>
            <tr>
                <td>
                    <?php echo $session->getFormation()->getLibelle(); ?>
                </td>
                <td>
                    <?php echo $session->getPeriode(); ?>
                </td>
                <td>
                    <?php echo $this->etatinstance($session->getEtatActif(), ['display-categorie' => false]); ?>
                </td>
                <td class="action">
                    <?php if ($canSessionAfficher) : ?>
                        <?php /** @see \Formation\Controller\SessionController::afficherAction() */ ?>
                        <a href="<?php echo $this->url('formation/session/afficher', ['session' => $session->getId()], [], true); ?>">
                            <span class="icon icon-voir"></span>
                            Accéder
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<h2> Sessions de formation inactive </h2>

<?php if (empty($sessionsInactives)) : ?>
    <em> Aucune session de formations</em>
<?php else : ?>
    <table class="table table-condensed" id="actives">
        <thead>
        <tr>
            <th class="libelle"> Libellé</th>
            <th class="periode"> Période</th>
            <th class="etat"> État</th>
            <th class="action"> Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($sessionsInactives as $session): ?>
            <?php //todo >>> $canSessionAfficher = $this->isAllowed($session, FormationinstancePrivileges::FORMATIONINSTANCE_AFFICHER); ?>
            <?php $canSessionAfficher = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_AFFICHER)); ?>
            <tr>
                <td>
                    <?php echo $session->getFormation()->getLibelle(); ?>
                </td>
                <td>
                    <?php echo $session->getPeriode(); ?>
                </td>
                <td>
                    <?php echo $this->etatinstance($session->getEtatActif(), ['display-categorie' => false]); ?>
                </td>
                <td class="action">
                    <?php if ($canSessionAfficher) : ?>
                        <?php /** @see \Formation\Controller\SessionController::afficherAction() */ ?>
                        <a href="<?php echo $this->url('formation/session/afficher', ['session' => $session->getId()], [], true); ?>">
                            <span class="icon icon-voir"></span>
                            Accéder
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<style>
    th.libelle {
        width: 50%;
    }

    th.periode {
        /*width:50%;*/
    }

    th.etat {
        width: 10rem;
    }
</style>