<?php

/**
 * @var Form $form
 */

use Laminas\Form\Form;

?>

<?php //echo $this->form($form); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formControlGroup($form->get('formateur-type')); ?>

<div id="Organisme">
    <?php echo $this->formControlGroup($form->get('organisme')); ?>
</div>
<div id="Formateur">
    <?php echo $this->formControlGroup($form->get('nom')); ?>
    <?php echo $this->formControlGroup($form->get('prenom')); ?>
    <?php echo $this->formControlGroup($form->get('attachement')); ?>
</div>
<?php echo $this->formControlGroup($form->get('email')); ?>
<?php echo $this->formControlGroup($form->get('telephone')); ?>
<?php echo $this->formControlGroup($form->get('creer')); ?>
<?php echo $this->form()->closeTag(); ?>

<script>
    function checkType() {
        let vtype = $('select#formateur-type option:selected').val();
        if (vtype === 'Formateur') {
            $('div#Formateur').show();
            $('div#Organisme').hide();
        }
        if (vtype === 'Organisme') {
            $('div#Formateur').hide();
            $('div#Organisme').show();
        }
    }

    checkType();
    $('select#formateur-type').change(
        function() {
            checkType();
        }
    );

</script>

