<?php

use FicheMetier\Entity\Db\FicheMetier;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @see \Application\Controller\FicheMetierController::ajouterActiviteExistanteAction()
 * @see \Application\Controller\SpecificiteController::ajouterActiviteAction()
 * @var string $url
 *
 */

?>

<form method="post" action="<?php echo $url; ?>">
    <label for="activite"> Mission additionnelle : </label>
    <?php
    /** @see  \Application\Controller\ActiviteController::rechercherActiviteAction() */
    $structureF = new SearchAndSelect('activite');
    $structureF
        ->setAutocompleteSource($this->url('mission-principale/rechercher'))
        ->setSelectionRequired()
        ->setAttributes([
            'id' => 'activite',
            'placeholder' => "Sélectionner une mission additionnelle",
        ]);
    ?>
    <?php echo $this->formControlGroup($structureF); ?>
    <input type="submit" value="Ajouter l'activité" class="btn btn-primary action">
</form>

<div id="description">

</div>

<script>
   $(function() {
       $("input[type=text]").change(function (e) {
           let activite_id = $("input#activite").val();

           let url = "../../mission-principale/afficher/" + activite_id;
           $.ajax({
               type: "POST",
               url: url,
               beforeSend:
                   function () {
                       document.getElementById('description').innerHTML = "Récupération de l'activité ...";
                   },
               success:
                   function (retour) {
                       document.getElementById('description').innerHTML = retour;
                   }
           });
       });
   });
</script>
