<?php

/**
 * @see \Application\Controller\SpecificiteController::gererActiviteAction()
 * @var MissionAdditionnelle $missionAdditionnelle
 * @var MissionActivite[] $descriptions
 */

use FicheMetier\Entity\Db\MissionActivite;
use FichePoste\Entity\Db\MissionAdditionnelle;

usort($descriptions, function (MissionActivite $a, MissionActivite $b) { return $a->getOrdre()>$b->getOrdre();});

$retrait = explode(";",$missionAdditionnelle->getRetraits());
$retraits = [];
foreach ($retrait as $item) $retraits[(int) $item] = true;
?>

<form
    method="post"
    action="<?php echo $this->url("specificite/gerer-activite", ["specificite-activite" => $missionAdditionnelle->getId()], [], true); ?>"
>
    <?php foreach ($descriptions as $description) : ?>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="<?php echo $description->getId(); ?>" name="<?php echo $description->getId(); ?>"
               <?php if (!isset($retraits[$description->getId()])) echo " checked "; ?>
        />
        <label class="form-check-label" for="<?php echo $description->getId(); ?>"><?php echo $description->getLibelle(); ?></label>
    </div>
    <?php endforeach; ?>
    <input type="submit" class="btn btn-primary" value="Enregistrer">
</form>
