<?php

use Application\Controller\ElementController;
use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FicheMetierPrivileges;
use Element\Entity\Db\ApplicationElement;
use Element\Entity\Db\Interfaces\HasApplicationCollectionInterface;
use Element\Provider\Privilege\ApplicationPrivileges;
use FicheMetier\Entity\Db\FicheMetier;
use FichePoste\Provider\Privilege\FichePostePrivileges;

/**
 * @see ApplicationsViewHelper
 * @var ApplicationElement[] $applications
 * @var HasApplicationCollectionInterface $object
 * @var string $mode
 */

$debug = false;

$tableId = $options['table-id'] ?? 'applications_table';

$canAfficherApplication = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_AFFICHER));

$scope = null;
if ($object instanceof FicheMetier) $scope = FicheMetier::class;
if ($object instanceof FichePoste) $scope = FichePoste::class;


$canModifierApplicationElement = false;
$canSupprimerApplicationElement = false;
$canSetClefApplicationElement = false;
$canSetNiveauApplicationElement = false;
if ($mode === 'modification' and $scope !== null) {
    switch ($scope) {
        case FicheMetier::class :
            $canModifierApplicationElement = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));
            $canSupprimerApplicationElement = $canModifierApplicationElement;
            $canSetClefApplicationElement = $canModifierApplicationElement;
            $canSetNiveauApplicationElement = $canModifierApplicationElement;
            break;
        case FichePoste::class :
            $canModifierApplicationElement = $this->isAllowed($object, FichePostePrivileges::FICHEPOSTE_MODIFIER_POSTE);
            $canSupprimerApplicationElement = $canModifierApplicationElement;
            $canSetClefApplicationElement = $canModifierApplicationElement;
            $canSetNiveauApplicationElement = $canModifierApplicationElement;
            break;
    }
}

?>

<?php if ($debug) : ?>
    <dl>
        <dt>Mode</dt>
        <dd><?php echo $mode; ?></dd>
    </dl>
<?php endif; ?>


<?php if ($scope === null and $mode = 'modification') : ?>
    <div class="alert alert-warning">
        <span class="icon icon-warning"></span>
        La portée du tableau d'application n'a pas pu être déterminé : blocage des options de modification des
        applications.
    </div>
<?php endif; ?>

<table class="table table-condensed datatable" id="<?php echo $tableId; ?>">
    <thead>
    <tr>
        <th class="col-md-3"> Application</th>
        <th class="col-md-3"> Thème</th>
        <th class="col-md-2" data-type="num"> Niveau de maîtrise</th>
        <th class="col-md-2"> Clé</th>
        <th class="action col-md-2"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($applications as $applicationArray) : ?>
        <?php
        //todo examiner l'utilité d'envoyé les élements sous la forme d'un tableau [entite, raison, conserve]
        $applicationElement = $applicationArray['entite'];
        $application = $applicationElement->getApplication();
        ?>
        <?php $niveau = $applicationElement->getNiveauMaitrise(); ?>
        <tr>
            <td data-column-id="Application"> <?php echo $application->getLibelle(); ?> </td>
            <td data-column-id="Thème"> <?php echo($application->getTheme() ? $application->getTheme()->getLibelle() : "<em>Aucun thème</em>"); ?> </td>
            <td data-column-id="Niveau de maîtrise"
                data-order="<?php echo $niveau ? $niveau->getNiveau() : PHP_INT_MAX; ?>"> <?php echo($niveau ? $niveau->getLibelle() : "<em>Non renseigné</em>"); ?>
                <?php if ($canSetNiveauApplicationElement) : ?>
                    <br>
                    <span class="action">
                    <?php /** @see ElementController::changerNiveauAction() */ ?>
                        <a href="<?php echo $this->url("element_/changer-niveau", ['type' => ElementController::TYPE_APPLICATION, 'id' => $applicationElement->getId(), 'clef' => 'masquer'], [], true); ?>"
                            class="action primary ajax-modal" data-event="refresh-applications">
                        <span class="icon icon-editer"></span>
                        Modifier niveau
                    </a>
                    </span>
                <?php endif; ?>
            </td>
            <td data-column-id="Clef">
                <?php if ($applicationElement->isClef()) : ?>
                    <span class="icon icon-clef" data-bs-toggle="tooltip" data-bs-html="true"></span>
                    Application clé
                <?php endif; ?>
                <?php if ($canSetClefApplicationElement) : ?>
                    <br>
                    <span class="action">
                    <span
                       class="action primary toggleClef" id="<?php echo $applicationElement->getId() ?>">
                        <?php if ($applicationElement->isClef()) : ?>
                            <span class="icon icon-toggle-on"></span>
                        <?php else : ?>
                            <span class="icon icon-toggle-off"></span>
                        <?php endif; ?>
                        Modifier clé
                    </span>
                <?php endif; ?>
            </td>
            <td class="action" data-column-id="Action">
                <?php if ($canAfficherApplication) : ?>
                    <?php /** @see \Element\Controller\ApplicationController::afficherAction(); */ ?>
                    <a href="<?php echo $this->url('element/application/afficher', ['application' => $application->getId()], [], true); ?>"
                       class="action secondary ajax-modal">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canSupprimerApplicationElement) : ?>
                    <br>
                    <?php /** @see ElementController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('element_/supprimer', ['type' => ElementController::TYPE_APPLICATION, 'id' => $applicationElement->getId()], [], true); ?>"
                       class="action danger">
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $('table#<?php echo $tableId; ?>').DataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [4], orderable: false}
            ]
        });

        $("table#<?php echo $tableId; ?> span.toggleClef").click(function () {
            $("#neue_applications div.card-body").addClass('refreshing');
            let id = $(this).attr('id');
            <?php /** @see ElementController::toggleClefAction() */ ?>
            let url = "<?php echo $this->url("element_/toggle-clef", ['type' => ElementController::TYPE_APPLICATION]); ?>" + "/" + id;
            console.log("toggleing clef")
            $.ajax({
                type: "POST",
                url: url,
                success:
                    function () {
                        refreshApplications()
                    }
            });
        });
    });
</script>