<?php

use Application\Controller\ElementController;
use Application\Entity\Db\Agent;
use FicheMetier\Entity\Db\FicheMetier;
use Application\Provider\Privilege\AgentPrivileges;
use Application\Provider\Privilege\FicheMetierPrivileges;
use Element\Entity\Db\Application;
use Element\Entity\Db\ApplicationElement;
use Element\Entity\Db\Interfaces\HasCompetenceCollectionInterface;
use Element\View\Helper\CompetenceBlocViewHelper;
use Formation\Entity\Db\Formation;
use Formation\Provider\Privilege\FormationPrivileges;

/**
 * @see \Application\View\Helper\ApplicationBlocViewHelper
 * @var array $applications
 * @var HasCompetenceCollectionInterface|null $objet
 * @var array $options
 *
 * la sutrcture de application est la suivante :
 *
 * $applications = [
 *      ID => [
 *          'entite' => Application,
 *          'display' => true|false,
 *          'raison' => [
 *                  [ 'source', SourceEntity ],
 *                  [ 'source', SourceEntity ],
 *                  ...
 *              ]
 *          ],
 *      ...
 *  ]
 */

//var_dump($options);
$canAcquisAfficher = false;
$canAcquisModifier = false;
if ($objet instanceof FicheMetier) {
    $canAcquisAfficher = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));
    $canAcquisModifier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));
} else {
    if ($objet instanceof Formation) {
        $canAcquisAfficher = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AFFICHER));
        $canAcquisModifier = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_MODIFIER));
    } else {
        $canAcquisAfficher = $this->isAllowed($objet, AgentPrivileges::AGENT_ACQUIS_AFFICHER);
        $canAcquisModifier = $this->isAllowed($objet, AgentPrivileges::AGENT_ACQUIS_MODIFIER);
    }
}

$canAfficher        = (CompetenceBlocViewHelper::isActionActivee($options, 'afficher')  AND $canAcquisAfficher);
$canAjouter         = (CompetenceBlocViewHelper::isActionActivee($options, 'ajouter')   AND $canAcquisModifier);
$canModifier        = (CompetenceBlocViewHelper::isActionActivee($options, 'modifier')  AND $canAcquisModifier);
$canSupprimer       = (CompetenceBlocViewHelper::isActionActivee($options, 'supprimer') AND $canAcquisModifier);
$canValider         = (CompetenceBlocViewHelper::isActionActivee($options, 'valider')   AND $canAcquisModifier);

$displayTitre       = CompetenceBlocViewHelper::isDisplayed($options,'titre');
$displayValidation  = CompetenceBlocViewHelper::isDisplayed($options,'validation');
$displayRaison      = CompetenceBlocViewHelper::isDisplayed($options,'raison');

//var_dump($displayTitre);
//var_dump($displayValidation);

$groupes = [];
$sansGroupe = "zzz";
foreach ($applications as $item) {
    /** @var Application $application */
    $entite = $item['entite'];
    $application = $entite;
    if ($entite instanceof ApplicationElement) $application = $entite->getApplication();
    if ($application) {
        $libelleGroupe = ($application->getGroupe()) ? $application->getGroupe()->getLibelle() : $sansGroupe;
        if ($item['conserve'] === true) $groupes[$libelleGroupe][] = $item;
    }
}

ksort($groupes);

?>

<?php if ($displayTitre) : ?>
    <div class="titre">
        <div class="row">
            <div class="col-md-8" style="border-bottom: 1px solid #31708f">
                <h3> <span class="icon application"></span> Applications</h3>
            </div>
            <div class="pull-right">
                <?php if ($canAjouter) : ?>
                    <br/>
                    <?php if ($objet instanceof Agent) : ?>
                        <a
                            <?php /** @see \Element\Controller\ElementController::ajouterApplicationElementAction() */?>
                            <?php //todo ... Agent::class => get_class($objet) ... ?>
                                href="<?php echo $this->url('element_/ajouter-application-element', ['type' => Agent::class, 'id' => $objet->getId(), 'clef' => ($objet instanceof FicheMetier)?'afficher':'masquer'], [], true); ?>"
                                class="ajax-modal btn btn-primary action"
                                data-event="modification"
                        >
                            <span class="icon icon-ajouter" title="Ajouter une application"></span>
                            Ajouter une application
                        </a>
                    <?php endif; ?>
                    <?php if ($objet instanceof Formation) : ?>
                        <a
                            <?php /** @see \Formation\Controller\FormationController::ajouterApplicationElementAction() */?>
                            <?php //todo ... Agent::class => get_class($objet) ... ?>
                                href="<?php echo $this->url('formation/ajouter-application-element', ['type' => Formation::class, 'id' => $objet->getId(), 'clef' => ($objet instanceof FicheMetier)?'afficher':'masquer'], [], true); ?>"
                                class="ajax-modal btn btn-primary action"
                                data-event="modification"
                        >
                            <span class="icon icon-ajouter" title="Ajouter une application"></span>
                            Ajouter une application
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        <br/>
    </div>
<?php endif; ?>

<div class="listing">
    <table>
        <?php foreach ($groupes as $libelle => $groupe) : ?>
        <?php if ($groupe !== null AND !empty($groupe)) : ?>
        <tr>
            <th colspan="5">
                <?php echo $libelle; ?>
            </th>
        </tr>
        <?php usort($groupe, function ($a, $b) { return $a['entite']->getLibelle() > $b['entite']->getLibelle(); }); ?>
        <?php foreach ($groupe as $element) : ?>
            <?php
            $entite = $element['entite'];
            $application = $entite;
            $isClef = false;
            if ($application instanceof ApplicationElement) {
                $isClef = $application->isClef();
                $application = $entite->getApplication();
            }
            ?>
            <tr>
                <td >
                    <?php echo $application->getLibelle(); ?>
                    <?php if ($displayRaison) : ?>
                        <?php echo $this->raisons($element['raison']); ?>
                    <?php endif; ?>
                </td>
                <td class="niveau">
                    <?php if ($entite instanceof ApplicationElement) : ?>
                        <?php echo ($entite->getNiveauMaitrise())?$entite->getNiveauMaitrise()->getLibelle():"Non précisé"; ?>
                    <?php endif; ?>
                </td>
                <td class="clef">
                    <?php if ($isClef) : ?>
                        <span class="icon icon-star"></span>
                    <?php endif; ?>
                </td>
                <?php if ($displayValidation) : ?>
                    <td class="validation">
                        <span class="todo">Restaurer avec UnicaenValidation </span>
<!--                        --><?php //if ($entite instanceof ApplicationElement) : ?>
<!--                            --><?php //echo $this->validationBadge($entite->getValidation(),$options); ?>
<!--                        --><?php //endif; ?>
                    </td>
                <?php endif; ?>
                <td class="action">
                    <?php if ($entite instanceof ApplicationElement) : ?>
<!--                        --><?php //if ($canAfficher) : ?>
<!--                            <a  --><?php ///** @see \Application\Controller\ElementController::afficherAction() */ ?>
<!--                                    href="--><?php //echo $this->url("element/afficher", ['type' => ElementController::TYPE_APPLICATION, 'id' => $entite->getId()], [], true); ?><!--"-->
<!--                                    class="ajax-modal" data-bs-toggle="tooltip" data-bs-html="true"-->
<!--                                    title="Afficher l'application <span class='highlight application'>--><?php //echo $application->getLibelle(); ?><!--</span>">-->
<!--                                <span class="icon icon-voir"></span></a>-->
<!--                        --><?php //endif; ?>
                        <?php if ($canModifier) : ?>
                            <a  <?php /** @see \Application\Controller\ElementController::changerNiveauAction() */ ?>
                                    href="<?php echo $this->url("element_/changer-niveau", ['type' => ElementController::TYPE_APPLICATION, 'id' => $entite->getId(), 'clef' => ($objet instanceof FicheMetier)?'afficher':'masquer'], [], true); ?>"
                                    class="ajax-modal" data-event="modification" data-bs-toggle="tooltip" data-bs-html="true"
                                    title="Modifier le niveau de l'application <span class='highlight application'><?php echo $application->getLibelle(); ?></span>">
                                <span class="icon icon-editer"></span></a>
                        <?php endif; ?>
                        <?php if ($canSupprimer) : ?>
                            <a
                                <?php /** @see \Application\Controller\ElementController::supprimerAction() */?>
                                    href="<?php echo $this->url('element_/supprimer', ['type' => ElementController::TYPE_APPLICATION, 'id' => $entite->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    data-event="modification"
                            >
                                <span class="text-danger">
                                    <span class="icon icon-unchecked" title="Supprimer définitivement une application liées à l'agent"></span>
                                </span></a>
                        <?php endif; ?>
                        <?php if ($canValider) : ?>
                            <span class="todo">Restaurer avec UnicaenValidation </span>
<!--                            --><?php //if ($entite->getValidation() === null) : ?>
<!--                                <a-->
<!--                                    --><?php ///** @see \Application\Controller\AgentController::validerElementAction() */ ?>
<!--                                        href="--><?php //echo $this->url('agent/valider-element', ['type' => "AGENT_APPLICATION", 'id' => $entite->getId()], [], true); ?><!--"-->
<!--                                        class="ajax-modal" data-event="modification"-->
<!--                                >-->
<!--                                    <span class="icon validation-do" title="Valider l'application"></span></a>-->
<!--                            --><?php //else: ?>
<!--                                <a-->
<!--                                    --><?php ///** @see \Application\Controller\AgentController::revoquerElementAction() */ ?>
<!--                                        href="--><?php //echo $this->url('agent/revoquer-element', ['validation' => $entite->getValidation()->getId()], ['query' => ['retour' => $options['retour']]], true); ?><!--"-->
<!--                                >-->
<!--                                    <span class="icon validation-undo" title="Dévalider l'application"></span></a>-->
<!--                            --><?php //endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <?php endif; ?>
        <?php endforeach; ?>
    </table>
</div>
