<?php

use Application\Controller\ElementController;
use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use Element\Entity\Db\ApplicationElement;
use Element\Entity\Db\Interfaces\HasCompetenceCollectionInterface;
use Element\View\Helper\CompetenceBlocViewHelper;
use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;

/**
 * @see \Application\View\Helper\ApplicationBlocViewHelper
 * @var array $applications
 * @var HasCompetenceCollectionInterface|null $objet
 * @var array $options
 *
 * La structure d'application est la suivante :
 *
 * $applications = [
 *      ID => [
 *          'entite' => Application,
 *          'display' => true|false,
 *          'raison' => [
 *                  [ 'source', SourceEntity ],
 *                  [ 'source', SourceEntity ],
 *                  ...
 *              ]
 *          ],
 *      ...
 *  ]
 */

$isAcquis = (isset($options['acquis']) && $options['acquis'] === true);

//var_dump($options);
$canAcquisAfficher = false;
$canAcquisModifier = false;
if ($objet instanceof FicheMetier) {
    $canAcquisAfficher = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));
    $canAcquisModifier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));
} else {
    $canAcquisAfficher = $this->isAllowed($objet, AgentPrivileges::AGENT_ACQUIS_AFFICHER);
    $canAcquisModifier = $this->isAllowed($objet, AgentPrivileges::AGENT_ACQUIS_MODIFIER);
}

$canAfficher = (CompetenceBlocViewHelper::isActionActivee($options, 'afficher') and $canAcquisAfficher);
$canAjouter = (CompetenceBlocViewHelper::isActionActivee($options, 'ajouter') and $canAcquisModifier);
$canModifier = (CompetenceBlocViewHelper::isActionActivee($options, 'modifier') and $canAcquisModifier);
$canSupprimer = $canModifier;
$canValider = (CompetenceBlocViewHelper::isActionActivee($options, 'valider') and $canAcquisModifier);

$displayTitre = CompetenceBlocViewHelper::isDisplayed($options, 'titre');
$displayValidation = CompetenceBlocViewHelper::isDisplayed($options, 'validation');
$displayRaison = CompetenceBlocViewHelper::isDisplayed($options, 'raison');

$elements = [];
foreach ($applications as $application) {
    $elements[] = $application['entite'];
}

?>

<?php if ($displayTitre) : ?>
    <div class="titre">
        <div class="row">
            <div class="col-md-8" style="border-bottom: 1px solid #31708f">
                <h3><span class="icon application"></span> Applications</h3>
            </div>
            <div class="pull-right">
                <?php if ($canAjouter) : ?>
                    <br/>
                    <?php if ($objet instanceof Agent) : ?>
                        <a
                            <?php /** @see \Element\Controller\ElementController::ajouterApplicationElementAction() */ ?>
                            <?php //todo ... Agent::class => get_class($objet) ... ?>
                                href="<?php echo $this->url('element_/ajouter-application-element', ['type' => Agent::class, 'id' => $objet->getId(), 'clef' => ($objet instanceof FicheMetier) ? 'afficher' : 'masquer'], [], true); ?>"
                                class="ajax-modal btn btn-primary"
                                data-event="modification"
                        >
                            <span class="icon icon-ajouter" title="Ajouter une application"></span>
                            Ajouter une application
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        <br/>
    </div>
<?php endif; ?>

<div class="listing">

    <table id="<?php echo $options['id'] ?? 'applications'; ?>" class="table table-condensed datatable">
        <thead>
        <tr>
            <th class="col-md-<?php echo (!isset($options['mode']) or $options['mode'] !== 'affichage')?"4":"5"; ?>"> Libellé</th>
            <th class="col-md-4" style="width:30%;"> Thème</th>
            <th class="col-md-2" data-type="num"> Niveau </th>
            <th class="col-md-2" data-type="num"> Clef </th>
            <?php if (!isset($options['mode']) or $options['mode'] !== 'affichage'): ?>
                <th class="col-md-2"> Action</th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php /** @var ApplicationElement $element */ ?>
        <?php foreach ($elements as $element) : ?>
            <tr>
                <td> <?php echo $element->getApplication()->getLibelle(); ?> </td>
                <td> <?php echo ($element->getApplication()->getTheme())?->getLibelle(); ?> </td>
                <td data-order="<?php echo ($element->getNiveauMaitrise())?->getNiveau(); ?>">
                    <?php echo ($element->getNiveauMaitrise())?->getLibelle(); ?>
                </td>
                <td>
                    <?php if ($element->isClef()) : ?>
                        <span class="icon icon-clef" title="Est une application clef"></span>
                    <?php endif; ?>
                </td>
                <?php if (!isset($options['mode']) or $options['mode'] !== 'affichage'): ?>
                    <td class="action">
                        <?php if ($canModifier) : ?>
                            <?php if (!$isAcquis) : ?>
                                <a <?php /** @see ElementController::changerNiveauAction */ ?>
                                        href="<?php echo $this->url("element_/changer-niveau", ['type' => ElementController::TYPE_APPLICATION, 'id' => $element->getId(), 'clef' => ($objet instanceof FicheMetier) ? 'afficher' : 'masquer'], [], true); ?>"
                                        class="ajax-modal action primary" data-event="modification"
                                >
                                    <span class="icon icon-editer"></span>
                                    Modifier </a>
                            <?php else : ?>
                                <a <?php /** @see ElementController::modifierApplicationElementAction */ ?>
                                        href="<?php echo $this->url("element_/modifier-application-element", ['application-element' => $element->getId()], [], true); ?>"
                                        class="ajax-modal action primary" data-event="modification"
                                >
                                    <span class="icon icon-editer"></span>
                                    Modifier </a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canSupprimer) : ?>
                            <br>
                            <a
                                <?php /** @see ElementController::supprimerAction */ ?>
                                    href="<?php echo $this->url('element_/supprimer', ['type' => ElementController::TYPE_APPLICATION, 'id' => $element->getId()], [], true); ?>"
                                    class="ajax-modal action danger" data-event="modification"
                            >
                                <span class="icon icon-unchecked"></span>
                                Supprimer
                            </a>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(function () {
        $('#<?php echo $options['id'] ?? 'applications'; ?>').DataTable({
            autoWidth: false,
            paging: false,
            info: false,
            order: [[1, 'asc'], [0, 'asc']],
            <?php if (!isset($options['mode']) or $options['mode'] !== 'affichage'): ?>
                columnDefs: [{
                    "targets": 4,
                    "orderable": false
                }],
            <?php endif; ?>
            language: {
                url: '/js/datatables_fr.json'
            }
        });
    });
</script>

