<?php

use Element\Entity\Db\Competence;

/**
 * @see \Element\View\Helper\CompetenceReferenceViewHelper
 * @var Competence $competence
 * @var array $options
 */

?>

<span class="badge" style="background:<?php echo $competence->getReferentiel()?$competence->getReferentiel()->getCouleur():"lightgray"; ?>;">
    <?php echo $competence->getReferentiel()->getLibelleCourt(); ?>
    <?php if ($competence->getIdSource()) echo " - ".$competence->getIdSource(); ?>
</span>
