<?php

use Application\Controller\ElementController;
use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use Application\Provider\Privilege\FicheMetierPrivileges;
use Element\Entity\Db\CompetenceElement;
use Element\Entity\Db\CompetenceType;
use Element\Entity\Db\Interfaces\HasCompetenceCollectionInterface;
use Element\View\Helper\CompetenceBlocViewHelper;
use FicheMetier\Entity\Db\FicheMetier;

/**
 * @see \Application\View\Helper\CompetenceBlocViewHelper
 * @var array $competences
 * @var CompetenceType[] $types (n.b. deja ordonnée)
 * @var HasCompetenceCollectionInterface $objet
 * @var array $options
 *
 * la sutrcture de application est la suivante :
 *
 * $applications = [
 *      ID => [
 *          'entite' => Application,
 *          'display' => true|false,
 *          'raison' => [
 *                  [ 'source', SourceEntity ],
 *                  [ 'source', SourceEntity ],
 *                  ...
 *              ]
 *          ],
 *      ...
 *  ]
 */

$isAcquis = (isset($options['acquis']) && $options['acquis'] === true);


$canAcquisAfficher = false;
$canAcquisModifier = false;
if ($objet instanceof FicheMetier) {
    $canAcquisAfficher = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));
    $canAcquisModifier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));
} else {
    $canAcquisAfficher = $this->isAllowed($objet, AgentPrivileges::AGENT_ACQUIS_AFFICHER);
    $canAcquisModifier = $this->isAllowed($objet, AgentPrivileges::AGENT_ACQUIS_MODIFIER);
}

$canAfficher = (CompetenceBlocViewHelper::isActionActivee($options, 'afficher') and $canAcquisAfficher);
$canAjouter = (CompetenceBlocViewHelper::isActionActivee($options, 'ajouter') and $canAcquisModifier);
$canModifier = (CompetenceBlocViewHelper::isActionActivee($options, 'modifier') and $canAcquisModifier);
$canSupprimer = $canModifier;

$displayTitre = CompetenceBlocViewHelper::isDisplayed($options, 'titre');
$displayValidation = CompetenceBlocViewHelper::isDisplayed($options, 'validation');
$displayRaison = CompetenceBlocViewHelper::isDisplayed($options, 'raison');
$displayTheme = CompetenceBlocViewHelper::isDisplayed($options, 'theme');


$elements = [];
foreach ($competences as $competence) {
    $elements[] = $competence['entite'];
}

?>

<!-- TITRE DU BLOC ---------------------------------------------------------------------------------------------------->

<?php if ($displayTitre) : ?>
    <div class="titre">
        <div class="row">
            <div class="col-md-8" style="border-bottom: 1px solid #31708f">
                <h3><span class="icon competence"></span> Compétences</h3>
            </div>
            <div class="pull-right">
                <?php if ($canAjouter) : ?>
                    <br/>
                    <?php if ($objet instanceof Agent) : ?>
                        <a
                            <?php /** @see \Element\Controller\ElementController::ajouterCompetenceElementAction() */ ?>
                            <?php //todo ... Agent::class => get_class($objet) ... ?>
                                href="<?php echo $this->url('element_/ajouter-competence-element', ['type' => Agent::class, 'id' => $objet->getId(), 'clef' => ($objet instanceof FicheMetier) ? 'afficher' : 'masquer'], [], true); ?>"
                                class="ajax-modal btn btn-primary"
                                data-event="modification"
                        >
                            <span class="icon icon-ajouter" title="Ajouter une compétence"></span>
                            Ajouter une compétence
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        <br/>
    </div>
<?php endif; ?>

<?php
$nbAction = 0;
if ($canModifier) $nbAction++;
if ($canSupprimer) $nbAction++;
?>

<table class="table table-condensed datatable" id="<?php echo $options['id'] ?? 'competences'; ?>">
    <thead>
    <tr>
        <th class="col-md-5"> Compétences</th>
        <th class="col-md-2"> Thèmes</th>
        <th class="col-md-2"> Type</th>
        <th class="col-md-2" data-type="num"> Niveau</th>
        <?php if (!isset($options['mode']) or $options['mode'] !== 'affichage'): ?>
            <th class="col-md-1"> Action</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php /** @var CompetenceElement $element */ ?>
    <?php foreach ($elements as $element) : ?>
        <tr>
            <td>
                <?php echo $element->getCompetence()->getLibelle(); ?>
                <?php if ($element->getCompetence()->getReferentiel()) : ?>
                    <?php echo $this->competenceReference($element->getCompetence()); ?>
                <?php endif; ?>
            </td>
            <td> <?php echo ($element->getCompetence()->getTheme())?->getLibelle(); ?> </td>
            <td> <?php echo ($element->getCompetence()->getType())?->getLibelle(); ?> </td>
            <td class="<?php echo ($element->getNiveauMaitrise())?->getNiveau(); ?>">
                <?php echo ($element->getNiveauMaitrise())?->getLibelle(); ?>
                <?php if ($element->isClef()): ?>
                    <span class="icon icon-star" title="Est une competence clef"></span>
                <?php endif; ?>
            </td>
            <?php if (!isset($options['mode']) or $options['mode'] !== 'affichage'): ?>
                <td class="action">
                    <?php if ($canModifier) : ?>
                        <?php if (!$isAcquis) : ?>
                            <a <?php /** @see \Element\Controller\ElementController::changerNiveauAction() */ ?>
                                    href="<?php echo $this->url("element_/changer-niveau", ['type' => ElementController::TYPE_COMPETENCE, 'id' => $element->getId(), 'clef' => ($objet instanceof FicheMetier) ? 'afficher' : 'masquer'], [], true); ?>"
                                    class="ajax-modal action primary" data-event="modification" data-bs-toggle="tooltip"
                                    data-bs-html="true"
                            >
                                <span class="icon icon-editer"></span> Modifier</a>
                        <?php else : ?>
                            <a <?php /** @see \Element\Controller\ElementController::modifierCompetenceElementAction() */ ?>
                                    href="<?php echo $this->url("element_/modifier-competence-element", ['competence-element' => $element->getId()], [], true); ?>"
                                    class="ajax-modal  action primary" data-event="modification"
                                    data-bs-toggle="tooltip"
                                    data-bs-html="true"
                            >
                                <span class="icon icon-editer"></span> Modifier</a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canSupprimer) : ?>
                        <br>
                        <a
                            <?php /** @see \Element\Controller\ElementController::supprimerAction() */ ?>
                                href="<?php echo $this->url('element_/supprimer', ['type' => ElementController::TYPE_COMPETENCE, 'id' => $element->getId()], [], true); ?>"
                                class="ajax-modal  action danger"
                                data-event="modification"
                        >
                        <span class="icon icon-unchecked"
                              title="Supprimer définitivement une compétence liées à l'agent"></span>
                            Supprimer
                        </a>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $('#<?php echo $options['id'] ?? 'competences'; ?>').DataTable({
            autoWidth: false,
            paging: false,
            info: false,
            order: [[2, 'asc'], [1, 'asc'], [0, 'asc']],
            <?php if (!isset($options['mode']) or $options['mode'] !== 'affichage'): ?>
            columnDefs: [{
                "targets": 4,
                "orderable": false
            }],
            <?php endif; ?>
            language: {
                url: '/js/datatables_fr.json'
            }
        });
    });
</script>
