<?php

use Application\Controller\ElementController;
use Application\Entity\Db\FichePoste;
use Element\Entity\Db\Competence;
use Element\Entity\Db\CompetenceDiscipline;
use Element\Entity\Db\CompetenceElement;
use Element\Entity\Db\CompetenceType;
use Element\Entity\Db\Interfaces\HasCompetenceCollectionInterface;
use Element\Provider\Privilege\CompetencePrivileges;
use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;
use FichePoste\Provider\Privilege\FichePostePrivileges;

/**
 * @see CompetencesViewHelper
 * @var CompetenceElement[] $competences
 * @var CompetenceType[] $type
 * @var HasCompetenceCollectionInterface $object
 * @var string $mode
 */

$debug = false;

$canAfficherCompetence = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_AFFICHER));

$scope = null;
if ($object instanceof FicheMetier) $scope = FicheMetier::class;
if ($object instanceof FichePoste) $scope = FichePoste::class;


$canModifierCompetenceElement = false;
$canSupprimerCompetenceElement = false;
$canSetClefCompetenceElement = false;
$canSetNiveauCompetenceElement = false;
if ($mode === 'modification' and $scope !== null) {
    switch ($scope) {
        case FicheMetier::class :
            $canModifierCompetenceElement = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));
            $canSupprimerCompetenceElement = $canModifierCompetenceElement;
            $canSetClefCompetenceElement = $canModifierCompetenceElement;
            $canSetNiveauCompetenceElement = $canModifierCompetenceElement;
            break;
        case FichePoste::class :
            $canModifierCompetenceElement = $this->isAllowed($object, FichePostePrivileges::FICHEPOSTE_MODIFIER_POSTE);
            $canSupprimerCompetenceElement = $canModifierCompetenceElement;
            $canSetClefCompetenceElement = $canModifierCompetenceElement;
            $canSetNiveauCompetenceElement = $canModifierCompetenceElement;
            break;
    }
}


$empty=new CompetenceDiscipline(); $empty->setLibelle("Sans discipline"); $empty->setId(PHP_INT_MAX);
$discipline = [];
$dictionnaire = [];
foreach ($competences as $competence) {
    $c = $competence['entite']->getCompetence();
    $d = $c->getDiscipline()??$empty;
    $key = ($d === null)?-1:$d->getId();
    $discipline[$key] = $d;
    $dictionnaire[$key][] = $competence;
}

usort($discipline, function (CompetenceDiscipline $a, CompetenceDiscipline $b) { return $a->getLibelle() <=> $b->getLibelle(); });

?>

<?php if (!empty($discipline)) : ?>
    <?php if ($scope === null and $mode = 'modification') : ?>
        <div class="alert alert-warning">
            <span class="icon icon-warning"></span>
            La portée du tableau des compétences n'a pas pu être déterminé : blocage des options de modification des
            compétences.
        </div>
    <?php endif; ?>

    <div id="specifique">
    <?php foreach ($discipline as $d) : ?>
        <?php $key = $d->getId(); ?>

        <h3> <strong>Discipline : <?php echo $d->getLibelle(); ?></strong> </h3>

        <table class="table table-condensed datatable" id="<?php echo "spec_discipline_".$d->getId(); ?>">
            <thead>
            <tr>
                <th class="col-md-4"> Libellé</th>
                <th class="col-md-3"> Thème</th>
                <th class="col-md-2" data-type="num"> Niveau de maîtrise</th>
                <th class="col-md-1"> Clé</th>
                <th class="action col-md-2"> Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($dictionnaire[$key] as $competenceArray) : ?>
                <?php
                //todo examiner l'utilité d'envoyé les élements sous la forme d'un tableau [entite, raison, conserve]
                $competenceElement = $competenceArray['entite'];
                /** @var Competence $competence */
                $competence = $competenceElement->getCompetence();
                ?>
                <?php $niveau = $competenceElement->getNiveauMaitrise(); ?>
                <tr>
                    <td data-column-id="Libellé">
                        <?php echo $competence->getLibelle(); ?>
                        <?php if ($competence->getDescription()) : ?>
                            <span class="icon icon-info"
                                  title="<?php echo strip_tags($competence->getDescription()); ?>"
                                  data-bs-toggle="tooltip" data-bs-html="true"></span>
                        <?php endif; ?>
                        <br>
                        <?php echo ($competence->getReferentiel()) ? $competence->printReference() : "Aucun"; ?>
                    </td>
                    <td data-column-id="Thème"> <?php echo($competence->getTheme() ? $competence->getTheme()->getLibelle() : "<em>Aucun thème</em>"); ?> </td>
                    <td data-column-id="Niveau de maîtrise"
                        data-order="<?php echo $niveau ? $niveau->getNiveau() : PHP_INT_MAX; ?>"> <?php echo($niveau ? $niveau->getLibelle() : "<em>Non renseigné</em>"); ?>
                        <?php if ($canSetNiveauCompetenceElement) : ?>
                            <br>
                            <span class="action">
                            <?php /** @see ElementController::changerNiveauAction() */ ?>
                                <a href="<?php echo $this->url("element_/changer-niveau", ['type' => ElementController::TYPE_COMPETENCE, 'id' => $competenceElement->getId(), 'clef' => 'masquer'], [], true); ?>"
                                   class="action primary ajax-modal" data-event="refresh-competences-specifiques"
                                   data-competence-type="<?php echo $competence->getType()->getCode(); ?>">
                                    <span class="icon icon-editer"></span>
                                    Modifier niveau
                                </a>
                            </span>
                        <?php endif; ?>
                    </td>
                    <td data-column-id="Clé">
                        <?php if ($competenceElement->isClef()) : ?>
                            <div style="width:2rem; display: inline-block;">
                                <span class="icon icon-clef" title="Cette compétence est clé"></span>
                            </div>
                        <?php else: ?>
                            <div style="width:2rem; display: inline-block;"></div>
                        <?php endif; ?>
                        <?php if ($mode === "modification") : ?>
                            <span class="<?php if ($canSetClefCompetenceElement) echo " toggleClef "; ?>"
                                  data-competence-type="<?php echo $competence->getType()->getCode(); ?>"
                                  id="<?php echo $competenceElement->getId() ?>">
                                <?php if ($competenceElement->isClef()) : ?>
                                    <span class="text-success icon icon-toggle-on"></span>
                                <?php else : ?>
                                    <span class="text-danger icon icon-toggle-off"></span>
                                <?php endif; ?>
                        </span>
                        <?php endif; ?>
                    </td>
                    <td class="action" data-column-id="Action">
                        <?php if ($canAfficherCompetence) : ?>
                            <?php /** @see \Element\Controller\CompetenceController::afficherAction(); */ ?>
                            <a href="<?php echo $this->url('element/competence/afficher', ['competence' => $competence->getId()], [], true); ?>"
                               class="action secondary ajax-modal">
                                <span class="icon icon-voir"></span>
                                Afficher
                            </a>
                        <?php endif; ?>
                        <?php if ($canSupprimerCompetenceElement) : ?>
                            <br>
                            <?php /** @see ElementController::supprimerAction() */ ?>
                            <a href="<?php echo $this->url('element_/supprimer', ['type' => ElementController::TYPE_COMPETENCE, 'id' => $competenceElement->getId()], [], true); ?>"
                               class="action danger ajax-modal" data-event="refresh-competences-specifiques"
                               data-competence-type="<?php echo $competence->getType()->getCode(); ?>">
                                <span class="icon icon-unchecked"></span>
                                Supprimer
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <br>
    <?php endforeach; ?>
    </div>
<?php endif; ?>

<script>
    $(function () {
        <?php foreach ($discipline as $d): ?>
            $('table#<?php echo "spec_discipline_".$d->getId(); ?>').DataTable({
                paging: false,
                info: false,
                autoWidth: false,
                language: {
                    "url": "/js/datatables_fr.json",
                },
                columnDefs: [
                    {targets: [4], orderable: false}
                ]
            });
        <?php endforeach; ?>

        $("div#specifique table span.toggleClef").click(function () {

            let id = $(this).attr('id');
            let type = $(this).data('competence-type').replaceAll(' ', '_');
            $("div#competence_" + type).addClass('refreshing');
            <?php /** @see ElementController::toggleClefAction() */ ?>
            let url = "<?php echo $this->url("element_/toggle-clef", ['type' => ElementController::TYPE_COMPETENCE]); ?>" + "/" + id;
            console.log("toggleing clef (" + type + ")");
            $.ajax({
                type: "POST",
                url: url,
                success:
                    function () {
                        refreshCompetencesSpecifiques(type);
                    }
            });
        });
    });
</script>