<?php

namespace Formation\Provider\Template;

class MailTemplates {

    //déclaration des formations
    const FORMATION_INSCRIPTION_OUVERTE                 = "FORMATION_INSCRIPTION_OUVERTE";
    const FORMATION_NOUVELLES_FORMATIONS                = "FORMATION_NOTIFICATION_NOUVELLES_FORMATIONS";

    //circuit d'inscription
    const FORMATION_INSCRIPTION_DEMANDE_AGENT           = "FORMATION_INSCRIPTION_DEMANDE_AGENT";
    const FORMATION_INSCRIPTION_RESPONSABLE_VALIDATION  = "FORMATION_INSCRIPTION_RESPONSABLE_VALIDATION";
    const FORMATION_INSCRIPTION_RESPONSABLE_REFUS       = "FORMATION_INSCRIPTION_RESPONSABLE_REFUS";
    const FORMATION_INSCRIPTION_DRH_VALIDATION          = "FORMATION_INSCRIPTION_DRH_VALIDATION";
    const FORMATION_INSCRIPTION_DRH_REFUS               = "FORMATION_INSCRIPTION_DRH_REFUS";

    //rappel
    const FORMATION_RAPPEL_AVANT_FORMATION              = "FORMATION_INSCRIPTION_RAPPEL_AVANT_FORMATION";
    const FORMATION_INSCRIPTION_CLOTURE_AUTOMATIQUE     = "FORMATION_INSCRIPTION_CLOTURE_AUTOMATIQUE";

}