<?php

namespace Formation\Provider\Template;

class MailTemplates {

    //circuit d'inscription
    const FORMATION_INSCRIPTION_DEMANDE_AGENT           = "FORMATION_INSCRIPTION_1_AGENT";
    const FORMATION_INSCRIPTION_RESPONSABLE_VALIDATION  = "FORMATION_INSCRIPTION_2_RESPONSABLE_VALIDATION";
    const FORMATION_INSCRIPTION_RESPONSABLE_REFUS       = "FORMATION_INSCRIPTION_2_RESPONSABLE_REFUS";
    const FORMATION_INSCRIPTION_DRH_VALIDATION          = "FORMATION_INSCRIPTION_3_DRH_VALIDATION";
    const FORMATION_INSCRIPTION_DRH_REFUS               = "FORMATION_INSCRIPTION_3_DRH_REFUS";

    //session
    const SESSION_CONVOCATION                           = "FORMATION_SESSION_CONVOCATION";
    const SESSION_EMARGEMENT                            = "FORMATION_SESSION_EMARGEMENT";
    const SESSION_LISTE_PRINCIPALE                      = "FORMATION_SESSION_LISTE_PRINCIPALE";
    const SESSION_LISTE_COMPLEMENTAIRE                  = "FORMATION_SESSION_LISTE_COMPLEMENTAIRE";
    const SESSION_DEMANDE_RETOUR                        = "FORMATION_SESSION_DEMANDE_RETOUR";
    const SESSION_ANNULEE                               = "FORMATION_SESSION_ANNULEE";

    //rappel
    const FORMATION_RAPPEL_AVANT_FORMATION              = "FORMATION_NOTIFICATION_SESSION_IMMINENTE";
    const FORMATION_INSCRIPTION_OUVERTE                 = "FORMATION_NOTIFICATION_ABONNEMENT_FORMATION";
    const FORMATION_NOUVELLES_FORMATIONS                = "FORMATION_NOTIFICATION_NOUVELLES_SESSIONS";

    //RAPPORT
    const FORMATION_INSCRIPTION_CLOTURE_AUTOMATIQUE     = "FORMATION_RAPPORT_CLOTURE_AUTOMATIQUE";
    const FORMATION_CONVOCATION_AUTOMATIQUE             = "FORMATION_RAPPORT_CONVOCATION_AUTOMATIQUE";

    //DEMANDE EXTERNE //--------------------

    const DEMANDE_EXTERNE_VALIDATION_AGENT            = "FORMATION_DEMANDE_EXTERNE_VALIDATION_AGENT";
    const DEMANDE_EXTERNE_VALIDATION_RESP_DRH         = "FORMATION_DEMANDE_EXTERNE_VALIDATION_RESP_DRH";
    const DEMANDE_EXTERNE_VALIDATION_RESP_AGENT       = "FORMATION_DEMANDE_EXTERNE_VALIDATION_RESP_AGENT";
    const DEMANDE_EXTERNE_VALIDATION_DRH              = "FORMATION_DEMANDE_EXTERNE_VALIDATION_DRH";
    const DEMANDE_EXTERNE_VALIDATION_REFUS            = "FORMATION_DEMANDE_EXTERNE_VALIDATION_REFUS";
}