<?php

namespace Formation\Provider\Template;

class MailTemplates {

    //circuit d'inscription
    const FORMATION_INSCRIPTION_DEMANDE_AGENT           = "FORMATION_INSCRIPTION_1_AGENT";
    const FORMATION_INSCRIPTION_RESPONSABLE_VALIDATION  = "FORMATION_INSCRIPTION_2_RESPONSABLE_VALIDATION";
    const FORMATION_INSCRIPTION_RESPONSABLE_REFUS       = "FORMATION_INSCRIPTION_2_RESPONSABLE_REFUS";
    const FORMATION_INSCRIPTION_DRH_VALIDATION          = "FORMATION_INSCRIPTION_3_DRH_VALIDATION";
    const FORMATION_INSCRIPTION_DRH_REFUS               = "FORMATION_INSCRIPTION_3_DRH_REFUS";

    //rappel
    const FORMATION_RAPPEL_AVANT_FORMATION              = "FORMATION_NOTIFICATION_SESSION_IMMINENTE";
    const FORMATION_INSCRIPTION_OUVERTE                 = "FORMATION_NOTIFICATION_ABONNEMENT_FORMATION";
    const FORMATION_NOUVELLES_FORMATIONS                = "FORMATION_NOTIFICATION_NOUVELLES_SESSIONS";

    //RAPPORT
    const FORMATION_INSCRIPTION_CLOTURE_AUTOMATIQUE     = "FORMATION_RAPPORT_CLOTURE_AUTOMATIQUE";

}