<?php

namespace Formation\Provider\Template;

class TextTemplates {

    const MES_FORMATIONS_ACCUEIL = "MES_FORMATIONS_ACCUEIL";
    const MES_FORMATIONS_PROJETPERSO = "MES_FORMATIONS_PROJETPERSO";
    const ENQUETE_EXPLICATION = "ENQUETE_EXPLICATION";

    const PLANS_DE_FORMATION = "PLANS_DE_FORMATION";
    const INSCRIPTION_STAGE_HORS_PLAN = "INSCRIPTION_STAGE_HORS_PLAN";
    const INSCRIPTION_FORMATION_DU_PLAN = "INSCRIPTION_FORMATION_DU_PLAN";


}