<?php

/**
 * @see \Element\Controller\CompetenceDisciplineController::afficherAction()
 * @var CompetenceDiscipline $discipline
 * @var FicheMetier[] $fichesMetiers
 */

use Element\Entity\Db\Competence;
use Element\Entity\Db\CompetenceDiscipline;
use Element\Provider\Privilege\CompetencePrivileges;
use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;

$canAfficherCompetence = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_AFFICHER));
$canAfficherFicheMetier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));

$competences = $discipline->getCompetences();
usort($competences, function (Competence $a, Competence $b) {
    if ($a->getType() !== $b->getType()) { return $a->getType()->getLibelle() <=> $b->getType()->getLibelle(); }
    return $a->getLibelle() <=> $b->getLibelle();
});

?>

<dl class="dl-horizontal">
    <dt> Libellé </dt>
    <dd> <?php echo $discipline->getLibelle(); ?> </dd>
    <dt> Compétences associées </dt>
    <dd>
        <?php echo count($competences); ?> compétence·s associée·s
        <ul>
            <?php foreach ($competences as $competence) : ?>
                <li>
                    <span class="badge"> <?php echo $competence->getType()->getLibelle(); ?> </span>
                    <?php echo $competence->getLibelle(); ?>
                    <?php if ($canAfficherCompetence) : ?>
                        <?php /** @see \Element\Controller\CompetenceController::afficherAction() */ ?>
                        <span class="action">
                        <a  href="<?php echo $this->url('element/competence/afficher', ['competence' => $competence->getId()], [], true); ?>"
                            class="action secondary">
                            <span class="icon icon-voir"></span>
                            Accéder
                        </a>
                    </span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </dd>
    <dt> Fiches métiers ayant une compétence de cette discipline </dt>
    <dd>
        <?php echo count($fichesMetiers); ?> Fiche·s métier·s associée·s
        <ul>
            <?php foreach ($fichesMetiers as $ficheMetier) : ?>
            <li>
                <?php echo $this->etatinstance($ficheMetier->getEtatActif()); ?> <?php echo $ficheMetier->getLibelle(); ?>
                <?php if ($canAfficherFicheMetier) : ?>
                    <?php /** @see \FicheMetier\Controller\FicheMetierController::afficherAction() */ ?>
                    <span class="action">
                    <a  href="<?php echo $this->url('fiche-metier/afficher', ['fiche-metier' => $ficheMetier->getId()], [], true); ?>"
                        class="action secondary">
                        <span class="icon icon-voir"></span>
                        Accéder
                    </a>
                    </span>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </dd>
</dl>

