<?php

use Agent\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\AgentForceSansObligation;
use EntretienProfessionnel\Entity\Db\Campagne;
use Structure\Entity\Db\Structure;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @var Campagne[] $campagnes
 * @var ?Campagne $campagne
 * @var ?Agent $agent
 * @var ?string $forcage
 * @var ?string $structure
 * @var array $structuresGroups
 */

?>

<div class="card card-default">
    <div class="card-header">
        <span class="icon icon-filtrer"></span>
        Filtre de recherche des exceptions
    </div>
    <div class="card-body">

        <form id="filtre" action="<?php echo $this->url(); ?>" method="get">
            <div class="row">
                <div class="col-md-10">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="campagne">Campagne : </label>
                            <select id="campagne" name="campagne" class="selectpicker" data-live-search="true">
                                <option value=""> Toutes les campagnes</option>
                                <?php foreach ($campagnes as $campagne_) : ?>
                                    <?php $texte = "data-content='" . $campagne_->getAnnee() . "  "; ?>
                                    <?php if ($campagne_->estEnCours()) : ?>
                                        <?php $texte .= '<span class="text-success"><span class="icon icon-checked"></span> En cours </span>'; ?>
                                    <?php else : ?>
                                        <?php $texte .= '<span class="danger"><span class="icon icon-unchecked"></span> Terminée </span>'; ?>
                                    <?php endif; ?>
                                    <?php $texte .= "'"; ?>
                                    <option value="<?php echo $campagne_->getId(); ?>" <?php if ($campagne_ === $campagne) echo " selected "; ?> <?php echo $texte; ?>>
                                        <?php echo $campagne_->getAnnee(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="forcage"> Type d'exception : </label>
                            <select id="forcage" name="forcage" class="selectpicker">
                                <option value=""> Peu importe</option>
                                <?php foreach (AgentForceSansObligation::FORCAGE_ARRAY as $id => $libelle): ?>
                                    <option value="<?php echo $id; ?>"
                                        <?php if (isset($forcage) and $forcage === $id) echo " selected "; ?>
                                    > <?php echo $libelle; ?> </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="structure"> Structure d'affectation : </label>
                            <select id="structure" name="structure" class="form-control selectpicker" data-live-search="true">
                                <option value="" disabled  hidden
                                        <?php if (!isset($structure) OR $structure === '') { echo " selected " ; } ?>
                                >
                                    Sélectionnez une option
                                </option>
                                <option value="-1"
                                        <?php if (isset($structure) AND $structure == '-1') { echo " selected " ; } ?>
                                >
                                    Aucune structure
                                </option>
                                <?php foreach ($structuresGroups as $group) : ?>
                                    <optgroup label="<?php echo $group['label']; ?>">
                                        <?php foreach ($group['options'] as $id => $label) : ?>
                                            <option value="<?php echo $id; ?>"
                                                    <?php if ($structure  == $id) echo 'selected'; ?>
                                            >
                                                <?php echo $label; ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </optgroup>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-1" style="width: auto !important;">
                            <label for="agent"> Agent·e : </label>
                        </div>
                        <div class="col-md-10">
                            <?php
                            /** @see  \Agent\Controller\AgentController::rechercherAction() */
                            $agentF = new SearchAndSelect('agent');
                            $agentF
                                ->setAutocompleteSource($this->url('agent/rechercher'))
                                ->setSelectionRequired()
                                ->setAttributes([
                                    'id' => 'agent',
                                    'placeholder' => "Rechercher un·e agent·e (min. 2 lettres)",
                                ]);
                            ?>
                            <?php echo $this->formControlGroup($agentF); ?>
                        </div>
                    </div>
                </div>
                <!-- BOUTON -->
                <div class="col-md-2">
                    <button class="btn btn-primary action" id="filter">
                        <span class="icon icon-filtrer"></span>
                        Filtrer
                    </button>
                    <button class="btn btn-primary action" id="clear">
                        <span class="icon icon-gommer"></span>
                        Remise à zéro
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $("form#filtre").submit(function (e) {
        e.preventDefault();
    });

    $('button#clear').on("click", function (e) {
        e.preventDefault();
        window.location.href = '?';
    });

    $('button#filter').click(function () {
        // let groupeId = $('select#campagne option:selected').val();
        // let activiteId = $('select#activite option:selected').val();
        // console.log( "activite=" + activiteId);

        let campagneId = $('select#campagne option:selected').val();
        let agentId = $('input[name="agent[id]"]').val();
        let forcageId = $('select#forcage option:selected').val();
        let $structureId = $('select#structure option:selected').val();

        let query = "";
        query += "&forcage=" + forcageId;
        query += "&campagne=" + campagneId;
        query += "&agent=" + agentId;
        query += "&structure=" + $structureId;
        window.location.href = '?' + query;
    });

    $(function () {
        <?php if ($agent !== null) :?>
        $('input[name="agent[id]"]').val("<?php echo $agent->getId(); ?>");
        $('input[name="agent[label]"]').val("<?php echo $agent->getDenomination(); ?>");
        <?php endif; ?>
    });
</script>
