<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\AgentForceSansObligation;
use EntretienProfessionnel\Entity\Db\Campagne;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @var Campagne[] $campagnes
 * @var ?Campagne $campagne
 * @var ?Agent $agent
 * @var ?string $forcage
 */

?>

<div class="card card-default">
    <div class="card-header">
        <span class="icon icon-filtrer"></span>
        Filtre de recherche des forçages
    </div>
    <div class="card-body">

        <form id="filtre" action="<?php echo $this->url(); ?>" method="get">
            <div class="row">
                <div class="col-md-3">
                    <label for="campagne">Campagne d'entretien professionnel: </label><br>
                    <select id="campagne" name="campagne" class="selectpicker" data-live-search="true">
                        <option value=""> Toutes les campagnes</option>
                        <?php foreach ($campagnes as $campagne_) : ?>
                            <?php $texte = "data-content='" . $campagne_->getAnnee() . "  "; ?>
                            <?php if ($campagne_->estEnCours()) : ?>
                                <?php $texte .= '<span class="text-success"><span class="icon icon-checked"></span> En cours </span>'; ?>
                            <?php else : ?>
                                <?php $texte .= '<span class="danger"><span class="icon icon-unchecked"></span> Terminée </span>'; ?>
                            <?php endif; ?>
                            <?php $texte .= "'"; ?>
                            <option value="<?php echo $campagne_->getId(); ?>" <?php if ($campagne_ === $campagne) echo " selected "; ?> <?php echo $texte; ?>>
                                <?php echo $campagne_->getAnnee(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="forcage"> Type de forçage : </label>
                    <select id="forcage" name="forcage" class="selectpicker">
                        <option value=""> Peu importe</option>
                        <?php foreach (AgentForceSansObligation::FORCAGE_ARRAY as $id => $libelle): ?>
                            <option value="<?php echo $id; ?>"
                                <?php if (isset($forcage) and $forcage === $id) echo " selected "; ?>
                            > <?php echo $libelle; ?> </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="activite"> Agent : </label>
                    <?php
                    /** @see  \Application\Controller\AgentController::rechercherAction() */
                    $agentF = new SearchAndSelect('agent');
                    $agentF
                        ->setAutocompleteSource($this->url('agent/rechercher'))
                        ->setSelectionRequired(true)
                        ->setAttributes([
                            'id' => 'agent',
                            'placeholder' => "Sélectionner un·e agent·e",
                        ]);
                    ?>
                    <?php echo $this->formControlGroup($agentF); ?>
                </div>
                <!-- BOUTON -->
                <div class="col-md-3">
                    <div class="pull-right">
                        <button class="btn btn-primary action" id="clear">
                            <span class="icon icon-gommer"></span>
                            R.A.Z.
                        </button>

                        <button class="btn btn-primary action" id="filter">
                            <span class="icon icon-filtrer"></span>
                            Filtrer
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $("form#filtre").submit(function (e) {
        e.preventDefault();
    });

    $('button#clear').on("click", function (e) {
        e.preventDefault();
        window.location.href = '?';
    });

    $('button#filter').click(function () {
        // let groupeId = $('select#campagne option:selected').val();
        // let activiteId = $('select#activite option:selected').val();
        // console.log( "activite=" + activiteId);

        let campagneId = $('select#campagne option:selected').val();
        let agentId = $('input[name="agent[id]"]').val();
        let forcageId = $('select#forcage option:selected').val();

        let query = "";
        query += "&forcage=" + forcageId;
        query += "&campagne=" + campagneId;
        query += "&agent=" + agentId;
        window.location.href = '?' + query;
    });

    $(function () {
        <?php if ($agent !== null) :?>
        $('input[name="agent[id]"]').val("<?php echo $agent->getId(); ?>");
        $('input[name="agent[label]"]').val("<?php echo $agent->getDenomination(); ?>");
        <?php endif; ?>
    });
</script>
