<?php

use Structure\Entity\Db\Observateur;
use Structure\Provider\Privilege\StructureobservateurPrivileges;

/**
 * @see \Structure\Controller\ObservateurController::indexAction()
 * @var Observateur[] $observateurs
 */

$this->headTitle("Observateur·trices de structure");


$canAfficher = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_AFFICHER));
$canAjouter = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_AJOUTER));
$canModifier = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_MODIFIER));
$canHistoriser = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_HISTORISER));
$canSupprimer = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_SUPPRIMER));

?>

<h1 class="page-header">
    Observateur·trices de structure
</h1>

<div class="alert alert-info">
    <span class="icon icon-information"></span>
    Nommer une personne en tant qu'observateur·trice d'une structure la nomme "automatiquement" pour les structures filles de celle-ci.
</div>

<div>
    <span class="todo">Ajouter Filtre de recherche</span>
</div>

<?php if ($canAjouter) : ?>
    <?php /** @see \Structure\Controller\ObservateurController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('structure/observateur/ajouter', [], [], true); ?>"
    class="btn btn-primary ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un·e observateur·trice
    </a>
<?php endif; ?>

<table class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Structure </th>
        <th> Utilisateur·trice </th>
        <th> Description </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($observateurs as $observateur) : ?>
        <tr class="<?php if ($observateur->estHistorise()) echo " historise "; ?>">
            <td>
                <?php //todo action vers structures ?>
                <?php echo $observateur->getStructure()->getLibelleLong(); ?>
            </td>
            <td>
                <?php //todo action vers utilisateurs ?>
                <?php echo $observateur->getUtilisateur()->getDisplayName(); ?>
            </td>
            <td>
                <?php if ($observateur->getDescription()): ?>
                    <span class="icon icon-checked text-success" data-bs-toggle="tooltip" data-bs-html="true"
                          title="<?php echo $observateur->getDescription(); ?>"></span>
                <?php else : ?>
                    <span class="icon icon-unchecked text-danger"></span>
                <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Structure\Controller\ObservateurController::afficherAction() */ ?>
                    <a href="<?php echo $this->url("structure/observateur/afficher", ['observateur' => $observateur->getId()] , [], true); ?>"
                       class="ajax-modal">
                        <span class="icon icon-voir"></span> Afficher</a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \Structure\Controller\ObservateurController::modifierAction() */ ?>
                    <a href="<?php echo $this->url("structure/observateur/modifier", ['observateur' => $observateur->getId()] , [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span> Modifier</a>
                <?php endif; ?>
                <?php if ($canHistoriser): ?>
                    <br>
                    <?php if ($observateur->estNonHistorise()) : ?>
                        <?php /** @see \Structure\Controller\ObservateurController::historiserAction() */ ?>
                        <a href="<?php echo $this->url("structure/observateur/historiser", ['observateur' => $observateur->getId()] , [], true); ?>">
                            <span class="icon icon-historiser"></span> Historiser</a>
                    <?php else : ?>
                        <?php /** @see \Structure\Controller\ObservateurController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url("structure/observateur/restaurer", ['observateur' => $observateur->getId()] , [], true); ?>">
                            <span class="icon icon-restaurer"></span> Restaurer</a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer): ?>
                    <br>
                    <?php /** @see \Structure\Controller\ObservateurController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url("structure/observateur/supprimer", ['observateur' => $observateur->getId()] , [], true); ?>"
                        class="ajax-modal" data-event="modification">
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span> Supprimer
                        </span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>