<?php

/**
 * @see \UnicaenEtat\Controller\EtatTypeController::indexAction()
 * @var EtatType[] $etatTypes
 */

use UnicaenEtat\Entity\Db\EtatType;

?>
<h1 class="page-header">
    Index des types d'état
</h1>

<div class="main">

    <div class="row">
        <div class="col-md-8">
            <h2>Etat Type <span class="badge"><?php echo count($etatTypes); ?></span></h2>
        </div>
        <div class="pull-right">
            <?php /** @see \UnicaenEtat\Controller\IndexController::indexAction() */ ?>
            <a href="<?php echo $this->url('unicaen-etat', [], [], true); ?>"
               class="btn btn-info action">
                <span class="icon icon-retour"></span>
                Retour à l'index du module
            </a>
            <br/>
            <?php /** @see \UnicaenEtat\Controller\EtatTypeController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('unicaen-etat/etat-type/ajouter', [], [], true); ?>"
               class="btn btn-primary action ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un type d'état
            </a>
        </div>
    </div>

    <br/>

    <table id="etat-type" class="datatable table table-condensed">
        <thead>
        <tr>
            <th>Badge</th>
            <th>Code</th>
            <th>Libelle</th>
            <th style="width: 8rem;">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($etatTypes as $etatType) : ?>
            <tr class="<?php if ($etatType->estHistorise()) echo "historise"; ?>">
                <td> <?php echo $this->etattype($etatType); ?> </td>
                <td> <?php echo $etatType->getCode(); ?> </td>
                <td> <?php echo $etatType->getLibelle(); ?> </td>
                <td>
                    <?php /** @see \UnicaenEtat\Controller\EtatTypeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('unicaen-etat/etat-type/modifier', ['etat-type' => $etatType->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span></a>
                    <?php if ($etatType->estNonHistorise()) : ?>
                        <?php /** @see \UnicaenEtat\Controller\EtatTypeController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('unicaen-etat/etat-type/historiser', ['etat-type' => $etatType->getId()], [], true); ?>">
                            <span class="icon icon-historiser"></span></a>
                    <?php else: ?>
                        <?php /** @see \UnicaenEtat\Controller\EtatTypeController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('unicaen-etat/etat-type/restaurer', ['etat-type' => $etatType->getId()], [], true); ?>">
                            <span class="icon icon-restaurer"></span></a>
                    <?php endif; ?>
                    <?php /** @see \UnicaenEtat\Controller\EtatTypeController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('unicaen-etat/etat-type/supprimer', ['etat-type' => $etatType->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>