<?php

use Element\Entity\Db\Competence;
use FicheMetier\Form\FicheMetierImportation\FicheMetierImportationForm;
use Metier\Entity\Db\Metier;
use Metier\Entity\Db\Reference;

/**
 * @see \FicheReferentiel\Controller\ImporterController::importerDgafpCsvAction()
 * @var FicheMetierImportationForm $form
 * @var string|null $mode
 *
 * @var array $resultCompetences
 * @var array $resultMetiers
 * @var array $resultFiches
 */

?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Importation de fiches référentiels REFERENS3
        </h1>
    </div>
    <div class="col-md-3">
        <?php /** @see \FicheReferentiel\Controller\FicheReferentielController::indexAction() */ ?>
        <a href="<?php echo $this->url("fiche-referentiel", [], [], true); ?>"
           class="btn btn-primary">
            <span class="icon icon-listing"></span>
            Retour à l'index des fiches référentiels
        </a>
    </div>
</div>

<div class="card card-default">
    <div class="card-header">
        <h2>
            <span class="icon icon-csv"></span>
            Importer depuis un fichier csv
        </h2>
    </div>
    <div class="card-body">
        <?php echo $this->form($form); ?>
    </div>
</div>


<?php if (isset($mode) AND $mode !== null) : ?>
    <h2> Résultats de la lecture (mode: <?php echo $mode; ?>)</h2>

    <?php if ($resultCompetences AND !empty($resultCompetences['manquantes'])) : ?>
        <div class="alert alert-info">
            <?php echo count($resultCompetences['manquantes']); ?> nouvelles compétences non pas été trouvées (veuillez mettre à jour le dictionnaire de compétence REFERENS :
            <ul>
                <?php foreach ($resultCompetences['manquantes'] as $competence) : ?>
                    <li>
                        Compétence #<?php echo $competence; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <?php if ($resultMetiers AND !empty($resultMetiers['nouveaux'])) : ?>
        <div class="alert alert-info">
            <?php echo count($resultMetiers['nouveaux']); ?> nouveaux métiers <?php echo ($mode === 'import')?"ont":"seront"; ?> été ajoutés :
            <ul>
                <?php /** @var Metier $metier */ ?>
                <?php foreach ($resultMetiers['nouveaux'] as $code => $metier) : ?>
                    <li>
                        <span class="badge" style="background: var(--unistrap-color-main);">
                            <?php echo  $code; ?>
                        </span>
                        <?php echo $metier->getLibelle(); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <?php echo count($resultFiches['dictionnaires']); ?> fiches référentiels
    <?php if ($mode !== 'import') : ?>
        lues :
    <?php else : ?>
        importées
    <?php endif; ?>

    <ul>
    <?php foreach ($resultFiches['dictionnaires'] as $fiche) : ?>
        <li>
            <?php echo $fiche->getMetier()->getLibelle(); ?>
            <?php if ($mode === 'import') : ?>
                <?php /** @see \FicheReferentiel\Controller\FicheReferentielController::afficherAction() */ ?>
                <a href="<?php echo $this->url('fiche-referentiel/afficher', ['fiche-referentiel' => $fiche->getId()], [], true); ?>">
                    <span class="icon icon-voir"></span>
                    Afficher la fiche
                </a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>