<?php


use Application\Entity\Db\Agent;
use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\FormationInstanceInscrit;
use Structure\Entity\Db\Structure;
use Structure\Entity\Db\StructureResponsable;

/**
 * @see \Formation\Controller\StructureController::afficherAction()
 * @var Structure $structure
 * @var Structure[] $selecteur
 *
 * @var StructureResponsable[] $responsables
 * @var StructureResponsable[] $gestionnaires
 * @var Agent[] $agents
 *
 * @var FormationInstanceInscrit[] $inscriptionsNonValidees
 * @var FormationInstanceInscrit[] $inscriptionsValidees
 * @var DemandeExterne[] $demandesNonValidees
 * @var DemandeExterne[] $demandesValidees
 *
 */

$this->headTitle("Structure : " . $structure->getLibelleLong());

$now = new DateTime();

$nbAgent = count($agents);

$filles = $structure->getEnfants();
$filles = array_filter($filles, function (Structure $a) use ($now) {
    $fermeture = $a->getFermetureOW() ?? $a->getFermeture();
    return ($a->getDeleted() === null AND ($fermeture === null OR $fermeture > $now));  });
?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Structure
            <span class="highlight structure">
                <?php echo $structure->getLibelleLong(); ?>
            </span>
        </h1>
    </div>
    <div class="col-md-4">
    <?php if (! empty($selecteur)) : ?>
        <label for="structure-selecteur">Structure à afficher : <br/></label>
        <select id="structure-selecteur" name="structure-selecteur" class="bootstrap-select">
            <option value="">Aucune sélection</option>
            <?php foreach ($selecteur as $s) : ?>
                <option value="<?php echo $s->getId(); ?>" <?php if ($structure->getId() == $s->getId()) echo "selected"; ?>><?php echo $s->getLibelleCourt(); ?></option>
            <?php endforeach; ?>
        </select>
    <?php endif; ?>
    </div>
</div>

<?php echo $this->partial('partial/resume', ['structure' => $structure, 'filles' => $filles, 'responsables' => $responsables, 'gestionnaires' => $gestionnaires]); ?>

<div class="row">
    <div class="col-md-7">
        La structure est liée à <?php echo $nbAgent; ?> agent·s.
    </div>
    <div class="col-md-5">
        <?php /** @see \Formation\Controller\StructureController::listerLesAgentsAction() */ ?>
        <a href="<?php echo $this->url('formation/structure/lister-les-agents', ['structure' => $structure->getId()], [], true); ?>"
           class="btn btn-secondary ajax-modal"
       >
            <span class="icon icon-lister"></span>
            Lister les agents liés à la structure
        </a>
    </div>
</div>
<div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="formation-demande-tab"
            data-bs-toggle="tab" data-bs-target="#formation-demande"
            type="button" role="tab" aria-controls="formation-demande" aria-selected="true">
        Demandes de formations
    </button>
    <button class="nav-link" id="formation-liste-tab"
            data-bs-toggle="tab" data-bs-target="#formation-liste"
            type="button" role="tab" aria-controls="formation-liste" aria-selected="true">
        Listes des formations
    </button>
    <button class="nav-link" id="extraction-tab"
            data-bs-toggle="tab" data-bs-target="#extraction"
            type="button" role="tab" aria-controls="extraction" aria-selected="true">
        Extractions
    </button>
</div>

<div class="tab-content">
    <div id="formation-demande" class="tab-pane">
        <?php echo $this->partial('partial/demande-formation', ['inscriptions' => $inscriptionsNonValidees, 'demandes' => $demandesNonValidees]); ?>
    </div>

    <div id="formation-liste" class="tab-pane">
        <?php echo $this->partial('partial/liste-formation', ['inscriptions' => $inscriptionsValidees, 'demandes' => $demandesValidees]); ?>
    </div>

    <!-- Extraction ------------------------------------------------------------------------------------->
    <div id="extraction" class="tab-pane">
        <?php echo $this->partial('partial/extraction', ['structure' => $structure]); ?>
    </div>
</div>



<script>
    $(function() {
        $('select#structure-selecteur').change(function() {
            let id = $('select#structure-selecteur option:selected').val();
            if (id !== "" && id !== "<?php echo $structure->getId(); ?>") {
                let url = window.location.href;
                let splits = url.split("/");
                let last = (splits.at(-1));
                if (last === "structure") {
                    window.location.href = './structure/' + id;
                } else {
                    window.location.href = './' + id;
                }
            }
        });
    });

    $(function () {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "formation-demande";

        $('button').removeClass('active');
        $('button#' + name + '-tab').addClass('active');
        $('div.tab-pane').hide().removeClass('active');
        $('div#' + name).show().addClass('active');

        //$('#' + name + '-tab').tab("show");
        $('button.nav-link').on('click', function (e) {
            let anchor = $(this).attr('aria-controls');
            $('div.tab-pane').hide().removeClass('active');
            $('div#' + anchor).show().addClass('active');
            $('button').removeClass('active');
            $('button#' + anchor + '-tab').addClass('active');
            // console.log(anchor);
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#" + anchor);
        });
    });

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

