<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentStatut;
use UnicaenUtilisateur\Entity\Db\Role;
use UnicaenUtilisateur\Entity\Db\User;

/**
 * @see \Formation\Controller\StructureController::listerLesAgentsAction()
 * @var Agent[] $agents
 * @var User $user
 * @var Role $role
 */

$nbAgent = count($agents)
?>


<table class="table table-condensed table-hover">
    <thead>
    <tr>
        <th> Dénomination </th>
        <th> Statut·s </th>
        <th> Affectation·s </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) : ?>
        <tr>
            <td>
                <?php echo $agent->getDenomination(); ?>
            </td>
            <td>
                <?php $status = $statuts = AgentStatut::generateStatutsArray($agent->getStatutsActifs()); ?>
                <ul>
                    <?php foreach ($statuts as $statut) : ?>
                        <li>
                            <?php echo $statut; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td>
                <?php $affections = $agent->getAffectationsActifs(); ?>
                <ul>
                    <?php foreach ($affections as $affection) : ?>
                        <li>
                            <?php
                            $structure = $affection->getStructure();
                            $niveau2 = $structure?$structure->getNiv2():null;
                            ?>
                            <?php if ($structure) : ?>
                                <?php echo $structure->getLibelleLong(); ?>
                                <?php if ($niveau2 AND $niveau2 !== $structure) : ?>
                                    <br/> Rattaché&middot;e à <?php echo $niveau2->getLibelleLong(); ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($affection->isPrincipale()) : ?>
                                <br/> <em>Affectation principale</em>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<ul>
