<?php

use Agent\Entity\Db\Agent;
use Agent\Entity\Db\AgentEmploiType;
use Agent\Entity\Db\AgentGrade;
use Agent\Provider\Privilege\AgentPrivileges;
use Carriere\Entity\Db\EmploiType;

/**
 * @see \Carriere\Controller\EmploiTypeController::afficherAgentsAction();
 * @var EmploiType $emploiType
 * @var AgentEmploiType[] $agentEmploiTypes
 * @var Agent[] $agents
 */


usort($agentEmploiTypes, function (AgentEmploiType $a, AgentEmploiType $b) { return $a->getAgent()->getDenomination() <=> $b->getAgent()->getDenomination(); });

$now = new DateTime();
$actifs = 0;
$inactifs = 0;
foreach ($agentEmploiTypes as $agentEmploiType) {
    if ($agentEmploiType->estFini($now)) $inactifs++; else $actifs++;
}
?>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-5"> Emploi-Type</dt>
            <dd class="col-md-7">[#<?php echo $emploiType->getId(); ?>] <?php echo $emploiType->getLibelleLong(); ?></dd>
            <!--            <dt class="col-md-5"> #Agent </dt>-->
            <!--            <dd class="col-md-7"> --><?php //echo count($agents); ?><!--</dd>-->
            <dt class="col-md-5"> #Agent·e</dt>
            <dd class="col-md-7"> <?php echo $actifs; ?> actif·ives (<?php echo $inactifs ?> inactif·ives)</dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-5"> Date ouverture</dt>
            <dd class="col-md-7"> <?php echo ($emploiType->getDateDebut()) ? $emploiType->getDateDebut()->format('d/m/Y') : "---"; ?>  </dd>
            <dt class="col-md-5"> Date fermeture</dt>
            <dd class="col-md-7"> <?php echo ($emploiType->getDateFin()) ? $emploiType->getDateFin()->format('d/m/Y') : "---"; ?></dd>
        </dl>
    </div>
</div>

<label for="actif_only">Conserver que les situations en cours</label>
<input type="checkbox" name="actif_only" id="actif_only" checked>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Id</th>
        <th> Agent·e</th>
        <th> Début</th>
        <th> Fin</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($agentEmploiTypes as $agentEmploiType) : ?>
        <?php $agent = $agentEmploiType->getAgent(); ?>
        <tr <?php if ($agentEmploiType->estFini($now)) echo 'class="historise"'; ?> >
            <td> <?php echo $agentEmploiType->getId(); ?> </td>
            <td>
                <?php if ($this->isAllowed($agent, AgentPrivileges::AGENT_AFFICHER)) : ?>
                    <?php /** @see \Agent\Controller\AgentController::informationsAction() */ ?>
                    <a href="<?php echo $this->url('agent/informations', ['agent' => $agent->getId()], [], true); ?>"
                            target="_blank"
                       >
                        <?php echo $agent->getDenomination(); ?>
                    </a>
                <?php else : ?>
                    <?php echo $agent->getDenomination(); ?>
                <?php endif; ?>
            </td>
            <td> <?php echo ($agentEmploiType->getDateDebut()) ? $agentEmploiType->getDateDebut()->format('d/m/Y') : "---"; ?> </td>
            <td> <?php echo ($agentEmploiType->getDateFin()) ? $agentEmploiType->getDateFin()->format('d/m/Y') : "---"; ?> </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $('tr.historise').hide();
    $('#actif_only').on('change', function () {
        let val = $('#actif_only').is(':checked');
        if (val === true) $('tr.historise').hide(); else $('tr.historise').show();
    });
</script>


