<?php

use Agent\Entity\Db\Agent;
use Carriere\Entity\Db\EmploiType;
use Carriere\Provider\Privilege\EmploiTypePrivileges;

/**
 * @see \Carriere\Controller\EmploiTypeController::indexAction()
 * @var EmploiType[] $emploisTypes
 * @var Agent[] $agents
 * @var bool $avecAgent
 * @var array $dictionnaire
 */


$this->headTitle("Liste des emplois types");

$canLister = $this->isAllowed(EmploiTypePrivileges::getResourceId(EmploiTypePrivileges::EMPLOITYPE_LISTER_AGENTS));
$canModifier = $this->isAllowed(EmploiTypePrivileges::getResourceId(EmploiTypePrivileges::EMPLOITYPE_MODIFIER));

?>

<h1 class="page-header">
    Liste des emplois types
    <span class="badge">
        <?php if ($avecAgent) : ?>
            <?php echo count($dictionnaire); ?>
        <?php else : ?>
            <?php echo count($emploisTypes); ?>
        <?php endif; ?>
    </span>
</h1>

<div class="col-md-6 alert alert-info" style="margin-top: 1rem;">
    <span class="icon icon-refresh"></span>
    Données synchronisées
    <?php if ($avecAgent) : ?>
        <br>
        <span class="icon icon-information"></span>
        Seuls les emploi-types avec au moins un agent·e sont présentés
    <?php endif; ?>
</div>

<table class="datatable table table-condensed" id="emploi_types">
    <thead>
    <tr>
        <th class="col-md-6"> Libellé</th>
        <th class="col-md-2"> Code</th>
        <th class="col-md-2"> #Agent/Emploi-Type</th>
        <th class="col-md-2"> Action</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($emploisTypes as $emploiType) : ?>
        <?php if (!$avecAgent or (isset($dictionnaire[$emploiType->getId()]) and $dictionnaire[$emploiType->getId()] !== 0)) : ?>
            <tr>
                <td data-column-id="Libellé">
                <span title="<?php echo $emploiType->generateTooltip(); ?>" data-bs-toggle="tooltip"
                      data-bs-html="true">
                    <?php echo $emploiType->getLibelleLong(); ?>
                </span>
                </td>
                <td data-column-id="Code">
                    <code><?php echo $emploiType->getCode(); ?></code>
                </td>
                <td data-column-id="#Agent/Emploi-Type">
                    <?php echo $dictionnaire[$emploiType->getId()]??0; ?>
                </td>
                <td data-column-id="Action">
                    <?php if ($canLister) : ?>
                        <a
                                <?php /** @see \Carriere\Controller\EmploiTypeController::afficherAgentsAction() */ ?>
                                href="<?php echo $this->url('emploi-type/afficher-agents', ['emploi-type' => $emploiType->getId()], ['fragment' => 'emploi-type'], true); ?>"
                                class="ajax-modal action secondary" data-event="modification"
                        >
                            <span class="icon icon-users"></span>
                            Lister les agents
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('table#emploi_types').DataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [3], orderable: false}
            ]
        });
    });
</script>