<?php

/**
 * @var Autoform\Entity\Db\Formulaire $formulaire
 * @var Autoform\Entity\Db\FormulaireReponse[] $reponses
 */

?>

        <?php
            /** @var Autoform\Entity\Db\Categorie[] $categories */
            $categories = $formulaire->getCategories();
            $categories = array_filter($categories, function (Autoform\Entity\Db\Categorie $categorie) { return $categorie->estNonHistorise();});
            usort($categories, function (Autoform\Entity\Db\Categorie $a, Autoform\Entity\Db\Categorie $b) { return $a->getOrdre() - $b->getOrdre();});
        ?>

        <?php foreach ($categories as $categorie) : ?>

            <?php
                /** @var Autoform\Entity\Db\Champ[] $champs */
                $champs = $categorie->getChamps();
                $champs = array_filter($champs, function (Autoform\Entity\Db\Champ $champ) { return $champ->estNonHistorise();});
                usort($champs, function (Autoform\Entity\Db\Champ $a, Autoform\Entity\Db\Champ $b) { return $a->getOrdre() - $b->getOrdre();});

                $results = [];
                foreach ($champs as $champ) {
                    if ($reponses[$champ->getId()]) $results[] = $reponses[$champ->getId()];
                }
            ?>



            <?php if (!empty($champs) && !(empty($results))) : ?>

                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h2> <?php echo $categorie->getLibelle(); ?> </h2>
                    </div>
                    <div class="panel-body">
                        <ul>
                        <?php foreach ($champs as $champ) : ?>
                            <?php if (isset($reponses[$champ->getId()])) : ?>
                                 <?php echo $this->champAsResult()->render($champ, $reponses[$champ->getId()]->getReponse()); ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>

        <?php endforeach; ?>

