<?php

use Autoform\Entity\Db\Categorie;
use Autoform\Entity\Db\Champ;
use Autoform\Entity\Db\Formulaire;

/**
 * @see \Autoform\Controller\FormulaireController::afficherFormulaireAction()
 * @var Formulaire $formulaire
 * @var array $reponses
 * @var string $url
 */

$a=1;
?>


    <form class="autoform" method="post" action="<?php echo $url; ?>" >

<!--        <span id="hide" class="btn btn-info"> Cacher les catégories </span>-->
<!--        <span id="show" class="btn btn-info">Afficher les catégories </span>-->
        <input type="submit" value="Enregistrer le formulaire" class="btn btn-primary"/>

        <br/>
        <br/>

        <?php
            /** @var Categorie[] $categories */
            $categories = $formulaire->getCategories();
            $categories = array_filter($categories, function (Categorie $categorie) { return $categorie->estNonHistorise();});
            usort($categories, function (Categorie $a, Categorie $b) { return $a->getOrdre() - $b->getOrdre();});
        ?>

        <?php foreach ($categories as $categorie) : ?>

            <?php
                /** @var Champ[] $champs */
                $champs = $categorie->getChamps();
                $champs = array_filter($champs, function (Champ $champ) { return $champ->estNonHistorise();});
                usort($champs, function (Champ $a, Champ $b) { return $a->getOrdre() - $b->getOrdre();});
            ?>

            <?php if (!empty($champs)) : ?>

                <div class="panel panel-info">
                    <div class="panel-heading title-reductible">
                        <h2> <?php echo $categorie->getLibelle(); ?> </h2>
                    </div>
                    <div class="panel-body body-reductible">
                        <?php foreach ($champs as $champ) : ?>
                            <div> <?php echo $this->champAsInput()->render($champ, $reponses); ?> </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

        <?php endforeach; ?>

        <input type="submit" value="Enregistrer le formulaire" class="btn btn-primary"/>
    </form>

<script>
    // $('div.body-reductible').each(function() { $(this).hide()});
    //
    // $('div.title-reductible').click(function() {
    //     $(this).siblings().each(function() { $(this).toggle(); });
    // });
    //
    // $('span#hide').click(function() {
    //     $('div.body-reductible').each(function() { $(this).hide()});
    // });
    //
    // $('span#show').click(function() {
    //     $('div.body-reductible').each(function() { $(this).show()});
    // });

    $("select.periode").change(function() {
        checkPeriode($(this));
    });

    $("select.periode").each(function() {
        checkPeriode($(this));
    });

    function checkPeriode(element) {
        let name = element.attr('name');
        let splits = name.split("_");
        let id = splits[1];
        let value = $("select[name="+name+"] option:selected").val();

        if (value === "Balisée") {
            $("span#datation_" + id).show();
        } else {
            $("span#datation_" + id).hide();
        }
    }

    $('.selectpicker').selectpicker();

</script>