<?php

/**
 * @see \Autoform\Controller\FormulaireController::afficherResultatAction()
 * @var Formulaire $formulaire
 * @var FormulaireReponse[] $reponses
 */

use Autoform\Entity\Db\Categorie;
use Autoform\Entity\Db\Champ;
use Autoform\Entity\Db\Formulaire;
use Autoform\Entity\Db\FormulaireReponse;

?>

        <?php
            /** @var Categorie[] $categories */
            $categories = $formulaire->getCategories();
            $categories = array_filter($categories, function (Categorie $categorie) { return $categorie->estNonHistorise();});
            usort($categories, function (Categorie $a, Categorie $b) { return $a->getOrdre() - $b->getOrdre();});
        ?>

        <?php foreach ($categories as $categorie) : ?>

            <?php
                /** @var Champ[] $champs */
                $champs = $categorie->getChamps();
                $champs = array_filter($champs, function (Champ $champ) { return $champ->estNonHistorise();});
                usort($champs, function (Champ $a, Champ $b) { return $a->getOrdre() - $b->getOrdre();});

                $results = [];
                foreach ($champs as $champ) {
                    if ($reponses[$champ->getId()]) $results[] = $reponses[$champ->getId()];
                }
            ?>



            <?php if (!empty($champs) && !(empty($results))) : ?>

                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h2> <?php echo $categorie->getLibelle(); ?> </h2>
                    </div>
                    <div class="panel-body">
                        <ul>
                        <?php foreach ($champs as $champ) : ?>
                            <?php if (isset($reponses[$champ->getId()])) : ?>
                                 <?php echo $this->champAsResult()->render($champ, $reponses[$champ->getId()]->getReponse()); ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>

        <?php endforeach; ?>

