<?php

/**
 * @var \Autoform\Entity\Db\Formulaire $formulaire
 *
 * @see \Autoform\Controller\Formulaire\FormulaireController::modifierAction()
 */
use Autoform\Entity\Db\Categorie;
use Autoform\Entity\Db\Champ;
use Autoform\Provider\Privilege\CategoriePrivileges;
use Autoform\Provider\Privilege\ChampPrivileges;
use Autoform\Provider\Privilege\FormulairePrivileges;

$categories = $formulaire->getCategories();
usort($categories, function (Categorie $a, Categorie $b) { return ($a->getOrdre() - $b->getOrdre());});


$canModifierDescription     = $this->isAllowed(FormulairePrivileges::getResourceId(FormulairePrivileges::MODIFIER));

$canAjouterCategorie        = $this->isAllowed(CategoriePrivileges::getResourceId(CategoriePrivileges::CREER));
$canModifierCategorie       = $this->isAllowed(CategoriePrivileges::getResourceId(CategoriePrivileges::MODIFIER));
$canHistoriserCategorie     = $this->isAllowed(CategoriePrivileges::getResourceId(CategoriePrivileges::HISTORISER));
$canDetruireCategorie       = $this->isAllowed(CategoriePrivileges::getResourceId(CategoriePrivileges::DETRUIRE));

$canAjouterChamp            = $this->isAllowed(ChampPrivileges::getResourceId(ChampPrivileges::CREER));
$canModifierChamp           = $this->isAllowed(ChampPrivileges::getResourceId(ChampPrivileges::MODIFIER));
$canHistoriserChamp         = $this->isAllowed(ChampPrivileges::getResourceId(ChampPrivileges::HISTORISER));
$canDetruireChamp           = $this->isAllowed(ChampPrivileges::getResourceId(ChampPrivileges::DETRUIRE));

?>

<h1 class="page-header">
    Modification du formulaire : <br/>
    <?php echo $formulaire->getLibelle(); ?>
</h1>

<div class="main">

    <?php if ($canModifierDescription) : ?>
        <a
            <?php /** @see \Autoform\Controller\FormulaireController::modifierDescriptionAction() */ ?>
            href="<?php echo $this->url('autoform/formulaire/modifier-description', ['formulaire' => $formulaire->getId()], [], true); ?>"
           class="btn btn-primary ajax-modal"
           data-event="modification"
        >
            <span class="editer"></span>
            Modifier description
        </a>
    <?php endif; ?>

    <dl>
        <dt> Libellé </dt>
        <dd> <?php echo $formulaire->getLibelle(); ?> </dd>
        <dt> Description </dt>
        <dd> <?php echo $formulaire->getDescription(); ?></dd>
    </dl>

    <h2> Vue du formulaire </h2>

    <?php if ($canAjouterCategorie) : ?>
        <a
            <?php /** @see \Autoform\Controller\FormulaireController::ajouterCategorieAction() */ ?>
            href="<?php echo $this->url('autoform/formulaire/modifier/ajouter-categorie', ['formulaire' => $formulaire->getId()], [], true); ?>"
            class="btn btn-primary ajax-modal" data-event="modification"
        >
            <span class="icon ajouter"></span>
            Ajouter une catégorie
        </a>
    <?php endif; ?>
    <?php echo count($categories); ?> catégories.

<br/><br/>


    <?php foreach($categories as $categorie) : ?>
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="row">
                <div class="col-md-10">
                    <?php echo $categorie->getLibelle(); ?>
                </div>
                <div class="col-md-2">

                    <?php if ($canModifierCategorie) : ?>
                        <a
                            <?php /** @see \Autoform\Controller\FormulaireController::modifierCategorieAction() */ ?>
                            href="<?php echo $this->url('autoform/formulaire/modifier/modifier-categorie', ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                        >
                            <span class="icon editer" title="Modifier la catégorie"></span></a>
                        <a
                            <?php /** @see \Autoform\Controller\FormulaireController::bougerCategorieAction() */ ?>
                            href="<?php echo $this->url('autoform/formulaire/modifier/bouger-categorie', ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId(), 'direction' => 'haut'], [], true); ?>"
                        >
                            <span class="icon monter" title="Déplacer vers le haut" ></span></a>
                        <a
                            <?php /** @see \Autoform\Controller\FormulaireController::bougerCategorieAction() */ ?>
                            href="<?php echo $this->url('autoform/formulaire/modifier/bouger-categorie', ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId(), 'direction' => 'bas'], [], true); ?>"
                        >
                            <span class="icon descendre" title="Déplacer vers le bas"></span></a>
                    <?php endif; ?>

                    <?php if ($canHistoriserCategorie) : ?>
                        <?php if ($categorie->estNonHistorise()) : ?>
                            <a
                                <?php /** @see \Autoform\Controller\FormulaireController::historiserCategorieAction() */ ?>
                                href="<?php echo $this->url('autoform/formulaire/modifier/historiser-categorie', ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId()], [], true); ?>"
                            >
                                <span class="icon historiser" title="Historiser la catégorie" ></span></a>
                        <?php else : ?>
                            <a
                                <?php /** @see \Autoform\Controller\FormulaireController::restaurerCategorieAction() */ ?>
                                href="<?php echo $this->url('autoform/formulaire/modifier/restaurer-categorie', ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId()], [], true); ?>"
                            >
                                <span class="icon restaurer" title="Restaurer la catégorie" ></span></a>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if ($canDetruireCategorie) : ?>
                        <a
                            <?php /** @see \Autoform\Controller\FormulaireController::detruireCategorieAction() */ ?>
                            href="<?php echo $this->url('autoform/formulaire/modifier/detruire-categorie', ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId()], [], true); ?>">
                            <span class="icon detruire" title="Détuire la catégorie" ></span></a>
                    <?php endif; ?>
                </div>
                </div>
            </div>
            <div class="panel-body">
                <?php if ($canAjouterChamp) : ?>
                    <a
                        <?php /** @see \Autoform\Controller\FormulaireController::ajouterChampAction() */ ?>
                        href="<?php echo $this->url('autoform/formulaire/categorie/ajouter-champ',
                                ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId()],
                                [],
                                true); ?>"
                       class="btn btn-primary ajax-modal"
                       data-event="modification"
                    >
                        <span  class="icon ajouter"></span>
                        Ajouter un champ
                </a>
                <?php endif; ?>
                <?php echo count($categorie->getChamps()); ?> champs.

                <br/><br/>

                <?php
                    $champs = $categorie->getChamps();
                    usort($champs, function (Champ $a, Champ $b) { return ($a->getOrdre() - $b->getOrdre());});
                ?>
                <?php foreach($champs as $champ) : ?>
                    <div class="row survol">
                        <div class="col-md-10">
                            <?php
                            echo $this->champAsInput()->render($champ);
                            ?>
                        </div>
                        <div class="col-md-2">
                            <?php if ($canModifierChamp) : ?>
                                <a
                                    <?php /** @see \Autoform\Controller\FormulaireController::modifierChampAction() */ ?>
                                    href="<?php echo $this->url('autoform/formulaire/categorie/champ/modifier',
                                    ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId(), 'champ' => $champ->getId()],
                                    [],
                                    true); ?>"
                                   class="ajax-modal"
                                   data-event="modification"
                                >
                                <span class="icon editer" title="Modifier la catégorie"></span></a>
                                <a
                                    <?php /** @see \Autoform\Controller\FormulaireController::bougerChampAction() */ ?>
                                    href="<?php echo $this->url('autoform/formulaire/categorie/champ/bouger',
                                    ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId(), 'champ' => $champ->getId(), 'direction' => 'haut'],
                                    [],
                                    true); ?>">
                                <span class="icon monter" title="Déplacer vers le haut" ></span></a>
                                <a
                                    <?php /** @see \Autoform\Controller\FormulaireController::bougerChampAction() */ ?>
                                    href="<?php echo $this->url('autoform/formulaire/categorie/champ/bouger',
                                    ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId(), 'champ' => $champ->getId(), 'direction' => 'bas'],
                                    [],
                                    true); ?>">
                                <span class="icon descendre" title="Déplacer vers le bas"></span></a>
                            <?php endif; ?>

                            <?php if ($canHistoriserChamp) : ?>
                                <?php if ($champ->estNonHistorise()) : ?>
                                    <a
                                        <?php /** @see \Autoform\Controller\FormulaireController::historiserChampAction() */ ?>
                                        href="<?php echo $this->url('autoform/formulaire/categorie/champ/historiser',
                                        ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId(), 'champ' => $champ->getId()],
                                        [],
                                        true); ?>">
                                    <span class="icon historiser" title="Historiser la catégorie" ></span></a>
                                <?php else : ?>
                                    <a
                                        <?php /** @see \Autoform\Controller\FormulaireController::restaurerChampAction() */ ?>
                                        href="<?php echo $this->url('autoform/formulaire/categorie/champ/restaurer',
                                        ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId(), 'champ' => $champ->getId()],
                                        [],
                                        true); ?>">
                                    <span class="icon restaurer" title="Restaurer la catégorie" ></span></a>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($canDetruireChamp) : ?>
                                <a
                                    <?php /** @see \Autoform\Controller\FormulaireController::detruireChampAction() */ ?>
                                    href="<?php echo $this->url('autoform/formulaire/categorie/champ/detruire',
                                    ['formulaire' => $formulaire->getId(), 'categorie' => $categorie->getId(), 'champ' => $champ->getId()],
                                    [],
                                    true); ?>">
                                <span class="icon detruire" title="Détuire la catégorie" ></span></a>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endforeach; ?>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>