<?php

/**
 * @see \Application\Controller\ValidationController::afficherAction()
 *
 * @var \Application\Entity\Db\Validation $validation
 */
?>

<dl>
    <dt> Type </dt>
    <dd> <?php echo $validation->getType()->getLibelle(); ?> </dd>

    <dt> Validateur </dt>
    <dd> <?php echo $validation->getHistoModificateur()->getDisplayName(); ?></dd>

    <dt> Date de dernière modification </dt>
    <dd> <?php echo $validation->getHistoModification()->format('d/m/Y à H:i:s'); ?></dd>

    <dt> Valeur </dt>
    <dd> <?php echo $validation->getValeur()->getLibelle(); ?> </dd>

    <dt> Commentaire associé </dt>
    <dd> <?php echo $validation->getCommentaire(); ?></dd>
</dl>
