<?php

use FicheMetier\Entity\Db\CodeFonction;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;

/**
 * @see \FicheMetier\Controller\CodeFonctionController::afficherAction()
 * @var CodeFonction $codeFonction
 */

$fichesmetiers = $codeFonction->getFichesMetiers();

$canAfficherFicheMetier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));
?>

<?php if ($codeFonction->estHistorise()) : ?>
    <span class="badge" style="background: darkred; font-size: Large">Historisé</span>
<?php endif; ?>
<br>
<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-4"> Code fonction</dt>
            <dd class="col-md-8"> <code><?php echo $codeFonction->computeCode(); ?></code> </dd>
            <dt class="col-md-4"> Niveau de fonction</dt>
            <dd class="col-md-8"> <?php echo $codeFonction->getNiveauFonction()?->getLibelle(); ?> <code><?php echo $codeFonction->getNiveauFonction()?->getCode(); ?></code> </dd>
            <dt class="col-md-4"> Famille Professionnelle</dt>
            <dd class="col-md-8">
                <?php echo $codeFonction->getFamilleProfessionnelle()?->getLibelle(); ?>
                <code>
                    <?php echo $codeFonction->getFamilleProfessionnelle()?->getCorrespondance()?->getCategorie(); ?><?php echo $codeFonction->getFamilleProfessionnelle()?->getPosition(); ?>
                </code>
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-4"> Créée </dt>
            <dd class="col-md-8"> Le <?php echo $codeFonction->getHistoCreation()->format('d/m/y à H:i'); ?> par <?php echo $codeFonction->getHistoCreateur()->getDisplayName(); ?> </dd>
            <?php if ($codeFonction->getHistoModification()) : ?>
                <dt class="col-md-4"> Modifiée </dt>
                <dd class="col-md-8"> Le <?php echo $codeFonction->getHistoModification()->format('d/m/y à H:i'); ?> par <?php echo $codeFonction->getHistoModificateur()->getDisplayName(); ?> </dd>
            <?php endif; ?>
            <?php if ($codeFonction->getHistoDestruction()) : ?>
                <dt class="col-md-4"> Historisée </dt>
                <dd class="col-md-8"> Le <?php echo $codeFonction->getHistoDestruction()->format('d/m/y à H:i'); ?> par <?php echo $codeFonction->getHistoDestructeur()->getDisplayName(); ?> </dd>
            <?php endif; ?>
        </dl>
    </div>
</div>


<dl>
    <dt> Fiche·s métier·s attachée·s au code fonction </dt>
    <dd>
        <?php echo count($fichesmetiers); ?> fiche·s métier·s
        <ul>
            <?php foreach ($fichesmetiers as $fichemetier) : ?>
                <?php $libelle = $fichemetier->getLibelle()??$fichemetier->getMetier()->getLibelle(); ?>
                <li>
                    <?php
                    $ficheId = $fichemetier->getId();
                    ?>
                    <?php echo $fichemetier->printReference(); ?>
                    <?php echo $this->etatinstance($fichemetier->getEtatActif()); ?>
                    <?php if ($libelle !== null) : ?>
                        <?php echo $libelle; ?>
                        <?php if ($codeFonction === true): ?>
                            - <?php echo $fichemetier->getCodeFonction()?$fichemetier->getCodeFonction()->computeCode():"<em style='color:gray;'>Aucun code fonction</em>"; ?>
                        <?php endif; ?>
                    <?php else : ?>
                        <span class="text-danger"> Aucun libellé ou métier d'associé à la fiche métier #<?php echo $ficheId; ?></span>
                    <?php endif; ?>
                    <small>
                        <?php if ($canAfficherFicheMetier) : ?>
                            <?php /** @see \FicheMetier\Controller\FicheMetierController::afficherAction() */ ?>
                            <a href="<?php echo $this->url('fiche-metier/afficher', ['fiche-metier' => $fichemetier->getId()], ['force_canonical' => true], true); ?>"
                               class="action secondary" target="_blank"
                            >
                                <span class="icon icon-voir"></span>
                                Afficher
                            </a>
                        <?php endif; ?>
                    </small>
                </li>
            <?php endforeach; ?>
        </ul>
    </dd>
