<?php

use FicheMetier\Provider\Privilege\CodeFonctionPrivileges;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;
use FicheMetier\Entity\Db\CodeFonction;

/**
 * @see \FicheMetier\Controller\CodeFonctionController::indexAction()
 * @var CodeFonction[] $codesFonctions
 */

$this->headTitle("Codes fonctions");

$canFicheMetierIndex = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_INDEX));

$canAfficher = $this->isAllowed(CodeFonctionPrivileges::getResourceId(CodeFonctionPrivileges::CODEFONCTION_AFFICHER));
$canAjouter = $this->isAllowed(CodeFonctionPrivileges::getResourceId(CodeFonctionPrivileges::CODEFONCTION_AJOUTER));
$canModifier = $this->isAllowed(CodeFonctionPrivileges::getResourceId(CodeFonctionPrivileges::CODEFONCTION_MODIFIER));
$canHistoriser = $this->isAllowed(CodeFonctionPrivileges::getResourceId(CodeFonctionPrivileges::CODEFONCTION_HISTORISER));
$canSupprimer = $this->isAllowed(CodeFonctionPrivileges::getResourceId(CodeFonctionPrivileges::CODEFONCTION_SUPPRIMER));

?>

<h1 class="page-header">
    Codes fonctions
</h1>

<?php if ($canAjouter) : ?>
    <?php /** @see \FicheMetier\Controller\CodeFonctionController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('code-fonction/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un code fonction
    </a>
<?php endif; ?>

<table class="table table-condensed" id="codesfonctions">
    <thead>
    <tr>
        <th class="col-md-3"> Code fonction </th>
        <th class="col-md-3"> Niveau de fonction </th>
        <th class="col-md-4"> Famille professionnelle </th>
        <th class="col-md-2 action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($codesFonctions as $codeFonction): ?>
        <tr class="<?php if ($codeFonction->estHistorise()) echo "historise "; ?>">
            <td data-column-id="Code fonction">
                <code><?php echo $codeFonction->computeCode(); ?></code>
                <br>
                <?php $fichesmetiers = $codeFonction->getFichesMetiers(); ?>
                <?php if (!empty($fichesmetiers)): ?>
                    <?php if ($canFicheMetierIndex): ?>
                        <?php /** @see \FicheMetier\Controller\FicheMetierController::indexAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier', [], ['query' => ['codefonction' => $codeFonction->getId()]], true) ?>">
                            <span class="badge fichemetier"><?php echo count($fichesmetiers) ?> fiches métiers</span></a>
                    <?php else:  ?>
                        <span class="badge fichemetier"><?php echo count($fichesmetiers) ?> fiches métiers</span>
                    <?php endif; ?>
                <?php endif; ?>

            </td>
            <td data-column-id="Niveau de fonction">
                <?php if ($codeFonction->getNiveauFonction()) : ?>
                    <?php echo $codeFonction->getNiveauFonction()->getLibelle(); ?>
                <?php else : ?>
                    <em style="color: gray;">Aucun niveau de fonction</em>
                <?php endif; ?>
            </td>
            <td data-column-id="Famille professionnelle">
                <?php if ($codeFonction->getFamilleProfessionnelle()) : ?>
                    <?php echo $codeFonction->getFamilleProfessionnelle()->getLibelle(); ?>
                <?php else : ?>
                    <em style="color: gray;">Aucune famille professionnelle</em>
                <?php endif; ?>
            </td>
            <td data-column-id="Action" class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \FicheMetier\Controller\CodeFonctionController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('code-fonction/afficher', ['code-fonction' => $codeFonction->getId()], [], true) ?>"
                       class="action secondary ajax-modal">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\CodeFonctionController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('code-fonction/modifier', ['code-fonction' => $codeFonction->getId()], [], true) ?>"
                       class="action primary ajax-modal" data-event="modification">
                        <span class="icon icon-modifier"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($codeFonction->estNonHistorise()): ?>
                        <?php /** @see \FicheMetier\Controller\CodeFonctionController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('code-fonction/historiser', ['code-fonction' => $codeFonction->getId()], [], true) ?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else: ?>
                        <?php /** @see \FicheMetier\Controller\CodeFonctionController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('code-fonction/restaurer', ['code-fonction' => $codeFonction->getId()], [], true) ?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\CodeFonctionController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('code-fonction/supprimer', ['code-fonction' => $codeFonction->getId()], [], true) ?>"
                       class="action danger ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("#codesfonctions").DataTable({
            info: true,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [3], orderable: false }
            ]
        });
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>