<?php

/**
 * @see CompetenceController::afficherCompetenceTypeAction()
 *
 * @var CompetenceType $type
 */
use Application\Controller\CompetenceController;use Application\Entity\Db\CompetenceType;

?>

<dl class="dl-horizontal">
    <dt> Libellé </dt>
    <dd> <?php echo $type->getLibelle(); ?> </dd>
    <dt> Modificateur </dt>
    <dd> <?php echo $type->getHistoModificateur()->getDisplayName() ; ?> le <?php echo $type->getHistoModification()->format('d/m/Y à H:m:s'); ?> </dd>
    <dt> Compétences associées </dt>
    <dd> TODO </dd>
</dl>
