<?php

/**
 * @see \Application\Controller\CompetenceMaitriseController::afficherAction()
 *
 * @var CompetenceMaitrise $maitrise
 */

use Application\Controller\CompetenceController;
use Application\Entity\Db\CompetenceMaitrise;
use Application\Entity\Db\CompetenceTheme;

?>

<dl class="dl-horizontal">
    <dt> Libellé </dt>
    <dd> <?php echo $maitrise->getLibelle(); ?> </dd>
    <dt> Niveau </dt>
    <dd> <?php echo $maitrise->getNiveau(); ?> </dd>
    <dt> Description </dt>
    <dd> <?php echo $maitrise->getDescription(); ?> </dd>
    <dt> Modificateur </dt>
    <dd> <?php echo $maitrise->getHistoModificateur()->getDisplayName() ; ?> le <?php echo $maitrise->getHistoModification()->format('d/m/Y à H:i:s'); ?> </dd>
    <?php if ($maitrise->estHistorise()) : ?>
        <dt> Historisation </dt>
        <dd> <?php echo $maitrise->getHistoDestructeur()->getDisplayName() ; ?> le <?php echo $maitrise->getHistoDestruction()->format('d/m/Y à H:i:s'); ?> </dd>
    <?php endif; ?>
</dl>
