<?php

/**
 * @see CompetenceController::afficherAction()
 *
 * @var Competence $competence
 */

use Application\Controller\CompetenceController;
use Application\Entity\Db\Competence;

?>

<dl class="dl-horizontal">
    <dt> Libellé </dt>
    <dd> <?php echo $competence->getLibelle(); ?> </dd>
    <dt> Type </dt>
    <dd> <?php echo ($competence->getType())?$competence->getType()->getLibelle():"Aucun"; ?> </dd>
    <dt> Thème </dt>
    <dd> <?php echo ($competence->getTheme())?$competence->getTheme()->getLibelle():"Aucun"; ?> </dd>
    <dt> Précision </dt>
    <dd> <?php echo $competence->getPrecision(); ?> </dd>
    <dt> Description </dt>
    <dd> <?php echo $competence->getDescription(); ?> </dd>

    <dt> Modificateur </dt>
    <dd> <?php echo $competence->getHistoModificateur()->getDisplayName() ; ?> le <?php echo $competence->getHistoModification()->format('d/m/Y à H:i:s'); ?> </dd>
    <dt> Agents </dt>
    <dd>
<!--        <span class="badge"> --><?php //echo count($theme->getCompetences()); ?><!--</span>-->
<!--        <ul>-->
<!--            --><?php //foreach ($theme->getCompetences() as $competence) : ?>
<!--                <li> --><?php //echo $competence->getLibelle(); ?><!-- </li>-->
<!--            --><?php //endforeach; ?>
<!--        </ul>-->
    </dd>
</dl>
