<?php

/**
 * @see CompetenceController::indexAction()
 * @var CompetenceType[]    $types
 * @var CompetenceTheme[]   $themes
 * @var Competence[]        $competences
 * @var array               $competencesByType
 */

use Application\Controller\CompetenceController;
use Application\Entity\Db\Competence;
use Application\Entity\Db\CompetenceTheme;
use Application\Entity\Db\CompetenceType;
use Application\Provider\Privilege\CompetencePrivileges;

$canVoir        = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_AFFICHER));
$canAjouter     = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_AJOUTER));
$canModifier    = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_EDITER));
$canHistoriser  = $canModifier;
$canDetruire    = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_EFFACER));

$this->headTitle("Index des compétences");

?>

<h1 class="page-header">
    Index des compétences
</h1>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <?php foreach ($competencesByType as $type => $competences) : ?>
            <?php
            $libelle = str_replace("é","e",$type);
            $clibelle = str_replace("é","e",$type);
            ?>
            <li role="<?php echo $libelle; ?>" >
                <a href="#<?php echo $clibelle; ?>" aria-controls="<?php echo $clibelle; ?>" role="tab" data-toggle="tabz" >
                    <?php echo $libelle; ?> &nbsp;
                    <span class="badge">
                        <?php echo count($competences); ?>
                    </span>
                </a>
            </li>
        <?php endforeach; ?>
        <li role="type">
            <a href="#type" aria-controls="type" role="tab" data-toggle="tabz">
                Types &nbsp;
                <span class="badge">
                        <?php echo count($types); ?>
                    </span>
            </a>
        </li>
        <li role="theme">
            <a href="#theme" aria-controls="theme" role="tab" data-toggle="tabz">
                Thèmes &nbsp;
                <span class="badge">
                    <?php echo count($themes); ?>
                </span>
            </a>
        </li>
    </ul>

    <div class="main-with-tab">

        <div class="tab-content">
            <?php foreach ($types as $type) : ?>
                <?php
                $libelle = $type->getCompetences();
                $competences = $type->getCompetences();
                ?>
                <div id="<?php echo str_replace("é","e",$type->getLibelle()); ?>" class="tab-pane " role="tabpanel">
                    <div class="row">
                        <div class="col-md-8">
                            <h2>
                                Compétence <span style="color:#2B6FB6;"><?php echo ($type)?$type->getLibelle():"Sans type"; ?></span>
                            </h2>
                        </div>
                        <div class="pull-right">
                            <?php /** @see CompetenceController::ajouterAction() */ ?>
                            <a href="<?php echo $this->url('competence/ajouter', ['competence-type' => ($type)?$type->getId():null], [], true); ?>"
                               class="btn btn-primary action ajax-modal"
                               data-event="modification"
                            >
                                <span class="icon ajouter"></span> Ajouter une compétence</a>
                        </div>
                    </div>

                    <br/>

                    <table id="<?php echo "competence_".$type->getId().""; ?>" class="datatable table table-condensed" data-order='[ 1, "asc" ]'>
                        <thead>
                        <tr>
                            <th style="width:75%;"> Libellé </th>
                            <th> Thème </th>
                            <th style="width:9rem;"> Action </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($competences as $competence) : ?>
                            <tr>
                                <td> <?php echo $competence->getLibelle(); ?> </td>
                                <td> <?php echo ($competence->getTheme())?$competence->getTheme()->getLibelle():"Aucun"; ?> </td>
                                <td>
                                    <?php if ($canVoir): ?>
                                        <?php /** @see CompetenceController::afficherAction() */?>
                                        <a href="<?php echo $this->url('competence/afficher', ['competence' => $competence->getId()], [], true); ?>"
                                           class="ajax-modal">
                                            <span class="icon voir" title="Afficher la compétence "></span></a>
                                    <?php else: ?>
                                        <span class="icon voir" style="color:lightgray;"></span>
                                    <?php endif; ?>
                                    <?php if ($canModifier): ?>
                                        <?php /** @see CompetenceController::modifierAction() */?>
                                        <a href="<?php echo $this->url('competence/modifier', ['competence' => $competence->getId()], [], true); ?>"
                                           class="ajax-modal"
                                           data-event="modification"
                                        >
                                            <span class="icon editer" title="Modifier la compétence"></span></a>
                                    <?php else: ?>
                                        <span class="icon editer" style="color:lightgray;"></span>
                                    <?php endif; ?>
                                    <?php if ($canModifier): ?>
                                        <?php if($competence->estNonHistorise()) : ?>
                                            <?php /** @see CompetenceController::historiserAction() */?>
                                            <a href="<?php echo $this->url('competence/historiser', ['competence' => $competence->getId()], [], true); ?>">
                                                <span class="icon historiser" title="Historiser la compétence"></span></a>
                                        <?php else : ?>
                                            <?php /** @see CompetenceController::restaurerAction() */?>
                                            <a href="<?php echo $this->url('competence/restaurer', ['competence' => $competence->getId()], [], true); ?>">
                                                <span class="icon restaurer" title="Restaurer la compétence"></span></a>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if($competence->estNonHistorise()) : ?>
                                            <span class="icon historiser" style="color:lightgray;"></span>
                                        <?php else : ?>
                                            <span class="icon restaurer" style="color:lightgray;"></span>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($canDetruire): ?>
                                        <?php /** @see CompetenceController::detruireAction() */?>
                                        <a href="<?php echo $this->url('competence/detruire', ['competence' => $competence->getId()], [], true); ?>"
                                           class="ajax-modal" data-event="modification">
                                            <span class="icon detruire" title="Detruire la compétence"></span></a>
                                    <?php else: ?>
                                        <span class="icon detruire" style="color:lightgray;"></span>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endforeach; ?>

            <div id="sans-type" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Compétence <span style="color:#2B6FB6;"> Sans type </span>
                        </h2>
                    </div>
                    <div class="pull-right">
                        <?php /** @see CompetenceController::ajouterAction() */ ?>
                        <a href="<?php echo $this->url('competence/ajouter', ['competence-type' => null], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="modification"
                        >
                            <span class="icon ajouter"></span> Ajouter une compétence</a>
                    </div>
                </div>

                <br/>

                <table class="datatable table table-condensed" data-order='[ 1, "asc" ]'>
                    <thead>
                    <tr>
                    <tr>
                        <th style="width:75%;"> Libellé </th>
                        <th> Thème </th>
                        <th style="width:9rem;"> Action </th>
                    </tr>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($competencesSansType as $competence) : ?>
                        <tr>
                            <td> <?php echo $competence->getLibelle(); ?> </td>
                            <td> <?php echo ($competence->getTheme())?$competence->getTheme()->getLibelle():"Aucun"; ?> </td>
                            <td>
                                <?php if ($canVoir): ?>
                                    <?php /** @see CompetenceController::afficherAction() */?>
                                    <a href="<?php echo $this->url('competence/afficher', ['competence' => $competence->getId()], [], true); ?>"
                                       class="ajax-modal">
                                        <span class="icon voir" title="Afficher la compétence "></span></a>
                                <?php else: ?>
                                    <span class="icon voir" style="color:lightgray;"></span>
                                <?php endif; ?>
                                <?php if ($canModifier): ?>
                                    <?php /** @see CompetenceController::modifierAction() */?>
                                    <a href="<?php echo $this->url('competence/modifier', ['competence' => $competence->getId()], [], true); ?>"
                                       class="ajax-modal"
                                       data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier la compétence"></span></a>
                                <?php else: ?>
                                    <span class="icon editer" style="color:lightgray;"></span>
                                <?php endif; ?>
                                <?php if ($canModifier): ?>
                                    <?php if($competence->estNonHistorise()) : ?>
                                        <?php /** @see CompetenceController::historiserAction() */?>
                                        <a href="<?php echo $this->url('competence/historiser', ['competence' => $competence->getId()], [], true); ?>">
                                            <span class="icon historiser" title="Historiser la compétence"></span></a>
                                    <?php else : ?>
                                        <?php /** @see CompetenceController::restaurerAction() */?>
                                        <a href="<?php echo $this->url('competence/restaurer', ['competence' => $competence->getId()], [], true); ?>">
                                            <span class="icon restaurer" title="Restaurer la compétence"></span></a>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if($competence->estNonHistorise()) : ?>
                                        <span class="icon historiser" style="color:lightgray;"></span>
                                    <?php else : ?>
                                        <span class="icon restaurer" style="color:lightgray;"></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canDetruire): ?>
                                    <?php /** @see CompetenceController::detruireAction() */?>
                                    <a href="<?php echo $this->url('competence/detruire', ['competence' => $competence->getId()], [], true); ?>"
                                       class="ajax-modal" data-event="modification">
                                        <span class="icon detruire" title="Detruire la compétence"></span></a>
                                <?php else: ?>
                                    <span class="icon detruire" style="color:lightgray;"></span>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div id="type" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Types de compétences
                        </h2>
                    </div>
                    <div class="pull-right">
                        <?php /** @see CompetenceController::ajouterCompetenceTypeAction() */ ?>
                        <a href="<?php echo $this->url('competence-type/ajouter', [], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="modification"
                        >
                            <span class="icon ajouter"></span> Ajouter un type de compétence</a>
                    </div>
                </div>

                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th style="width:66%;"> Libellé </th>
                        <!--            <th> Type </th>-->
                        <th> #Compétence </th>
                        <th> Ordre </th>
                        <th style="width:11rem;"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($types as $type) : ?>
                        <tr>
                            <td> <?php echo $type->getLibelle(); ?> </td>
                            <td> <?php echo count($type->getCompetences()); ?> </td>
                            <td> <?php echo $type->getOrdre(); ?> </td>
                            <td>
                                <?php if ($canVoir) : ?>
                                    <?php /** @see CompetenceController::afficherCompetenceTypeAction() */ ?>
                                    <a href="<?php echo $this->url('competence-type/afficher', ['competence-type' => $type->getId()], [], true); ?>"
                                       class="ajax-modal">
                                        <span class="icon voir" title="Afficher le type de compétence [<?php echo $type->getLibelle(); ?>]"></span></a>
                                <?php else : ?>
                                    <span class="icon voir" style="color: lightgrey"></span>
                                <?php endif; ?>
                                <?php if ($canModifier) : ?>
                                    <?php /** @see CompetenceController::modifierCompetenceTypeAction() */ ?>
                                    <a href="<?php echo $this->url('competence-type/modifier', ['competence-type' => $type->getId()], [], true); ?>"
                                       class="ajax-modal" data-event="modification">
                                        <span class="icon editer" title="Modifier le type de compétence [<?php echo $type->getLibelle(); ?>]"></span></a>
                                <?php else : ?>
                                    <span class="icon editer" style="color: lightgrey"></span>
                                <?php endif; ?>
                                <?php if ($canHistoriser): ?>
                                    <?php if($competence->estNonHistorise()) : ?>
                                        <?php /** @see CompetenceController::historiserCompetenceTypeAction() */?>
                                        <a href="<?php echo $this->url('competence-type/historiser', ['competence-type' => $type->getId()], [], true); ?>">
                                            <span class="icon historiser" title="Historiser le type de compétence [<?php echo $type->getLibelle(); ?>]"></span></a>
                                    <?php else : ?>
                                        <?php /** @see CompetenceController::restaurerCompetenceTypeAction() */?>
                                        <a href="<?php echo $this->url('competence-type/restaurer', ['competence-type' => $type->getId()], [], true); ?>">
                                            <span class="icon restaurer" title="Restaurer le type de compétence [<?php echo $type->getLibelle(); ?>]"></span></a>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if($competence->estNonHistorise()) : ?>
                                        <span class="icon historiser" style="color:lightgray;"></span>
                                    <?php else : ?>
                                        <span class="icon restaurer" style="color:lightgray;"></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canDetruire) : ?>
                                    <?php /** @see CompetenceController::detruireCompetenceTypeAction() */ ?>
                                    <a href="<?php echo $this->url('competence-type/detruire', ['competence-type' => $type->getId()], [], true); ?>"
                                       class="ajax-modal" data-event="modification">
                                        <span class="icon detruire" title="Supprimer le type de compétence [<?php echo $type->getLibelle(); ?>]"></span></a>
                                <?php else : ?>
                                    <span class="icon detruire" style="color: lightgrey"></span>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div id="theme" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Thèmes de compétences
                        </h2>
                    </div>
                    <div class="pull-right">
                        <?php /** @see CompetenceController::ajouterCompetenceThemeAction() */ ?>
                        <a href="<?php echo $this->url('competence-theme/ajouter', [], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="modification"
                        >
                            <span class="icon ajouter"></span> Ajouter un thème de compétence</a>
                    </div>
                </div>

                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th style="width:75%;"> Libellé </th>
                        <th> #Compétence </th>
                        <th style="width:11rem;"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($themes as $theme) : ?>
                        <tr>
                            <td> <?php echo $theme->getLibelle(); ?> </td>
                            <td> <?php echo count($theme->getCompetences()); ?> </td>
                            <td>
                                <?php if ($canVoir) : ?>
                                    <?php /** @see CompetenceController::afficherCompetenceThemeAction() */ ?>
                                    <a href="<?php echo $this->url('competence-theme/afficher', ['competence-theme' => $theme->getId()], [], true); ?>"
                                       class="ajax-modal">
                                        <span class="icon voir" title="Afficher le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                                <?php else : ?>
                                    <span class="icon voir" style="color: lightgrey"></span>
                                <?php endif; ?>
                                <?php if ($canModifier) : ?>
                                    <?php /** @see CompetenceController::modifierCompetenceThemeAction() */ ?>
                                    <a href="<?php echo $this->url('competence-theme/modifier', ['competence-theme' => $theme->getId()], [], true); ?>"
                                       class="ajax-modal" data-event="modification">
                                        <span class="icon editer" title="Modifier le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                                <?php else : ?>
                                    <span class="icon editer" style="color: lightgrey"></span>
                                <?php endif; ?>
                                <?php if ($canHistoriser): ?>
                                    <?php if($competence->estNonHistorise()) : ?>
                                        <?php /** @see CompetenceController::historiserCompetenceThemeAction() */?>
                                        <a href="<?php echo $this->url('competence-theme/historiser', ['competence-theme' => $theme->getId()], [], true); ?>">
                                            <span class="icon historiser" title="Historiser le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                                    <?php else : ?>
                                        <?php /** @see CompetenceController::restaurerCompetenceThemeAction() */?>
                                        <a href="<?php echo $this->url('competence-theme/restaurer', ['competence-theme' => $theme->getId()], [], true); ?>">
                                            <span class="icon restaurer" title="Restaurer le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if($competence->estNonHistorise()) : ?>
                                        <span class="icon historiser" style="color:lightgray;"></span>
                                    <?php else : ?>
                                        <span class="icon restaurer" style="color:lightgray;"></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canDetruire) : ?>
                                    <?php /** @see CompetenceController::detruireCompetenceThemeAction() */ ?>
                                    <a href="<?php echo $this->url('competence-theme/detruire', ['competence-theme' => $theme->getId()], [], true); ?>"
                                       class="ajax-modal" data-event="modification">
                                        <span class="icon detruire" title="Supprimer le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                                <?php else : ?>
                                    <span class="icon detruire" style="color: lightgrey"></span>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--$competences = $competencesArray['competences'];-->

<style>
    th.action-cell {
        width:8rem;
    }
    th.modificateur-cell {
        width:12rem;
    }
</style>

<script>
    let loaded = false;
    let search ;
    let page ;
    let id = 'competence_3';

    $(function() {
        <?php foreach ($types as $type) : ?>
            let table_<?php echo $type->getId(); ?> = $('#competence_<?php echo $type->getId(); ?>').DataTable();
        <?php endforeach; ?>

        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "Connaissances";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
