<?php

use Application\Entity\Db\MissionSpecifique;
use Application\Entity\Db\MissionSpecifiqueTheme;
use Application\Entity\Db\MissionSpecifiqueType;

/**
 * @see \Application\Controller\MissionSpecifiqueController::indexAction()
 * @var MissionSpecifique[] $missions
 * @var MissionSpecifiqueType[] $types
 * @var MissionSpecifiqueTheme[] $themes
 */

$canVoir = true;
$canAjouter = true;
$canModifier = true;
$canHistoriser = true;
$canDetruire = true;

$this->headTitle("Missions spécifiques");
?>

<h1 class="page-header">
    Missions spécifiques
</h1>

<div class="main">
    <div role="tabpanel">
        <ul class="nav nav-tabs" role="tablist">

            <li role="mission">
                <a href="#mission" aria-controls="mission" role="tab" data-toggle="tabz">
                    Missions spécifiques &nbsp;
                    <span class="badge">
                    <?php echo count($missions); ?>
                </span>
                </a>
            </li>

            <li role="type">
                <a href="#type" aria-controls="type" role="tab" data-toggle="tabz">
                    Types &nbsp;
                    <span class="badge">
                    <?php echo count($types); ?>
                </span>
                </a>
            </li>

            <li role="theme">
                <a href="#theme" aria-controls="theme" role="tab" data-toggle="tabz" >
                    Thèmes &nbsp;
                    <span class="badge">
                    <?php echo count($themes); ?>
                </span>
                </a>
            </li>
        </ul>

        <div class="main-with-tab">

            <div class="tab-content">

                <!-- Mission------------------------------------------------------------------------------------------->
                <div id="mission" class="tab-pane " role="tabpanel">

                    <?php if ($canAjouter) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::ajouterMissionAction() */?>
                                href="<?php echo $this->url('mission-specifique/mission/ajouter', [], [], true); ?>"
                                class="ajax-modal action btn btn-primary" data-event="modification"
                        >
                            <span class="icon ajouter"></span>
                            Ajouter d'une mission spécifique
                        </a>
                    <?php endif; ?>

                    <table class="table table-condensed">
                        <thead>
                        <tr>
                            <th> Libellé </th>
                            <th> Type </th>
                            <th> Thème </th>
                            <th class="cell-action"> Action </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($missions as $mission) : ?>
                            <tr <?php if ($mission->estHistorise()) echo "class='historise'"; ?>>
                                <td> <?php echo $mission->getLibelle(); ?> </td>
                                <td> <?php echo ($mission->getType())?$mission->getType()->getLibelle():"<span class='probleme'><span class='icon attention'></span>Sans type</span>"; ?> </td>
                                <td> <?php echo ($mission->getTheme())?$mission->getTheme()->getLibelle():"<span class='probleme'><span class='icon attention'></span>Sans thème</span>"; ?> </td>
                                <td>
                                    <?php if ($canVoir) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\MissionSpecifiqueController::afficherMissionAction() */?>
                                                href="<?php echo $this->url('mission-specifique/mission/afficher', ['mission' => $mission->getId()], [], true); ?>"
                                                class="ajax-modal">
                                            <span class="icon voir"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Afficher la mission spécifique"></span></a>
                                    <?php endif; ?>

                                    <?php if ($canModifier) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\MissionSpecifiqueController::modifierMissionAction() */?>
                                                href="<?php echo $this->url('mission-specifique/mission/modifier', ['mission' => $mission->getId()], [], true); ?>"
                                                class="ajax-modal" data-event="modification">
                                            <span class="icon editer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Modifier la mission spécifique"></span></a>
                                    <?php endif; ?>

                                    <?php if ($canHistoriser) : ?>
                                        <?php if ($mission->estNonHistorise()) : ?>
                                            <a
                                                <?php /** @see \Application\Controller\MissionSpecifiqueController::historiserMissionAction() */?>
                                                    href="<?php echo $this->url('mission-specifique/mission/historiser', ['mission' => $mission->getId()], [], true); ?>"
                                            >
                                            <span class="icon historiser"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Historiser la mission spécifique"></span></a>
                                        <?php else: ?>
                                            <a
                                                <?php /** @see \Application\Controller\MissionSpecifiqueController::restaurerMissionAction() */?>
                                                    href="<?php echo $this->url('mission-specifique/mission/restaurer', ['mission' => $mission->getId()], [], true); ?>"
                                            >
                                            <span class="icon restaurer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Restaurer la mission spécifique"></span></a>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($canDetruire) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\MissionSpecifiqueController::detruireMissionAction() */?>
                                                href="<?php echo $this->url('mission-specifique/mission/detruire', ['mission' => $mission->getId()], [], true); ?>"
                                                class="ajax-modal" data-event="modification">
                                            <span class="icon detruire"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Supprimer la mission spécifique"></span></a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

                <!-- Type---------------------------------------------------------------------------------------------->
                <div id="type" class="tab-pane " role="tabpanel">

                    <?php if ($canAjouter) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::ajouterTypeAction() */?>
                                href="<?php echo $this->url('mission-specifique/type/ajouter', [], [], true); ?>"
                            class="ajax-modal action btn btn-primary" data-event="modification"
                           >
                            <span class="icon ajouter"></span>
                            Ajouter un type de mission
                        </a>
                    <?php endif; ?>

                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th> Libellé </th>
                                <th> #Mission </th>
                                <th class="cell-action"> Action </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($types as $type) : ?>
                                <tr <?php if ($type->estHistorise()) echo "class='historise'"; ?>>
                                    <td> <?php echo $type->getLibelle(); ?> </td>
                                    <td> <?php echo count($type->getMissions()); ?> </td>
                                    <td>
                                        <?php if ($canVoir) : ?>
                                            <a
                                                <?php /** @see \Application\Controller\MissionSpecifiqueController::afficherTypeAction() */?>
                                                href="<?php echo $this->url('mission-specifique/type/afficher', ['type' => $type->getId()], [], true); ?>"
                                                class="ajax-modal">
                                            <span class="icon voir"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Afficher le type de mission spécifique"></span></a>
                                        <?php endif; ?>

                                        <?php if ($canModifier) : ?>
                                            <a
                                                <?php /** @see \Application\Controller\MissionSpecifiqueController::modifierTypeAction() */?>
                                                    href="<?php echo $this->url('mission-specifique/type/modifier', ['type' => $type->getId()], [], true); ?>"
                                                    class="ajax-modal" data-event="modification">
                                            <span class="icon editer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Modifier le type de mission spécifique"></span></a>
                                        <?php endif; ?>

                                        <?php if ($canHistoriser) : ?>
                                            <?php if ($type->estNonHistorise()) : ?>
                                                <a
                                                    <?php /** @see \Application\Controller\MissionSpecifiqueController::historiserTypeAction() */?>
                                                        href="<?php echo $this->url('mission-specifique/type/historiser', ['type' => $type->getId()], [], true); ?>"
                                                        >
                                            <span class="icon historiser"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Historiser le type de mission spécifique"></span></a>
                                            <?php else: ?>
                                                <a
                                                    <?php /** @see \Application\Controller\MissionSpecifiqueController::restaurerTypeAction() */?>
                                                        href="<?php echo $this->url('mission-specifique/type/restaurer', ['type' => $type->getId()], [], true); ?>"
                                                >
                                            <span class="icon restaurer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Restaurer le type de mission spécifique"></span></a>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if ($canDetruire) : ?>
                                            <a
                                                <?php /** @see \Application\Controller\MissionSpecifiqueController::detruireTypeAction() */?>
                                                    href="<?php echo $this->url('mission-specifique/type/detruire', ['type' => $type->getId()], [], true); ?>"
                                                    class="ajax-modal" data-event="modification">
                                            <span class="icon detruire"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Supprimer le type de mission spécifique"></span></a>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

                <!-- Theme--------------------------------------------------------------------------------------------->
                <div id="theme" class="tab-pane " role="tabpanel">
                    <?php if ($canAjouter) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::ajouterThemeAction() */?>
                                href="<?php echo $this->url('mission-specifique/theme/ajouter', [], [], true); ?>"
                                class="ajax-modal action btn btn-primary" data-event="modification"
                        >
                            <span class="icon ajouter"></span>
                            Ajouter un thème de mission
                        </a>
                    <?php endif; ?>

                    <table class="table table-condensed">
                        <thead>
                        <tr>
                            <th> Libellé </th>
                            <th> #Mission </th>
                            <th class="cell-action"> Action </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($themes as $theme) : ?>
                            <tr <?php if ($theme->estHistorise()) echo "class='historise'"; ?>>
                                <td> <?php echo $theme->getLibelle(); ?> </td>
                                <td> <?php echo count($theme->getMissions()); ?> </td>
                                <td>
                                    <?php if ($canVoir) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\MissionSpecifiqueController::afficherThemeAction() */?>
                                                href="<?php echo $this->url('mission-specifique/theme/afficher', ['theme' => $theme->getId()], [], true); ?>"
                                                class="ajax-modal">
                                            <span class="icon voir"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Afficher le thème de mission spécifique"></span></a>
                                    <?php endif; ?>

                                    <?php if ($canModifier) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\MissionSpecifiqueController::modifierThemeAction() */?>
                                                href="<?php echo $this->url('mission-specifique/theme/modifier', ['theme' => $theme->getId()], [], true); ?>"
                                                class="ajax-modal" data-event="modification">
                                            <span class="icon editer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Modifier le thème de mission spécifique"></span></a>
                                    <?php endif; ?>

                                    <?php if ($canHistoriser) : ?>
                                        <?php if ($type->estNonHistorise()) : ?>
                                            <a
                                                <?php /** @see \Application\Controller\MissionSpecifiqueController::historiserThemeAction() */?>
                                                    href="<?php echo $this->url('mission-specifique/theme/historiser', ['theme' => $theme->getId()], [], true); ?>"
                                            >
                                            <span class="icon historiser"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Historiser le thème de mission spécifique"></span></a>
                                        <?php else: ?>
                                            <a
                                                <?php /** @see \Application\Controller\MissionSpecifiqueController::restaurerThemeAction() */?>
                                                    href="<?php echo $this->url('mission-specifique/theme/restaurer', ['theme' => $theme->getId()], [], true); ?>"
                                            >
                                            <span class="icon restaurer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Restaurer le thème de mission spécifique"></span></a>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($canDetruire) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\MissionSpecifiqueController::detruireThemeAction() */?>
                                                href="<?php echo $this->url('mission-specifique/theme/detruire', ['theme' => $theme->getId()], [], true); ?>"
                                                class="ajax-modal" data-event="modification">
                                            <span class="icon detruire"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Supprimer le thème de mission spécifique"></span></a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });
    });

    $(document).ready(function() {
        $('.datatable').DataTable( {
            sorting:false,
            paging:false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "metier";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>