<?php

use Metier\Entity\Db\MetierNiveau;

/**
 * @see \Metier\View\Helper\MetierNiveauViewHelper
 * @var MetierNiveau|null $metierniveau
 * @var array $options
 */

?>

<?php if ($metierniveau === null) : ?>
    Non&nbsp;précisé
<?php else: ?>
    [<?php echo $metierniveau->getBorneInferieure()->getEtiquette(); ?>:<?php echo $metierniveau->getBorneSuperieure()->getEtiquette(); ?>]<br/>
    Recommandé&nbsp;<?php echo $metierniveau->getValeurRecommandee()->getEtiquette(); ?>
<?php endif; ?>


