<?php

/**
 * @var string $source
 * @var string $historise
 * @var array $groupes [id => libelle ]
 * @var string $groupe
 * @var PlanDeFormation[] $plansDeFormation
 * @var ?PlanDeFormation $planDeFormation
 */

use Application\Entity\Db\Interfaces\HasSourceInterface;
use Formation\Entity\Db\PlanDeFormation;

?>

<div class="card default">
    <div class="card-header">
        <span class="icon icon-filtrer"></span>
        Filtrage des actions de formation
    </div>
    <div class="card-body">
        <form id="filtre" action="<?php echo $this->url(); ?>" method="get">
            <div class="row">
                <div class="col-md-3">
                    <label for="groupe">Thème de formation : </label>
                    <select id="groupe" name="groupe" class="selectpicker" data-live-search="true">
                        <option value=""> Tous les thèmes </option>
                        <?php foreach ($groupes as $id => $libelle) : ?>
                        <option value="<?php echo $id; ?>"> <?php echo $libelle['label']; ?> </option>
                        <?php endforeach; ?>
                    </select>
                </div>
<!--                <div class="col-md-3">-->
<!--                    <label for="source">Source : </label>-->
<!--                    <select id="source" name="source" class="selectpicker">-->
<!--                        <option value=""> Toutes les sources </option>-->
<!--                        <option value="--><?php //echo HasSourceInterface::SOURCE_EMC2; ?><!--"> --><?php //echo HasSourceInterface::SOURCE_EMC2; ?><!-- </option>-->
<!--                        <option value="--><?php //echo HasSourceInterface::SOURCE_LAGAF; ?><!--"> --><?php //echo HasSourceInterface::SOURCE_LAGAF; ?><!-- </option>-->
<!--                    </select>-->
<!--                </div>-->
                <div class="col-md-3">
                    <label for="source">Plan de formation : </label>
                    <select id="planDeFormation" name="planDeFormation" class="selectpicker" data-live-search="true">
                        <option value=""> Peu importe le plan de formation </option>
                        <?php foreach ($plansDeFormation as $planDeFormation_) : ?>
                            <option value="<?php echo $planDeFormation_->getId(); ?>" <?php if (isset($planDeFormation) && $planDeFormation_ === $planDeFormation) echo 'selected="selected"'; ?>
                                    data-content="<strong><?php echo $planDeFormation_->getLibelle(); ?> </strong> (<?php echo $planDeFormation_->getDateDebut()->format('d/m/Y'); ?> - <?php echo $planDeFormation_->getDateFin()->format('d/m/Y'); ?>)"
                            >
                                <?php echo $planDeFormation_->getLibelle(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="historise">Historisé : </label>
                    <select id="historise" name="historise" class="selectpicker">
                        <option value=""> Peu importe </option>
                        <option value="1"> Historisé </option>
                        <option value="0"> Non historisé </option>
                    </select>
                </div>
                <!-- BOUTON -->
                <div class="col-md-3">
                    <div class="pull-right">
                        <button class="btn btn-primary action" id="clear">
                            <span class="icon icon-gommer"></span> Remise à zéro
                        </button>

                        <button class="btn btn-primary action" id="filter">
                            <span class="icon icon-filtrer"></span>
                            Filtrer
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    //let source = <?php //echo '"' . $source . '"'; ?>//;
    let planDeFormation <?php echo '"' . ($planDeFormation)?->getId() . '"'; ?>;
    let historise = <?php echo '"' . $historise . '"'; ?>;
    let groupe = <?php echo '"' . (int) $groupe . '"'; ?>;
    // console.log("source=" + source);
    // console.log("plan de formation =" + planDeFormation);
    // console.log("historise=" + historise);
    // console.log("groupe=" + groupe);

    $("form#filtre").submit(function(e){
        e.preventDefault();
    });

    $('button#clear').click(function() {
        window.location.href = '?';
    });

    $('button#filter').click(function() {
        // let sourceId = $('select#source option:selected').val();
        // console.log( "source=" + sourceId);
        let planId = $('select#planDeFormation option:selected').val();
        console.log( "planDeFormation=" + planId);
        let historiseId = $('select#historise option:selected').val();
        console.log( "historise=" + historiseId);
        let groupeId = $('select#groupe option:selected').val();
        console.log( "groupe=" + groupeId);

        let query = "";
        query += "&planDeFormation=" + planId;
        query += "&historise=" + historiseId;
        query += "&groupe=" + groupeId;
        window.location.href = 'formation?'+ query ;
    });

    $('select#source option[value=' + source + ']').prop('selected', true);
    $('select#historise option[value=' + historise + ']').prop('selected', true);
    $('select#groupe option[value=' + groupe + ']').prop('selected', true);

</script>