<?php

/**
 * @var Formation[] $formations
 * @var boolean[] $droits
 */

use Formation\Entity\Db\Formation;

$canAfficher = $droits['afficher'];
$canAjouter = $droits['ajouter'];
$canAjouterInstance = $droits['ajouter'];
$canHistoriser = $droits['historiser'];
$canDetruire = $droits['detruire'];

?>

<div class="row">
    <div class="col-md-8">
        <h2>
            Actions de formation
        </h2>
    </div>
    <div class="col-md-4">
        <?php if ($canAjouter) : ?>
            <br/>


            <a
                <?php /** @see FormationController::ajouterAction() */ ?>
                href="<?php echo $this->url('formation/ajouter', [], [], true); ?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification">
                <span class="icon ajouter"></span>
                Ajouter une action
            </a>
        <?php endif; ?>
    </div>
</div>

<br/>

<table class="datatable" id="formations" style="width:100%;">
    <thead>
        <tr>
            <th class="col-md-6 nosort"> Libellé </th>
            <th class="col-md-3 nosort"> Groupe </th>
            <th class="col-md-2 nosort"> Source </th>
            <th class="col-md-1 nosort"> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($formations as $formation) : ?>
        <tr>
            <td> <?php echo $formation->getLibelle(); ?> </td>
            <td> <?php echo ($formation->getGroupe())?$formation->getGroupe()->getLibelle():"Sans groupe ..."; ?> </td>
            <td>
                <span class="badge source <?php echo $formation->getSource(); ?>">
                    <?php echo $formation->getSource(); ?>  <?php echo ($formation->getIdSource())?:$formation->getId(); ?>
                </span>
            </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see FormationController::editerAction() */ ?>
                        href="<?php echo $this->url('formation/editer', ['formation' => $formation->getId()], [], true); ?>"
                    >
                        <span class="icon voir" title="Afficher la formation"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($formation->estNonHistorise()) : ?>
                        <a
                            <?php /** @see FormationController::historiserAction() */ ?>
                            href="<?php echo $this->url('formation/historiser', ['formation' => $formation->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser la formation"></span></a>
                    <?php else : ?>
                        <a
                            <?php /** @see FormationController::restaurerAction() */ ?>
                            href="<?php echo $this->url('formation/restaurer', ['formation' => $formation->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer la formation"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <a
                        <?php /** @see FormationController::detruireAction() */ ?>
                        href="<?php echo $this->url('formation/detruire', ['formation' => $formation->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer la formation"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        let table = $('#formations').DataTable({
            "pageLength": 25,
            "sorting": false,
            "columnDefs": [
                {"targets": ['nosort'], "orderable": false},
            ],
            "language": {
                "search": "Filtre : _INPUT_",
                'infoFiltered': "<small class=\"text-highlight\">(_MAX_ &eacute;l&eacute;ments au total)</small>",
                'emptyTable': "Aucune donnée disponible",
                'zeroRecords': "Aucun enregistrement trouvé",
            },
        } );
    } );
</script>

