<?php
    use Formation\Entity\Db\FormationInstance;
?>

<dl>
    <dt> Qui</dt>
    <dd>
        Tous les rôles ayant le privilèges <span class="privilege"><span class="icon clef"></span>FormationInstance_Gerer_Inscription</span>.<br/>
        Par exemple :
        <ul>
            <li> Administrateur Technique/Fonctionnelle</li>
            <li> Gestionnaire de formation</li>
        </ul>
    </dd>
    <dt> Où</dt>
    <dd>
        Dans l'affichage d'une action de formation<br/>
    </dd>
    <dt> Comment</dt>
    <dd>
        Accès en cliquant sur le bouton :
        <button class="label btn-primary"><span class="icon inscription-ouverture"></span> Ouvrir les inscriptions
        </button>
    </dd>
    <dt> Que se passe t'il</dt>
    <dd>
        <ol>
            <li> Formation instance reçoit
                état <?php echo $this->etatbadge(FormationInstance::ETAT_INSCRIPTION_OUVERTE); ?> </li>
            <li> Notification des agents de l'ouverture de l'instance de formation grâce au mail <span
                    class="mail"><span class="icon courrier"></span>FORMATION_INSCRIPTION_OUVERTE</span></li>
        </ol>
    </dd>
</dl>