<?php

/**
 * @see \UnicaenValidation\View\Helper\ValidationBadgeViewHelper
 * @var ValidationInstance $validation
 * @var array $options
 */

use UnicaenValidation\Entity\Db\ValidationInstance;

$texte = (isset($options['texte']) AND $options['texte'] === true);
?>

<?php if ($validation !== null) : ?>
    <?php if ($validation->getValeur() === null) : ?>
        <span class="icon icon-checked" style="color: darkgreen;"
              data-bs-toggle="tooltip" data-bs-html="true"
              title="Validé le <span class='highlight date'> <?php echo $validation->getHistoCreation()->format('d/m/Y'); ?> </span> par <span class='highlight agent'> <?php echo $validation->getHistoCreateur()->getDisplayName(); ?>">
            <?php echo ($texte)?"Validée":""; ?>
        </span>
    <?php else : ?>
        <span class="icon icon-retirer" style="color: darkred;"
              data-bs-toggle="tooltip" data-bs-html="true"
              title="Validé le <span class='highlight date'> <?php echo $validation->getHistoCreation()->format('d/m/Y'); ?> </span> par <span class='highlight agent'> <?php echo $validation->getHistoCreateur()->getDisplayName(); ?>">
            <?php echo ($texte)?"Refusée":""; ?>
        </span>
    <?php endif; ?>
<?php else : ?>
    <span style="color:#123456;"><span class="icon aucune"></span> &nbsp;<?php echo ($texte)?"Aucune":""; ?></span>
<?php endif; ?>
