<?php

/**
 * @var \UnicaenValidation\Entity\Db\ValidationInstance $instance
 * @var array $options
 */

$type = $instance->getType();

?>

<div class="validation validation-affichage <?php echo ($instance->getValeur() === null)?"validation-valider":"validation-refuser" ?>">
        <?php if ($instance->getValeur() !== null) : ?>
            Refusé
        <?php else : ?>
            Validé
        <?php endif; ?>
        le  <?php echo $instance->getHistoModification()->format('d/m/Y à H:i:s'); ?>
        par <?php echo $instance->getHistoModificateur()->getDisplayName(); ?>.
</div>
