<?php

/**
 * @var MissionSpecifiqueTheme[] $themes
 * @var array $droits
 */

use Application\Entity\Db\MissionSpecifiqueTheme;

?>

<?php if ($droits["ajouter"] === true) : ?>
    <a
        <?php /** @see \Application\Controller\MissionSpecifiqueController::ajouterThemeAction() */?>
        href="<?php echo $this->url('mission-specifique/theme/ajouter', [], [], true); ?>"
        class="ajax-modal action btn btn-primary" data-event="modification"
    >
        <span class="icon ajouter"></span>
        Ajouter un thème de mission
    </a>
<?php endif; ?>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> #Mission </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($themes as $theme) : ?>
        <tr <?php if ($theme->estHistorise()) echo "class='historise'"; ?>>
            <td> <?php echo $theme->getLibelle(); ?> </td>
            <td> <?php echo count($theme->getMissions()); ?> </td>
            <td>
                <?php if ($droits["voir"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::afficherThemeAction() */?>
                        href="<?php echo $this->url('mission-specifique/theme/afficher', ['theme' => $theme->getId()], [], true); ?>"
                        class="ajax-modal">
                                            <span class="icon voir"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Afficher le thème de mission spécifique"></span></a>
                <?php endif; ?>

                <?php if ($droits["modifier"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::modifierThemeAction() */?>
                        href="<?php echo $this->url('mission-specifique/theme/modifier', ['theme' => $theme->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                                            <span class="icon editer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Modifier le thème de mission spécifique"></span></a>
                <?php endif; ?>

                <?php if ($droits["historiser"] === true) : ?>
                    <?php if ($theme->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::historiserThemeAction() */?>
                            href="<?php echo $this->url('mission-specifique/theme/historiser', ['theme' => $theme->getId()], [], true); ?>"
                        >
                                            <span class="icon historiser"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Historiser le thème de mission spécifique"></span></a>
                    <?php else: ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::restaurerThemeAction() */?>
                            href="<?php echo $this->url('mission-specifique/theme/restaurer', ['theme' => $theme->getId()], [], true); ?>"
                        >
                                            <span class="icon restaurer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Restaurer le thème de mission spécifique"></span></a>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($droits["supprimer"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::detruireThemeAction() */?>
                        href="<?php echo $this->url('mission-specifique/theme/detruire', ['theme' => $theme->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                                            <span class="icon detruire"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Supprimer le thème de mission spécifique"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>