<?php

/**
 * @var MissionSpecifique[] $missions
 * @var MissionSpecifiqueTheme[] $themes
 * @var MissionSpecifiqueType[] $types
 * @var array $params
 * @var array $droits
 */

use Application\Entity\Db\MissionSpecifique;
use Application\Entity\Db\MissionSpecifiqueTheme;
use Application\Entity\Db\MissionSpecifiqueType;

?>

<br/>

<div class="row">
    <div class="col-md-8">
        <h2>Liste des missions spécifiques </h2>
    </div>
    <div class="col-md-4">
        <?php if ($droits["ajouter"] === true) : ?>
            <br/>
            <a
                <?php /** @see \Application\Controller\MissionSpecifiqueController::ajouterMissionAction() */?>
                    href="<?php echo $this->url('mission-specifique/mission/ajouter', [], [], true); ?>"
                    class="ajax-modal action btn btn-primary" data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter une mission spécifique
            </a>
        <?php endif; ?>
    </div>
</div>


<?php echo $this->partial('partial/filtre', ['types' => $types, 'themes' => $themes, 'params' => $params]); ?>

<table class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th style="width: 50%;"> Libellé </th>
        <th style="width: 20%;"> Type </th>
        <th style="width: 20%;"> Thème </th>
        <th style="width: 10%;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($missions as $mission) : ?>
        <tr <?php if ($mission->estHistorise()) echo "class='historise'"; ?>>
            <td> <?php echo $mission->getLibelle(); ?> </td>
            <td> <?php echo ($mission->getType())?$mission->getType()->getLibelle():"<span class='probleme'><span class='icon attention'></span>Sans type</span>"; ?> </td>
            <td> <?php echo ($mission->getTheme())?$mission->getTheme()->getLibelle():"<span class='probleme'><span class='icon attention'></span>Sans thème</span>"; ?> </td>
            <td>
                <?php if ($droits["voir"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::afficherMissionAction() */?>
                        href="<?php echo $this->url('mission-specifique/mission/afficher', ['mission' => $mission->getId()], [], true); ?>"
                        class="ajax-modal">
                                            <span class="icon voir"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Afficher la mission spécifique"></span></a>
                <?php endif; ?>

                <?php if ($droits["modifier"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::modifierMissionAction() */?>
                        href="<?php echo $this->url('mission-specifique/mission/modifier', ['mission' => $mission->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                                            <span class="icon editer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Modifier la mission spécifique"></span></a>
                <?php endif; ?>

                <?php if ($droits["historiser"] === true) : ?>
                    <?php if ($mission->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::historiserMissionAction() */?>
                            href="<?php echo $this->url('mission-specifique/mission/historiser', ['mission' => $mission->getId()], [], true); ?>"
                        >
                                            <span class="icon historiser"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Historiser la mission spécifique"></span></a>
                    <?php else: ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::restaurerMissionAction() */?>
                            href="<?php echo $this->url('mission-specifique/mission/restaurer', ['mission' => $mission->getId()], [], true); ?>"
                        >
                                            <span class="icon restaurer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Restaurer la mission spécifique"></span></a>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($droits["detruire"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::detruireMissionAction() */?>
                        href="<?php echo $this->url('mission-specifique/mission/detruire', ['mission' => $mission->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                                            <span class="icon detruire"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Supprimer la mission spécifique"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>