<?php

/**
 * @var MissionSpecifiqueType[] $types
 * @var array $droits
 */

use Application\Entity\Db\MissionSpecifiqueType;

?>

<?php if ($droits["ajouter"] === true) : ?>
    <a
        <?php /** @see \Application\Controller\MissionSpecifiqueController::ajouterTypeAction() */?>
        href="<?php echo $this->url('mission-specifique/type/ajouter', [], [], true); ?>"
        class="ajax-modal action btn btn-primary" data-event="modification"
    >
        <span class="icon ajouter"></span>
        Ajouter un type de mission
    </a>
<?php endif; ?>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> #Mission </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($types as $type) : ?>
        <tr <?php if ($type->estHistorise()) echo "class='historise'"; ?>>
            <td> <?php echo $type->getLibelle(); ?> </td>
            <td> <?php echo count($type->getMissions()); ?> </td>
            <td>
                <?php if ($droits["voir"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::afficherTypeAction() */?>
                        href="<?php echo $this->url('mission-specifique/type/afficher', ['type' => $type->getId()], [], true); ?>"
                        class="ajax-modal">
                                            <span class="icon voir"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Afficher le type de mission spécifique"></span></a>
                <?php endif; ?>

                <?php if ($droits["modifier"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::modifierTypeAction() */?>
                        href="<?php echo $this->url('mission-specifique/type/modifier', ['type' => $type->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                                            <span class="icon editer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Modifier le type de mission spécifique"></span></a>
                <?php endif; ?>

                <?php if ($droits["historiser"] === true) : ?>
                    <?php if ($type->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::historiserTypeAction() */?>
                            href="<?php echo $this->url('mission-specifique/type/historiser', ['type' => $type->getId()], [], true); ?>"
                        >
                                            <span class="icon historiser"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Historiser le type de mission spécifique"></span></a>
                    <?php else: ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueController::restaurerTypeAction() */?>
                            href="<?php echo $this->url('mission-specifique/type/restaurer', ['type' => $type->getId()], [], true); ?>"
                        >
                                            <span class="icon restaurer"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Restaurer le type de mission spécifique"></span></a>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($droits["detruire"] === true) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueController::detruireTypeAction() */?>
                        href="<?php echo $this->url('mission-specifique/type/detruire', ['type' => $type->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                                            <span class="icon detruire"
                                                  data-toggle="tooltip" data-html="true"
                                                  title="Supprimer le type de mission spécifique"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>