<?php

/**
 * @see \Formation\Controller\IndexController::indexGestionnaireAction()
 * @var User $user
 * @var Role $role
 * @var EtatType[]  $etatsTypesSession
 * @var EtatType[]  $etatsTypesDemande
 * @var Session[][]  $dictionnaireSession
 * @var Session[]  $sessionsSansGestionnaire
 *
 *
 * @var DemandeExterne[]  $dictionnaireDemande
 * @var DemandeExterne[]  $demandesSansGestionnaire
 */

use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\Session;
use UnicaenEtat\Entity\Db\EtatType;
use UnicaenUtilisateur\Entity\Db\Role;
use UnicaenUtilisateur\Entity\Db\User;

$this->headTitle("Index de gestion de vos sessions de formation ");

$sessionsEnGestion = 0;
foreach ($dictionnaireSession as $etatCode => $sessions) {
    $sessionsEnGestion += count($sessions);
}
$demandesEnGestion = 0;
foreach ($dictionnaireDemande as $etatCode => $demandes) {
    $demandesEnGestion += count($demandes);
}

?>

<h1 class="page-header">
    Index de gestion de vos sessions de formation
</h1>


<h2> Sessions dont vous êtes gestionnaire
    <span class="badge"><?php echo $sessionsEnGestion; ?></span>
</h2>

<?php foreach ($dictionnaireSession as $etatCode => $sessions) : ?>
    <?php if (!empty($sessions)) : ?>
    <div class="card">
        <div class="card-header bg-default">
            <?php echo $this->etattype($etatsTypesSession[$etatCode]); ?>
            <?php echo count($sessions); ?> session·s à l'états [<?php echo $etatsTypesSession[$etatCode]->getLibelle(); ?>]
        </div>
        <?php if (count($sessions) > 0) : ?>
        <div class="card-body">
            <?php echo $this->formationInstanceArray($sessions, ['affichage' => ['gestionnaires' => false]]); ?>
        </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>
<?php endforeach; ?>

<h2>
    Sessions sans gestionnaire
    <span class="badge"><?php echo count($sessionsSansGestionnaire); ?></span>
</h2>

<div class="card-body">
    <?php echo $this->formationInstanceArray($sessionsSansGestionnaire, ['affichage' => ['gestionnaires' => false]]); ?>
</div>

<h2>
    Demandes hors plan de formations en attente de gestions
    <span class="badge"><?php echo $demandesEnGestion ?></span>
</h2>


<?php foreach ($dictionnaireDemande as $etatCode => $demandes) : ?>
    <?php if (!empty($demandes)) : ?>
    <div class="card">
        <div class="card-header bg-default">
            <?php echo $this->etattype($etatsTypesDemande[$etatCode]); ?>
            <?php echo count($demandes); ?> demande·s externe·s à l'états [<?php echo $etatsTypesDemande[$etatCode]->getLibelle(); ?>]
        </div>
        <?php if (count($demandes) > 0) : ?>
            <div class="card-body">
                <?php echo $this->demandeExterneArray($demandes, ['affichage' => ['gestionnaires' => false]]); ?>
            </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>
<?php endforeach; ?>

<h2>
    Demandes sans gestionnaire
    <span class="badge"><?php echo count($demandesSansGestionnaire); ?></span>
</h2>

<div class="card-body">
    <?php echo $this->demandeExterneArray($demandesSansGestionnaire, ['affichage' => ['gestionnaires' => false]]); ?>
</div>
