<?php

use Metier\Entity\Db\Domaine;
use Metier\Entity\Db\FamilleProfessionnelle;
use Metier\Entity\Db\Metier;

/**
 * @see \Metier\Controller\DomaineController::afficherAction()
 * @var Domaine $domaine
 */

?>

<dl class="row">
    <dt class="col-md-4"> Domaine </dt>
    <dd class="col-md-8"> <?php echo $domaine->getLibelle(); ?> </dd>
    <dt class="col-md-4"> Type </dt>
    <dd class="col-md-8"> <?php echo $domaine->getTypeFonction(); ?> </dd>
    <dt class="col-md-4"> Famille·s professionnelle·s </dt>
    <dd class="col-md-8">
        <?php
            $familles = $domaine->getFamilles();
            usort($familles, function (FamilleProfessionnelle $a, FamilleProfessionnelle $b) { return $a->getLibelle() <=> $b->getLibelle(); });
        ?>
        <?php if (empty($familles)) : ?>
            <em> Aucune famille professionnelle attachée à ce domaine </em>
        <?php else : ?>
            <ul>
                <?php foreach ($familles as $famille) : ?>
                    <li> <?php echo $famille->getLibelle(); ?> </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </dd>
    <dt class="col-md-4"> Métier·s </dt>
    <dd class="col-md-8">
        <?php
            $metiers = $domaine->getMetiers();
            usort($metiers, function (Metier $a, Metier $b) { return $a->getLibelle() <=> $b->getLibelle(); });
        ?>
        <?php if (empty($metiers)) : ?>
            <em> Aucun métier attaché à ce domaine </em>
        <?php else : ?>
            <ul>
                <?php foreach ($metiers as $metier) : ?>
                    <li> <?php echo $metier->getLibelle(); ?> </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </dd>
</dl>
