<?php

/**
 * @see \Metier\Controller\DomaineController::indexAction()
 * @var Domaine[] $domaines
 *
 * @var FamilleProfessionnelle[] $familles
 * @var string[] $types
 *
 * @var string $famille
 * @var string $type
 * @var string $historise
 */

use Metier\Entity\Db\Domaine;
use Metier\Entity\Db\FamilleProfessionnelle;
use Metier\Provider\Privilege\DomainePrivileges;

$canAafficher      = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_AFFICHER));
$canAjouter        = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_AJOUTER));
$canEditer         = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_MODIFIER));;
$canHistoriser     = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_HISTORISER));
$canEffacer        = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_SUPPRIMER));

$this->headTitle('Liste des domaines')
?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Liste des domaines
        </h1>
    </div>
    <div class="pull-right">
        <?php if ($canAjouter) : ?>
            <a
                <?php /** @see \Metier\Controller\DomaineController::ajouterAction() */ ?>
                href="<?php echo $this->url('domaine/ajouter', [], [], true);?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un domaine
            </a>
        <?php endif;?>
    </div>
</div>

<?php echo $this->partial('partial/filtre', ['familles' => $familles, 'types' => $types, 'famille' => $famille, 'type' => $type, 'historise' => $historise]); ?>

<table id="domaines" class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th> Libelle </th>
        <th> Type </th>
        <th> Famille professionnelle </th>
        <th> #metier </th>
        <th style="min-width: 10rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($domaines as $domaine): ?>
        <tr <?php if ($domaine->estHistorise()) echo ' class="historise" '; ?>>
            <td> <?php echo $domaine->getLibelle(); ?> </td>
            <td>
                <?php echo $this->typefonction($domaine); ?>
            </td>
            <td> <?php echo $domaine->getFamille(); ?> </td>
            <td>
                <?php echo count($domaine->getMetiers()); ?>
            </td>
            <td>
                <?php if ($canEditer) : ?>
                    <a  <?php /** @see \Metier\Controller\DomaineController::modifierAction() */ ?>
                        href="<?php echo $this->url('domaine/modifier', ['domaine' => $domaine->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon editer" title="Modifier le domaine"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($domaine->estNonHistorise()) : ?>
                        <a  <?php /** @see \Application\Controller\DomaineController::historiserAction() */ ?>
                            href="<?php echo $this->url('domaine/historiser', ['domaine' => $domaine->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser le domaine"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \Application\Controller\DomaineController::restaurerAction() */ ?>
                            href="<?php echo $this->url('domaine/restaurer', ['domaine' => $domaine->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer le domaine"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <a  <?php /** @see \Application\Controller\DomaineController::effacerAction() */ ?>
                        href="<?php echo $this->url('domaine/effacer', ['domaine' => $domaine->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire"  title="Supprimer le domaine"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('#domaines').DataTable( {
            sorting: false,
            paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );
</script>