<?php

/**
 * @see \Metier\Controller\DomaineController::indexAction()
 * @var Domaine[] $domaines
 * @var string[] $types
 * @var string $type
 * @var string $historise
 */

use Metier\Entity\Db\Domaine;
use Metier\Entity\Db\FamilleProfessionnelle;
use Metier\Provider\Privilege\DomainePrivileges;

$canAfficher       = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_AFFICHER));
$canAjouter        = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_AJOUTER));
$canEditer         = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_MODIFIER));
$canHistoriser     = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_HISTORISER));
$canEffacer        = $this->isAllowed(DomainePrivileges::getResourceId(DomainePrivileges::DOMAINE_SUPPRIMER));

$canAction = ($canAfficher OR $canAjouter or $canEditer or $canHistoriser or $canEffacer);

$this->headTitle('Liste des domaines')
?>

<h1 class="page-header">
    Liste des domaines
</h1>

<?php echo $this->partial('partial/filtre', ['types' => $types, 'type' => $type, 'historise' => $historise]); ?>

<?php if ($canAjouter) : ?>
    <a
        <?php /** @see \Metier\Controller\DomaineController::ajouterAction() */ ?>
            href="<?php echo $this->url('domaine/ajouter', [], [], true);?>"
            class="btn btn-primary ajax-modal"
            data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un domaine
    </a>
<?php endif;?>

<table id="domaines" class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th  class="col-md-3"> Libelle </th>
        <th  class="col-md-2"> Type </th>
        <th  class="col-md-2"> #metier </th>
        <?php if ($canAction) : ?>
            <th class="col-md-"> Action </th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach($domaines as $domaine): ?>
        <tr <?php if ($domaine->estHistorise()) echo ' class="historise" '; ?>>
            <td> <?php echo $domaine->getLibelle(); ?> </td>
            <td>
                <?php echo $this->typefonction($domaine); ?>
            </td>
            <td>
                <?php echo count($domaine->getMetiers()); ?>
            </td>
            <?php if ($canAction) : ?>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <a  <?php /** @see \Metier\Controller\DomaineController::afficherAction() */ ?>
                            href="<?php echo $this->url('domaine/afficher', ['domaine' => $domaine->getId()], [], true); ?>"
                            class="ajax-modal action secondary"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <br/>
                    <a  <?php /** @see \Metier\Controller\DomaineController::modifierAction() */ ?>
                        href="<?php echo $this->url('domaine/modifier', ['domaine' => $domaine->getId()], [], true); ?>"
                        class="ajax-modal action primary"
                        data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br/>
                    <?php if ($domaine->estNonHistorise()) : ?>
                        <a  <?php /** @see \Metier\Controller\DomaineController::historiserAction() */ ?>
                            href="<?php echo $this->url('domaine/historiser', ['domaine' => $domaine->getId()], [], true); ?>"
                            class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <a  <?php /** @see \Metier\Controller\DomaineController::restaurerAction() */ ?>
                            href="<?php echo $this->url('domaine/restaurer', ['domaine' => $domaine->getId()], [], true); ?>"
                            class="action secondary"
                        >
                            <span class="icon icon-restaurer"></span>
                            Supprimer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <br/>
                    <a  <?php /** @see \Metier\Controller\DomaineController::supprimerAction() */ ?>
                        href="<?php echo $this->url('domaine/supprimer', ['domaine' => $domaine->getId()], [], true); ?>"
                        class="ajax-modal action danger" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>

                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('table#domaines').dataTable({
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [4], orderable: false }
            ]
        });
    });
</script>