<?php

namespace EntretienProfessionnel\Provider\Etat;

class EntretienProfessionnelEtats {

    const TYPE = 'ENTRETIEN_PROFESSIONNEL';

    const ETAT_ENTRETIEN_ACCEPTATION        = 'ENTRETIEN_ACCEPTATION';
    const ETAT_ENTRETIEN_ACCEPTER           = 'ENTRETIEN_ACCEPTER';
    const ENTRETIEN_VALIDATION_RESPONSABLE  = 'ENTRETIEN_VALIDATION_RESPONSABLE';
    const ENTRETIEN_VALIDATION_OBSERVATION  = 'ENTRETIEN_VALIDATION_OBSERVATION';
    const ENTRETIEN_VALIDATION_HIERARCHIE   = 'ENTRETIEN_VALIDATION_HIERARCHIE';
    const ENTRETIEN_VALIDATION_AGENT        = 'ENTRETIEN_VALIDATION_AGENT';
}