<?php

/**
 * @see \FicheMetier\Controller\ConfigurationController::applicationAction()
 * @var ConfigurationFicheMetier[] $defaultApplication
 * @var Parametre[] $parametres
 */

use Application\Entity\Db\ConfigurationFicheMetier;
use Element\Entity\Db\Application;
use Element\Provider\Privilege\ApplicationPrivileges;
use UnicaenParametre\Entity\Db\Parametre;

$this->headTitle("Configuration des fiches métiers");

$canConfigurer = true; //todo
$canVoirApplication = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_AFFICHER));

/** @see \FicheMetier\Controller\ConfigurationController::applicationAction() */
$retour = $this->url('fiche-metier/configuration/application', [], [], true);
?>

<!-- inclusion du header -->
<?php echo $this->partial('header', ['selected' => 'application', 'parametres' => $parametres]); ?>


<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<div class="alert alert-info">
    <span class="icon icon-info"></span>
    Les applications ci-dessous sont ajoutées automatiquement aux fiches métiers lors de leur création.
</div>

<?php /** @see \FicheMetier\Controller\ConfigurationController::ajouterAction() */ ?>
<a href="<?php echo $this->url('fiche-metier/configuration/ajouter', ['type' => 'application'], [], true); ?>"
   class="btn btn-primary ajax-modal" data-event="modification"
>
    <span class="icon icon-ajouter"></span>
    Ajouter une application
</a>
<?php /** @see \FicheMetier\Controller\ConfigurationController::reappliquerAction() */ ?>
<a href="<?php echo $this->url("fiche-metier/configuration/reappliquer", ['type' => 'application'], [], true); ?>"
   class="btn btn-primary ajax-modal" data-event="modification"
>
    <span class="icon icon-gerer"></span>
    Réappliquer les applications
</a>

<table class="table table-condensed" id="default_competence">
    <thead>
    <tr>
        <th class="col-md-10"> Libellé</th>
        <th class="col-md-2 action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($defaultApplication as $application): ?>
        <tr>
            <td> <?php echo $application->getEntity()->getLibelle(); ?> </td>
            <td class="action">
                <?php if ($canVoirApplication): ?>
                    <a href="<?php echo $this->url('element/application/afficher', ['application' => $application->getEntity()->getId()], [], true); ?>"
                       class="action secondary ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canConfigurer): ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\ConfigurationController::retirerAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier/configuration/retirer', ['id' => $application->getId()], ['query' => ['retour' => $retour]], true); ?>"
                       class="action danger"
                    >
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
