<?php

/**
 * @see \FicheMetier\Controller\ConfigurationController::competenceAction()
 * @see \FicheMetier\Controller\ConfigurationController::applicationAction()
 * @var string $selected
 * @var Parametre[] $parametres
 */

use FicheMetier\Provider\Parametre\FicheMetierParametres;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;
use UnicaenParametre\Entity\Db\Parametre;

$this->headTitle("Configuration des fiches métiers");

$canFicheMetierIndex = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_INDEX));
?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Configuration des fiches métiers
        </h1>
    </div>
    <div class="col-md-3">
        <?php if ($canFicheMetierIndex) : ?>
            <?php /** @see \FicheMetier\Controller\FicheMetierController::indexAction() */ ?>
            <a href="<?php echo $this->url('fiche-metier', [],[], true); ?>"
               class="btn btn-secondary">
                <span class="icon icon-listing"></span>
                Accéder aux fiches métiers
            </a>
        <?php endif; ?>
    </div>
</div>


<div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link <?php if ($selected === "competence") echo " active "; ?>"
            id="competence-tab"
            data-bs-toggle="tab" data-bs-target="#competence"
            type="button" role="tab" aria-controls="competence"
            aria-selected="true"
            onclick="location.href='<?php echo $this->url('fiche-metier/configuration/competence', [], [], true); ?>'">
        Compétences par défaut
    </button>
        <?php if (isset($parametres[FicheMetierParametres::DISPLAY_APPLICATION]) AND $parametres[FicheMetierParametres::DISPLAY_APPLICATION]?->getValeur() === "true") : ?>
        <button class="nav-link <?php if ($selected === "application") echo " active "; ?>"
                id="application-tab"
                data-bs-toggle="tab" data-bs-target="#application"
                type="button" role="tab" aria-controls="application"
                aria-selected="true"
                onclick="location.href='<?php echo $this->url('fiche-metier/configuration/application', [], [], true); ?>'">
            Applications par défaut
        </button>
    <?php endif; ?>
    <button class="nav-link <?php if ($selected === "tendance") echo " active "; ?>"
            id="tendance-tab"
            data-bs-toggle="tab" data-bs-target="#tendance"
            type="button" role="tab" aria-controls="tendance"
            aria-selected="true"
            onclick="location.href='<?php echo $this->url('fiche-metier/tendance-type', [], [], true); ?>'">
        Tendances d'évolution
    </button>
    <button class="nav-link <?php if ($selected === "thematique") echo " active "; ?>"
            id="thematique-tab"
            data-bs-toggle="tab" data-bs-target="#thematique"
            type="button" role="tab" aria-controls="thematique"
            aria-selected="true"
            onclick="location.href='<?php echo $this->url('fiche-metier/thematique-type', [], [], true); ?>'">
        Contexte et environnement de travail
    </button>
</div>

<br>

<script>
    $("body").on("modification", function (event) {
        event.div.modal('hide');
        window.location.reload();
    });
</script>