<?php

use Application\Entity\Db\ConfigurationFicheMetier;
use Element\Provider\Privilege\ApplicationPrivileges;
use Element\Provider\Privilege\CompetencePrivileges;
use FicheMetier\Provider\Parametre\FicheMetierParametres;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;
use UnicaenParametre\Entity\Db\Parametre;

/**
 * @see \FicheMetier\Controller\ConfigurationController::indexAction()
 * @var ConfigurationFicheMetier[] $defaultApplication
 * @var ConfigurationFicheMetier[] $defaultCompetence
 * @var Parametre[] $parametres
 */

$this->headTitle("Configuration des fiches métiers");

$canConfigurer = true; //todo
$canFicheMetierIndex = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_INDEX));
$canVoirApplication = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_AFFICHER));
$canVoirCompetence = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_AFFICHER));
?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Configuration des fiches métiers
        </h1>
    </div>
    <div class="col-md-3">
        <?php if ($canFicheMetierIndex) : ?>
            <?php /** @see \FicheMetier\Controller\FicheMetierController::indexAction() */ ?>
            <a href="<?php echo $this->url('fiche-metier', [],[], true); ?>"
               class="btn btn-secondary">
                <span class="icon icon-listing"></span>
                Accéder aux fiches métiers
            </a>
        <?php endif; ?>
    </div>
</div>


<div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link"
            id="competence-tab"
            data-bs-toggle="tab" data-bs-target="#competence"
            type="button" role="tab" aria-controls="competence"
            aria-selected="true"
            onclick="location.href='<?php echo $this->url('fiche-metier/configuration', [], [], true); ?>'">
        Compétences par défaut
    </button>
    <?php $a=1; ?>
    <?php if ($parametres[FicheMetierParametres::DISPLAY_APPLICATION] AND $parametres[FicheMetierParametres::DISPLAY_APPLICATION]->getValeur() === true) : ?>
        <button class="nav-link"
                id="application-tab"
                data-bs-toggle="tab" data-bs-target="#element"
                type="button" role="tab" aria-controls="element"
                aria-selected="true"
                onclick="location.href='<?php echo $this->url('fiche-metier/configuration', [], [], true); ?>'">
            Applications par défaut
        </button>
    <?php endif; ?>
    <button class="nav-link"
            id="element-tab"
            data-bs-toggle="tab" data-bs-target="#element"
            type="button" role="tab" aria-controls="element"
            aria-selected="true"
            onclick="location.href='<?php echo $this->url('fiche-metier/configuration', [], [], true); ?>'">
        Tendances
    </button>
    <button class="nav-link"
            id="element-tab"
            data-bs-toggle="tab" data-bs-target="#element"
            type="button" role="tab" aria-controls="element"
            aria-selected="true"
            onclick="location.href='<?php echo $this->url('fiche-metier/configuration', [], [], true); ?>'">
        Thématiques
    </button>
</div>


<?php /** @see \FicheMetier\Controller\ConfigurationController::reappliquerAction() */ ?>
<a href="<?php echo $this->url("fiche-metier/configuration/reappliquer", [], [], true); ?>"
   class="btn btn-primary"
>
    <span class="icon icon-gerer"></span>
    Réappliquer les applications et compétences
</a>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<h2> Compétences ajoutées par défaut</h2>

<div class="alert alert-info">
    <span class="icon icon-info"></span>
    Les compétences ci-dessous sont ajoutées automatiquement aux fiches métiers lors de leur création.
</div>

<?php /** @see \FicheMetier\Controller\ConfigurationController::ajouterAction() */ ?>
<a href="<?php echo $this->url('fiche-metier/configuration/ajouter', ['type' => 'competence'], [], true); ?>"
   class="btn btn-primary ajax-modal" data-event="modification"
>
    <span class="icon icon-ajouter"></span>
    Ajouter une compétence
</a>

<table class="table table-condensed" id="default_competence">
    <thead>
    <tr>
        <th class="col-md-10"> Libellé </th>
        <th class="col-md-2 action"> Action </th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($defaultCompetence as $competence): ?>
            <tr>
                <td> <?php echo $competence->getEntity()->getLibelle(); ?> </td>
                <td class="action">
                    <?php if ($canVoirCompetence): ?>
                       <a href="<?php echo $this->url('element/competence/afficher', ['competence' => $competence->getEntity()->getId()], [], true); ?>"
                           class="action secondary ajax-modal" data-event="modification"
                       >
                            <span class="icon icon-voir"></span>
                            Afficher
                        </a>
                    <?php endif; ?>
                    <?php if ($canConfigurer): ?>
                        <br>
                        <?php /** @see \FicheMetier\Controller\ConfigurationController::retirerAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/configuration/retirer', ['id' => $competence->getId()], [], true); ?>"
                           class="action danger"
                        >
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<h2> Applications ajoutées par défaut</h2>

<div class="alert alert-info">
    <span class="icon icon-info"></span>
    Les applications ci-dessous sont ajoutées automatiquement aux fiches métiers lors de leur création.
</div>

<?php /** @see \FicheMetier\Controller\ConfigurationController::ajouterAction() */ ?>
<a href="<?php echo $this->url('fiche-metier/configuration/ajouter', ['type' => 'application'], [], true); ?>"
   class="btn btn-primary ajax-modal" data-event="modification"
>
    <span class="icon icon-ajouter"></span>
    Ajouter une application
</a>

<table class="table table-condensed" id="default_application">
    <thead>
    <tr>
        <th class="col-md-10"> Libellé </th>
        <th class="col-md-2 action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($defaultApplication as $application): ?>
        <tr>
            <td> <?php echo $application->getEntity()->getLibelle(); ?> </td>
            <td class="action">
                <?php if ($canVoirApplication): ?>
                    <?php /** @see \Element\Controller\ApplicationController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('element/application/afficher', ['application' => $application->getEntity()->getId()], [], true); ?>"
                       class="action secondary ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canConfigurer): ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\ConfigurationController::retirerAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier/configuration/retirer', ['id' => $application->getId()], [], true); ?>"
                       class="action danger"
                    >
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $("body").on("modification", function (event) {
        event.div.modal('hide');
        window.location.reload();
    });
</script>