SELECT a.c_individu,
    a.utilisateur_id,
    a.prenom,
    a.nom_usage,
    a.created_on,
    a.updated_on,
    a.deleted_on,
    a.octo_id,
    a.preecog_id,
    a.harp_id,
    a.login,
    a.email,
    a.sexe,
    a.t_contrat_long,
    a.date_naissance,
    a.nom_famille,
    a.id,
    a.histo_createur_id,
    a.histo_modificateur_id,
    a.histo_destructeur_id,
    a.source_id,
    a.id_orig
   FROM agent a
  WHERE a.deleted_on IS NULL