SELECT agent.c_individu,
    agent.utilisateur_id,
    agent.prenom,
    agent.nom_usage,
    agent.created_on,
    agent.updated_on,
    agent.deleted_on,
    agent.octo_id,
    agent.preecog_id,
    agent.harp_id,
    agent.login,
    agent.email,
    agent.sexe,
    agent.t_contrat_long,
    agent.date_naissance,
    agent.nom_famille,
    agent.id,
    agent.histo_createur_id,
    agent.histo_modificateur_id,
    agent.histo_destructeur_id,
    agent.source_id,
    agent.id_orig
   FROM agent
  WHERE (agent.utilisateur_id IS NOT NULL)