<?php

/**
 * @var array $params
 */

use UnicaenApp\Form\Element\SearchAndSelect;

$denomination = (isset($params['denomination']) AND trim($params['denomination']) !== '')?trim($params['denomination']):null;
?>

        <form id="filtre" action="<?php echo $this->url(); ?>" method="get">
            <div class="row">
                <div class="col-md-9">
                    <input type="hidden" value="acceder" id="type" name="type"/>
                    <label for="denomination">Accéder directement à une fiche agent : </label>
                    <?php
                    $agentFiltreSas = new SearchAndSelect('agent-sas');
                    /** @see \Agent\Controller\AgentController::rechercherLargeAction() */
                    $agentFiltreSas->setAutocompleteSource($this->url('agent/rechercher-large'));
                    $agentFiltreSas
                        ->setSelectionRequired()
                        ->setAttributes([
                            'id' => 'agent-sas',
                            'placeholder' => "Nom ou prénom (minimum 2 caractères)",
                        ]);
                    ?>
                    <?php echo $this->formControlGroup($agentFiltreSas); ?>
                </div>
                <!-- BOUTON -->
                <div class="col-md-3">
                    <div class="pull-right">
                        <div style="height:1.2rem;">&nbsp;</div>
                        <button class="btn btn-primary action" id="acceder">
                            <span class="icon icon-voir"></span>
                            Accéder
                        </button>
                    </div>
                </div>
            </div>
        </form>

<script>

</script>