<?php

/**
 * @var array $params
 */

use UnicaenApp\Form\Element\SearchAndSelect;

$denomination = (isset($params['denomination']) AND trim($params['denomination']) !== '')?trim($params['denomination']):null;
?>

        <form id="filtre" action="<?php echo $this->url(); ?>" method="get">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="hidden" value="filtrer" id="type" name="type"/>
                            <label for="denomination">Dénomination : </label>
                            <input type="text" id="denomination" name="denomination"/>
                        </div>
                        <div class="col-md-4">
                            <?php
                            /** @see \Structure\Controller\StructureController::rechercherAction() */
                            $structureF = new SearchAndSelect('structure-filtre', ['label' => "Structure :"]);
                            $structureF
                                ->setAutocompleteSource($this->url('structure/rechercher'))
                                ->setSelectionRequired()
                                ->setAttributes([
                                    'id' => 'structure-filtre',
                                    'placeholder' => "Nom de la structure ...",
                                ]);
                            ?>
                            <?php echo $this->formControlGroup($structureF); ?>
                        </div>
                        <div class="col-md-4">
                            <label for="encours">Affectation en cours : </label>
                            <select id="encours" name="encours" class="selectpicker">
                                <option value="1"> Oui </option>
                                <option value="0"> Indifférent </option>
                            </select>
                        </div>
                    </div>
                </div>
                <!-- BOUTON -->
                <div class="col-md-3">
                    <div class="pull-right">
                        <button class="btn btn-primary action" id="filter">
                            <span class="icon icon-filtrer"></span>
                            Filtrer
                        </button>
                        <button class="btn btn-primary action" id="clear">
                            <span class="icon icon-gommer"></span> Remise à zéro
                        </button>


                    </div>
                </div>
            </div>
        </form>

<script>
    $('button#clear').click(function() {
        window.location.href = '?';
    });

    <?php if (isset($params['denomination'])) :?>
        $('input#denomination').val(<?php echo '"'.$params['denomination'].'"'; ?>);
    <?php endif; ?>
    <?php if (isset($params['structure-filtre'])) :?>
        $('input[name="structure-filtre[label]"]').val("<?php echo trim($params['structure-filtre']['label']); ?>");
        $('input[name="structure-filtre[id]"]').val("<?php echo $params['structure-filtre']['id']; ?>");
    <?php endif; ?>
    <?php if (isset($params['encours'])) :?>
        $('select#encours option[value=<?php echo $params['encours']; ?>]').prop('selected', true);
    <?php endif; ?>
</script>