<?php

/**
 * @see \EntretienProfessionnel\Controller\CampagneConfigurationIndicateurController::indexAction()
 * @var CampagneConfigurationIndicateur[] $campagneConfigurationIndicateurs
 */

use EntretienProfessionnel\Entity\Db\CampagneConfigurationIndicateur;
use EntretienProfessionnel\Provider\Privilege\CampagnePrivileges;

$this->headTitle("Configuration des indicateurs de campagne");

$canAjouter = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_MODIFIER));
$canAfficher = $canAjouter;
$canModifier = $canAjouter;
$canHistoriser = $canAjouter;
$canSupprimer = $canAjouter;
$canReappliquer = $canAjouter;

$canIndexCampagne = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_AFFICHER));

?>


<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Configuration des campagnes d'entretien professionnel
        </h1>
    </div>
    <div class="col-md-4">
        <?php if ($canIndexCampagne) : ?>
            <?php /** @see \EntretienProfessionnel\Controller\CampagneController::indexAction() */ ?>
            <a href="<?php echo $this->url('entretien-professionnel/campagne', [], [], true); ?>"
               class="btn btn-primary float-end">
                <span class="icon icon-listing"></span>
                Accéder aux campagnes
            </a>
        <?php endif; ?>
    </div>
</div>

<?php echo $this->partial('partial/onglets', ['current' => 'indicateurs'], [], true); ?>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<?php if ($canAjouter) : ?>
    <?php /** @see \EntretienProfessionnel\Controller\CampagneConfigurationIndicateurController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-indicateur/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un indicateur
    </a>
<?php endif; ?>
<?php if ($canReappliquer) : ?>
    <?php /** @see \EntretienProfessionnel\Controller\CampagneConfigurationIndicateurController::reappliquerAction() */ ?>
    <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-indicateur/reappliquer', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-refresh"></span>
        Ré-appliquer pour une campagne
    </a>
<?php endif; ?>

<br>

<?php if (empty($campagneConfigurationIndicateurs)) : ?>
    <em> Aucun indicateur </em>
<?php else : ?>
<table class="table table-condensed" id="indicateurs">
    <thead>
    <tr>
        <th class="col-md-4"> Identification </th>
        <th class="col-md-8"> Requête</th>
        <th class="col-md-2 action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($campagneConfigurationIndicateurs as $campagneConfigurationIndicateur) : ?>
        <tr class="<?php if ($campagneConfigurationIndicateur->estHistorise()) echo " historise "; ?>">
            <td>
                <code> <?php echo $campagneConfigurationIndicateur->getCode(); ?> </code>
                <br>
                <?php echo $campagneConfigurationIndicateur->getLibelle(); ?>
            </td>
            <td>
                <?php echo $campagneConfigurationIndicateur->prettyprint(); ?>
            </td>
            <td class="action">
                <?php if ($canModifier): ?>
                    <?php /**  @see \EntretienProfessionnel\Controller\CampagneConfigurationIndicateurController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-indicateur/modifier', ['campagne-configuration-indicateur' => $campagneConfigurationIndicateur->getId()], [], true); ?>"
                       class="action primary ajax-modal" data-event="modification">
                        <span class="icon icon-modifier"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser): ?>
                    <br>
                    <?php if ($campagneConfigurationIndicateur->estNonHistorise()) : ?>
                        <?php /**  @see \EntretienProfessionnel\Controller\CampagneConfigurationIndicateurController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-indicateur/historiser', ['campagne-configuration-indicateur' => $campagneConfigurationIndicateur->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /**  @see \EntretienProfessionnel\Controller\CampagneConfigurationIndicateurController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-indicateur/restaurer', ['campagne-configuration-indicateur' => $campagneConfigurationIndicateur->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer): ?>
                    <br>
                    <?php /**  @see \EntretienProfessionnel\Controller\CampagneConfigurationIndicateurController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-indicateur/supprimer', ['campagne-configuration-indicateur' => $campagneConfigurationIndicateur->getId()], [], true); ?>"
                       class="action danger ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('table#indicateurs').dataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [2], orderable: false }
            ]
        });
    });

</script>