<?php

/**
 * @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::indexAction()
 * @var CampagneConfigurationRecopie[] $campagneConfigurationRecopies
 */

use EntretienProfessionnel\Entity\Db\CampagneConfigurationRecopie;
use EntretienProfessionnel\Provider\Privilege\CampagnePrivileges;

$this->headTitle("Configuration des recopies de campagne");

$canAjouter = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_MODIFIER));
$canAfficher = $canAjouter;
$canModifier = $canAjouter;
$canHistoriser = $canAjouter;
$canSupprimer = $canAjouter;
$canReappliquer = $canAjouter;

$canIndexCampagne = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_AFFICHER));

?>


<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Configuration des campagnes d'entretien professionnel
        </h1>
    </div>
    <div class="col-md-4">
        <?php if ($canIndexCampagne) : ?>
            <?php /** @see \EntretienProfessionnel\Controller\CampagneController::indexAction() */ ?>
            <a href="<?php echo $this->url('entretien-professionnel/campagne', [], [], true); ?>"
               class="btn btn-primary float-end">
                <span class="icon icon-listing"></span>
                Accéder aux campagnes
            </a>
        <?php endif; ?>
    </div>
</div>

<?php echo $this->partial('partial/onglets', ['current' => 'recopies'], [], true); ?>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<?php if ($canAjouter) : ?>
    <?php /** @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-recopie/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter une recopie
    </a>
<?php endif; ?>
<?php if ($canReappliquer) : ?>
    <?php /** @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::verifierAction() */ ?>
    <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-recopie/verifier', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-refresh"></span>
        Vérifier les recopies
    </a>
<?php endif; ?>

<br>

<?php if (empty($campagneConfigurationRecopies)) : ?>
    <em> Aucune recopies </em>
<?php else : ?>
    <table class="table table-condensed" id="recopies">
        <thead>
        <tr>
            <th class="col-md-5"> Champ dans la campagne précédente</th>
            <th class="col-md-5"> Champ dans la nouvelle campagne</th>
            <th class="col-md-5 action"> Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($campagneConfigurationRecopies as $campagneConfigurationRecopie) : ?>
            <tr class="<?php if ($campagneConfigurationRecopie->estHistorise()) echo " historise "; ?>">
                <td>
                    <?php echo $campagneConfigurationRecopie->getFrom()->getLibelle(); ?>
                    <br>
                    <code><?php echo $campagneConfigurationRecopie->getFrom()->getType()->getLibelle(); ?></code>
                </td>
                <td>
                    <?php echo $campagneConfigurationRecopie->getTo()->getLibelle(); ?>
                    <br>
                    <code><?php echo $campagneConfigurationRecopie->getTo()->getType()->getLibelle(); ?></code>
                </td>
                <td class="action">
                    <?php if ($canModifier): ?>
                        <?php /**  @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::modifierAction() */ ?>
                        <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-recopie/modifier', ['campagne-configuration-recopie' => $campagneConfigurationRecopie->getId()], [], true); ?>"
                           class="action primary ajax-modal" data-event="modification">
                            <span class="icon icon-modifier"></span>
                            Modifier
                        </a>
                    <?php endif; ?>
                    <?php if ($canHistoriser): ?>
                        <br>
                        <?php if ($campagneConfigurationRecopie->estNonHistorise()) : ?>
                            <?php /**  @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::historiserAction() */ ?>
                            <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-recopie/historiser', ['campagne-configuration-recopie' => $campagneConfigurationRecopie->getId()], [], true); ?>"
                               class="action warning">
                                <span class="icon icon-historiser"></span>
                                Historiser
                            </a>
                        <?php else : ?>
                            <?php /**  @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::restaurerAction() */ ?>
                            <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-recopie/restaurer', ['campagne-configuration-recopie' => $campagneConfigurationRecopie->getId()], [], true); ?>"
                               class="action warning">
                                <span class="icon icon-restaurer"></span>
                                Restaurer
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canSupprimer): ?>
                        <br>
                        <?php /**  @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::supprimerAction() */ ?>
                        <a href="<?php echo $this->url('entretien-professionnel/campagne/configuration-recopie/supprimer', ['campagne-configuration-recopie' => $campagneConfigurationRecopie->getId()], [], true); ?>"
                           class="action danger ajax-modal" data-event="modification">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('table#recopies').dataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [2], orderable: false}
            ]
        });
    });

</script>