<?php

use EntretienProfessionnel\Entity\Db\CampagneConfigurationRecopie;
use EntretienProfessionnel\Form\CampagneConfigurationRecopie\CampagneConfigurationRecopieForm;

/**
 * @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::ajouterAction()
 * @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::modifierAction()
 * @var CampagneConfigurationRecopieForm $form
 * @var CampagneConfigurationRecopie $recopie
 */

?>

<?php echo $this->form($form); ?>

<script>
    $('select#champ-from').parent().hide();
    $('select#champ-to').parent().hide();

    async function generateSelect(formulaireId) {
        let url = "<?php echo $this->url("formulairechamps", [], ['force_canonical' => true], true); ?>" + "/" + formulaireId;
        return await $.ajax({
            type: "POST",
            url: url,
            dataType: "json"
        });
    }

    async function manageChampForm(id) {
        let value = $('select#formulaire-from').val();

        if (value !== '') {
            const data = await generateSelect(value);

            $('select#champ-from').empty();
            data.forEach(group => {
                const optgroup = document.createElement('optgroup');
                optgroup.label = group.label;

                group.options.forEach(opt => {
                    const option = new Option(opt.text, opt.value);
                    optgroup.appendChild(option);
                });

                document.getElementById('champ-from').appendChild(optgroup);
                if (id !== undefined) $('select#champ-from option[value='+id+']').prop('selected', true);
            });

            $('select#champ-from').parent().show();
        } else {
            $('select#champ-from').parent().hide();
        }
    }

    async function manageChampTo(id) {
        let value = $('select#formulaire-to').val();
        // console.log("changement select formulaire-form ... ["+ value +"]");
        if (value !== '') {
            // console.log("peuplement select");
            const data = await generateSelect(value);
            // console.log(data);

            $('select#champ-to').empty();
            data.forEach(group => {
                const optgroup = document.createElement('optgroup');
                optgroup.label = group.label;

                group.options.forEach(opt => {
                    const option = new Option(opt.text, opt.value);
                    optgroup.appendChild(option);
                });

                document.getElementById('champ-to').appendChild(optgroup);
                if (id !== undefined) $('select#champ-to option[value=' + id + ']').prop('selected', true);
            });

            // console.log("affichage du select pour les champ-from");
            $('select#champ-to').parent().show();

            // todo
        } else {
            // console.log("masquage du select pour les champ-from");
            $('select#champ-to').parent().hide();
        }
    }

    $(function() {
        $('select#formulaire-from').on('change', function() {
            manageChampForm();
        });
        $('select#formulaire-to').on('change', function() {
            manageChampTo();
        });

        manageChampForm(<?php echo $recopie->getFrom()?->getId(); ?>);
        manageChampTo(<?php echo $recopie->getTo()?->getId(); ?>);
    });
</script>