<?php

use EntretienProfessionnel\Entity\Db\Campagne;

/**
 * @see \EntretienProfessionnel\Controller\CampagneConfigurationIndicateurController::reappliquerAction()
 * @see \EntretienProfessionnel\Controller\CampagneConfigurationRecopieController::verifierAction()
 * @var Campagne[] $campagnes
 * @var string $url
 * @var ?string $info
 */

?>

<?php if (isset($info)) : ?>
    <div class="alert alert-info">
        <span class="icon icon-info"></span>
        <?php echo $info; ?>
    </div>
<?php endif; ?>

<form method="post" action="<?php echo $url; ?>">
    <label for="campagne">
        Campagne <span class="icon icon-obligatoire"></span>:
    </label>
    <select id="campagne" name="campagne">
        <option value=""> Sélectionner une campagne ... </option>
        <?php foreach ($campagnes as $campagne) : ?>
            <option value="<?php echo $campagne->getId(); ?>">
                <?php echo $campagne->getAnnee(); ?>
            </option>
        <?php endforeach; ?>
    </select>
    <button class="btn btn-primary">
        Réappliquer sur la campagne
    </button>
</form>

<script>
    $('select').selectpicker();
</script>