<?php

/**
 * @see \EntretienProfessionnel\Controller\ObservateurController::indexAction()
 * @var Campagne[] $campagnes
 * @var Observateur[] $observateurs
 * @var array $params
 **/

use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\Observateur;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use EntretienProfessionnel\Provider\Privilege\ObservateurPrivileges;

//note economie de temps en testant globalement
$canAcceder = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AFFICHER));

$canAjouter = $this->isAllowed(ObservateurPrivileges::getResourceId(ObservateurPrivileges::OBSERVATEUR_AJOUTER));
$canImporter = $this->isAllowed(ObservateurPrivileges::getResourceId(ObservateurPrivileges::OBSERVATEUR_AJOUTER));
$canHistorise = $this->isAllowed(ObservateurPrivileges::getResourceId(ObservateurPrivileges::OBSERVATEUR_HISTORISER));
$canSupprimer = $this->isAllowed(ObservateurPrivileges::getResourceId(ObservateurPrivileges::OBSERVATEUR_SUPPRIMER));
?>


<h1 class="page-header">
    Observateur·trices d'entretiens professionnels
</h1>


<?php echo $this->partial('partial/filtre', ['campagnes' => $campagnes, 'params' => $params]); ?>

<div>
    <?php if ($canAcceder): ?>
        <?php /** @see \EntretienProfessionnel\Controller\ObservateurController::ajouterAction() */ ?>
        <a href="<?php echo $this->url("entretien-professionnel/observateur/ajouter", [], [], true); ?>"
           class="btn btn-primary ajax-modal" data-event="modification">
            <span class="icon icon-ajouter"></span>
            Ajouter un observateur
        </a>
    <?php endif; ?>

    <?php if ($canImporter): ?>
        <?php /** @see \EntretienProfessionnel\Controller\ObservateurController::importerAction() */ ?>
        <a href="<?php echo $this->url("entretien-professionnel/observateur/importer", [], [], true); ?>"
           class="btn btn-primary">
            <span class="icon icon-csv"></span>
            Importer des observateurs depuis un CSV
        </a>
    <?php endif; ?>
</div>

<table class="table table-condensed datatable" id="observateurs">
    <thead>
        <tr>
            <th>
                Observateurs
            </th>
            <th data-type="string">
                Acteurs de l'entretien
            </th>
            <th data-type="num">
                Campagne et date
            </th>
            <th data-type="num">
                État
            </th>
            <th class="action">
                Action
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($observateurs as $observateur) : ?>
        <?php $entretien = $observateur->getEntretienProfessionnel(); ?>
        <tr class=" <?php echo ($observateur->estHistorise())?" historise ":""; ?> ">
            <td>
                <?php echo $observateur->getUser()->getDisplayName(); ?>
            </td>
            <td data-order="<?php echo $entretien->getAgent()->getDenomination(); ?>">
                <dl class="row">
                    <dt class="col-md-4"> Agent·e&nbsp;:</dt>
                    <dd class="col-md-8"> <?php echo $entretien->getAgent()->getDenomination(true); ?> </dd>
                    <dt class="col-md-4"> Responsable&nbsp;:</dt>
                    <dd class="col-md-8"> <?php echo $entretien->getResponsable()->getDenomination(true); ?> </dd>
                </dl>
            </td>
            <td data-order="<?php echo $entretien->getDateEntretien()->getTimestamp(); ?>">
                <dl class="row">
                    <dt class="col-md-4"> Campagne&nbsp;:</dt>
                    <dd class="col-md-8"> <?php echo $entretien->getCampagne()->getAnnee(); ?>
                    <dt class="col-md-4"> Date de l'entretien&nbsp;:</dt>
                    <dd class="col-md-8"> <?php echo $entretien->getDateEntretien()->format("d/m/Y"); ?></dd>
                </dl>
            </td>
            <?php $etat = $entretien->getEtatActif(); ?>
            <td data-order="<?php echo $etat->getType()->getOrdre();?>">
                <?php echo $this->etatinstance($entretien->getEtatActif()); ?>
            </td>
            <td class="action">
                <?php if ($canAcceder) : ?>
                    <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::accederAction() */ ?>
                    <a href="<?php echo $this->url('entretien-professionnel/acceder', ['entretien-professionnel' => $entretien->getId()] ,[], true); ?>"
                       class="action secondary"
                    >
                        <span class="icon icon-voir"></span>
                        Accéder
                    </a>
                <?php endif; ?>
                <?php if ($canHistorise) : ?>
                    <br>
                    <?php if ($observateur->estNonHistorise()) : ?>
                        <a href="<?php echo $this->url('entretien-professionnel/observateur/historiser', ['observateur' => $observateur->getId()], ["query" => ["retour" => $this->url()]], true); ?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historise
                        </a>
                    <?php else : ?>
                        <a href="<?php echo $this->url('entretien-professionnel/observateur/restaurer', ['observateur' => $observateur->getId()], ["query" => ["retour" => $this->url()]], true); ?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::accederAction() */ ?>
                    <a href="<?php echo $this->url('entretien-professionnel/observateur/supprimer', ['observateur' => $observateur->getId()] ,[], true); ?>"
                       class="action danger ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('#observateurs').DataTable({
            autoWidth: false,
            columnDefs: [{
                "targets": 4,
                "orderable": false
            }],
            language: {
                url: '/js/datatables_fr.json'
            }
        });
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>