<?php

/**
 * @see \Element\Controller\ApplicationController::afficherAction()
 * @var Application $application
 */
use Element\Entity\Db\Application;
?>

<dl class="row">
    <dt class="col-md-4"> Identifiant</dt>
    <dd class="col-md-8"> <?php echo $application->getId(); ?> </dd>
    <dt class="col-md-4"> Libellé</dt>
    <dd class="col-md-8"> <?php echo $application->getLibelle(); ?> </dd>
    <dt class="col-md-4"> Lien</dt>
    <dd class="col-md-8">
        <a href="<?php echo $application->getUrl(); ?>">
            <?php echo $application->getUrl(); ?>
        </a>
    </dd>
    <dt class="col-md-4"> Actif</dt>
    <dd class="col-md-8">
        <?php if ($application->isActif()) : ?>
            <span class="badge" style="background-color: darkgreen;">&nbsp;</span> Actif
        <?php else: ?>
            <span class="badge" style="background-color: darkred;">&nbsp;</span> Désactivé
        <?php endif;?>
    </dd>
    <?php if ($application->getDescription()) : ?>
        <dt class="col-md-4"> Description</dt>
        <dd class="col-md-8"> <?php echo $application->getDescription(); ?> </dd>
    <?php endif; ?>
</dl>
