<?php

use Element\Entity\Db\Application;
use Element\Provider\Privilege\ApplicationPrivileges;
use Element\Entity\Db\ApplicationTheme;
use Element\Provider\Privilege\ApplicationthemePrivileges;

/**
 * @see \Element\Controller\ApplicationController::indexAction()
 * @var Application[] $applications
 * @var ApplicationTheme[] $groupes
 * @var int $groupeSelected
 * @var int $activite
 */

$this->headTitle("Liste des applications");

$canAfficher = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_AFFICHER));
$canAjouter = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_AJOUTER));
$canModifier =  $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_MODIFIER));
$canHistoriser =  $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_HISTORISER));
$canSupprimer = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_EFFACER));

$canApplicationThemeIndex = $this->isAllowed(ApplicationthemePrivileges::getResourceId(ApplicationthemePrivileges::APPLICATIONTHEME_INDEX));
$canCartographie = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_CARTOGRAPHIE));

$canAction = ($canAfficher OR $canModifier OR $canHistoriser OR $canSupprimer);

?>

<h1 class="page-header">
    Liste des applications
</h1>

<div class="row">
    <div class="col-md-6">
        <?php if ($canAjouter) : ?>
            <a  <?php /** @see \Element\Controller\ApplicationController::creerAction() */?>
                    href="<?php echo $this->url('element/application/creer', [], [], true);?>"
                    class="btn btn-primary ajax-modal"
                    data-event="modification"
            >
                <span class="icon icon-ajouter"></span>
                Ajouter une application
            </a>
        <?php endif; ?>

    </div>
    <div class="col-md-6">
        <?php if ($canApplicationThemeIndex) : ?>
            <a  <?php /** @see \Element\Controller\ApplicationThemeController::indexAction() */?>
                href="<?php echo $this->url('element/application-theme'); ?>"
               class="btn btn-secondary"
            >
                <span class="icon icon-listing"></span>
                Accéder aux thèmes
            </a>
        <?php endif; ?>
        <?php if ($canCartographie) : ?>
            <a href="<?php echo $this->url('element/application/cartographie'); ?>"
               class="btn btn-secondary"
            >
                <span class="icon icon-voir"> Cartographie </span>
            </a>
        <?php endif; ?>
    </div>
</div>

<table id="applications" class="table table-condensed table-hover">
    <thead>
    <tr>
        <th> Libelle</th>
        <th> Thème </th>
        <th> Liens </th>
        <th style="width: 4rem;"> Actif </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($applications as $application): ?>
        <tr class="<?php if ($application->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $application->getLibelle(); ?> </td>
            <td>
                <?php if ($application->getTheme()) : ?>
                    <?php echo $application->getTheme()->getLibelle(); ?>
                <?php else : ?>
                    Sans groupe
                <?php endif; ?>
            </td>
            <td>
                <?php if ($application->getUrl() === null) : ?>
                    <em> Aucun lien fourni </em>
                <?php else : ?>
                    <a href="<?php echo $application->getUrl(); ?>"><?php echo $application->getUrl(); ?></a>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canModifier) : ?>
                <a
                    <?php /** @see \Element\Controller\ApplicationController::changerStatusAction() */?>
                        href="<?php echo $this->url('element/application/changer-status', ['id' => $application->getId()], [], true); ?>"
                        title="Activer/Desactiver l'application"
                >
                    <?php endif; ?>
                    <?php if ($application->isActif()) : ?>
                        <span class="badge" style="background-color: darkgreen;">&nbsp;</span>
                    <?php else : ?>
                        <span class="badge" style="background-color: darkred;">&nbsp;</span>
                    <?php endif;?>
                    <?php if ($canModifier) : ?>
                </a>
            <?php endif; ?>
            </td>
            <?php if ($canAction) : ?>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Element\Controller\ApplicationController::afficherAction() */?>
                    <a href="<?php echo $this->url('element/application/afficher', ['application' => $application->getId(), 'withAgent' => "1"], [], true); ?>"
                       class="ajax-modal action secondary">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br/>
                    <?php /** @see \Element\Controller\ApplicationController::editerAction() */?>
                    <a href="<?php echo $this->url('element/application/editer', ['id' => $application->getId()], [], true); ?>"
                       class="ajax-modal action primary" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($application->estNonHistorise()) : ?>
                        <?php /** @see \Element\Controller\ApplicationController::historiserAction() */?>
                        <a href="<?php echo $this->url('element/application/historiser', ['id' => $application->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Element\Controller\ApplicationController::restaurerAction() */?>
                        <a href="<?php echo $this->url('element/application/restaurer', ['id' => $application->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \Element\Controller\ApplicationController::effacerAction() */?>
                    <a href="<?php echo $this->url('element/application/effacer', ['id' => $application->getId()], [], true); ?>"
                            class="ajax-modal action danger" data-event="modification">
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('table#applications').dataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [4], orderable: false }
            ]
        });
    });
</script>

