<?php

/** @var $form */
?>

<!--<h1 class="page-header">-->
<!--    Ajout d'une activité existante-->
<!--</h1>-->


<div>
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formControlGroup($form->get('activite')); ?>
    <?php echo $this->formControlGroup($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>

<br/>

<div id="none" class="alert-info preview">
    Aucune prévisualisation.
</div>

<?php foreach ($options as $key => $infos) :?>
    <div style='display:none;' class="preview alert-info" id="<?php echo $key;?>">
        <h3><?php echo $infos["title"]; ?></h3>
        <?php echo $infos["description"]; ?>
    </div>
<?php endforeach; ?>

<script>
    $(function() {
        $("select#activite").change(function () {
            let text = $("select#activite option:selected").val();
            $("div.preview").hide();
            if (text.length > 0) {
                $("div#" + text).show();
            } else {

                $("div#none").show();
            }

        });
    });
</script>
