<?php

/** @var $form */
?>

<h1 class="page-header">
    Modification des missions principales
</h1>

<?php
    echo $this->form($form);
?>

<script>
        // Prevent bootstrap dialog from blocking focusin
        $(document).on('focusin', function(e) {
            if ($(e.target).closest(".mce-window").length) {
                e.stopImmediatePropagation();
            }
        });
        $('#open').click(function() {
            $("#dialog").dialog({
                width: 800,
                modal: true
            });
        });
</script>
