<?php

use MissionSpecifique\Entity\Db\MissionSpecifiqueType;
use Missionspecifique\Provider\Privilege\MissionspecifiquePrivileges;
use Missionspecifique\Provider\Privilege\MissionspecifiquethemePrivileges;
use Missionspecifique\Provider\Privilege\MissionspecifiquetypePrivileges;

/**
 * @see \MissionSpecifique\Controller\MissionSpecifiqueTypeController::indexAction()
 * @var MissionSpecifiqueType[] $types
 */

$this->headTitle("Types de mission spécifique");

$canIndexMissionSpecifique = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_INDEX));
$canIndexMissionSpecifiqueTheme = $this->isAllowed(MissionspecifiquethemePrivileges::getResourceId(MissionspecifiquethemePrivileges::MISSIONSPECIFIQUETHEME_INDEX));

$canAfficher = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_AFFICHER));
$canAjouter = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_AJOUTER));
$canModifier = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_MODIFIER));
$canHistoriser = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_HISTORISER));
$canEffacer = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_DETRUIRE));

?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Types de mission spécifique
        </h1>

        <?php if ($canAjouter) : ?>
            <?php /** @see \MissionSpecifique\Controller\MissionSpecifiqueTypeController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('mission-specifique-type/ajouter', [], [], true); ?>"
               class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un type de mission
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-3">
        <?php if ($canIndexMissionSpecifique) : ?>
            <?php /** @see \MissionSpecifique\Controller\MissionSpecifiqueController::indexAction() */ ?>
            <a href="<?php echo $this->url("mission-specifique"); ?>" class="btn btn-secondary">
                <span class="icon icon-listing"></span>
                Accéder aux missions
            </a>
        <?php endif; ?>
        <?php if ($canIndexMissionSpecifiqueTheme) : ?>
            <?php /** @see \MissionSpecifique\Controller\MissionSpecifiqueThemeController::indexAction() */ ?>
            <a href="<?php echo $this->url("mission-specifique-theme"); ?>" class="btn btn-secondary">
                <span class="icon icon-listing"></span>
                Accéder aux thèmes
            </a>
        <?php endif; ?>
    </div>
</div>

<br/>

<table class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Libellé</th>
        <th> #Missions</th>
        <th class="action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($types as $type) : ?>
        <tr class="<?php if ($type->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $type->getLibelle(); ?> </td>
            <td> <?php echo count($type->getMissions()); ?> </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \MissionSpecifique\Controller\MissionSpecifiqueTypeController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('mission-specifique-type/afficher', ['type' => $type->getId()], [], true); ?>"
                       class="ajax-modal action secondary"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \MissionSpecifique\Controller\MissionSpecifiqueTypeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('mission-specifique-type/modifier', ['type' => $type->getId()], [], true); ?>"
                       class="ajax-modal action primary" data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($type->estNonHistorise()) : ?>
                        <?php /** @see \MissionSpecifique\Controller\MissionSpecifiqueTypeController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('mission-specifique-type/historiser', ['type' => $type->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \MissionSpecifique\Controller\MissionSpecifiqueTypeController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('mission-specifique-type/restaurer', ['type' => $type->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <br>
                    <?php /** @see \MissionSpecifique\Controller\MissionSpecifiqueTypeController::detruireAction() */ ?>
                    <a href="<?php echo $this->url('mission-specifique-type/detruire', ['type' => $type->getId()], [], true); ?>"
                       class="ajax-modal action danger" data-event="modification"
                    >
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors = [];
            window.location.reload();
        });

        $('.datatable').DataTable({
            autoWidth: false,
            paging: false,
            order: [[0, 'asc'], [1, 'asc']],
            columnDefs: [{
                "targets": 2,
                "orderable": false
            }],
            language: {
                url: '/js/datatables_fr.json'
            }
        });
    });
</script>