<?php

/**
 * @var FicheMetier $fiche
 * @var FicheMetierTypeActivite[] $activites
 * @var SpecificitePoste $specificite
 */

use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FicheMetierTypeActivite;
use Application\Entity\Db\SpecificitePoste;
use Application\Provider\Privilege\FicheMetierPrivileges;

$canAssocierAgent = true;
$canAssocierMetierType = true;

$canEditerSpecificte = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::EDITER));
$canEditer = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::EDITER));
?>

<h1 class="page-header">
    Fiche métier : <?php echo $fiche->getLibelle(); ?> <br/>
    Affectation : <?php echo $fiche->getAffectation(); ?>
</h1>


<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h2> Agent occupant le poste </h2>
            </div>
            <div class="col-md-4">
                <?php if($canAssocierAgent) : ?>
                    <a href="<?php echo $this->url('fiche-metier/associer-agent',['fiche' => $fiche->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="modification"
                    >
                        <i class="fas fa-plus-circle"></i>
                        Associer un agent
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="panel-body">


        <?php $agent = $fiche->getAgent(); ?>

        <?php if($agent === null) : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucun agent d'associé à ce poste
            </div>
        <?php else : ?>
            <dl class="dl-horizontal">
                <dt> Dénomination </dt>
                    <dd> <?php echo $agent->getPrenom(); ?> <?php echo $agent->getNom(); ?> </dd>
                <dt> Numéro poste SIHAM </dt>
                <dd> <?php echo $agent->getNumeroPoste(); ?> </dd>
                <dt> Status de l'agent  </dt>
                    <dd> <?php echo $agent->getStatus(); ?> </dd>
                <dt> Correspondance  </dt>
                <dd> <?php echo $agent->getCorrespondance(); ?> </dd>
                <dt> Corps ou Grade </dt>
                    <dd> <?php echo $agent->getCorps(); ?> </dd>
                <dt> Quotité travaillée </dt>
                    <dd> <?php echo $agent->getQuotite(); ?> % </dd>
                <dt> Date de début </dt>
                    <dd> <?php echo ($agent->getDateDebut())?$agent->getDateDebut()->format('d/m/Y'):'---'; ?> </dd>
                <dt> Date de fin </dt>
                    <dd> <?php echo ($agent->getDateFin())?$agent->getDateFin()->format('d/m/Y'):'---'; ?> </dd>
            </dl>
        <?php endif; ?>



        <?php if($agent && ! $agent->getMissionsComplementaires()->isEmpty()) : ?>

            <h3> Missions complémentaires </h3>
            <ul>
            <?php foreach ($agent->getMissionsComplementaires() as $mission) : ?>
                <li> <?php echo $mission; ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h2> Environnement du poste de travail dans l'organisation </h2>
            </div>
            <div class="col-md-4">
                <?php if($canAssocierAgent) : ?>
                    <a href="" class="btn btn-primary action">
                        <i class="fas fa-plus-circle"></i>
                        Associer un poste
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">

        <div>
            <h3> Affectation du poste </h3>
            <?php if ($fiche->getAffectation() !== null) : ?>
                <?php if ($fiche->getAffectation()->getDescription() !== null) :?>
                    <?php echo $fiche->getAffectation()->getDescription(); ?>
                <?php else: ?>
                    <div class="alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i>
                        Aucune description de fournie pour l'affectation <em><?php echo $fiche->getAffectation()->getLibelle(); ?></em>.
                    </div>
                <?php endif; ?>
            <?php else : ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucune affectation de renseignée.
                </div>
            <?php endif; ?>
        </div>

        <div>
            <h3> Positionnement dans l'établissement</h3>
            <?php if ($fiche->getPoste() === null) : ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucun poste n'est attaché à ce poste
                </div>
            <?php else: ?>
                <?php echo $this->poste()->render($fiche->getPoste()); ?>
            <?php endif; ?>

        </div>







    </div>
</div>

<!-- FICHE METIER TYPE ------------------------------------------------------------------------------------------------>
<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h2> Description de la fiche métier type </h2>
            </div>
            <div class="col-md-4">
                <?php if($canAssocierMetierType) : ?>
                    <a href="<?php echo $this->url('fiche-metier/associer-metier-type',['fiche' => $fiche->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="modification"
                    >
                        <i class="fas fa-plus-circle"></i>
                        Associer un metier type
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <?php if ($fiche->getMetierType() === null): ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucune fiche de métier type d'associée à ce poste
            </div>
        <?php else: ?>
            <div>

            <h3> Libelle du métier type </h3>

                <?php echo $fiche->getMetierType()->getMetier()->getLibelle(); ?>

            <h3> Mission principale </h3>

           <?php echo $fiche->getMetierType()->getMissionsPrincipales(); ?>

            <h3> Activités associées </h3>

                <?php foreach($activites as $activite) : ?>
                    <h4>
                        <?php echo $activite->getActivite()->getLibelle(); ?>
                    </h4>
                    <?php echo $activite->getActivite()->getDescription(); ?>
                <?php endforeach; ?>

            </div>
            <div>
                <h3> Parcours de formation de base pour la prise de poste </h3>

                    <div class="row">
                        <div class="col-md-4">
                            <h4> Compétences principales </h4>
                        </div>
                        <div class="col-md-4">
                            <h4> Accompagnement à la prise de poste </h4>
                        </div>
                        <div class="col-md-4">
                            <h4> Lien vers le référentiel </h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <h5> Savoir & connaissances </h5>

                            <ul>
                                <li> Connaître </li>
                                <li> Savoir </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h5> Lien vers le plan de formation </h5>

                            <ul>
                                <li> Décrouvrir </li>
                            </ul>
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <h5> Savoir-faire & compétences opérationnelles </h5>

                            <ul>
                                <li> Conduire des projets </li>
                                <li> Maîtriser les outils </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h5> Applications </h5>

                            <ul>
                                <li> redmine </li>
                                <li> Zimbra </li>
                            </ul>
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <h5> Savoir être & compétences comportementales </h5>

                            <ul>
                                <li> Encadrer </li>
                                <li> Prévenir </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h5> Lien vers le plan de formation </h5>

                            <ul>
                                <li> Former </li>
                            </ul>
                        </div>
                        <div class="col-md-4">

                        </div>
                    </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<!-- SPECIFICITE DU POSTE --------------------------------------------------------------------------------------------->
<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h2> Spécificité du poste </h2>
            </div>
            <div class="col-md-4">
                <?php if($canEditerSpecificte) : ?>
                    <a href="<?php echo $this->url('fiche-metier/specificite',['fiche' => $fiche->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="modification"
                    >
                        <i class="fas fa-plus-circle"></i>
                        Renseigner les spécificité
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <?php if ($fiche->getSpecificite() === null) : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucune spécificité attachée à ce poste.
            </div>
        <?php else: ?>
            <?php echo $this->specificitePoste()->render($fiche->getSpecificite()); ?>
        <?php endif; ?>
    </div>
</div>



<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

</script>