<?php

/**
 * @var FicheMetier $fiche
 * @var FicheMetierTypeActivite[] $activites
 * @var SpecificitePoste $specificite
 */

use Application\Entity\Db\Application;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FicheMetierTypeActivite;
use Application\Entity\Db\SpecificitePoste;
use Application\Provider\Privilege\FicheMetierPrivileges;

$canAssocierAgent = true;
$canAssocierMetierType = true;

$canEditerSpecificte = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::EDITER));
$canEditer = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::EDITER));
?>

<style>
    a.action {width: 18em;}
</style>

<h1 class="page-header">
    Fiche métier : <?php echo $fiche->getLibelle(); ?> <br/>
</h1>


<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2> Agent occupant le poste </h2>
            </div>
            <div class="col-md-3">
                <?php if($canAssocierAgent) : ?>
                    <a href="<?php echo $this->url('fiche-metier/associer-agent',['fiche' => $fiche->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="modification"
                    >
                        <i class="fas fa-plus-circle"></i>
                        Associer un agent
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-md-3">
                <?php if($canAssocierAgent) : ?>
                    <a href="<?php echo $this->url('agent/ajouter',[], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="modification"
                    >
                        <i class="fas fa-plus"></i>
                        Ajouter un agent
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="panel-body">


        <?php $agent = $fiche->getAgent(); ?>

        <?php if($agent === null) : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucun agent d'associé à ce poste
            </div>
        <?php else : ?>
            <?php echo $this->agent()->render($agent); ?>
        <?php endif; ?>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2> Environnement du poste de travail </h2>
            </div>
            <div class="col-md-3">
                <?php if($canAssocierAgent) : ?>
                    <a href="<?php echo $this->url('fiche-metier/associer-poste',['fiche' => $fiche->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="modification"
                    >
                        <i class="fas fa-plus-circle"></i>
                        Associer un poste
                    </a>
                <?php endif; ?>
            </div>
            <div class="col-md-3">
                <?php if($canAssocierAgent) : ?>
                    <a href="<?php echo $this->url('poste/ajouter',[], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="modification"
                    >
                        <i class="fas fa-plus"></i>
                        Ajouter un poste
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
            <h3> Affectation du poste </h3>
            <?php if ($fiche->getPoste() !== null && $fiche->getPoste()->getStructure() !== null) : ?>
                <?php if ($fiche->getPoste()->getStructure()->getDescription() !== null) :?>
                    <?php echo $fiche->getPoste()->getStructure()->getDescription(); ?>
                <?php else: ?>
                    <div class="alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i>
                        Aucune description de fournie pour l'affectation <em><?php echo $fiche->getPoste()->getStructure()->getLibelleCourt(); ?></em>.
                    </div>
                <?php endif; ?>
            <?php else : ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucune affectation de renseignée.
                </div>
            <?php endif; ?>

            <h3> Positionnement dans l'établissement</h3>
            <?php if ($fiche->getPoste() === null) : ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucun poste n'est attaché à ce poste
                </div>
            <?php else: ?>
                <?php echo $this->poste()->render($fiche->getPoste()); ?>
            <?php endif; ?>
    </div>
</div>

<!-- FICHES TYPES ----------------------------------------------------------------------------------------------------->
<?php /** @var \Application\Entity\Db\FicheTypeExterne $ficheType **/ ?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Fiche composée de <?php echo count($fiche->getFichesTypes()); ?> fiche(s) type(s).</h2>
        <ul>
            <?php foreach ($fiche->getFichesTypes() as $ficheType) : ?>
                <li> <?php echo $ficheType->getFicheType()->getMetier(); ?> à <?php echo $ficheType->getQuotite(); ?>% </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<?php foreach ($fiche->getFichesTypes() as $ficheType) : ?>
<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2> <?php echo $ficheType->getFicheType()->getMetier(); ?> </h2>
            </div>
            <div class="col-md-3 pull-right">
                <?php if ($ficheType->getPrincipale()) :?>
                    <strong>fiche type principale</strong>
                <?php else : ?>
                    <?php echo $ficheType->getQuotite(); ?>%
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <!-- MISSIONS PRINCIPALES -->
        <?php if($ficheType->getPrincipale()): ?>
            <h3> Missions principales </h3>
            <?php echo $ficheType->getFicheType()->getMissionsPrincipales(); ?>
        <?php endif; ?>

        <!-- FORMATION -->
        <?php if($ficheType->getPrincipale()): ?>
            <h3> Parcours de formation de base pour la prise de poste  </h3>
            <div class="row">
                <div class="col-md-6">
                    <h4> Connaissances </h4>
                    <?php echo $ficheType->getFicheType()->getConnaissances(); ?>
                </div>
                <div class="col-md-6">
                    <h4> Plan de formation </h4>
                    <?php echo$ficheType->getFicheType()->getConnaissancesFormation(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4> Compétences opérationnelles </h4>
                    <?php echo $ficheType->getFicheType()->getCompetencesOperationnelles(); ?>
                </div>
                <div class="col-md-6">
                    <h4> Plan de formation </h4>
                    <?php echo $ficheType->getFicheType()->getCompetencesOperationnellesFormation(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4> Compétences comportementales </h4>
                    <?php echo $ficheType->getFicheType()->getCompetencesComportementales(); ?>
                </div>
                <div class="col-md-6">
                    <h4> Plan de formation </h4>
                    <?php echo $ficheType->getFicheType()->getCompetencesComportementalesFormation(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4> Applications </h4>
                    <ul>
                        <?php /** @var Application $application */ ?>
                        <?php foreach($ficheType->getFicheType()->getApplications() as $application) : ?>
                            <li> <?php echo $application->getLibelle(); ?> </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="col-md-6">
                    <h4> Plan de formation </h4>
                    <?php echo $ficheType->getFicheType()->getApplicationsFormation(); ?>
                </div>
            </div>
        <?php endif; ?>

        <!-- ACTIVITE -->
        <h3> Activités </h3>
        <?php $activites = explode(";", $ficheType->getActivites()); ?>
        <?php foreach ($activites as $activite): ?>
            <p><?php echo $activite; ?></p>
        <?php endforeach; ?>
        <!--        --><?php //foreach($ficheType->getFicheType()->getActivites() as $activite) : ?>
        <!--            --><?php //if (array_search($activite, $activites)) : ?>
        <!--                <h4>-->
        <!--                    --><?php //echo $activite->getActivite()->getLibelle(); ?>
        <!--                </h4>-->
        <!--                --><?php //echo $activite->getActivite()->getDescription(); ?>
        <!--            --><?php //endif; ?>
        <!--        --><?php //endforeach; ?>
    </div>
</div>

<?php endforeach; ?>


<!-- SPECIFICITE DU POSTE --------------------------------------------------------------------------------------------->
<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h2> Spécificité du poste </h2>
            </div>
            <div class="col-md-4">
                <?php if($canEditerSpecificte) : ?>
                    <a href="<?php echo $this->url('fiche-metier/specificite',['fiche' => $fiche->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal"
                       data-event="modification"
                    >
                        <i class="fas fa-plus-circle"></i>
                        Renseigner les spécificités
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <?php if ($fiche->getSpecificite() === null) : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucune spécificité attachée à ce poste.
            </div>
        <?php else: ?>
            <?php echo $this->specificitePoste()->render($fiche->getSpecificite()); ?>
        <?php endif; ?>
    </div>
</div>



<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>