<?php

/**
 * @see \Application\Controller\FicheMetierController::afficherApplications()
 * @var FicheMetier $fichemetier
 * @var ApplicationElement[] $applications
 */

use Element\Entity\Db\ApplicationElement;
use FicheMetier\Entity\Db\FicheMetier;

?>

<div class="card-body">
    <?php echo $this->applicationBloc($applications, $fichemetier,
        ['display' => ['titre' => false, 'validation' => false, 'raison' => false],
            'actions' => ['modifier' => false, 'supprimer' => false, 'valider' => false]]); ?>
</div>
