<?php

/**
 * @see FicheMetierController::afficherAction()
 * @var FicheMetier $fiche
 * @var ParcoursDeFormation $parcours
 * @var array $applications
 */

use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\ParcoursDeFormation;

$libelle = ($fiche->getMetier())?$fiche->getMetier()->getLibelle():"Aucun libellé";
$this->headTitle('Affichage de la fiche métier #' . $fiche->getId(). " : " . $libelle);
?>

<?php
    echo $this->ficheMetier($fiche, null, ['mode' => 'affichage', 'parcours' => $parcours, 'applications' => $applications]);
?>

