<?php

use Application\Form\FicheMetier\ActiviteExistanteForm;

/**
 * @see \Application\Controller\FicheMetierController::ajouterActiviteExistanteAction()
 * @var ActiviteExistanteForm $form
 * @var array $options
 */

?>

<div>
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formControlGroup($form->get('activite')); ?>
    <?php echo $this->formControlGroup($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>

<hr/>

<div id="none" class="preview">
    Aucune prévisualisation.
</div>

<?php foreach ($options as $key => $infos) :?>
    <div class="preview" style='display:none;' id="<?php echo $key;?>">
        <div class="activite">
            <h3><?php echo $infos["title"]; ?></h3>
            <?php echo $infos["description"]; ?>
        </div>
    </div>
<?php endforeach; ?>

<script>
    $(function() {
        $("select#activite").change(function () {
            let text = $("select#activite option:selected").val();
            $("div.preview").hide();
            if (text.length > 0) {
                $("div#" + text).show();
            } else {
                $("div#none").show();
            }
        });
    });

    $('select.bootstrap-selectpicker').selectpicker();
</script>
