<?php

use Application\Controller\FicheMetierController;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\ParcoursDeFormation;

/**
 * @see FicheMetierController::editerAction()
 * @var FicheMetier $fiche
 * @var array $competences
 * @var array $applications
 * @var ParcoursDeFormation $parcours
 */

$libelle = ($fiche->getMetier())?$fiche->getMetier()->getLibelle():"Aucun libellé";
$this->headTitle('Modification de la fiche métier #' . $fiche->getId(). " : " . $libelle);

echo $this->ficheMetier($fiche, null, ['mode' => 'edition-fiche-metier', 'competences' => $competences, 'applications' => $applications, 'parcours' => $parcours]);
