<?php

/**
 * @var FicheMetier[] $fichesMetiers
 */

use Application\Entity\Db\FicheMetier;
use Application\Provider\Privilege\FicheMetierPrivileges;

$this->headTitle("Index des fiches métiers");

$canAjouter         = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::AJOUTER));
$canVoir            = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::AFFICHER));
$canHistoriser      = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::HISTORISER));
?>

<h1 class="page-header">
    Index des fiches métiers
    <span class="badge"><?php echo count($fichesMetiers); ?></span>
</h1>


<div class="main">

    <?php if($canAjouter) : ?>
        <a href="<?php echo $this->url('fiche-metier/creer', [], [], true); ?>"
           class="btn btn-primary action"
        >
            <i class="fas fa-plus-square"></i>
            Ajouter une fiche métier
        </a>
        <br/> <br/>
    <?php endif; ?>


<table class="table table-condensed">
    <thead>
        <tr>
            <th> Id </th>
            <th> Libellé </th>
            <th> Dernière modification </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($fichesMetiers as $ficheMetier) : ?>
        <tr>
            <td> <?php echo $ficheMetier->getId(); ?></td>
            <td> <?php echo $ficheMetier->getLibelle(); ?></td>
            <td> <?php echo $ficheMetier->getHistoModification()->format('H:i:s d/m/Y'); ?></td>
            <td>
                <?php if ($canVoir) : ?>
                    <a href="<?php echo $this->url('fiche-metier/afficher', ['id' => $ficheMetier->getId()], [], true); ?>"
                       title="Afficher la fiche metier">
                        <i class='fas fa-eye' title='Afficher la fiche'></i>
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($ficheMetier->getHistoDestruction() === null) : ?>
                        <a href="<?php echo $this->url('fiche-metier/historiser', ['id' => $ficheMetier->getId()], [], true); ?>"
                           title="Historiser la fiche metier">
                            <i class='fas fa-trash-alt' title='Historiser la fiche'></i>
                        </a>
                    <?php else : ?>
                        <a href="<?php echo $this->url('fiche-metier/restaurer', ['id' => $ficheMetier->getId()], [], true); ?>"
                           title="Restaurer la fiche metier">
                            <span class="glyphicon glyphicon-leaf"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>