<?php

/**
 * @var FicheMetier[] $fichesMetiers
 */

use Application\Entity\Db\FicheMetier;


$this->headTitle("Index des fiches métiers");

$canVoir = true;
$canHistoriser = true;
?>

<h1 class="page-header">
    Index des fiches métiers
    <span class="badge"><?php echo count($fichesMetiers); ?></span>
</h1>


    <a href=""
       class="btn btn-primary action"
    >
        <span class="glyphicon glyphicon-plus"></span> Ajouter une fiche métier
    </a>

<br/>
<br/>


<table class="table table-condensed">
    <thead>
        <tr>
            <th> Id </th>
            <th> Libellé </th>
            <th> Dernière modification </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($fichesMetiers as $ficheMetier) : ?>
        <tr>
            <td> <?php echo $ficheMetier->getId(); ?></td>
            <td> <?php echo $ficheMetier->getLibelle(); ?></td>
            <td> <?php echo $ficheMetier->getHistoModification()->format('H:i:s d/m/Y'); ?></td>
            <td>
                <?php if ($canVoir) : ?>
                    <a href="<?php echo $this->url('fiche-metier/afficher', ['id' => $ficheMetier->getId()], [], true); ?>"
                       title="Afficher la fiche metier">
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($ficheMetier->getHistoDestruction() === null) : ?>
                        <a href="<?php echo $this->url('fiche-metier/historiser', ['id' => $ficheMetier->getId()], [], true); ?>"
                           title="Historiser la fiche metier">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    <?php else : ?>
                        <a href="<?php echo $this->url('fiche-metier/restaurer', ['id' => $ficheMetier->getId()], [], true); ?>"
                           title="Restaurer la fiche metier">
                            <span class="glyphicon glyphicon-leaf"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>