<?php

/**
 * @see \Application\Controller\FicheMetierController::indexNAction()
 * @var array $dictionnaires
 */

$this->headTitle("Index des fiches métiers");

?>

<h1 class="page-header">
    Index des fiches métiers
</h1>

<table class="table condensed datatable" id="datatable">
    <thead>
        <tr>
            <th> Métier </th>
            <th> Domaine </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($dictionnaires as $entry) : ?>
        <tr class="metier">
            <td> <?php echo $entry['metier']->getLibelle(); ?> </td>
            <td> <ul>
                    <?php foreach ($entry['metier']->getDomaines() as $domaine) : ?>
                        <li> <?php echo $domaine->getLibelle(); ?> </li>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td> <span class="todo">Action</span></td>
        </tr>
        <tr class="fiches">
            <td colspan="3">
                <table class="fiches">
                    <?php foreach ($entry['fiches'] as $fiche) : ?>
                        <tr>
                            <td> Fiche #<?php echo $fiche->getId(); ?></td>
                            <td> <?php echo $fiche->getHistoModification()->format('d/m/Y à H:i'); ?></td>
                            <td> <?php echo $this->etatbadge($fiche->getEtat()); ?></td>
                            <td> <span class="todo">Action</span></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('#datatable').DataTable( {
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );
</script>