<?php

/**
 * @var Agent[] $agents
 */

use Application\Entity\Db\Agent;

?>

<h1>
    Liste des agents enregistrées
</h1>

<div class="main">

<!--    <div class="pull-right">-->
<!--        --><?php //if ($canAjouterRessource) : ?>
<!--            <a-->
<!--                href="--><?php //echo $this->url('ressource-rh/agent-status/creer', [], [], true); ?><!--"-->
<!--                class="btn btn-primary action ajax-modal"-->
<!--                data-event="modification"-->
<!--            >-->
<!--                <i class="fas fa-plus"></i>-->
<!--                Ajouter un status-->
<!--            </a>-->
<!--        --><?php //endif; ?>
<!--    </div>-->

    <?php if (count($agents) > 0) : ?>
        <table class="table table-condensed">
            <thead>
            <tr>
                <th> Numero de poste </th>
                <th> Dénomination </th>
                <th> Corps </th>
                <th class="action"> Action </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($agents as $agent) : ?>
                <tr>
                    <td> <?php echo $agent->getNumeroPoste(); ?> </td>
                    <td> <?php echo $agent->getPrenom(); ?> <?php echo $agent->getNom(); ?></td>
                    <td> <?php echo $agent->getCorps(); ?></td>
                    <td>
<!--                        --><?php //if ($canEditerRessource) : ?>
<!--                            <a href="--><?php //echo $this->url('ressource-rh/agent-status/modifier', ['id' => $statu->getId()], [], true); ?><!--"-->
<!--                               data-event="modification"-->
<!--                               class="ajax-modal"-->
<!--                            >-->
<!--                                <i class="fas fa-pencil-alt" title="Éditer le status"></i>-->
<!--                            </a>-->
<!--                        --><?php //endif; ?>
<!--                        --><?php //if ($canEffacerRessource) : ?>
<!--                            <a href="--><?php //echo $this->url('ressource-rh/agent-status/effacer', ['id' => $statu->getId()], [], true); ?><!--" >-->
<!--                                <i class="fas fa-trash-alt" title="Effacer le status"></i>-->
<!--                            </a>-->
<!--                        --><?php //endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>

</div>

