<?php

/**
 * @var \Application\Entity\Db\FichePoste $ficheMetier
 * @var \Application\Entity\Db\FicheTypeExterne $ficheTypeExterne
 */

$idActivites = explode(";",$ficheTypeExterne->getActivites());
?>

Liste des activités de la fiche type <br/>
<strong><?php echo $ficheTypeExterne->getFicheType()->getMetier(); ?></strong>

<br/><br/>

<form method="post" action="<?php echo $this->url('fiche-metier/selectionner-activite', ['fiche' => $ficheMetier->getId(), 'fiche-type-externe' => $ficheTypeExterne->getId()], [], true); ?>">

    <?php $activites = $ficheTypeExterne->getFicheType()->getActivites() ; ?>
    <?php foreach ($activites as $activite) : ?>
        <div class="form-group">
            <div class="checkbox">
                <label>
                    <input type="checkbox"
                           id="<?php echo $activite->getActivite()->getId(); ?>"
                           name="<?php echo $activite->getActivite()->getId(); ?>"
                           <?php if (array_search($activite->getActivite()->getId(), $idActivites) !== false) echo " checked "; ?>
                    >
                    <?php echo $activite->getActivite()->getLibelle(); ?>
                </label>
            </div>
    <?php endforeach; ?>

    <input type="submit" class="btn btn-primary" value="Valider la sélection">
</form>