<?php

/**
 * @see FormationGroupeController::afficherGroupeAction()
 *
 * @var string $title
 * @var FormationGroupe $groupe
 */

use Formation\Entity\Db\FormationGroupe;

?>

<dl>
    <dt> Libellé </dt>
    <dd> <?php echo $groupe->getLibelle(); ?> </dd>
    <?php if ($groupe->getAxe()) : ?>
        <dt> Axe </dt>
        <dd> <?php echo $groupe->getAxe()->getLibelle(); ?> </dd>
    <?php endif; ?>
    <dt> Dernière modification </dt>
    <dd>
        <?php echo $groupe->getHistoModificateur()->getDisplayName(); ?>
        <br/>
        <?php echo $groupe->getHistoModification()->format('d/m/Y à H:i:s'); ?>
    </dd>
    <dt> Source </dt>
    <dd>
        <?php echo $groupe->getSource(); ?> -
        <?php echo $groupe->getIdSource(); ?>
    </dd>
    <dt>
        Liste des formations
        <span class="badge"> <?php echo count($groupe->getFormations()); ?></span>
    </dt>
    <dd>
        <ul>
            <?php foreach($groupe->getFormations() as $formation) : ?>
                <li> <?php echo $formation->getLibelle(); ?> </li>
            <?php endforeach; ?>
        </ul>
    </dd>
</dl>

