<?php

use Formation\Entity\Db\FormationGroupe;
use Formation\Provider\Privilege\FormationgroupePrivileges;

/**
 * @see \Formation\Controller\FormationGroupeController::indexAction()
 * @var FormationGroupe[] $groupes
 * @var string $historise
 * @var string $source
 */

$canAfficher        = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_AFFICHER));
$canAjouter         = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_AJOUTER));
$canEditer          = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_MODIFIER));
$canHistoriser      = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_HISTORISER));
$canDetruire        = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_SUPPRIMER));

$this->headTitle("Thèmes de formation");
?>

<h1 class="page-header">
    Thèmes de formation
</h1>

<?php if ($canAjouter) : ?>
    <br/>
    <a
        <?php /** @see FormationGroupeController::ajouterGroupeAction() */ ?>
        href="<?php echo $this->url('formation-groupe/ajouter', [], [], true); ?>"
        class="btn btn-primary ajax-modal"
        data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un thème
    </a>
<?php endif; ?>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<table class="datatable table table-condensed table-hover" id="groupes">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> Axe </th>
        <th> Ordre </th>
        <th style="width: 10rem;"> #Formation </th>
        <th style="width: 14rem;"> Source </th>
        <th style="width: 9rem;">  Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($groupes as $groupe) : ?>
        <tr id="<?php echo $groupe->getId(); ?>"  class="<?php if ($groupe->estHistorise()) echo "historise"; ?>">

            <td> <!-- LIBELLE -->
                <?php echo $groupe->getLibelle(); ?>
                <?php if ($groupe->getDescription() !== null) : ?>
                    <span class="icon icon-info" title="<?php echo $groupe->getDescription(); ?>"
                          data-bs-toggle="tooltip" data-bs-html="true">
                    </span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($groupe->getAxe() === null) : ?>
                    <em> Aucun axe associé</em>
                <?php else: ?>
                    <?php echo $groupe->getAxe()->getLibelle(); ?>
                <?php endif; ?>
            </td>
            <td> <!-- ORDRE -->
                <?php echo $groupe->getOrdre(); ?>
            </td>
            <td> <!-- NB FORMATION -->
                <?php echo count($groupe->getFormations()); ?>
            </td>
            <td> <!-- SOURCE -->
                <span class="badge source <?php echo $groupe->getSource(); ?>" id="<?php echo $groupe->getSource(); ?>">
                    <?php echo $groupe->getSource(); ?>
                    <?php echo $groupe->getIdSource(); ?>
                </span>
            </td>
            <td class="action"> <!-- ACTION -->
                <?php if ($canAfficher) : ?>
                    <a  <?php /** @see FormationGroupeController::afficherGroupeAction() */ ?>
                        href="<?php echo $this->url('formation-groupe/afficher', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal">
                        <span class="icon icon-voir" title="Afficher le thème"></span></a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <a
                        <?php /** @see FormationGroupeController::editerGroupeAction() */ ?>
                        href="<?php  echo $this->url('formation-groupe/editer', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon icon-editer" title="Modifier le thème"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($groupe->estNonHistorise()) : ?>
                        <a
                            <?php /** @see FormationGroupeController::historiserGroupeAction() */ ?>
                            href="<?php  echo $this->url('formation-groupe/historiser', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        >
                            <span class="icon icon-historiser" title="Supprimer le thème"></span></a>
                    <?php else : ?>
                        <a
                            <?php /** @see FormationGroupeController::restaurerGroupeAction() */ ?>
                            href="<?php  echo $this->url('formation-groupe/restaurer', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        >
                            <span class="icon icon-restaurer" title="Restaurer le thème"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire AND $groupe->estHistorise()) : ?>
                    <a
                        <?php /** @see FormationGroupeController::detruireGroupeAction() */ ?>
                        href="<?php  echo $this->url('formation-groupe/detruire', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-unchecked text-danger" title="Supprimer définitivement le thème"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
