<?php

use Formation\Entity\Db\FormationGroupe;
use Formation\Provider\Privilege\FormationgroupePrivileges;

/**
 * @see \Formation\Controller\FormationGroupeController::indexAction()
 * @var FormationGroupe[] $groupes
 * @var string $historise
 * @var string $source
 */

$canAfficher        = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_AFFICHER));
$canAjouter         = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_AJOUTER));
$canEditer          = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_MODIFIER));
$canHistoriser      = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_HISTORISER));
$canDetruire        = $this->isAllowed(FormationgroupePrivileges::getResourceId(FormationgroupePrivileges::FORMATIONGROUPE_SUPPRIMER));

?>

<div class="row">
    <div class="col-md-8">
        <h2 class="page-header">
            Groupes des formations
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouter) : ?>
            <br/>
            <a
                <?php /** @see FormationGroupeController::ajouterGroupeAction() */ ?>
                href="<?php echo $this->url('formation-groupe/ajouter', [], [], true); ?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification">
                <span class="icon ajouter"></span>
                Ajouter un groupe
            </a>
        <?php endif; ?>
    </div>
</div>

<?php echo $this->partial('partial/filtre',['historise' => $historise, 'source' => $source], [], true); ?>

<table class="datatable table table-condensed table-hover" id="groupes">
    <thead>
    <tr>
        <th> Libellé </th>
        <th style="width: 12rem;"> #Formation </th>
        <th style="width: 12rem;"> Source </th>
        <th style="width: 12rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($groupes as $groupe) : ?>
        <tr id="<?php echo $groupe->getId(); ?>"  class="<?php if ($groupe->estHistorise()) echo "historise"; ?>">
            <td> <?php echo $groupe->getLibelle(); ?> </td>
            <td> <?php echo count($groupe->getFormations()); ?> </td>
            <td> <span class="badge source <?php echo $groupe->getSource(); ?>" id="<?php echo $groupe->getSource(); ?>"><?php echo $groupe->getSource(); ?></span> </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <a  <?php /** @see FormationGroupeController::afficherGroupeAction() */ ?>
                        href="<?php echo $this->url('formation-groupe/afficher', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal">
                        <span class="icon voir" title="Afficher le groupe"></span></a>
                <?php else : ?>
                    <span class="icon voir" style="color:lightgrey;"></span>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <a
                        <?php /** @see FormationGroupeController::editerGroupeAction() */ ?>
                        href="<?php  echo $this->url('formation-groupe/editer', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon editer" title="Modifier le groupe"></span></a>
                <?php else : ?>
                    <span class="icon editer" style="color:lightgrey;"></span>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($groupe->estNonHistorise()) : ?>
                        <a
                            <?php /** @see FormationGroupeController::historiserGroupeAction() */ ?>
                            href="<?php  echo $this->url('formation-groupe/historiser', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser le groupe"></span></a>
                    <?php else : ?>

                        <a
                            <?php /** @see FormationGroupeController::restaurerGroupeAction() */ ?>
                            href="<?php  echo $this->url('formation-groupe/restaurer', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer le groupe"></span></a>
                    <?php endif; ?>
                <?php else : ?>
                    <?php if ($groupe->estNonHistorise()) : ?>
                        <span class="icon historiser" style="color:lightgrey;"></span>
                    <?php else : ?>
                        <span class="icon restaurer" style="color:lightgrey;"></span>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <a
                        <?php /** @see FormationGroupeController::detruireGroupeAction() */ ?>
                        href="<?php  echo $this->url('formation-groupe/detruire', ['formation-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire" title="Afficher le groupe"></span></a>
                <?php else : ?>
                    <span class="icon detruire" style="color:lightgrey;"></span>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
