<?php

use Formation\Entity\Db\StagiaireExterne;
use Formation\Provider\Privilege\StagiaireexternePrivileges;

/**
 * @see \Formation\Controller\StagiaireExterneController::indexAction()
 * @var StagiaireExterne[] $stagiaires
 */

$this->headTitle("Stagiaires externes");

$canAfficher = $this->isAllowed(StagiaireexternePrivileges::getResourceId(StagiaireexternePrivileges::STAGIAIREEXTERNE_AFFICHER));
$canAjouter = $this->isAllowed(StagiaireexternePrivileges::getResourceId(StagiaireexternePrivileges::STAGIAIREEXTERNE_AJOUTER));
$canModifier = $this->isAllowed(StagiaireexternePrivileges::getResourceId(StagiaireexternePrivileges::STAGIAIREEXTERNE_MODIFIER));
$canHistoriser = $this->isAllowed(StagiaireexternePrivileges::getResourceId(StagiaireexternePrivileges::STAGIAIREEXTERNE_HISTORISER));
$canSupprimer = $this->isAllowed(StagiaireexternePrivileges::getResourceId(StagiaireexternePrivileges::STAGIAIREEXTERNE_SUPPRIMER));
?>

<h1 class="page-header">
    Stagiaires externes
</h1>

<?php /** @see \Formation\Controller\StagiaireExterneController::ajouterAction() */ ?>
<a href="<?php echo $this->url('stagiaire-externe/ajouter', [], [], true); ?>"
   class="btn btn-primary ajax-modal" data-event="modification">
    <span class="icon icon-ajouter"></span>
    Ajouter un·e stagiaire
</a>

<table class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Dénomination </th>
        <th> Structure </th>
        <th> Adresse électronique </th>
        <th> Compte </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($stagiaires as $stagiaire): ?>
        <?php if ($canSupprimer OR $stagiaire->estNonHistorise()) : ?>
            <tr class="<?php if ($stagiaire->estHistorise()) echo " historise "; ?>">
            <td data-order="<?php echo $stagiaire->getNom()."|".$stagiaire->getPrenom(); ?>">
                <?php echo $stagiaire->getPrenom(); ?>
                <?php echo $stagiaire->getNom(); ?>
            </td>
            <td>
                <?php if ($stagiaire->getStructure()) : ?>
                    <?php echo $stagiaire->getStructure(); ?>
                <?php else : ?>
                    <em> Aucune structure connue</em>
                <?php endif; ?>
            </td>
            <td>
                <?php echo $stagiaire->getEmail(); ?>
            </td>
            <td>
                <?php if ($stagiaire->getLogin()) : ?>
                    <?php echo $stagiaire->getLogin(); ?>
                <?php else:  ?>
                    <em> Aucun compte associé</em>
                <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Formation\Controller\StagiaireExterneController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('stagiaire-externe/afficher', ['stagiaire-externe' => $stagiaire->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                        <span class="icon icon-voir"></span> Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \Formation\Controller\StagiaireExterneController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('stagiaire-externe/modifier', ['stagiaire-externe' => $stagiaire->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span> Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                <br>
                    <?php if ($stagiaire->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\StagiaireExterneController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('stagiaire-externe/historiser', ['stagiaire-externe' => $stagiaire->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification">
                            <span class="icon icon-historiser"></span> Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Formation\Controller\StagiaireExterneController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('stagiaire-externe/restaurer', ['stagiaire-externe' => $stagiaire->getId()], [], true); ?>"
                        >
                            <span class="icon icon-restaurer"></span> Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php /** @see \Formation\Controller\StagiaireExterneController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('stagiaire-externe/supprimer', ['stagiaire-externe' => $stagiaire->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span> Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('.datatable').DataTable({
            paging: false,
        });
    });
</script>
