<?php

/**
 * @see \UnicaenDocument\Controller\ContenuController::indexAction()
 * @var Content[] $contenus
 */

use UnicaenDocument\Entity\Db\Content;
use UnicaenDocument\Provider\Privilege\DocumentcontentPrivileges;

$canAjouter    = $this->isAllowed(DocumentcontentPrivileges::getResourceId(DocumentcontentPrivileges::DOCUMENTCONTENU_AJOUTER));
$canAfficher   = $this->isAllowed(DocumentcontentPrivileges::getResourceId(DocumentcontentPrivileges::DOCUMENTCONTENU_INDEX));
$canModifier   = $this->isAllowed(DocumentcontentPrivileges::getResourceId(DocumentcontentPrivileges::DOCUMENTCONTENU_MODIFIER));
$canHistoriser = $this->isAllowed(DocumentcontentPrivileges::getResourceId(DocumentcontentPrivileges::DOCUMENTCONTENU_HISTORISER));
$canDetruire   = $this->isAllowed(DocumentcontentPrivileges::getResourceId(DocumentcontentPrivileges::DOCUMENTCONTENU_SUPPRIMER));

$this->headTitle("Index des contenus");
?>

<h1 class="page-header">
    Index des contenus
</h1>

<div class="main">

    <?php if ($canAjouter) : ?>
        <a href="<?php echo $this->url('contenu/contenu/ajouter', [], [], true); ?>"
           class="btn btn-primary action ajax-modal" data-event="modification">
            <span class="icon ajouter"></span>
            Ajouter un contenu
        </a>
    <?php endif; ?>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th> Code </th>
                <th> Type </th>
                <th> Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($contenus as $contenu) : ?>
                <tr>
                    <td>
                        <?php echo $contenu->getCode(); ?>
                        <?php if ($contenu->getDescription() !== null) : ?>
                            <span class="icon information" title="<?php echo $contenu->getDescription(); ?>"></span>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php echo $contenu->getType(); ?>
                    </td>
                    <td>
                        <?php if ($canAfficher) : ?>
                            <a href="<?php echo $this->url('contenu/contenu/afficher', ['contenu' => $contenu->getId()], [], true); ?>"
                               class="ajax-modal"
                            >
                                <span class="icon voir"></span></a>
                        <?php endif; ?>
                        <?php if ($canModifier) : ?>
                            <a href="<?php echo $this->url('contenu/contenu/modifier', ['contenu' => $contenu->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification"
                            >
                                <span class="icon editer"></span></a>
                        <?php endif; ?>
                        <?php if ($canHistoriser) : ?>
                            <?php if ($contenu->estNonHistorise()) : ?>
                                <a href="<?php echo $this->url('contenu/contenu/historiser', ['contenu' => $contenu->getId()], [], true); ?>"
                                >
                                    <span class="icon historiser"></span></a>
                            <?php else : ?>
                                <a href="<?php echo $this->url('contenu/contenu/restaurer', ['contenu' => $contenu->getId()], [], true); ?>"
                                >
                                    <span class="icon restaurer"></span></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canDetruire) : ?>
                            <a href="<?php echo $this->url('contenu/contenu/detruire', ['contenu' => $contenu->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification"
                            >
                                <span class="icon detruire"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>