<?php

/**
 * @see \Carriere\Controller\NiveauFonctionController::indexAction()
 * @var NiveauFonction[] $niveauxFonctions
 * @var NiveauFonctionService $service
 */

use Carriere\Entity\Db\NiveauFonction;
use Carriere\Provider\Privilege\NiveaufonctionPrivileges;
use Carriere\Service\NiveauFonction\NiveauFonctionService;

$this->headTitle("Niveau de fonction");

$canAfficher = $this->isAllowed(NiveaufonctionPrivileges::getResourceId(NiveaufonctionPrivileges::NIVEAUFONCTION_AFFICHER));
$canAjouter = $this->isAllowed(NiveaufonctionPrivileges::getResourceId(NiveaufonctionPrivileges::NIVEAUFONCTION_AJOUTER));
$canModifier = $this->isAllowed(NiveaufonctionPrivileges::getResourceId(NiveaufonctionPrivileges::NIVEAUFONCTION_MODIFIER));
$canHistoriser = $this->isAllowed(NiveaufonctionPrivileges::getResourceId(NiveaufonctionPrivileges::NIVEAUFONCTION_HISTORISER));
$canSupprimer = $this->isAllowed(NiveaufonctionPrivileges::getResourceId(NiveaufonctionPrivileges::NIVEAUFONCTION_SUPPRIMER));

?>

<h1 class="page-header">
    Codes Fonctions
</h1>

<?php if ($canAjouter) : ?>
    <?php /** @see \Carriere\Controller\NiveauFonctionController::indexAction() */ ?>
    <a href="<?php echo $this->url('niveau-fonction/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un niveau de fonction
    </a>
<?php endif; ?>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<table class="table table-condensed" id="niveauxfonctions">
    <thead>
    <tr>
        <th class="col-md-2"> Code</th>
        <th class="col-md-8"> Libellé</th>
        <th class="col-md-2 action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($niveauxFonctions as $niveauFonction) : ?>
        <tr <?php if ($niveauFonction->estHistorise()) echo ' class="historise" '; ?> >
            <td data-column-id="Code"> <?php echo $niveauFonction->getCode(); ?> </td>
            <td data-column-id="Libellé">
                <?php echo $niveauFonction->getLibelle(); ?>
                <?php if ($niveauFonction->getDescription()) : ?>
                    <span class="icon icon-info" title="<?php echo $niveauFonction->getDescription(); ?>"
                          data-bs-toggle="tooltip" data-bs-html="true"></span>
                <?php endif; ?>
            </td>
            <td class="action" data-column-id="Action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Carriere\Controller\NiveauFonctionController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('niveau-fonction/afficher', ['niveau-fonction' => $niveauFonction->getId()], [], true); ?>"
                       class="action secondary ajax-modal">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \Carriere\Controller\NiveauFonctionController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('niveau-fonction/modifier', ['niveau-fonction' => $niveauFonction->getId()], [], true); ?>"
                       class="action primary ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($niveauFonction->estNonHistorise()) : ?>
                        <?php /** @see \Carriere\Controller\NiveauFonctionController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('niveau-fonction/historiser', ['niveau-fonction' => $niveauFonction->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Carriere\Controller\NiveauFonctionController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('niveau-fonction/restaurer', ['niveau-fonction' => $niveauFonction->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \Carriere\Controller\NiveauFonctionController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('niveau-fonction/supprimer', ['niveau-fonction' => $niveauFonction->getId()], [], true); ?>"
                       class="action danger ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $("body").on("modification", function (event) {
        event.div.modal('hide');
        window.location.reload();
    });

    $(function () {
        $('table#niveauxfonctions').DataTable({
            autoWidth: false,
            paging: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [2], orderable: false}
            ]
        });
    });
</script>