<?php

/**
 * @see \Element\Controller\CompetenceThemeController::indexAction()
 * @var CompetenceTheme[] $themes;
 */

use Element\Entity\Db\CompetenceTheme;
use Element\Provider\Privilege\CompetencePrivileges;
use Element\Provider\Privilege\CompetencethemePrivileges;
use Element\Provider\Privilege\CompetencetypePrivileges;

$this->headTitle("Liste des thèmes de compétence");

$canCompetenceIndex = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_INDEX));
$canCompetenceTypeIndex = $this->isAllowed(CompetencetypePrivileges::getResourceId(CompetencetypePrivileges::COMPETENCETYPE_INDEX));

$canAfficher = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_AFFICHER));
$canModifier = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_MODIFIER));
$canAjouter = $canModifier;
$canHistoriser = $canModifier;
$canDetruire = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_EFFACER));
?>

<h1 class="page-header">
    Liste des thèmes de compétences
</h1>

<div class="row">
    <div class="col-md-6">
        <?php if ($canAjouter) : ?>
            <a href="<?php echo $this->url('element/competence-theme/ajouter', [], [], true); ?>"
               class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un thème
            </a>
        <?php endif; ?>
    </div>
    <div class="pull-right">
        <?php if ($canCompetenceIndex) : ?>
            <a href="<?php echo $this->url('element/competence', [], [], true); ?>" class="btn btn-primary">
                <span class="icon acceder"></span>
                Accéder aux compétences</a>
        <?php endif; ?>

        <?php if ($canCompetenceTypeIndex) : ?>
            <a href="<?php echo $this->url('element/competence-type', [], [], true); ?>" class="btn btn-primary">
                <span class="icon acceder"></span>
                Accéder aux types</a>
        <?php endif; ?>
    </div>
</div>

<table class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th style="width:75%;"> Libellé </th>
        <th> #Compétence </th>
        <th style="width:11rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($themes as $theme) : ?>
        <tr class="<?php if ($theme->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $theme->getLibelle(); ?> </td>
            <td> <?php echo count($theme->getCompetences()); ?> </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <?php /** @see CompetenceController::afficherCompetenceThemeAction() */ ?>
                    <a href="<?php echo $this->url('element/competence-theme/afficher', ['competence-theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal">
                        <span class="icon icon-voir" title="Afficher le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                <?php else : ?>
                    <span class="icon icon-voir" style="color: lightgrey"></span>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <?php /** @see CompetenceController::modifierCompetenceThemeAction() */ ?>
                    <a href="<?php echo $this->url('element/competence-theme/modifier', ['competence-theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-editer" title="Modifier le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                <?php else : ?>
                    <span class="icon icon-editer" style="color: lightgrey"></span>
                <?php endif; ?>
                <?php if ($canHistoriser): ?>
                    <?php if($theme->estNonHistorise()) : ?>
                        <?php /** @see CompetenceController::historiserCompetenceThemeAction() */?>
                        <a href="<?php echo $this->url('element/competence-theme/historiser', ['competence-theme' => $theme->getId()], [], true); ?>">
                            <span class="icon icon-historiser" title="Historiser le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                    <?php else : ?>
                        <?php /** @see CompetenceController::restaurerCompetenceThemeAction() */?>
                        <a href="<?php echo $this->url('element/competence-theme/restaurer', ['competence-theme' => $theme->getId()], [], true); ?>">
                            <span class="icon icon-restaurer" title="Restaurer le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                    <?php endif; ?>
                <?php else: ?>
                    <?php if($theme->estNonHistorise()) : ?>
                        <span class="icon icon-historiser" style="color:lightgray;"></span>
                    <?php else : ?>
                        <span class="icon icon-restaurer" style="color:lightgray;"></span>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <?php /** @see CompetenceController::detruireCompetenceThemeAction() */ ?>
                    <a href="<?php echo $this->url('element/competence-theme/detruire', ['competence-theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-retirer" title="Supprimer le thème de compétence [<?php echo $theme->getLibelle(); ?>]"></span></a>
                <?php else : ?>
                    <span class="icon icon-retirer" style="color: lightgrey"></span>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>