<?php

/**
 * @see \Element\Controller\CompetenceThemeController::indexAction()
 * @var CompetenceTheme[] $themes;
 */

use Element\Entity\Db\CompetenceTheme;
use Element\Provider\Privilege\CompetencedisciplinePrivileges;
use Element\Provider\Privilege\CompetencePrivileges;
use Element\Provider\Privilege\CompetencereferentielPrivileges;
use Element\Provider\Privilege\CompetencethemePrivileges;
use Element\Provider\Privilege\CompetencetypePrivileges;

$this->headTitle("Thèmes associés aux compétences");

$canCompetenceIndex = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_INDEX));
$canCompetenceDisciplineIndex = $this->isAllowed(CompetencedisciplinePrivileges::getResourceId(CompetencedisciplinePrivileges::COMPETENCEDISCIPLINE_INDEX));
$canCompetenceTypeIndex = $this->isAllowed(CompetencetypePrivileges::getResourceId(CompetencetypePrivileges::COMPETENCETYPE_INDEX));
$canCompetenceReferentielIndex = $this->isAllowed(CompetencereferentielPrivileges::getResourceId(CompetencereferentielPrivileges::COMPETENCEREFERENTIEL_INDEX));

$canAfficher    = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_AFFICHER));
$canAjouter     = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_AJOUTER));
$canModifier    = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_MODIFIER));
$canHistoriser  = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_HISTORISER));
$canDetruire    = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_EFFACER));

$canAction = ($canAfficher OR $canModifier OR $canHistoriser OR $canDetruire);
?>

<h1 class="page-header">
    Thèmes associés aux compétences
</h1>

<div class="row">
    <div class="col-md-6">
        <?php if ($canAjouter) : ?>
            <?php /** @see \Element\Controller\CompetenceThemeController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('element/competence-theme/ajouter', [], [], true); ?>"
               class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un thème
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <?php if ($canCompetenceIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceController::listingAction() */ ?>
            <a href="<?php echo $this->url('element/competence/listing', [], [], true); ?>" class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux compétences</a>
        <?php endif; ?>

        <?php if ($canCompetenceDisciplineIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceDisciplineController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-discipline', [], [], true); ?>"
               class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux disciplines</a>
        <?php endif; ?>

        <?php if ($canCompetenceTypeIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceTypeController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-type', [], [], true); ?>" class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux types</a>
        <?php endif; ?>

        <?php if ($canCompetenceReferentielIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceReferentielController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-referentiel', [], [], true); ?>"
               class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux référentiels</a>
        <?php endif; ?>
    </div>
</div>

<table class="table table-condensed table-hover">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> #Compétence </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($themes as $theme) : ?>
        <tr class="<?php if ($theme->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $theme->getLibelle(); ?> </td>
            <td> <?php echo count($theme->getCompetences()); ?> </td>
            <?php if ($canAction) : ?>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Element\Controller\CompetenceThemeController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('element/competence-theme/afficher', ['competence-theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal action secondary">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \Element\Controller\CompetenceThemeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('element/competence-theme/modifier', ['competence-theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal action primary" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser): ?>
                    <br>
                    <?php if($theme->estNonHistorise()) : ?>
                        <?php /** @see \Element\Controller\CompetenceThemeController::historiserAction() */?>
                        <a href="<?php echo $this->url('element/competence-theme/historiser', ['competence-theme' => $theme->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Element\Controller\CompetenceThemeController::restaurerAction() */?>
                        <a href="<?php echo $this->url('element/competence-theme/restaurer', ['competence-theme' => $theme->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <br>
                    <?php /** @see \Element\Controller\CompetenceThemeController::detruireAction() */?>
                    <a href="<?php echo $this->url('element/competence-theme/detruire', ['competence-theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal action danger" data-event="modification">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>