
<div class="jumbotron" style="border:2px solid black;">
<h1 style="color:darkred;">
    Erreur 403 : Accès interdit
</h1>

<p class="error">
    <strong>Vous n'êtes pas habilité·e à accéder à cette page.</strong>
</p>

<div style="font-size: 21px; font-weight: 200;">
Résolution possible :
<ul>
    <li> vérifiez que vous êtes bien authentifié·e ;</li>
    <li> vérifiez que vous incarnez un rôle permettant d'accéder à cette page. </li>
</ul>

Si le problème persiste, merci de contacter l'assistance d'EMC2 : <a href="mailto:assistance-emc2@unicaen.fr" target="_blank">assistance-emc2@unicaen.fr</a>
</div>
</div>