<?php

/**
 * @see \UnicaenValidation\Controller\IndexController::indexAction()
 */

use UnicaenValidation\Provider\Privilege\ValidationinstancePrivileges;
use UnicaenValidation\Provider\Privilege\ValidationtypePrivileges;

$canAfficherType = $this->isAllowed(ValidationtypePrivileges::getResourceId(ValidationtypePrivileges::VALIDATIONTYPE_AFFICHER));
$canAfficherInstance = $this->isAllowed(ValidationinstancePrivileges::getResourceId(ValidationinstancePrivileges::VALIDATIONINSTANCE_AFFICHER));
?>

<h1 class="page-header">
    Index du module de validation
</h1>

<div class="main">
    <p>
        Module permettabt de gérer les validations et les types de validations.
    </p>

    <?php if ($canAfficherType) : ?>
        <h2> Gestion des types de validation</h2>

        <p> Permet d'ajouter, modifier, historiser et supprimer des type de validation </p>

        <a
            <?php /** @see \UnicaenValidation\Controller\ValidationTypeController::indexAction() */?>
            href="<?php echo $this->url('validation/type', [], [], true); ?>"
            class="btn btn-primary action"
        >
            <span class="icon voir"></span> Voir les types de validation
        </a>
    <?php endif; ?>

    <?php if ($canAfficherInstance) : ?>
        <h2> Gestion des instances de validation</h2>

        <p> Permet d'ajouter, modifier, historiser et supprimer des instances de validation </p>

        <a
            <?php /** @see \UnicaenValidation\Controller\ValidationInstanceController::indexAction() */?>
                href="<?php echo $this->url('validation/instance', [], [], true); ?>"
                class="btn btn-primary action"
        >
            <span class="icon voir"></span> Voir les instances de validation
        </a>
    <?php endif; ?>
</div>
