<?php

/**
 * @var Domaine[] $domaines
 * @var FamilleProfessionnelle[] $familles
 * @var int $domaine
 * @var int $famille
 * @var string $historise
 */

use Metier\Entity\Db\Domaine;
use Metier\Entity\Db\FamilleProfessionnelle;

?>

<div class="card">
    <div class="card-header bg-default">
        <span class="icon icon-filtrer"></span>
        Filtrage de la liste des métiers
    </div>
    <div class="card-body">
        <form id="filter" method="get" action="<?php echo $this->url(); ?>">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="domaine">Domaine d'activité associé : </label>
                            <select id="domaine" name="domaine" class="selectpicker" data-live-search="true">
                                <option value="">Peu importe</option>
                                <?php foreach ($domaines as $domaine_) : ?>
                                    <option value="<?php echo $domaine_->getId(); ?>">  <?php echo $domaine_->getLibelle(); ?> </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="famille">Famille professionnelle associée : </label>
                            <select id="famille" name="famille" class="selectpicker" data-live-search="true">
                                <option value="">Peu importe</option>
                                <?php foreach ($familles as $famille_) : ?>
                                    <option value="<?php echo $famille_->getId(); ?>">  <?php echo $famille_->getLibelle(); ?> </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="historise">Métiers historisés : </label>
                            <select id="historise" name="historise" class="selectpicker">
                                <option value="">Peu importe</option>
                                <option value="1">Oui</option>
                                <option value="0">Non</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <button type="button" id="filter" class="btn btn-primary filter-action">
                        <span class="icon icon-filtrer" aria-hidden="true"></span> Filtrer
                    </button>
                    <br/>
                    <button type="button" id="reset" class="btn btn-primary filter-action">
                        <span class="icon icon-gommer" aria-hidden="true"></span> R.A.Z.
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    $('button#reset').click(function (e) {
        e.preventDefault();
        window.location = '?';
    });
    $('button#filter').click(function () {
        $('form#filter').submit();
    });

    $('select#domaine option[value="<?php echo $domaine; ?>"]').prop('selected', true);
    $('select#famille option[value="<?php echo $famille; ?>"]').prop('selected', true);
    $('select#historise option[value="<?php echo $historise; ?>"]').prop('selected', true);
</script>