<?php

/**
 * @var Metier[] $metiers
 * @var boolean[] $droits
 */

use Metier\Entity\Db\Metier;

$canAjouter                 = $droits["ajouter"];
$canEditer                  = $droits["editer"];
$canModifierNiveaux         = $droits["editer"];
$canHistoriser              = $droits["historiser"];
$canEffacer                 = $droits["effacer"];

?>
<div class="row">
    <div class="col-md-8">
        <h2>
            Liste des métiers
        </h2>
    </div>
    <div class="pull-right">
        <br/>
        <?php if ($canAjouter) : ?>
            <a  <?php /** @see \Metier\Controller\MetierController::ajouterAction() */ ?>
                href="<?php echo $this->url('metier/ajouter', [], [], true);?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un métier
            </a>
        <?php endif;?>
    </div>
</div>
<br/>
<table id="metiers" class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Libelle </th>
        <th> Domaines </th>
        <th> Références </th>
        <th> Catégorie </th>
        <th> Niveaux </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($metiers as $metier): ?>
        <tr <?php if ($metier->estHistorise()) echo ' class="historise" '; ?>>
            <td>
                <span title='<?php echo $metier->generateTooltip(); ?>'
                      data-toggle='tooltip' data-html='true'
                >
                    <?php echo $metier->getLibelle(); ?>
                </span>
            </td>
            <td>
                <ul>
                    <?php foreach ($metier->getDomaines() as $domaine) : ?>
                        <li>
                            <?php echo $domaine; ?>
                            <?php echo $this->typefonction($domaine); ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td>
                <?php $references =  $metier->getReferences(); ?>
                <?php if (empty($references)) : ?>
                    Aucune
                <?php else: ?>
                <?php foreach ($references as $reference) : ?>
                <a href="<?php echo $reference->getUrl(); ?>" target="_blank" title="<?php echo $reference->getTitre(); ?>">
                    <?php echo $reference->getCode(); ?>
                </a>
                <?php if ($canEditer) : ?>
                <a  <?php /** @see \Metier\Controller\ReferenceController::modifierAction() */ ?>
                    href="<?php echo $this->url('metier/reference/modifier', ['reference' => $reference->getId()], [], true); ?>"
                    class="ajax-modal" data-event="modification"
                >
                    <span class="icon editer" title="Modifier la référence"></span></a>
                <a href="">
                    <a  <?php /** @see \Metier\Controller\ReferenceController::supprimerAction() */ ?>
                        href="<?php echo $this->url('metier/reference/supprimer', ['reference' => $reference->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer la référence"></span></a>
                    <?php endif; ?>
                    <br/>
                    <?php endforeach ?>
                    <?php endif; ?>
            </td>
            <td>
                <?php echo ($metier->getCategorie())?$metier->getCategorie()->getCode():""; ?>
            </td>
            <td>
                <?php echo $this->niveauEnveloppe($metier->getNiveaux()) ?>
                <?php if ($canModifierNiveaux) : ?>
                    <?php if ($metier->getNiveaux()) : ?>
                        <?php /**  @see \Metier\Controller\MetierController::modifierNiveauxAction() */ ?>
                        <a href="<?php echo $this->url('metier/modifier-niveaux', ['metier' => $metier->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        >
                            <span class="icon editer"></span></a>
                    <?php else : ?>
                        <?php /**  @see \Metier\Controller\MetierController::modifierNiveauxAction() */ ?>
                        <a href="<?php echo $this->url('metier/modifier-niveaux', ['metier' => $metier->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        >
                            <span class="icon ajouter"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canEditer) : ?>
                    <a
                        <?php /** @see \Metier\Controller\MetierController::modifierAction() */ ?>
                        href="<?php echo $this->url('metier/modifier', ['metier' => $metier->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon editer" title="Modifier le métier"></span></a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <a
                        <?php /** @see \Metier\Controller\ReferenceController::ajouterAction() */ ?>
                        href="<?php echo $this->url('metier/reference/ajouter', ['metier' => $metier->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon ajouter" title="ajouter une référence"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($metier->estNonHistorise()) : ?>
                        <a  <?php /** @see \Metier\Controller\MetierController::historiserAction() */ ?>
                            href="<?php echo $this->url('metier/historiser', ['metier' => $metier->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser le métier"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \Application\Controller\MetierController::restaurerAction() */ ?>
                            href="<?php echo $this->url('metier/restaurer', ['metier' => $metier->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer le métier"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <a  <?php /** @see \Metier\Controller\MetierController::supprimerAction() */ ?>
                        href="<?php echo $this->url('metier/supprimer', ['metier' => $metier->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire"  title="Supprimer l'application"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $('#metiers').DataTable( {
            // sorting: false,
            // paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );
</script>