<?php

/**
 * @see \Structure\Controller\StructureController::afficherAction()
 * @var Structure[] $selecteur
 * @var Structure $structure
 * @var StructureResponsable[] $responsables
 * @var StructureGestionnaire[] $gestionnaires
 * @var Structure[] $filles
 * @var AgentMissionSpecifique[] $missions
 * @var FichePoste[] $fichespostes
 * @var FichePoste[] $fichespostes_pdf
 * @var FichePoste[] $fichesCompletes
 * @var FichePoste[] $fichesIncompletes
 * @var EtatType[] $fichePosteEtats
// * @var FichePoste[] $fichesRecrutements
 * @var Agent[] $agents
 * @var Agent[] $agentsForces
 * @var Agent[] $agentsAll
// * @var FicheProfil[] $profils
 *
 * @var Agent[] $autorites;
 * @var Agent[] $superieurs;
 *
 * ------- ENTRETIENS PROFESSIONNELS -------
 * @var Campagne[] $campagnes
 * @var Agent[] $agentsArray
 * @var EntretienProfessionnel[] $entretiensArray
 *  $agentsArray = [
 *      (int) $campagneId => (array) Agent[]
 *  ]
 *  $entretiensArray = [
 *      (int) $campagneId => (array) entretiensCampagne [
 *          $agentId => (?EntretienProfessionnel) $entretien
 *      ]
 *  ]
 *
 * @var string $emailAssistance
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentMissionSpecifique;
use Application\Entity\Db\FichePoste;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use Structure\Entity\Db\Structure;
use Structure\Entity\Db\StructureGestionnaire;
use Structure\Entity\Db\StructureResponsable;
use Structure\Provider\Privilege\StructurePrivileges;
use UnicaenEtat\Entity\Db\EtatType;

$this->headTitle($structure->getLibelleLong());

$canAfficherStructure   = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_AFFICHER);

?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            <strong> <?php echo $structure->getLibelleLong(); ?> </strong> <br/>
            <?php echo $structure->getType(); ?>
        </h1>
    </div>
    <div class="col-md-4">
        <br/>
        <?php if (! empty($selecteur)) : ?>
            <label for="structure-selecteur">Structure à afficher : <br/></label>
            <select id="structure-selecteur" name="structure-selecteur" class="bootstrap-select">
                <option value="">Aucune sélection</option>
                <?php foreach ($selecteur as $s) : ?>
                    <option value="<?php echo $s->getId(); ?>" <?php if ($structure->getId() == $s->getId()) echo "selected"; ?>><?php echo $s->getLibelleCourt(); ?></option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
</div>



<?php if (! $canAfficherStructure) : ?>

    <div class="alert alert-danger col-md-8">
        <p class="lead">
            <span class="icon icon-attention"></span>
            Vous n'êtes pas habilité&middot;e à visualiser cette structure.
        </p>
    </div>

<?php else : ?>

    <?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

    <div class="main">

        <?php echo $this->partial('partial/resume', ['structure' => $structure, 'filles' => $filles, 'responsables' => $responsables, 'gestionnaires' => $gestionnaires]); ?>

        <ul class="nav">
            <li class="nav-item">
                <a href="#agents" class="nav-link" aria-controls="agents">
                    Agents <br/> &nbsp;
                </a>
            </li>
            <li class="nav-item">
                <a href="#informations" class="nav-link" aria-controls="informations">
                    Fiches de  <br/> poste
                </a>
            </li>
            <li class="nav-item">
                <a href="#missions" class="nav-link" aria-controls="missions">
                    Missions <br/> spécifiques
                </a>
            </li>

            <?php foreach ($campagnes as $campagne) : ?>
                <li class="nav-item">
                    <a href="#campagne_<?php echo $campagne->getId(); ?>" class="nav-link" aria-controls="campagne_<?php echo $campagne->getId(); ?>">
                        Entretien professionnel <br/>
                        <strong><?php echo $campagne->getAnnee(); ?></strong>
                    </a>
                </li>
            <?php endforeach;?>

<!--            <li class="nav-item">-->
<!--                <a href="#profil" class="nav-link" aria-controls="profil">-->
<!--                    Profil de  <br/>-->
<!--                    recrutement-->
<!--                </a>-->
<!--            </li>-->

            <li class="nav-item">
                <a href="#extraction" class="nav-link" aria-controls="extraction">
                    Extractions  <br/> &nbsp;
                </a>
            </li>
        </ul>


        <div class="tab-content">

                <!-- Informations ------------------------------------------------------------------------------------->
                <div id="agents" class="tab-pane">
                    <div class="row">
                        <div class="col-md-4">
                            <h2>
                                Agents
                                <span class="badge"><?php echo count($agents); ?></span>
                            </h2>
                        </div>
                        <div class="col-md-8">
                            <div class="alert alert-info">
                                <span class="icon icon-information"></span>
                                En cas d'incohérence sur la chaîne hiérarchique d'un agent, veuillez remonter l'information à l'adresse
                                <a href="mailto:<?php echo $emailAssistance; ?>"><?php echo $emailAssistance; ?></a>
                            </div>
                        </div>
                    </div>

                    <?php echo $this->partial('partial/agents', ['structure' => $structure, 'agents' => $agents, 'superieurs' => $superieurs, 'autorites' => $autorites]); ?>

                    <div class="row">
                        <div class="col-md-8">
                            <h2>
                                Agents manuellement ajoutés
                                <span class="badge"><?php echo count($agentsForces); ?></span>
                            </h2>
                        </div>
                        <div class="pull-right">
                            <?php /** @see \Application\Controller\StructureController::ajouterManuellementAgentAction(); */ ?>
                            <a class="btn btn-primary action ajax-modal" data-event="modification"
                               href="<?php echo $this->url("structure/ajouter-manuellement-agent", ["structure" => $structure->getId()], [], true); ?>"
                            >
                                <span class="icon icon-utilisateur-ajouter"></span> Ajouter manuellement un agent
                            </a>
                        </div>
                    </div>
                    <?php echo $this->partial('partial/agents', ['structure' => $structure, 'agents' => $agentsForces, 'options' => ['force' => true]]); ?>

                </div>

                <!-- Informations ------------------------------------------------------------------------------------->
                <div id="informations" class="tab-pane">
                    <?php echo $this->partial('partial/fiches-postes', ['agents' => $agentsAll, 'structure' => $structure, 'fichespostes' => $fichespostes, 'fichespostes_pdf' => $fichespostes_pdf, 'etats' => $fichePosteEtats]); ?>
                </div>

                <!-- Missions spécifique ------------------------------------------------------------------------------------->
                <div id="missions" class="tab-pane">
                    <?php echo $this->partial('partial/missions-specifiques', ['structure' => $structure, 'missions' => $missions]); ?>
                </div>

                <!-- Campagne ------------------------------------------------------------------------------------->
                <?php foreach ($campagnes as $campagne) : ?>
                    <div id="campagne_<?php echo $campagne->getId(); ?>" class="tab-pane">
                        <?php echo $this->partial('partial/campagne', ['campagne' => $campagne, 'structure' => $structure, 'agents' => $agentsArray[$campagne->getId()], 'entretiens' => $entretiensArray[$campagne->getId()]]); ?>
                    </div>
                <?php endforeach; ?>

                <!-- Profil de recrutement ------------------------------->
<!--                <div id="profil" class="tab-pane">-->
<!--                    --><?php //echo $this->partial('partial/profil', ['structure' => $structure, 'profils' => $profils, 'fichesRecrutements' => $fichesRecrutements]); ?>
<!--                </div>-->

                <!-- Extraction ------------------------------------------------------------------------------------->
                <div id="extraction" class="tab-pane">
                    <?php echo $this->partial('partial/extraction', ['structure' => $structure]); ?>
                </div>
            </div>
    </div>
<?php endif; ?>

<script>
    // $("body").on("modification", function (event) {
    //     event.div.modal('hide');
    //     window.location.reload();
    // });

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "agents";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

    });

    $(function() {
        $('select#structure-selecteur').change(function() {
            let id = $('select#structure-selecteur option:selected').val();
            if (id !== "" && id !== "<?php echo $structure->getId(); ?>") {
                window.location.href = './' + id;
            }
        });
    });


    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "formulaire";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav a').click(function (e) {
            let anchor = $(this).attr('aria-controls');
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#"+anchor);
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
