<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\Campagne;
use Structure\Entity\Db\Structure;
use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @see \Structure\Controller\StructureController::agentsAction()
 *
 * @var Structure $structure
 * @var Agent[] $agents
 * @var Agent[] $agentsRetires
 * @var string[] $raison
 * @var Agent[] $agentsForces
 * @var Agent[] $superieurs
 * @var Agent[] $autorites
 * @var Campagne[] $campagnes
 * @var string $emailAssistance
 * @var Structure[] $selecteur
 * @var ?string $debug
 */

$this->headTitle($structure->getLibelleLong() . " - Liste des Agent·es");

$canAjouterAgent = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_AGENT_FORCE);
?>

<?php echo $this->partial('partial/entete', ['structure' => $structure, 'campagnes' => $campagnes, 'current' => 'agents', 'selecteur' => $selecteur]); ?>

<?php if ($debug) : ?>
    <div class="alert alert-warning">
        <?php echo $debug; ?>
    </div>
<?php endif; ?>

<div class="alert alert-info">
    <span class="icon icon-information"></span>
    En cas d'incohérence sur la chaîne hiérarchique d'un agent, veuillez remonter l'information à l'adresse
    <a href="mailto:<?php echo $emailAssistance; ?>"><?php echo $emailAssistance; ?></a>
</div>

<h2>
    Agents
    <span class="badge"><?php echo count($agents); ?></span>
</h2>

<?php echo $this->partial('partial/agents', ['options' => ['id' => 'agent'], 'structure' => $structure, 'agents' => $agents, 'superieurs' => $superieurs, 'autorites' => $autorites, 'raison' => $raison]); ?>

<h2>
Agents masqués
    <span class="badge"><?php echo count($agentsRetires); ?></span>
</h2>

<?php echo $this->partial('partial/agents', ['options' => ['id' => 'agents-retires'], 'structure' => $structure, 'agents' => $agentsRetires, 'superieurs' => $superieurs, 'autorites' => $autorites, 'raison' => $raison]); ?>

<h2>
    Agents manuellement ajoutés
    <span class="badge"><?php echo count($agentsForces); ?></span>
</h2>

<?php if ($canAjouterAgent) : ?>
    <?php /** @see \Structure\Controller\StructureController::ajouterManuellementAgentAction(); */ ?>
    <a class="btn btn-primary action ajax-modal" data-event="modification"
       href="<?php echo $this->url("structure/ajouter-manuellement-agent", ["structure" => $structure->getId()], [], true); ?>"
    >
        <span class="icon icon-utilisateur-ajouter"></span> Ajouter manuellement un agent
    </a>
<?php endif; ?>

<?php echo $this->partial('partial/agents', [ 'structure' => $structure, 'agents' => $agentsForces, 'options' => ['force' => true, 'id' => 'force']]); ?>


<script>
    $('button#agents-tab').addClass('active');
</script>
