<?php

use Agent\Entity\Db\AgentAffectation;
use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentAutorite;
use Application\Entity\Db\AgentSuperieur;
use EntretienProfessionnel\Entity\Db\Campagne;
use Structure\Entity\Db\Structure;
use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @see \Structure\Controller\StructureController::agentsAction()
 *
 * @var Structure $structure
 * @var Agent[] $agents
 * @var Agent[] $agentsRetires
 * @var string[] $raison
 * @var Agent[] $agentsForces
 * @var AgentSuperieur[] $superieurs
 * @var AgentAutorite[] $autorites
 * @var AgentAffectation[] $affectations
 * @var Campagne[] $campagnes
 * @var string $emailAssistance
 * @var Structure[] $selecteur
 * @var ?string $debug
 */

$this->headTitle($structure->getLibelleLong() . " - Liste des Agent·es");

$canAjouterAgent = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_AGENT_FORCE);
$canAfficherAgentsExclus = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_AGENT_MASQUE))
?>

<?php echo $this->partial('partial/entete', ['structure' => $structure, 'campagnes' => $campagnes, 'current' => 'agents', 'selecteur' => $selecteur]); ?>

<?php if ($debug) : ?>
    <div class="alert alert-warning">
        <?php echo $debug; ?>
    </div>
<?php endif; ?>

<div class="alert alert-info">
    <span class="icon icon-information"></span>
    En cas d'incohérence sur la chaîne hiérarchique d'un agent, veuillez remonter l'information à l'adresse
    <a href="mailto:<?php echo $emailAssistance; ?>"><?php echo $emailAssistance; ?></a>
</div>

<h2>
    Agents
    <span class="badge"><?php echo count($agents); ?></span>
</h2>

<?php echo $this->partial('partial/agents', ['options' => ['id' => 'agent'], 'structure' => $structure, 'agents' => $agents,
    'superieurs' => $superieurs, 'autorites' => $autorites, 'affectations' => $affectations,
    'raison' => $raison]); ?>

<?php if ($canAfficherAgentsExclus) : ?>
    <span id="button_exclus" class="btn btn-secondary">
        <span id="icone_exclus" class="icon icon-voir"></span>
        <span id="texte_exclus">Afficher les agent·es exclu·es (<?php echo count($agentsRetires); ?> agent·es)</span>
    </span>
<?php endif; ?>

<div id="agents_exclus" style="display: none">
    <h2>
        Agents exclus
        <span class="badge"><?php echo count($agentsRetires); ?></span>
    </h2>

    <?php echo $this->partial('partial/agents', ['options' => ['id' => 'agents-retires'], 'structure' => $structure, 'agents' => $agentsRetires,
        'superieurs' => $superieurs, 'autorites' => $autorites, 'affectations' => $affectations,
        'raison' => $raison]); ?>
</div>

<h2>
    Agents manuellement ajoutés
    <span class="badge"><?php echo count($agentsForces); ?></span>
</h2>

<?php if ($canAjouterAgent) : ?>
    <?php /** @see \Structure\Controller\StructureController::ajouterManuellementAgentAction(); */ ?>
    <a class="btn btn-primary ajax-modal" data-event="modification"
       href="<?php echo $this->url("structure/ajouter-manuellement-agent", ["structure" => $structure->getId()], [], true); ?>"
    >
        <span class="icon icon-utilisateur-ajouter"></span> Ajouter manuellement un agent
    </a>
<?php endif; ?>

<?php echo $this->partial('partial/agents', [ 'structure' => $structure, 'agents' => $agentsForces,
    'superieurs' => $superieurs, 'autorites' => $autorites, 'affectations' => $affectations,
    'options' => ['force' => true, 'id' => 'force']]); ?>


<script>
    $('button#agents-tab').addClass('active');
</script>


<script>
    $('span#button_exclus').on('click', function() {
        $('div#agents_exclus').toggle();
        if ($('div#agents_exclus').is(":visible")) {
            // alert('visible');
            $('span#icone_exclus').removeClass('icon-voir').addClass('icon-masquer');
            $('span#texte_exclus').text("Masquer les agent·es exclu·es (<?php echo count($agentsRetires); ?> agent·es)");
        } else {
            // alert('masquer');
            $('span#icone_exclus').removeClass('icon-masquer').addClass('icon-voir');
            $('span#texte_exclus').text("Afficher les agent·es exclu·es (<?php echo count($agentsRetires); ?> agent·es)");
        }

    });
</script>