<?php

use Application\Entity\Db\Agent;
use Structure\Entity\Db\Structure;

/**
 * @see \Structure\Controller\StructureController::descriptionAction()
 * @var Structure $structure
 *
 * @var Agent[] $responsables
 *
 * @var Structure $niveau2
 * @var Structure $parent
 * @var Structure[] $filles
 */

$this->headTitle($structure->getLibelleLong() . " - Description");

?>

<?php echo $this->partial('partial/entete', ['structure' => $structure]); ?>

<div class="row">
    <div class="col-md-6">
        <h2> Description </h2>

        <h3> Rattachement </h3>

        Structure rattachée à <?php echo $niveau2->getLibelleLong(); ?>

        <h3> Présentation de la structure</h3>

        <?php if ($structure->getRepriseResumeMere()) : ?>
            <div class="alert alert-info">
                <span class="icon icon-information"></span>
                Reprise du résumé de la structure mère.
            </div>
        <?php endif; ?>
        <?php if ($structure->getDescriptionComplete()) : ?>
            <?php echo $structure->getDescriptionComplete(); ?>
        <?php else : ?>
            <span class="text-warning">
                <span class="icon icon-attention"></span>
                Aucune description
            </span>
        <?php endif; ?>

        <h3> Autres informations </h3>

        <dl class="row">
            <?php if ($structure->getOuverture() !== null) : ?>
                <dt class="col-md-4"> Date d'ouverture </dt>
                <dd class="col-md-8"> <?php echo $structure->getOuverture()->format('d/m/Y'); ?></dd>
            <?php endif; ?>
            <?php if ($structure->getFermeture() !== null) : ?>
                <dt class="col-md-4"> Date de fermeture </dt>
                <dd class="col-md-8"> <?php echo $structure->getFermeture()->format('d/m/Y'); ?></dd>
            <?php endif; ?>
            <?php if ($structure->getAdresseFonctionnelle() !== null) : ?>
                <dt class="col-md-4"> Adresse de contact </dt>
                <dd class="col-md-8"> <?php echo $structure->getAdresseFonctionnelle(); ?></dd>
            <?php endif; ?>
        </dl>
    </div>
    <div class="col-md-6">
        <h2> Responsable·s </h2>

        <?php if (empty($responsables)) : ?>
            <span class="text-warning">
                <span class="icon icon-attention"></span>
                Aucun responsable de désigné·e pour cette structure.
            </span>
        <?php else : ?>
            <ul>
                <?php foreach ($responsables as $responsable) : ?>
                    <li>
                    <span title="Responsabilité valide sur la période du <?php echo ($responsable->getDateDebut())?$responsable->getDateDebut()->format('d/m/Y'):"N.C"; ?> au  <?php echo ($responsable->getDateFin())?$responsable->getDateFin()->format('d/m/Y'):"N.C"; ?>">
                        <?php echo $responsable->getAgent()->getDenomination(); ?>
                    </span>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <h2> Positionnement de la structure </h2>

        <h3>Structure mère <code>n+1</code></h3>
        <?php echo $parent->getLibelleLong(); ?>

        <h3>Structure courante <code>n</code></h3>
        <?php echo $structure->getLibelleLong(); ?>

        <h3>Structure·s enfant·s <code>n-1</code></h3>
        <?php foreach ($filles as $enfant) : ?>
            <?php echo $enfant->getLibelleLong()?>
            <br/>
        <?php endforeach; ?>

    </div>
</div>
