<?php

use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @see \Application\Controller\StructureController::indexAction()
 * @var Structure\Entity\Db\Structure[] $structures
 */

$this->headTitle("Index des structures");

$canAfficher    = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_AFFICHER));

?>

<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Structures
            <span class="badge">
                <?php echo count($structures); ?>
            </span>
            <?php echo $this->synchroniserIcon(); ?>
        </h1>
    </div>
</div>

<a href="<?php echo $this->url("structure/synchroniser",[],[],true); ?>" class="btn btn-primary">SYNCHRO</a>
<div class="main">

    <table id="structures" class="datatable table table-condensed table-hover">
        <thead>
            <tr>
                <th> Libellé </th>
                <th> Code </th>
                <th> Type </th>
<!--                <th> Resp./Gest. </th>-->
                <th> Resp. </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($structures as $structure) : ?>
                <tr>
                    <td>
                        <abbr title="<?php echo $structure->getLibelleLong(); ?>">
                            <?php echo $structure->getLibelleCourt(); ?>
                        </abbr>
                        <?php if ($structure->getFermeture() !== null) : ?>
                            <span class="ferme" title="<?php echo $structure->getFermeture()->format('d/m/Y'); ?>">
                                Fermée
                            </span>
                        <?php endif; ?>
                    </td>
                    <td> <?php echo $structure->getCode(); ?> </td>
                    <td> <?php echo $structure->getType(); ?> </td>
                    <td>
                        <!-- responsables -->
                        <?php
                            $responsables = $structure->getResponsables();
                            $listing = "<u><b>Responsable(s) : </b></u><br/>";
                            foreach ($responsables as $responsable) {
                                if ($responsable->getAgent()) {
                                    $listing .= $responsable->getAgent()->getDenomination() . "<br/>";
                                } else {
                                    $listing .= "Problème avec le responsable [".$responsable->getId()."]". "<br/>";
                                }
                            }
                        ?>
                        <span title="<?php echo $listing; ?>" data-bs-toggle="tooltip" data-bs-html="true" <?php if (empty($responsables)) echo ' style="color:darkred;" '; ?> >
                        <?php echo count($responsables); ?> <span class="icon icon-user"></span>
                        </span>

<!--                        /-->
                        <!-- gestionnaires -->
<!--                        --><?php
//                            $gestionnaires = $structure->getGestionnaires();
//                            $listing = "<u><b>Gestionnaires(s) : </b></u><br/>";
//                            foreach ($gestionnaires as $gestionnaire) {
//                                if ($gestionnaire->getAgent()) {
//                                    $listing .= $gestionnaire->getAgent()->getDenomination() . "<br/>";
//                                } else {
//                                    $listing .=  "Problème avec le gestionnaire [".$gestionnaire->getId()."]". "<br/>";
//                                }
//                            }
//                        ?>
<!--                        <span title="--><?php //echo $listing; ?><!--" data-bs-toggle="tooltip" data-bs-html="true"  >-->
<!--                        --><?php //echo count($gestionnaires); ?><!-- <span class="icon icon-user"></span>-->
<!--                        </span>-->
                    </td>
                    <td>
                        <?php if ($canAfficher) : ?>
                            <?php /** @see \Structure\Controller\StructureController::descriptionAction() */ ?>
                            <a href="<?php echo $this->url('structure/description', ['structure' => $structure->getId()], [], true); ?>"
                            >
                                <span class="icon icon-voir"   title="Afficher la structure"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('.datatable').DataTable({
            paging: false,
        });
    });
</script>