<?php

use Structure\Entity\Db\Structure;
use Structure\Entity\Db\StructureType;
use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @see \Structure\Controller\StructureController::indexAction()
 * @var Structure[] $structures
 * @var StructureType[] $types
 * @var array $params
 */

$this->headTitle("Index des structures");

$canAfficher = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_AFFICHER));
$now = new DateTime();
?>

<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Structures
        </h1>
    </div>
</div>


<?php echo  $this->partial('partial/filtre', ['types' => $types, 'params' => $params]); ?>


<table id="structures" class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th> Structure de rattachement</th>
        <th> Libellé</th>
        <th> Code</th>
        <th> Type</th>
        <th> Niveau</th>
        <th> Resp.</th>
        <th> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($structures as $structure) : ?>
        <tr>
            <td>
                <?php $rattachement = $structure->getNiv2() ?? $structure; ?>
                <?php if ($rattachement->getSigle()) : ?>
                    [<?php echo $rattachement->getSigle(); ?>]
                <?php endif; ?>
                <?php echo $rattachement->getLibelleCourt(); ?>
                <br>
                <?php echo $rattachement->getLibelleLong(); ?>
            </td>
            <td>
                <?php if ($structure->getSigle()) : ?>
                    [<?php echo $structure->getSigle(); ?>]
                <?php endif; ?>
                <?php echo $structure->getLibelleCourt(); ?>
                <?php if ($structure->getFermeture() && $structure->getFermeture() <= $now) : ?>
                    &nbsp;<span class="badge bg-danger"
                                title="La structure est fermée depuis le <?php echo $structure->getFermeture()->format('d/m/Y'); ?>.">
                                Structure fermée
                            </span>
                <?php endif; ?>
                <br/>
                <?php echo $structure->getLibelleLong(); ?>
            </td>
            <td> <?php echo $structure->getCode(); ?> </td>
            <td>
                <?php if ($structure->getType()) : ?>
                    <?php echo $structure->getType()->getLibelle(); ?>
                <?php else : ?>
                    <span class="text-warning">
                                <span class="icon icon-attention"></span>
                                Type de structure manquant
                            </span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($structure->getNiveau()) : ?>
                    <?php echo $structure->getNiveau(); ?>
                <?php else : ?>
                     -
                <?php endif; ?>
            </td>
            <td>
                <!-- responsables -->
                <?php
                $responsables = $structure->getResponsables();
                $listing = "<u><b>Responsable(s) : </b></u><br/>";
                foreach ($responsables as $responsable) {
                    if ($responsable->getAgent()) {
                        $listing .= $responsable->getAgent()->getDenomination() . "<br/>";
                    } else {
                        $listing .= "Problème avec le responsable [" . $responsable->getId() . "]" . "<br/>";
                    }
                }
                ?>
                <span title="<?php echo $listing; ?>" data-bs-toggle="tooltip"
                      data-bs-html="true" <?php if (empty($responsables)) echo ' style="color:darkred;" '; ?> >
                        <?php echo count($responsables); ?> <span class="icon icon-user"></span>
                        </span>
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Structure\Controller\StructureController::descriptionAction() */ ?>
                    <a href="<?php echo $this->url('structure/description', ['structure' => $structure->getId()], [], true); ?>"
                       class="action secondary"
                    >
                        <span class="icon icon-voir"></span>
                        Visualiser
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function () {
        $('table#structures').dataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [6], orderable: false}
            ]
        });
    });
</script>