<?php

use Application\Entity\Db\AgentMissionSpecifique;
use Application\Provider\Privilege\MissionspecifiqueaffectationPrivileges;
use Missionspecifique\Provider\Privilege\MissionspecifiquePrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use Structure\Entity\Db\Structure;

/**
 * @see \Structure\Controller\StructureController::missionsSpecifiquesAction()
 * @var Structure $structure
 * @var Structure[] $selecteur
 * @var AgentMissionSpecifique[] $missionsSpecifiques
 *
 * @var Campagne[] $campagnes
 */

$this->headTitle($structure->getLibelleLong() . " - Description");

$canVoirAffectation         = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_AFFICHER));
$canAjouterAffectation      = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_AJOUTER));
$canModifierAffectation     = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_MODIFIER));
$canHistoriserAffectation   = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_HISTORISER));
$canDetruireAffectation     = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_DETRUIRE));

?>

<?php echo $this->partial('partial/entete', ['structure' => $structure, 'campagnes' => $campagnes, 'current' => 'missions-specifiques', 'selecteur' => $selecteur]); ?>

<?php if ($canAjouterAffectation) : ?>
    <a
        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::ajouterAction() */ ?>
        href="<?php echo $this->url('mission-specifique-affectation/ajouter', [], ["query" => ['structure' => $structure->getId()]], true); ?>"
        class="btn btn-primary ajax-modal"
        data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter une mission spécifique
    </a>
<?php endif; ?>

<?php echo $this->affectationsMissionSpecifique($missionsSpecifiques, ['retour' => $this->url('structure/missions-specifiques', ['structure' => $structure->getId()], [], true)]); ?>


<script>
    $(document).ready(function () {
        $('button#mission-specifique-tab').addClass('active');
    });
</script>