<?php

use Application\Entity\Db\AgentMissionSpecifique;
use Application\Provider\Privilege\MissionspecifiquePrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use Structure\Entity\Db\Structure;

/**
 * @see \Structure\Controller\StructureController::missionsSpecifiquesAction()
 * @var Structure $structure
 * @var Structure[] $selecteur
 * @var AgentMissionSpecifique[] $missionsSpecifiques
 *
 * @var Campagne[] $campagnes
 */

$this->headTitle($structure->getLibelleLong() . " - Description");

$canVoirAffectation         = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_AFFICHER));
$canAjouterAffectation      = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_MODIFIER));
$canModifierAffectation     = $canAjouterAffectation;
$canHistoriserAffectation   = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_HISTORISER));
$canDetruireAffectation     = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_DETRUIRE));

?>

<?php echo $this->partial('partial/entete', ['structure' => $structure, 'campagnes' => $campagnes, 'current' => 'missions-specifiques', 'selecteur' => $selecteur]); ?>

<?php if ($canAjouterAffectation) : ?>
    <a
        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::ajouterAction() */ ?>
        href="<?php echo $this->url('mission-specifique-affectation/ajouter', [], ["query" => ['structure' => $structure->getId()]], true); ?>"
        class="btn btn-primary action ajax-modal"
        data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter une mission spécifique
    </a>
<?php endif; ?>


<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Agent </th>
        <th> Structure </th>
        <th> Mission </th>
        <th> Volume horaire </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($missionsSpecifiques as $mission) : ?>
        <tr <?php echo ($mission->estHistorise())?'class="historise"':''; ?>>
            <td> <?php echo $mission->getAgent()->getDenomination(); ?> </td>
            <td> <?php echo $mission->getStructure()->getLibelleLong(); ?> </td>
            <td> <?php echo $mission->getMission()->getLibelle(); ?> </td>
            <td>
                <?php if ($mission->getDecharge() !== null): ?>
                    <?php echo $mission->getDecharge(); ?> h.
                <?php else : ?>
                    Aucune
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirAffectation) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::afficherAction() */?>
                        href="<?php echo $this->url('mission-specifique-affectation/afficher', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                        class="ajax-modal"
                    >
                        <span class="icon icon-voir" data-toggle='tooltip'  data-html='true' title="Afficher l'affectation"></span></a>
                <?php endif; ?>
                <?php if ($canVoirAffectation) : ?>
                    <?php /** @see MissionSpecifiqueAffectationController::genererLettreTypeAction() */ ?>
                    <a href="<?php echo $this->url('mission-specifique-affectation/generer-lettre-type', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                       target="_blank"
                    >
                        <span class="icon icon-pdf"  data-bs-toggle="tooltip" data-bs-html="true"
                              title="Générer la lettre type associée l'affectation"></span></a>
                <?php endif; ?>
                <?php if ($canModifierAffectation) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::modifierAction() */?>
                        href="<?php echo $this->url('mission-specifique-affectation/modifier', ['agent-mission-specifique' => $mission->getId()], ["query" => ['structure' => $structure->getId()]], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon icon-editer" data-toggle='tooltip'  data-html='true' title="Modifier l'affectation"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriserAffectation) : ?>
                    <?php if ($mission->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::historiserAction() */?>
                            href="<?php echo $this->url('mission-specifique-affectation/historiser', ['agent-mission-specifique' => $mission->getId()], ["query" => ["retour" => $this->url('structure/missions-specifiques', ['structure' => $structure->getId()], [], true)]], true); ?>"
                        >
                            <span class="icon icon-historiser" data-toggle='tooltip'  data-html='true' title="Historiser l'affectation"></span></a>
                    <?php else : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::restaurerAction() */?>
                            href="<?php echo $this->url('mission-specifique-affectation/restaurer', ['agent-mission-specifique' => $mission->getId()], ["query" => ["retour" => $this->url('structure/missions-specifiques', ['structure' => $structure->getId()], [], true)]], true); ?>"
                        >
                            <span class="icon icon-restaurer" data-toggle='tooltip'  data-html='true' title="Restaurer l'affectation"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruireAffectation) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::detruireAction() */?>
                        href="<?php echo $this->url('mission-specifique-affectation/detruire', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon icon-retirer" data-toggle='tooltip'  data-html='true' title="Supprimer l'affectation"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
