<?php

use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;

/**
 * @var Agent[] $agents
 */

?>

Voue êtes responsable de <?php echo count($agents); ?> agent·es.

<table class="table table-condensed datatable" id="agents">
    <thead>
    <tr>
        <th data-type="string"> Dénomination </th>
        <th> Affectations </th>
        <th> Grades </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) : ?>
        <tr>
            <td data-order="<?php echo $agent->getDenomination(); ?>">
                <?php echo $agent->getDenomination(true); ?>
            </td>
            <td>
                <?php $affectations = $agent->getAffectationsActifs(); ?>
                <?php foreach ($affectations as $affectation) : ?>
                    <?php if ($affectation->getStructure()->getNiv2()) : ?>
                        <?php echo $affectation->getStructure()->getNiv2()->getLibelleCourt(); ?>
                        >
                    <?php endif; ?>
                    <?php echo $affectation->getStructure()->getLibelleLong(); ?>
                    <?php if ($affectation->isPrincipale()) : ?>
                        <span class="badge" title="Affectation principale" style="background: seagreen">P</span>
                    <?php endif; ?>
                    <?php if ($affectation->isHierarchique()) : ?>
                        <span class="badge" title="Affectation hiérarchique" style="background: #3d6b6c">H</span>
                    <?php endif; ?>
                    <?php if ($affectation->isFonctionnelle()) : ?>
                        <span class="badge" title="Affectation fonctionnelle" style="background: #9a0422">F</span>
                    <?php endif; ?>
                <br/>
                <?php endforeach; ?>
            </td>
            <td>
                <?php $grades = $agent->getGradesActifs(); ?>
                <?php foreach ($grades as $grade) : ?>
                    <?php echo ($grade->getGrade())?$grade->getGrade()->getLibelleLong():"Aucun grade"; ?>
                    <br/>
                    <?php echo $this->correspondance($grade->getCorrespondance()); ?>
                <?php endforeach; ?>
            </td>
            <td class="action">
                <?php if ($this->isAllowed($agent, AgentPrivileges::AGENT_AFFICHER)) : ?>
                <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>">
                    <span class="icon icon-user"></span>
                    Afficher
                </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $("table#agents").DataTable( {
            'paging' : false,
            'searching' : true,
            'info' : false,
        });
    });
</script>
