<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Etat\EntretienProfessionnelEtats;
use EntretienProfessionnel\Provider\Template\TexteTemplates;
use UnicaenRenderer\Entity\Db\Template;
use UnicaenRenderer\Provider\Privilege\DocumenttemplatePrivileges;

/**
 * @var Campagne $campagne
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent $connectedAgent
 * @var Agent[] $agents
 * @var Template[] $templates
 */

$obligatoires = $agents[0];
$facultatifs = $agents[1];
$raisons = $agents[2];

//foreach ($agents as $agent) {
//    if (!empty($agent->getAffectationsActifs($dateMinEnPoste)) && !$agent->isForceSansObligation($campagne)) $obligatoires[] = $agent; else $facultatifs[] = $agent;
//}
//
$finalises = [];
$encours = [];
foreach ($entretiens as $entretien) {
    if ($entretien->isEtatActif(EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_AGENT)) {
        $finalises[] = $entretien;
    } else {
        $encours[] = $entretien;
    }
}

$sansObligatoires = []; $sansFacultatifs = [];
foreach ($obligatoires as $obligatoire) {
    if (!isset($entretiens[$obligatoire->getId()])) $sansObligatoires[] = $obligatoire;
}
foreach ($facultatifs as $facultatif) {
    if (!isset($entretiens[$facultatif->getId()])) $sansFacultatifs[] = $facultatif;
}

$canTemplateModifier = $this->isAllowed(DocumenttemplatePrivileges::getResourceId(DocumenttemplatePrivileges::DOCUMENTTEMPLATE_MODIFIER));


$this->headTitle("Campagne d'entretien professionnel " . $campagne->getAnnee() )
?>

<h1 class="page-header">
    Campagne d'entretien professionnel <?php echo $campagne->getAnnee(); ?>
</h1>

<div class="row">
    <div class="col-md-6">
        <h3> Information sur la campagne</h3>
        <?php echo $this->campagneInformation($campagne); ?>
    </div>
    <div class="col-md-6">
        <h3> Complétion de la campagne</h3>
        <?php echo $this->campagneAvancement($entretiens, $obligatoires); ?>
    </div>
</div>

<?php if (!empty($finalises)) : ?>
    <h2>
        Entretiens professionnels finalisés
        <span class="badge"> <?php echo count($finalises); ?> </span>
    </h2>

    <?php echo $this->entretienProfessionnelArray($finalises, ['affichages' => ['annee' => false], 'id' => 'complet_' . $campagne->getId()]); ?>
<?php endif; ?>


<?php if (!empty($encours)) : ?>
    <h2>
        Entretiens professionnels en cours d'évaluation
        <span class="badge"> <?php echo count($encours); ?> </span>
    </h2>

    <?php echo $this->entretienProfessionnelArray($encours, ['affichages' => ['annee' => false], 'id' => 'encours_' . $campagne->getId()]); ?>
<?php endif; ?>

<?php if (!empty($obligatoires)) : ?>
    <h2>
        Agents en attente d'entretien professionnel
        <span class="badge"> <?php echo count($sansObligatoires); ?> </span>
    </h2>
    <?php echo $this->convocationArray($sansObligatoires, $campagne, ['id' => 'sansentretien_' . $campagne->getId(), 'raison' => $raisons]); ?>
<?php endif; ?>

<?php if (!empty($facultatifs)) : ?>
    <h2>
        Agents sans obligation d'entretien professionnel
        <span class="badge"> <?php echo count($sansFacultatifs); ?> </span>
    </h2>

    <div class="alert alert-info">
        <div class="row">
            <div class="col-md-10">
                <?php echo $templates[TexteTemplates::EP_EXPLICATION_SANS_OBLIGATION]->getCorps(); ?>
            </div>
            <div class="col-md-2">
                <?php if ($canTemplateModifier) : ?>
                    <?php /** @see \UnicaenRenderer\Controller\TemplateController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('contenu/template/modifier', ['template' => $templates[TexteTemplates::EP_EXPLICATION_SANS_OBLIGATION]->getTemplate()->getId()], [], true); ?>" class="action primary">
                        <span class="icon icon-editer"></span> Modifier
                    </a>
                <?php endif; ?>
            </div>

        </div>
    </div>
    <?php echo $this->convocationArray($sansFacultatifs, $campagne, ['id' => 'sansobligation_' . $campagne->getId(), 'raison' => $raisons]); ?>
<?php endif; ?>


