<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Etat\EntretienProfessionnelEtats;

/**
 * @var Campagne $campagne
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent[] $agents
 */

$obligatoires = [];
$facultatifs = [];
$dateMinEnPoste = (DateTime::createFromFormat('d/m/Y', $campagne->getDateFin()->format('d/m/Y')))->sub(new DateInterval('P12M'));
foreach ($agents as $agent) {
    if (!empty($agent->getAffectationsActifs($dateMinEnPoste))) $obligatoires[] = $agent; else $facultatifs[] = $agent;
}

$finalises = [];
$encours = [];
foreach ($entretiens as $entretien) {
    if ($entretien->getEtat()->getCode() === EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_AGENT) {
        $finalises[] = $entretien;
    } else {
        $encours[] = $entretien;
    }
}

$sansObligatoires = []; $sansFacultatifs = [];
foreach ($obligatoires as $obligatoire) {
    if (!isset($entretiens[$obligatoire->getId()])) $sansObligatoires[] = $obligatoire;
}
foreach ($facultatifs as $facultatif) {
    if (!isset($entretiens[$facultatif->getId()])) $sansFacultatifs[] = $facultatif;
}

$this->headTitle("Campagne d'entretien professionnel " . $campagne->getAnnee() )
?>

<h1 class="page-header">
    Campagne d'entretien professionnel <?php echo $campagne->getAnnee(); ?>
</h1>

<div class="row">
    <div class="col-md-6">
        <h3> Information sur la campagne</h3>
        <?php echo $this->campagneInformation($campagne); ?>
    </div>
    <div class="col-md-6">
        <h3> Complétion de la campagne</h3>
        <?php echo $this->campagneAvancement($entretiens, $obligatoires); ?>
    </div>
</div>

<?php if (!empty($finalises)) : ?>
    <h2>
        Entretiens professionnels finalisés
        <span class="badge"> <?php echo count($finalises); ?> </span>
    </h2>

    <?php echo $this->entretienProfessionnelArray($finalises, ['id' => 'complet']); ?>
<?php endif; ?>


<?php if (!empty($encours)) : ?>
    <h2>
        Entretiens professionnels en cours d'évaluation
        <span class="badge"> <?php echo count($encours); ?> </span>
    </h2>

    <?php echo $this->entretienProfessionnelArray($encours, ['id' => 'encours']); ?>
<?php endif; ?>

<?php if (!empty($obligatoires)) : ?>
    <h2>
        Agents sans entretien professionnel pour la campagne
        <span class="badge"> <?php echo count($sansObligatoires); ?> </span>
    </h2>
    <?php echo $this->convocationArray($sansObligatoires, $campagne, ['id' => 'sansentretien']); ?>
<?php endif; ?>

<?php if (!empty($facultatifs)) : ?>
    <h2>
        Agents sans obligation d'entretien professionnel
        <span class="badge"> <?php echo count($sansFacultatifs); ?> </span>
    </h2>

    <div class="alert alert-info">
        <div class="row">
            <div class="col-md-1"><span class="icon icon-info"></span></div>
            <div class="col-md-10">
                Les agents n'étant pas en poste à la date du <?php echo $dateMinEnPoste->format('d/m/Y'); ?> n'ont pas d'obligation d'entretien professionnel.
                <br/>
                Vous pouvez cependant planifier un entretien professionnel si vous le souhaitez.
            </div>
        </div>
    </div>
    <?php echo $this->convocationArray($sansFacultatifs, $campagne, ['id' => 'sansobligation']); ?>
<?php endif; ?>


