<?php
/**
 * @var Agent[] $agents
 * @var FormationInstanceInscrit[] $demandesInternes
 * @var DemandeExterne[] $demandesExternes
 */

use Application\Entity\Db\Agent;
use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\FormationInstanceInscrit;
use Formation\Provider\Etat\DemandeExterneEtats;
use Formation\Provider\Etat\InscriptionEtats;

$canAfficherFormation = true;
$canValiderResponsable = true;
?>

<h2> Demande de formations internes (plan de formation) </h2>

<?php foreach ($agents as $agent) : ?>
    <?php if (isset($demandesInternes[$agent->getId()])) : ?>
        <h3> <?php echo $agent->getDenomination(); ?> </h3>

        <table id="formation" class="table table-condensed table-hover">
            <thead>
            <tr>
                <th>Formation</th>
                <th class="periode">Période</th>
                <th class="etat">Etat</th>
                <th class="action">Action</th>
            </tr>
            </thead>
            <tbody>
                <?php /** @var FormationInstanceInscrit $demande */ ?>
                <?php foreach ($demandesInternes[$agent->getId()] as $demande) : ?>
                <tr>
                    <td> <?php echo $demande->getInstance()->getFormation()->getLibelle() ;?> </td>
                    <td> <?php echo $demande->getInstance()->getPeriode() ;?> </td>
                    <td> <?php echo $this->etatbadge($demande->getEtat()) ;?> </td>
                    <td>
                        <?php if ($canAfficherFormation) : ?>
                            <?php /** @see \Formation\Controller\FormationInstanceInscritController::afficherAgentAction() */ ?>
                            <a href="<?php echo $this->url('formation-instance/afficher-agent', ['inscrit' => $demande->getId()], [], true); ?>"
                               class="ajax-modal">
                                <span class="icon icon-voir" title="Examiner l'inscription"></span></a>
                        <?php endif; ?>
                        <?php if ($canValiderResponsable AND $demande->getEtat()->getCode() === InscriptionEtats::ETAT_DEMANDE) : ?>
                            <?php  /** @see \Formation\Controller\FormationInstanceInscritController::validerResponsableAction() */ ?>
                            <a href="<?php echo $this->url('formation-instance/valider-responsable', ['inscrit' => $demande->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon icon-ok text-success"></span></a>
                            <?php  /** @see \Formation\Controller\FormationInstanceInscritController::refuserResponsableAction() */ ?>
                            <a href="<?php echo $this->url('formation-instance/refuser-responsable', ['inscrit' => $demande->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon icon-ko text-danger"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endforeach; ?>

<h2> Demande de stages externes </h2>

<?php foreach ($agents as $agent) : ?>
    <?php if (isset($demandesInternes[$agent->getId()])) : ?>
        <h3> <?php echo $agent->getDenomination(); ?> </h3>

        <table id="formation" class="table table-condensed table-hover">
            <thead>
            <tr>
                <th>Formation</th>
                <th class="periode">Période</th>
                <th class="etat">Etat</th>
                <th class="action">Action</th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var DemandeExterne $demande */ ?>
            <?php foreach ($demandesExternes[$agent->getId()] as $demande) : ?>
                <tr>
                    <td> <?php echo $demande->getLibelle() ;?> </td>
                    <td> <?php echo $demande->getPeriodeAsString() ;?> </td>
                    <td> <?php echo $this->etatbadge($demande->getEtat()) ;?> </td>
                    <td>
                        <?php if ($canAfficherFormation) : ?>
                            <?php /** @see \Formation\Controller\DemandeExterneController::afficherAction() */ ?>
                            <a href="<?php echo $this->url('formation/demande-externe/afficher', ['demande-externe' => $demande->getId()],[], true); ?>"
                            class="ajax-modal">
                            <span class="icon icon-voir"></span></a>
                        <?php endif; ?>
                        <?php if ($canValiderResponsable AND $demande->getEtat()->getCode() === DemandeExterneEtats::ETAT_VALIDATION_AGENT) : ?>
                            <?php /** @see \Formation\Controller\DemandeExterneController::validerDrhAction() */ ?>
                            <a href="<?php echo $this->url('formation/demande-externe/valider-drh', ['demande-externe' => $demande->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon icon-ok text-success"></span></a>
                            <?php /** @see \Formation\Controller\DemandeExterneController::refuserDrhAction() */ ?>
                            <a href="<?php echo $this->url('formation/demande-externe/refuser-drh', ['demande-externe' => $demande->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon icon-ko text-danger"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endforeach; ?>


<style>
    table#formation .action {
        min-width: 6rem;
        width: 6rem;
    }

    table#formation .etat {
        min-width: 6rem;
        width: 6rem;
    }

    table#formation .periode {
        min-width: 15rem;
        width: 15rem;
    }
</style>
