<?php

use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Entity\Db\Mission;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;

/**
 * @see \FicheMetier\Controller\MissionPrincipaleController::afficherAction();
 * @var Mission $mission
 * @var FicheMetier[] $fichesmetiers
 * @var bool $codeFonction
 * @var bool $modification
 * @var ?string $retour
 */

$canAfficherFicheMetier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));

?>

<?php if ($mission->estHistorise()) : ?>
    <span class="badge" style="background:darkred; font-size: larger;">
        Historisée
    </span>
    <br>
    <br>
<?php endif; ?>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt> Libellé de la mission</dt>
            <dd> <?php echo $mission->getLibelle(); ?> </dd>
            <?php if ($mission->getDescription() !== null) : ?>
                <dt> Description</dt>
                <dd> <?php echo $mission->getDescription(); ?> </dd>
            <?php endif; ?>
            <dt class="col-md-4"> Famille·s Professionnelle·s</dt>
            <dd class="col-md-8">
                <?php $familles = $mission->getFamillesProfessionnelles(); ?>
                <?php if (empty($familles)): ?>
                    <em style="color:gray;">Aucune famille professionnelle</em>
                <?php else : ?>
                    <ul>
                        <?php foreach ($mission->getFamillesProfessionnelles() as $famille) : ?>
                            <li> <?php echo $famille->getLibelle(); ?> </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </dd>
            <dt class="col-md-4"> Niveau</dt>
            <dd class="col-md-8">
                <?php if ($mission->getNiveau() === null) : ?>
                    <span class="missing-data">Aucun niveau </span>
                <?php else : ?>
                    <?php echo $this->niveauEnveloppe($mission->getNiveau()); ?>
                <?php endif; ?>
            </dd>
            <dt class="col-md-4"> Référence</dt>
            <dd class="col-md-8">
                <?php if ($mission->getReferentiel() === null and $mission->getReference() === null) : ?>
                    <span class="missing-data">Aucune référence </span>
                <?php else : ?>
                    <?php echo $mission->printReference(); ?>
                <?php endif; ?>
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <?php echo $this->historiqueBloc($mission, ["genre" => "F"]); ?>
    </div>
</div>

<dl>
    <dt> Fiche·s métier·s attachée·s à la mission principale</dt>
    <dd>
        <?php if (empty($fichesmetiers)): ?>
            Aucune fiche métier n'utilise cette mission principale
        <?php else: ?>
            <ul>
                <?php foreach ($fichesmetiers as $fichemetier): ?>
                    <li> <?php echo $fichemetier->getLibelle(); ?>
                        <?php if ($canAfficherFicheMetier) : //todo ajouter le check de l'assertion ?>
                            <small>
                                <?php /** @see \FicheMetier\Controller\FicheMetierController::afficherAction() */ ?>
                                <a href="<?php echo $this->url('fiche-metier/afficher', ['fiche-metier' => $fichemetier->getId()], ['force_canonical' => true], true); ?>"
                                   class="action secondary" target="_blank"
                                >
                                    <span class="icon icon-voir"></span>
                                    Afficher
                                </a>
                            </small>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </dd>
<!--    <dt>Fiche·s de poste listant à la mission principale</dt>-->
<!--    <dd>-->
<!--        --><?php //echo count($fichespostes); ?><!-- fiche·s de poste-->
<!--        <ul>-->
<!--            --><?php //foreach ($fichespostes as $ficheposte) : ?>
<!--                <li>-->
<!--                    --><?php
//                    $ficheId = ($ficheposte->getFicheposte()) ? $ficheposte->getFicheposte()->getId() : null;
//                    $agent = ($ficheposte->getFicheposte() and $ficheposte->getFicheposte()->getAgent()) ? $ficheposte->getFicheposte()->getAgent() : null;
//                    ?>
<!--                    --><?php //echo $this->etatinstance($ficheposte->getFicheposte()->getEtatActif()); ?>
<!--                    --><?php //echo $ficheposte->getFicheposte()->getLibelle() ?? "Fiche sans libellé"; ?>
<!--                    --><?php //if ($agent) : ?>
<!--                        --><?php //echo $agent->getDenomination(); ?>
<!--                    --><?php //else : ?>
<!--                        <span class="text-danger"> Aucun agent d'associé·e</span>-->
<!--                    --><?php //endif; ?>
<!--                    --><?php //if ($ficheId) : ?>
<!--                        (Fiche de poste #--><?php //echo $ficheId; ?><!--)-->
<!--                    --><?php //endif; ?>
<!--                    <small>-->
<!--                        --><?php ///** @see \Application\Controller\FichePosteController::afficherAction() */ ?>
<!--                        <a href="--><?php //echo $this->url('fiche-poste/afficher', ['fiche-poste' => $ficheposte->getFicheposte()->getId()], ['force_canonical' => true], true); ?><!--"-->
<!--                           class="action secondary" target="_blank"-->
<!--                        >-->
<!--                            <span class="icon icon-voir"></span>-->
<!--                            Afficher-->
<!--                        </a>-->
<!--                    </small>-->
<!--                </li>-->
<!--            --><?php //endforeach; ?>
<!--        </ul>-->
<!--    </dd>-->
</dl>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>