<?php

use FicheMetier\Entity\Db\Mission;
use FicheMetier\Provider\Privilege\MissionPrincipalePrivileges;
use Metier\Entity\Db\FamilleProfessionnelle;
use Referentiel\Entity\Db\Referentiel;

/**
 * @see \FicheMetier\Controller\MissionPrincipaleController::indexAction()
 * @var Mission[] $missions
 * @var Referentiel[] $referentiels
 * @var FamilleProfessionnelle[] $familles
 * @var array $params
 */

$this->headTitle('Missions principales');

$canAfficher = $this->isAllowed(MissionPrincipalePrivileges::getResourceId(MissionPrincipalePrivileges::MISSIONPRINCIPALE_AFFICHER));
$canAjouter = $this->isAllowed(MissionPrincipalePrivileges::getResourceId(MissionPrincipalePrivileges::MISSIONPRINCIPALE_AJOUTER));
$canModifier = $this->isAllowed(MissionPrincipalePrivileges::getResourceId(MissionPrincipalePrivileges::MISSIONPRINCIPALE_MODIFIER));
$canHistoriser = $this->isAllowed(MissionPrincipalePrivileges::getResourceId(MissionPrincipalePrivileges::MISSIONPRINCIPALE_HISTORISER));
$canSupprimer = $this->isAllowed(MissionPrincipalePrivileges::getResourceId(MissionPrincipalePrivileges::MISSIONPRINCIPALE_SUPPRIMER));

$canImporter = $this->isAllowed(MissionPrincipalePrivileges::getResourceId(MissionPrincipalePrivileges::MISSIONPRINCIPALE_MODIFIER));
?>


<h1 class="page-header">
    Missions principales
</h1>

<!-- Filtre ----------------------------------------------------------------------------------------------------------->
<div class="card">
    <div class="card-header bg-default">
        <span class="icon icon-filtrer"></span>
        Filtre de recherche des missions principales
    </div>
    <div class="card-body">
        <form method="get" action="<?php echo $this->url('mission-principale', [], [], true); ?>">
        <div class="row">
            <div class="col-md-10">
                <!-- fitres -->
                <div class="row">
                    <div class="col-md-4">
                        <label for="referentiel">Référentiel :</label>
                        <select id="referentiel" name="referentiel" class="form-control selectpicker" data-live-search="true">
                            <option value="">Peu importe</option>
                            <?php foreach ($referentiels as $referentiel) : ?>
                                <option value="<?php echo $referentiel->getId(); ?>" data-content="<?php echo $referentiel->printLabel(); ?>"
                                        <?php if ($params['referentiel'] == $referentiel->getId()) echo 'selected'; ?>
                                >
                                    <?php echo $referentiel->getLibelleLong(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="famille">Famille professionnelle :</label>
                        <select id="famille" name="famille" class="form-control selectpicker" data-live-search="true">
                            <option value="">Peu importe</option>
                            <?php foreach ($familles as $famille) : ?>
                                <option value="<?php echo $famille->getId(); ?>"
                                        <?php if ($params['famille'] == $famille->getId()) echo 'selected'; ?>
                                >
                                    <?php echo $famille->getLibelle(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="histo">Historisation :</label>
                        <select id="histo" name="histo" class="form-control selectpicker">
                            <option value="">Peu importe</option>
                            <option value="0" <?php if ($params['histo'] == 0) echo 'selected'; ?>>Non historisée</option>
                            <option value="1" <?php if ($params['histo'] == 1) echo 'selected'; ?>>Historisée</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <button class="btn btn-primary" id="filter">
                    <span class="icon icon-filtrer"></span>
                    Filtrer
                </button>
                <button class="btn btn-primary" id="clear">
                    <span class="icon icon-gommer"></span>
                    Remise à zéro
                </button>
            </div>
        </div>
        </form>
    </div>
</div>

<!-- Boutons d'actions ------------------------------------------------------------------------------------------------>

<?php if ($canAjouter) : ?>
    <?php /** @see \FicheMetier\Controller\MissionPrincipaleController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('mission-principale/ajouter', [], [], true); ?>"
       class="ajax-modal btn btn-primary"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter une mission principale
    </a>
<?php endif; ?>
<?php if ($canImporter) : ?>
    <?php /** @see \FicheMetier\Controller\MissionPrincipaleController::importerAction() */ ?>
    <a href="<?php echo $this->url('mission-principale/importer', [], [], true); ?>"
       class="btn btn-primary"
    >
        <span class="icon icon-csv"></span>
        Importer des missions principales depuis un csv
    </a>
<?php endif; ?>

<!-- Listing ---------------------------------------------------------------------------------------------------------->

<table class="table table-condensed table-hover" id="missions">
    <thead>
    <tr>
        <th> Libellé</th>
        <th> Famille·s professionnelle·s</th>
        <th> Niveau</th>
        <th style="width: 10rem;"> Liens</th>
        <th class="action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($missions as $mission) : ?>
        <tr class="<?php if ($mission->estHistorise()) echo " historise "; ?>">
            <td class="col-md-6">
                <?php echo $mission->getLibelle(); ?>
                <br>
                <?php echo $mission->printReference(); ?>
                <br>
                <span style="color: #4b4b4b;">
                    <?php echo count($mission->getActivites()); ?> activité·s
                </span>
            </td>
            <td class="col-md-2" data-column-id="Familles professionnelles">
                <?php if (empty($mission->getFamillesProfessionnelles())) : ?>
                    Aucune famille
                <?php else : ?>
                    <?php foreach ($mission->getFamillesProfessionnelles() as $famille) : ?>
                        <li> <?php echo $famille->getLibelle(); ?> </li>
                    <?php endforeach; ?>
                <?php endif; ?>

            </td>
            <td class="col-md-1" data-column-id="Niveau">
                <?php if ($mission->getNiveau() === null) : ?>
                    <p><em>Non précisé</em></p>
                <?php else : ?>
                    <?php echo $this->niveauEnveloppe($mission->getNiveau()); ?>
                <?php endif; ?>
            </td>
            <td class="col-md-2" data-column-id="Liens">
                Fiche métier : <?php echo count($mission->getListeFicheMetier()); ?> <br/>
                Fiche de poste : <?php echo count($mission->getListeFichePoste()); ?>
            </td>
            <td class="action col-md-1" data-column-id="Action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \FicheMetier\Controller\MissionPrincipaleController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('mission-principale/afficher', ['mission-principale' => $mission->getId()], [], true); ?>"
                       class="ajax-modal action secondary"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br/>
                    <?php /** @see \FicheMetier\Controller\MissionPrincipaleController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('mission-principale/modifier', ['mission-principale' => $mission->getId()], [], true); ?>"
                       class="action primary"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($mission->estNonHistorise()): ?>
                        <?php /** @see \FicheMetier\Controller\MissionPrincipaleController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('mission-principale/historiser', ['mission-principale' => $mission->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \FicheMetier\Controller\MissionPrincipaleController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('mission-principale/restaurer', ['mission-principale' => $mission->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\MissionPrincipaleController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('mission-principale/supprimer', ['mission-principale' => $mission->getId()], [], true); ?>"
                       class="ajax-modal action danger" data-event="modification"
                    >
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('table#missions').DataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [4], orderable: false}
            ]
        });
    });

    $('button#clear').click(function(e) {
        e.preventDefault();
        console.log("Clicked");
        window.location.href = '?';
    });
</script>