<?php

use FicheMetier\Form\MissionPrincipale\MissionPrincipaleForm;
use UnicaenRenderer\Entity\Db\Rendu;
use UnicaenRenderer\Provider\Privilege\DocumenttemplatePrivileges;

/**
 * @see \FicheMetier\Controller\MissionPrincipaleController::ajouterAction()
 * @see \FicheMetier\Controller\MissionPrincipaleController::modifierAction()
 * @var MissionPrincipaleForm $form
 * @var Rendu $rendu
 */

$canTemplateModifier = $this->isAllowed(DocumenttemplatePrivileges::getResourceId(DocumenttemplatePrivileges::DOCUMENTTEMPLATE_MODIFIER));

?>

<?php echo $this->form()->openTag($form); ?>

<h3> Description </h3>

<?php echo $this->formControlGroup($form->get('libelle')); ?>
<?php echo $this->formControlGroup($form->get('familleprofessionnelle')); ?>

<h3> Niveau de carrière associé </h3>

<div class="row">
    <div class="col-md-6"><?php echo $this->formControlGroup($form->get('borne_superieure')); ?></div>
    <div class="col-md-6"><?php echo $this->formControlGroup($form->get('borne_inferieure')); ?></div>
</div>



<?php echo $this->formControlGroup($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>



<script>
    $(function() {
        $('select').selectpicker();
        tinymce.remove();
        tinymce.init({
            selector: '.tinymce',
            toolbar: 'newdocument bullist',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck: true,
            branding: false,
            menu: {},
            menubar: false,
            height: 200,
            // body_id: 'description',
            setup: function (editor) {
                editor.on("focusout", function () {
                    // console.log(tinymce.get('description').getContent());
                    $('textarea').val(tinymce.get('description').getContent());
                });
            }
        });
    });
</script>
<!---->
<!--<style>-->
<!--    label[for=activites]::after {-->
<!--            content: "";-->
<!--            display: block;-->
<!--            padding: 10px;-->
<!--            background: #f0f0f0;-->
<!--            border-radius: 5px;-->
<!--            margin: 8px 0;-->
<!--            color: #333;-->
<!--            border-color: var(--bs-info);-->
<!--            border-left-width: 1rem;-->
<!--        }-->
<!--    }-->
<!--</style>-->