<?php

use FicheMetier\Form\MissionPrincipale\MissionPrincipaleForm;
use UnicaenRenderer\Entity\Db\Rendu;

/**
 * @see \FicheMetier\Controller\MissionPrincipaleController::ajouterAction()
 * @see \FicheMetier\Controller\MissionPrincipaleController::modifierAction()
 * @var MissionPrincipaleForm $form
 * @var Rendu $rendu
 */

?>

<?php echo $this->form()->openTag($form); ?>


<!--<h4> Description </h4>-->

<?php echo $this->formControlGroup($form->get('libelle')); ?>
<?php echo $this->formControlGroup($form->get('description')); ?>
<?php echo $this->formControlGroup($form->get('familleprofessionnelle')); ?>
<div class="row">
    <div class="col-md-6"><?php echo $this->formControlGroup($form->get('referentiel')); ?></div>
    <div class="col-md-6"><?php echo $this->formControlGroup($form->get('identifiant')); ?></div>
</div>

<!--<h4> Niveau de carrière associé </h4>-->

<div class="row">
    <div class="col-md-6"><?php echo $this->formControlGroup($form->get('borne_superieure')); ?></div>
    <div class="col-md-6"><?php echo $this->formControlGroup($form->get('borne_inferieure')); ?></div>
</div>


<?php echo $this->formControlGroup($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>


<script>
    $(document).ready(function () {

        tinymce.remove();
        tinymce.init({
            selector: 'textarea.tinymce',
            toolbar: 'newdocument undo redo | bold italic underline removeformat | bullist numlist',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck: true,
            branding: false,
            menu: {},
            menubar: false,
            height: 200,
            // body_id: 'description',
            setup: function (editor) {
                editor.on("focusout", function () {
                    // console.log(tinymce.get('description').getContent());
                    $('textarea').val(tinymce.get('description').getContent());
                });
            }
        });

        $('select:not(.select2)').selectpicker();
        $('.select2').select2();
    });
</script>