<?php

use Application\Entity\Db\MissionSpecifiqueTheme;

/**
 * @see \Application\Controller\MissionSpecifiqueThemeController::afficherAction()
 * @var MissionSpecifiqueTheme $theme
 */

$modificateur = ($theme->getHistoModificateur())?:$theme->getHistoCreateur();
$date = ($theme->getHistoModification())?:$theme->getHistoCreation();
?>

<div class="row">
    <div class="col-md-6">
        <dl>
            <dt> Libellé </dt>
            <dd> <?php echo $theme->getLibelle(); ?></dd>
            <dt> Missions de ce type </dt>
            <dd>
                Nombre de missions : <?php echo count($theme->getMissions()); ?> <br>
                <ul>
                    <?php foreach ($theme->getMissions() as $mission) : ?>
                        <li> <?php echo $mission->getLibelle(); ?> </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl>
            <dt> Dernière modification </dt>
            <dd>
                <?php echo $date->format('d/m/Y à H:i:s'); ?> <br/>
                <?php echo $modificateur->getDisplayName(); ?>
            </dd>
        </dl>

        <?php if ($theme->estHistorise()) : ?>
            <dl>
                <dt> Historisé </dt>
                <dd>
                    <?php echo $theme->getHistoDestruction()->format('d/m/Y à H:i:s'); ?> <br/>
                    <?php echo $theme->getHistoDestructeur()->getDisplayName(); ?>
                </dd>
            </dl>
        <?php endif; ?>
    </div>
</div>
