<?php

use Application\Entity\Db\Activite;
use Application\Entity\Db\FicheMetierTypeActivite;

/**
 * @see \Application\Controller\ActiviteController::afficherAction()
 * @see \Application\Controller\ActiviteController::modifierAction()
 * @var Activite $activite
 * @var string $mode
 */

$applications   = $activite->getApplications();
$competences    = $activite->getCompetences();
$formations      = $activite->getFormations();
?>

<!--<div class="alert alert-warning">-->
<!--    !!! Débug à retirer plus tard !!!-->
<!--    <dl class="dl-horizontal">-->
<!--        <dt> Activite Id</dt>-->
<!--        <dd> --><?php //echo $activite->getId(); ?><!--</dd>-->
<!--        <dt> Mode </dt>-->
<!--        <dd> --><?php //echo $mode; ?><!--</dd>-->
<!--    </dl>-->
<!--</div>-->

<?php if ($mode === 'modifier-activite') : ?>
    <h1 class="page-header">
        Modification de l'activité
    </h1>
<?php endif; ?>

<?php echo $this->activite($activite, $mode); ?>

<?php
    /** @var FicheMetierTypeActivite[] $ficheMetiers */
    $ficheMetiers = $activite->getFichesMetiers()->toArray();
?>
<h2>
    Fiches métiers associées
    <span class="badge">
        <?php echo  count($ficheMetiers); ?>
    </span>
</h2>

<ul>
    <?php foreach ($ficheMetiers as $ficheMetier) : ?>
        <li> <?php echo $ficheMetier->getFiche()->getMetier()->getLibelle(); ?> </li>
    <?php endforeach; ?>
</ul>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });
    });
</script>