<?php

/**
 * @var Activite[] $activites
 */

use Application\Entity\Db\Activite;
use Application\Provider\Privilege\ActivitePrivileges;

$this->headTitle('Index des activités');

$canAjouter     = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::AJOUTER));
$canEditer      = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::EDITER));
$canEffacer     = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::EFFACER));
?>

<h1>
    Activité
    <span class="badge"> <?php echo count($activites); ?> </span>
</h1>

<div class="main">

    <?php if ($canAjouter) : ?>
        <a href="<?php echo $this->url('activite/creer', [], [], true); ?>"
           class="btn btn-primary action ajax-modal"
           data-event="modification"
           >
            <i class="fas fa-plus-square"></i>
            Ajouter une activité
        </a>
        <br/><br/>
    <?php endif; ?>

    <table class="table table-condensed">
        <thead>
            <th> Id </th>
            <th> Activité </th>
            <th> Dernière modification </th>
            <th> Action </th>
        </thead>
        <tbody>
            <?php foreach($activites as $activite) : ?>
                <tr>
                    <td> <?php echo $activite->getId(); ?> </td>
                    <td>
                        <?php echo $activite->getLibelle(); ?> <br/>
                        <div class="alert alert-info">
                            <?php echo $activite->getDescription(); ?>
                        </div>
                    </td>
                    <td>
                        <?php echo $activite->getHistoModification()->format('H:i d/m/Y'); ?> <br/>
                        <?php echo $activite->getHistoModificateur()->getDisplayName(); ?>
                    </td>
                    <td>
                        <?php if ($canEditer) : ?>
                            <a href="<?php echo $this->url('activite/editer', ['id' => $activite->getId()], [], true); ?>"
                               class="ajax-modal"
                               data-event="modification"
                            >
                                <i class="fas fa-pencil-alt" title="Éditer l'activité"></i>
                            </a>
                        <?php endif; ?>
                        <?php if ($canEffacer) : ?>
                        <a href="<?php echo $this->url('activite/effacer', ['id' => $activite->getId()], [], true); ?>">
                            <i class="fas fa-trash-alt"  title="Supprimer l'activité"></i>
                        </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
