<?php

/**
 * @var Activite[] $activites
 */

use Application\Entity\Db\Activite;
use Application\Provider\Privilege\ActivitePrivileges;

$this->headTitle('Index des activités');

$canVisualiser  = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::AFFICHER));
$canAjouter     = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::AJOUTER));
$canEditer      = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::EDITER));
$canHistoriser  = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::EDITER));
$canEffacer     = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::EFFACER));
?>

<h1>
    Activité
    <span class="badge"> <?php echo count($activites); ?> </span>
</h1>

<div class="main">

    <?php if ($canAjouter) : ?>
        <a href="<?php echo $this->url('activite/creer', [], [], true); ?>"
           class="btn btn-primary action ajax-modal"
           data-event="modification"
           >
            <span class="icon ajouter"></span>
            Ajouter une activité
        </a>
        <br/><br/>
    <?php endif; ?>

    <table class="table table-condensed">
        <thead>
<!--            <th> Id </th>-->
            <th> Activité </th>
            <th> Modification </th>
            <th> Modificateur </th>
            <th> Action </th>
        </thead>
        <tbody>
            <?php foreach($activites as $activite) : ?>
                <tr>
<!--                    <td> --><?php //echo $activite->getId(); ?><!-- </td>-->
                    <td>
                        <?php echo $activite->getLibelle(); ?> <br/>
                    </td>
                    <td>
                        <?php echo $activite->getHistoModification()->format('d/m/Y'); ?>
                    </td>
                    <td>
                        <?php echo $activite->getHistoModificateur()->getDisplayName(); ?>
                    </td>
                    <td>
                        <?php if ($canVisualiser) : ?>
                            <a href="<?php echo $this->url('activite/afficher', ['activite' => $activite->getId()], [], true); ?>"
                               class="ajax-modal"
                            >
                                <span class="icon voir" title="Voir l'activité"></span></a>
                        <?php endif; ?>
                        <?php if ($canEditer) : ?>
                            <a href="<?php echo $this->url('activite/editer', ['activite' => $activite->getId()], [], true); ?>"
                               class="ajax-modal"
                               data-event="modification"
                            >
                                <span class="icon editer" title="Éditer l'activité"></span></a>
                        <?php endif; ?>
                        <?php if($canHistoriser) :?>
                            <?php if($activite->estNonHistorise()): ?>
                                <a href="<?php echo $this->url('activite/historiser', ['activite' => $activite->getId()], [], true); ?>"
                                >
                                    <span class="icon historiser" title="Historiser l'activité"></span></a>
                            <?php else : ?>
                                <a href="<?php echo $this->url('activite/restaurer', ['activite' => $activite->getId()], [], true); ?>"
                                >
                                    <span class="icon restaurer" title="Restaurer l'activité"></span></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canEffacer) : ?>
                            <a href="<?php echo $this->url('activite/detruire', ['activite' => $activite->getId()], [], true); ?>">
                                <span class="icon detruire"  title="Supprimer l'activité"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
