<?php

/**
 * @var FormulaireInstance $instance
 * @var string $url
 * @var FormulaireReponse[] $reponses
 */

use Autoform\Entity\Db\Categorie;
use Autoform\Entity\Db\Champ;
use Autoform\Entity\Db\FormulaireInstance;
use Autoform\Entity\Db\FormulaireReponse;

$formulaire = $instance->getFormulaire();

?>

<form class="autoform" method="post" action="<?php echo $url; ?>" >

<!--    <span id="hide" class="btn btn-info"> Cacher les catégories </span>-->
<!--    <span id="show" class="btn btn-info">Afficher les catégories </span>-->
    <input type="submit" value="Valider le formulaire" class="btn btn-primary"/>

    <br/>
    <br/>

    <?php
    /** @var \Autoform\Entity\Db\Categorie[] $categories */
    $categories = $formulaire->getCategories();
    $categories = array_filter($categories, function (Categorie $categorie) { return $categorie->estNonHistorise();});
    usort($categories, function (Categorie $a, Categorie $b) { return $a->getOrdre() - $b->getOrdre();});
    ?>

    <?php foreach ($categories as $categorie) : ?>

        <?php
        /** @var \Autoform\Entity\Db\Champ[] $champs */
        $champs = $categorie->getChamps();
        $champs = array_filter($champs, function (Champ $champ) { return $champ->estNonHistorise();});
        usort($champs, function (Champ $a, Champ $b) { return $a->getOrdre() - $b->getOrdre();});
        ?>

        <?php if (!empty($champs)) : ?>

            <div class="categorie">
                <h3 class="categorie"> <?php echo $categorie->getLibelle(); ?> </h3>

                <div class="champs">
                    <?php foreach ($champs as $champ) : ?>
                        <div> <?php echo $this->champAsInput()->render($champ, $reponses); ?> </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

    <?php endforeach; ?>

    <input type="submit" value="Valider le formulaire" class="btn btn-primary"/>
</form>

<script>
    // $('div.body-reductible').each(function() { $(this).hide()});
    //
    // $('div.title-reductible').click(function() {
    //     $(this).siblings().each(function() { $(this).toggle(); });
    // });
    //
    // $('span#hide').click(function() {
    //     $('div.body-reductible').each(function() { $(this).hide()});
    // });
    //
    // $('span#show').click(function() {
    //     $('div.body-reductible').each(function() { $(this).show()});
    // });

    $("select.periode").change(function() {
        checkPeriode($(this));
    });

    $("select.periode").each(function() {
        checkPeriode($(this));
    });

    // $('.selectpicker').selectpicker();

</script>

<style>
    h3.categorie {
        border-bottom: 1px solid #31708f;
    }

    div.categorie div.champs {
        margin-left: 2rem;
        width:95%;
    }
</style>