<?php

/**
 * @var FicheMetier $fichemetier
 * @var array $applications
 * @var string $mode
 */

use FicheMetier\Entity\Db\FicheMetier;

$actions = ['modifier' => false, 'supprimer' => false, 'valider' => false];
if ($mode === 'edition-fiche-metier') {
    $actions['modifier'] = true;
    $actions['supprimer'] = true;
}

?>

<div class="card info">
    <div class="card-header">
        <div class="row">
            <div class="col-md-3">
                <h2>
                    <span class="icon application"></span>
                    Applications
                    <span class="badge"><?php echo count($applications); ?></span>
                </h2>
            </div>
            <div class="col-md-9">
                <div class="float-end">
                    <?php /** @see \FicheMetier\Controller\GraphiqueController::graphiqueApplicationsAction() */ ?>
                    <a href="<?php echo $this->url('graphique/applications', ['fiche-metier' => $fichemetier->getId()], [], true); ?>"
                       class="btn btn-secondary action ajax-modal" style="margin: 0 0.5rem;"
                    >
                        <span class="icon icon-diagramme"></span>
                        Afficher les applications
                    </a>

                    <?php if ($actions['modifier'] === true) : ?>
                        <?php /** @see \FicheMetier\Controller\FicheMetierController::gererApplicationsAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/gerer-applications', ['fiche-metier' => $fichemetier->getId()], [], true); ?>"
                           class="btn btn-primary ajax-modal" data-event="modification">
                            <span class="icon icon-gerer"></span>
                            Gérer les applications
                        </a>
                    <?php endif; ?>

<!--                    --><?php //if ($actions['modifier'] === true) : ?>
<!--                        --><?php ///** @see \Application\Controller\FicheMetierController::clonerApplicationsAction() */ ?>
<!--                        <a href="--><?php //echo $this->url('fiche-metier-type/cloner-applications', ['fiche-metier' => $fichemetier->getId()], [], true); ?><!--"-->
<!--                           class="btn btn-primary action ajax-modal" style="margin: 0 0.5rem;"-->
<!--                           data-event="modification"-->
<!--                        >-->
<!--                            <span class="icon icon-cloner"></span>-->
<!--                            Cloner depuis une autre fiche-->
<!--                        </a>-->
<!--                    --><?php //endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <?php echo $this->applicationBloc($applications, $fichemetier,
            ['display' => ['titre' => false, 'validation' => false, 'raison' => false],
                'actions' => $actions]); ?>
    </div>
</div>