<?php

/**
 * @see \FicheMetier\Controller\FicheMetierController::refreshMissionsAction()
 * @var FicheMetier $fichemetier
 * @var MissionElement[] $missions
 * @var string $mode
 */

use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Entity\Db\MissionElement;
use FicheMetier\Provider\Privilege\FicheMetierPrivileges;

$actions = ['modifier' => false, 'supprimer' => false, 'valider' => false];
if ($mode === 'edition-fiche-metier') {
    $actions['modifier'] = true;
    $actions['supprimer'] = true;
}

$canModifier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));
?>

<div id="missions_view">
    <div class="card info">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6"><h2> Missions principales </h2></div>
                <div class="col-md-6">
                    <div class="float-end">
                        <?php if ($mode === 'edition-fiche-metier' and $canModifier) : ?>
                            <?php /** @see FicheMetierController::gererMissionsPrincipalesAction() */ ?>
                            <a class="btn btn-primary ajax-modal" style="margin: 0 0.5rem;"
                               data-event="refresh-missions"
                               href="<?php echo $this->url('fiche-metier/gerer-missions-principales', ['fiche-metier' => $fichemetier->getId()], [], true); ?>">
                                <span class="icon icon-listing"></span>
                                Gérer
                            </a>
                            <?php /** @see FicheMetierController::purgerMissionsPrincipalesAction() */ ?>
                            <a class="btn btn-warning ajax-modal" style="margin: 0 0.5rem;"
                               data-event="refresh-missions"
                               href="<?php echo $this->url('fiche-metier/purger-missions-principales', ['fiche-metier' => $fichemetier->getId()], [], true); ?>">
                                <span class="icon icon-nettoyer"></span>
                                Purger
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body" style="color:rgb(80,80,80);">
            <?php if (empty($missions)): ?>
                <span class="missing-data"> Aucune mission </span>
            <?php else : ?>
                <ul>
                    <?php foreach ($missions as $mission) : ?>
                        <li>
                            <?php echo $mission->getMission()->printReference() ?>
                            <?php echo $mission->getMission()->getLibelle(); ?>
                            <?php if ($mode === "edition-fiche-metier" and $canModifier) : ?>
                                <div style="display: inline-block;">
                                    <small>
                                        <?php /** @see \FicheMetier\Controller\FicheMetierController::bougerMissionAction() */ ?>
                                        <span class="missions-ajax action primary icon icon-monter"
                                              data-url="<?php echo $this->url('fiche-metier/bouger-mission', ['fiche-metier' => $fichemetier->getId(), 'mission-element' => $mission->getId(), 'direction' => '-1'], [], true); ?>"
                                        >
                            </span>
                                        <?php /** @see \FicheMetier\Controller\FicheMetierController::bougerMissionAction() */ ?>
                                        <span class="missions-ajax action primary icon icon-descendre "
                                              data-url="<?php echo $this->url('fiche-metier/bouger-mission', ['fiche-metier' => $fichemetier->getId(), 'mission-element' => $mission->getId(), 'direction' => '1'], [], true); ?>"
                                        >
                            </span>
                                        <?php /** @see \FicheMetier\Controller\FicheMetierController::retirerMissionAction() */ ?>
                                        <span class="missions-ajax action danger icon icon-unchecked"
                                              data-url="<?php echo $this->url('fiche-metier/retirer-mission', ['fiche-metier' => $fichemetier->getId(), 'mission-element' => $mission->getId()], [], true); ?>"
                                        >
                            </span>
                                    </small>
                                </div>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>
</div>

<script>
    function refreshMissions() {
        <?php /** @see \FicheMetier\Controller\FicheMetierController::refreshMissionsAction() */ ?>
        let url = "<?php echo $this->url("fiche-metier/refresh-missions", ['fiche-metier' => $fichemetier->getId(), 'mode' => $mode]); ?>";
        console.log("refreshing activites");
        $.ajax({
            type: "POST",
            url: url,
            beforeSend:
                function () {
                    $("#missions_view").addClass('refreshing');
                },
            success:
                function (retour) {
                    $("#missions_view").html(retour).removeClass('refreshing');
                }
        });
    }

    $(".missions-ajax").on("click", function (event) {
        let url = $(this).data("url");
        $("#missions_view").addClass('refreshing');
        $.ajax({
            type: "POST",
            url: url,
            success:
                function () {
                    refreshMissions();
                }
        });
    });
</script>
