<?php

/**
 * @var FicheMetier $fichemetier
 * @var array $competences
 * @var string $mode
 */

use FicheMetier\Entity\Db\FicheMetier;

$actions = ['modifier' => false, 'supprimer' => false, 'valider' => false];
if ($mode === 'edition-fiche-metier') {
    $actions['modifier'] = true;
    $actions['supprimer'] = true;
}

?>

<div class="card info">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h2>
                    <span class="icon competence"></span>
                    Compétences
                    <span class="badge"><?php echo count($competences); ?></span>
                </h2>
            </div>
            <div class="col-md-6">
                <div class="float-end">
                    <?php /** @see \FicheMetier\Controller\GraphiqueController::graphiqueCompetencesAction() */ ?>
                    <a href="<?php echo $this->url('graphique/competences', ['fiche-metier' => $fichemetier->getId()], [], true); ?>"
                       class="btn btn-secondary ajax-modal"
                    >
                        <span class="icon icon-diagramme"></span>
                        Afficher les compétences
                    </a>

                    <?php if ($actions['modifier'] === true) : ?>
                        <?php /** @see \FicheMetier\Controller\FicheMetierController::gererCompetencesAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/gerer-competences', ['fiche-metier' => $fichemetier->getId()], [], true); ?>"
                           class="btn btn-primary ajax-modal" style="margin: 0 0.5rem;"
                           data-event="modification"
                        >
                            <span class="icon icon-lister"></span>
                            Gérer les compétences
                        </a>
                    <?php endif; ?>

<!--                    --><?php //if ($actions['modifier'] === true) : ?>
<!--                        --><?php ///** @see \Application\Controller\FicheMetierController::clonerCompetencesAction() */ ?>
<!--                        <a href="--><?php //echo $this->url('fiche-metier-type/cloner-competences', ['fiche-metier' => $fichemetier->getId()], [], true); ?><!--"-->
<!--                           class="btn btn-primary action ajax-modal" style="margin: 0 0.5rem;"-->
<!--                           data-event="modification"-->
<!--                        >-->
<!--                            <span class="icon icon-cloner"></span>-->
<!--                            Cloner depuis une autre fiche-->
<!--                        </a>-->
<!--                    --><?php //endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <?php echo $this->competenceBloc($competences, $fichemetier,
            ['display' => ['titre' => false, 'validation' => false, 'raison' => false], 'mode' => $mode,
                'actions' => $actions]); ?>
    </div>
</div>