<?php

/**
 * @var FicheMetier $fichemetier
 * @var array $competences
 * @var string $mode
 */

use Element\Entity\Db\CompetenceType;
use FicheMetier\Entity\Db\FicheMetier;

$actions = ['modifier' => false, 'supprimer' => false, 'valider' => false];
if ($mode === 'edition-fiche-metier') {
    $actions['modifier'] = true;
    $actions['supprimer'] = true;
}

?>

<div class="card info">
    <div class="card-header">
        <div class="row">
            <div class="col-md-7">
                <h2>
                    <span class="icon competence"></span>
                    Compétences spécifiques
                </h2>
            </div>
            <div class="col-md-5">
                <div class="float-end">
                    <?php if ($actions['modifier'] === true) : ?>
                        <?php /** @see \FicheMetier\Controller\FicheMetierController::gererCompetencesSpecifiquesAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/gerer-competences-specifiques', ['fiche-metier' => $fichemetier->getId()], [], true); ?>"
                           class="btn btn-primary ajax-modal" style="margin: 0 0.5rem;"
                           data-event="refresh-competences"
                           data-competence-type="<?php echo CompetenceType::CODE_SPECIFIQUE; ?>"
                        >
                            <span class="icon icon-lister"></span>
                            Gérer les compétences
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div id="competence_SPEC">
            &nbsp;
        </div>
    </div>
</div>