<?php

/**
 * @var EtatType[] $etatTypes
 * @var array $params
 */

use UnicaenEtat\Entity\Db\EtatType;

?>


<div class="card" style="margin-top: 0.5rem; margin-bottom: 0.5rem;">
    <div class="card-header bg-default">
        <span class="icon icon-filtrer"></span> Filtre des fiches métiers
    </div>
    <div class="card-body">
        <form method="get" id="filtre" action="<?php echo $this->url(); ?>">
            <div class="row">
                <div class="col-md-10">
                    <div class="row">
                        <!-- ETAT -->
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="etat">État de la fiche :</label>
                                <select id="etat" name="etat" class="selectpicker">
                                    <option value=""> Tous les états</option>
                                    <?php foreach ($etatTypes as $etatType) : ?>
                                        <option
                                                value="<?php echo $etatType->getId(); ?>"
                                                data-content='<?php echo $this->etattype($etatType); ?> <?php echo str_replace("'", "", $etatType->getLibelle()); ?>'
                                            <?php if ($etatType->getId() === $params['etat']) echo " selected "; ?>
                                        >
                                            <?php echo $etatType->getLibelle(); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <!-- EXPERTISE -->
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="expertise">Sujet à expertise:</label>
                                <select id="expertise" name="expertise" class="selectpicker">
                                    <option value="">Pas de sélection</option>
                                    <option value="1" <?php if ("1" == $params['expertise']) echo " selected "; ?>>Oui
                                    </option>
                                    <option value="0" <?php if ("0" == $params['expertise']) echo " selected "; ?>>Non
                                    </option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- BOUTON -->
                <div class="col-md-2">
                    <button class="btn btn-primary" id="filter">
                        <span class="icon icon-filtrer"></span>
                        Filtrer
                    </button>
                    <button class="btn btn-primary" id="clear">
                        <span class="icon icon-gommer"></span>
                        Remise à zéro
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    $("form#filtre").on("submit", function (e) {
        e.preventDefault();
    });

    $('button#clear').on("click", function () {
        window.location.href = 'fiche-metier';
    });

    $('button#filter').on("click", function () {
        let etatId = $('select#etat option:selected').val();
        let expertise = $('select#expertise').val();
        console.log("etat=" + etatId + " | "  + "expertise=" + expertise);

        let query = "";
        query += "&etat=" + etatId;
        query += "&expertise=" + expertise;
        window.location.href = 'fiche-metier?' + query;
    });
</script>