<?php

/**
 * @var Referentiel[] $referentiels
 * @var EtatType[] $etatTypes
 * @var CodeFonction[] $codesFonctions
 * @var array $params
 * @var bool $displayCodeFonction
 */

use FicheMetier\Entity\Db\CodeFonction;
use Referentiel\Entity\Db\Referentiel;
use UnicaenEtat\Entity\Db\EtatType;

?>


<div class="card" style="margin-top: 0.5rem; margin-bottom: 0.5rem;">
    <div class="card-header bg-default">
        <span class="icon icon-filtrer"></span> Filtre des fiches métiers
    </div>
    <div class="card-body">
        <form method="get" id="filtre" action="<?php echo $this->url(); ?>">
            <div class="row">
                <div class="col-md-10">
                    <div class="row">
                        <!-- REFERENTIEL -->
                        <div class="col-md-4">
                            <label for="referentiel">Référentiel :</label>
                            <select id="referentiel" name="referentiel" class="form-control selectpicker"
                                    data-live-search="true">
                                <option value="">Peu importe</option>
                                <?php foreach ($referentiels as $referentiel) : ?>
                                    <option value="<?php echo $referentiel->getId(); ?>"
                                            data-content="<?php echo $referentiel->printLabel(); ?>"
                                            <?php if ($params['referentiel'] == $referentiel->getId()) echo 'selected'; ?>
                                    >
                                        <?php echo $referentiel->getLibelleLong(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <!-- ETAT -->
                        <div class="col-md-4">
                            <label for="etat">État de la fiche :</label>
                            <br>
                            <select id="etat" name="etat" class="selectpicker">
                                <option value=""> Tous les états</option>
                                <?php foreach ($etatTypes as $etatType) : ?>
                                    <option
                                            value="<?php echo $etatType->getId(); ?>"
                                            data-content='<?php echo $this->etattype($etatType); ?> <?php echo str_replace("'", "", $etatType->getLibelle()); ?>'
                                            <?php if ($etatType->getId() === $params['etat']) echo " selected "; ?>
                                    >
                                        <?php echo $etatType->getLibelle(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <!-- CODE FONCTION -->
                        <?php if ($displayCodeFonction) : ?>
                            <div class="col-md-4">
                                <label for="codefonction">Code fonction :</label>
                                <br>
                                <select id="codefonction" name="codefonction" class="selectpicker">
                                    <option value=""> Tous les codes fonctions</option>
                                    <?php foreach ($codesFonctions as $codefonction) : ?>
                                        <option
                                                value="<?php echo $codefonction->getId(); ?>"
                                                data-content='<code><?php echo $codefonction->computeCode(); ?></code>'
                                                <?php if ($codefonction->getId() == $params['codefonction']) echo " selected "; ?>
                                        >
                                            <?php echo $codefonction->computeCode(); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <!-- BOUTON -->
                <div class="col-md-2">
                    <button class="btn btn-primary" id="filter">
                        <span class="icon icon-filtrer"></span>
                        Filtrer
                    </button>
                    <button class="btn btn-primary" id="clear">
                        <span class="icon icon-gommer"></span>
                        Remise à zéro
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    $('button#clear').click(function (e) {
        e.preventDefault();
        console.log("Clicked");
        window.location.href = '?';
    });
</script>