<?php

use Application\Provider\Privilege\FicheMetierPrivileges;
use FicheMetier\Entity\Db\FicheMetier;

/**
 * @var FicheMetier $fichemetier
 * @var string $mode
 */

$canEditer = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));

$metier = $fichemetier->getMetier();
$libelle = $metier->getLibelle();

?>

<div class="card">
    <div class="card-header bg-default">
        <div class="row">
            <div class="col-md-8">
                <h3>Raison d'être du métier dans l'établissement</h3>
            </div>
            <div class="col-md-4">
                <?php if ($canEditer AND $mode === 'edition-fiche-metier' ) : ?>
                    <div class="float-end">
                        <?php /** @see FicheMetierController::modifierRaisonAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier/modifier-raison', ['fiche-metier' => $fichemetier->getId()], [], true); ?>"
                           class="btn btn-primary ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-editer"></span>
                            Modifier la raison
                        </a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="card-body">
        <?php if ($fichemetier->getRaison() !== null) : ?>
            <?php echo $fichemetier->getRaison(); ?>
        <?php else :?>
            Aucune raison de fournie
        <?php endif; ?>
    </div>
</div>

