<?php

use Application\Provider\Privilege\FicheMetierPrivileges;
use FicheMetier\Entity\Db\FicheMetier;

/**
 * @var FicheMetier $fichemetier
 * @var string $mode
 */

$canEditer = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));

$metier = $fichemetier->getMetier();

?>

<dl class="row">
    <dt class="col-md-4"> État</dt>
    <dd class="col-md-8">
        <?php echo $this->etatinstance($fichemetier->getEtatActif()); ?>
    </dd>
    <dt class="col-md-4"> Domaine</dt>
    <dd class="col-md-8">
        <?php $domaines = $metier->getDomaines(); ?>
        <?php if (!empty($domaines)) : ?>
            <?php foreach ($domaines as $domaine) : ?>
                <?php echo $domaine->getLibelle(); ?>
            <?php endforeach; ?>
        <?php else : ?>
            Aucun domaine
        <?php endif; ?>
    </dd>
    <dt class="col-md-4"> Références</dt>
    <dd class="col-md-8">
        <?php
        $references = $metier->getReferences();
        $first = true;
        ?>
        <?php if (!empty($references)) : ?>
            <?php foreach ($references as $reference) : ?>
                <?php if ($first) : ?>
                    <?php $first = false; ?>
                <?php else : ?>
                    <br/>
                <?php endif; ?>
                <a href="<?php echo $reference->getUrl(); ?>">
                    <?php echo $reference->getTitre(); ?>
                </a>
            <?php endforeach; ?>
        <?php else : ?>
            Aucune référence
        <?php endif; ?>
    </dd>
    <dt class="col-md-4"> Expertise</dt>
    <dd class="col-md-8">
        <?php if ($fichemetier->hasExpertise()) : ?>
            Sujet à expertise
        <?php else : ?>
            Non sujet à expertise
        <?php endif; ?>
        <?php if ($mode === 'edition-fiche-metier') : ?>
            <a
                <?php /** @see FicheMetierController::modifierExpertiseAction() */ ?>
                    href="<?php echo $this->url('fiche-metier/modifier-expertise', ['fiche-fiche' => $fichemetier->getId()], [], true); ?>"
            >
                <span class="icon icon-synchroniser"></span>
            </a>
        <?php endif; ?>
    </dd>
    <dt class="col-md-4"> Niveau</dt>
    <dd class="col-md-8">
        <?php $enveloppe = $metier->getNiveaux(); ?>
        <?php if ($enveloppe !== null) : ?>
            De <?php echo $enveloppe->getBorneInferieure()->getLibelle(); ?> (<?php echo $enveloppe->getBorneInferieure()->getEtiquette(); ?>)
            à <?php echo $enveloppe->getBorneSuperieure()->getLibelle(); ?> (<?php echo $enveloppe->getBorneSuperieure()->getEtiquette(); ?>)
        <?php else : ?>
            Non renseigné
        <?php endif; ?>
    </dd>
</dl>
