<?php

use Application\Provider\Privilege\FicheMetierPrivileges;
use FicheMetier\Entity\Db\FicheMetier;

/**
 * @var FicheMetier $fichemetier
 * @var string $titre
 * @var string $mode
 */

$canModifier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));

?>


<h1 class="page-header">
    <?php echo ($mode === 'affichage')?'Affichage':'Modification'; ?> de la fiche métier
    <br>
    <span style="font-weight:bold; color: var(--unistrap-color-main);">
            <?php echo $fichemetier->getLibelle(); ?>
    </span>
</h1>
<?php if ($mode !== 'affichage' AND $canModifier): ?>
    <?php /** @see \FicheMetier\Controller\FicheMetierController::modifierLibelleAction() */ ?>
    <a href="<?php echo $this->url('fiche-metier/modifier-libelle', ['fiche-metier' => $fichemetier->getId()], [], true); ?>"
       class="action primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-editer"></span>
        Modifier le libellé
    </a>
<?php endif; ?>
