<?php

use FicheReferentiel\Entity\Db\FicheReferentiel;
use FicheReferentiel\Provider\Privilege\FichereferentielPrivileges;

/**
 * @see \FicheReferentiel\Controller\FicheReferentielController::indexAction()
 * @var FicheReferentiel[] $fiches
 */

$this->headTitle('Fiche Référentiel');

$canFicheAfficher = $this->isAllowed(FichereferentielPrivileges::getResourceId(FichereferentielPrivileges::FICHEREFERENTIEL_AFFICHER));

?>

<h1 class="page-header">
    Fiche Référentiel
</h1>

<a href="<?php echo $this->url('fiche-referentiel/importer-dgafp-csv'); ?>"
   class="btn btn-primary">
    Importer depuis un CSV (format DGAFP)
</a>

<table class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Id </th>
        <th> Référentiel </th>
        <th> Métier </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($fiches as $fiche) : ?>
        <tr>
            <td> <?php echo $fiche->getId(); ?></td>
            <td> <span class="badge"><?php echo $fiche->getReferentiel()->getLibelleCourt(); ?></span></td>
            <td> <?php echo $fiche->getMetier()->getLibelle(); ?></span></td>
            <td class="action">
                <?php if ($canFicheAfficher): ?>
                    <a href="<?php echo $this->url('fiche-referentiel/afficher', ['fiche-referentiel' => $fiche->getId()], [], true); ?>">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

