<?php

use Metier\Entity\Db\Metier;
use Metier\Entity\Db\Reference;
use Metier\Entity\Db\Referentiel;

/**
 * @see \Metier\Controller\ReferentielController::afficherAction()
 * @var Referentiel $referentiel
 * @var Reference[] $references
 * @var Metier[] $metiers
 */

usort($references, function (Reference $a, Reference $b) {return $a->getCode() <=> $b->getCode();});
?>

<dl class="row">
    <dt class="col-md-4"> Référentiel </dt>
    <dd class="col-md-8"> <?php echo $referentiel->getLibelleLong(); ?> </dd>
    <dt class="col-md-4"> Métier·s référencé·s</dt>
    <dd class="col-md-8">
        <?php if (empty($references)) : ?>
            <em>Aucun métier de référencé</em>
        <?php else : ?>
            <ul>
            <?php foreach ($references as $reference) : ?>
                <li> <?php echo $reference->getCode(); ?> - <?php echo $metiers[$reference->getCode()]->getLibelle(); ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </dd>
</dl>
