<?php

/**
 * @see \Metier\Controller\ReferentielController::indexAction()
 * @var Referentiel[] $referentiels
 * @var boolean[] $droits
 */

use Metier\Entity\Db\Referentiel;
use Metier\Provider\Privilege\ReferentielmetierPrivileges;

$canAfficher = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_AFFICHER));
$canAjouter = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_AJOUTER));
$canEditer = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_MODIFIER));
$canHistoriser = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_HISTORISER));
$canEffacer = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_SUPPRIMER));

$canAction = ($canAfficher or $canAjouter or $canEditer or $canHistoriser or $canEffacer);

$this->headTitle("Liste des référentiels métiers");
?>

<h1 class="page-header">
    Liste des référentiels métiers
</h1>

<?php if ($canAjouter) : ?>
    <a <?php /** @see \Metier\Controller\ReferentielController::ajouterAction() */ ?>
            href="<?php echo $this->url('metier/referentiel/ajouter', [], [], true); ?>"
            class="btn btn-primary ajax-modal"
            data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un référentiel métier
    </a>
<?php endif; ?>

<table class="datatable table table-condensed" id="referentiels">
    <thead>
    <tr>
        <th> Libelle</th>
        <th> Préfix</th>
        <th> Type</th>
        <?php if ($canAction) : ?>
            <th class="cell-action"> Action</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($referentiels as $referentiel) : ?>
        <tr <?php if ($referentiel->estHistorise()) echo 'class="historise"'; ?>>
            <td>
                [<strong><?php echo $referentiel->getLibelleCourt(); ?></strong>]
                <?php echo $referentiel->getLibelleLong(); ?>
            </td>
            <td>
                <?php if ($referentiel->getPrefix()) : ?>
                    <span class="icon icon-checked" style="color:darkgreen"
                          title="<?php echo $referentiel->getPrefix(); ?>"></span>
                <?php else: ?>
                    <span class="icon icon-unchecked" style="color:darkred"></span>
                <?php endif; ?>
            </td>
            <td>
                <?php echo $referentiel->getType(); ?>
            </td>
            <?php if ($canAction) : ?>
                <td class="action">
                    <?php if ($canAfficher) : ?>
                        <a
                            <?php /** @see \Metier\Controller\ReferentielController::afficherAction() */ ?>
                                href="<?php echo $this->url('metier/referentiel/afficher', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                class="ajax-modal action secondary"
                        >
                            <span class="icon icon-voir"></span>
                            Afficher
                        </a>
                    <?php endif; ?>
                    <?php if ($canEditer) : ?>
                        <br>
                        <a
                            <?php /** @see \Metier\Controller\ReferentielController::modifierAction() */ ?>
                                href="<?php echo $this->url('metier/referentiel/modifier', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                class="ajax-modal action primary"
                                data-event="modification"
                        >
                            <span class="icon icon-editer"></span>
                            Modifier
                        </a>
                    <?php endif; ?>
                    <?php if ($canHistoriser) : ?>
                        <br>
                        <?php if ($referentiel->estNonHistorise()) : ?>
                            <a <?php /** @see \Metier\Controller\ReferentielController::historiserAction() */ ?>
                                    href="<?php echo $this->url('metier/referentiel/historiser', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                    class="action warning"
                            >
                                <span class="icon icon-historiser"></span>
                                Historiser
                            </a>
                        <?php else : ?>
                            <a <?php /** @see \Metier\Controller\ReferentielController::restaurerAction() */ ?>
                                    href="<?php echo $this->url('metier/referentiel/restaurer', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                    class="action warning"
                            >
                                <span class="icon icon-restaurer"></span>
                                Restaurer
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canEffacer) : ?>
                        <br/>
                        <a <?php /** @see \Metier\Controller\ReferentielController::supprimerAction() */ ?>
                                href="<?php echo $this->url('metier/referentiel/supprimer', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                class="ajax-modal action danger" data-event="modification"
                        >
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </a>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('#referentiels').DataTable({
            autoWidth: false,
            order: [[0, 'asc'], [1, 'asc']],
            columnDefs: [{
                "targets": 3,
                "orderable": false
            }],
            language: {
                url: '/js/datatables_fr.json'
            }
        });
    });
</script>