<?php

/**
 * @see \Metier\Controller\ReferentielController::indexAction()
 * @var Referentiel[] $referentiels
 * @var boolean[] $droits
 */

use Metier\Entity\Db\Referentiel;
use Metier\Provider\Privilege\ReferentielmetierPrivileges;

$canAfficher       = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_AFFICHER));
$canAjouter        = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_AJOUTER));
$canEditer         = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_MODIFIER));
$canHistoriser     = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_HISTORISER));
$canEffacer        = $this->isAllowed(ReferentielmetierPrivileges::getResourceId(ReferentielmetierPrivileges::REFERENTIEL_SUPPRIMER));

?>

<h1 class="page-header">
    Liste des référentiels metiers
</h1>

<?php if ($canAjouter) : ?>
    <a  <?php /** @see \Metier\Controller\ReferentielController::ajouterAction() */ ?>
            href="<?php echo $this->url('metier/referentiel/ajouter', [], [], true);?>"
            class="btn btn-primary action ajax-modal"
            data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un référentiel métier
    </a>
<?php endif;?>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Libelle </th>
        <th> Préfix </th>
        <th> Type </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($referentiels as $referentiel) : ?>
        <tr <?php if ($referentiel->estHistorise()) echo 'class="historise"'; ?>>
            <td>
                [<strong><?php echo $referentiel->getLibelleCourt(); ?></strong>]
                <?php echo $referentiel->getLibelleLong(); ?>
            </td>
            <td>
                <?php if ($referentiel->getPrefix()) : ?>
                    <span class="icon icon-checked" style="color:darkgreen" title="<?php echo $referentiel->getPrefix(); ?>"></span>
                <?php else: ?>
                    <span class="icon icon-retirer" style="color:darkred"></span>
                <?php endif; ?>
            </td>
            <td>
                <?php echo $referentiel->getType(); ?>
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <span class="icon icon-voir"></span>
                    Afficher
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <br>
                    <a
                        <?php /** @see \Metier\Controller\ReferentielController::modifierAction() */ ?>
                        href="<?php echo $this->url('metier/referentiel/modifier', ['referentiel' => $referentiel->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($referentiel->estNonHistorise()) : ?>
                        <a  <?php /** @see \Metier\Controller\ReferentielController::historiserAction() */ ?>
                            href="<?php echo $this->url('metier/referentiel/historiser', ['referentiel' => $referentiel->getId()], [], true); ?>"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <a  <?php /** @see \Metier\Controller\ReferentielController::restaurerAction() */ ?>
                            href="<?php echo $this->url('metier/referentiel/restaurer', ['referentiel' => $referentiel->getId()], [], true); ?>"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <br/>
                    <a  <?php /** @see \Metier\Controller\ReferentielController::supprimerAction() */ ?>
                        href="<?php echo $this->url('metier/referentiel/supprimer', ['referentiel' => $referentiel->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-retirer"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>