<?php
/**
 * @var Champ $champ
 * @var string $data
 */

use Autoform\Entity\Db\Champ;

?>
<?php if ($data !== null && $data != '') : ?>
    <?php $splits = explode(";", (string) $data); ?>
    <?php echo $champ->getLibelle(); ?>&nbsp;:
    <?php echo $libelles = explode(';',$champ->getOptions()); ?>
    <?php $size = max(count($libelles), count($splits)); ?>
    <ul>
        <?php for($position = 0 ; $position < $size ; $position ++) : ?>
            <li>
                <?php $sub = explode("|", $libelles[$position]); ?>
                <?php echo $sub[1] ?> :
                <?php
                    $resplits = str_replace("_"," ",$splits[$position]);
                    echo $resplits;
                ?>
            </li>
        <?php endfor; ?>
    </ul>
<?php endif; ?>
