<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FichePostePrivileges;
use Structure\Entity\Db\Structure;

/**
 * @var FichePoste $fiche
 * @var Agent $agent
 * @var Structure|null $structure
 * @var string mode
 */

$canModifier = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_MODIFIER);

?>

<div class="card panel-info">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h2> Environnement du poste de travail </h2>
            </div>
        </div>
    </div>
    <div class="card-body">
        <?php
            $structures = [];
            if ($agent !== null) $structures = $agent->getStructures();
            else if ($structure !== null) $structures[] = $structure;
        ?>
        <?php if (empty($structures)) : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucune structure.
            </div>
        <?php else: ?>
            <?php foreach ($structures as $structure) : ?>
                <h4> <?php echo $structure->getLibelleLong(); ?> </h4>

                <?php if ($structure->getDescriptionComplete() !== null) :?>
                    <?php echo $structure->getDescriptionComplete(); ?>
                <?php else: ?>
                    <div class="alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i>
                        Aucune description de fournie pour l'affectation <em><?php echo $structure->getLibelleCourt(); ?></em>.
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>