<?php

use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FichePostePrivileges;

/**
 * @var FichePoste $fiche
 * @var string mode
 */

$canModifier = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_MODIFIER);

$poste = $fiche->getPoste();
$structure=($poste)?$poste->getStructure():null;

?>

<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2> Environnement du poste de travail </h2>
            </div>
            <div class="col-md-6">
                <?php if($mode === 'edition' AND $canModifier) : ?>
                    <?php /** @see \Application\Controller\FichePosteController::associerPosteAction() */ ?>
                    <a href="<?php echo $this->url('fiche-poste/associer-poste',['fiche-poste' => $fiche->getId()], ["query" => ["structure" => ($structure)?$structure->getId():null, "sous-structure" => $sousstructure]], true); ?>"
                       class="btn btn-primary action ajax-modal pull-right"
                       data-event="modification"
                    >
                        <span class="icon selectionner"></span>
                        Associer un poste
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <h3> Affectation du poste </h3>
        <?php if ($structure !== null) : ?>
            <?php if ($structure->getDescription() !== null) :?>
                <?php echo $structure->getDescription(); ?>
            <?php else: ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucune description de fournie pour l'affectation <em><?php echo $structure->getLibelleCourt(); ?></em>.
                </div>
            <?php endif; ?>
        <?php else : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucune affectation de renseignée.
            </div>
        <?php endif; ?>

        <h3> Positionnement dans l'établissement</h3>
        <?php if ($poste === null) : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucun poste n'est attaché à ce poste
            </div>
        <?php else: ?>
            <?php echo $this->poste($poste); ?>
        <?php endif; ?>
    </div>
</div>