<?php

// echo $this->partial('partial/information-poste', ['fiche' => $fiche, 'mode' => 'affichage']);
/**
 * @var AgentPoste[] $postes
 * @var string $mode
 * @var FichePoste $fiche
 */

use Application\Entity\Db\AgentPoste;
use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FichePostePrivileges;
use FichePoste\Provider\Parametre\FichePosteParametres;

$canAfficher = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER_POSTE));
$canModifier = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER_POSTE));
?>

<?php if ($canAfficher) : ?>
    <div class="card ">
        <div class="card-header ">
            <div class="row">
                <div class="col-md-8">
                    <h2>Information sur le poste associé</h2>
                </div>
                <div class="col-md-3">
                    <?php if ($mode === 'edition' AND $canModifier) : ?>
                        <?php /** @see \Application\Controller\FichePosteController::modifierInformationPosteAction() */ ?>
                        <a  href="<?php echo $this->url('fiche-poste/modifier-information-poste', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                            class="btn btn-primary ajax-modal" data-event="modification">
                            <span class="icon icon-editer"></span>
                            Modifier les informations
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="card-body">
            <?php if (!isset($parametres[FichePosteParametres::CODE_FONCTION]) || $parametres[FichePosteParametres::CODE_FONCTION]->getValeur() !== "false") : ?>
            <dl class="row">
                <dt class="col-md-3">
                    Code fonction
                </dt>
                <dd class="col-md-9">
                    <?php if ($fiche->getCodeFonction()) : ?>
                        <code> <?php echo $fiche->getCodeFonction(); ?> </code>
                    <?php else : ?>
                        Non renseigné
                    <?php endif; ?>

                    <?php if ($mode === 'edition' AND $canModifier) : ?>
                        <?php /** @see FichePosteController::modifierCodeFonctionAction() */ ?>
                        <a href="<?php echo $this->url('fiche-poste/modifier-code-fonction', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                           class="ajax-modal action primary" data-event="modification"
                        >
                            <small>
                                <span class="icon icon-editer"></span>
                                Modifier
                            </small>
                        </a>
                    <?php endif; ?>
                </dd>
            </dl>
            <?php endif; ?>


            <?php if (empty($postes)) : ?>
                Informations non renseignées
            <?php else : ?>
                <?php foreach ($postes as $poste) : ?>
                <dl class="row">
                    <dt class="col-md-2"> Code du poste</dt>
                    <dd class="col-md-2">
                        <?php if ($poste->getCode()) : ?>
                            <?php echo $poste->getCode(); ?>
                        <?php else : ?>
                            Non renseigné
                        <?php endif; ?>
                    </dd>
                    <dt class="col-md-2"> Intitulé </dt>
                    <dd class="col-md-6">
                        <?php if ($poste->getLibelle()) : ?>
                            <?php echo $poste->getLibelle(); ?>
                        <?php else : ?>
                            Non renseigné
                        <?php endif; ?>
                    </dd>
                </dl>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
