<?php

// echo $this->partial('partial/information-poste', ['fiche' => $fiche, 'mode' => 'affichage']);
/**
 * @var AgentPoste[] $postes
 * @var string $mode
 */

use Application\Entity\Db\AgentPoste;
use Application\Provider\Privilege\FichePostePrivileges;

$canAfficher = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER_POSTE));
$canModifier = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER_POSTE));
?>

<?php if ($canAfficher) : ?>
    <div class="card ">
        <div class="card-header ">
            <div class="row">
                <div class="col-md-8">
                    <h2>Information sur le poste associé</h2>
                </div>
                <div class="col-md-3">
                    <?php if ($mode === 'edition' AND $canModifier) : ?>
                        <?php /** @see \Application\Controller\FichePosteController::modifierInformationPosteAction() */ ?>
                        <a  href="<?php echo $this->url('fiche-poste/modifier-information-poste', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                            class="btn btn-primary ajax-modal" data-event="modification">
                            <span class="icon icon-editer"></span>
                            Modifier les informations
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="card-body">
            <?php if (empty($postes)) : ?>
                Informations non renseignées
            <?php else : ?>
                <?php foreach ($postes as $poste) : ?>
                <dl class="row">
                    <dt class="col-md-2"> Code du poste</dt>
                    <dd class="col-md-2">
                        <?php if ($poste->getCode()) : ?>
                            <?php echo $poste->getCode(); ?>
                        <?php else : ?>
                            Non renseigné
                        <?php endif; ?>
                    </dd>
                    <dt class="col-md-2"> Intitulé </dt>
                    <dd class="col-md-6">
                        <?php if ($poste->getLibelle()) : ?>
                            <?php echo $poste->getLibelle(); ?>
                        <?php else : ?>
                            Non renseigné
                        <?php endif; ?>
                    </dd>
                </dl>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
