<?php

use Application\Entity\Db\FichePoste;

/**
 * @var FichePoste $ficheposte
 */

$ficheprincipale = null;
if ($ficheposte->getFicheTypeExternePrincipale()) {
    $ficheprincipale = $ficheposte->getLibelleMetierPrincipal(FichePoste::TYPE_GENRE);
}else {
    $ficheprincipale = "Aucune fiche métier principale";
}
$saisielibre = $ficheposte->getLibelle();

?>

<?php if ($saisielibre) : ?>
    <strong>
        <?php echo $saisielibre; ?>
    </strong>
    <br/>
    Rattaché à
<?php endif; ?>
<strong>
    <?php echo $ficheprincipale; ?>
</strong>



