<?php


/**
 * @var Agent $agent
 * @var FichePoste $fiche
 * @var string $mode
 * @var array $parcours
 * @var array $options
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\FichePoste;


$canValidate = false;
?>

<div class="row">
    <div class="col-md-10" style="margin-left:5rem;background-color:#d9edf7;">
        <h3 style="color:#3c6c8b;">
            <span class="icon formation"></span>
            Parcours d'entrée dans le métier
        </h3>
    </div>
    <div class="col-md-1" style="background-color:#d9edf7;">
        <h3>&nbsp;</h3>
    </div>
</div>

<div class="row" style="margin: 1rem;">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <?php ksort($parcours); ?>
        <?php foreach ($parcours as $subparcours) : ?>
        <?php foreach ($subparcours as $parcours) : ?>
            <?php echo $this->parcoursDeFormation($parcours, $agent, ['mode' => 'modification', 'modification' => $canValidate]); ?>
        <?php endforeach; ?>
        <?php endforeach; ?>

        <?php if($fiche !== null) : ?>
            <?php echo $this->parcoursApplication($fiche, $agent, $options); ?>
        <?php endif; ?>
    </div>
</div>
