<?php

/** @var Structure $structure */

use Structure\Provider\Privilege\StructurePrivileges;
use Structure\Entity\Db\Structure;

$canGereStructure = $this->isAllowed(StructurePrivileges::getResourceId(StructurePrivileges::STRUCTURE_AFFICHER));

?>

<div class="row">
    <?php if ($structure !== null AND $canGereStructure) : ?>
        <a href="<?php echo $this->url('structure/fiches-de-poste', ['structure' => $structure->getId()], [], true); ?>"
           class="btn btn-primary action" style="margin:1rem;">
            <span class="icon icon-retour"></span>
            Retour vers  la structure
        </a>
    <?php endif; ?>
</div>
