<?php

use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FichePostePrivileges;

/**
 * @var FichePoste $fiche
 * @var string $mode
 */

$canEditerSpecificte = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_MODIFIER);
$date = new DateTime();

?>

<div class="card panel-info">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h2> <span title="Régime indemnitaire des fonctionnaires de l'État">RIFSEEP</span> et <span title="Nouvelle bonification indiciaire">NBI</span> </h2>
            </div>
            <div class="col-md-6">
                <?php if($canEditerSpecificte AND  $mode === 'edition') : ?>
                    <a
                        <?php /** @see \Application\Controller\FichePosteController::editerRifseepAction(); */ ?>
                            href="<?php echo $this->url('fiche-poste/editer-rifseep',['fiche-poste' => $fiche->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal pull-right"
                            data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Renseigner le RIFSEEP et NBI
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="card-body">
        <dl>
            <dt> Régime indemnitaire des fonctionnaires de l'État (RIFSEEP) </dt>
            <dd> <?php echo ($fiche->getRifseep())?"Groupe ".$fiche->getRifseep():"Non renseigné"; ?> </dd>
            <dt> Nouvelle bonification indiciaire (NBI) </dt>
            <dd> <?php echo ($fiche->getNbi())?$fiche->getNbi()." point(s)":"Non renseignée"; ?> </dd>
        </dl>
    </div>
</div>
