<?php

use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FichePostePrivileges;
use FichePoste\Entity\Db\MissionAdditionnelle;

/**
 * @var FichePoste $fiche
 * @var string $mode
 */

$canEditerSpecificte = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_MODIFIER);
$date = new DateTime();

?>

<?php if ($fiche->getSpecificite() !== NULL OR  $mode === 'edition') : ?>
    <div class="card panel-info">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <h2> Spécificités du poste </h2>
                </div>
                <div class="col-md-6">
                    <?php if($canEditerSpecificte AND  $mode === 'edition') : ?>
                        <a
                            <?php /** @see \Application\Controller\FichePosteController::editerSpecificiteAction(); */ ?>
                            href="<?php echo $this->url('fiche-poste/editer-specificite',['fiche-poste' => $fiche->getId()], [], true); ?>"
                            class="btn btn-primary action ajax-modal pull-right"
                            data-event="modification"
                        >
                            <span class="icon icon-editer"></span>
                            Renseigner les spécificités
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="card-body">
            <?php if ($mode === 'edition') : ?>
            <?php endif; ?>
            <?php echo $this->specificitePoste($fiche, $fiche->getSpecificite(), ["mode" => $mode]); ?>
        </div>

        <?php
            $canAjouterActivite = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_MODIFIER);
            $missionsAdditionnelles = $fiche->getMissionsAdditionnelles();
            usort($missionsAdditionnelles, function (MissionAdditionnelle $a, MissionAdditionnelle $b) { return $a->getMission()->getLibelle() > $b->getMission()->getLibelle();});
        ?>

        <?php if (!empty($missionsAdditionnelles)) : ?>
            <div class="row">
                <div class="col-md-8">
                    <h3> Autres missions additionnelles au poste </h3>
                </div>
            </div>

            <?php if ($mode === 'edition' AND $canAjouterActivite) : ?>
                <?php /** @see \Application\Controller\SpecificiteController::ajouterActiviteAction() */ ?>
                <a href="<?php echo $this->url('specificite/ajouter-activite', ['fiche-poste' => $fiche->getId(), 'specificite-poste' => ($fiche->getSpecificite())?$fiche->getSpecificite()->getId():null], [], true); ?>"
                   class="btn btn-primary action ajax-modal" data-event="modification">
                    <span class="icon icon-ajouter"></span>
                    Ajouter une mission additionnelle
                </a>
            <?php endif; ?>

            <?php foreach ($missionsAdditionnelles as $missionAdditionnelle) : ?>
                <?php echo $this->specificiteActivite($missionAdditionnelle, ['fiche' => $fiche, 'mode' => $mode]); ?>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
<?php endif; ?>