<?php

use UnicaenContact\Entity\Db\Contact;
use UnicaenContact\Entity\Db\Type;
use UnicaenContact\Provider\Privilege\ContacttypePrivileges;

/**
 * @see \UnicaenContact\Controller\ContactController::indexAction()
 * @var Contact[] $contacts
 */

$this->headTitle('Contacts');

$canAjouter = $this->isAllowed(ContacttypePrivileges::getResourceId(ContacttypePrivileges::CONTACTTYPE_AJOUTER));
$canAfficher = $this->isAllowed(ContacttypePrivileges::getResourceId(ContacttypePrivileges::CONTACTTYPE_AFFICHER));
$canModifier = $this->isAllowed(ContacttypePrivileges::getResourceId(ContacttypePrivileges::CONTACTTYPE_MODIFIER));
$canHistoriser = $this->isAllowed(ContacttypePrivileges::getResourceId(ContacttypePrivileges::CONTACTTYPE_HISTORISER));
$canSupprimer = $this->isAllowed(ContacttypePrivileges::getResourceId(ContacttypePrivileges::CONTACTTYPE_SUPPRIMER));
?>

<h1 class="page-header">
    Contacts
</h1>

<?php if ($canAjouter) : ?>
    <?php /** @see \UnicaenContact\Controller\TypeController::ajouterAction() */ ?>
    <a
        href="<?php echo $this->url('unicaen-contact/contact/ajouter', [],[], true); ?>"
        class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un contact
    </a>
<?php endif; ?>

<table class="table table-condensed datatable" id="contacts">
    <thead>
    <tr>
        <th> Type </th>
        <th> Service/Dénomination </th>
        <th> Contact </th>
        <th class="action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($contacts as $contact): ?>
        <tr class="<?php if ($contact->estHistorise()) echo " historise"; ?>">
            <td> <code> <?php echo $contact->getType()->getCode(); ?> </code> </td>
            <td>
                <?php if ($contact->getService()) : ?>
                    <?php echo $contact->getService(); ?>
                <?php else : ?>
                    Aucun service renseigné
                <?php endif; ?>
                <br>
                <?php if ($contact->getPrenom()) : ?>
                    <?php echo $contact->getPrenom(); ?>
                <?php else : ?>
                    Aucun prénom renseigné
                <?php endif; ?>
                <?php if ($contact->getNom()) : ?>
                    <?php echo $contact->getNom(); ?>
                <?php else : ?>
                    Aucun nom renseigné
                <?php endif; ?>
            </td>
            <td>
                <?php if ($contact->getTelephone()) : ?>
                    Téléphone : <?php echo $contact->getTelephone(); ?>
                <?php else : ?>
                    Aucun téléphone renseigné
                <?php endif; ?>
                <br>
                <?php if ($contact->getEmail()) : ?>
                    Adresse électronique : <?php echo $contact->getEmail(); ?>
                <?php else : ?>
                    Aucune adresse électronique renseignée
                <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canAjouter) : ?>
                    <?php /** @see \UnicaenContact\Controller\ContactController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('unicaen-contact/contact/afficher', ['contact' => $contact->getId()], [], true); ?>"
                       class="action secondary ajax-modal">
                        <span class="icon icon-voir"></span>
                        Visualiser
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \UnicaenContact\Controller\ContactController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('unicaen-contact/contact/modifier', ['contact' => $contact->getId()], [], true); ?>"
                       class="action primary ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($contact->estNonHistorise()) : ?>
                        <?php /** @see \UnicaenContact\Controller\ContactController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('unicaen-contact/contact/historiser', ['contact' => $contact->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \UnicaenContact\Controller\ContactController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('unicaen-contact/contact/restaurer', ['contact' => $contact->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \UnicaenContact\Controller\ContactController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('unicaen-contact/contact/supprimer', ['contact' => $contact->getId()], [], true); ?>"
                       class="action danger ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span>
                        Restaurer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('table#contacts').dataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [4], orderable: false }
            ]
        });
    });
</script>