<?php

/**
 * @var bool $estAnnulee
 * @var FormationInstance $session
 */

use Formation\Entity\Db\Formateur;
use Formation\Entity\Db\FormationInstance;
use Formation\Provider\Privilege\FormateurPrivileges;
use Formation\Provider\Privilege\FormationinstancePrivileges;

$canFormateurAjouter = $this->isAllowed(FormateurPrivileges::getResourceId(FormateurPrivileges::FORMATEUR_AJOUTER));
$canFormateurModifier = (!$estAnnulee and $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_GERER_FORMATEUR)));

$formateurs = $session->getFormateurs();
usort($formateurs, function (Formateur $a, Formateur $b) {
    return (strcmp($a->getDenomination(), $b->getDenomination()));
});

?>

<div class="row">
    <div class="col-md-6">
        <h2>Formateur(s) </h2>
    </div>
    <div class="col-md-6">
        <?php if ($canFormateurAjouter) : ?>
            <?php /** @see \Formation\Controller\FormateurController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('formation/formateur/ajouter', [], [], true); ?>"
               class="action btn btn-primary ajax-modal" data-event="modification"
            >
                <span class="icon icon-ajouter"></span>
                Créer un·e formateur·trice
            </a>
        <?php endif; ?>
        <?php if ($canFormateurModifier) : ?>
            <?php /** @see \Formation\Controller\FormationInstanceController::ajouterFormateurAction() */ ?>
            <a href="<?php echo $this->url('formation/session/ajouter-formateur', ['session' => $session->getId()], [], true); ?>"
               class="action btn btn-primary ajax-modal" data-event="modification"
            >
                <span class="icon icon-ajouter"></span>
                Ajouter un·e formateur·trice
            </a>
        <?php endif; ?>
    </div>
</div>
<?php if (empty($formateurs)) : ?>
    <div class="alert alert-warning">
        <strong>
            <span class="icon icon-attention"></span>
            Aucun formateur de déclaré pour cette formation.
        </strong>
        <br/>
        Sans formateur la formation ne pourra être ouverte.
    </div>
<?php else : ?>
    <table id="formateurs" class="table table-condensed">
        <thead>
        <tr>
            <th> Dénomination</th>
            <th> Structure de rattachement</th>
            <th> Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($formateurs as $formateur) : ?>
            <tr class="<?php echo ($formateur->estHistorise()) ? "historise" : ""; ?>">
                <td>
                    <?php echo $formateur->getDenomination(); ?>
                    <?php if ($formateur->getUtilisateur() !== null) : ?>
                        <span class="icon icon-information text-info" title="Compte utilisateur associé (<?php echo $formateur->getUtilisateur()->getUsername(); ?>)"></span>
                    <?php else : ?>
                        <span class="icon icon-attention text-warning" title="Aucun compte utilisateur associé"></span>
                    <?php endif; ?>
                </td>
                <td> <?php echo ($formateur->getAttachement()) ?: "Non renseigné"; ?> </td>
                <td class="action">
                    <?php if ($canFormateurModifier) : ?>
                        <?php /** @see \Formation\Controller\FormationInstanceController::retirerFormateurAction() */ ?>
                        <a href="<?php echo $this->url('formation/session/retirer-formateur', ['session' => $session->getId(), 'formateur' => $formateur->getId()], [], true); ?>">
                                        <span class="text-danger">
                                            <span class="icon icon-unchecked"></span>
                                            Retirer
                                        </span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table><br/>
<?php endif; ?>