<?php

/**
 * @var FormationInstance $instance
 */

use Formation\Entity\Db\FormationInstance;
use Formation\Provider\Etat\InscriptionEtats;
use Formation\Provider\Etat\SessionEtats;
use Formation\Provider\Privilege\FormationinstancefraisPrivileges;
use Formation\Provider\Privilege\FormationinstancePrivileges;


$principales = $instance->getListePrincipale();
$complementaires = $instance->getListeComplementaire();
$historises = $instance->getListeHistorisee();

$estAnnulee = ($instance->getEtatActif() && $instance->isEtatActif(SessionEtats::ETAT_SESSION_ANNULEE));

$canAfficherIndividu    = true;
$canInscritModifier     = (!$estAnnulee && $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_GERER_INSCRIPTION)));
$canFraisAfficher       = false; //$this->isAllowed(FormationinstancefraisPrivileges::getResourceId(FormationinstancefraisPrivileges::FORMATIONINSTANCEFRAIS_AFFICHER));
$canFraisModifier       = (!$estAnnulee &&  $this->isAllowed(FormationinstancefraisPrivileges::getResourceId(FormationinstancefraisPrivileges::FORMATIONINSTANCEFRAIS_MODIFIER)));

$urlRetour = $this->url('formation-instance/afficher', ['formation-instance' => $instance->getId()], ['fragment' => 'inscriptions'], true);
?>

<div class="row">
    <div class="col-md-6">
        <h2> Inscription·s </h2>
    </div>

    <div class="col-md-6">
        <?php if ($canInscritModifier AND (count($principales) < $instance->getNbPlacePrincipale() OR count($complementaires) < $instance->getNbPlaceComplementaire())) : ?>
            <a <?php /**  @see \Formation\Controller\InscriptionController::ajouterAction() */ ?>
                href="<?php echo $this->url('formation/inscription/ajouter', ['session' => $instance->getId()], [], true); ?>"
                class="btn btn-primary action ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un·e inscription
            </a>
        <?php endif; ?>
    </div>

</div>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<?php
$liste = $instance->getListeDisponible();
$principaleComplete = $instance->isListePrincipaleComplete();
$complementaireComplete = $instance->isListeComplementaireComplete();
$inscriptions = $instance->getInscriptions()
?>

<table id="agents" class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Dénomination </th>
        <th> Affection principale </th>
        <th style="width:6rem;"> Statut </th>
        <th style="width:13rem;"> Date de demande </th>
        <th style="width:6rem;"> Liste </th>
        <th style="width:13rem;"> État </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($inscriptions as $inscription) : ?>
        <?php if ($inscription->estNonHistorise()) : ?>
        <tr <?php if ($inscription->estHistorise()) echo " class='historise' "; ?>>
            <td>
                <?php echo $inscription->getStagiaireDenomination(); ?>
            </td>
            <td> <?php echo $inscription->getStagiaireStructure(); ?> </td>
            <td>
                <?php if ($inscription->isInterne()) : ?>
                    <?php echo $inscription->getAgent()->getStatutToString(); ?>
                <?php endif; ?>
                <?php if ($inscription->isExterne()) : ?>
                    Stagiaire Externe
                <?php endif; ?>
            </td>
            <td> <?php echo $inscription->getHistoCreation()->format('d/m/Y'); ?> </td>
            <td> <?php echo $inscription->getListe()??"Aucune"; ?> </td>
            <td> <?php echo $this->etatinstance($inscription->getEtatActif()); ?> </td>
            <td class="action">

                <?php if ($canAfficherIndividu) : ?>
                    <?php if ($inscription->isInterne()) : ?>
                        <a href="<?php echo $this->url('formation/agent', ['agent' => $inscription->getAgent()->getId()], [], true); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true" title="Afficher la fiche de <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span>"
                        >
                            <span class="icon icon-user"></span> Afficher </a>
                    <?php endif; ?>
                    <?php if ($inscription->isExterne()) : ?>
                        <a href="<?php echo $this->url('stagiaire-externe/afficher', ['stagiaire-externe' => $inscription->getStagiaire()->getId()], [], true); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true" title="Afficher la fiche de <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span>"
                        >
                            <span class="icon icon-user"></span> Afficher </a>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($canInscritModifier && $inscription->isEtatActif(InscriptionEtats::ETAT_VALIDER_RESPONSABLE)) : ?>
                    <?php  /** @see \Formation\Controller\InscriptionController::validerDrhAction() */ ?>
                    <a href="<?php echo $this->url('formation/inscription/valider-drh', ['inscription' => $inscription->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon icon-checked text-success"> Valider</span>  </a>
                    <?php  /** @see \Formation\Controller\InscriptionController::refuserDrhAction() */ ?>
                    <a href="<?php echo $this->url('formation/inscription/refuser-drh', ['inscription' => $inscription->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon icon-unchecked text-danger"> Refuser</span>  </a>
                <?php endif; ?>

                <?php if ($inscription->isEtatActif(InscriptionEtats::ETAT_VALIDER_DRH) && $inscription->getListe() === null) :?>
                    <br>
                    <?php  /** @see \Formation\Controller\InscriptionController::classerAction() */ ?>
                    <a href="<?php echo $this->url('formation/inscription/classer', ['inscription' => $inscription->getId()], [], true); ?>">
                        <span class="icon icon-sort" title="Classer l'inscription"></span> Classer</a>
                <?php endif; ?>

                    <br>
                    <?php /** @see \Formation\Controller\InscriptionController::historiserAgentAction() */?>
                    <a  href="<?php echo $this->url('formation/inscription/historiser', ['inscription' => $inscription->getId()], ['query' => ['retour' => $urlRetour] ], true); ?>"
                        data-bs-toggle="tooltip" data-bs-html="true" title="Retirer <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> de la formation"
                    >
                        <span class="icon icon-historiser"></span>
                        Historiser
                    </a>

                    <br>
                    <?php /** @see \Formation\Controller\InscriptionController::supprimerAction() */?>
                    <a  href="<?php echo $this->url('formation/inscription/supprimer', ['inscription' => $inscription->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                        data-bs-toggle="tooltip" data-bs-html="true" title="Retirer définitivement <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> de la formation."
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>
            </td>
        </tr>
        <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table><br/>

<h4>
    Liste principale
    (<?php echo count($principales); ?>/<?php echo $instance->getNbPlacePrincipale(); ?>)
    <?php if ($instance->isListePrincipaleComplete()) : ?>
        <span class="label label-success"> Complète</span>
    <?php endif; ?>
</h4>

<table id="agents" class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Dénomination </th>
        <th style="width:26rem;"> Affection principale </th>
        <th style="width:6rem;"> Statut </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($principales as $inscription) : ?>
        <tr <?php if ($inscription->estHistorise()) echo " class='historise' "; ?>>
            <td> <?php echo $inscription->getStagiaireDenomination(); ?> </td>
            <td> <?php echo $inscription->getStagiaireStructure(); ?> </td>
            <td>
                <?php if ($inscription->isInterne()) : ?>
                    <?php echo $inscription->getAgent()->getStatutToString(); ?>
                <?php endif; ?>
                <?php if ($inscription->isExterne()) : ?>
                    Stagiaire Externe
                <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canInscritModifier) : ?>
                    <?php if ($inscription->isInterne()) : ?>
                        <a href="<?php echo $this->url('formation/agent', ['agent' => $inscription->getAgent()->getId()], [], true); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true" title="Afficher la fiche de <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span>"
                        >
                            <span class="icon icon-user"></span> Afficher </a>
                    <?php endif; ?>
                    <?php if ($inscription->isExterne()) : ?>
                        <a href="<?php echo $this->url('stagiaire-externe/afficher', ['stagiaire-externe' => $inscription->getStagiaire()->getId()], [], true); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true" title="Afficher la fiche de <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span>"
                        >
                            <span class="icon icon-user"></span> Afficher </a>
                    <?php endif; ?>
                    <br>
                    <?php /** @see FormationInstanceDocumentController::genererConvocationAction() */?>
                    <a  href="<?php echo $this->url('formation-instance/generer-convocation', ['inscription' => $inscription->getId()], [], true); ?>"
                        data-toogle="tooltip" data-bs-html="true" title="Générer la convocation">
                        <span class="icon icon-pdf"></span>
                        Convocation
                    </a>
                    <br>
                    <?php /** @see FormationInstanceDocumentController::genererAttestationAction() */?>
                    <a  href="<?php echo $this->url('formation-instance/generer-attestation', ['inscription' => $inscription->getId()], [], true); ?>"
                        data-toogle="tooltip" data-bs-html="true" title="Générer l'attestation">
                        <span class="icon icon-pdf"></span>Attestation</a>
                    <?php if ($canFraisAfficher) : ?>
                        <?php if ($canFraisModifier) : ?>
                            <br>
                            <?php /** @see FormationInstanceFraisController::renseignerFraisAction() */?>
                            <a href="<?php echo $this->url('formation-instance/renseigner-frais', ['inscrit' => $inscription->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                            >
                        <?php endif; ?>
                        <span class="icon icon-euro" data-bs-toggle="tooltip" data-bs-html="true" title="Frais de missions pour <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span><br/><?php echo ($inscription->getFrais())?$inscription->getFrais()->afficheFrais():"Aucun"; ?>"></span>
                        <?php if ($canFraisModifier) : ?>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if (! $complementaireComplete) : ?>
                        <br>
                        <?php /** @see \Formation\Controller\InscriptionController::envoyerListeComplementaireAction() */?>
                        <a  href="<?php echo $this->url('formation/inscription/envoyer-liste-complementaire', ['inscription' => $inscription->getId()], [], true); ?>"
                            data-bs-toggle="tooltip" data-bs-html="true" title="Déplacer <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> en liste complémentaire."
                        >
                            <span class="icon icon-descendre"></span> Liste comp.</a>
                    <?php endif; ?>
                    <?php if ($inscription->estNonHistorise()) : ?>
                        <br>
                        <?php /** @see FormationInstanceInscritController::historiserAgentAction() */?>
                        <a  href="<?php echo $this->url('formation/inscription/historiser', ['inscription' => $inscription->getId()], [], true); ?>"
                            data-bs-toggle="tooltip" data-bs-html="true" title="Retirer <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> de la formation"
                        >
                            <span class="icon icon-historiser"></span> Historiser</a>
                    <?php endif; ?>
                    <?php /** @see FormationInstanceInscritController::supprimerAgentAction() */?>
                    <br>
                    <a  href="<?php echo $this->url('formation/inscription/supprimer', ['inscription' => $inscription->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                        data-bs-toggle="tooltip" data-bs-html="true" title="Retirer définitivement <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> de la formation."
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span> Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table><br/>

<h4>
    Liste complémentaire
    (<?php echo count($complementaires); ?>/<?php echo $instance->getNbPlaceComplementaire(); ?>)
    <?php if ($instance->isListeComplementaireComplete()) : ?>
        <span class="label label-success"> Complète</span>
    <?php endif; ?>
</h4>
<table id="agents" class="datatable table table-condensed">
    <thead>
    <tr>
        <th > Dénomination </th>
        <th style="width:26rem;"> Affection principale </th>
        <th style="width:6rem;"> Statut </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($complementaires as $inscription) : ?>
        <tr <?php if ($inscription->estHistorise()) echo " class='historise' "; ?>>
            <td> <?php echo $inscription->getStagiaireDenomination(); ?> </td>
            <td> <?php echo $inscription->getStagiaireStructure(); ?> </td>
            <td>
                <?php if ($inscription->isInterne()) : ?>
                    <?php echo $inscription->getAgent()->getStatutToString(); ?>
                <?php endif; ?>
                <?php if ($inscription->isExterne()) : ?>
                    Stagiaire Externe
                <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canInscritModifier) : ?>
                    <?php if ($inscription->isInterne()) : ?>
                        <a href="<?php echo $this->url('formation/agent', ['agent' => $inscription->getAgent()->getId()], [], true); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true" title="Afficher la fiche de <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span>"
                        >
                            <span class="icon icon-user"></span> Afficher </a>
                    <?php endif; ?>
                    <?php if ($inscription->isExterne()) : ?>
                        <a href="<?php echo $this->url('stagiaire-externe/afficher', ['stagiaire-externe' => $inscription->getStagiaire()->getId()], [], true); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true" title="Afficher la fiche de <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span>"
                        >
                            <span class="icon icon-user"></span> Afficher </a>
                    <?php endif; ?>
                    <?php if (! $principaleComplete) : ?>
                        <br/>
                        <?php /** @see \Formation\Controller\InscriptionController::envoyerListePrincipaleAction() */?>
                        <a  href="<?php echo $this->url('formation/inscription/envoyer-liste-principale', ['inscription' => $inscription->getId()], [], true); ?>"
                            data-bs-toggle="tooltip" data-bs-html="true" title="Déplacer <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> en liste principale."
                        >
                            <span class="icon icon-monter"></span> Liste princ.</a>
                    <?php endif; ?>
                    <br>
                    <?php if ($inscription->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\InscriptionController::historiserAction() */?>
                        <a  href="<?php echo $this->url('formation/inscription/historiser', ['inscription' => $inscription->getId()],  ['query' => ['retour' => $urlRetour] ], true); ?>"
                            data-bs-toggle="tooltip" data-bs-html="true" title="Retirer <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> de la formation">
                            <span class="icon icon-historiser"></span> Historiser</a>
                    <?php endif; ?>
                    <br>
                    <?php /** @see FormationInstanceInscritController::supprimerAgentAction() */?>
                    <a  href="<?php echo $this->url('formation/inscription/supprimer', ['inscription' => $inscription->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                        data-bs-toggle="tooltip" data-bs-html="true" title="Retirer définitivement <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> de la formation."
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                            </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table><br/>

<h4>
    Stagiaire·s historisé·es
    (<?php echo count($historises); ?>)
</h4>

<table id="agents" class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th style="width:50rem;"> Dénomination </th>
        <th> Affection principale </th>
        <th style="width:6rem;"> Statut </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($historises as $inscription) : ?>
        <tr <?php if ($inscription->estHistorise()) echo " class='historise' "; ?>>
            <td>
                <?php echo $inscription->getStagiaireDenomination(); ?>
            </td>
            <td> <?php echo $inscription->getStagiaireStructure(); ?> </td>
            <td>
                <?php if ($inscription->isInterne()) : ?>
                    <?php echo $inscription->getAgent()->getStatutToString(); ?>
                <?php endif; ?>
                <?php if ($inscription->isExterne()) : ?>
                    Stagiaire Externe
                <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canInscritModifier) : ?>
                    <?php if ($inscription->isInterne()) : ?>
                        <a href="<?php echo $this->url('formation/agent', ['agent' => $inscription->getAgent()->getId()], [], true); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true" title="Afficher la fiche de <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span>"
                        >
                            <span class="icon icon-user"></span> Afficher </a>
                    <?php endif; ?>
                    <?php if ($inscription->isExterne()) : ?>
                        <a href="<?php echo $this->url('stagiaire-externe/afficher', ['stagiaire-externe' => $inscription->getStagiaire()->getId()], [], true); ?>"
                           data-bs-toggle="tooltip" data-bs-html="true" title="Afficher la fiche de <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span>"
                        >
                            <span class="icon icon-user"></span> Afficher </a>
                    <?php endif; ?>

                    <?php if ($liste !== null) : ?>
                        <br>
                        <?php /** @see \Formation\Controller\InscriptionController::restaurerAction() */?>
                        <a  href="<?php echo $this->url('formation/inscription/restaurer', ['inscription' => $inscription->getId()], ['query' => ['retour' => $urlRetour] ], true); ?>"
                            data-bs-toggle="tooltip" data-bs-html="true" title="Restaurer <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> dans la formation."
                        >
                            <span class="icon icon-restaurer"></span> Restaurer</a>
                    <?php endif; ?>
                    <?php /** @see \Formation\Controller\InscriptionController::supprimerAction() */?>
                    <br>
                    <a  href="<?php echo $this->url('formation/inscription/supprimer', ['inscription' => $inscription->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                        data-bs-toggle="tooltip" data-bs-html="true" title="Retirer définitivement <span class='highlight agent'><?php echo $inscription->getStagiaireDenomination(); ?></span> de la formation."
                    >
                            <span class="text-danger">
                            <span class="icon icon-unchecked"></span> Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>