<?php

/**
 * @var \Structure\Form\Contact\ContactForm $form
 * @var string|null $info
 * @var string|null $warning
 * @var ?Structure $structure
 */

use Laminas\Form\Form;
use Structure\Entity\Db\Structure;

?>

<?php if (isset($info)) : ?>
    <div class="alert alert-info">
        <?php echo $info; ?>
    </div>
<?php endif; ?>

<?php if (isset($warning)) : ?>
    <div class="alert alert-warning">
        <?php echo $warning; ?>
    </div>
<?php endif; ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formControlGroup($form->get('type')); ?>
<?php echo $this->formControlGroup($form->get('service')); ?>
<?php echo $this->formControlGroup($form->get('prenom')); ?>
<?php echo $this->formControlGroup($form->get('nom')); ?>
<?php echo $this->formControlGroup($form->get('telephone')); ?>
<?php echo $this->formControlGroup($form->get('email')); ?>
<?php if (!isset($structure)) echo $this->formControlGroup($form->get('structures')); ?>
<?php echo $this->formControlGroup($form->get('creer')); ?>
<?php echo $this->form()->closeTag(); ?>


<script>
    <?php if (isset($js)): ?>
    <?php echo $js; ?>
    <?php endif; ?>

    $(function() {
        $('select').selectpicker();
    });
</script>