<?php

/**
 * @see \Structure\Controller\StructureController::indexAction()
 * @var Structure[] $structures
 */

use Structure\Entity\Db\Structure;
use UnicaenContact\Entity\Db\Contact;
use UnicaenContact\Provider\Privilege\ContactPrivileges;
use UnicaenContact\Provider\Privilege\ContacttypePrivileges;

$this->headTitle('Contacts');

$canIndexType = $this->isAllowed(ContacttypePrivileges::getResourceId(ContacttypePrivileges::CONTACTTYPE_INDEX));
$canAjouterContact = $this->isAllowed(ContactPrivileges::getResourceId(ContactPrivileges::CONTACT_AJOUTER));
$canModifierContact = $this->isAllowed(ContactPrivileges::getResourceId(ContactPrivileges::CONTACT_MODIFIER));
$canSupprimerContact = $this->isAllowed(ContactPrivileges::getResourceId(ContactPrivileges::CONTACT_SUPPRIMER));

?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Contacts
        </h1>
    </div>
    <div class="col-md-4">
        <?php /** @see \UnicaenContact\Controller\TypeController::indexAction() */ ?>
        <?php if ($canIndexType) : ?>
            <a href="<?php echo $this->url('unicaen-contact/type', [], ['query' => ['retour' => $this->url(null, [], [], true)]], true); ?>"
               class="btn btn-secondary float-end">
                <span class="icon icon-listing "></span>
                Accéder aux types
            </a>
        <?php endif; ?>
    </div>
</div>

<?php if ($canAjouterContact) : ?>
    <a href=""
        class="btn btn-primary ajax-modal" data-event="modification" >
        <span class="icon icon-ajouter"></span>
        Ajouter un contact
    </a>
<?php endif; ?>


<div class="card">
    <div class="card-header">
        <span class="icon icon-filter"></span>
        Filtre de recherches
    </div>
    <div class="card-body">
        <div class="col-md-9">
            TYPE
            STRUCTURE
        </div>
        <div class="col-md-3">
            Filtrer RAZ
        </div>
    </div>
</div>

<table class="table table-condensed" id="contacts">
    <thead>
    <tr>
        <th class="col-md-1"> Id </th>
        <th class="col-md-2" data-order="string"> Dénomination </th>
        <th class="col-md-3"> Informations de contact </th>
        <th class="col-md-1"> Type</th>
        <th class="col-md-3"> Structures </th>
        <th class="col-md-2 action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($structures as $structure): ?>
        <?php /** @var Contact $contact */ ?>
        <?php foreach ($structure->getContacts() as $contact): ?>
            <tr>
                <td data-column-id="Id">
                    <?php echo $contact->getId(); ?>
                </td>
                <td data-colomun="Dénomination" data-order="<?php echo $contact->getNom(); ?> <?php echo $contact->getPrenom(); ?>">
                    <?php echo $contact->getPrenom(); ?> <?php echo $contact->getNom(); ?>
                </td>
                <td data-colomun="Informations de contact">
                    <?php if ($contact->getTelephone()) : ?>
                        <?php echo $contact->getTelephone(); ?>
                    <?php else : ?>
                        <span class="missing-data">Aucun numéro de téléphone</span>
                    <?php endif; ?>
                    <br>
                    <?php if ($contact->getEmail()) : ?>
                        <?php echo $contact->getEmail(); ?>
                    <?php else : ?>
                        <span class="missing-data">Aucune adresse électronique</span>
                    <?php endif; ?>
                </td>
                <td data-column-id="Type">
                    <?php echo $contact->getType()->getLibelle(); ?> <br>
                    <code><?php echo $contact->getType()->getCode(); ?></code>
                </td>
                <td data-column-id="Structure">
                    TO BE CHANGED
                    <?php if ($structure->getNiv2() AND $structure->getNiv2() !== $structure) : ?>
                        <?php echo $structure->getNiv2()->getLibelleCourt(); ?> >
                    <?php endif; ?>
                    <?php echo $structure->getLibelleLong(); ?><br>
                    <?php echo $structure->getType()->getLibelle(); ?>
                </td>
                <td data-column-id="Action">
                    TO DO
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>
