INSERT INTO unicaen_etat_etat_type (code, libelle, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id)
                            VALUES ('DEFAULT', 'État par défaut', null, 'gray', current_date, 0, current_date, 0);
INSERT INTO public.unicaen_etat_etat_type (id, code, libelle, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id) VALUES (7, 'ENTRETIEN_PROFESSIONNEL', 'États liés aux entretiens professionnels', 'fa fa-briefcase', '#033ed0', '2020-10-13 16:19:06.000000', 19, '2020-10-13 16:19:06.000000', 19, null, null);
INSERT INTO public.unicaen_etat_etat_type (id, code, libelle, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id) VALUES (8, 'FICHE_METIER', 'États associés aux fiches métiers', 'fas fa-book-open', '#27807b', '2020-10-29 11:48:08.000000', 19, '2020-10-29 11:50:09.000000', 19, null, null);
INSERT INTO public.unicaen_etat_etat_type (id, code, libelle, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id) VALUES (9, 'MAIL', 'États associés aux mails', 'fas fa-envelope', '#ef690b', '2021-04-08 10:36:56.000000', 19, '2021-04-08 11:13:02.000000', 19, null, null);

INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (5, 'ENTRETIEN_VALIDATION_AGENT', 'Validation de l&rsquo;agent', 7, 'fas fa-user', '#cbcb00', '2021-02-02 15:40:15.000000', 19, '2021-03-01 09:31:23.000000', 19, null, null, 4);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (6, 'ENTRETIEN_VALIDATION_HIERARCHIE', 'Validation du responsable hiérarchique', 7, 'far fa-check-square', '#37d100', '2021-02-02 15:41:10.000000', 19, '2021-03-01 09:31:31.000000', 19, null, null, 5);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (3, 'ENTRETIEN_ACCEPTATION', 'En attente confirmation de l&rsquo;agent', 7, 'fas fa-user-clock', '#b90b80', '2021-02-02 15:06:45.000000', 19, '2021-03-01 09:30:56.000000', 19, null, null, 1);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (7, 'ENTRETIEN_ACCEPTER', 'Entretien accepté par l&rsquo;agent', 7, 'fas fa-user-check', '#c100b5', '2021-02-02 15:30:45.000000', 19, '2021-03-01 09:31:08.000000', 19, null, null, 2);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (4, 'ENTRETIEN_VALIDATION_RESPONSABLE', 'Validation du responsable de l&rsquo;entretien professionnel', 7, 'fas fa-user-tie', '#c98400', '2021-02-02 15:39:09.000000', 19, '2021-03-01 09:31:16.000000', 19, null, null, 3);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (1, 'FICHE_METIER_OK', 'Fiche métier validée', 8, 'fas fa-check', '#00a004', '2020-10-29 11:53:31.000000', 19, '2020-10-29 11:53:31.000000', 19, null, null, 9999);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (0, 'FICHE_METIER_REDACTION', 'Fiche métier en cours de rédaction', 8, 'fas fa-pencil-ruler', '#ff9500', '2020-10-29 11:51:18.000000', 19, '2020-10-29 11:51:31.000000', 19, null, null, 9999);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (2, 'FICHE_METIER_MASQUEE', 'Fiche métier masquée', 8, 'fas fa-mask', '#cb0000', '2020-10-29 11:52:25.000000', 19, '2020-10-29 11:52:25.000000', 19, null, null, 9999);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (14, 'MAIL_PENDING', 'En envoi', 9, 'fas fa-hourglass-start', '#ebbd11', '2021-04-08 10:52:30.000000', 19, '2021-04-08 10:52:30.000000', 19, null, null, 1);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (15, 'MAIL_SUCCESS', 'Envoi réussi', 9, 'fas fa-check', '#006400', '2021-04-08 10:53:23.000000', 19, '2021-04-08 10:55:34.000000', 19, null, null, 2);
INSERT INTO public.unicaen_etat_etat (id, code, libelle, type_id, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id, histo_destruction, histo_destructeur_id, ordre) VALUES (16, 'MAIL_FAILURE', 'Envoi échoué', 9, 'fas fa-times', '#8b0000', '2021-04-08 10:54:28.000000', 19, '2021-04-08 10:55:48.000000', 19, null, null, 2);

-- ---------------------------------------------------------------------------------------------------------------------
-- ETATS ASSOCIE AUX MODULE DE FORMATION -------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------

INSERT INTO unicaen_etat_etat_type (code, libelle, icone, couleur, histo_creation, histo_createur_id, histo_modification, histo_modificateur_id)
VALUES ('FORMATION_ACTION', 'États associés aux actions de formation', 'fas fa-chalkboard-teacher', '#da0296', current_date, 0, current_date, 0 );
INSERT INTO unicaen_etat_etat
(code,                            libelle,                                                     type_id,                          icone,                   couleur,   ordre,   histo_creation, histo_createur_id, histo_modification, histo_modificateur_id)
VALUES
('FORMATION_RETOUR',              'Action de formation en attente des retours de formation',   UNICAEN_ETAT_TYPE_ID_SEQ.currval, 'fas fa-user-clock',     '#00d59e', 6,       current_date, 0, current_date, 0),
('FORMATION_FERMEE',              'Action de formation terminée',                              UNICAEN_ETAT_TYPE_ID_SEQ.currval, 'far fa-check-square',   '#38f200', 7,       current_date, 0, current_date, 0),
('FORMATION_CONVOCATION',         'Envoi des convocations + Formation en cours',               UNICAEN_ETAT_TYPE_ID_SEQ.currval, 'far fa-envelope',       '#b0b0b0', 4,       current_date, 0, current_date, 0),
('FORMATION_INSCRIPTION_FERMEE',  'Action de formation avec inscription complète',             UNICAEN_ETAT_TYPE_ID_SEQ.currval, 'fas fa-calendar-check', '#e1d800', 3,       current_date, 0, current_date, 0),
('FORMATION_INSCRIPTION_OUVERTE', 'Action de formation ouverte au inscription',                UNICAEN_ETAT_TYPE_ID_SEQ.currval, 'fas fa-edit',           '#f78800', 2,       current_date, 0, current_date, 0),
('FORMATION_EN_CREATION',         'Action de formation en cours de création',                  UNICAEN_ETAT_TYPE_ID_SEQ.currval, 'fas fa-spinner',        '#e20000', 1,       current_date, 0, current_date, 0);