<?php

/**
 * @var string $title
 * @var string $text
 * @var string $action
 * @var boolean $refus
 */

$refusable = ($refus === null OR $refus === true)
?>

<p class="lead">
    <?php echo $text; ?>
</p>

<table>
    <tr><td>
            <form method="post" action="<?php echo $action; ?>">
                <input type="hidden" name="reponse" value="oui">
                <input type="submit" name="oui" class="btn btn-success action" value="Valider">
            </form>
        </td>
        <?php if ($refusable) : ?>
            <td>
                <form method="post" action="<?php echo $action; ?>">
                    <input type="hidden" name="reponse" value="non">
                    <input type="submit" name="non" class="btn btn-danger action"  value="Refuser">
                </form>
            </td>
        <?php endif; ?>
    </tr>
</table>

<script>
    $(function() {
        $("input#non").click(function(e){
            $('div.modal').modal('hide');
            e.preventDefault(e);
        });
    });
</script>

