<?php

/**
 * @see \Element\Controller\CompetenceReferentielController::afficherAction()
 * @var CompetenceReferentiel $referentiel
 */

use Element\Entity\Db\Competence;
use Element\Entity\Db\CompetenceReferentiel;

$utilisateur = ($referentiel->getHistoModificateur() ?: $referentiel->getHistoCreateur());
$date = ($referentiel->getHistoModification() ?: $referentiel->getHistoCreation());
?>

<dl class="dl-horizontal">
    <dt> Libellé</dt>
    <dd>
        <?php echo $referentiel->getLibelleLong(); ?> <br>
        <span class="badge" style="background:<?php echo $referentiel->getCouleur(); ?>"; ?>
            <?php echo $referentiel->getLibelleCourt(); ?> <br>
        </span>
    </dd>
    <dt> Modificateur</dt>
    <dd> <?php echo $utilisateur->getDisplayName(); ?> le <?php echo $date->format('d/m/Y à H:m:s'); ?> </dd>
    <dt> Compétences associées
        <span class="badge"> <?php echo count($referentiel->getCompetences()); ?></span>
    </dt>
    <dd>

        <ul>
            <?php
                $competences = $referentiel->getCompetences()->toArray();
                usort($competences, function (Competence $a, Competence $b) { return $a->getLibelle() <=> $b->getLibelle(); });
            ?>
            <?php foreach ($competences as $competence) : ?>
                <li> <?php echo $competence->getLibelle(); ?> </li>
            <?php endforeach; ?>
        </ul>
    </dd>
</dl>
