<?php

/**
 * @see \Element\Controller\CompetenceReferentielController::indexAction()
 * @var CompetenceReferentiel[] $referentiels ;
 */

use Element\Entity\Db\CompetenceReferentiel;
use Element\Provider\Privilege\CompetencedisciplinePrivileges;
use Element\Provider\Privilege\CompetencePrivileges;
use Element\Provider\Privilege\CompetencereferentielPrivileges;
use Element\Provider\Privilege\CompetencethemePrivileges;
use Element\Provider\Privilege\CompetencetypePrivileges;

$this->headTitle("Référentiels de compétences");

$canCompetenceIndex = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_INDEX));
$canCompetenceDisciplineIndex = $this->isAllowed(CompetencedisciplinePrivileges::getResourceId(CompetencedisciplinePrivileges::COMPETENCEDISCIPLINE_INDEX));
$canCompetenceThemeIndex = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_INDEX));
$canCompetenceTypeIndex = $this->isAllowed(CompetenceTypePrivileges::getResourceId(CompetenceTypePrivileges::COMPETENCETYPE_INDEX));

$canAfficher = $this->isAllowed(CompetencereferentielPrivileges::getResourceId(CompetencereferentielPrivileges::COMPETENCEREFERENTIEL_AFFICHER));
$canAjouter = $this->isAllowed(CompetencereferentielPrivileges::getResourceId(CompetencereferentielPrivileges::COMPETENCEREFERENTIEL_AJOUTER));
$canModifier = $this->isAllowed(CompetencereferentielPrivileges::getResourceId(CompetencereferentielPrivileges::COMPETENCEREFERENTIEL_MODIFIER));
$canHistoriser = $this->isAllowed(CompetencereferentielPrivileges::getResourceId(CompetencereferentielPrivileges::COMPETENCEREFERENTIEL_HISTORISER));
$canDetruire = $this->isAllowed(CompetencereferentielPrivileges::getResourceId(CompetencereferentielPrivileges::COMPETENCEREFERENTIEL_EFFACER));
$canVider = $this->isAllowed(CompetencereferentielPrivileges::getResourceId(CompetencereferentielPrivileges::COMPETENCEREFERENTIEL_EFFACER));

$canAction = ($canAfficher or $canModifier or $canHistoriser or $canDetruire);

?>

<h1 class="page-header">
    Référentiels de compétences
</h1>


<div class="row">
    <div class="col-md-6">
        <?php if ($canAjouter) : ?>
            <?php /** @see \Element\Controller\CompetenceReferentielController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('element/competence-referentiel/ajouter', [], [], true); ?>"
               class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un référentiel
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <?php if ($canCompetenceIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceController::listingAction() */ ?>
            <a href="<?php echo $this->url('element/competence/listing', [], [], true); ?>" class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux compétences</a>
        <?php endif; ?>

        <?php if ($canCompetenceDisciplineIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceDisciplineController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-discipline', [], [], true); ?>"
               class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux disciplines</a>
        <?php endif; ?>


        <?php if ($canCompetenceThemeIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceThemeController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-theme', [], [], true); ?>" class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux thèmes</a>
        <?php endif; ?>

        <?php if ($canCompetenceTypeIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceTypeController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-type', [], [], true); ?>" class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux types</a>
        <?php endif; ?>
    </div>
</div>


<table class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th> Libellé</th>
        <th> Badge</th>
        <th> #Compétence</th>

        <th class="action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($referentiels as $referentiel) : ?>
        <tr class="<?php if ($referentiel->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $referentiel->getLibelleLong(); ?> </td>
            <td>
                <span class="badge" style="background:<?php echo $referentiel->getCouleur(); ?>;">
                    <?php echo $referentiel->getLibelleCourt(); ?>
                </span>
            </td>
            <td> <?php echo count($referentiel->getCompetences()); ?> </td>
            <?php if ($canAction) : ?>
                <td class="action">
                    <?php if ($canAfficher) : ?>
                        <?php /** @see \Element\Controller\CompetenceReferentielController::afficherAction() */ ?>
                        <a href="<?php echo $this->url('element/competence-referentiel/afficher', ['competence-referentiel' => $referentiel->getId()], [], true); ?>"
                           class="ajax-modal action secondary">
                            <span class="icon icon-voir"></span>
                            Afficher
                        </a>
                    <?php endif; ?>
                    <?php if ($canModifier) : ?>
                        <br>
                        <?php /** @see \Element\Controller\CompetenceReferentielController::modifierAction() */ ?>
                        <a href="<?php echo $this->url('element/competence-referentiel/modifier', ['competence-referentiel' => $referentiel->getId()], [], true); ?>"
                           class="ajax-modal action primary" data-event="modification">
                            <span class="icon icon-editer"></span>
                            Modifier
                        </a>
                    <?php endif; ?>
                    <?php if ($canHistoriser): ?>
                        <br>
                        <?php if ($referentiel->estNonHistorise()) : ?>
                            <?php /** @see \Element\Controller\CompetenceReferentielController::historiserAction() */ ?>
                            <a href="<?php echo $this->url('element/competence-referentiel/historiser', ['competence-referentiel' => $referentiel->getId()], [], true); ?>"
                               class="action warning"
                            >
                                <span class="icon icon-historiser"></span>
                                Historiser
                            </a>
                        <?php else : ?>
                            <?php /** @see \Element\Controller\CompetenceReferentielController::restaurerAction() */ ?>
                            <a href="<?php echo $this->url('element/competence-referentiel/restaurer', ['competence-referentiel' => $referentiel->getId()], [], true); ?>"
                               class="action warning"
                            >
                                <span class="icon icon-restaurer"></span>
                                Restaurer
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canVider) : ?>
                        <br>
                        <?php /** @see \Element\Controller\CompetenceReferentielController::viderAction() */ ?>
                        <a href="<?php echo $this->url('element/competence-referentiel/vider', ['competence-referentiel' => $referentiel->getId()], [], true); ?>"
                           class="ajax-modal action warning" data-event="modification">
                            <span class="icon icon-vider"></span>
                            Vider
                        </a>
                    <?php endif; ?>
                    <?php if ($canDetruire) : ?>
                        <br>
                        <?php /** @see \Element\Controller\CompetenceReferentielController::supprimerAction() */ ?>
                        <a href="<?php echo $this->url('element/competence-referentiel/supprimer', ['competence-referentiel' => $referentiel->getId()], [], true); ?>"
                           class="ajax-modal action danger" data-event="modification">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </a>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>