<?php

use EntretienProfessionnel\Entity\Db\Campagne;
use Structure\Entity\Db\Structure;

/**
 * @var Structure $structure
 * @var string $current <i> onglet actif pour mise en forme
 * @var Campagne[] $campagnes
 */

?>

<h1 class="page-header">
    <strong><?php echo $structure->getLibelleLong(); ?></strong>
    <br>
    <?php echo $structure->getType()->getLibelle(); ?>
</h1>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::descriptionAction() */ ?>
            <a href="<?php echo $this->url('structure/description', ['structure' => $structure->getId()],[], true); ?>"
               class="nav-link" aria-controls="description" role="tab">
                Description de <br/> la structure
            </a>
        </li>
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::agentsAction() */ ?>
            <a href="<?php echo $this->url('structure/agents', ['structure' => $structure->getId()],[], true); ?>"
               class="nav-link" aria-controls="agents" role="tab">
                Liste des <br/>Agent·es
            </a>
        </li>
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::fichesDePosteAction() */ ?>
            <a href="<?php echo $this->url('structure/fiches-de-poste', ['structure' => $structure->getId()],[], true); ?>"
               class="nav-link" aria-controls="fiches-de-poste" role="tab">
                Fiches de <br/>poste
            </a>
        </li>
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::missionsSpecifiquesAction() */ ?>
            <a href="<?php echo $this->url('structure/missions-specifiques', ['structure' => $structure->getId()],[], true); ?>"
               class="nav-link" aria-controls="missions-specifiques" role="tab">
                Missions <br/> spécifiques
            </a>
        </li>
        <?php foreach ($campagnes as $campagne) : ?>
        <li class="nav-item">
            <a href="<?php echo $this->url('entretien-professionnel/campagne/structure', ['structure' => $structure->getId(), 'campagne' => $campagne->getId()],[],true); ?>"
               class="nav-link" aria-controls="campagne_<?php echo $campagne->getId(); ?>" role="tab">
                Entretiens professionnels <br/> <?php echo $campagne->getAnnee(); ?>
            </a>
        </li>
        <?php endforeach; ?>
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::extractionsAction() */ ?>
            <a href="<?php echo $this->url('structure/extractions', ['structure' => $structure->getId()], [], true); ?>" class="nav-link" aria-controls="extractions" role="tab">
                Extractions <br/> &nbsp;
            </a>
        </li>
    </ul>
</div>

<script>
    $('a[aria-controls="<?php echo $current; ?>"]').addClass('active');
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
