<?php

use Application\Provider\Privilege\MissionspecifiqueaffectationPrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use Structure\Entity\Db\Structure;

/**
 * @var Structure $structure
 * @var string $current <i> onglet actif pour mise en forme
 * @var Campagne[] $campagnes
 */

$canMissionSpecifiqueOnglet = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_ONGLET));

?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            <strong><?php echo $structure->getLibelleLong(); ?></strong>
            <br>
            <?php if ($structure->getType()) : ?>
                <?php echo $structure->getType()->getLibelle(); ?>
            <?php else : ?>
                <span class="text-warning">
                    <span class="icon icon-attention"></span>
                    Type de structure manquant
                </span>
            <?php endif; ?>
        </h1>
    </div>
    <div class="col-md-4">
        <?php if (! empty($selecteur)) : ?>
            <label for="structure-selecteur">Structure à afficher : <br/></label>
            <select id="structure-selecteur" name="structure-selecteur" class="bootstrap-select">
                <option value="">Aucune sélection</option>
                <?php foreach ($selecteur as $s) : ?>
                    <option value="<?php echo $s->getId(); ?>" <?php if ($structure->getId() == $s->getId()) echo "selected"; ?>><?php echo $s->getLibelleCourt(); ?></option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
</div>


<div class="nav nav-tabs" id="nav-tab" role="tablist">
        <?php /** @see \Structure\Controller\StructureController::descriptionAction() */ ?>
        <button class="nav-link" id="informations-tab"
                data-bs-toggle="tab" data-bs-target="#informations"
                type="button" role="tab" aria-controls="informations" aria-selected="true"
                onclick="location.href='<?php echo $this->url('structure/description', ['structure' => $structure->getId()],[], true); ?>'"
        >
            Description de la structure
        </button>
        <?php /** @see \Structure\Controller\StructureController::agentsAction() */ ?>
        <button class="nav-link" id="agents-tab"
                data-bs-toggle="tab" data-bs-target="#agents"
                type="button" role="tab" aria-controls="agents" aria-selected="true"
                onclick="location.href='<?php echo $this->url('structure/agents', ['structure' => $structure->getId()],[], true); ?>'"
        >
            Liste des Agent·es
        </button>
        <?php /** @see \Structure\Controller\StructureController::fichesDePosteAction() */ ?>
        <button class="nav-link" id="fiches-de-poste-tab"
                data-bs-toggle="tab" data-bs-target="#fiches-de-poste"
                type="button" role="tab" aria-controls="fiches-de-poste" aria-selected="true"
                onclick="location.href='<?php echo $this->url('structure/fiches-de-poste', ['structure' => $structure->getId()],[], true); ?>'"
        >
            Fiches de poste
        </button>
        <?php if ($canMissionSpecifiqueOnglet) : ?>
            <?php /** @see \Structure\Controller\StructureController::missionsSpecifiquesAction() */ ?>
            <button class="nav-link" id="mission-specifique-tab"
                    data-bs-toggle="tab" data-bs-target="#mission-specifique"
                    type="button" role="tab" aria-controls="mission-specifique" aria-selected="true"
                    onclick="location.href='<?php echo $this->url('structure/missions-specifiques', ['structure' => $structure->getId()],[], true); ?>'"
            >
                    Missions spécifiques
            </button>
        <?php endif; ?>
        <?php foreach ($campagnes as $campagne) : ?>
            <?php if ($campagne !== null) : ?>
                <?php /** @see \EntretienProfessionnel\Controller\CampagneController::structureAction() */ ?>
                <button class="nav-link" id="campagne<?php echo $campagne->getId(); ?>-tab"
                        data-bs-toggle="tab" data-bs-target="#mission-specifique"
                        type="button" role="tab" aria-controls="mission-specifique" aria-selected="true"
                        onclick="location.href='<?php echo $this->url('entretien-professionnel/campagne/structure', ['structure' => $structure->getId(), 'campagne' => $campagne->getId()],[],true); ?>'"
                >
                    Entretiens professionnels <?php echo $campagne->getAnnee(); ?>
                </button>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php /** @see \Structure\Controller\StructureController::extractionsAction() */ ?>
        <button class="nav-link" id="extraction-tab"
            data-bs-toggle="tab" data-bs-target="#extraction"
            type="button" role="tab" aria-controls="extraction" aria-selected="true"
            onclick="location.href='<?php echo $this->url('structure/extractions', ['structure' => $structure->getId()], [], true); ?>'">
                Extractions
        </button>
</div>

<script>
    $('a[aria-controls="<?php echo $current; ?>"]').addClass('active');
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
    $(function() {
        $('select#structure-selecteur').change(function() {
            let id = $('select#structure-selecteur option:selected').val();
            if (id !== "" && id !== "<?php echo $structure->getId(); ?>") {
                window.location.href = './' + id;
            }
        });
    });

</script>
