<?php

use EntretienProfessionnel\Entity\Db\Campagne;
use Structure\Entity\Db\Structure;

/**
 * @var Structure $structure
 * @var string $current <i> onglet actif pour mise en forme
 * @var Campagne[] $campagnes
 */

?>


<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            <strong><?php echo $structure->getLibelleLong(); ?></strong>
            <br>
            <?php if ($structure->getType()) : ?>
                <?php echo $structure->getType()->getLibelle(); ?>
            <?php else : ?>
                <span class="text-warning">
                    <span class="icon icon-attention"></span>
                    Type de structure manquant
                </span>
            <?php endif; ?>
        </h1>
    </div>
    <div class="col-md-4">
        <?php if (! empty($selecteur)) : ?>
            <label for="structure-selecteur">Structure à afficher : <br/></label>
            <select id="structure-selecteur" name="structure-selecteur" class="bootstrap-select">
                <option value="">Aucune sélection</option>
                <?php foreach ($selecteur as $s) : ?>
                    <option value="<?php echo $s->getId(); ?>" <?php if ($structure->getId() == $s->getId()) echo "selected"; ?>><?php echo $s->getLibelleCourt(); ?></option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
</div>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::descriptionAction() */ ?>
            <a href="<?php echo $this->url('structure/description', ['structure' => $structure->getId()],[], true); ?>"
               class="nav-link" aria-controls="description" role="tab">
                Description de <br/> la structure
            </a>
        </li>
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::agentsAction() */ ?>
            <a href="<?php echo $this->url('structure/agents', ['structure' => $structure->getId()],[], true); ?>"
               class="nav-link" aria-controls="agents" role="tab">
                Liste des <br/>Agent·es
            </a>
        </li>
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::fichesDePosteAction() */ ?>
            <a href="<?php echo $this->url('structure/fiches-de-poste', ['structure' => $structure->getId()],[], true); ?>"
               class="nav-link" aria-controls="fiches-de-poste" role="tab">
                Fiches de <br/>poste
            </a>
        </li>
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::missionsSpecifiquesAction() */ ?>
            <a href="<?php echo $this->url('structure/missions-specifiques', ['structure' => $structure->getId()],[], true); ?>"
               class="nav-link" aria-controls="missions-specifiques" role="tab">
                Missions <br/> spécifiques
            </a>
        </li>
        <?php foreach ($campagnes as $campagne) : ?>
        <li class="nav-item">
            <a href="<?php echo $this->url('entretien-professionnel/campagne/structure', ['structure' => $structure->getId(), 'campagne' => $campagne->getId()],[],true); ?>"
               class="nav-link" aria-controls="campagne_<?php echo $campagne->getId(); ?>" role="tab">
                Entretiens professionnels <br/> <?php echo $campagne->getAnnee(); ?>
            </a>
        </li>
        <?php endforeach; ?>
        <li class="nav-item">
            <?php /** @see \Structure\Controller\StructureController::extractionsAction() */ ?>
            <a href="<?php echo $this->url('structure/extractions', ['structure' => $structure->getId()], [], true); ?>" class="nav-link" aria-controls="extractions" role="tab">
                Extractions <br/> &nbsp;
            </a>
        </li>
    </ul>
</div>

<script>
    $('a[aria-controls="<?php echo $current; ?>"]').addClass('active');
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
    $(function() {
        $('select#structure-selecteur').change(function() {
            let id = $('select#structure-selecteur option:selected').val();
            if (id !== "" && id !== "<?php echo $structure->getId(); ?>") {
                window.location.href = './' + id;
            }
        });
    });
</script>
