<?php

use Application\Entity\Db\Agent;
use Fichier\Entity\Db\Fichier;
use Formation\Entity\Db\DemandeExterne;
use Formation\Provider\Etat\DemandeExterneEtats;
use Formation\Provider\Privilege\FormationinstancePrivileges;
use Formation\Provider\Validation\DemandeExterneValidations;

/**
 * @see \Formation\Controller\DemandeExterneController::afficherAction()
 * @var DemandeExterne $demande
 * @var Agent $agent;
 */

//$canValiderDrh = $this->isAllowed($demande,DemandeexternePrivileges::DEMANDEEXTERNE_VALIDER_DRH);

$canAfficherSession = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_AFFICHER));
$canModifierSession = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_MODIFIER));
$canGererGestionnaires = $canModifierSession;
?>

<?php if ($canModifierSession) : ?>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <dl>
                        <dt>Gestionnaire·s associé·es : </dt>
                        <dd>
                            <?php if (empty($demande->getGestionnaires())) : ?>
                                <em> Aucun·e gestionnaire</em>
                            <?php else : ?>
                                <ul>
                                    <?php foreach ($demande->getGestionnaires() as $gestionnaire) : ?>
                                        <li> <?php echo $gestionnaire->getDisplayName(); ?> </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </dd>

                    </dl>
                </div>
                <div class="col-md-6">
                    <?php if ($canGererGestionnaires) : ?>
                        <?php /** @see \Formation\Controller\DemandeExterneController::selectionnerGestionnairesAction() */ ?>
                        <a href="<?php echo $this->url('formation/demande-externe/selectionner-gestionnaires', ['demande-externe' => $demande->getId()], [], true); ?>"
                           class="btn btn-primary ajax-modal" data-event="modification">
                            <span class="icon icon-editer"></span>
                            Renseigner les gestionnaires
                        </a>
                    <?php endif; ?>
                </div>
            </div>

        </div>
    </div>
<?php endif; ?>


<div class="card card-info">
    <div class="card-header">
        Informations à propos de l'Agent demandant le stage
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-md-2"> Prénom </dt>
            <dd class="col-md-4"> <?php echo $agent->getPrenom(); ?> </dd>
            <dt class="col-md-2"> Nom </dt>
            <dd class="col-md-4"> <?php echo $agent->getNomUsuel()??$agent->getNomFamille(); ?> </dd>
            <dt class="col-md-2"> Adresse électronique </dt>
            <dd class="col-md-10"> <?php echo $agent->getEmail(); ?> </dd>
            <dt class="col-md-2"> Statut </dt>
            <dd class="col-md-4"> <?php echo $agent->getStatutToString(); ?> </dd>
            <dt class="col-md-2"> Corps </dt>
            <dd class="col-md-4">
                <?php $corps = $agent->getGradesActifs(); ?>
                <?php foreach ($corps as $corp) echo $corp->getCorps()->getLibelleLong(); ?>
            </dd>
            <dt class="col-md-2"> Service </dt>
            <dd class="col-md-10">
                <?php $affectations = $agent->getAffectationsActifs(); ?>
                <?php foreach ($affectations as $affectation) {
                    $structure = $affectation->getStructure();
                    $niv2 = $structure->getNiv2();
                    if ($niv2 !== null AND $niv2 !== $structure) echo $niv2->getLibelleLong() . " > ";
                    echo $affectation->getStructure()->getLibelleLong();
                }
                ?>
            </dd>
        </dl>
    </div>
</div>

<div class="card card-info">
    <div class="card-header">
        Formulaire de demande de formation externe
    </div>
    <div class="card-body">

        <h3> Description de la formation demandée </h3>
        <dl class="row">
            <dt class="col-md-4"> Libellé : </dt>
            <dd class="col-md-8"> <?php echo $demande->getLibelle(); ?> </dd>
            <dt class="col-md-2"> Organisme :</dt>
            <dd class="col-md-4"> <?php echo $demande->getOrganisme(); ?> </dd>
            <dt class="col-md-2"> Contact :</dt>
            <dd class="col-md-4"> <?php echo $demande->getContact(); ?> </dd>
            <dt class="col-md-4"> Pourquoi le choix de cet organisme :</dt>
            <dd class="col-md-12"> <?php echo $demande->getPourquoi(); ?> </dd>
            <dt class="col-md-2"> Lieu :</dt>
            <dd class="col-md-4"> <?php echo $demande->getLieu(); ?> </dd>
            <dt class="col-md-2"> Periode :</dt>
            <dd class="col-md-4"> <?php echo $demande->getDebut()->format('d/m/Y'); ?> au <?php echo $demande->getFin()->format('d/m/Y'); ?> </dd>
            <dt class="col-md-4"> Montant : </dt>
            <dd class="col-md-8"><?php echo $demande->getMontant(); ?> </dd>
        </dl>

        <h3> Motivation </h3>
        <div class="row">
            <div class="col-md-12">
                <dl>
                    <dt> Mission·s en lien avec la demande de formation :</dt>
                    <dd> <?php echo $demande->getMissions(); ?></dd>
                    <dt> Motivation·s </dt>
                    <dt><?php echo $demande->getJustificationAgent(); ?> </dt>
                </dl>
            </div>
            <div class="col-md-12"> <?php echo $demande->getJustificationAgent(); ?> </div>
            <dl class="row">
                <dt class="col-md-4"> Formation au titre de congé de formation syndicale </dt>
                <dd class="col-md-8"> <?php echo ($demande->isCongeFormationSyndicale())?"Oui" : "Non"; ?> </dd>
            </dl>
        </div>

        <h3> Cofinancement </h3>
        <dl class="row">
            <dt class="col-md-4"> Prise en charge </dt>
            <dd class="col-md-8"> <?php echo ($demande->isPriseEnCharge())?"Oui" : "Non"; ?> </dd>
            <dt class="col-md-4"> Cofinanceur </dt>
            <dd class="col-md-8"> <?php echo $demande->getCofinanceur(); ?> </dd>
        </dl>
    </div></div>

<div class="card card-info">
    <div class="card-header">
        Devis
    </div>
    <div class="card-body">
        <?php /** @var Fichier  $devis */
        foreach ($demande->getDevis() as $devis) : ?>
        <a href="<?php echo $this->url('download-fichier', ['fichier' => $devis->getId()], [], true); ?>">
            <span class="icon icon-fichier"></span>
            <?php echo $devis->getNomOriginal(); ?>
        </a>&nbsp;
        <br/>
        <?php endforeach; ?>
    </div>
</div>

<div class="card">
    <div class="card-header bg-default">
        Validation
    </div>
    <div class="card-body">
        <dl class="row">
            <?php if ($validation = $demande->getValidationActiveByTypeCode(DemandeExterneValidations::FORMATION_DEMANDE_AGENT)) : ?>
                <dt class="col-md-4"> Validation de l'agent </dt>
                <dd class="col-md-8">
                    <?php echo $validation->getHistoCreateur()->getDisplayName(); ?> le <?php echo $validation->getHistoCreation()->format('d/m/Y à H:i'); ?> <br/>
                    <?php echo $demande->getJustificationAgent(); ?>
                </dd>
            <?php endif; ?>
            <?php if ($validation = $demande->getValidationActiveByTypeCode(DemandeExterneValidations::FORMATION_DEMANDE_RESPONSABLE)) : ?>
                <dt class="col-md-4"> Validation du responsable </dt>
                <dd class="col-md-8">
                    <?php echo $validation->getHistoCreateur()->getDisplayName(); ?> le <?php echo $validation->getHistoCreation()->format('d/m/Y à H:i'); ?> <br/>
                    <?php echo $demande->getJustificationResponsable(); ?>
                </dd>
            <?php endif; ?>
            <?php if ($validation = $demande->getValidationActiveByTypeCode(DemandeExterneValidations::FORMATION_DEMANDE_DRH)) : ?>
                <dt class="col-md-4"> Validation de la DRH </dt>
                <dd class="col-md-8"> <?php echo $validation->getHistoCreateur()->getDisplayName(); ?> le <?php echo $validation->getHistoCreation()->format('d/m/Y à H:i'); ?> </dd>
            <?php endif; ?>
            <?php if ($validation = $demande->getValidationActiveByTypeCode(DemandeExterneValidations::FORMATION_DEMANDE_REFUS)) : ?>
                <dt class="col-md-4"> Refus </dt>
                <dd class="col-md-8">
                    <?php echo $validation->getHistoCreateur()->getDisplayName(); ?> le <?php echo $validation->getHistoCreation()->format('d/m/Y à H:i'); ?> <br/>
                    <?php echo $demande->getJustificationRefus(); ?>
                </dd>
            <?php endif; ?>

            <?php if ($demande->isEtatActif(DemandeExterneEtats::ETAT_TERMINEE)) : ?>
                <dt class="col-md-4">Action de formation associée </dt>
                <dd class="col-md-8">
                    <?php if (empty($demande->getSessions())) : ?>
                        <em> Aucun action de formation associée à cette demande </em>
                    <?php else : ?>
                        <ul>
                            <?php foreach ($demande->getSessions() as $session) : ?>
                                <li>
                                    <?php echo $session->getFormation()->getLibelle(); ?>
                                    (<?php echo $session->getPeriode(); ?>)
                                    <?php if ($canAfficherSession) : ?>
                                        <span class="action">
                                            <?php /** @see \Formation\Controller\SessionController::afficherAction(); */ ?>
                                            <a href="<?php echo $this->url('formation/session/afficher', ['session' => $session->getId()], [], true); ?>"
                                               target="_blank">
                                                <span class="icon icon-voir"></span> Acceder
                                            </a>
                                        </span>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </dd>
            <?php endif; ?>
        </dl>
    </div></div>

<?php //if ($canValiderDrh) : ?>
<!--    --><?php ///** @see \Formation\Controller\DemandeExterneController::indexAction() */ ?>
<!--    <a href="--><?php //echo $this->url('formation/demande-externe', [], [], true); ?><!--"-->
<!--       class="btn btn-primary">-->
<!--        Retour à l'index des demandes-->
<!--    </a>-->
<?php //endif; ?>
<!---->
<?php //if ($canValiderDrh AND $demande->isEtatActif(DemandeExterneEtats::ETAT_VALIDATION_RESP)) : ?>
<!--    --><?php ///** @see \Formation\Controller\DemandeExterneController::validerDrhAction() */ ?>
<!--    <a href="--><?php //echo $this->url('formation/demande-externe/valider-drh', ['demande-externe' => $demande->getId()], [], true); ?><!--"-->
<!--       class="btn btn-success ajax-modal" data-event="modification">-->
<!--        <span class="icon icon-checked"></span>-->
<!--        Valider la demande-->
<!--    </a>-->
<!--    --><?php ///** @see \Formation\Controller\DemandeExterneController::refuserDrhAction() */ ?>
<!--    <a href="--><?php //echo $this->url('formation/demande-externe/refuser-drh', ['demande-externe' => $demande->getId()], [], true); ?><!--"-->
<!--       class="btn btn-danger ajax-modal" data-event="modification">-->
<!--        <span class="icon icon-checked"></span>-->
<!--        Refuser la demande-->
<!--    </a>-->
<?php //endif; ?>
<!---->


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

