<?php

use Application\Entity\Db\Agent;
use Formation\Form\DemandeExterne\DemandeExterneForm;

/**
 * @see \Formation\Controller\DemandeExterneController::ajouterAction()
 * @see \Formation\Controller\DemandeExterneController::modifierAction()
 * @var Agent $agent;
 * @var DemandeExterneForm $form;
 */

$this->headTitle("Demande de stage externe");

?>

<h1 class="page-header">
    Demande de stage externe
</h1>

<div class="alert alert-info">
    <p>
    <span class="text-danger"><strong>À retourner impérativement 2 mois avant le début de la formation.</strong></span>
    </p>

    <p>
    Dans le cas d’un stage extérieur, le cofinancement entre la DRH et la composante de l’agent est la règle.
    </p>
    <p>
    Toute demande de stage extérieur (toute action hors plan de formation) nécessite de compléter ce formulaire
    pour accord de la composante de prise en charge des frais de mission de l’agent et pour accord de la Direction
    des Ressources Humaines (y compris pour les formations de l’AMUE)
    </p>
</div>

<div class="card card-info">
    <div class="card-header">
        Informations à propos de l'Agent demandant le stage
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-md-2"> Prénom </dt>
            <dd class="col-md-4"> <?php echo $agent->getPrenom(); ?> </dd>
            <dt class="col-md-2"> Nom </dt>
            <dd class="col-md-4"> <?php echo $agent->getNomUsuel()??$agent->getNomFamille(); ?> </dd>
            <dt class="col-md-2"> Adresse électronique </dt>
            <dd class="col-md-10"> <?php echo $agent->getEmail(); ?> </dd>
            <dt class="col-md-2"> Statut </dt>
            <dd class="col-md-4"> <?php echo $agent->getStatutToString(); ?> </dd>
            <dt class="col-md-2"> Corps </dt>
            <dd class="col-md-4">
                <?php $corps = $agent->getGradesActifs(); ?>
                <?php foreach ($corps as $corp) echo $corp->getCorps()->getLibelleLong(); ?>
            </dd>
            <dt class="col-md-2"> Service </dt>
            <dd class="col-md-10">
                <?php $affectations = $agent->getAffectationsActifs(); ?>
                <?php foreach ($affectations as $affectation) {
                    $structure = $affectation->getStructure();
                    $niv2 = $structure->getNiv2();
                    if ($niv2 !== null AND $niv2 !== $structure) echo $niv2->getLibelleLong() . " > ";
                    echo $affectation->getStructure()->getLibelleLong();
                }
            ?>
            </dd>
        </dl>
    </div>
</div>

<div class="card card-info">
    <div class="card-header">
        Formulaire de demande de formation externe
    </div>
    <div class="card-body">

        <?php echo $this->form()->openTag($form); ?>
        <h3> Description de la formation demandée </h3>
        <div class="row">
            <div class="col-md-12"> <?php echo $this->formControlGroup($form->get('libelle')); ?> </div>
            <div class="col-md-6"> <?php echo $this->formControlGroup($form->get('organisme')); ?> </div>
            <div class="col-md-6"><?php echo $this->formControlGroup($form->get('contact')); ?> </div>
            <div class="col-md-12"> <?php echo $this->formControlGroup($form->get('pourquoi')); ?></div>
            <div class="col-md-4"><?php echo $this->formControlGroup($form->get('lieu')); ?> </div>
            <div class="col-md-4"><?php echo $this->formControlGroup($form->get('debut')); ?> </div>
            <div class="col-md-4"><?php echo $this->formControlGroup($form->get('fin')); ?> </div>
            <div class="col-md-12"><?php echo $this->formControlGroup($form->get('modalite')); ?> </div>
            <div class="col-md-12"><?php echo $this->formControlGroup($form->get('montant')); ?> </div>
        </div>

        <h3> Motivation </h3>
        <div class="row">
            <div class="col-md-12"> <?php echo $this->formControlGroup($form->get('motivation')); ?> </div>
        </div>

        <h3> Cofinancement </h3>
        <div class="row">
            <div class="col-md-12"> <?php echo $this->formControlGroup($form->get('prise-en-charge')); ?> </div>
            <div class="col-md-12"> <?php echo $this->formControlGroup($form->get('cofinanceur')); ?> </div>
        </div>

<!--        <h3> Devis </h3>-->
<!--        <div class="card-body">-->
<!--            <div class="row">-->
<!--                <div class="col-md-12"> --><?php //echo $this->formControlGroup($form->get('devis1')); ?><!-- </div>-->
<!--                <div class="col-md-12"> --><?php //echo $this->formControlGroup($form->get('devis2')); ?><!-- </div>-->
<!--                <div class="col-md-12"> --><?php //echo $this->formControlGroup($form->get('devis3')); ?><!-- </div>-->
<!--            </div>-->
<!--        </div>-->

        <?php echo $this->formControlGroup($form->get('creer')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div></div>

<style>

</style>

<script>
    // $('.input-date').click(function() {
    //     // alert('click');
    //     $(this).children('div').css('z-index',10000);
    // });

    $(document).ready(function() {
        tinymce.remove();
        tinymce.init({
            selector: '.type2',
            toolbar: 'newdocument undo redo | bold italic underline removeformat | bullist',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck : true,
            branding: false,
            menu: {},
            body_id: 'description',
            setup: function (editor) {
                editor.on("focusout", function () {
                    console.log(tinymce.get('description').getContent());
                    $('textarea#description').val(tinymce.get('description').getContent());
                });
            }
        });
    });

    $('select').selectpicker();
</script>
