<?php

use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\FormationInstanceInscrit;
use Formation\Provider\Privilege\DemandeexternePrivileges;

/**
 * @see \Formation\Controller\DemandeExterneController::parapheurAction()
 * @var FormationInstanceInscrit[] $demandesInternes
 * @var DemandeExterne[] $demandesExternes
 */

$this->headTitle("Parapheur des formations externes");

// ATTENTION : ici pas d'appel à l'assertion pour économiser du temps
$canAfficher    = $this->isAllowed(DemandeexternePrivileges::getResourceId(DemandeexternePrivileges::DEMANDEEXTERNE_AFFICHER));
$canModifier    = $this->isAllowed(DemandeexternePrivileges::getResourceId(DemandeexternePrivileges::DEMANDEEXTERNE_MODIFIER));
$canHistoriser  = $this->isAllowed(DemandeexternePrivileges::getResourceId(DemandeexternePrivileges::DEMANDEEXTERNE_HISTORISER));
$canSupprimer   = $this->isAllowed(DemandeexternePrivileges::getResourceId(DemandeexternePrivileges::DEMANDEEXTERNE_SUPPRIMER));
$canValider     = $this->isAllowed(DemandeexternePrivileges::getResourceId(DemandeexternePrivileges::DEMANDEEXTERNE_VALIDER_DRH));

?>

<h1 class="page-header">
    Parapheurs des demandes de formations
</h1>

<h2>
    Demandes de formation interne
</h2>


<table class="table table-condensed table-hover">
    <thead>
    <tr>
        <th class="agent"> Agent             </th>
        <th class="formation"> Formation </th>
        <th> Type </th>
        <th class="etat"> État </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($demandesInternes as $demande) : ?>
        <tr class=" <?php if ($demande->estHistorise()) echo " historise "; ?> ">
            <td> <?php echo $demande->getAgent()->getDenomination(); ?> </td>
            <td> <?php echo $demande->getInstance()->getFormation()->getLibelle(); ?> </td>
            <td> <?php echo $demande->getInstance()->getType(); ?> </td>
            <td> <?php
                echo $this->etatinstance($demande->getEtatActif());
                ?> </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Formation\Controller\FormationInstanceInscritController::afficherAgentAction() */ ?>
                    <a href="<?php echo $this->url('formation-instance/afficher-agent', ['inscrit' => $demande->getId()], [], true); ?>"
                       class="ajax-modal">
                        <span class="icon icon-voir"></span></a>
                <?php else : ?>
                    <span class="icon icon-voir nope"></span>
                <?php endif; ?>
                <?php if ($canValider) : ?>
                    <?php  /** @see \Formation\Controller\InscriptionController::validerDrhAction() */ ?>
                    <a href="<?php echo $this->url('formation/inscription/valider-drh', ['inscription' => $demande->getId()], [], true); ?>" class="ajax-modal" data-event="modification">
                        <span class="icon icon-ok text-success"></span></a>
                    <?php  /** @see \Formation\Controller\InscriptionController::refuserDrhAction() */ ?>
                    <a href="<?php echo $this->url('formation/inscription/refuser-drh', ['inscription' => $demande->getId()], [], true); ?>" class="ajax-modal" data-event="modification">
                        <span class="icon icon-ko text-danger"></span></a>
                <?php else: ?>
                    <span class="icon icon-ok nope"></span>
                    <span class="icon icon-ko nope"></span>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($demande->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\FormationInstanceInscritController::historiserAgentAction() */ ?>
                        <a href="<?php echo $this->url('formation-instance/historiser-agent', ['inscrit' => $demande->getId()], [], true); ?>"
                           title="Supprimer la demande externe"
                        >
                            <span class="icon icon-historiser"></span></a>
                    <?php else : ?>
                        <?php /** @see \Formation\Controller\FormationInstanceInscritController::restaurerAgentAction() */ ?>
                        <a href="<?php echo $this->url('formation-instance/restaurer-agent', ["inscrit" => $demande->getId()], [], true); ?>"
                           title="Restaurer la demande externe"
                        >
                            <span class="icon icon-restaurer"></span></a>
                    <?php endif; ?>
                <?php else : ?>
                    <span class="icon icon-historiser nope"></span>
                <?php endif; ?>
<!--                --><?php //if ($canSupprimer) : ?>
<!--                    --><?php ///** @see \Formation\Controller\DemandeExterneController::supprimerAction() */ ?>
<!--                    <a href="--><?php //echo $this->url('formation/demande-externe/supprimer', ["demande-externe" => $demande->getId()], [], true); ?><!--"-->
<!--                       class="ajax-modal" data-event="modification"-->
<!--                       title="Supprimer définitivement la demande externe"-->
<!--                    >-->
<!--                        <span class="icon icon-unchecked text-danger"></span></a>-->
<!--                --><?php //else : ?>
<!--                    <span class="icon icon-unchecked nope"></span>-->
<!--                --><?php //endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<h2>
    Demandes de formation externe
</h2>

<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th class="agent"> Agent             </th>
            <th class="formation"> Formation </th>
            <th> Organisme </th>
            <th class="etat"> État </th>
            <th class="action"> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($demandesExternes as $demande) : ?>
        <tr class=" <?php if ($demande->estHistorise()) echo " historise "; ?> ">
            <td> <?php echo $demande->getAgent()->getDenomination(); ?> </td>
            <td> <?php echo $demande->getLibelle(); ?> </td>
            <td> <?php echo $demande->getOrganisme(); ?> </td>
            <td>
                <?php
                echo $this->etatinstance($demande->getEtatActif());
                ?> </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Formation\Controller\DemandeExterneController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/demande-externe/afficher', ['demande-externe' => $demande->getId()],[], true); ?>"
                    class="ajax-modal">
                    <span class="icon icon-voir"></span></a>
                <?php else : ?>
                    <span class="icon icon-voir nope"></span>
                <?php endif; ?>
                <?php if ($canValider) : ?>
                    <?php /** @see \Formation\Controller\DemandeExterneController::validerDrhAction() */ ?>
                    <a href="<?php echo $this->url('formation/demande-externe/valider-drh', ['demande-externe' => $demande->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-ok text-success"></span></a>
                    <?php /** @see \Formation\Controller\DemandeExterneController::refuserDrhAction() */ ?>
                    <a href="<?php echo $this->url('formation/demande-externe/refuser-drh', ['demande-externe' => $demande->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-ko text-danger"></span></a>
                <?php else: ?>
                    <span class="icon icon-ok nope"></span>
                    <span class="icon icon-ko nope"></span>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($demande->estNonHistorise()) : ?>
                        <?php /** @see \Formation\Controller\DemandeExterneController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('formation/demande-externe/historiser', ['demande-externe' => $demande->getId()], [], true); ?>"
                           title="Supprimer la demande externe"
                        >
                            <span class="icon icon-historiser"></span></a>
                    <?php else : ?>
                <?php /** @see \Formation\Controller\DemandeExterneController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('formation/demande-externe/restaurer', ["demande-externe" => $demande->getId()], [], true); ?>"
                           title="Restaurer la demande externe"
                        >
                            <span class="icon icon-restaurer"></span></a>
                    <?php endif; ?>
                <?php else : ?>
                    <span class="icon icon-historiser nope"></span>
                <?php endif; ?>
<!--                --><?php //if ($canSupprimer) : ?>
<!--                    --><?php ///** @see \Formation\Controller\DemandeExterneController::supprimerAction() */ ?>
<!--                    <a href="--><?php //echo $this->url('formation/demande-externe/supprimer', ["demande-externe" => $demande->getId()], [], true); ?><!--"-->
<!--                       class="ajax-modal" data-event="modification"-->
<!--                       title="Supprimer définitivement la demande externe"-->
<!--                    >-->
<!--                        <span class="icon icon-unchecked text-danger"></span></a>-->
<!--                --><?php //else : ?>
<!--                    <span class="icon icon-unchecked nope"></span>-->
<!--                --><?php //endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });
    });
</script>

<style>
    th.etat {
        min-width:6rem;
        width:6rem;
    }

    th.action {
        min-width:7rem;
        width:7rem;
    }

    th.agent {
        min-width:20rem;
        width:20rem;
    }
    th.formation {
        min-width:30rem;
        width:30rem;
    }
</style>