<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Etat\EntretienProfessionnelEtats;

/**
 * @see \EntretienProfessionnel\View\Helper\CampagneInformationArrayViewHelper
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent[] $agents
 * @var array $options
 */

$mode = 'div';
if (isset($options['mode'])) $mode = $options['mode'];

$validerSuperieur = []; $validerAutorite = []; $validerAgent = []; $encours = []; $sans = [];
foreach ($entretiens as $entretien) {
    switch ($entretien->getEtat()->getCode()) {
        case EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_RESPONSABLE :
            $validerSuperieur[] = $entretien;
            break;
        case EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_HIERARCHIE :
            $validerAutorite[] = $entretien;
            break;
        case EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_AGENT :
            $validerAgent[] = $entretien;
            break;
        default :
            $encours[] = $entretien;
            break;
    }
}
foreach ($agents as $agent) {
    if (!isset($entretiens[$agent->getId()]))  $sans[] = $agent;
}

$nbValiderAgent = count($validerAgent);
$nbValiderAutorite = count($validerAutorite);
$nbValiderSuperieur = count($validerSuperieur);
$nbEncours = count($encours);
$nbSans = count($sans);
$nbTotal =  $nbValiderAgent + $nbValiderAutorite +  $nbValiderSuperieur + $nbEncours + $nbSans;

if ($nbTotal !== 0) {
    $ratioAgent = $nbValiderAgent / $nbTotal * 100;
    $ratioAutorite = $nbValiderAutorite / $nbTotal * 100;
    $ratioSuperieur = $nbValiderSuperieur / $nbTotal * 100;
    $ratioPlanifie = count($encours) / $nbTotal * 100;
    $ratioSans = 100 - ($ratioAgent + $ratioAutorite + $ratioSuperieur + $ratioPlanifie);
}

?>

<?php if ($mode === 'div') : ?>
    <div class="progress">
        <div class="progress-bar entretien-agent" role="progressbar" style="width: <?php echo $ratioAgent; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
             title="Entretiens complétés <?php echo $nbValiderAgent; ?>/<?php echo $nbTotal; ?>">
            <?php echo round($ratioAgent); ?>%</div>
        <div class="progress-bar entretien-autorite" role="progressbar" style="width: <?php echo $ratioAutorite; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
             title="Entretiens en attente de validation de l'agent <?php echo $nbValiderAutorite; ?>/<?php echo $nbTotal; ?>">
            <?php echo round($ratioAutorite); ?>%</div>
        <div class="progress-bar entretien-superieur" role="progressbar" style="width: <?php echo $ratioSuperieur; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
             title="Entretiens en attente de validation de l'autorité hiérarchique <?php echo $nbValiderSuperieur; ?>/<?php echo $nbTotal; ?>">
            <?php echo round($ratioSuperieur); ?>%</div>
        <div class="progress-bar planifie" role="progressbar" style="width: <?php echo $ratioPlanifie; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
             title="Entretiens planifiés <?php echo $nbEncours; ?>/<?php echo $nbTotal; ?>">
            <?php echo round($ratioPlanifie); ?>%</div>
        <div class="progress-bar sans"   role="progressbar" style="width: <?php echo $ratioSans; ?>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
             title="Entretiens non planifiés <?php echo $nbSans; ?>/<?php echo $nbTotal; ?>">
            <?php echo round($ratioSans); ?>%</div>
    </div>
<?php endif; ?>
<?php if ($mode === 'table') : ?>
    <table>
        <tr>
            <td class="entretien-agent" style="width: <?php echo $ratioAgent; ?>%;">
                <?php echo round($ratioAgent); ?>%
            </td>
            <td class="entretien-autorite" style="width: <?php echo $ratioAutorite; ?>%;">
                <?php echo round($ratioAutorite); ?>%
            </td>
            <td class="entretien-superieur" style="width: <?php echo $ratioSuperieur; ?>%;">
                <?php echo round($ratioSuperieur); ?>%
            </td>
            <td class="planifie" style="width: <?php echo $ratioPlanifie; ?>%;">
                <?php echo round($ratioPlanifie); ?>%
            </td>
            <td class="sans" style="width: <?php echo $ratioSans; ?>%;">
                <?php echo round($ratioSans); ?>%
            </td>
        </tr>
    </table>
<?php endif; ?>


<div style="margin:0.25rem;">
    <span class="legende entretien-agent">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretien complétés <br/>
    <span class="legende entretien-autorite">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretien en attente de validation de l'agent <br/>
    <span class="legende entretien-superieur">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretien en attente de validation de l'autorité hiérarchique <br/>
    <span class="legende planifie">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretien planifié <br/>
    <span class="legende sans">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretien non planifié <br/>
</div>

<style>
    .sans {
        background-color: #960000;
    }
    .planifie {
        background-color: #ff6c0a;
    }
    .entretien-superieur {
        background-color: #ffcc01;
    }
    .entretien-autorite {
        background-color: #9dc500;
    }
    .entretien-agent {
        background-color: #009600;
    }

    span.legende {
        border:1px solid black;
        border-radius: 0.25rem;
        min-width: 3rem;
        margin-right: 2rem;
    }
</style>