<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Etat\EntretienProfessionnelEtats;

/**
 * @see \EntretienProfessionnel\View\Helper\CampagneAvancementViewHelper
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent[]|null $agents
 * @var int|null $nbAgents
 * @var array $options
 */

$mode = 'div';
$array = false;
if (isset($options['mode'])) $mode = $options['mode'];
if (isset($options['array'])) $array = $options['array'];

if ($nbAgents === null) {
    if ($agents !== null) $nbAgents = count($agents);
}

$validerSuperieur = []; $validerObservation = []; $validerAutorite = []; $validerAgent = []; $encours = []; $sans = [];
if ($array === false) {
    foreach ($entretiens as $entretien) {
        if ($entretien->getEtatActif() === null) {
            $encours[] = $entretien;
            //throw new RuntimeException("L'entretien #".$entretien->getId()." na pas d'état actif");
        } else {
            switch ($entretien->getEtatActif()->getType()->getCode()) {
                case EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_RESPONSABLE :
                    $validerSuperieur[] = $entretien;
                    break;
                case EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_OBSERVATION :
                    $validerObservation[] = $entretien;
                    break;
                case EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_HIERARCHIE :
                    $validerAutorite[] = $entretien;
                    break;
                case EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_AGENT :
                    $validerAgent[] = $entretien;
                    break;
                default :
                    $encours[] = $entretien;
                    break;
            }
        }
    }

    foreach ($agents as $agent) {
        if (!isset($entretiens[$agent->getId()])) $sans[] = $agent;
    }
} else {
    $validerSuperieur = $entretiens[EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_RESPONSABLE] ?? [];
    $validerObservation = $entretiens[EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_OBSERVATION] ?? [];
    $validerAutorite = $entretiens[EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_HIERARCHIE] ?? [];
    $validerAgent = $entretiens[EntretienProfessionnelEtats::ENTRETIEN_VALIDATION_AGENT] ?? [];
    $encours =  array_merge($entretiens[EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTER] ?? [], $entretiens[EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTATION] ?? []);
}

$nbValiderAgent = count($validerAgent);
$nbValiderAutorite = count($validerAutorite);
$nbValiderObservation = count($validerObservation);
$nbValiderSuperieur = count($validerSuperieur);
$nbEncours = count($encours);
$nbSans = $nbAgents - ($nbValiderAgent + $nbValiderObservation + $nbValiderAutorite +  $nbValiderSuperieur + $nbEncours);

$nbTotal =  $nbValiderAgent +  $nbValiderObservation + $nbValiderAutorite +  $nbValiderSuperieur + $nbEncours + $nbSans;

$ratioAgent = "NC"; $ratioObservation = "NC"; $ratioAutorite = "NC"; $ratioSuperieur = "NC"; $ratioPlanifie = "NC"; $ratioSans = "NC";
if ($nbTotal !== 0) {
    $ratioAgent = $nbValiderAgent / $nbTotal * 100;
    $ratioAutorite = $nbValiderAutorite / $nbTotal * 100;
    $ratioSuperieur = $nbValiderSuperieur / $nbTotal * 100;
    $ratioObservation = $nbValiderObservation / $nbTotal * 100;
    $ratioPlanifie = count($encours) / $nbTotal * 100;
    $ratioSans = 100 - ($ratioAgent + $ratioAutorite + $ratioSuperieur + $ratioPlanifie + $ratioObservation);
}

?>

<?php if ($mode === 'div') : ?>
    <?php if ($nbTotal !== 0) : ?>
        <div class="progress">
            <div class="progress-bar entretien-agent" role="progressbar" style="width: <?php echo $ratioAgent; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens complétés <?php echo $nbValiderAgent; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioAgent); ?>%</div>
            <div class="progress-bar entretien-autorite" role="progressbar" style="width: <?php echo $ratioAutorite; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens validés par l'autorité hiérarchique <?php echo $nbValiderAutorite; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioAutorite); ?>%</div>
            <div class="progress-bar entretien-observation" role="progressbar" style="width: <?php echo $ratioObservation; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens avec des observations émises par l'agent·e <?php echo $nbValiderObservation; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioObservation); ?>%</div>
            <div class="progress-bar entretien-superieur" role="progressbar" style="width: <?php echo $ratioSuperieur; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens validés par le ou la supérieure hierarchique <?php echo $nbValiderSuperieur; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioSuperieur); ?>%</div>
            <div class="progress-bar planifie" role="progressbar" style="width: <?php echo $ratioPlanifie; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens planifiés <?php echo $nbEncours; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioPlanifie); ?>%</div>
            <div class="progress-bar sans"   role="progressbar" style="width: <?php echo $ratioSans; ?>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens non planifiés <?php echo $nbSans; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioSans); ?>%</div>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php if ($mode === 'table') : ?>
    <table>
        <tr>
            <td class="entretien-agent" style="width: <?php echo $ratioAgent; ?>%;">
                <?php echo round($ratioAgent); ?>%
            </td>
            <td class="entretien-autorite" style="width: <?php echo $ratioAutorite; ?>%;">
                <?php echo round($ratioAutorite); ?>%
            </td>
            <td class="entretien-superieur" style="width: <?php echo $ratioSuperieur; ?>%;">
                <?php echo round($ratioSuperieur); ?>%
            </td>
            <td class="planifie" style="width: <?php echo $ratioPlanifie; ?>%;">
                <?php echo round($ratioPlanifie); ?>%
            </td>
            <td class="sans" style="width: <?php echo $ratioSans; ?>%;">
                <?php echo round($ratioSans); ?>%
            </td>
        </tr>
    </table>
<?php endif; ?>


<div style="margin:0.25rem;">
    <span class="legende entretien-agent">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens complétés <br/>
    <span class="legende entretien-autorite">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens validés par l'autorité hiérarchique <br/>
    <span class="legende entretien-observation">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens avec des observations de l'agent·e<br/>
    <span class="legende entretien-superieur">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens validés par le ou la supérieur·e hiérarchique <br/>
    <span class="legende planifie">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens planifiés <br/>
    <span class="legende sans">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens non planifiés <br/>
</div>

<style>
    .sans {
        background-color: #960000;
    }
    .planifie {
        background-color: #ff6c0a;
    }
    .entretien-superieur {
        background-color: #ffcc01;
    }
    .entretien-observation {
        background-color: rgb(183,182,12);
    }
    .entretien-autorite {
        background-color: rgb(110,161,23);
    }
    .entretien-agent {
        background-color: rgb(34,139,34);
    }

    span.legende {
        border:1px solid black;
        border-radius: 0.25rem;
        min-width: 3rem;
        margin-right: 2rem;
    }
</style>