<?php

use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;

/**
 * @see \EntretienProfessionnel\View\Helper\ConvocationArrayViewHelper
 * @var Agent[] $agents
 * @var Campagne $campagne
 * @var array $options[]
 */

$canAfficher = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canConvoquer = ($campagne->estEnCours() AND $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_CONVOQUER)));
$canAction = ($canAfficher OR $canConvoquer);

$raison = (isset($options['raison']))?$options['raison']:[];
?>

<table class="table table-condensed table-hover" id="<?php echo $options['id']; ?>">
    <thead>
        <tr>
            <th class="col-md-4" data-type="string"> Dénomination </th>
            <th class="col-md-4"> Affectation·s </th>
            <?php if ($canAction) : ?>
                <th class="col-md-3"> Grade·s </th>
                <th class="col-md-1 action">
                    Action
                </th>
            <?php else: ?>
                <th class="col-md-4"> Grade·s </th>
            <?php endif; ?>

        </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) : ?>
        <tr>
            <td data-order="<?php echo $agent->getDenomination(); ?>"> <?php echo $agent->getDenomination(false, true, true); ?>
                <?php if (isset($raison[$agent->getId()]) AND trim($raison[$agent->getId()]) !== '<ul></ul>') : ?>
                    <span class="icon icon-information" data-bs-toggle="tooltip" data-bs-html="true"
                          <?php if (isset($raison[$agent->getId()])) : ?>
                            title="<?php echo $raison[$agent->getId()]; ?>"
                          <?php endif; ?>
                    ></span>
                <?php endif; ?>
            </td>
            <td>
                <?php $affectations = $agent->getAffectationsActifs($campagne->getDateDebut()); ?>
                <?php if (empty($affectations)) : ?>
                    <span class="text-warning">
                        <span class="icon icon-attention"></span>
                        Aucune affectation à la date du <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?>
                    </span>
                <?php else : ?>
                    <?php foreach ($affectations as $affectation) : ?>
                         <?php echo $affectation->getStructure()->getLibelleLong(); ?> <br/>
                    <?php endforeach; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php $grades = $agent->getGradesActifs($campagne->getDateDebut()); ?>
                <?php if (empty($grades)) : ?>
                    <span class="text-warning">
                        <span class="icon icon-attention"></span>
                        Aucun grade à la date du <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?>
                    </span>
                <?php else : ?>
                    <?php foreach ($grades as $grade) : ?>
                        <?php if ($grade->getGrade() === null): ?>
                        <span class="text-warning">
                            <span class="icon icon-attention">
                                Aucun grade
                            </span>
                        </span>
                        <?php else : ?>
                            <?php echo $grade->getGrade()->getLibelleLong(); ?> <br/>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </td>
            <?php if ($canAction) : ?>
            <td class="action">
                <?php if ($this->isAllowed($agent, AgentPrivileges::AGENT_AFFICHER)) : ?>
                    <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                    <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                       target="_blank"
                       class="action secondary"
                    >
                        <span class="icon icon-user"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php
                    $entretien = new EntretienProfessionnel(); $entretien->setAgent($agent);
                    $canConvoquer = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_CONVOQUER);
//                    $canConvoquer = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_CONVOQUER));
                ?>
                <?php
                    if ($campagne->estEnCours() AND $canConvoquer) : ?>
                    <br>
                    <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::creerAction() */?>
                    <a
                        href="<?php echo $this->url('entretien-professionnel/creer', ['campagne' => $campagne->getId()], ["query" => ['agent' => $agent->getId()]], [], true); ?>"
                        class="ajax-modal action primary" data-event="modification"
                    >
                        <span class="icon icon-ajouter"></span>
                        Convoquer
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $("table#<?php echo $options['id']; ?>").DataTable( {
            'autoWidth' : false,
            'paging' : false,
            'searching' : true,
            'info' : false,
            language: {
                url: '/js/datatables_fr.json'
            },
        });
    });
</script>

<style>
    .tooltip-inner {
        max-width: 500px;
        text-align: left;
        padding: 0.5rem;
        margin: 0.5rem;
    };
</style>