<?php

/**
 * *** 27 mars 2026 ***
 * Discussion à propos des dates à considérer dans ces tableaux.
 * Les agents présentés ici n'ont pas encore d'entretien professionnel d'où le fait qu'ils soient convocable.
 *
 * Si la campagne n'a pas encore commencé, alors on utilise la date de début de campagne.
 * Si la campagne est en cours, alors on utilise la date du jour.
 * Si la campagne est terminée, alors on utilise la date de fin de la campagne
 *
 * Attention lorsque la campagne est en cours :
 * * Marseille souhaite la date de jour
 * * Montpellier souhaite la date de début de la campagne
 * * Marine serait plus pour la date de prise de poste
 *
 *  Quid peut-on le rendre facilement paramétrable ?
 *  1 - ajout d'une méthode dans la campagne pour retourner la date de situation à considérer
 */


use Agent\Entity\Db\AgentAffectation;
use Agent\Entity\Db\AgentGrade;
use Agent\Entity\Db\AgentStatut;
use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentAutorite;
use Application\Entity\Db\AgentSuperieur;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;

/**
 * @see \EntretienProfessionnel\View\Helper\ConvocationArrayViewHelper
 * @var Agent[] $agents
 * @var Campagne $campagne
 * @var AgentAffectation[] $affectations
 * @var AgentAutorite[] $autorites
 * @var AgentGrade[] $grades
 * @var AgentStatut[] $statuts
 * @var AgentSuperieur[] $superieurs
 * @var array $options[]
 */

$canAfficher = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canConvoquer = ($campagne->estEnCours() AND $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_CONVOQUER)));
$canAction = ($canAfficher OR $canConvoquer);

$raison = (isset($options['raison']))?$options['raison']:[];


$dateSituation = $campagne->getDateSituation();
$dateSituationAsString = $dateSituation?->format('d/m/Y');

?>

<div class="alert alert-info" style="margin-top: .5rem;">
    Date de situation considérée : <?php echo $dateSituationAsString; ?>
</div>

<table class="table table-condensed table-hover" id="<?php echo $options['id']; ?>">
    <thead>
        <tr>
            <th class="col-md-2" data-type="string"> Dénomination </th>
            <th class="col-md-2" data-type="string"> Supérieur·es </th>
            <th class="col-md-2" data-type="string"> Autorités </th>
            <?php if ($canAction) : ?>
                <th class="col-md-5"> Situation </th>
                <th class="col-md-1 action">
                    Action
                </th>
            <?php else: ?>
                <th class="col-md-6"> Situation </th>
            <?php endif; ?>

        </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) : ?>
        <tr>
            <td data-order="<?php echo $agent->getDenomination(); ?>"> <?php echo $agent->getDenomination(false, true, true); ?>
                <?php if (isset($raison[$agent->getId()]) AND trim($raison[$agent->getId()]) !== '') : ?>
                    <span class="icon icon-information" data-bs-toggle="tooltip" data-bs-html="true"
                            title="<ul><?php echo $raison[$agent->getId()]; ?></ul>"
                    ></span>
                <?php endif; ?>
            </td>
            <td>
                <?php if (empty($superieurs[$agent->getId()])) : ?>
                    <span class="text-warning">
                        <span class="icon icon-attention"></span>
                        Aucun·e supérieur·e connu à la date du <?php echo $dateSituationAsString; ?>
                    </span>
                    <br>
                <?php else: ?>
                    <ul>
                        <?php foreach ($superieurs[$agent->getId()] as $superieur) : ?>
                            <li><?php echo $superieur->getSuperieur()->getDenomination(); ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </td>
            <td>
                <?php if (empty($autorites[$agent->getId()])): ?>
                    <span class="text-warning">
                        <span class="icon icon-attention"></span>
                        Aucune autorité connue à la date du <?php echo $dateSituationAsString; ?>
                    </span>
                <?php else: ?>
                    <ul>
                        <?php foreach ($autorites[$agent->getId()] as $autorite) : ?>
                            <li><?php echo $autorite->getAutorite()->getDenomination(); ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </td>
            <td>
                <dl class="row">
                    <dt class="col-md-4"> Affectation·s </dt>
                    <dd class="col-md-8">
                        <?php if (empty($affectations[$agent->getId()])) : ?>
                            <span class="text-warning">
                                <span class="icon icon-attention"></span>
                                Aucune affectation à la date du <?php echo $dateSituationAsString ?>
                            </span>
                        <?php else : ?>
                            <?php foreach ($affectations[$agent->getId()] as $affectation) : ?>
                                 <?php echo $affectation->getStructure()->getLibelleLong(); ?>
                                <br>
                            <small>
                                <?php echo $affectation->getDateDebut()?$affectation->getDateDebut()->format('d/m/Y'):" ---- "; ?>
                                &rightarrow;
                                <?php echo $affectation->getDateFin()?$affectation->getDateFin()->format('d/m/Y'):" ---- "; ?>
                            </small>
                                <br>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </dd>
                    <dt class="col-md-4"> Grade·s</dt>
                    <dd class="col-md-8">
                        <?php if (empty($grades[$agent->getId()])) : ?>
                            <span class="text-warning">
                                <span class="icon icon-attention"></span>
                                Aucun grade à la date du <?php echo $dateSituationAsString; ?>
                            </span>
                        <?php else : ?>
                            <?php foreach ($grades[$agent->getId()] as $grade) : ?>
                                <?php if ($grade->getGrade() === null): ?>
                                <span class="text-warning">
                                    <span class="icon icon-attention">
                                        Aucun grade
                                    </span>
                                </span>
                                <?php else : ?>
                                    <?php echo $grade->getGrade()->getLibelleLong(); ?>
                                    <br>
                                <small>
                                    <?php echo $grade->getDateDebut()?$grade->getDateDebut()->format('d/m/Y'):" ---- "; ?>
                                    &rightarrow;
                                    <?php echo $grade->getDateFin()?$grade->getDateFin()->format('d/m/Y'):" ---- "; ?>
                                </small>
                                    <br>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <dt class="col-md-4"> Statut·s</dt>
                        <dd class="col-md-8">
                            <?php
                                $temoins = [];
                                foreach ($statuts[$agent->getId()]??[] as $statut) {
                                    foreach (AgentStatut::TEMOINS as $temoin) {
                                        if ($statut->getTemoin($temoin)) {
                                            $temoins[$temoin] = $temoin;
                                        }
                                    }
                                }
                            ?>
                            <?php foreach ($temoins as $temoin) : ?>
                                <span class="badge"><?php echo $temoin; ?></span>
                            <?php endforeach; ?>
                        </dd>
                        <?php endif; ?>
                    </dd>
                </dl>
            </td>
            <?php if ($canAction) : ?>
            <td class="action">
<!--                --><?php //if ($this->isAllowed($agent, AgentPrivileges::AGENT_AFFICHER)) : ?>
                <?php if ($this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER))) : ?>
                    <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                    <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                       target="_blank"
                       class="action secondary"
                    >
                        <span class="icon icon-user"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php
                    $entretien = new EntretienProfessionnel(); $entretien->setAgent($agent);
//                    $canConvoquer = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_CONVOQUER);
                ?>
                <?php
                    if ($campagne->estEnCours() AND $canConvoquer) : ?>
                    <br>
                    <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::creerAction() */?>
                    <a
                        href="<?php echo $this->url('entretien-professionnel/creer', ['campagne' => $campagne->getId()], ["query" => ['agent' => $agent->getId()]], [], true); ?>"
                        class="ajax-modal action primary" data-event="modification"
                    >
                        <span class="icon icon-ajouter"></span>
                        Convoquer
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function() {
        $("table#<?php echo $options['id']; ?>").DataTable( {
            'autoWidth' : false,
            'paging' : false,
            'searching' : true,
            'info' : false,
            language: {
                url: '/js/datatables_fr.json'
            },
        });
    });
</script>

<style>
    .tooltip-inner {
        max-width: 500px;
        text-align: left;
        padding: 0.5rem;
        margin: 0.5rem;
    };
</style>