<?php

/**
 * @see \Application\Controller\SynchroController::indexAction()
 * @var SynchroJob[] $jobs
 * @var SynchroJob $synchro
 */

use Application\Entity\Db\SynchroJob;

$this->headTitle('Synchronisations');

?>

<h1 class="page-header">
    Synchronisation
</h1>

<div class="main">

    <h2> Listes des synchros </h2>

    <?php foreach ($jobs as $job): ?>
        <?php echo $job->getKey(); ?> - <?php echo $job->getEntityClass(); ?> - <?php echo $job->getUrl(); ?> <br/>
        <p>
            <?php echo $job->getDescription(); ?>
        </p>
    <?php endforeach; ?>

    <h2> Test </h2>

    <?php echo $synchro->getKey(); ?> - <?php echo $synchro->getEntityClass(); ?> - <?php echo $synchro->getUrl(); ?> <br/>
    <p>
        <?php echo $synchro->getDescription(); ?>
    </p>


</div>
