<?php

/**
 * @see CompetenceController::afficherAction()
 *
 * @var Competence $competence
 * @var FicheMetier[] $fiches
 * @var Agent[] $agents
 * @var bool $displayCodeFonction
 */

use Application\Entity\Db\Agent;
use Element\Entity\Db\Competence;
use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Entity\Db\Mission;

?>

<dl class="row">
    <dt class="col-md-4"> Libellé </dt>
    <dd class="col-md-8"> <?php echo $competence->getLibelle(); ?> </dd>
    <dt class="col-md-4"> Type </dt>
    <dd class="col-md-8"> <?php echo ($competence->getType())?$competence->getType()->getLibelle():"Aucun"; ?> </dd>
    <dt class="col-md-4"> Thème </dt>
    <dd class="col-md-8"> <?php echo ($competence->getTheme())?$competence->getTheme()->getLibelle():"Aucun"; ?> </dd>
    <dt class="col-md-4"> Description </dt>
    <dd class="col-md-8"> <?php echo $competence->getDescription(); ?> </dd>
    <dt class="col-md-4"> Référence </dt>
    <dd class="col-md-8">
        <?php echo ($competence->getReferentiel())?$competence->printReference():"Aucun"; ?>
    </dd>
    <dt class="col-md-4"> Codes Emploi Types</dt>
    <dd class="col-md-8">
        <?php if ($competence->getCodesEmploiType()) : ?>
            <?php $codes =  explode("|", $competence->getCodesEmploiType()); ?>
            <ul>
            <?php foreach ($codes as $code) : ?>
                <li><?php echo $code; ?></li>
            <?php endforeach; ?>
            </ul>
        <?php else : ?>
            <span class="missing-data">Aucun code emploi type</span>
        <?php endif; ?>
    </dd>
    <?php if ($displayCodeFonction === true) : ?>
        <dt class="col-md-4"> Codes Fonction</dt>
        <dd class="col-md-8">
            <?php if ($competence->getCodesFonction()) : ?>
                <?php $codes =  explode("|", $competence->getCodesFonction()); ?>
                <ul>
                    <?php foreach ($codes as $code) : ?>
                        <li><?php echo $code; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php else : ?>
                <span class="missing-data">Aucun code fonction</span>
            <?php endif; ?>
        </dd>
    <?php endif; ?>
    <dt class="col-md-4"> Fiche·s metier·s </dt>
    <dd class="col-md-8">
        <!-- Nombre de fiches metiers : -->
        <?php echo count($fiches); ?> fiche·s métier·s
        <ul>
            <?php foreach ($fiches as $fiche) : ?>
                <li>
                    <?php if ($fiche->getLibelle()): ?>
                        <?php echo $fiche->getLibelle(); ?> (#<?php echo $fiche->getId(); ?>)
                    <?php endif; ?>
                    <?php if ($displayCodeFonction === true) : ?>
                        <?php if ($fiche->getCodeFonction()) : ?>
                            <code>
                                <?php echo $fiche->getCodeFonction()->computeCode(); ?>
                            </code>
                        <?php else : ?>
                            <span class="missing-data">Aucun code fonction</span>
                        <?php endif; ?>
                    <?php endif ?>

                </li>
            <?php endforeach; ?>
        </ul>
    </dd>
</dl>

<h2>  Agents ayant en acquis la compétence </h2>

<?php if (!empty($agents)) : ?>
    <ul>
        <?php foreach($agents as $agent): ?>
            <li> <?php echo $agent->getDenomination(true); ?> </li>
        <?php endforeach; ?>
    </ul>
<?php else : ?>
    Aucun·e agent·e ne possède cette compétence
<?php endif; ?>
