<?php

/**
 * @see \Element\Controller\CompetenceController::importerAction()
 * @var ImportationForm $form // todo quid de le remplacer par un formulaire sur place ...
 * @var CompetenceReferentiel[] $referentiels
 * @var Competence[] $competences
 * @var array $data
 * @var array $file
 * @var string[] $info
 * @var string[] $warning
 * @var string[] $error
 */

use Element\Entity\Db\Competence;
use Element\Entity\Db\CompetenceReferentiel;
use Element\Provider\Privilege\CompetencePrivileges;
use FicheReferentiel\Form\Importation\ImportationForm;

$this->headTitle("Importation de compétences");

$canCompetenceIndex = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_INDEX));
?>

<div class="row">
    <div class="col-md-6">
        <h1 class="page-header"> Importation de compétences</h1>
    </div>
    <div class="col-md-6">
        <?php if ($canCompetenceIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceController::listingAction() */ ?>
            <a href="<?php echo $this->url('element/competence/listing', [], [], true); ?>" class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux compétences</a>
        <?php endif; ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Importation de compétences depuis un CSV</div>
            <div class="card-body">
                <form enctype="multipart/form-data"
                      action="<?php echo $this->url('element/competence/importer', ['path' => null], [], true); ?>"
                      method="post">
                    <label for="file">Fichier à importer <span class="icon icon-obligatoire" title="Champ obligatoire"></span></label>
                    <input type="file" name="file" id="file" class="form-control" accept=".csv"/>
                    <label for="referentiel"> Référentiel <span class="icon icon-obligatoire" title="Champ obligatoire"></span> </label>
                    <select class="selectpicker show-tick form-control" id="referentiel" name="referentiel">
                        <option value="">Sélectionnez un référentiel</option>
                        <?php foreach ($referentiels as $referentiel): ?>
                            <option value="<?php echo $referentiel->getId(); ?>"
                                    <?php if (isset($data["referentiel"]) AND $data["referentiel"] == $referentiel->getId()) : ?>
                                        selected
                                    <?php endif; ?>
                            >
                                <?php echo $referentiel->getLibelleCourt(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <br>
                    <label for="mode"> Mode de traitement <span class="icon icon-obligatoire" title="Champ obligatoire"></span></label>
                    <select class="selectpicker show-tick form-control" id="mode" name="mode">
                        <option value="preview"
                            <?php if (isset($data["mode"]) AND $data["mode"] === "preview") : ?>
                                selected
                            <?php endif; ?>
                        >Prévisualisation</option>
                        <option value="import"
                            <?php if (isset($data["mode"]) AND $data["mode"] === "preview") : ?>
                                selected
                            <?php endif; ?>
                        >Importation</option>
                    </select>
                    <br>
                    <button type='submit' class="btn btn-success">
                        <span class="icon icon-csv"></span>
                        Importer
                    </button>

                </form>
            </div>
        </div>

    </div>
    <div class="col-md-6">
        <div class="alert alert-info">
            <span class="icon icon-info"></span> <strong>À propos du format des imports de compétences.</strong>
            <br>
            Le format d'importation est celui proposé par <strong>Referens3</strong> avec l'ajout de la colonne <code>Discipline</code>.
            Il est à noter que l'importation ne tient pas compte de l'ordre des colonnes, mais du libellé (exact) de
            celles-ci.
            Voici la liste des libellés interprétés :
            <ul>
                <li><code>Id_compétence</code> <span class="icon icon-obligatoire" title="colonne obligatoire"></span>
                    l'identifiant unique de la compétence,
                </li>
                <li><code>Compétence</code> <span class="icon icon-obligatoire" title="colonne obligatoire"></span>
                    le libellé de la compétence,
                </li>
                <li><code>Registre</code> <span class="icon icon-obligatoire" title="colonne obligatoire"></span>
                    le type de la compétence (connaissance, compétence comportementale, compétence opérationnelle, compétence spécifique),
                </li>
                <li><code>Domaine</code> le ou les thèmes associés à la compétence,</li>
                <li><code>Définition</code> la définition asssociée à la compétence,</li>
                <li><code>Discipline</code> colonne pour les compétences spécifiques uniquement - laisser vide pour les compétences "normales",
                </li>
                <li><code>Synonymes</code> la liste des libellés synonymes,</li>
            </ul>
        </div>
    </div>
</div>

<?php if (!empty($error)) : ?>
    <div class="alert alert-danger">
        <ul>
            <?php foreach ($error as $item) : ?>
                <li><?php echo $item; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<?php if (!empty($warning)) : ?>
    <div class="alert alert-warning">
        <ul>
            <?php foreach ($warning as $item) : ?>
                <li><?php echo $item; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<?php if (!empty($info)) : ?>
    <div class="alert alert-info">
        <ul>
            <?php foreach ($info as $item) : ?>
                <li><?php echo $item; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php if (!empty($competences)) : ?>
    <table class="table table-condensed" id="competences">
        <thead>
        <tr>
            <th class="col-md-1">Id</th>
            <th class="col-md-3">Libellé</th>
            <th class="col-md-2">Type</th>
            <th class="col-md-2">Thème</th>
            <th class="col-md-4">Autres</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($competences as $competence) : ?>
            <tr>
                <td> <?php echo $competence->getId(); ?></td>
                <td> <?php echo $competence->getLibelle(); ?></td>
                <td> <?php echo $competence->getType() ? $competence->getType()->getLibelle() : "<em>Aucun type</em>"; ?></td>
                <td> <?php echo $competence->getTheme() ? $competence->getTheme()->getLibelle() : "<em>Aucun theme</em>"; ?></td>
                <td>
                    <?php if ($competence->getDiscipline()) : ?>
                        <strong>Discipline </strong> <?php echo $competence->getDiscipline()->getLibelle(); ?>
                    <?php endif; ?>
                    <?php if ($competence->getDescription()) : ?>
                        <strong>Définition </strong> <?php echo $competence->getDescription(); ?>
                    <?php endif; ?>
                    <?php if ($competence->getSynonymes()) : ?>
                        <strong>Synonymes </strong> <?php echo $competence->getSynonymes(); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <script>
        $(function () {
            $('table#competences').DataTable({
                autoWidth: false,
                language: {
                    "url": "/js/datatables_fr.json",
                },
            });
        });
    </script>

<?php endif; ?>


<script>
    $(function () {
        $('select').selectpicker({});
    });
</script>