<?php

/**
 * @see CompetenceController::indexAction()
 * @var CompetenceType[]        $types
 * @var Competence[]            $competences
 * @var Niveau[]                $niveaux
 * @var array                   $competencesByType

 */

use Element\Entity\Db\Competence;
use Element\Entity\Db\CompetenceType;
use Element\Entity\Db\Niveau;
use Element\Provider\Privilege\CompetencePrivileges;
use Element\Provider\Privilege\CompetencereferentielPrivileges;
use Element\Provider\Privilege\CompetencethemePrivileges;
use Element\Provider\Privilege\CompetencetypePrivileges;

$canVoir        = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_AFFICHER));
$canAjouter     = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_AJOUTER));
$canModifier    = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_MODIFIER));
$canHistoriser  = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_HISTORISER));
$canDetruire    = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_EFFACER));
$canSubstituer  = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_SUBSTITUER));

$canCompetenceThemeIndex = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_INDEX));
$canCompetenceTypeIndex = $this->isAllowed(CompetencetypePrivileges::getResourceId(CompetencetypePrivileges::COMPETENCETYPE_INDEX));
$canCompetenceReferentielIndex = $this->isAllowed(CompetencereferentielPrivileges::getResourceId(CompetencereferentielPrivileges::COMPETENCEREFERENTIEL_INDEX));

$canAction = ($canVoir OR $canModifier OR $canSubstituer OR $canHistoriser OR $canDetruire);

$this->headTitle("Liste des compétences");

?>

<h1 class="page-header">
    Liste des compétences
</h1>

<div class="row">
    <div class="col-md-6">
        <?php if ($canAjouter) : ?>
            <?php /** @see \Element\Controller\CompetenceController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('element/competence/ajouter', [], [], true); ?>"
               class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter une compétence
            </a>
            <?php /** @see \Element\Controller\CompetenceImporterController::importerAction() */ ?>
            <a href="<?php echo $this->url('competence-import', [], [], true); ?>"
               class="btn btn-primary ajax-modal" >
                <span class="icon icon-ajouter"></span>
                Importer un référentiel
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <?php if ($canCompetenceThemeIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceThemeController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-theme', [], [], true); ?>"
               class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux thèmes</a>
        <?php endif; ?>

        <?php if ($canCompetenceTypeIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceTypeController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-type', [], [], true); ?>"
               class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux types</a>
        <?php endif; ?>

        <?php if ($canCompetenceReferentielIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceReferentielController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-referentiel', [], [], true); ?>"
               class="btn btn-secondary">
                <span class="icon icon-lister"></span>
                Accéder aux référentiels</a>
        <?php endif; ?>
    </div>
</div>

<?php foreach ($competencesByType as $type => $competences) : ?>
    <h2> Compétence : <?php echo  $type; ?> </h2>

    <table class="table table-condensed table-hover">
        <thead>
        <tr>
            <th> Libellé </th>
            <th> Thème </th>
            <th> Référence </th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($competences as $competence) : ?>
            <tr class="<?php if ($competence->estHistorise()) echo " historise "; ?>">
                <td> <?php echo $competence->getLibelle(); ?>
                    <?php if ($competence->getDescription() !== null AND trim($competence->getDescription() !== '')) : ?>
                        <span class="icon icon-information" title="<?php echo $competence->getDescription(); ?>"
                              data-bs-toggle="tooltip" data-bs-html="true"
                        ></span>
                    <?php endif; ?>
                </td>
                <td> <?php echo ($competence->getTheme())?$competence->getTheme()->getLibelle():"Aucun"; ?> </td>
                <td>
                    <?php echo ($competence->getReferentiel())?$this->competenceReference($competence):"Aucun"; ?>
                </td>
                <?php if ($canAction) : ?>
                <td class="action">
                    <?php if ($canVoir): ?>
                        <?php /** @see CompetenceController::afficherAction() */?>
                        <a href="<?php echo $this->url('element/competence/afficher', ['competence' => $competence->getId()], [], true); ?>"
                           class="ajax-modal">
                            <span class="icon icon-voir"></span>
                            Afficher
                        </a>
                    <?php endif; ?>
                    <?php if ($canModifier): ?>
                        <br>
                        <?php /** @see CompetenceController::modifierAction() */?>
                        <a href="<?php echo $this->url('element/competence/modifier', ['competence' => $competence->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification" >
                            <span class="icon icon-editer"></span>
                            Modifier
                        </a>
                    <?php endif; ?>
                    <?php if ($canSubstituer): ?>
                        <br>
                        <?php /** @see CompetenceController::substituerAction() */?>
                        <a href="<?php echo $this->url('element/competence/substituer', ['competence' => $competence->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification" >
                            <span class="icon icon-synchroniser"></span>
                            Fusionner
                        </a>
                    <?php endif; ?>
                    <?php if ($canHistoriser): ?>
                        <br/>
                        <?php if($competence->estNonHistorise()) : ?>
                            <?php /** @see CompetenceController::historiserAction() */?>
                            <a href="<?php echo $this->url('element/competence/historiser', ['competence' => $competence->getId()], [], true); ?>">
                                <span class="icon icon-historiser"></span>
                                Historiser
                            </a>
                        <?php else : ?>
                            <?php /** @see CompetenceController::restaurerAction() */?>
                            <a href="<?php echo $this->url('element/competence/restaurer', ['competence' => $competence->getId()], [], true); ?>">
                                <span class="icon icon-restaurer"></span>
                                Restaurer
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canDetruire): ?>
                        <br/>
                        <?php /** @see CompetenceController::detruireAction() */?>
                        <a href="<?php echo $this->url('element/competence/detruire', ['competence' => $competence->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification">
                            <span class="text-danger">
                                <span class="icon icon-unchecked"></span>
                                Supprimer
                            </span>
                        </a>
                    <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endforeach; ?>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

<style>
    span.badge.EMC2 {
        background: var(--unistrap-color-main);
    }

    span.badge.REFERENS3 {
        background: indianred;
    }
</style>
