<?php

/**
 * @see \Element\Controller\CompetenceController::rechercherAgentsAction()
 * @var Niveau[] $niveaux
 * @var Agent[]|null $agents
 */

use Application\Entity\Db\Agent;
use Element\Entity\Db\Niveau;

$this->headTitle("Rechercher des agent·es avec un ensemble de compétences");

?>

<h1 class="page-header">
    Rechercher des agent·es avec un ensemble de compétences
</h1>

<div class="card">
    <div class="card-header bg-default">
        Critères de recherche
    </div>
    <div class="card-body">
        <form method="get" action="<?php echo $this->url(); ?>">
        <div id="competence-criteres">
        <span class="header">Compétences</span>
            <div class="row">
                <div class="col-md-9">
                    <div id="competence-bloc">
                    </div>
                </div>
                <div class="col-md-3">
                    <button class="btn btn-primary" id="ajout-competence">
                        <span class="icon icon-plus"></span>
                        Ajouter un critère sur les compétences
                    </button>
                    <button class="btn btn-primary" id="raz-competence">
                        <span class="icon icon-gommer"></span>
                        Vider les critères sur les compétences
                    </button>
                </div>
            </div>
        </div>
        <div>
        <span class="header">Critères sur les agent·es</span>
            TODO
        </div>
        <div>
            <button class="btn btn-primary" id="rechercher">
                <span class="icon icon-search"></span>
                Rechercher des agents
            </button>
            <button class="btn btn-primary" id="raz">
                <span class="icon icon-gommer"></span>
                Remise à zéro
            </button>
        </div>
        </form>
    </div>
</div>



<?php if (isset($query)) : ?>
    <?php var_dump($query); ?>
<?php endif; ?>

<?php if ($agents === null) : ?>
    Aucun·e agent de remonté·e avec les critères de recherche
<?php else : ?>
    <table class="table table-condensed datatable">
        <thead>
            <tr>
                <th data-type="string"> Dénomination </th>
                <th> Affectation principale </th>
                <th> Statut </th>
                <th> Compétence </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($agents as $agent) : ?>
                <tr>
                    <td data-order="<?php echo $agent->getDenomination(); ?>"><?php echo $agent->getDenomination(true, true, true); ?></td>
                    <td>
                        <?php $affectation = $agent->getAffectationPrincipale(); ?>
                        <?php if ($affectation === null) : ?>
                            <span class="text-warning">
                                <span class="icon icon-attention"></span>
                                Aucune affectation principale
                            </span>
                        <?php else : ?>
                            <?php $structure = $affectation->getStructure(); $niveau2 = $structure?->getNiv2(); ?>
                            <?php if ($structure === null) : ?>
                                <span class="text-warning">
                                    <span class="icon icon-attention"></span>
                                    Aucune structure pour l'affecation #<?php echo $affectation->getId(); ?>
                                </span>
                            <?php else : ?>
                                <?php if ($niveau2 AND $niveau2 !== $structure) : ?>
                                    <?php echo $niveau2->getLibelleCourt(); ?> > <?php echo $structure->getLibelleCourt(); ?>
                                <?php else : ?>
                                    <?php echo $structure->getLibelleCourt(); ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>



<style>
    .card .card-body span.header {
        font-variant: small-caps;
        text-decoration: underline;
    }
</style>


<script>
    function generateSas2(idSas) {
        let text = ''
            + '<div class="mb-2">'
            + '     <input type="text" id="competence-filtre_'+idSas+'"              name="competence-filtre_'+idSas+'[id]"     placeholder="Aucune compétence" class="sas" value="" style="display:none;">'
            + '     <input type="text" id="competence-filtre_'+idSas+'-autocomplete" name="competence-filtre_'+idSas+'[label]"  placeholder="Aucune compétence" class="sas-autocomplete form-control form-control-sm" value="">'
            + '</div>'
            + ''
            ;
        return text;
    }

    function generateOperateurSelect(id) {
        let text =
            '<div class="col-md-3">'
            + '    <select id="operateur_'+id+'" name="operateur_'+id+'" class="selectpicker">'
            + '        <option value="">Aucun opérateur</option>'
            + '        <option value="superieur"> &gt; </option>'
            + '        <option value="superieur_ou_egal"> &ge; </option>'
            + '        <option value="egale"> &equals; </option>'
            + '        <option value="inferieur_ou_egal"> &le; </option>'
            + '        <option value="inferieur"> &lt; </option>'
            + '    </select>'
            + '</div>';
        return text;
    }

    function generateNiveauSelect(id) {
        let niveauId = 'undefined';
        let niveauLibelle = 'undefined';
        let text =
            '<div class="col-md-3">'
            + '    <select id="niveau_'+id+'" name="niveau_'+id+'" class="selectpicker">'
            + '        <option value="">Aucun niveau</option>'
            ;
            <?php foreach ($niveaux as $niveau): ?>
                 niveauId = "<?php echo $niveau->getId(); ?>";
                 niveauLibelle = "<?php echo $niveau->getLibelle(); ?>";
                text += '<option value="' + niveauId + '" >'+ niveauLibelle +'</option>';
            <?php endforeach; ?>
        text += '    </select>';
        text += '</div>';
        return text;
    }

    function ajouterCompetence(e) {
        if (e !== undefined) e.preventDefault();
        let id = Math.floor(Math.random() * 1000000);
        // let id = 15;
        $('div#competence-bloc').append(
            '<div class="row">' +
            '   <div class="col-md-1"> <span class="icon icon-minus text-danger"></span></div>' +
            '   <div class="col-md-5">' + generateSas2(id) + '</div>' +
            generateOperateurSelect(id) +
            generateNiveauSelect(id) +
            '</div>');
        $('select').selectpicker();

        var autocomp = $('.sas-autocomplete:last');
        console.log(autocomp);
        console.log("competence-filtre_"+id);
        autocomp.autocompleteUnicaen({
            elementDomId: "competence-filtre_"+id,
            source: '/element/competence/rechercher',
            minLength: 2,
            delay: 750
        });
    }

    $(function () {
        $('button#ajout-competence').on("click", function(e) { ajouterCompetence(e); });
    });


</script>



<style>
    ul.ui-autocomplete {
        z-index: 5000
    }
    .ui-autocomplete-loading {
        background: white url("//gest.unicaen.fr/images/ajax-loader-r.gif") right center no-repeat;
    }
</style>
<script>
    $(function() {
        ajouterCompetence();
    });
</script>