<?php

use Application\Entity\Db\Batiment;
use Application\Entity\Db\Site;

/**
 * @var Site[] $sites
 * @var Batiment[] $batiments
 */

$this->headTitle('Bâtiments et sites')
?>

<h1 class="page-header">
    Bâtiments et sites
</h1>

<div class="main">
    <h2>
        Sites
        <span class="badge"> <?php echo count($sites); ?> </span>
    </h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th> Id </th>
                <th> Libellé </th>
                <th> #Batiment </th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($sites as $site) : ?>
            <tr>
                <td> <?php echo $site->getId(); ?> </td>
                <td> <?php echo $site->getLibelle(); ?> </td>
                <td>
                    <?php
                        $text = "";
                        foreach ($site->getBatiments() as $batiment) $text .= $batiment->getLibelle()."\n";
                    ?>
                    <span title="<?php echo $text; ?>">
                        <?php echo count($site->getBatiments()); ?>
                        <span class="icon batiment"></span>
                    </span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="main">
    <h2>
        Bâtiments
        <span class="badge"> <?php echo count($batiments); ?> </span>
    </h2>

    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Id </th>
            <th> Libellé </th>
            <th> Site </th>
        </tr>
        </thead>
        <tbody>
            <?php foreach($batiments as $batiment) : ?>
                <tr>
                    <td> <?php echo $batiment->getId(); ?></td>
                    <td> <?php echo $batiment->getLibelle(); ?></td>
                    <td> <?php echo $batiment->getSite()->getLibelle(); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>