<?php

/**
 * @see IndicateurController::afficherAction()
 * @var Indicateur $indicateur
 * @var bool $exists
 * @var array $header
 * @var array $data
 */

use Indicateur\Entity\Db\Indicateur;

?>

<h1 class="page-header">
    Indicateur <br/>
    <?php echo $indicateur->getTitre(); ?>
</h1>

<?php if ($exists !== true) : ?>
    <div class="alert alert-danger">
        La vue matérialisée associée à l'indicateur ne semble pas exister.
    </div>
<?php else : ?>
    <div class="row">
        <?php /** @see IndicateurController::exportAction() */ ?>
        <a href="<?php echo $this->url('indicateur/exporter', ['indicateur' => $indicateur->getId()], [], true); ?>"
           class="btn btn-primary action"
        >
            <span class="icon icon-csv"></span>
            Exporter l'indicateur
        </a>

        <?php /** @see IndicateurController::rafraichirAction() */?>
        <a href="<?php echo $this->url('indicateur/rafraichir', ['indicateur' => $indicateur->getId()], [], true); ?>"
           class="btn btn-primary action"
        >
            <span class="icon icon-synchoniser"></span>
            Rafraichir l'indicateur
        </a>

        <small>dernier rafraichissement le <?php echo ($indicateur->getDernierRafraichissement()?$indicateur->getDernierRafraichissement()->format('d/m/Y à H:i:s'):"---"); ?></small>
    </div>

    <div role="tabpanel">
        <ul class="nav nav-tabs" role="tablist">
            <li>
                <a href="#indicateur" aria-controls="indicateur" role="tab" data-toggle="tabz">
                    Indicateur
                </a>
            </li>
            <li class="pull-right">
                <a href="#mail" aria-controls="mail" role="tab" data-toggle="tabz">
                    Mail
                </a>
            </li>
        </ul>
    </div>

    <div class="tab-content">

        <div id="indicateur" class="tab-pane " role="indicateur">
            <p class="lead">
                <?php echo $indicateur->getDescription(); ?>
            </p>

            <table id="datatable" class="table table-extra-condensed">
                <thead>
                <tr>
                    <?php foreach ($header as $item) : ?>
                        <th> <?php echo $item; ?> </th>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $item) : ?>
                        <tr>
                            <?php foreach ($item as $value) : ?>
                                <td><?php echo $value; ?></td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif; ?>

<script>
    $(document).ready(function() {
        $('#datatable').DataTable( {
            language: {
                url: '/localisation/fr_FR.json'
            }
        });
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "indicateur";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>