<?php

/**
 * @var Indicateur[] $indicateurs
 */

use Indicateur\Entity\Db\Indicateur;

?>

<h1 class="page-header">
    Indicateurs
</h1>

<div class="main">

    <table id="datatable" class="table table-condensed">
        <thead>
            <th> Titre </th>
            <th> Description </th>
            <th> Entity </th>
            <th> #Abonnement </th>
            <th> Action </th>
        </thead>
        <tbody>
            <?php foreach ($indicateurs as $indicateur) : ?>
                <tr>
                    <td> <?php echo $indicateur->getTitre(); ?> </td>
                    <td> <?php echo $indicateur->getDescription(); ?> </td>
                    <td> <?php echo $indicateur->getEntity(); ?> </td>
                    <td> <?php echo "TODO"; ?> </td>
                    <td> <?php echo "TODO"; ?> </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>
