<?php

/**
 * @see \Carriere\View\Helper\NiveauEnveloppeViewHelper
 * @var NiveauEnveloppe|null $niveauEnveloppe
 * @var array $options
 */

use Carriere\Entity\Db\NiveauEnveloppe;


?>

<?php if ($niveauEnveloppe === null) : ?>
    Non&nbsp;précisé
<?php else: ?>
    [<?php echo $niveauEnveloppe->getBorneInferieure()->getEtiquette(); ?>:<?php echo $niveauEnveloppe->getBorneSuperieure()->getEtiquette(); ?>]<br/>
    <?php if ($niveauEnveloppe->getValeurRecommandee()) : ?>
        Recommandé&nbsp;<?php echo $niveauEnveloppe->getValeurRecommandee()->getEtiquette(); ?>
    <?php endif; ?>
<?php endif; ?>


