<?php

use Application\Entity\Db\Fonction;

/**
 * @var Fonction $fonction
 */

?>

<dl class="dl-horizontal">
    <dt> Identifiant </dt>
    <dd> <?php echo $fonction->getId(); ?></dd>
    <dt> Source </dt>
    <dd>
        <?php echo $fonction->getSource(); ?>
        <?php if ($fonction->getIdSource()) : ?>
            <?php echo " - ". $fonction->getIdSource() ; ?>
        <?php endif; ?>
    </dd>
    <dt> Libellés </dt>
    <dd>
        <br/>
        <ul>
            <?php foreach ($fonction->getLibelles() as $libelle): ?>
                <li>
                    <span class="badge" style="width:2em;background-color: <?php echo ($libelle->getDefault())?"green":"stalegray"; ?>;">
                        <?php echo $libelle->getGenre(); ?>
                    </span>
                    <?php echo $libelle->getLibelle(); ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </dd>
    <dt> Modification </dt>
    <dd> <?php echo $fonction->getHistoModification()->format('d/m/Y à H:i'); ?></dd>
    <dt> Modificateur </dt>
    <dd> <?php echo $fonction->getHistoModificateur()->getDisplayName(); ?> </dd>
</dl>

