<?php

/**
 * @see \Application\Controller\FonctionController::indexAction()
 * @var FonctionActivite[] $activites
 * @var FonctionDestination[] $destinations
 */

use Application\Entity\Db\FonctionActivite;
use Application\Entity\Db\FonctionDestination;

?>

<h1 class="page-header">
    Fonctions
</h1>

<div class="main">
    <dl class="dl-horizontal">
        <dt> #Destination </dt>
        <dd> <?php echo count($destinations); ?> </dd>
        <dt> #Activite </dt>
        <dd> <?php echo count($activites); ?> </dd>
    </dl>

    <a href="<?php echo $this->url('fonction/destination/ajouter', [], [], true); ?>"
       class="btn btn-primary action ajax-modal" data-event="modification"
       >
        <span class="icon ajouter"></span>
        Ajouter une destination
    </a>

    <a href="<?php echo $this->url('fonction/activite/ajouter', [], [], true); ?>"
       class="btn btn-primary action ajax-modal" data-event="modification"
    >
        <span class="icon ajouter"></span>
        Ajouter une activité
    </a>

    <br/>
    <br/>

    <table class='fonction' >
        <?php foreach ($destinations as $destination) : ?>
            <tr>
                <td style="width:5rem;">
                    <?php echo $destination->getCode(); ?>

                    <br/>
                    <a href="<?php echo $this->url('fonction/destination/modifier', ['destination' => $destination->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                       data-toggle="tooltip" data-html="true" title="Modifier la destination">
                        <span class="icon editer"></span></a>
                    <a href="<?php echo $this->url('fonction/destination/supprimer', ['destination' => $destination->getId()], [], true); ?>"
                       data-toggle="tooltip" data-html="true" title="Supprimer la destination">
                        <span class="icon detruire"></span></a>
                </td>
                <td>
                    <?php echo $destination->getLibelle(); ?>
                </td>
                <td>
                    <table style='width:100%;'>
                    <?php
                        $activites = $destination->getActivites();
                        usort($activites, function(FonctionActivite $a, FonctionActivite $b) { return $a->getCode() > $b->getCode();});
                        foreach ($activites as $activite) : ?>
                        <tr>
                            <td style="width:5rem;">
                                <?php echo $activite->getCode(); ?>

                                <br/>
                                <a href="<?php echo $this->url('fonction/activite/modifier', ['activite' => $activite->getId()], [], true); ?>"
                                   class="ajax-modal" data-event="modification"
                                   data-toggle="tooltip" data-html="true" title="Modifier l'activité">
                                    <span class="icon editer"></span></a>
                                <a href="<?php echo $this->url('fonction/activite/supprimer', ['activite' => $activite->getId()], [], true); ?>"
                                   data-toggle="tooltip" data-html="true" title="Supprimer l'activité">
                                    <span class="icon detruire"></span></a>
                            </td>
                            <td>
                                <?php echo $activite->getLibelle(); ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                </td>
        <?php endforeach; ?>
    </table>
</div>

<style>
    table.fonction {
        width:100%;
    }
    table.fonction td {
        border:1px solid black;
    }
</style>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>