<?php

namespace Formation\Provider\Parametre;

class FormationParametres {

    const TYPE = 'FORMATION';

    const NB_PLACE_PRINCIPALE = 'NB_PLACE_PRINCIPALE';
    const NB_PLACE_COMPLEMENTAIRE = 'NB_PLACE_COMPLEMENTAIRE';

    const URL_PPP = 'URL_PPP';
    const MAIL_DRH_FORMATION = 'MAIL_DRH_FORMATION';
    const MAIL_PREVENTION_FORMATION = 'MAIL_PREVENTION_FORMATION';
    const MAIL_PERSONNEL = 'MAIL_PERSONNEL';


    const AUTO_FERMETURE = 'AUTO_FERMETURE';
    const AUTO_CONVOCATION = 'AUTO_CONVOCATION';
}