<?php

use Mailing\Entity\Db\Mail;

/**
 * @var Mail[] $mails
 */

$this->headTitle("Index des mails envoyées");
?>


<h1 class="page-header">
    Index des mails envoyées
</h1>

<a
        href="<?php echo $this->url('administration/mail-test', [], [] ,true);?>"
        class="btn btn-primary action"
>
    Envoie d'un mail de test
</a>

<table class="table table-extra-condensed">
    <thead>
        <tr>
<!--            <th> Id </th>-->
            <th> Status </th>
            <th> Date d'envoi </th>
            <th> Destinataires </th>
            <th> Redir </th>
            <th> Sujet </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($mails as $mail) : ?>
        <tr>
<!--            <td> --><?php //echo $mail->getId(); ?><!-- </td>-->
            <td> <?php echo htmlStatus($mail->getStatus()); ?> </td>
            <td> <?php echo $mail->getDateEnvoi()->format("H:i:s d/m/Y"); ?> </td>
            <td> <small><?php echo implode("<br/>",explode(",",$mail->getDestinatires())); ?></small> </td>
            <td> <?php echo htmlRedirection($mail->getRedir()); ?> </td>
            <td> <small><?php echo $mail->getSujet(); ?> </small> </td>
            <td>
                <a class="ajax-modal" href="<?php echo $this->url('administration/mails/affiche', ['mail' => $mail->getId()], [], true); ?>">
                    <span class="glyphicon glyphicon-eye-open"></span>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php
    function htmlStatus($status) {
        switch ($status) {
            case Mail::PENDING :
                $text = '<span class="badge badge-warning"> PENDING </span>';
                return $text;
            case Mail::SUCCESS :
                $text = '<span class="badge badge-success"> SUCCESS </span>';
                return $text;
            case Mail::FAILURE :
                $text = '<span class="badge badge-danger"> FAILURE </span>';
                return $text;
            default :
                $text = '<span class="badge"> FAILURE </span>';
                return $text;
        }
    }

    function htmlRedirection($redir) {
        if ($redir === 1) return '<span class="badge badge-success">&nbsp;</span>'; //"Oui";
        else return "";
    }
?>

<style>
    .badge-warning {
        background-color: #f89406;
    }

    .badge-success {
        background-color: #468847;
    }

    .badge-danger {
        background-color: #b94a48;
    }
</style>
