<?php

use Mailing\Model\Db\Mail;
use Mailing\Model\Db\MailType;
use Mailing\Provider\Privilege\MailingPrivileges;

/**
 * @see \Mailing\Controller\MailingController::indexAction()
 * @var Mail[] $mails
 * @var MailType[] $types
 */

$this->headTitle("Index des mails envoyées");

?>


<h1 class="page-header">
    Index des mails envoyées
</h1>


<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <li role="maillisting">
            <a href="#maillisting" aria-controls="maillisting" role="tab" data-toggle="tabz">
                Listing des mails
            </a>
        </li>

        <li role="mailtype">
            <a href="#mailtype" aria-controls="mailtype" role="tab" data-toggle="tabz">
                Types de mails &nbsp;
            </a>
        </li>
    </ul>

        <div class="main-with-tab">
            <div class="tab-content">

                <!-- listing ---------------------------------------------------------------------------------------------->
                <div id="maillisting" class="tab-pane " role="tabpanel">
                    <?php echo $this->partial('partial/liste-mail', ['mails' => $mails]); ?>
                </div>

                <!-- type ---------------------------------------------------------------------------------------------->
                <div id="mailtype" class="tab-pane " role="tabpanel">
                    <?php echo $this->partial('partial/liste-type', ['types' => $types]); ?>
                </div>

            </div>
        </div>

    </div>

<script>
    $(document).ready(function() {
        $('.datatable').DataTable( {
            // sorting: false,
            // paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "metier";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>