<?php

use Fichier\Entity\Db\Fichier;
use Formation\Entity\Db\DemandeExterne;
use Formation\Provider\Etat\DemandeExterneEtats;
use Formation\Provider\Privilege\DemandeexternePrivileges;
use Formation\Provider\Validation\DemandeExterneValidations;

/**
 * @see \Formation\View\Helper\DemandeExterneViewHelper
 * @var DemandeExterne $demande
 * @var array $options
 */

$retour = $options['retour'] ?? null;
$action = $options['action'] ?? true;
?>

<?php $canModifierDemande = $this->isAllowed($demande, DemandeexternePrivileges::DEMANDEEXTERNE_MODIFIER); ?>
<div class="row">

    <!-- DESCRIPTION -------------------------------------------------------------------------------------------------->
    <div class="col-md-7 description">

        <div>
        <?php echo $this->etatinstance($demande->getEtatActif(),['display-categorie' => false]); ?>
        <strong><?php echo $demande->getLibelle(); ?></strong>
        <br/>
        <?php echo $demande->getOrganisme(); ?> -
        <?php echo $demande->getLieu(); ?> ( du <?php echo $demande->getDebut()->format('d/m/Y'); ?> au <?php echo $demande->getFin()->format('d/m/Y'); ?>)
        </div>

        <div>
        <?php if (empty($demande->getDevis())) : ?>
            <div class="alert alert-danger">
                <span class="text-danger"><span class="icon icon-attention"></span> Aucun devis ! Pour pouvoir valider une demande, au moins un devis doit être déposé.</span>
            </div>
        <?php else : ?>
            <?php /** @var Fichier  $devis */
            foreach ($demande->getDevis() as $justificatif) : ?>
                <strong>Devis</strong>
                <a href="<?php echo $this->url('download-fichier', ['fichier' => $justificatif->getId()], [], true); ?>">
                    <span class="icon icon-fichier"></span>
                    <?php echo $justificatif->getNomOriginal(); ?>
                </a>&nbsp;
                <?php if ($canModifierDemande) : ?>
                    <?php /** @see \Formation\Controller\DemandeExterneController::retirerJustificatifAction() */ ?>
                    <a href="<?php echo $this->url('formation/demande-externe/retirer-justificatif', ['justificatif' => $justificatif->getId()], [], true); ?>" class="action">
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Retirer le devis
                        </span>
                    </a>
                <?php endif; ?>
                <br/>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php if (empty($demande->getProgrammes())) : ?>
            <div class="alert alert-danger">
                <span class="text-danger"><span class="icon icon-attention"></span> Aucun programme ! Pour pouvoir valider une demande, le programme de la formation doit être déposé.</span>
            </div>
        <?php else : ?>
            <?php /** @var Fichier  $devis */
            foreach ($demande->getDevis() as $justificatif) : ?>
                <strong>Programme</strong>
                <a href="<?php echo $this->url('download-fichier', ['fichier' => $justificatif->getId()], [], true); ?>">
                    <span class="icon icon-fichier"></span>
                    <?php echo $justificatif->getNomOriginal(); ?>
                </a>&nbsp;
                <?php if ($canModifierDemande) : ?>
                    <?php /** @see \Formation\Controller\DemandeExterneController::retirerJustificatifAction() */ ?>
                    <a href="<?php echo $this->url('formation/demande-externe/retirer-justificatif', ['justificatif' => $justificatif->getId()], [], true); ?>" class="action">
                    <span class="text-danger">
                        <span class="icon icon-unchecked"></span>
                        Retirer le programme
                    </span>
                    </a>
                <?php endif; ?>
                <br/>
            <?php endforeach; ?>
        <?php endif; ?>
        </div>
    </div>
    <div class="col-md-5">

        <?php if ($action) : ?>
        <!-- ACTION ------------------------------------------------------------------------------------------------------->
        <div>
        <?php
        $canModifierDemande = $this->isAllowed($demande, DemandeexternePrivileges::DEMANDEEXTERNE_MODIFIER);
        $canHistoriserDemande = $this->isAllowed($demande, DemandeexternePrivileges::DEMANDEEXTERNE_HISTORISER);
        ?>
        <?php if ($demande->isEtatActif(DemandeExterneEtats::ETAT_CREATION_EN_COURS)) : ?>
            <?php $canValiderAgentDemande = $this->isAllowed($demande, DemandeexternePrivileges::DEMANDEEXTERNE_VALIDER_AGENT); ?>
            <?php /** @see \Formation\Controller\DemandeExterneController::validerAgentAction() */?>
            <a  href="<?php echo $this->url('formation/demande-externe/valider-agent', ['demande-externe' => $demande->getId()], [], true); ?>"
                class="btn btn-success ajax-modal <?php if (!$canValiderAgentDemande OR empty($demande->isJustificatifsOk())) echo " disabled "; ?> " data-event="modification">
                <span class="icon icon-valider"></span>
                Valider la demande (Agent)
            </a>
        <?php endif; ?>
        <?php if ($canModifierDemande) : ?>
            <?php /** @see \Formation\Controller\DemandeExterneController::modifierAction() */?>
            <a  href="<?php echo $this->url('formation/demande-externe/modifier', ['demande-externe' => $demande->getId()], [], true); ?>"
                class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-modifier"></span>
                Modifier la demande
            </a>
            <?php /** @see \Formation\Controller\DemandeExterneController::ajouterDevisAction() */ ?>
                <a href="<?php echo $this->url('formation/demande-externe/ajouter-devis', ['demande-externe' => $demande->getId()], [], true); ?>"
                   class="btn btn-primary ajax-modal" data-event="modification">
                    <span class="icon icon-televerser"></span>Ajouter un devis</a><br/>
            <?php /** @see \Formation\Controller\DemandeExterneController::ajouterProgrammeAction() */ ?>
            <a href="<?php echo $this->url('formation/demande-externe/ajouter-programme', ['demande-externe' => $demande->getId()], [], true); ?>"
               class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-televerser"></span>Ajouter un programme</a><br/>
        <?php endif ?>
        <?php /** @see \Formation\Controller\DemandeExterneController::historiserAction() */?>
        <a  href="<?php echo $this->url('formation/demande-externe/historiser', ['demande-externe' => $demande->getId()], ['query' => ['retour' => $retour]], true); ?>"
            class="btn btn-danger <?php if (!$canHistoriserDemande) echo " disabled "; ?> ">
            <span class="icon icon-unchecked"></span>
            J'annule mon inscription
        </a>
        </div>
        <?php endif; ?>

        <!-- VALIDATION  ------------------------------------------------------------------------------------------------------->
        <div>
            <small>
            <?php $validationAgent = $demande->getValidationsByTypeCode(DemandeExterneValidations::FORMATION_DEMANDE_AGENT); ?>
            <?php if (!empty($validationAgent)) : ?>
                Validée par l'agent (<?php echo $validationAgent[0]->getHistoCreateur()->getDisplayName(); ?>) le <?php echo $validationAgent[0]->getHistoCreation()->format('d/m/Y'); ?>.
                <br/>
            <?php endif;?>
            <?php $validationResponsable = $demande->getValidationsByTypeCode(DemandeExterneValidations::FORMATION_DEMANDE_RESPONSABLE); ?>
            <?php if (!empty($validationResponsable)) : ?>
                Validée par le responsable (<?php echo $validationResponsable[0]->getHistoCreateur()->getDisplayName(); ?>) le <?php echo $validationResponsable[0]->getHistoCreation()->format('d/m/Y'); ?>.
                <br/>
            <?php endif;?>
            <?php $validationDrh = $demande->getValidationsByTypeCode(DemandeExterneValidations::FORMATION_DEMANDE_DRH); ?>
            <?php if (!empty($validationDrh)) : ?>
                Validée par le bureau de formation (<?php echo $validationDrh[0]->getHistoCreateur()->getDisplayName(); ?>) le <?php echo $validationDrh[0]->getHistoCreation()->format('d/m/Y'); ?>.
                <br/>
            <?php endif;?>
            </small>
        </div>
    </div>
</div>
