<?php

/**
 * @see \Formation\View\Helper\FormationInformationsViewHelper
 * @var Formation $formation
 * @var string $mode
 * @var array $options
 */

use Formation\Entity\Db\Formation;

?>

<?php if ($mode === 'liste') : ?>
    <dl class="row">
        <dt class="col-md-3"> Libellé </dt>
        <dd class="col-md-9"> <?php echo $formation->getLibelle(); ?> </dd>
        <?php if ($formation->getGroupe() !== null) : ?>
            <dt class="col-md-3"> Groupe </dt>
            <dd class="col-md-9"> <?php echo $formation->getGroupe()->getLibelle(); ?> </dd>
        <?php endif; ?>
        <?php if ($formation->getLien() !== null AND trim ($formation->getLien()) !== "") : ?>
            <dt class="col-md-3"> Lien </dt>
            <dd class="col-md-9"> <a href="<?php echo $formation->getLien(); ?>" title="Lien vers la documentation associée à la formation" data-bs-toggle="tooltip" data-bs-html="true">
                    <?php echo $formation->getLien(); ?></a> </dd>
        <?php endif; ?>
        <?php if ($formation->getDescription() !== null) : ?>
            <dt class="col-md-3"> Description </dt>
            <dd class="col-md-9"> <?php echo $formation->getDescription(); ?> </dd>
        <?php endif; ?>
    </dl>
<?php endif; ?>
