<?php

/**
 * @see \Formation\View\Helper\FormationInformationsViewHelper
 * @var Formation $formation
 * @var string $mode
 * @var array $options
 */

use Formation\Entity\Db\Formation;

?>

<?php if ($mode === 'liste') : ?>
    <dl class="row">
        <dt class="col-md-3"> Libellé </dt>
        <dd class="col-md-9"> <?php echo $formation->getLibelle(); ?> </dd>
        <?php if ($formation->getGroupe() !== null) : ?>
            <dt class="col-md-3"> Groupe </dt>
            <dd class="col-md-9"> <?php echo $formation->getGroupe()->getLibelle(); ?> </dd>
        <?php endif; ?>
        <?php if ($formation->getLien() !== null AND trim ($formation->getLien()) !== "") : ?>
            <dt class="col-md-3"> Lien </dt>
            <dd class="col-md-9"> <a href="<?php echo $formation->getLien(); ?>" title="Lien vers la documentation associée à la formation" data-bs-toggle="tooltip" data-bs-html="true">
                    <?php echo $formation->getLien(); ?></a> </dd>
        <?php endif; ?>
        <?php if ($formation->getDescription() !== null) : ?>
            <dt class="col-md-3"> Description </dt>
            <dd class="col-md-9"> <?php echo $formation->getDescription(); ?> </dd>
        <?php endif; ?>

        <?php if ($formation->getType() !== null AND trim($formation->getType() !== '')) : ?>
            <dt class="col-md-3"> Type/Modalité </dt>
            <dd class="col-md-9"> <?php echo Formation::TYPES[$formation->getType()]; ?> </dd>
        <?php endif; ?>
        <?php if ($formation->getObjectifs() !== null AND trim($formation->getObjectifs() !== '')) : ?>
            <dt class="col-md-3"> Objectifs </dt>
            <dd class="col-md-9"> <?php echo $formation->getObjectifs(); ?> </dd>
        <?php endif; ?>
        <?php if ($formation->getProgramme() !== null AND trim($formation->getProgramme() !== '')) : ?>
            <dt class="col-md-3"> Programme </dt>
            <dd class="col-md-9"> <?php echo $formation->getProgramme(); ?> </dd>
        <?php endif; ?>

        <dt class="col-md-3"> Affichage "plan" </dt>
        <dd class="col-md-9"> <?php echo ($formation->getAffichage())?"Oui":"Non"; ?> </dd>
        <?php if ($formation->getRattachement() !== null AND trim($formation->getRattachement() !== '')) : ?>
            <dt class="col-md-3"> Rattachement </dt>
            <dd class="col-md-9"> <?php echo $formation->getRattachement(); ?> </dd>
        <?php endif; ?>
    </dl>
<?php endif; ?>
