<?php

/**
 * @see \Formation\View\Helper\SessionInformationsViewHelper
 * @var Session $session
 * @var string $mode
 * @var array $options
 */

use Application\Entity\Db\Interfaces\HasSourceInterface;
use Formation\Entity\Db\Session;
use Formation\Provider\Privilege\DemandeexternePrivileges;


$gestionnaires = $session->getGestionnaires();

$canAfficherDemande = $this->isAllowed(DemandeexternePrivileges::getResourceId(DemandeexternePrivileges::DEMANDEEXTERNE_AFFICHER));

?>

<?php if ($mode === 'liste') : ?>
    <dl class="row">
        <dt class="col-md-3"> État</dt>
        <dd class="col-md-9">  <?php echo ($session->getEtatActif()) ? $this->etattype($session->getEtatActif()->getType(), ['display-categorie' => false]) . " " . $session->getEtatActif()->getType()->getLibelle() : "N.C."; ?> </dd>
        <?php if ($session->getComplement() !== null) : ?>
            <dt class="col-md-3"> Compléments</dt>
            <dd class="col-md-9"> <?php echo $session->getComplement(); ?></dd>
        <?php endif; ?>
        <dt class="col-md-3"> Taille liste principale</dt>
        <dd class="col-md-9"> <?php echo $session->getNbPlacePrincipale(); ?> </dd>
        <dt class="col-md-3"> Taille liste complémentaire</dt>
        <dd class="col-md-9"> <?php echo $session->getNbPlaceComplementaire(); ?> </dd>
        <dt class="col-md-3"> Date de clôture des inscriptions</dt>
        <dd class="col-md-9">
            <?php if ($session->getDateClotureInscription() != null) : ?>
                <?php echo $session->getDateClotureInscription()->format('d/m/Y'); ?>
                <?php if ($session->getDateClotureInscription() > $session->getDebut(true)) : ?>
                    <span class="text-danger">
                        <span class="icon icon-attention" title="La date de clôture précède la première séance ou le premier volume"></span>
                    </span>
                <?php endif; ?>
            <?php else: ?>
                <span class="text text-warning">
                    <span class="icon icon-attention"></span>
                    Aucun date de cloture fournie
                </span>
            <?php endif; ?>
        </dd>
        <dt class="col-md-3"> Lieu</dt>
        <dd class="col-md-9"> <?php echo ($session->getLieu()) ?: "Non communiqué"; ?> </dd>
        <?php if ($session->getType() !== null) : ?>
            <dt class="col-md-3"> Type</dt>
            <dd class="col-md-9"> <?php echo $session->getType(); ?> </dd>
        <?php endif; ?>
        <dt class="col-md-3"> Auto-inscription</dt>
        <dd class="col-md-9">
            <?php if ($session->isAutoInscription()) : ?>
                Oui (les agents peuvent s'inscrire eux-même)
            <?php else : ?>
                Non (les agents doivent notifier les gestionnaires de formation)
            <?php endif; ?>
        </dd>
        <dt class="col-md-3">
            Gestionnaire·s associé·es
        </dt>
        <dd class="col-md-9">
            <?php if (empty($gestionnaires)) : ?>
                Aucun·e gestionnaire
            <?php else: ?>
                <ul>
                    <?php foreach ($gestionnaires as $gestionnaire) : ?>
                        <li> <?php echo $gestionnaire->getDisplayName(); ?> </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </dd>
        <?php if ($session->getCoutHt() !== null) : ?>
            <dt class="col-md-3"> Coût HT</dt>
            <dd class="col-md-9"> <?php echo $session->getCoutHt(); ?>€</dd>
        <?php endif; ?>
        <?php if ($session->getCoutTtc() !== null) : ?>
            <dt class="col-md-3"> Coût TTC</dt>
            <dd class="col-md-9"> <?php echo $session->getCoutTtc(); ?>€</dd>
        <?php endif; ?>
        <?php if ($session->getCoutVacation() !== null) : ?>
            <dt class="col-md-3"> Coût Vacation</dt>
            <dd class="col-md-9"> <?php echo $session->getCoutVacation(); ?>€</dd>
        <?php endif; ?>
        <?php if ($session->getRecetteTtc() !== null) : ?>
            <dt class="col-md-3"> Recette TTC</dt>
            <dd class="col-md-9"> <?php echo $session->getRecetteTtc(); ?>€</dd>
        <?php endif; ?>
    </dl>
<?php endif; ?>

<?php if ($mode === 'bloc') : ?>
    <?php echo $this->etatinstance($session->getEtatActif(), ['display-categorie' => false]); ?>
    <strong><?php echo $session->getFormation()->getLibelle(); ?></strong>
    <br/>
    Session <?php echo $session->getId(); ?> du <?php echo $session->getDebut(); ?> au <?php echo $session->getFin(); ?>
    <br/>
    <?php if ($session->getSource() !== HasSourceInterface::SOURCE_LAGAF) : ?>
        <?php echo $session->getType(); ?> - <?php echo $session->getDuree(); ?> -
    <?php endif; ?>
    Liste principale
    <?php if ($session->getSource() !== HasSourceInterface::SOURCE_LAGAF) : ?>
        <?php echo count($session->getListePrincipale()); ?>/<?php echo $session->getNbPlacePrincipale(); ?>
    <?php endif; ?>
    <!--    --->
    <!--    Liste complémentaire --><?php //echo count($session->getListeComplementaire());  ?><!--/--><?php //echo $session->getNbPlaceComplementaire(); ?>
    <br>
    Date de clôture des inscriptions :
    <?php if ($session->getDateClotureInscription() !== null) : ?>
        <?php echo $session->getDateClotureInscription()->format('d/m/Y'); ?>
    <?php else : ?>
        <em>Aucune date connue</em>
    <?php endif; ?>
<?php endif; ?>


<?php if (!empty($session->getDemandesExternes())) : ?>
    <dt> Demandes de formations externes associées</dt>
    <dd>
        <ul>
            <?php foreach ($session->getDemandesExternes() as $demandesExterne) : ?>
                <li>
                    Demande #<?php echo $demandesExterne->getId(); ?>
                    (<?php echo $demandesExterne->getAgent()->getDenomination(true); ?>)
                    <?php if ($canAfficherDemande) : ?>
                        <?php /** @see \Formation\Controller\DemandeExterneController::afficherAction() */ ?>
                        <a href="<?php echo $this->url('formation/demande-externe/afficher', ['demande-externe' => $demandesExterne->getId()], [], true); ?>"
                           class="ajax-modal"
                        >
                        <span class="action">
                            <span class="icon icon-voir"></span>
                            Afficher
                        </span>
                        </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </dd>
<?php endif; ?>
