<?php

use FicheMetier\Entity\Db\FicheMetier;

/**
 * @see \FicheMetier\Controller\FicheMetierController::afficherAction()
 * @var FicheMetier $fiche
 * @var array $competences
 * @var array $applications
 * @var array $missions
 */

$mode = 'affichage';

$libelle = ($fiche->getMetier())?$fiche->getMetier()->getLibelle():"Aucun libellé";
$this->headTitle('Affichage de la fiche métier #' . $fiche->getId(). " : " . $libelle);

echo $this->partial('partial/entete', ['fichemetier' => $fiche, 'mode' => $mode], [], true);
echo $this->partial('partial/missions-principales',   ['fichemetier' => $fiche, 'missionsprincipales' => $missions, 'mode' => $mode ],  [], true);
echo $this->partial('partial/competences',            ['fichemetier' => $fiche, 'competences' => $competences, 'mode' => $mode ],       [], true);
echo $this->partial('partial/applications',           ['fichemetier' => $fiche, 'applications' => $applications, 'mode' => $mode ],     [], true);

