<?php

use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Provider\Parametre\FicheMetierParametres;
use UnicaenParametre\Entity\Db\Parametre;

/**
 * @see \FicheMetier\Controller\FicheMetierController::afficherAction()
 * @var FicheMetier $fiche
 * @var array $competences
 * @var array $competencesSpecifiques
 * @var array $applications
 * @var array $missions
 * @var array $tendancesTypes
 * @var array $tendancesElements
 * @var array $thematiquestypes
 * @var array $thematiqueselements
 * @var Parametre[] $parametres
 *
 * @var string $mode ('affichage', 'edition-fiche-metier')
 */

$libelle = ($fiche->getMetier())?$fiche->getMetier()->getLibelle():"Aucun libellé";
$titre = " de la fiche métier #" . $fiche->getId(). " : " . $libelle;
if ($mode === 'affichage') $titre = "Affichage".$titre;
if ($mode === 'edition-fiche-metier') $titre = "Modification".$titre;



$this->headTitle($titre);
?>

<div class="row">
    <div class="col-md-8">
        <?php if (!isset($parametres[FicheMetierParametres::DISPLAY_TITRE]) || $parametres[FicheMetierParametres::DISPLAY_TITRE]->getValeur() !== "false") : ?>
            <?php echo $this->partial('partial/titre',   ['fichemetier' => $fiche, 'titre' => $titre, 'mode' => $mode ],  [], true); ?>
        <?php endif; ?>
    </div>
    <div class="col-md-4">
        <?php if (!isset($parametres[FicheMetierParametres::DISPLAY_RESUME]) || $parametres[FicheMetierParametres::DISPLAY_RESUME]->getValeur() !== "false") : ?>
            <?php echo $this->partial('partial/resume',   ['fichemetier' => $fiche, 'mode' => $mode, 'parametres' => $parametres ],  [], true); ?>
        <?php endif; ?>
    </div>
</div>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_RAISON]) || $parametres[FicheMetierParametres::DISPLAY_RAISON]->getValeur() !== "false") : ?>
    <?php echo $this->partial('partial/raison',   ['fichemetier' => $fiche, 'mode' => $mode ],  [], true); ?>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_MISSION]) || $parametres[FicheMetierParametres::DISPLAY_MISSION]->getValeur() !== "false") : ?>
   <?php echo $this->partial('partial/missions-principales',   ['fichemetier' => $fiche, 'missionsprincipales' => $missions, 'mode' => $mode ],  [], true); ?>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_COMPETENCE]) || $parametres[FicheMetierParametres::DISPLAY_COMPETENCE]->getValeur() !== "false") : ?>
    <?php echo $this->partial('partial/competences',            ['fichemetier' => $fiche, 'competences' => $competences, 'mode' => $mode ],       [], true); ?>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_COMPETENCE_SPECIFIQUE]) || $parametres[FicheMetierParametres::DISPLAY_COMPETENCE_SPECIFIQUE]->getValeur() !== "false") : ?>
    <?php echo $this->partial('partial/competences-specifiques',            ['fichemetier' => $fiche, 'competences' => $competencesSpecifiques, 'mode' => $mode ],       [], true); ?>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_APPLICAITON]) || $parametres[FicheMetierParametres::DISPLAY_APPLICAITON]->getValeur() !== "false") : ?>
    <div id="neue_applications">
    </div>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_CONTEXTE]) || $parametres[FicheMetierParametres::DISPLAY_CONTEXTE]->getValeur() !== "false") : ?>
    <?php echo $this->partial('partial/thematiques', ['fichemetier' => $fiche, 'thematiquesTypes' => $thematiquestypes, 'thematiquesElements' => $thematiqueselements, 'mode' => $mode], [], true); ?>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_TENDANCE]) || $parametres[FicheMetierParametres::DISPLAY_TENDANCE]->getValeur() !== "false") : ?>
    <?php echo $this->partial('partial/tendances', ['fichemetier' => $fiche, 'tendancesTypes' => $tendancesTypes, 'tendancesElements' => $tendancesElements, 'mode' => $mode], [], true); ?>
<?php endif; ?>

<script>
    function refreshApplications() {
        <?php /** @see \FicheMetier\Controller\FicheMetierController::refreshApplicationsAction() */ ?>
        let url = "<?php echo $this->url("fiche-metier/refresh-applications", ['fiche-metier' => $fiche->getId(), 'mode' => $mode ]); ?>";
        console.log("refreshing applications");
        $.ajax({
            type: "POST",
            url: url,
            beforeSend:
                function () {
                    //$("#neue_applications").html("<div class='card info'><div class='card-header'><h2>Applications </h2></div><div class='card-body'><span class='icon icon-hourglass'></span> Rafraîssement du bloc Applications</div>");
                    $("#neue_applications div.card-body").addClass('refreshing');
                },
            success:
                function (retour) {
                    $("#neue_applications").html(retour).removeClass('refreshing');
                }
        });
    }

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $("body").on("refresh-applications", function (event) {
            event.div.modal('hide');
            refreshApplications();
        });
        refreshApplications();
    });
</script>