<?php

use Application\Provider\Privilege\FicheMetierPrivileges;
use Element\Entity\Db\CompetenceType;
use FicheMetier\Entity\Db\ActiviteElement;
use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Provider\Parametre\FicheMetierParametres;
use UnicaenParametre\Entity\Db\Parametre;

/**
 * @see \FicheMetier\Controller\FicheMetierController::afficherAction()
 * @see \FicheMetier\Controller\FicheMetierController::modifierAction()
 * @var FicheMetier $fiche
 * @var CompetenceType[] $types
 * @var array $competences
 * @var array $competencesSpecifiques
 * @var array $applications
 * @var array $missions
 * @var array $dictionnaire
 * @var ActiviteElement[] $activites
 * @var array $tendancesTypes
 * @var array $tendancesElements
 * @var array $thematiquestypes
 * @var array $thematiqueselements
 * @var Parametre[] $parametres
 *
 * @var string $mode ('affichage', 'edition-fiche-metier')
 */

$libelle = $fiche->getLibelle();
$titre = " de la fiche métier #" . $fiche->getId(). " : " . $libelle;
if ($mode === 'affichage') $titre = "Affichage".$titre;
if ($mode === 'edition-fiche-metier') $titre = "Modification".$titre;

$this->headTitle($titre);

$canExporterFicheMetier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));
$canAfficher = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_AFFICHER));
$canModifier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_MODIFIER));

$actions = ['modifier' => false, 'supprimer' => false, 'valider' => false];
if ($mode === 'edition-fiche-metier') {
    $actions['modifier'] = true;
    $actions['supprimer'] = true;
}
?>

<div class="row">
    <div class="col-md-8">
        <?php if (!isset($parametres[FicheMetierParametres::DISPLAY_TITRE]) || $parametres[FicheMetierParametres::DISPLAY_TITRE]->getValeur() !== "false") : ?>
            <?php echo $this->partial('partial/titre',   ['fichemetier' => $fiche, 'titre' => $titre, 'mode' => $mode ],  [], true); ?>
        <?php endif; ?>
    </div>
    <div class="col-md-4">
        <?php if (!isset($parametres[FicheMetierParametres::DISPLAY_RESUME]) || $parametres[FicheMetierParametres::DISPLAY_RESUME]->getValeur() !== "false") : ?>
            <?php echo $this->partial('partial/resume',   ['fichemetier' => $fiche, 'mode' => $mode, 'parametres' => $parametres ],  [], true); ?>
        <?php endif; ?>
    </div>
</div>

<div class="row">
<div class="float-end">
    <?php if ($fiche->hasLink()) : ?>
        <div class="dropdown" style="display:inline-block">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Fiche de référence
            </button>
            <ul class="dropdown-menu">
                <?php if ($fiche->getLienWeb() !== null): ?>
                    <li><a class="dropdown-item" href="<?php echo $fiche->getLienWeb(); ?>">Version WEB</a></li>
                <?php endif; ?>
                <?php if ($fiche->getLienPdf() !== null): ?>
                    <li><a class="dropdown-item" href="<?php echo $fiche->getLienWeb(); ?>">Version PDF</a></li>
                <?php endif; ?>
            </ul>
        </div>
    <?php endif; ?>
    <?php if ($canExporterFicheMetier): ?>
        <?php /** @see \FicheMetier\Controller\FicheMetierController::exporterAction() */ ?>
        <a href="<?php echo $this->url('fiche-metier/exporter', ['fiche-metier' => $fiche->getId()], [], true); ?>"
           class="btn btn-secondary" target="_blank">
            <span class="icon icon-pdf"></span>
            Exporter la fiche métier
        </a>
    <?php endif; ?>
    <?php if ($canModifier AND $mode === "affichage"): ?>
        <?php /** @see \FicheMetier\Controller\FicheMetierController::modifierAction() */ ?>
        <a href="<?php echo $this->url('fiche-metier/modifier', ['fiche-metier' => $fiche->getId()], [], true); ?>"
           class="btn btn-primary">
            <span class="icon icon-editer"></span>
            Basculer en mode Édition
        </a>
    <?php endif; ?>
    <?php if ($canModifier AND $mode === "edition-fiche-metier"): ?>
        <?php /** @see \FicheMetier\Controller\FicheMetierController::afficherAction() */ ?>
        <a href="<?php echo $this->url('fiche-metier/afficher', ['fiche-metier' => $fiche->getId()], [], true); ?>"
           class="btn btn-primary">
            <span class="icon icon-voir"></span>
            Basculer en mode Visualisation
        </a>
    <?php endif; ?>
</div>
</div>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_RAISON]) || $parametres[FicheMetierParametres::DISPLAY_RAISON]->getValeur() !== "false") : ?>
    <div class="card">
        <div class="card-header bg-default">
            <div class="row">
                <div class="col-md-8">
                    <h3>Raison d'être du métier dans l'établissement</h3>
                </div>
                <div class="col-md-4">
                    <?php if ($canModifier AND $mode === 'edition-fiche-metier' ) : ?>
                        <div class="float-end">
                            <?php /** @see FicheMetierController::modifierRaisonAction() */ ?>
                            <a href="<?php echo $this->url('fiche-metier/modifier-raison', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                               class="btn btn-primary ajax-modal"  style="margin: 0 0.5rem;"
                               data-event="refresh-raison"
                            >
                                <span class="icon icon-editer"></span>
                                Modifier la raison
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="card-body" style="color:rgb(80,80,80);" id="raison_view">
            <?php echo $this->partial('partial/bloc-raison', ['fichemetier' => $fiche, 'mode' => $mode ]); ?>
        </div>
    </div>

<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_MISSION]) || $parametres[FicheMetierParametres::DISPLAY_MISSION]->getValeur() !== "false") : ?>
   <?php echo $this->partial('partial/missions-principales',   ['fichemetier' => $fiche, 'missionsprincipales' => $missions, 'mode' => $mode ],  [], true); ?>

    <div class="card info">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6"><h2> Missions principales </h2></div>
                <div class="col-md-6">
                    <div class="float-end">
                        <?php if ($mode === 'edition-fiche-metier' AND $canModifier) : ?>
                            <?php /** @see FicheMetierController::gererMissionsPrincipalesAction() */ ?>
                            <a class="btn btn-primary ajax-modal" style="margin: 0 0.5rem;"
                               data-event="refresh-missions"
                               href="<?php echo $this->url('fiche-metier/gerer-missions-principales', ['fiche-metier' => $fiche->getId()], [], true); ?>">
                                <span class="icon icon-listing"></span>
                                Gérer les missions
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body" style="color:rgb(80,80,80);" id="missions_view">
            <?php echo $this->partial('partial/bloc-mission', ['fichemetier' => $fiche, 'missions' => $missions, 'mode' => $mode ]); ?>
        </div>
    </div>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_ACTIVITE]) || $parametres[FicheMetierParametres::DISPLAY_ACTIVITE]->getValeur() !== "false") : ?>
<div class="card info">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6"><h2> Activités </h2></div>
            <div class="col-md-6">
                <div class="float-end">
                    <?php if ($mode === 'edition-fiche-metier' AND $canModifier) : ?>
                        <?php /** @see FicheMetierController::gererActivitesAction() */ ?>
                        <a class="btn btn-primary ajax-modal" style="margin: 0 0.5rem;"
                           data-event="refresh-activites"
                           href="<?php echo $this->url('fiche-metier/gerer-activites', ['fiche-metier' => $fiche->getId()], [], true); ?>">
                            <span class="icon icon-listing"></span>
                            Gérer les activités
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body" style="color:rgb(80,80,80);" id="activites_view">
        <?php echo $this->partial('partial/bloc-activite', ['fichemetier' => $fiche, 'activites' => $activites, 'mode' => $mode ]); ?>
    </div>
</div>
<?php endif; ?>

<!-- COMPETENCES STANDARDS -------------------------------------------------------------------------------------------->
<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_COMPETENCE]) || $parametres[FicheMetierParametres::DISPLAY_COMPETENCE]->getValeur() !== "false") : ?>
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-5">
                    <h2> Compétences </h2>
                </div>
                <div class="col-md-7">
                    <div class="float-end">
                        <?php /** @see \FicheMetier\Controller\GraphiqueController::graphiqueCompetencesAction() */ ?>
                        <a href="<?php echo $this->url('graphique/competences', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                           class="btn btn-secondary ajax-modal" style="margin: 0 0.5rem;"
                        >
                            <span class="icon icon-diagramme"></span>
                            Afficher les compétences
                        </a>

                        <?php if ($mode === 'edition-fiche-metier'): ?>
                            <?php /** @see \FicheMetier\Controller\FicheMetierController::gererCompetencesAction() */ ?>
                            <a href="<?php echo $this->url('fiche-metier/gerer-competences', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                               class="btn btn-primary ajax-modal" data-event="refresh-competences">
                                <span class="icon icon-lister"></span>
                                Gérer les compétences
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <?php foreach($types as $type): ?>
                <?php if ($type->getCode() !== CompetenceType::CODE_SPECIFIQUE): ?>
                    <div id="competence_<?php echo str_replace(" ","_",$type->getCode()); ?>">
                        <?php
                            $liste = $competences[$type->getCode()];
                            echo $this->partial('partial/bloc-competences', ['fichemetier' => $fiche, 'type' => $type, 'competences' => $liste, 'mode' => $mode ]);
                        ?>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>


<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_COMPETENCE_SPECIFIQUE]) || $parametres[FicheMetierParametres::DISPLAY_COMPETENCE_SPECIFIQUE]->getValeur() !== "false") : ?>
    <div class="card info">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h2>
                        <span class="icon competence"></span>
                        Compétences spécifiques
                    </h2>
                </div>
                <div class="col-md-5">
                    <div class="float-end">
                        <?php if ($actions['modifier'] === true) : ?>
                            <?php /** @see \FicheMetier\Controller\FicheMetierController::gererCompetencesSpecifiquesAction() */ ?>
                            <a href="<?php echo $this->url('fiche-metier/gerer-competences-specifiques', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                               class="btn btn-primary ajax-modal" style="margin: 0 0.5rem;"
                               data-event="refresh-competences-specifiques"
                               data-competence-type="<?php echo CompetenceType::CODE_SPECIFIQUE; ?>"
                            >
                                <span class="icon icon-lister"></span>
                                Gérer les compétences
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body" style="color:rgb(80,80,80);" id="competence_SPEC">
            <?php echo $this->partial('partial/bloc-competences-specifiques', ['fichemetier' => $fiche, 'type' => $types[CompetenceType::CODE_SPECIFIQUE], 'competences' => $competencesSpecifiques, 'mode' => $mode ]); ?>
        </div>
    </div>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_APPLICATION]) || $parametres[FicheMetierParametres::DISPLAY_APPLICATION]->getValeur() !== "false") : ?>
    <div class="card info">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h2>
                        <span class="icon application"></span>
                        Applications
                    </h2>
                </div>
                <div class="col-md-5">
                    <div class="float-end">
                        <?php /** @see \FicheMetier\Controller\GraphiqueController::graphiqueApplicationsAction() */ ?>
                        <a href="<?php echo $this->url('graphique/applications', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                           class="btn btn-secondary ajax-modal" style="margin: 0 0.5rem;"
                        >
                            <span class="icon icon-diagramme"></span>
                            Afficher les applications
                        </a>

                        <?php if ($mode === 'edition-fiche-metier' AND $canModifier) : ?>
                            <?php /** @see \FicheMetier\Controller\FicheMetierController::gererApplicationsAction() */ ?>
                            <a href="<?php echo $this->url('fiche-metier/gerer-applications', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                               class="btn btn-primary ajax-modal" data-event="refresh-applications">
                                <span class="icon icon-lister"></span>
                                Gérer les applications
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body" style="color:rgb(80,80,80);" id="applications_view">
            <?php echo $this->partial('partial/bloc-applications', ['fichemetier' => $fiche, 'applications' => $applications, 'mode' => $mode ]); ?>
        </div>
    </div>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_CONTEXTE]) || $parametres[FicheMetierParametres::DISPLAY_CONTEXTE]->getValeur() !== "false") : ?>
    <?php echo $this->partial('partial/thematiques', ['fichemetier' => $fiche, 'thematiquesTypes' => $thematiquestypes, 'thematiquesElements' => $thematiqueselements, 'mode' => $mode], [], true); ?>
<?php endif; ?>

<?php if (!isset($parametres[FicheMetierParametres::DISPLAY_TENDANCE]) || $parametres[FicheMetierParametres::DISPLAY_TENDANCE]->getValeur() !== "false") : ?>
    <?php echo $this->partial('partial/tendances', ['fichemetier' => $fiche, 'tendancesTypes' => $tendancesTypes, 'tendancesElements' => $tendancesElements, 'mode' => $mode], [], true); ?>
<?php endif; ?>



<script>
    function refreshCompetences(type) {
        <?php /** @see \FicheMetier\Controller\FicheMetierController::refreshCompetencesAction() */ ?>
        let url = "<?php echo $this->url("fiche-metier/refresh-competences", ['fiche-metier' => $fiche->getId(), 'mode' => $mode ]); ?>";
        if (type !== undefined) url += "/"+type;
        console.log("refreshing competences " + type);
        $.ajax({
            type: "POST",
            url: url,
            beforeSend:
                function () {
                    $("div#competence_" + type).addClass('refreshing');
                },
            success:
                function (retour) {
                    $("div#competence_" + type)
                        .html(retour)
                        .removeClass('refreshing');
                }
        });
    }

    $(function() {
        let types = [ <?php echo implode(", ", array_map(function (CompetenceType $type) { return "'".str_replace(" ","_",$type->getCode())."'"; }, $types)); ?>];

        $("body")
        .on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        }).on("refresh-raison", function (event) {
                event.div.modal('hide');
                refreshRaison();
        }).on("refresh-activites", function (event) {
            event.div.modal('hide');
            refreshActivites();
        }).on("refresh-missions", function (event) {
            event.div.modal('hide');
            refreshMissions();
        }).on("refresh-applications", function (event) {
            event.div.modal('hide');
            refreshApplications();
        }).on("refresh-competences", function (event) {

        }).on("refresh-competences-specifiques", function (event) {
            event.div.modal('hide');
            let type = event.a.data('competence-type');
            if (type !== undefined) {
                refreshCompetences(type);
            } else {
                types.forEach(function (type) {
                    refreshCompetences(type);
                });
            }
        });

        // types.forEach(function (type) {
        //     refreshCompetences(type);
        // });
    });
</script>
