<?php

use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\AgentPrivileges;
use EmploiRepere\Entity\Db\EmploiRepere;
use FicheMetier\Entity\Db\FicheMetier;
use FichePoste\Provider\Privilege\FichePostePrivileges;

/**
 * @see \FicheMetier\Controller\FicheMetierController::listerAgentsAction()
 * @var FicheMetier $fichemetier
 * @var FichePoste[] $fichespostes
 * @var array[] $agentsTableaux
 */

?>

<h2> Liste des agents depuis les fiches poste </h2>

<table class="table table-condensed table-hover" id="listing">
    <thead>
    <tr>
        <th> Agent </th>
        <th colspan="2"> Fiche de poste</th>
        <th> Affectation </th>
        <th> Quotité </th>
        <th data-type="num"> État </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($fichespostes as $ficheposte) : ?>
        <tr>
            <td data-column-id="agent">
                <?php $agent = $ficheposte->getAgent(); ?>
                <?php if ($this->isAllowed($agent, AgentPrivileges::AGENT_AFFICHER)) : ?>
                    <?php /** @see \Application\Controller\AgentController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent?->getId()], [], true); ?>" target="_blank">
                        <?php echo $agent->getDenomination(); ?>
                    </a>
                <?php else : ?>
                    <?php echo $agent->getDenomination(); ?>
                <?php endif; ?>
            </td>
            <td data-column-id="Fiche de poste">
                <?php if ($this->isAllowed($ficheposte, FichePostePrivileges::FICHEPOSTE_AFFICHER)) : ?>
                    <?php /** @see \Application\Controller\FichePosteController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('fiche-poste/afficher', ['fiche-poste' => $ficheposte?->getId()], [], true); ?>" target="_blank">
                        Fiche #<?php echo $ficheposte->getId(); ?>
                    </a>
                <?php else : ?>
                    <?php echo $ficheposte->getId(); ?>
                <?php endif; ?>
            </td>
            <td data-column-id="Fiche de poste">
                <?php echo $ficheposte->getLibelle()??$ficheposte->getLibelleMetierPrincipal(); ?>
            </td>
            <td>
                <?php $affectations = $agent->getAffectationsActifs(); ?>
                <?php foreach ($affectations as $affectation) : ?>
                    <?php echo $affectation->getStructure()->getLibelleCourt(); ?>
                    <?php echo $affectation->getDateDebut()?$affectation->getDateDebut()->format("d/m/Y"):"---"; ?>
                    &rightarrow;
                    <?php echo $affectation->getDateFin()?$affectation->getDateFin()->format("d/m/Y"):"---"; ?>
                <br>
                <?php endforeach; ?>
            </td>
            <td>
                <?php echo $ficheposte->getQuotiteComposition($fichemetier); ?> %
            </td>
            <?php $etat = $ficheposte->getEtatActif(); ?>
            <td data-order="<?php echo $etat->getType()?->getOrdre(); ?>"> <?php echo $this->etatinstance($etat); ?></td>

        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php if (!empty($agentsTableaux)) : ?>

    <h2> Liste des agents depuis les emplois repères </h2>

    <table class="table table-condensed" id="emplois">
        <thead>
        <tr>
            <th> Agent </th>
            <th> Numéro de poste </th>
            <th> Libellé du poste</th>
            <th> Code Fonction </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($agentsTableaux as $item) : ?>
            <tr>
                <td>
                    <?php $agent = $item['agent']??null; ?>
                    <?php if ($agent) : ?>
                        <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>" target="_blank">
                            <?php echo $item['agent']->getDenomination(); ?>
                        </a>
                    <?php endif; ?>
                </td>
                <td><?php echo $item['numero']??"Non précisé"; ?> </td>
                <td><?php echo $item['intitulé']??"Non précisé"; ?> </td>
                <td><code><?php echo $item['code-fonction']->computeCode(); ?></code></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<script>
    $(function() {
        $("#listing").DataTable({
            info: true,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
        });
        $("#emplois").DataTable({
            info: true,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
        });
    });
</script>
