<?php

use FicheMetier\Form\FicheMetierIdentification\FicheMetierIdentificationForm;

/**
 * @see \FicheMetier\Controller\FicheMetierController::modifierIdentificationAction()
 * @var FicheMetierIdentificationForm $form
 */

?>

<?php echo $this->form()->openTag($form); ?>


<?php echo $this->formControlGroup($form->get('libelle')); ?>
<div class="row">
    <div class="col-md-6"><?php echo $this->formControlGroup($form->get('referentiel')); ?></div>
    <div class="col-md-6"><?php echo $this->formControlGroup($form->get('identifiant')); ?></div>
</div>

<?php echo $this->formControlGroup($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>


<script>
    $(document).ready(function () {
        $('select:not(.select2)').selectpicker();
        $('.select2').select2();
    });
</script>