<?php

namespace FichePoste\Provider\Template;

class MailTemplates {

    const FICHE_POSTE_VALIDATION_RESPONSABLE = 'FICHE_POSTE_VALIDATION_RESPONSABLE';
    const FICHE_POSTE_VALIDATION_AGENT       = 'FICHE_POSTE_VALIDATION_AGENT';
    const FICHE_POSTE_VALIDATION_DRH         = 'FICHE_POSTE_VALIDATION_DRH';
}