<?php

use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @see \Formation\Controller\FormationInstanceController::ajouterAvecFormulaireAction()
 */

?>

<form method="post" action="<?php echo $this->url('formation-instance/ajouter-avec-formulaire', [], [], true); ?>">
    <label for="formation">Formation associée à la nouvelle session : </label>
    <?php
    /** @see  \Formation\Controller\FormationController::rechercherFormationAction() */
    $structureF = new SearchAndSelect('formation');
    $structureF
        ->setAutocompleteSource($this->url('formation/rechercher-formation'))
        ->setSelectionRequired()
        ->setAttributes([
            'id' => 'formation',
            'placeholder' => "Sélectionner une formation",
        ]);
    ?>
    <?php echo $this->formControlGroup($structureF); ?>
    <input type="submit" value="Créer nouvelle session" class="btn btn-primary action">
</form>