<?php

use Formation\Entity\Db\FormationInstance;
use UnicaenEtat\Entity\Db\Etat;

/**
 * @see \Formation\Controller\FormationInstanceController::changerEtatAction()
 * @var FormationInstance $instance
 * @var Etat[] $etats
 */

?>

<div class="alert alert-info">
    La session de formation <strong><?php echo $instance->getFormation()->getLibelle(); ?></strong>
    (<?php echo $instance->getPeriode(); ?>) est actuellement à l'état <strong><?php echo $instance->getEtat()->getLibelle(); ?></strong>
    <?php echo $this->etatbadge($instance->getEtat()); ?>.
</div>

<form method="POST" action="<?php echo  $this->url('formation-instance/changer-etat', ['formation-instance' => $instance->getId()], [], true); ?>">
    <label for="etat">État : </label>
    <select id="etat" name="etat" data-live-search="true">
        <?php foreach ($etats as $etat) : ?>
            <option
                value="<?php echo $etat->getId(); ?>"
                data-content='<?php  echo $this->etatbadge($etat); ?> <?php echo str_replace("'", "", $etat->getLibelle()); ?>'
            >
                <?php echo $etat->getLibelle(); ?>
            </option>
        <?php endforeach; ?>
    </select>

    <br/>

    <button class="btn btn-primary">
        Valider
    </button>
</form>


<script>
    $('select').selectpicker();
</script>

