<?php

/**
 * @var FormationInstance[] $instances
 */

use Formation\Entity\Db\FormationInstance;
use Formation\Provider\Privilege\FormationPrivileges;

usort($instances, function (FormationInstance $a, FormationInstance $b) { return $a->getDebut() <=> $b->getDebut();});

$canVoir = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AFFICHER));
?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Sessions en cours
        </h1>
    </div>
    <div class="pull-right">
        <a href="<?php echo $this->url('formation-instance/ajouter-avec-formulaire', [], [], true); ?>"
           class="btn btn-primary action ajax-modal" data-event="modification"
           >
            <span class="icon icon-ajouter">
                Ouvrir une nouvelle session
            </span>
        </a>
    </div>
</div>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<?php echo $this->formationInstanceArray($instances); ?>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
