<?php

use Formation\Entity\Db\FormationInstanceInscrit;
use Formation\Entity\Db\Seance;
use Formation\Provider\Privilege\FormationPrivileges;

/**
 * @see \Application\Controller\FormationInstanceController::renseignerQuestionnaireAction()
 * @var FormationInstanceInscrit $inscrit
 */

$instanceLibelle = $inscrit->getInstance()->getInstanceCode() . " ".$inscrit->getInstance()->getFormation()->getLibelle();
$this->headTitle("Renseignement du formulaire de retour de formation : " . $instanceLibelle);

$agent = $inscrit->getAgent();
$instancef = $inscrit->getInstance();

$canVoir        = $this->isAllowed($inscrit, FormationPrivileges::FORMATION_QUESTIONNAIRE_VISUALISER);
$canRenseigner  = $this->isAllowed($inscrit, FormationPrivileges::FORMATION_QUESTIONNAIRE_MODIFIER);

?>

<h1 class="page-header">
    Formulaire de retour de formation <br/>
    <strong><?php echo $instanceLibelle; ?> </strong> pour l'agent <strong><?php echo $agent->getDenomination(); ?></strong>
</h1>

<div class="main">
    <?php if (!$canVoir AND !$canRenseigner) : ?>
        <div class="alert alert-danger">
            Vous n'êtes pas habilité&middot;e à visualiser le formulaire de retour.
        </div>
    <?php else : ?>
        <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3> Information sur l'agent </h3>
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt> Dénomination </dt>
                        <dd> <?php echo $agent->getDenomination(); ?></dd>
                        <dt> Affectation principale </dt>
                        <dd> <?php echo ($agent->getAffectationPrincipale())?$agent->getAffectationPrincipale()->getStructure()->getLibelleLong():"Non renseigné"; ?> </dd>
                        <dt> Présence </dt>
                        <dd>

                    <table class="presence">
                    <tr>
                    <?php /** @var Seance $journee */?>
                    <?php foreach ($instancef->getJournees() as $journee) : ?>
                        <td class="journee">
                            <?php if ($journee->getType() === Seance::TYPE_SEANCE) : ?>
                                <?php echo $journee->getJour()->format('d/m/Y'); ?> <br/>
                                <?php echo $journee->getDebut(); ?> &rightarrow; <?php echo $journee->getFin(); ?>
                            <?php endif; ?>
                            <?php if ($journee->getType() === Seance::TYPE_VOLUME) : ?>
                                <?php echo $journee->getVolume(); ?> heures
                            <?php endif; ?>
                        </td>
                    <?php endforeach; ?>
                    </tr>
                    <tr>
                    <?php foreach ($instancef->getJournees() as $journee) : ?>
                        <td class="reponse">
                            <?php if ($inscrit->wasPresent($journee)) : ?>
                                <span class="icon icon-checked" style="color:darkgreen;" ></span>
                            <?php else : ?>
                                <span class="icon icon-retirer" style="color:darkred;" ></span>
                            <?php endif; ?>
                        </td>
                    <?php endforeach;?>
                    </tr>
                    </table>

                        </dd>
                        <dt> Durée de présence </dt>
                        <dd> <?php echo $inscrit->getDureePresence(); ?> </dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3>Information sur la formation</h3>
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt> Action de formation </dt>
                        <dd> <?php echo $instanceLibelle; ?> </dd>
                        <dt> Période de formation</dt>
                        <dd> <?php echo $instancef->getDebut(); ?> &rightarrow; <?php echo $instancef->getFin(); ?></dd>
                        <dt> Durée de la formation</dt>
                        <dd> <?php echo $instancef->getDuree(); ?></dd>
                        <dt> Formateur(s)</dt>
                        <dd>
                            <ul>
                                <?php foreach ($instancef->getFormateurs() as $formateur) : ?>
                                <li><?php echo $formateur->getPrenom(); ?> <?php echo $formateur->getNom(); ?> (<?php echo $formateur->getAttachement()?:"Non renseigné";?>)</li>
                                <?php endforeach; ?>
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?php
    $instance = $inscrit->getQuestionnaire();
    $formulaire = $instance->getFormulaire();
    $reponses = $instance->getReponses();

    /** nécessaire car l'aide de vue var utiliser l'id du champ comme référence dans le tableau ...  */
    $data = [];
    foreach ($reponses as $reponse) {
        $data[$reponse->getChamp()->getId()] = $reponse;
    }
    ?>

    <?php if ($canRenseigner) : ?>
        <?php
        /** @see \Autoform\View\Helper\InstanceAsFormulaireHelper */
        $retour = $this->url('formation-instance/renseigner-questionnaire', ['inscrit' => $inscrit->getId()], ['force_canonical' => false], true);
        $url = $this->url('autoform/formulaire/afficher-formulaire', ['formulaire' => $formulaire->getId(), 'instance' => $instance->getId()], ['query' => ['retour' => $retour], 'force_canonical' => false], true);

        echo $this->instanceAsFormulaire()->render($instance, $url, $data);
        ?>
    <?php else : ?>
        <?php echo $this->instanceAsText()->render($instance); ?>
    <?php endif; ?>
</div>

<style>
    table.presence {
        /*border : 1px solid black;*/
    }

    table.presence tr td {
        border : 1px solid black;
    }

    table.presence tr td.journee{
        writing-mode: vertical-rl;
        text-orientation: mixed;
        padding-top:.5rem;
        padding-bottom:1rem;
        background: #1b6d85;
        color:white;
        width: 5rem;
    }

    table.presence tr td.reponse {
        vertical-align: center;
        text-align: center;
        width: 5rem;
        height: 5rem;
    }
</style>