<?php

/**
 * @see \Formation\Controller\AxeController::afficherAction()
 *
 * @var string $title
 * @var Axe $axe
 */

use Formation\Entity\Db\Axe;

?>

<dl>
    <dt> Libellé </dt>
    <dd> <?php echo $axe->getLibelle(); ?> </dd>
    <dt> Dernière modification </dt>
    <dd>
        <?php echo $axe->getHistoModificateur()->getDisplayName(); ?>
        <br/>
        <?php echo $axe->getHistoModification()->format('d/m/Y à H:i:s'); ?>
    </dd>
<!--    <dt> Source </dt>-->
<!--    <dd>-->
<!--        --><?php //echo $groupe->getSource(); ?><!-- --->
<!--        --><?php //echo $groupe->getIdSource(); ?>
<!--    </dd>-->
    <dt>
        Liste des thèmes
        <span class="badge"> <?php echo count($axe->getGroupes()); ?></span>
    </dt>
    <dd>
        <ul>
            <?php foreach($axe->getGroupes() as $groupe) : ?>
                <li> <?php echo $groupe->getLibelle(); ?> </li>
            <?php endforeach; ?>
        </ul>
    </dd>
</dl>

