<?php

use Formation\Entity\Db\Axe;
use Formation\Provider\Privilege\AxePrivileges;

/**
 * @see \Formation\Controller\AxeController::indexAction()
 * @var Axe[] $axes
 * // * @var string $historise
 * // * @var string $source
 */

$canAfficher = $this->isAllowed(AxePrivileges::getResourceId(AxePrivileges::AXE_AFFICHER));
$canAjouter = $this->isAllowed(AxePrivileges::getResourceId(AxePrivileges::AXE_AJOUTER));
$canEditer = $this->isAllowed(AxePrivileges::getResourceId(AxePrivileges::AXE_MODIFIER));
$canHistoriser = $this->isAllowed(AxePrivileges::getResourceId(AxePrivileges::AXE_HISTORISER));
$canDetruire = $this->isAllowed(AxePrivileges::getResourceId(AxePrivileges::AXE_SUPPRIMER));

$this->headTitle("Axes de formation");
?>

<h1 class="page-header">
    Axes de formation
</h1>

<?php if ($canAjouter) : ?>
    <br/>
    <a
        <?php /** @see \Formation\Controller\AxeController::ajouterAction() */ ?>
            href="<?php echo $this->url('axe/ajouter', [], [], true); ?>"
            class="btn btn-primary ajax-modal"
            data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un axe
    </a>
<?php endif; ?>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<table class="datatable table table-condensed table-hover" id="axes">
    <thead>
    <tr>
        <th> Libellé</th>
        <th> Ordre</th>
        <th style="width: 10rem;"> #Thème</th>
        <th class="action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($axes as $axe) : ?>
        <tr id="<?php echo $axe->getId(); ?>" class="<?php if ($axe->estHistorise()) echo "historise"; ?>">

            <td> <!-- LIBELLE -->
                <?php echo $axe->getLibelle(); ?>
                <?php if ($axe->getDescription() !== null) : ?>
                    <span class="icon icon-info" title="<?php echo $axe->getDescription(); ?>"
                          data-bs-toggle="tooltip" data-bs-html="true">
                    </span>
                <?php endif; ?>
            </td>
            <td> <!-- ORDRE -->
                <?php echo $axe->getOrdre(); ?>
            </td>
            <td> <!-- NB THEME -->
                <?php echo count($axe->getGroupes()); ?>
            </td>
            <!-- SOURCE -->
<!--            <td> -->
<!--                <span class="badge source --><?php //echo $axe->getSource(); ?><!--" id="--><?php //echo $axe->getSource(); ?><!--">-->
<!--                    --><?php //echo $axe->getSource(); ?>
<!--                    --><?php //echo $axe->getIdSource(); ?>
<!--                </span>-->
<!--            </td>-->
            <td class="action"> <!-- ACTION -->
                <?php if ($canAfficher) : ?>
                    <a <?php /** @see \Formation\Controller\AxeController::afficherAction() */ ?>
                            href="<?php echo $this->url('axe/afficher', ['axe' => $axe->getId()], [], true); ?>"
                            class="ajax-modal">
                        <span class="icon icon-voir" title="Afficher le axe"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <br>
                    <a
                        <?php /** @see \Formation\Controller\AxeController::modifierAction() */ ?>
                            href="<?php echo $this->url('axe/modifier', ['axe' => $axe->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon icon-editer" title="Modifier le axe"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($axe->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \Formation\Controller\AxeController::historiserAction() */ ?>
                                href="<?php echo $this->url('axe/historiser', ['axe' => $axe->getId()], [], true); ?>"
                        >
                            <span class="icon icon-historiser" title="Historiser le axe"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <a
                            <?php /** @see \Formation\Controller\AxeController::restaurerAction() */ ?>
                                href="<?php echo $this->url('axe/restaurer', ['axe' => $axe->getId()], [], true); ?>"
                        >
                            <span class="icon icon-restaurer" title="Restaurer le axe"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire and $axe->estHistorise()) : ?>
                    <br>
                    <a
                        <?php /** @see \Formation\Controller\AxeController::supprimerAction() */ ?>
                            href="<?php echo $this->url('axe/supprimer', ['axe' => $axe->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked text-danger" title="Supprimer définitivement le axe"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
