<?php

namespace EntretienProfessionnel\Provider\Template;

class MailTemplates {

    const CAMPAGNE_OUVERTURE_DAC    = 'CAMPAGNE_OUVERTURE_DAC';
    const CAMPAGNE_OUVERTURE_BIATSS = 'CAMPAGNE_OUVERTURE_BIATSS';

    const ENTRETIEN_CONVOCATION_ENVOI = 'ENTRETIEN_CONVOCATION_ENVOI';
    const ENTRETIEN_CONVOCATION_ACCEPTER = 'ENTRETIEN_CONVOCATION_ACCEPTER';
    const ENTRETIEN_ANNULATION = 'ENTRETIEN_ANNULATION';

    const ENTRETIEN_VALIDATION_1_RESPONSABLE = 'ENTRETIEN_VALIDATION_1-RESPONSABLE';
    const ENTRETIEN_VALIDATION_2_OBSERVATION = 'ENTRETIEN_VALIDATION_2-OBSERVATION';
    const ENTRETIEN_VALIDATION_2_PAS_D_OBSERVATION = 'ENTRETIEN_VALIDATION_2-PAS_D_OBSERVATION';
    const ENTRETIEN_VALIDATION_2_OBSERVATION_TRANSMISSION = 'ENTRETIEN_VALIDATION_2-OBSERVATION_TRANSMISSION';
    const ENTRETIEN_VALIDATION_3_HIERARCHIE = 'ENTRETIEN_VALIDATION_3-HIERARCHIE';
    const ENTRETIEN_VALIDATION_4_AGENT = 'ENTRETIEN_VALIDATION_4-AGENT';

    const RAPPEL_CAMPAGNE_AVANCEMENT_AUTORITE = 'NOTIFICATION_RAPPEL_CAMPAGNE_AUTORITE';
    const RAPPEL_CAMPAGNE_AVANCEMENT_SUPERIEUR = 'NOTIFICATION_RAPPEL_CAMPAGNE_SUPERIEUR';
    const RAPPEL_ENTRETIEN_AGENT = 'NOTIFICATION_RAPPEL_ENTRETIEN';

    const RAPPEL_ATTENTE_VALIDATION_SUPERIEUR = 'RAPPEL_ATTENTE_VALIDATION_SUPERIEUR';
    const RAPPEL_ATTENTE_VALIDATION_AUTORITE  = 'RAPPEL_ATTENTE_VALIDATION_AUTORITE';
    const RAPPEL_ATTENTE_VALIDATION_AGENT     = 'RAPPEL_ATTENTE_VALIDATION_AGENT';

    const MODIFICATIONS_APPORTEES_AUX_CRS = 'MODIFICATIONS_APPORTEES_AUX_CRS';

}