<?php

use FicheMetier\Entity\Db\FicheMetier;
use Metier\Entity\Db\Metier;

/**
 * @see \Metier\Controller\MetierController::afficherAction()
 * @var Metier $metier
 * @var FicheMetier[] $fiches
 */

?>

<dl class="row">
    <dt class="col-md-4">
        Libellé
    </dt>
    <dd class="col-md-8">
        <?php echo $metier->getLibelle(); ?>
    </dd>
    <dt class="col-md-4">
            Référence·s
    </dt>
    <dd class="col-md-8">
        <?php $references = $metier->getReferences(); ?>
        <?php if (empty($references)) : ?>
            <em> Aucune référence d'associée au métier </em>
        <?php else : ?>
            <ul>
            <?php foreach ($references as $reference) : ?>
                <li>
                    <?php echo $this->reference($reference); ?>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </dd>
    <dt class="col-md-4">
        Famille professionnelle
    </dt>
    <dd class="col-md-8">
        <?php $familles = $metier->getFamillesProfessionnelles(); ?>
        <?php if (empty($familles)) : ?>
            <em> Aucune famille professionnelle d'associée au métier </em>
        <?php else : ?>
            <ul>
                <?php foreach ($familles as $famille) : ?>
                    <li>
                        <?php echo $famille->getLibelle(); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </dd>
    <dt class="col-md-4">
        Catégorie
    </dt>
    <dd class="col-md-8">
        <?php $categorie = $metier->getCategorie(); ?>
        <?php if ($categorie === null) : ?>
            <em> Aucune catégorie d'associée au métier</em>
        <?php else : ?>
            <?php echo $categorie->getLibelle(); ?>
        <?php endif; ?>
    </dd>
    <dt class="col-md-4">
        Niveau
    </dt>
    <dd class="col-md-8">
        <?php $niveaux = $metier->getNiveaux(); ?>
        <?php if ($niveaux === null) : ?>
            <em> Enveloppe de niveau non définie </em>
        <?php else : ?>
            <?php echo $this->niveauEnveloppe($metier->getNiveaux(), ['verbose' => true]) ?>
        <?php endif; ?>
    </dd>

    <dt class="col-md-4">
        Fiche·s métier·s
    </dt>
    <dd class="col-md-8">
        <?php if (empty($fiches)) : ?>
            <em> Aucune fiche métier définie pour ce métier</em>
        <?php else : ?>
            <ul>
            <?php foreach ($fiches as $fiche) : ?>
                <li> #<?php echo $fiche->getId(); ?> - <?php echo $metier->getLibelle(); ?>
                    <?php if ($fiche->getEtatActif()) : ?>
                        <?php echo $this->etatinstance($fiche->getEtatActif()); ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </dd>
</dl>
