<?php

/**
 * @see \Metier\Controller\MetierController::indexAction()
 * @var FamilleProfessionnelle[] $familles
 * @var Metier[] $metiers
 *
 * @var string $famille
 * @var string $historise
 */

use Metier\Entity\Db\FamilleProfessionnelle;
use Metier\Entity\Db\Metier;
use Metier\Provider\Privilege\MetierPrivileges;
use Metier\Provider\Privilege\ReferentielmetierPrivileges;

$this->headTitle('Liste des métiers');

$canAfficher    = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_AFFICHER));
$canAjouter     = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_AJOUTER));
$canEditer      = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_MODIFIER));
$canHistoriser  = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_HISTORISER));
$canEffacer     = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_SUPPRIMER));
$canLister      = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_LISTER_AGENTS));


$canAction = ($canAfficher OR $canAjouter OR $canEditer OR $canHistoriser OR $canEffacer OR $canLister);

?>
<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Liste des métiers
        </h1>
    </div>
</div>


<?php if ($canAjouter) : ?>
    <a  <?php /** @see \Metier\Controller\MetierController::ajouterAction() */ ?>
            href="<?php echo $this->url('metier/ajouter', [], [], true);?>"
            class="btn btn-primary ajax-modal"
            data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un métier
    </a>
<?php endif;?>

<?php echo $this->partial('partial/filtre', ['familles' => $familles, 'famille' => $famille,'historise' => $historise]); ?>

<table id="metiers" class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th> Libelle </th>
        <th> Catégorie </th>
        <th> Familles professionnelles </th>
        <th> Références </th>
        <th> Niveaux </th>
        <?php if ($canAction) :?>
            <th style="min-width: 10rem;"> Action </th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach($metiers as $metier): ?>
        <tr <?php if ($metier->estHistorise()) echo ' class="historise" '; ?>>
            <td>
                <span title='<?php echo $metier->generateTooltip(); ?>'
                      data-bs-toggle='tooltip' data-bs-html='true'
                >
                    <?php echo $metier->getLibelle(); ?>
                    <br>
                    <?php echo $metier->printReference(); ?>
                </span>
            </td>
            <td id="categorie">
                <?php echo ($metier->getCategorie())?$metier->getCategorie()->getCode():""; ?>
            </td>
            <td>
                <?php $familles = $metier->getFamillesProfessionnelles(); ?>
                <?php if (empty($familles)) : ?>
                    <em>Aucune famille professionnelle de renseignée</em>
                <?php else : ?>
                    <ul>
                        <?php /** @var FamilleProfessionnelle $famille */ ?>
                        <?php foreach ($metier->getFamillesProfessionnelles() as $famille) : ?>
                            <li> <?php echo $famille->getLibelle(); ?> </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </td>
            <td class="action" id="references">
                <?php $references =  $metier->getReferences(); ?>
                <?php if (empty($references)) : ?>
                    Aucune
                <?php else: ?>
                <?php foreach ($references as $reference) : ?>
                    <?php echo $this->reference($reference); ?>
                    <?php if ($canEditer) : ?>
                    <br>
                    <a  <?php /** @see \Metier\Controller\ReferenceController::modifierAction() */ ?>
                            href="<?php echo $this->url('metier/reference/modifier', ['reference' => $reference->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                    <br>
                    <a  <?php /** @see \Metier\Controller\ReferenceController::supprimerAction() */ ?>
                            href="<?php echo $this->url('metier/reference/supprimer', ['reference' => $reference->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>
                        <?php endif; ?>
                        <br/>
                    <?php endforeach ?>
                    <?php endif; ?>

                    <?php if ($canEditer) : ?>
                        <br>
                        <a
                            <?php /** @see \Metier\Controller\ReferenceController::ajouterAction() */ ?>
                                href="<?php echo $this->url('metier/reference/ajouter', ['metier' => $metier->getId()], [], true); ?>"
                                class="ajax-modal action primary"
                                data-event="modification"
                        >
                            <span class="icon icon-ajouter"></span>
                            Ajouter
                        </a>
                    <?php endif; ?>
            </td>
            <td class="action" id="niveaux">
                <?php echo $this->niveauEnveloppe($metier->getNiveaux()) ?>
                <?php if ($canEditer) : ?>
                    <?php if ($metier->getNiveaux()) : ?>
                        <?php /**  @see \Metier\Controller\MetierController::modifierNiveauxAction() */ ?>
                        <a href="<?php echo $this->url('metier/modifier-niveaux', ['metier' => $metier->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-editer"></span>
                            Modifier
                        </a>
                    <?php else : ?>
                        <?php /**  @see \Metier\Controller\MetierController::modifierNiveauxAction() */ ?>
                        <br>
                        <a href="<?php echo $this->url('metier/modifier-niveaux', ['metier' => $metier->getId()], [], true); ?>"
                           class="ajax-modal action primary" data-event="modification"
                        >
                            <span class="icon icon-ajouter"></span>
                            Ajouter
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <?php if ($canAction) : ?>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Metier\Controller\MetierController::afficherAction() */ ?>
                            href="<?php echo $this->url('metier/afficher', ['metier' => $metier->getId()], [], true); ?>"
                            class="ajax-modal action secondary"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canLister) : ?>
                    <br/>
                    <a
                        <?php /** @see \Metier\Controller\MetierController::listerAgentsAction() */ ?>
                            href="<?php echo $this->url('metier/lister-agents', ['metier' => $metier->getId()], [], true); ?>"
                            class="ajax-modal action secondary"
                    >
                        <span class="icon icon-users"></span>
                        Lister les agents
                    </a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <br>
                    <a
                        <?php /** @see \Metier\Controller\MetierController::modifierAction() */ ?>
                            href="<?php echo $this->url('metier/modifier', ['metier' => $metier->getId()], [], true); ?>"
                            class="ajax-modal action primary"
                            data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($metier->estNonHistorise()) : ?>
                        <a  <?php /** @see \Metier\Controller\MetierController::historiserAction() */ ?>
                                href="<?php echo $this->url('metier/historiser', ['metier' => $metier->getId()], [], true); ?>"
                                class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <a  <?php /** @see \Application\Controller\MetierController::restaurerAction() */ ?>
                                href="<?php echo $this->url('metier/restaurer', ['metier' => $metier->getId()], [], true); ?>"
                                class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <br>
                    <a  <?php /** @see \Metier\Controller\MetierController::supprimerAction() */ ?>
                            href="<?php echo $this->url('metier/supprimer', ['metier' => $metier->getId()], [], true); ?>"
                            class="ajax-modal action danger" data-event="modification"
                    >
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<br/>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('table#metiers').dataTable({
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [5], orderable: false }
            ]
        });
    });
</script>
