<?php

/**
 * @see \Metier\Controller\MetierController::indexAction()
 * @var Domaine[] $domaines
 * @var Metier[] $metiers
 *
 * @var string $domaine
 * @var string $historise
 */

use Metier\Entity\Db\Domaine;
use Metier\Entity\Db\Metier;
use Metier\Provider\Privilege\MetierPrivileges;

$this->headTitle('Liste des métiers');

$canAfficher    = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_AFFICHER));
$canAjouter     = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_AJOUTER));
$canEditer      = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_MODIFIER));
$canHistoriser  = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_HISTORISER));
$canEffacer     = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_SUPPRIMER));

?>

<h1 class="page-header">
    Liste des métiers
</h1>

<?php echo $this->partial('partial/filtre', ['domaines' => $domaines, 'domaine' => $domaine, 'historise' => $historise]); ?>

<?php if ($canAjouter) : ?>
    <a  <?php /** @see \Metier\Controller\MetierController::ajouterAction() */ ?>
            href="<?php echo $this->url('metier/ajouter', [], [], true);?>"
            class="btn btn-primary action ajax-modal"
            data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un métier
    </a>
<?php endif;?>


<table id="metiers" class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th> Libelle </th>
        <th> Domaines </th>
        <th> Références </th>
        <th> Catégorie </th>
        <th> Niveaux </th>
        <th style="min-width: 10rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($metiers as $metier): ?>
        <tr <?php if ($metier->estHistorise()) echo ' class="historise" '; ?>>
            <td>
                <span title='<?php echo $metier->generateTooltip(); ?>'
                      data-toggle='tooltip' data-html='true'
                >
                    <?php echo $metier->getLibelle(); ?>
                </span>
            </td>
            <td>
                <ul>
                    <?php foreach ($metier->getDomaines() as $domaine) : ?>
                        <li>
                            <?php echo $domaine; ?>
                            <?php echo $this->typefonction($domaine); ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td class="action">
                <?php $references =  $metier->getReferences(); ?>
                <?php if (empty($references)) : ?>
                    Aucune
                <?php else: ?>
                <?php foreach ($references as $reference) : ?>
                    <?php echo $this->reference($reference); ?>
                    <?php if ($canEditer) : ?>
                    <br>
                    <a  <?php /** @see \Metier\Controller\ReferenceController::modifierAction() */ ?>
                            href="<?php echo $this->url('metier/reference/modifier', ['reference' => $reference->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                    <br>
                    <a  <?php /** @see \Metier\Controller\ReferenceController::supprimerAction() */ ?>
                            href="<?php echo $this->url('metier/reference/supprimer', ['reference' => $reference->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-retirer"></span>
                            Supprimer
                        </span>
                    </a>
                        <?php endif; ?>
                        <br/>
                    <?php endforeach ?>
                    <?php endif; ?>

                    <?php if ($canEditer) : ?>
                        <br>
                        <a
                            <?php /** @see \Metier\Controller\ReferenceController::ajouterAction() */ ?>
                                href="<?php echo $this->url('metier/reference/ajouter', ['metier' => $metier->getId()], [], true); ?>"
                                class="ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon icon-ajouter"></span>
                            Ajouter
                        </a>
                    <?php endif; ?>
            </td>
            <td>
                <?php echo ($metier->getCategorie())?$metier->getCategorie()->getCode():""; ?>
            </td>
            <td class="action">
                <?php echo $this->niveauEnveloppe($metier->getNiveaux()) ?>
                <?php if ($canEditer) : ?>
                    <?php if ($metier->getNiveaux()) : ?>
                        <?php /**  @see \Metier\Controller\MetierController::modifierNiveauxAction() */ ?>
                        <a href="<?php echo $this->url('metier/modifier-niveaux', ['metier' => $metier->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-editer"></span>
                            Modifier
                        </a>
                    <?php else : ?>
                        <?php /**  @see \Metier\Controller\MetierController::modifierNiveauxAction() */ ?>
                        <a href="<?php echo $this->url('metier/modifier-niveaux', ['metier' => $metier->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        ><br>
                            <span class="icon icon-ajouter"></span>
                            Ajouter
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Metier\Controller\MetierController::listerAgentsAction() */ ?>
                            href="<?php echo $this->url('metier/lister-agents', ['metier' => $metier->getId()], [], true); ?>"
                            class="ajax-modal"
                    >
                        <span class="icon users"></span>
                        Lister les agents
                    </a>
                <?php endif; ?>
                <?php if ($canAfficher) : ?>
                    <br/>
                    <a
                        <?php /** @see \Metier\Controller\MetierController::afficherAction() */ ?>
                            href="<?php echo $this->url('metier/afficher', ['metier' => $metier->getId()], [], true); ?>"
                            class="ajax-modal"
                    >
                            <span class="icon icon-voir"></span>
                            Afficher
                    </a>
                <?php endif; ?>

                <?php if ($canEditer) : ?>
                    <br>
                    <a
                        <?php /** @see \Metier\Controller\MetierController::modifierAction() */ ?>
                            href="<?php echo $this->url('metier/modifier', ['metier' => $metier->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>

                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($metier->estNonHistorise()) : ?>
                        <a  <?php /** @see \Metier\Controller\MetierController::historiserAction() */ ?>
                                href="<?php echo $this->url('metier/historiser', ['metier' => $metier->getId()], [], true); ?>"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <a  <?php /** @see \Application\Controller\MetierController::restaurerAction() */ ?>
                                href="<?php echo $this->url('metier/restaurer', ['metier' => $metier->getId()], [], true); ?>"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <br>
                    <a  <?php /** @see \Metier\Controller\MetierController::supprimerAction() */ ?>
                            href="<?php echo $this->url('metier/supprimer', ['metier' => $metier->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-retirer"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<br/>

<script>
    $(document).ready(function() {
        $('#metiers').DataTable( {
            // sorting: false,
            // paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );
</script>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
