<?php

/**
 * @see \Formation\Controller\FormationInstanceInscritController::formationsAction()
 * @var Inscription[] $inscriptions
 * @var Agent $agent
 * @var StagiaireExterne $stagiaire
 * @var string|null $mailcontact
 *
 * @var Rendu $enqueteExplication
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\Interfaces\HasSourceInterface;
use Formation\Entity\Db\Inscription;
use Formation\Entity\Db\StagiaireExterne;
use Formation\Provider\FichierNature\FichierNature;
use Formation\Provider\Privilege\FormationinstancedocumentPrivileges;
use Formation\Provider\Privilege\InscriptionPrivileges;
use UnicaenRenderer\Entity\Db\Rendu;

$realisees  = array_filter($inscriptions, function (Inscription $a) { return $a->getSession()->estRealisee();} );
usort($realisees, function (Inscription $a, Inscription $b) { return $a->getSession()->getDebut(true) <=> $b->getSession()->getDebut(true); });


$canGenererAbsence = $this->isAllowed(FormationinstancedocumentPrivileges::getResourceId(FormationinstancedocumentPrivileges::FORMATIONINSTANCEDOCUMENT_ABSENCE));
$canGenererAttestation = $this->isAllowed(FormationinstancedocumentPrivileges::getResourceId(FormationinstancedocumentPrivileges::FORMATIONINSTANCEDOCUMENT_ATTESTATION));
$canGenererHistorique = $this->isAllowed(FormationinstancedocumentPrivileges::getResourceId(FormationinstancedocumentPrivileges::FORMATIONINSTANCEDOCUMENT_HISTORIQUE));
$canEnquete = $this->isAllowed(InscriptionPrivileges::getResourceId(InscriptionPrivileges::INSCRIPTION_ENQUETE));
?>

<h2>
    Formations réalisées
</h2>


<div class="row">
<div class="alert alert-info col-md-9">
    <strong><span class="icon icon-attention"></span> <?php echo $enqueteExplication->getSujet(); ?> </strong>
    <?php echo $enqueteExplication->getCorps(); ?>
</div>
</div>

<?php if ($canGenererHistorique AND $agent !== null) : ?>
<?php /**  @see \Formation\Controller\FormationInstanceDocumentController::genererHistoriqueAction() */ ?>
<a href="<?php echo $this->url('formation/session/generer-historique', ['agent' => $agent->getId()], [], true); ?>"
   class="btn btn-primary" target="_blank"
>
    <span class="icon icon-pdf"></span>
    Générer l'historique de formation
</a>
<?php endif; ?>

<?php if (empty($realisees)) : ?>
    <em> Aucune formation en attente de retour </em>
<?php else : ?>
    <?php foreach ($realisees as $inscription) : ?>
        <div class="row formation-inscription">
            <div class="col-md-7 description">
                <?php echo $this->sessionInformations($inscription->getSession(), 'bloc'); ?>
                <br/>
                <br/>
            </div>
            <div class="col-md-5">
                <!-- Si une attestation est déposée alors elle prévaut sur le mécanisme de base -->
                <?php $attestations = $inscription->getFichiersByNatureCode(FichierNature::INSCRIPTION_ATTESTATION); ?>
                <?php if (!empty($attestations)) : ?>
                    <ul>
                    <?php foreach ($attestations as $attestation) : ?>
                        <li>
                            <?php /** @see \Formation\Controller\InscriptionController::telechargerAttestationAction() */ ?>
                            <a href="<?php echo $this->url('formation/inscription/telecharger-attestation', ['inscription' => $inscription->getId(), 'attestation' => $attestation->getId()], [], true); ?>">
                                <span class="icon icon-telecharger"></span>
                                <?php echo $attestation->getNomOriginal(); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                    </ul>
                <?php else : ?>
                    <?php if ($inscription->getSource() !== HasSourceInterface::SOURCE_EMC2) : ?>
                    <div class="alert alert-warning">
                        <span class="icon icon-information"></span>
                            Formation gérée par <?php echo $inscription->getSource(); ?>, mes-formations ne peut pas vous fournir d'attestation.
<!--                        --><?php //if ($mailcontact === null) : ?>
<!--                            la DRH-->
<!--                        --><?php //else : ?>
<!--                            <a href="mailto:--><?php //echo $mailcontact; ?><!--">--><?php //echo $mailcontact; ?><!--</a>-->
<!--                        --><?php //endif; ?>
                    </div>
                    <?php else : ?>
                        <?php if ($canEnquete && $inscription->getSession()->isEnqueteActive() AND $inscription->getValidationEnquete() === null) : ?>
                            <a
                                <?php /** @see \Formation\Controller\InscriptionController::repondreEnqueteAction() */?>
                                    href="<?php echo $this->url('formation/inscription/repondre-enquete', ['inscription' => $inscription->getId()], [], true); ?>"
                                    class="btn btn-primary action <?php if ($inscription->getValidationEnquete() !== null) echo " disabled "; ?>"
                            >
                                <span class="icon icon-editer"> Je complète l'enquête</span>
                            </a>
                            <br/>
                            <a
                                <?php /** @see \Formation\Controller\InscriptionController::validerEnqueteAction() */?>
                                    href="<?php echo $this->url('formation/inscription/valider-enquete', ['inscription' => $inscription->getId()], [], true); ?>"
                                    class="btn btn-primary ajax-modal action <?php if ($inscription->getEnquete() === null ) echo " disabled "; ?>"
                                    data-event="modification"
                            >
                                <span class="icon icon-checked"> Je valide mes réponses</span>
                            </a>
                        <?php else : ?>
                            <?php if ($canGenererAttestation) : ?>
                                <br/>
                                <a
                                    <?php /** @see \Formation\Controller\FormationInstanceDocumentController::genererAttestationAction() */?>
                                        href="<?php echo $this->url('formation/session/generer-attestation', ['inscription' => $inscription->getId()], [], true); ?>"
                                        class="btn btn-primary action <?php //if ($inscription->getValidationEnquete() === null) echo " disabled "; ?>"
                                >
                                    <span class="icon icon-pdf"> Je télécharge mon attestation</span>
                                </a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canGenererAbsence && $inscription->hasAbsence()) : ?>
                            <br>
                            <a
                                <?php /** @see \Formation\Controller\FormationInstanceDocumentController::genererAbsenceAction()Action() */?>
                                    href="<?php echo $this->url('formation/session/generer-absence', ['inscription' => $inscription->getId()], [], true); ?>"
                                    class="btn btn-primary action <?php //if ($inscription->getValidationEnquete() === null) echo " disabled "; ?>"
                            >
                                <span class="icon icon-pdf"> Je télécharge mon constat d'absence</span>
                            </a>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>