<?php

/**
 * @see \Formation\Controller\FormationInstanceInscritController::inscriptionInterneAction()
 * @var Session[] $sessions
 * @var Inscription[] $inscriptions
 * @var Agent $agent
 * @var Rendu $rendu
 */

$canInscrire = true; //todo !!!!

use Application\Entity\Db\Agent;
use Formation\Entity\Db\Inscription;
use Formation\Entity\Db\Session;
use UnicaenRenderer\Entity\Db\Rendu;

$this->headTitle("M'inscrire à une formation du plan de formation");

?>


<br/>

<h1 class="page-header"> M'inscrire à une formation du plan de formation </h1>

<div class="row">
    <div class="col-md-9">
        <?php if ($rendu) : ?>
            <div class="alert alert-info">
                <?php echo $rendu->getCorps(); ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>


<?php foreach ($sessions as $instance) : ?>
    <?php
    $nbPlace = ($instance->getNbPlacePrincipale() + $instance->getNbPlaceComplementaire()) - (count($instance->getListePrincipale()) + count($instance->getListeComplementaire()));
    $dejaInscrit = !empty(array_filter($inscriptions, function (Inscription $a) use ($instance) {
        return $a->estNonHistorise() and $a->getSession() === $instance;
    }));
    ?>
    <div class="row formation-instance">
        <div class="col-md-8 description">
            <?php echo $this->sessionInformations($instance, 'bloc'); ?>
        </div>
        <div class="col-md-4">
            <?php if ($dejaInscrit) : ?>
                <span class="alert alert-success"> <span class="icon icon-checked"></span>Demande d'inscription effectuée.</span>
            <?php else: ?>
                <?php if ($nbPlace <= 0) : ?>
                    <span class="alert alert-danger">Action de formation complète.</span>
                <?php else: ?>
                    <?php if ($canInscrire) : ?>
                        <?php /**  @see \Formation\Controller\InscriptionController::inscriptionAction() */ ?>
                        <a href="<?php echo $this->url('formation/inscription/creer-inscription', [
                            'session' => $instance->getId(),
                            'agent' => $agent->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal" data-event="modification">
                            <span class="icon inscription-ouverture"> Je m'inscris</span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors = [];
            window.location.reload();
        });
    });

    $(document).ready(function () {
        $('.datatable').DataTable({
            sorting: false,
            paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        });
    });

    $(function () {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "instances";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav a').click(function (e) {
            let anchor = $(this).attr('aria-controls');
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#" + anchor);
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>