<?php

/**
 * @see \Formation\Controller\FormationInstanceInscritController::inscriptionsAction()
 * @var FormationInstance[] $instances
 * @var Inscription[] $inscriptions
 * @var DemandeExterne[] $demandes
 * @var Agent $agent
 */

use Application\Entity\Db\Agent;
use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\FormationInstance;
use Formation\Entity\Db\Inscription;
use Formation\Provider\Etat\DemandeExterneEtats;
use Formation\Provider\Etat\SessionEtats;

$canInscrire = true;

$formationValidees = [];
foreach ($inscriptions as $inscription) {
    if ($inscription->getSession()->estPrete() AND $inscription->getListe() === Inscription::PRINCIPALE) $formationValidees[] = $inscription;
}
$demandesValidees = [];
$demandesAttentes = [];
foreach ($demandes as $demande) {
    if ($demande->isEtatActif(DemandeExterneEtats::ETAT_VALIDATION_DRH)) {
        $demandesValidees[] = $demande;
    } else {
        $demandesAttentes[] = $demande;
    }
}

$formationsAttentes = [];
foreach ($inscriptions as $inscription) {
    if ($inscription->getSession()->estPrete() AND $inscription->getListe() !== Inscription::PRINCIPALE) $formationsAttentes[] = $inscription;
    if ($inscription->getSession()->estPreparation()) $formationsAttentes[] = $inscription;
}

?>
<h1>
    Mes inscriptions validées
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<?php if (empty($formationValidees) AND empty($demandesValidees)) : ?>
    <em> Aucune formation validée </em>
<?php else : ?>
    <?php foreach ($formationValidees as $inscription) : ?>
    <?php
        $instance = $inscription->getInstance();
        $nbPlace = ($instance->getNbPlacePrincipale() + $instance->getNbPlaceComplementaire()) - (count($instance->getListePrincipale()) + count($instance->getListeComplementaire()));
    ?>
    <div class="row formation-inscription">
        <div class="col-md-8 description">
            <?php echo $this->formationInstanceInformations($instance, 'bloc'); ?>
            <br/>
            <strong> Inscrit en liste <?php echo $inscription->getListe(); ?></strong>
        </div>
        <div class="col-md-4">
            <a
                <?php /** @see \Formation\Controller\FormationInstanceInscritController::desinscriptionAction() */?>
                    href="<?php echo $this->url('formation-instance/desinscription', ['inscrit' => $inscription->getId()], [], true); ?>"
                    class="btn btn-danger action ajax-modal" data-event="modification"
            >
                <span class="icon icon-unchecked"> J'annule mon inscription </span>
            </a>
            <?php if ($instance->isEtatActif(SessionEtats::ETAT_FORMATION_CONVOCATION) && $inscription->getListe() === Inscription::PRINCIPALE) : ?>
            <br/>
                <a
                    <?php /** @see \Formation\Controller\FormationInstanceDocumentController::genererConvocationAction() */?>
                        href="<?php echo $this->url('formation-instance/generer-convocation', ['inscrit' => $inscription->getId()], [], true); ?>" class="btn btn-primary action"
                >
                    <span class="icon icon-pdf"> Je télécharge ma convocation</span>
                </a>
            <?php endif; ?>
        </div>
    </div>
    <br/>
<?php endforeach; ?>
    <?php foreach ($demandesValidees as $demande) : ?>
        <?php echo $this->demandeExterne($demande); ?>
    <?php endforeach; ?>
<?php endif; ?>

<h1>
    Mes inscriptions en attente de validation
</h1>

<?php if (empty($formationsAttentes) AND empty($demandesAttentes)) : ?>
    <em> Aucune formation en attente de validation </em>
<?php else : ?>
    <?php foreach ($formationsAttentes as $inscription) : ?>
    <?php
    $instance = $inscription->getSession();
    $nbPlace = ($instance->getNbPlacePrincipale() + $instance->getNbPlaceComplementaire()) - (count($instance->getListePrincipale()) + count($instance->getListeComplementaire()));
    ?>
    <div class="row formation-inscription">
        <div class="col-md-7 description">
            <?php echo $this->formationInstanceInformations($instance, 'bloc'); ?>
            <br/>
        </div>
        <div class="col-md-5">
            <a
                <?php /** @see \Formation\Controller\InscriptionController::desinscriptionAction() */?>
                    href="<?php echo $this->url('formation/inscription/annuler-inscription', ['inscription' => $inscription->getId()], [], true); ?>"
                    class="btn btn-danger action ajax-modal" data-event="modification"
            >
                <span class="icon icon-unchecked"> J'annule mon inscription </span>
            </a>
            <?php if ($instance->isEtatActif(SessionEtats::ETAT_FORMATION_CONVOCATION) && $inscription->getListe() === Inscription::PRINCIPALE) : ?>
                <br/>
                <a
                    <?php /** @see \Formation\Controller\InscriptionController::genererConvocationAction() */?>
                        href="<?php echo $this->url('formation/inscripitoninstance/generer-convocation', ['inscrit' => $inscription->getId()], [], true); ?>" class="btn btn-primary action"
                >
                    <span class="icon icon-pdf"> Je télécharge ma convocation</span>
                </a>
            <?php endif; ?>
        </div>
    </div>
    <br/>
<?php endforeach; ?>
    <?php foreach ($demandesAttentes as $demande) : ?>
        <?php echo $this->demandeExterne($demande); ?>
    <?php endforeach; ?>
<?php endif; ?>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>