<?php

/**
 * @see \Formation\Controller\FormationInstanceInscritController::inscriptionExterneAction()
 * @var DemandeExterne[] $demandes
 * @var Agent $agent
 */

use Application\Entity\Db\Agent;
use Formation\Entity\Db\DemandeExterne;
use Formation\Provider\Privilege\DemandeexternePrivileges;

$this->headTitle("M'inscrire à un stage hors du plan de formation");

?>


<br/>

<h1 class="page-header"> M'inscrire à un stage hors du plan de formation </h1>

<div class="alert alert-info">
    <span class="icon icon-attention"></span>
    <strong>La demande d'inscription ne vaut pas acceptation.</strong>
    Votre inscription est soumise à validation et en fonction des places disponibles.
</div>


<?php

$canAjouterDemande      = $this->isAllowed(DemandeexternePrivileges::getResourceId(DemandeexternePrivileges::DEMANDEEXTERNE_AJOUTER));
?>

<h2>
    S'inscire à un stage hors du plan de formation
</h2>

<div class="row">
    <div class="col-md-7">
        Afin de réaliser cette demande :
        <ol>
            <li> remplir le formulaire ;</li>
            <li> déposer au moins un devis (ou document équivalent) ;</li>
            <li> valider votre demande.</li>
        </ol>
    </div>
    <div class="col-md-5">
        <?php /** @see \Formation\Controller\DemandeExterneController::ajouterAction() */ ?>
        <a href="<?php echo $this->url('formation/demande-externe/ajouter', ['agent' => $agent->getId()], [], true); ?>"
           class="btn btn-primary ajax-modal <?php if (!$canAjouterDemande) echo " disabled "; ?> " data-event="modification"
        >
            <span class="icon icon-ajouter"></span>
            Je remplis le formulaire
        </a>
    </div>
</div>

<br/>

<h2> Demandes que je n'ai pas encore validées </h2>

<?php foreach($demandes as $demande) : ?>
    <?php
    $url = $this->url('inscription-formation', [], ['force_canonical' => true, 'fragment' => 'demandes'], true);
    echo $this->demandeExterne($demande, ['retour' => $url]);
    ?>
<?php endforeach; ?>




<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });
    });

    $(document).ready(function() {
        $('.datatable').DataTable( {
            sorting:false,
            paging:false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "instances";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav a').click(function (e) {
            let anchor = $(this).attr('aria-controls');
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#"+anchor);
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>