<?php

/**
 * @see \Formation\Controller\FormationInstanceInscritController::listeFormationsInstancesAction()
 * @var FormationInstance[] $instances
 * @var DemandeExterne[] $demandes
 * @var FormationInstance[] $formations
 * @var FormationInstanceInscrit[] $inscriptions
 * @var Agent $agent
 * @var string $texteParcours
 */

use Application\Entity\Db\Agent;
use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\FormationInstance;
use Formation\Entity\Db\FormationInstanceInscrit;

$this->headTitle("Liste des actions de formations proposées");

?>

<h1 class="page-header">
    Liste des actions de formations proposées
</h1>


<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<br/>

<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" href="#instances" aria-controls="instances">
            Actions de formation
            <span class="badge"> <?php echo count($instances); ?> </span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#demandes" aria-controls="demandes">
            Demandes de formation externe
            <span class="badge"> <?php echo count($demandes); ?> </span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#inscriptions" aria-controls="inscriptions" role="tab" data-toggle="tabz">
            Mes inscriptions
            <span class="badge"> <?php echo count($inscriptions); ?> </span>
        </a>
    </li>
    <li class="nav-item" >
        <a class="nav-link" href="#formations" aria-controls="formations" role="tab" data-toggle="tabz">
            Mes formations suivies
            <span class="badge">
            <?php echo count($formations); ?>
        </span>
        </a>
    </li>
<!--    <li class="nav-item pull-right" style="margin-left: 10rem;">-->
<!--        <a class="nav-link" href="#parcours" aria-controls="parcours" role="tab" data-toggle="tabz" >-->
<!--            Mon parcours d'entrée-->
<!--        </a>-->
<!--    </li>-->
</ul>

<div class="tab-content">

    <!-- Mission------------------------------------------------------------------------------------------->
    <div id="instances" class="tab-pane">
        <?php echo $this->partial('partial/instances', ['instances' => $instances, 'inscriptions' => $inscriptions, 'agent' => $agent]); ?>
    </div>

    <!-- Mission------------------------------------------------------------------------------------------->
    <div id="demandes" class="tab-pane">
        <?php echo $this->partial('partial/demandes-externes', ['demandes' => $demandes, 'agent' => $agent]); ?>
    </div>


    <!-- Type---------------------------------------------------------------------------------------------->
    <div id="inscriptions" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/inscriptions', ['instances' => $instances, 'inscriptions' => $inscriptions, 'agent' => $agent]); ?>
    </div>

    <!-- Type---------------------------------------------------------------------------------------------->
    <div id="formations" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/formations', ['formations' => $formations, 'agent' => $agent]); ?>
    </div>

    <!-- Type---------------------------------------------------------------------------------------------->
    <div id="parcours" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/parcours-entree', ['description' => $texteParcours, 'agent' => $agent]); ?>
    </div>

</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });
    });

    $(document).ready(function() {
        $('.datatable').DataTable( {
            sorting:false,
            paging:false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "instances";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav a').click(function (e) {
            let anchor = $(this).attr('aria-controls');
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#"+anchor);
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>