<?php

/**
 * @var string $source
 * @var string $historise
 */

use Application\Entity\Db\Interfaces\HasSourceInterface;

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="icon filtrer"></span>
        Filtrage des groupes de formation
    </div>
    <div class="panel-body">
        <form id="filtre" action="<?php echo $this->url(); ?>" method="get">
            <div class="col-md-4">
                <label for="source">Source : </label>
                <select id="source" name="source" class="selectpicker">
                    <option value=""> Toutes les sources </option>
                    <option value="<?php echo HasSourceInterface::SOURCE_EMC2; ?>"> <?php echo HasSourceInterface::SOURCE_EMC2; ?> </option>
                    <option value="<?php echo HasSourceInterface::SOURCE_LAGAF; ?>"> <?php echo HasSourceInterface::SOURCE_LAGAF; ?> </option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="historise">Historisé : </label>
                <select id="historise" name="historise" class="selectpicker">
                    <option value=""> Peu importe </option>
                    <option value="1"> Historisé </option>
                    <option value="0"> Non historisé </option>
                </select>
            </div>
            <!-- BOUTON -->
            <div class="col-md-4">
                <div class="pull-right">
                    <button class="btn btn-primary action" id="clear">
                        <span class="icon effacer"></span>
                    </button>

                    <button class="btn btn-primary action" id="filter">
                        <span class="icon filtrer"></span>
                        Filtrer
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    let source = <?php echo '"' . $source . '"'; ?>;
    let historise = <?php echo '"' . $historise . '"'; ?>;
    // console.log("source=" + source);
    // console.log("historise=" + historise);

    $("form#filtre").submit(function(e){
        e.preventDefault();
    });

    $('button#clear').click(function() {
        window.location.href = '?';
    });

    $('button#filter').click(function() {
        let sourceId = $('select#source option:selected').val();
        console.log( "source=" + sourceId);
        let historiseId = $('select#historise option:selected').val();
        console.log( "historise=" + historiseId);

        let query = "";
        query += "&source=" + sourceId;
        query += "&historise=" + historiseId;
        window.location.href = 'formation-groupe?'+ query ;
    });

    $('select#source option[value=' + source + ']').prop('selected', true);
    $('select#historise option[value=' + historise + ']').prop('selected', true);

</script>