<?php

use Formation\Entity\Db\Formation;
use Formation\Entity\Db\PlanDeFormation;

/**
 * @see \Formation\Controller\FormationController::ajouterPlanDeFormationAction()
 * @var Formation $formation
 * @var PlanDeFormation[] $plans
 */

?>

<?php /** @see \Formation\Controller\FormationController::ajouterPlanDeFormationAction() */ ?>
<form method="post" action="<?php echo $this->url('formation/ajouter-plan-de-formation', ['formation' => $formation->getId()], [], true); ?>">
    <label for="plan">Selectionner un plan de formation à ajouter :</label>
    <select id="plan" name="plan" class="selected" data-live-search="true">
        <?php foreach ($plans as $plan) : ?>
            <?php if (!$formation->hasPlanDeFormation($plan)) :?>
                <option value="<?php echo $plan->getId(); ?>"> <?php echo $plan->getAnnee(); ?> </option>
            <?php endif; ?>
        <?php endforeach; ?>
    </select>
    <button class="btn btn-primary">
        <span class="icon icon-ajouter"></span>
        Ajouter
    </button>
</form>
