<?php

use Application\Entity\Db\Agent;
use Formation\Entity\Db\ActionCoutPrevisionnel;
use Formation\Entity\Db\Formation;
use Formation\Entity\Db\Session;
use Formation\Entity\Db\Seance;

/**
 * @see \Formation\Controller\FormationController::ficheAction()
 * @var Formation $formation
 * @var Session[] $sessions
 * @var ActionCoutPrevisionnel[] $coutsPrevisionnels
 * @var ?Agent $agent
 */


?>

<h2> Description de la formation </h2>

<?php echo $this->formationInformations($formation, 'liste', ['no-action' => true]); ?>

<h2> Liste des sessions ouvertes </h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Identifiant </th>
        <th> Séances et volumes </th>
        <th> Informations sur la session</th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($sessions as $session): ?>
    <tr>
        <td> <?php echo $session->getId(); ?> </td>
        <td>
            <?php echo $session->getPeriode(); ?>
            <ul>
            <?php foreach ($session->getSeances() as $seance) : ?>
                <li>
                    <?php if ($seance->getType() === Seance::TYPE_SEANCE) : ?>
                        <?php echo $seance->getJour()->format('d/m/Y'); ?>
                        de <?php echo $seance->getDebut() ; ?> à <?php echo $seance->getFin() ; ?>
                        <span style="color:var(--unistrap-color-main); font-weight:bold;">SÉANCE</span>
                    <?php endif; ?>
                    <?php if ($seance->getType() === Seance::TYPE_VOLUME) : ?>
                        du <?php echo $seance->getVolumeDebut()->format('d/m/Y'); ?>
                        au <?php echo $seance->getVolumeFin()->format('d/m/Y'); ?>
                        (<?php echo $seance->getVolume(); ?> heure·s)
                        <span style="color:var(--unistrap-color-main); font-weight:bold;">VOLUME</span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </td>
        <td>
            <strong>Taille de la liste principale : </strong> <?php echo $session->getNbPlacePrincipale(); ?> <br>
            <strong>Clôture des inscriptions </strong> :
            <?php if ($session->getDateClotureInscription() !== null) : ?>
                <?php echo $session->getDateClotureInscription()->format('d/m/Y'); ?>
            <?php else : ?>
                <em>Aucune date connue</em>
            <?php endif; ?>
        </td>
        <td>
            <?php if ($agent !== null): ?>
                <?php if ($session->hasIndividu($agent)) : ?>
                    <span class="text-success">
                        <span class="icon icon-checked"></span>
                        Vous êtes inscrit·e
                    </span>
                <?php else: ?>
                    <?php /**  @see \Formation\Controller\InscriptionController::inscriptionAction() */ ?>
                    <a href="<?php echo $this->url('formation/inscription/creer-inscription', [
                        'session' => $session->getId(),
                        'agent' => $agent->getId()], [], true); ?>"
                       class="btn btn-primary" data-event="modification">
                        <span class="icon inscription-ouverture"> Je m'inscris</span>
                    </a>
                <?php endif; ?>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
