<?php

use Formation\Entity\Db\Formation;
use Formation\Entity\Db\FormationInstance;
use Formation\Provider\Privilege\FormationinstancePrivileges;
use Formation\Provider\Privilege\FormationPrivileges;

/**
 * @var Formation $formation
 * @var string $mode
 */

$canModifierInformations    = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_MODIFIER));
$canAfficherInstance        = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_AFFICHER));
$canAjouterInstance         = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_AJOUTER));
$canHistoriserInstance      = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_HISTORISER));
$canSupprimerInstance       = $this->isAllowed(FormationinstancePrivileges::getResourceId(FormationinstancePrivileges::FORMATIONINSTANCE_SUPPRIMER));

/** @var FormationInstance[] $instances */
$instances = $formation->getInstances();
?>

<h1 class="page-header">
    Formation #<?php echo $formation->getId(); ?>
</h1>

<div class="main">
    <div class="row">
        <div class="col-md-8">
            <dl class="dl-horizontal">
                <dt>Libelle</dt>
                <dd>
                    <?php echo $formation->getLibelle(); ?>
                </dd>
                <dt>Description</dt>
                <dd>
                    <?php echo ($formation->getDescription() !== null AND trim($formation->getDescription()) !== "")?$formation->getDescription():"Aucune description"; ?>
                </dd>
                <dt>Thème</dt>
                <dd>
                    <?php echo ($formation->getTheme())?$formation->getTheme()->getLibelle():"Non renseigné"; ?>
                </dd>
                <dt>Groupe</dt>
                <dd>
                    <?php echo ($formation->getGroupe())?$formation->getGroupe()->getLibelle():"Non renseigné"; ?>
                </dd>
                <dt>Lien</dt>
                <dd>
                    <?php echo ($formation->getLien())?"<a href='".$formation->getLien()."'>Lien vers la fiche de la formation</a>":"Non renseigné"; ?>
                </dd>
            </dl>
        </div>
        <div class="pull-right">
            <?php if ($canModifierInformations) : ?>
                <?php /** @see FormationController::modifierFormationInformationsAction() */?>
                <a      href="<?php echo $this->url('formation/modifier-formation-informations', ['formation' => $formation->getId()], [], true); ?>"
                        class="btn btn-primary action ajax-modal" data-event="modification"
                >
                    <span class="icon editer"></span>
                    Modifier les informations
                </a>
            <?php endif; ?>
            <br/>
            <?php /** @see \Application\Controller\FormationController::indexAction() */ ?>
            <a      href="<?php echo $this->url('formation', [], ['fragment' => "formation"], true); ?>"
                    class="btn btn-info action">
                <span class="icon retour"></span>
                Retour à l'index des formations

            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <h2>
                Instances de la formation
                <span class="badge"><?php echo count($instances); ?></span>
            </h2>
        </div>
        <div class="pull-right">
            <br/>
            <?php if ($canAjouterInstance) : ?>
                <?php /** @see FormationInstanceController::ajouterAction() */ ?>
                <a      href="<?php echo $this->url('formation-instance/ajouter', ['formation' => $formation->getId()], [], true); ?>"
                        class="btn btn-primary action"
                >
                    <span class="icon ajouter"></span>
                    Ajouter une instance
                </a>
            <?php endif; ?>
            <br/>
            <br/>
        </div>
    </div>

    <table class="datatable table table-condensed">
        <thead>
            <tr>
                <th> Id </th>
                <th> Début </th>
                <th> Fin </th>
                <th> #Jour </th>
                <th> #Inscrit </th>
                <th> État </th>
                <th> Action</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($instances as $instance) : ?>
            <tr <?php if ($instance->estHistorise()) echo 'class="historise"'; ?> >
                <td> <?php echo $instance->getId(); ?> </td>
                <td> <?php echo ($instance->getDebut())?:"???"; ?></td>
                <td> <?php echo ($instance->getFin())?:"???"; ?></td>
                <td> <?php echo ($instance->getJournees())?count($instance->getJournees()):"???"; ?></td>
                <td>
                    <?php if ($instance->getInscrits()) : ?>
                        Principale : <?php echo count($instance->getListePrincipale())."/".$instance->getNbPlacePrincipale(); ?>
                        <?php if ($instance->isListePrincipaleComplete()) : ?>
                            <span class="label label-success"> Complète</span>
                        <?php endif; ?>
                        <br/>
                        Complémentaire : <?php echo count($instance->getListeComplementaire())."/".$instance->getNbPlaceComplementaire(); ?>
                        <?php if ($instance->isListeComplementaireComplete()) : ?>
                            <span class="label label-success"> Complète</span>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo ($instance->getEtat())?$this->etatbadge($instance->getEtat()):"N.C."; ?>
                </td>
                <td>
                    <?php if ($canAfficherInstance) : ?>
                        <?php /** @see FormationInstanceController::afficherAction() */ ?>
                        <a  href="<?php echo $this->url('formation-instance/afficher', ['formation-instance' => $instance->getId()], [], true); ?>"
                            data-toogle="tooltip" data-html="true" title="Afficher/Modifier l'instance de formation">
                            <span class="icon voir"></span></a>
                    <?php endif; ?>
                    <?php if ($canAfficherInstance) : ?>
                            <span class="icon pdf"></span>
                    <?php endif; ?>
                    <?php if ($canHistoriserInstance) : ?>
                        <?php if ($instance->estNonHistorise()) : ?>
                            <?php /** @see FormationInstanceController::historiserAction() */ ?>
                            <a   href="<?php echo $this->url('formation-instance/historiser', ['formation-instance' => $instance->getId()], [], true); ?>"
                                 data-toogle="tooltip" data-html="true" title="Historiser l'instance de formation">
                                <span class="icon historiser"></span></a>
                        <?php else : ?>
                            <?php /** @see FormationInstanceController::restaurerAction() */ ?>
                            <a   href="<?php echo $this->url('formation-instance/restaurer', ['formation-instance' => $instance->getId()], [], true); ?>"
                                 data-toogle="tooltip" data-html="true" title="Restaurer l'instance de formation">
                                <span class="icon restaurer"></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canSupprimerInstance) : ?>
                        <?php /** @see FormationInstanceController::supprimerAction() */ ?>
                        <a   href="<?php echo $this->url('formation-instance/supprimer', ['formation-instance' => $instance->getId()], [], true); ?>"
                             class="ajax-modal" data-event="modification"
                             data-toogle="tooltip" data-html="true" title="Supprimer l'instance de formation">
                            <span class="icon detruire"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });
    });
</script>