<?php

use Application\Entity\Db\Formation;

/**
 * @var Formation $formation
 */

?>

<div class="panel panel-info">
    <div class="panel-heading">
        <h2><?php echo $formation->getLibelle() ?></h2>
    </div>
    <div class="panel-body">
        <h3> Description </h3>
        <?php if ($formation->getDescription() !== null) : ?>
            <?php echo $formation->getDescription(); ?>
        <?php else : ?>
            Aucune description.
        <?php endif; ?>

        <h3> Lien </h3>
        <?php if ($formation->getLien() !== null && $formation->getLien() !== "") : ?>
            <a href="<?php echo $formation->getLien(); ?>">
                <?php echo $formation->getLien(); ?>
            </a>
        <?php else : ?>
            Aucun lien.
        <?php endif; ?>

        <h3> Connaissances/Compétences liées
            <span class="badge">
                <?php echo count($formation->getMissions()); ?>
            </span>
        </h3>
        <?php if (!empty($formation->getMissions())): ?>
            <ul>
                <?php foreach ($formation->getMissions() as $mission) : ?>
                    <li> <?php echo $mission->getLibelle(); ?> </li>
                <?php endforeach; ?>
            </ul>
        <?php else : ?>
            Aucune connaissance ou compétence liée à cette formation
        <?php endif; ?>

        <h3> Applications liées
            <span class="badge">
                <?php echo count($formation->getApplications()); ?>
            </span>
        </h3>
        <?php if (!empty($formation->getApplications())): ?>
            <ul>
                <?php foreach ($formation->getApplications() as $application) : ?>
                    <li> <?php echo $application->getLibelle(); ?> </li>
                <?php endforeach; ?>
            </ul>
        <?php else : ?>
            Aucune application liée à cette formation
        <?php endif; ?>
    </div>
</div>
