<?php

/**
 * @see RessourceRhController::indexMissionSpecifiqueAction()
 *
 * @var Formation[] $formations
 * @var FormationTheme[] $themes
 */

use Application\Controller\FormationController;
use Application\Controller\RessourceRhController;
use Application\Entity\Db\Formation;
use Application\Entity\Db\FormationTheme;
use Application\Provider\Privilege\FormationPrivileges;

$canAfficher = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AFFICHER));
$canAjouter = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_AJOUTER));
$canEditer = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_EDITER));
$canHistoriser = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_HISTORISER));
$canDetruire = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::FORMATION_DETRUIRE));

$this->headTitle("Index des formations");
?>

<h1 class="page-header">
    Index des formations
</h1>


<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">
        <li role="formation">
            <a href="#formation" aria-controls="formation" role="tab" data-toggle="tabz" >
                Formations &nbsp;
                <span class="badge">
                    <?php echo count($formations); ?>
                </span>
            </a>
        </li>
        <li role="theme">
            <a href="#theme" aria-controls="theme" role="tab" data-toggle="tabz">
                Thèmes &nbsp;
                <span class="badge">
                    <?php echo count($themes); ?>
                </span>
            </a>
        </li>
    </ul>

    <div class="main-with-tab">

        <div class="tab-content">

            <div id="theme" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Thèmes des formations
                        </h2>
                    </div>
                    <div class="col-md-4">
                        <?php if ($canAjouter) : ?>
                            <br/>
                            <a href="<?php echo $this->url('formation-theme/ajouter', [], [], true); ?>"
                               class="btn btn-primary action ajax-modal"
                               data-event="modification">
                                <span class="icon ajouter"></span>
                                Ajouter un thème
                            </a>
                        <?php endif; ?>
                    </div>
                </div>

                <br/>

                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libellé </th>
                        <th> #Formation </th>
                        <th> Modification </th>
                        <th> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($themes as $theme) : ?>
                        <tr>
                            <td> <?php echo $theme->getLibelle(); ?> </td>
                            <td> <?php echo count($theme->getFormations()); ?> </td>
                            <td>
                                <small>
                                    <?php echo $theme->getHistoModification()->format('d/m/Y à H:i'); ?>
                                    <br/>
                                    <?php echo $theme->getHistoModificateur()->getDisplayName(); ?>
                                </small>
                            </td>
                            <td>
                                <?php if ($canAfficher) : ?>
                                    <?php /** @see FormationController::afficherThemeAction() */ ?>
                                    <a href="<?php  echo $this->url('formation-theme/afficher', ['formation-theme' => $theme->getId()], [], true); ?>"
                                       class="ajax-modal">
                                        <span class="icon voir" title="Afficher le thème"></span></a>
                                <?php else : ?>
                                    <span class="icon voir" style="color:lightgrey;"></span>
                                <?php endif; ?>
                                <?php if ($canEditer) : ?>
                                    <?php /** @see FormationController::editerThemeAction() */ ?>
                                    <a href="<?php  echo $this->url('formation-theme/editer', ['formation-theme' => $theme->getId()], [], true); ?>"
                                       class="ajax-modal"
                                       data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier le thème"></span></a>
                                <?php else : ?>
                                    <span class="icon editer" style="color:lightgrey;"></span>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($theme->estNonHistorise()) : ?>
                                        <?php /** @see FormationController::historiserThemeAction() */ ?>
                                        <a href="<?php  echo $this->url('formation-theme/historiser', ['formation-theme' => $theme->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser le thème"></span></a>
                                    <?php else : ?>
                                        <?php /** @see FormationController::restaurerThemeAction() */ ?>
                                        <a href="<?php  echo $this->url('formation-theme/restaurer', ['formation-theme' => $theme->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer le thème"></span></a>
                                    <?php endif; ?>
                                <?php else : ?>
                                    <?php if ($theme->estNonHistorise()) : ?>
                                        <span class="icon historiser" style="color:lightgrey;"></span>
                                    <?php else : ?>
                                        <span class="icon restaurer" style="color:lightgrey;"></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canDetruire) : ?>
                                    <?php /** @see FormationController::detruireThemeAction() */ ?>
                                    <a href="<?php echo $this->url('formation-theme/detruire', ['formation-theme' => $theme->getId()], [], true); ?>"
                                    >
                                        <span class="icon detruire" title="Afficher le thème"></span></a>
                                <?php else : ?>
                                    <span class="icon detruire" style="color:lightgrey;"></span>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>


            <div id="formation" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Formations
                        </h2>
                    </div>
                    <div class="col-md-4">
                        <?php if ($canAjouter) : ?>
                            <br/>

                            <?php /** @see FormationController::ajouterThemeAction() */ ?>
                            <a href="<?php echo $this->url('formation/ajouter', [], [], true); ?>"
                               class="btn btn-primary action ajax-modal"
                               data-event="modification">
                                <span class="icon ajouter"></span>
                                Ajouter une formation
                            </a>
                        <?php endif; ?>
                    </div>
                </div>

                <br/>

                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libellé </th>
                        <th> Thème </th>
                        <th> Lien </th>
                        <th> Modification </th>
                        <th> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($formations as $formation) : ?>
                        <tr>
                            <td> <?php echo $formation->getLibelle(); ?> </td>
                            <td> <?php echo ($formation->getTheme())?$formation->getTheme()->getLibelle():""; ?> </td>
                            <td>
                                <?php if ($formation->getLien() !== null) : ?>
                                    <a href="<?php echo $formation->getLien(); ?>">
                                        <?php echo $formation->getLien(); ?>
                                    </a>
                                <?php endif; ?>
                            </td>
                            <td>
                                <small>
                                    <?php echo $formation->getHistoModification()->format('d/m/Y à H:i'); ?>
                                    <br/>
                                    <?php echo $formation->getHistoModificateur()->getDisplayName(); ?>
                                </small>
                            </td>
                            <td>
                                <?php if ($canAfficher) : ?>
                                    <a href="<?php echo $this->url('formation/afficher', ['formation' => $formation->getId()], [], true); ?>"
                                       class="ajax-modal">
                                        <span class="icon voir" title="Afficher la formation"></span></a>
                                <?php else : ?>
                                    <span class="icon voir" style="color:lightgrey;"></span>
                                <?php endif; ?>
                                <?php if ($canEditer) : ?>
                                    <a href="<?php echo $this->url('formation/editer', ['formation' => $formation->getId()], [], true); ?>"
                                       class="ajax-modal"
                                       data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier la formation"></span></a>
                                <?php else : ?>
                                    <span class="icon editer" style="color:lightgrey;"></span>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($formation->estNonHistorise()) : ?>
                                        <a href="<?php echo $this->url('formation/historiser', ['formation' => $formation->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser la formation"></span></a>
                                    <?php else : ?>
                                        <a href="<?php echo $this->url('formation/restaurer', ['formation' => $formation->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer la formation"></span></a>
                                    <?php endif; ?>
                                <?php else : ?>
                                    <?php if ($formation->estNonHistorise()) : ?>
                                        <span class="icon historiser" style="color:lightgrey;"></span>
                                    <?php else : ?>
                                        <span class="icon restaurer" style="color:lightgrey;"></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canDetruire) : ?>
                                    <a href="<?php echo $this->url('formation/detruire', ['formation' => $formation->getId()], [], true); ?>"
                                    >
                                        <span class="icon detruire" title="Afficher la formation"></span></a>
                                <?php else : ?>
                                    <span class="icon detruire" style="color:lightgrey;"></span>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <script>
        $(document).ready(function() {
            $('.datatable').DataTable( {
                language: {
                    url: '/localisation/fr_FR.json'
                }
            } );
        } );

        $(function() {
            let hash = $(location).attr('hash');
            let name = hash.substr(1);
            if (name === undefined || name === "") name = "formation";

            $('a[aria-controls=' + name + ']').tab('show');

            $('.nav-tabs a').click(function (e) {
                // No e.preventDefault() here
                $(this).tab('show');
            });

            $("body").on("modification", function (event) {
                event.div.modal('hide');
                window.location.reload();
            });
        });
    </script>
