<?php

/**
 * @var Formation[] $formations
 */

use Application\Entity\Db\Formation;
use Application\Provider\Privilege\FormationPrivileges;

$canAfficher = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::AFFICHER));
$canAjouter = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::EDITER));
$canEditer = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::EDITER));
$canHistoriser = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::EDITER));
$canDetruire = $this->isAllowed(FormationPrivileges::getResourceId(FormationPrivileges::DETRUIRE));

?>

<h1 class="page-header">
    Formations
    <span class="badge">
        <?php echo count($formations); ?>
    </span>
</h1>

<div class="main">
    <?php if ($canAjouter) : ?>
        <a href="<?php echo $this->url('formation/ajouter', [], [], true); ?>"
           class="btn btn-primary action ajax-modal"
           data-event="modification">
            <span class="icon ajouter"></span>
            Ajouter une formation
        </a>

        <br/>
        <br/>
    <?php endif; ?>

    <table id="datatable" class="table table-condensed">
        <thead>
            <tr>
                <th> Libellé </th>
                <th> Lien </th>
                <th> Modification </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($formations as $formation) : ?>
                <tr>
                    <td> <?php echo $formation->getLibelle(); ?> </td>
                    <td>
                        <?php if ($formation->getLien() !== null) : ?>
                            <a href="<?php echo $formation->getLien(); ?>">
                                <?php echo $formation->getLien(); ?>
                            </a>
                        <?php endif; ?>
                    </td>
                    <td>
                        <small>
                            <?php echo $formation->getHistoModification()->format('d/m/Y à H:i'); ?>
                            <br/>
                            <?php echo $formation->getHistoModificateur()->getDisplayName(); ?>
                        </small>
                    </td>
                    <td>
                        <?php if ($canAfficher) : ?>
                            <a href="<?php echo $this->url('formation/afficher', ['formation' => $formation->getId()], [], true); ?>"
                               class="ajax-modal">
                                <span class="icon voir" title="Afficher la formation"></span></a>
                        <?php else : ?>
                            <span class="icon voir" style="color:lightgrey;"></span>
                        <?php endif; ?>
                        <?php if ($canEditer) : ?>
                            <a href="<?php echo $this->url('formation/editer', ['formation' => $formation->getId()], [], true); ?>"
                               class="ajax-modal"
                               data-event="modification"
                            >
                                <span class="icon editer" title="Éditer la formation"></span></a>
                        <?php else : ?>
                            <span class="icon editer" style="color:lightgrey;"></span>
                        <?php endif; ?>
                        <?php if ($canHistoriser) : ?>
                            <?php if ($formation->estNonHistorise()) : ?>
                                <a href="<?php echo $this->url('formation/historiser', ['formation' => $formation->getId()], [], true); ?>"
                                   >
                                    <span class="icon historiser" title="Historiser la formation"></span></a>
                            <?php else : ?>
                                <a href="<?php echo $this->url('formation/restaurer', ['formation' => $formation->getId()], [], true); ?>"
                                   >
                                    <span class="icon restaurer" title="Restaurer la formation"></span></a>
                            <?php endif; ?>
                        <?php else : ?>
                            <?php if ($formation->estNonHistorise()) : ?>
                                <span class="icon historiser" style="color:lightgrey;"></span>
                            <?php else : ?>
                                <span class="icon restaurer" style="color:lightgrey;"></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canDetruire) : ?>
                            <a href="<?php echo $this->url('formation/detruire', ['formation' => $formation->getId()], [], true); ?>"
                               >
                                <span class="icon detruire" title="Afficher la formation"></span></a>
                        <?php else : ?>
                            <span class="icon detruire" style="color:lightgrey;"></span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function() {
        $('#datatable').DataTable( {
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>