<?php

use Utilisateur\Entity\Db\Role;
use Utilisateur\Entity\Db\User;
//use Utilisateur\Provider\Privilege\Privileges;
use Utilisateur\Provider\Privilege\UtilisateurPrivileges;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @see \Application\Controller\UtilisateurController::indexAction()
 * @var User $utilisateur
 * @var Role[] $roles
 * @var Role[] $rolesAffectes
 * @var Role[] $rolesDisponibles
 */

$canAfficher    = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::AFFICHER));
$canAjouter     = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::AJOUTER));
$canStatus      = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::CHANGER_STATUS));
$canRole        = $this->isAllowed(UtilisateurPrivileges::getResourceId(UtilisateurPrivileges::MODIFIER_ROLE));

?>

<?php $this->headTitle($this->translate("Administration des utilisateurs")) ?>

<h1 class="page-header" > Administration des utilisateurs </h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<div class="main">

<a name="recherche"></a>
<h2> Recherche d'utilisateur et affectation de rôles </h2>

<form method='post' class="form-inline " style="margin-bottom:10px;">
    <?php
    $sas = new SearchAndSelect('utilisateur');
    $sas->setAttribute('placeholder','Recherchez un utilisateur');
    $sas->setAttribute('class', 'individu-finder');
    $sas->setAutocompleteSource($this->url('utilisateur-preecog/rechercher-utilisateur', [], [], true));
    echo $this->formControlGroup($sas, 'formSearchAndSelect');
    ?>
    <input type="submit" class="" value="Sélectionner l'utilisateur"/>
</form>

<?php if($canAjouter): ?>
<a name="ajout"></a>
<h2> Ajout d'un nouvel utilisateur </h2>

<form method='post' class="form-inline " style="margin-bottom:10px;">
    <?php
    $sas = new SearchAndSelect('ldap');
    $sas->setAttribute('placeholder','Recherchez un individu');
    $sas->setAttribute('class', 'individu-finder');
    $sas->setAutocompleteSource($this->url('utilisateur-preecog/rechercher-people', [], [], true));
    echo $this->formControlGroup($sas, 'formSearchAndSelect');
    ?>
    <input type="submit" class="" value="Ajouter l'utilisateur sélectionné"/>
</form>
<?php endif; ?>

<?php if($utilisateur !== null): ?>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2> Information sur l'utilisateur selectionné </h2>
        </div>
        <div class="panel-body">
            <div  class="pull-left">
                <dl>
                    <dt> Nom affiché dans l'application </dt>
                    <dd> <?php echo $utilisateur->getDisplayName();?> </dd>
                    <dt> Adresse électronique associé </dt>
                    <dd> <?php echo $utilisateur->getEmail();?> </dd>
                    <dt> Activité du compte </dt>
                    <dd>
                        <?php if ($utilisateur->getState() == 1): ?>
                            Actif
                        <?php else: ?>
                            Désactivé
                        <?php endif; ?>
                    </dd>
                </dl>
            </div>
            <div class="pull-right">
                <?php if ($canStatus) : ?>
                    <a href="<?php echo $this->url('utilisateur-preecog/changer-status', ['utilisateur' => $utilisateur->getId()], [], true); ?>"
                       class="btn btn-warning action">
                        <span class="glyphicon glyphicon-refresh"></span> Changer le status
                    </a>
                <?php endif; ?>

                <br/>

                <?php if ($canAjouter) : ?>
                <a href="<?php echo $this->url('utilisateur-preecog/effacer', ['utilisateur' => $utilisateur->getId()], [], true); ?>"
                   class="btn btn-danger action">
                    <span class="glyphicon glyphicon-remove"></span> Supprimer le compte
                </a>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            <h2> Information sur l'utilisateur selectionné </h2>
        </div>
        <div class="panel-body">

            <div class="col-md-6">
                <h3> Rôles affectés </h3>

                <?php foreach ($roles as $role) : ?>
                    <?php
                        $affecter = false;
                        foreach ($rolesDisponibles as $roleDisponible) {
                            if ($roleDisponible->getId() === $role->getId()) {
                                $affecter = true;
                                break;
                            }
                        }
                    ?>
                    <div class="cliquable remove-role" id="affecte_<?php echo $utilisateur->getId(); ?>_<?php echo $role->getId(); ?>"
                         style="<?php if ($affecter === true) echo 'display:none;'; ?>"
                    >
                        <?php if ($canRole): ?>
                            <span id="<?php echo $utilisateur->getId().'_'.$role->getId(); ?>"
                                  style="color:red;"
                                  class=" glyphicon glyphicon-minus-sign pointer">
                            </span>
                        <?php endif; ?>
                        <?php echo $role->getRoleId(); ?>
                    </div>
                <?php endforeach; ?>

            </div>
            <div class="col-md-6">
                <h3> Rôles disponibles </h3>

                <?php foreach ($roles as $role) : ?>
                    <?php
                        $affecter = false;
                        foreach ($rolesDisponibles as $roleDisponible) {
                            if ($roleDisponible->getId() === $role->getId()) {
                                $affecter = true;
                                break;
                            }
                        }
                    ?>
                    <div class="cliquable add-role" id="disponible_<?php echo $utilisateur->getId(); ?>_<?php echo $role->getId(); ?>"
                         style="<?php if ($affecter === false) echo 'display:none;'; ?>"
                    >
                        <?php if ($canRole): ?>
                        <span id="<?php echo $utilisateur->getId().'_'.$role->getId(); ?>"
                              style="color:green;"
                              class="glyphicon glyphicon-plus-sign pointer">
                        </span>
                        <?php endif; ?>
                        <?php echo $role->getRoleId(); ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>

</div>

<script>
    $(document).ready(function () {
        $(".remove-role").click(function () {
            let id = $(this).attr("id");
            let splits = id.split("_");
            let role = splits[2];
            let individu = splits[1];

            let url = "utilisateur/remove-role/" + individu + "/" + role;
            $("#affecte_" + individu + "_" + role).hide();
            $("#disponible_" + individu + "_" + role).show();

            $.ajax({
                type: "POST",
                url: url
            });
        });
    });
    $(document).ready(function () {
        $(".add-role").click(function () {
            let id = $(this).attr("id");
            let splits = id.split("_");
            let role = splits[2];
            let individu = splits[1];

            let url = "utilisateur/add-role/" + individu + "/" + role;
            $("#affecte_" + individu + "_" + role).show();
            $("#disponible_" + individu + "_" + role).hide();

            $.ajax({
                type: "POST",
                url: url
            });
        });
    });
</script>

<style>
    .cliquable {
        border: 1px solid lightgray;
        border-radius : 5px;
        margin: 0.25rem;
        padding: 0.25rem;
    }

    .cliquable:hover {
        background-color: lightyellow;
        cursor : pointer ;
    }
</style>