<?php

use FicheMetier\Entity\Db\Activite;
use FicheMetier\Entity\Db\FicheMetier;

/**
 * @see \FicheMetier\Controller\ActiviteController::afficherAction()
 * @var Activite $activite
 * @var FicheMetier[] $fichesmetiers
 */

?>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-4"> Libellé</dt>
            <dd class="col-md-8"> <?php echo $activite->getLibelle(); ?> </dd>
            <?php if ($activite->getDescription()) : ?>
                <dt class="col-md-4"> Description</dt>
                <dd class="col-md-8"> <?php echo $activite->getDescription(); ?> </dd>
            <?php endif; ?>
            <dt class="col-md-4"> Référence</dt>
            <dd class="col-md-8">
                <?php echo $activite->printReference(); ?>
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <?php echo $this->historiqueBloc($activite, ["genre" => "F"]); ?>
    </div>
</div>

<h2> Listing des fiches métiers incluants cette activité </h2>

<?php if (empty($fichesmetiers)): ?>
    Aucune fiche métier n'utilise cette activité
<?php else: ?>
    <ul>
        <?php foreach ($fichesmetiers as $fichemetier): ?>
            <li> <?php echo $fichemetier->getLibelle(); ?> </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
