<?php

use FicheMetier\Entity\Db\Activite;
use FicheMetier\Provider\Privilege\ActivitePrivileges;
use Referentiel\Entity\Db\Referentiel;

/**
 * @see \FicheMetier\Controller\ActiviteController::importerAction()
 * @var bool $displayCodeFonction
 * @var string $separateur
 * @var array $data
 * @var array $file
 * @var Activite[] $activites
 *
 * @var Referentiel[] $referentiels
 * @var string $filename
 * @var string $filepath
 *
 * @var string[] $info
 * @var string[] $warning
 * @var string[] $error
 */

$this->headTitle("Importation d'activité");

$canIndex = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::ACTIVITE_INDEX));
?>

<script>
    function reset() {
        console.log('click');
        window.location.href = "../activite/importer";
    }
</script>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Importation d'activité
        </h1>
    </div>
    <div class="col-md-4">
        <?php if ($canIndex) : ?>
            <?php /** @see \FicheMetier\Controller\ActiviteController::indexAction() */ ?>
            <a href="<?php echo $this->url('activite', [], [], true); ?>" class="btn btn-secondary float-end">
                <span class="icon icon-listing"></span>
                Accéder aux activités
            </a>
        <?php endif; ?>
    </div>
</div>

<br>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Importation des activités depuis un CSV</div>
            <div class="card-body">
                <form enctype="multipart/form-data"
                      action="<?php echo $this->url("activite/importer", ['path' => null], [], true); ?>"
                      method="post">
                    <?php if ($filepath !== null) : ?>
                        <span class="form-label">Fichier téléversé : </span><br>
                        <div style="padding:0.5rem;border:solid 1px lightgrey;width:100%; border-radius:6px;">
                            <div class='row'>
                                <div class='col-md-9'> <?php echo $filename; ?> </div>
                                <div class='col-md-3'>
                                    <div class='float-end'>
                                        <span class="action text-danger" style="cursor: pointer;" onclick="reset()">
                                            <span class='icon icon-unchecked' id='remove_file' title='Retirer le fichier'></span> Retirer
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="filepath" id="filepath" value="<?php echo $filepath; ?>">
                        <input type="hidden" name="filename" id="filename" value="<?php echo $filename; ?>">
                    <?php else : ?>
                        <label for="file">Fichier à importer <span class="icon icon-obligatoire"
                                                                   title="Champ obligatoire"></span></label>
                        <input type="file" name="file" id="file" class="form-control" accept=".csv"/>
                    <?php endif; ?>
                    <label for="referentiel"> Référentiel <span class="icon icon-obligatoire"
                                                                title="Champ obligatoire"></span> </label>
                    <select class="selectpicker show-tick form-control" id="referentiel" name="referentiel">
                        <option value="">Sélectionnez un référentiel</option>
                        <?php foreach ($referentiels as $referentiel): ?>
                            <option value="<?php echo $referentiel->getId(); ?>"
                                    <?php if (isset($data["referentiel"]) and $data["referentiel"] == $referentiel->getId()) : ?>
                                        selected
                                    <?php endif; ?>
                            >
                                <?php echo $referentiel->getLibelleCourt(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <br>
                    <label for="mode"> Mode de traitement <span class="icon icon-obligatoire"
                                                                title="Champ obligatoire"></span></label>
                    <select class="selectpicker show-tick form-control" id="mode" name="mode">
                        <option value="preview"
                                <?php if (isset($data["mode"]) and $data["mode"] === "preview") : ?>
                                    selected
                                <?php endif; ?>
                        >Prévisualisation
                        </option>
                        <option value="import"
                                <?php if (isset($data["mode"]) and $data["mode"] === "import") : ?>
                                    selected
                                <?php endif; ?>
                        >Importation
                        </option>
                    </select>
                    <br>
                    <button type='submit' class="btn btn-success">
                        <span class="icon icon-csv"></span>
                        Traiter le fichier
                    </button>

                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="alert alert-info">
            Le fichier csv doit être constitué des colonnes suivantes :
            <ul>
                <li> <code><?php echo Activite::ACTIVITE_HEADER_ID; ?></code> <span class="icon icon-obligatoire"></span> Identifiant de l'activité dans le référentiel</li>
                <li> <code><?php echo Activite::ACTIVITE_HEADER_LIBELLE; ?></code> <span class="icon icon-obligatoire"></span> le libellé de l'activité</li>
<!--                <li> <code>--><?php //echo Activite::ACTIVITE_HEADER_DESCRIPTION; ?><!--</code> la description de l'activité</li>-->
                <li><code><?php echo Activite::ACTIVITE_HEADER_CODES_EMPLOITYPE; ?></code> : la liste des codes des fiches métiers incluant l'activité,
                    <?php if ($displayCodeFonction) : ?>
                <li><code><?php echo Activite::ACTIVITE_HEADER_CODES_FONCTION; ?></code> : la liste des codes des "fonctions" incluant l'activité.</li>
                <?php endif; ?>
            </ul>

            <strong><u>Remarques :</u></strong>
            <ul>
                <li>L'intitulé des colonnes doit être exactement celui spécifié (majuscule et accent).</li>
                <li>Les colonnes obligatoires sont désignées par <span class="icon icon-obligatoire"></span>.</li>
                <li>L'ordre des colonnes n'a pas besoin d'être respecté.</li>
                <li>Le séparateur dans les listes est <code><?php echo $separateur; ?></code>.</li>
                <li>Le fichier doit être enregistré en <strong>CSV UTF8</strong>.</li>
            </ul>

            <?php if ($displayCodeFonction) : ?>
                <a href="<?php echo $this->url('home',[],['force_canonical' => true], true); ?>exemples/trame_csv/import_activites_codefonction.csv"><span class="icon icon-csv"></span>Télécharger la trame d'import des activités</a>
            <?php else: ?>
                <a href="<?php echo $this->url('home',[],['force_canonical' => true], true); ?>exemples/trame_csv/import_activites.csv"><span class="icon icon-csv"></span>Télécharger la trame d'import des activités</a>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php if (!empty($error)) : ?>
    <div class="alert alert-danger">
        <?php foreach ($error as $line) : ?>
            <?php echo $line ?> <br>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if (!empty($info)) : ?>
    <div class="alert alert-info">
        <?php foreach ($info as $line) : ?>
            <?php echo $line ?> <br>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if (!empty($warning)) : ?>
    <div class="alert alert-warning">
        <?php foreach ($warning as $line) : ?>
            <?php echo $line ?> <br>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<?php if (!empty($activites)): ?>
    <table class="table table-condensed" id="activites">
        <thead>
            <tr>
                <th class="col-md-10"> Libellé </th>
                <th class="col-md-2"> Codes </th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($activites as $activite) : ?>
            <tr>
                <td>
                    <?php echo $activite->getLibelle(); ?> <br>
                    <?php echo $activite->printReference(); ?>
                </td>
                <td>
                    <?php if ($activite->getCodesFicheMetier()) : ?>
                        <?php $codes = explode($separateur, $activite->getCodesFicheMetier()); ?>
                        <strong>Codes Emploi-Types :</strong>
                        <ul>
                            <?php foreach ($codes as $code) : ?>
                                <li> <?php echo $code; ?> </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <?php if ($displayCodeFonction AND $activite->getCodesFonction()) : ?>
                        <?php $codes = explode($separateur, $activite->getCodesFonction()); ?>
                        <strong>Codes Fonctions :</strong>
                        <ul>
                            <?php foreach ($codes as $code) : ?>
                                <li> <?php echo $code; ?> </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </td>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<script>
    <?php if (isset($data['referentiel'])): ?>
        let valueReferentiel = '<?php echo $data['referentiel']; ?>';
        $('select[name="referentiel"]').val(valueReferentiel);
    <?php endif; ?>
    <?php if (isset($data['mode'])): ?>
        let valueMode = '<?php echo $data['mode']; ?>';
        $('select[name="mode"]').val(valueMode);
    <?php endif; ?>

    $(function () {
        $('table#activites').DataTable({
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
        });
    });
</script>

<style>
    span#remove_file {
        color: var(--bs-danger);
    }
</style>
