<?php

use FicheMetier\Entity\Db\Activite;
use FicheMetier\Provider\Privilege\ActivitePrivileges;
use Referentiel\Entity\Db\Referentiel;

/**
 * @see \FicheMetier\Controller\ActiviteController::indexAction()
 * @var Activite[] $activites
 * @var Referentiel[] $referentiels
 * @var array $dictionnaire
 */

$this->headTitle("Activités");

$canActiviteAfficher = $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::ACTIVITE_AFFICHER));
$canActiviteAjouter =  $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::ACTIVITE_AJOUTER));
$canActiviteModifier =  $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::ACTIVITE_MODIFIER));
$canActiviteHistoriser =  $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::ACTIVITE_HISTORISER));
$canActiviteSupprimer =  $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::ACTIVITE_SUPPRIMER));
$canActiviteImporter =  $this->isAllowed(ActivitePrivileges::getResourceId(ActivitePrivileges::ACTIVITE_IMPORTER));

?>

<h1 class="page-header">
    Activités
</h1>


<!-- Filtre ----------------------------------------------------------------------------------------------------------->
<div class="card">
    <div class="card-header bg-default">
        <span class="icon icon-filtrer"></span>
        Filtre de recherche des activités
    </div>
    <div class="card-body">
        <form method="get" action="<?php echo $this->url('activite', [], [], true); ?>">
            <div class="row">
                <div class="col-md-10">
                    <!-- fitres -->
                    <div class="row">
                        <div class="col-md-4">
                            <label for="referentiel">Référentiel :</label>
                            <select id="referentiel" name="referentiel" class="form-control selectpicker" data-live-search="true">
                                <option value="">Peu importe</option>
                                <?php foreach ($referentiels as $referentiel) : ?>
                                    <option value="<?php echo $referentiel->getId(); ?>" data-content="<?php echo $referentiel->printLabel(); ?>"
                                            <?php if (isset($params['referentiel']) AND $params['referentiel'] == $referentiel->getId()) echo 'selected'; ?>
                                    >
                                        <?php echo $referentiel->getLibelleLong(); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="histo">Historisation :</label>
                            <select id="histo" name="histo" class="form-control selectpicker">
                                <option value="">Peu importe</option>
                                <option value="0" <?php if (isset($params['histo']) AND $params['histo'] == 0) echo 'selected'; ?>>Non historisée</option>
                                <option value="1" <?php if (isset($params['histo']) AND $params['histo'] == 1) echo 'selected'; ?>>Historisée</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-primary" id="filter">
                        <span class="icon icon-filtrer"></span>
                        Filtrer
                    </button>
                    <button class="btn btn-primary" id="clear">
                        <span class="icon icon-gommer"></span>
                        Remise à zéro
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<?php if ($canActiviteAjouter) : ?>
    <?php /** @see \FicheMetier\Controller\ActiviteController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('activite/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
   >
        <span class="icon icon-ajouter"></span>
        Ajouter une activité
    </a>
<?php endif; ?>
<?php if ($canActiviteImporter) : ?>
    <?php /** @see \FicheMetier\Controller\ActiviteController::importerAction() */ ?>
    <a href="<?php echo $this->url('activite/importer', [], [], true); ?>"
       class="btn btn-primary"
    >
        <span class="icon icon-csv"></span>
        Importer des activités depuis un csv
    </a>
<?php endif; ?>

<table class="table table-condensed" id="activites">
    <thead>
        <tr>
            <th class="col-md-6"> Libellé </th>
            <th class="col-md-2"> Référence </th>
            <th class="col-md-2"> #Fiches métiers </th>
            <th class="action col-md-2"> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($activites as $activite): ?>
        <tr <?php if ($activite->estHistorise()) echo " class='historise' "; ?> >
            <td data-column-id="Libellé">
                <?php echo $activite->getLibelle(); ?>
                <?php if ($activite->getDescription()): ?>
                    <span class="icon icon-info" title="<?php echo $activite->getDescription(); ?>" data-bs-toggle="tooltip" data-bs-html="true"></span>
                <?php endif; ?>
            </td>
            <td data-column-id="Référence">
                <?php echo $activite->printReference(); ?>
            </td>
            <td data-column-id="#Fiches métiers"> <?php echo $dictionnaire[$activite->getId()]??0; ?> </td>
            <td data-column-id="Action" class="action">
                <?php if ($canActiviteAfficher) : ?>
                    <?php /** @see \FicheMetier\Controller\ActiviteController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('activite/afficher', ['activite' => $activite->getId()], [], true); ?>"
                       class="action secondary ajax-modal">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canActiviteModifier) : ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\ActiviteController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('activite/modifier', ['activite' => $activite->getId()], [], true); ?>"
                       class="action primary ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canActiviteHistoriser): ?>
                    <br>
                    <?php if ($activite->estHistorise()) : ?>
                        <?php /** @see \FicheMetier\Controller\ActiviteController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('activite/restaurer', ['activite' => $activite->getId()], [], true);?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php else : ?>
                        <?php /** @see \FicheMetier\Controller\ActiviteController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('activite/historiser', ['activite' => $activite->getId()], [], true);?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canActiviteSupprimer): ?>
                    <br>
                    <?php /** @see \FicheMetier\Controller\ActiviteController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('activite/supprimer', ['activite' => $activite->getId()], [], true);?>"
                       class="action danger ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>

    </tbody>

</table>


<script>
    $(function(){
        $("#activites").DataTable({
            info: true,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [3], orderable: false }
            ]
        });
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $('button#clear').click(function(e) {
        e.preventDefault();
        window.location.href = '?';
    });
</script>