<?php

/**
 * @see \Carriere\Controller\FonctionTypeController::indexAction()
 * @var FonctionType[] $fonctionsTypes
 * @var FonctionTypeService $service
 */

use Carriere\Entity\Db\FonctionType;
use Carriere\Provider\Privilege\FonctiontypePrivileges;
use Carriere\Service\FonctionType\FonctionTypeService;

$this->headTitle("Code Fonction");

$canAfficher = $this->isAllowed(FonctiontypePrivileges::getResourceId(FonctiontypePrivileges::FONCTIONTYPE_AFFICHER));
$canAjouter = $this->isAllowed(FonctiontypePrivileges::getResourceId(FonctiontypePrivileges::FONCTIONTYPE_AJOUTER));
$canModifier = $this->isAllowed(FonctiontypePrivileges::getResourceId(FonctiontypePrivileges::FONCTIONTYPE_MODIFIER));
$canHistoriser = $this->isAllowed(FonctiontypePrivileges::getResourceId(FonctiontypePrivileges::FONCTIONTYPE_HISTORISER));
$canSupprimer = $this->isAllowed(FonctiontypePrivileges::getResourceId(FonctiontypePrivileges::FONCTIONTYPE_SUPPRIMER));

?>

<h1 class="page-header">
    Codes Fonctions
</h1>

<?php if($canAjouter) : ?>
    <?php /** @see \Carriere\Controller\FonctionTypeController::indexAction() */ ?>
    <a href="<?php echo $this->url('fonction-type/ajouter', [], [], true); ?>"
        class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un code fonction
    </a>
<?php endif; ?>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<table class="table table-condensed" id="fonctionstypes">
    <thead>
    <tr>
        <th class="col-md-2"> Code </th>
        <th class="col-md-8"> Libellé </th>
        <th class="col-md-2 action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($fonctionsTypes as $fonctionType) : ?>
        <tr <?php if ($fonctionType->estHistorise()) echo ' class="historise" '; ?> >
            <td data-column-id="Code"> <?php echo $fonctionType->getCode(); ?> </td>
            <td data-column-id="Libellé">
                <?php echo $fonctionType->getLibelle(); ?>
                <?php if ($fonctionType->getDescription()) : ?>
                    <span class="icon icon-info" title="<?php echo $fonctionType->getDescription(); ?>" data-bs-toggle="tooltip" data-bs-html="true"></span>
                <?php endif; ?>
            </td>
            <td class="action" data-column-id="Action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Carriere\Controller\FonctionTypeController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('fonction-type/afficher', ['fonction-type' => $fonctionType->getId()], [], true); ?>"
                       class="action secondary ajax-modal">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                <br>
                    <?php /** @see \Carriere\Controller\FonctionTypeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('fonction-type/modifier', ['fonction-type' => $fonctionType->getId()], [], true); ?>"
                       class="action primary ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($fonctionType->estNonHistorise()) : ?>
                        <?php /** @see \Carriere\Controller\FonctionTypeController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('fonction-type/historiser', ['fonction-type' => $fonctionType->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Carriere\Controller\FonctionTypeController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('fonction-type/restaurer', ['fonction-type' => $fonctionType->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \Carriere\Controller\FonctionTypeController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('fonction-type/supprimer', ['fonction-type' => $fonctionType->getId()], [], true); ?>"
                       class="action danger ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $("body").on("modification", function (event) {
        event.div.modal('hide');
        window.location.reload();
    });

    $(function () {
        $('table#fonctionstypes').DataTable({
            autoWidth: false,
            paging: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [2], orderable: false }
            ]
        });
    });
</script>