<?php

/** @see \Application\Controller\AgentHierarchieController::calculerAction()
 * @var AgentHierarchieCalculForm $form
 * @var Structure $structure
 * @var string $type
 * @var Agent[] $agents
 * @var array $superieurs
 * @var array $autorites
 */

use Application\Entity\Db\Agent;
use Application\Form\AgentHierarchieCalcul\AgentHierarchieCalculForm;
use Structure\Entity\Db\Structure;

$this->headTitle("Chaînes hiérarchiques calculées");

$listing = [];
if ($type === Agent::ROLE_SUPERIEURE) $listing = $superieurs;
if ($type === Agent::ROLE_AUTORITE) $listing = $autorites;
?>

<?php echo $this->form($form); ?>


<?php if (!empty($error)) : ?>
    <div class="alert alert-danger">
        <span class="icon icon-attention"></span>
        <?php echo implode('<br>', $error); ?>
    </div>
<?php else : ?>
    <?php if (!empty($warning)) : ?>
        <div class="alert alert-warning">
            <ul>
                <?php foreach ($warning as $item) : ?>
                    <li> <?php echo $item; ?> </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if (isset($structure)) : ?>
    <h2> Calcul des chaînes hiérarchiques pour
        <?php if ($structure->getNiv2() !== null) : ?>
            <?php echo $structure->getNiv2()->getLibelleCourt(); ?> >
        <?php endif; ?>
        <?php echo $structure->getLibelleLong(); ?></h2>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th>Agent</th>
            <th><?php echo $type; ?></th>
            <th>Période</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($agents as $agent): ?>
            <?php if (!empty($listing[$agent->getId()])) : ?>
                <?php foreach ($listing[$agent->getId()] as $responsable) : ?>
                    <tr>
                        <td> <?php echo $agent->getDenomination(); ?> </td>
                        <td>
                            <?php if ($type === Agent::ROLE_SUPERIEURE) : ?>
                                <?php echo $responsable->getSuperieur()->getDenomination(); ?>
                            <?php endif; ?>
                            <?php if ($type === Agent::ROLE_AUTORITE) : ?>
                                <?php echo $responsable->getAutorite()->getDenomination(); ?>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php echo ($responsable->getDateDebut()) ? $responsable->getDateDebut()->format('d/m/Y') : "---"; ?>
                            &rightarrow;
                            <?php echo ($responsable->getDateFin()) ? $responsable->getDateFin()->format('d/m/Y') : "---"; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<script>
    $('select').selectpicker();
</script>
