<?php

/**
 * @see \Application\Controller\AgentHierarchieController::importerAction()
 * @var string $title
 * @var AgentHierarchieImportationForm $form
 * @var string $type
 * @var string[] $error
 * @var string[] $warning
 * @var Agent[] $chaines
 */

use Application\Entity\Db\Agent;
use Application\Form\AgentHierarchieImportation\AgentHierarchieImportationForm;


?>

<?php echo $this->form($form); ?>

<?php if (!empty($error)) : ?>
    <div class="alert alert-danger">
        <span class="icon icon-attention"></span>
        <?php echo implode('<br>', $error); ?>
    </div>
<?php else : ?>

    <?php if (!empty($warning)) : ?>
    <div class="alert alert-warning">
        <ul>
        <?php foreach ($warning as $item) : ?>
            <li> <?php echo $item; ?> </li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

    <?php if (isset($chaines) AND $chaines !== []) : ?>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Agent </th>
            <th> <?php echo $type; ?> </th>
            <th> Date de début </th>
            <th> Date de fin </th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($chaines as [$agent, $responsable, $dateDebut, $dateFin]) : ?>
                <tr>
                    <td> <?php echo $agent->getDenomination(); ?> </td>
                    <td> <?php echo $responsable->getDenomination(); ?> </td>
                    <td> <?php echo ($dateDebut)?$dateDebut->format('d/m/Y'):"---"; ?> </td>
                    <td> <?php echo ($dateFin)?$dateFin->format('d/m/Y'):"---"; ?> </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<?php endif; ?>
