<?php

/**
 * @see \Application\Controller\AgentHierarchieController::importerAction()
 * @var string $title
 * @var AgentHierarchieImportationForm $form
 * @var string[] $error
 * @var string[] $warning
 * @var Agent[] $agents
 * @var array $array
 */

use Application\Entity\Db\Agent;
use Application\Form\AgentHierarchieImportation\AgentHierarchieImportationForm;


?>

<?php echo $this->form($form); ?>

<?php if (!empty($error)) : ?>
    <div class="alert alert-danger">
        <span class="icon icon-attention"></span>
        <?php echo implode('<br>', $error); ?>
    </div>
<?php else : ?>

    <?php if (!empty($warning)) : ?>
    <div class="alert alert-warning">
        <ul>
        <?php foreach ($warning as $item) : ?>
            <li> <?php echo $item; ?> </li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

    <?php if (isset($array)) : ?>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Agent </th>
            <th> Supérieur·es hiérachique·s </th>
            <th> Autorité·s hiérachique·s </th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($array as $line) : ?>
                <tr>
                    <?php
                        $agent = $line[0];
                        $superieurs = array_slice($line, 1, 3);
                        $autorites = array_slice($line, 4, 3);
                    ?>

                    <td>
                        <?php if ($agent !== null AND isset($agents[$agent])) : ?>
                            <?php echo $agents[$agent]->getDenomination(); ?>
                        <?php endif; ?>
                    </td>
                    <td>
                        <ul>
                            <?php foreach ($superieurs as $superieur) : ?>
                                <?php if ($superieur !== null AND isset($agents[$superieur])) : ?>
                                    <li> <?php echo $agents[$superieur]->getDenomination(); ?></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </td>
                    <td>
                        <ul>
                            <?php foreach ($autorites as $autorite) : ?>
                                <?php if ($autorite !== null AND isset($agents[$autorite])) : ?>
                                    <li> <?php echo $agents[$autorite]->getDenomination(); ?></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<?php endif; ?>
