<?php

/** @see \Application\Controller\AgentHierarchieController::indexAction() */

use Application\Entity\Db\Agent;

$this->headTitle("Gestion des chaînes hiérarchiques");
?>

<h1 class="page-header">
    Gestion des chaînes hiérarchiques
</h1>

<p class="lead">
    Deux moyens sont mises à disposition pour la gestion des chaînes hiérarchiques : un import depuis un csv ou un calcul exploitant les responsabilité de structure.
</p>

<h2> Importation des chaînes </h2>

Le format du CSV exploité est le suivant :
<code>agent_id ; reponsable_id ; date_debut; date_fin</code>. <br/>
Un·e agent·e peut avoir plusieurs lignes dans ce fichier si plusieurs responsables sont lié·es.

<div class="alert alert-warning">
    Tous les agent·es listé·es dans le fichier CSV verront leur chaîne hiérarchique historisée.
</div>

<?php /** @see \Application\Controller\AgentHierarchieController::importerAction() */ ?>
<a href="<?php echo $this->url('agent/hierarchie/importer', ['type' => Agent::ROLE_SUPERIEURE ], [], true); ?>"
   class="btn btn-primary ajax-modal"
>
    Importer les supérieur·es depuis csv
</a>

<?php /** @see \Application\Controller\AgentHierarchieController::importerAction() */ ?>
<a href="<?php echo $this->url('agent/hierarchie/importer', ['type' => Agent::ROLE_AUTORITE ], [], true); ?>"
   class="btn btn-primary ajax-modal"
>
    Importer les autorités depuis csv
</a>

<h2> Calcul des chaînes </h2>

Le calcul se fait à partir d'une structure et détermine pour chaque agent·e affecté·e ses supérieur·es et autorités hiérarchiques.
Les règles exploitées sont les suivantes :
<ul>
    <li>Les supérieur·es sont les responsables de la structure la plus proche de l'agent·e.</li>
    <li> Les autorités sont les responsables de la structure de niveau 2 de l'agent
        (ou de niveau 1 si les supérieur·es sont les responsables de la structure de niveau 2). </li>
</ul>
<div class="alert alert-warning">
    Tous les agent·es de la structure verront leur chaîne hiérarchique historisée.
</div>

<?php /** @see \Application\Controller\AgentHierarchieController::calculerAction() */ ?>
<a href="<?php echo $this->url('agent/hierarchie/calculer', [], [], true); ?>"
   class="btn btn-primary ajax-modal"
>
    Calculer depuis structure
</a>

<a href="" class="btn btn-warning disabled">
    Remise à zéro pour une structure
</a>

<h2> Saisie manuelle pour un·e agent </h2>

La saisie manuelle est réalisable depuis la fiche de l'agent.

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
