<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentAutorite;
use Application\Entity\Db\AgentSuperieur;
use Application\Provider\Parametre\GlobalParametres;

/** @see \Application\Controller\AgentHierarchieController::visualiserAction()
 * @var Agent $agent
 * @var string $type
 * @var AgentSuperieur[]|AgentAutorite[] $chaines
 **/

$appName = $this->parametreValue(GlobalParametres::TYPE, GlobalParametres::APP_NAME);

$revoques = [];
$historises = [];
$valides = [];
foreach ($chaines as $chaine) {
    if ($chaine->getSourceId() !== 'EMC2' and $chaine->estHistorise()) {
        $revoques[] = $chaine;
    } else {
        if ($chaine->estHistorise()) {
            $historises[] = $chaine;
        } else {
            $valides[] = $chaine;
        }
    }
}

?>

<div class="row">
    <div class="col-md-6">
        <h2> Chaînes valides</h2>

        <?php usort($valides, function (AgentSuperieur|AgentAutorite $a, AgentSuperieur|AgentAutorite $b) {
            if ($a->getDateDebut()->format('Y-m-d') !== $b->getDateDebut()->format('Y-m-d')) {
                return $a->getDateDebut() <=> $b->getDateDebut();
            }
            if ($a instanceof AgentSuperieur) return $a->getSuperieur()->getDenomination() <=> $b->getSuperieur()->getDenomination();
            return $a->getAutorite()->getDenomination() <=> $b->getAutorite()->getDenomination();
        });
        ?>

        <h3> Passée </h3>

        <ul>
            <?php foreach ($valides as $chaine) : ?>
                <?php if ($chaine->estFini()) : ?>
                    <?php $agent = $chaine->getAgent(); ?>
                    <?php $hierarchie = ($type === 'superieur') ? $chaine->getSuperieur() : $chaine->getAutorite(); ?>
                    <li>
                        <span class="badge"><?php echo $chaine->getSourceId(); ?></span>
                        <?php echo $hierarchie->getDenomination(true); ?>
                        (<?php echo ($chaine->getDateDebut()) ? $chaine->getDateDebut()->format('d/m/Y') : "---"; ?>
                        &RightArrow;
                        <?php echo ($chaine->getDateFin()) ? $chaine->getDateFin()->format('d/m/Y') : "---"; ?>)
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>

        <h3> En cours </h3>

        <ul>
            <?php foreach ($valides as $chaine) : ?>
                <?php if ($chaine->estEnCours()) : ?>
                    <?php $agent = $chaine->getAgent(); ?>
                    <?php $hierarchie = ($type === 'superieur') ? $chaine->getSuperieur() : $chaine->getAutorite(); ?>
                    <li>
                        <span class="badge"><?php echo $chaine->getSourceId(); ?></span>
                        <?php echo $hierarchie->getDenomination(true); ?>
                        (<?php echo ($chaine->getDateDebut()) ? $chaine->getDateDebut()->format('d/m/Y') : "---"; ?>
                        &RightArrow;
                        <?php echo ($chaine->getDateFin()) ? $chaine->getDateFin()->format('d/m/Y') : "---"; ?>)
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>

        <h3> À venir </h3>

        <ul>
            <?php foreach ($valides as $chaine) : ?>
                <?php if (!$chaine->estCommence()) : ?>
                    <?php $agent = $chaine->getAgent(); ?>
                    <?php $hierarchie = ($type === 'superieur') ? $chaine->getSuperieur() : $chaine->getAutorite(); ?>
                    <li>
                        <span class="badge"><?php echo $chaine->getSourceId(); ?></span>
                        <?php echo $hierarchie->getDenomination(true); ?>
                        (<?php echo ($chaine->getDateDebut()) ? $chaine->getDateDebut()->format('d/m/Y') : "---"; ?>
                        &RightArrow;
                        <?php echo ($chaine->getDateFin()) ? $chaine->getDateFin()->format('d/m/Y') : "---"; ?>)
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>


    </div>
    <div class="col-md-6">

        <h2> Chaînes revoquées</h2><span class="icon icon-info" title="Chaînes importées depuis le SIRH qui ont été manuellement révoquées depuis <?php echo $appName; ?>" style="cursor: help"> À propos de chaînes révoquées</span>
        <?php usort($revoques, function (AgentSuperieur|AgentAutorite $a, AgentSuperieur|AgentAutorite $b) {
            if ($a->getDateDebut()->format('Y-m-d') !== $b->getDateDebut()->format('Y-m-d')) {
                return $a->getDateDebut() <=> $b->getDateDebut();
            }
            if ($a instanceof AgentSuperieur) return $a->getSuperieur()->getDenomination() <=> $b->getSuperieur()->getDenomination();
            return $a->getAutorite()->getDenomination() <=> $b->getAutorite()->getDenomination();
        });
        ?>

        <ul>
            <?php foreach ($revoques as $chaine) : ?>
                <?php $agent = $chaine->getAgent(); ?>
                <?php $hierarchie = ($type === 'superieur') ? $chaine->getSuperieur() : $chaine->getAutorite(); ?>
                <li>
                    <span class="badge"><?php echo $chaine->getSourceId(); ?></span>
                    <?php echo $hierarchie->getDenomination(true); ?>
                    (<?php echo ($chaine->getDateDebut()) ? $chaine->getDateDebut()->format('d/m/Y') : "---"; ?>
                    &RightArrow;
                    <?php echo ($chaine->getDateFin()) ? $chaine->getDateFin()->format('d/m/Y') : "---"; ?>)
                    <br>
                    <em>revoquée le <?php echo $chaine->getHistoDestruction()->format('d/m/Y'); ?>
                        par <?php echo $chaine->getHistoDestructeur()->getDisplayName(); ?></em>
                </li>
            <?php endforeach; ?>
        </ul>

        <h2> Chaînes annulées</h2>
        <?php usort($historises, function (AgentSuperieur|AgentAutorite $a, AgentSuperieur|AgentAutorite $b) {
            if ($a->getDateDebut()->format('Y-m-d') !== $b->getDateDebut()->format('Y-m-d')) {
                return $a->getDateDebut() <=> $b->getDateDebut();
            }
            if ($a instanceof AgentSuperieur) return $a->getSuperieur()->getDenomination() <=> $b->getSuperieur()->getDenomination();
            return $a->getAutorite()->getDenomination() <=> $b->getAutorite()->getDenomination();
        });
        ?>

        <ul>
            <?php foreach ($historises as $chaine) : ?>
                <?php $agent = $chaine->getAgent(); ?>
                <?php $hierarchie = ($type === 'superieur') ? $chaine->getSuperieur() : $chaine->getAutorite(); ?>
                <li>
                    <span class="badge"><?php echo $chaine->getSourceId(); ?></span>
                    <?php echo $hierarchie->getDenomination(true); ?>
                    (<?php echo ($chaine->getDateDebut()) ? $chaine->getDateDebut()->format('d/m/Y') : "---"; ?>
                    &RightArrow;
                    <?php echo ($chaine->getDateFin()) ? $chaine->getDateFin()->format('d/m/Y') : "---"; ?>)
                    <br>
                    <em>annulée le <?php echo $chaine->getHistoDestruction()->format('d/m/Y'); ?>
                        par <?php echo $chaine->getHistoDestructeur()->getDisplayName(); ?></em>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

