<?php

/**
 * @see RessourceRhController::afficherMissionSpecifiqueAction()
 *
 * @var string $title
 * @var MissionSpecifique $mission
 */

use Application\Controller\RessourceRhController;
use Application\Entity\Db\MissionSpecifique;

?>

<dl>
    <dt> Libellé </dt>
    <dd> <?php echo $mission->getLibelle(); ?> </dd>
    <dt> Type </dt>
    <dd> <?php echo ($mission->getType())?$mission->getType()->getLibelle():"Aucun"; ?> </dd>
    <dt> Thème </dt>
    <dd> <?php echo ($mission->getTheme())?$mission->getTheme()->getLibelle():"Aucun"; ?> </dd>
    <dt> Dernière modification </dt>
    <dd>
        <?php echo $mission->getHistoModificateur()->getDisplayName(); ?>
        <br/>
        <?php echo $mission->getHistoModification()->format('d/m/Y à H:i:s'); ?>
    </dd>
    <dt>
        Liste des Agents
        <span class="badge"> <?php echo count($mission->getAffectations()); ?></span>
    </dt>
    <dd>
        <ul>
            <?php foreach($mission->getAffectations() as $affectation) : ?>
                <li> <?php echo $affectation->getAgent()->getDenomination(); ?> </li>
            <?php endforeach; ?>
        </ul>
    </dd>
</dl>

