<?php

/**
 * @var Application\Entity\Db\Metier[] $metiers
 */

?>

<h1 class="page-header"> Cartographie des métiers </h1>

<div class="main">

    EXPORT CSV!!!

    <table class="table table-condensed">
        <thead>
            <tr>
                <th> Famille professionnelle </th>
                <th> Domaine </th>
                <th> Métier </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($metiers as $metier) : ?>
            <tr>
                <td> <?php echo $metier->getFamille()->getLibelle(); ?></td>
                <td> <?php echo $metier->getDomaine()->getLibelle(); ?></td>
                <td> <?php echo $metier->getLibelle(); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
