<?php

/**
 * @see \Application\Controller\RessourceRhController::cartographieAction()
 * @var array $results
 */

use Application\Provider\Privilege\MetierPrivileges;

$canCarto = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_CARTOGRAPHIE));
$this->headTitle('Cartographie des métiers');
?>

<h1 class="page-header"> Cartographie des métiers </h1>

<div class="main">

    <div class="row">

        <div class="col-md-5" >
            <?php if ($canCarto) : ?>
                <a class="btn btn-primary action "
                   href="<?php echo $this->url('ressource-rh/cartographie/export', [], [], true); ?>"
                >
                    Export de la cartographie
                </a>
            <?php endif ; ?>
        </div>

        <div class="col-md-5 pull-right">
        <div class="alert alert-warning">
            <strong>Attention :</strong> La cartographie se base sur les métiers. Par conséquent, une fonction  (resp. un domaine ou une famille) vide ne sera pas cartographié.
        </div>
        </div>

    </div>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th> Famille professionnelle </th>
                <th> Fonction </th>
                <th> Domaine </th>
                <th> Métier </th>
                <th> Emploi-Type </th>
                <th> #Fiche métier</th>
<!--                <th> #Fiche poste </th>-->
            </tr>
        </thead>
        <tbody>
            <?php foreach($results as $result) : ?>


            <tr>
                <td> <?php echo $result['famille']; ?> </td>
                <td> <?php echo $result['fonction']; ?> </td>
                <td> <?php echo $result['domaine']; ?> </td>
                <td> <?php echo $result['metier']; ?> </td>
                <td> <?php echo $result['emploi-type']; ?> </td>
                <td> <?php echo $result['nbFiche']; ?> </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
