<?php

/**
 * @var Correspondance[] $correspondances_actives
 * @var Correspondance[] $correspondances_historisees
 */

use Application\Entity\Db\Correspondance;

$this->headTitle('Index des correpondances');

?>

<div class="row">
    <div class="col-md-6">
        <h1 class="page-header">
            Correspondances
            <span class="badge">
                <?php echo count($correspondances_actives) + count($correspondances_historisees); ?>
            </span>
        </h1>
    </div>
    <div class="pull-right col-md-5 alert alert-info">
        <span class="icon synchoniser"></span>
        Les correspondances sont synchronisées depuis Octopus.
    </div>
</div>


<div class="main">
    <h2>
        Liste des catégorie actives
        <span class="badge">
        <?php echo count($correspondances_actives); ?>
    </span>
    </h2>

    <?php if (count($correspondances_actives) > 0) : ?>
        <table class="table table-condensed">
            <thead>
            <tr>
                <th> Categorie </th>
                <th> Libellé court </th>
                <th> Libellé long </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($correspondances_actives as $correspondance) : ?>
                <tr>
                    <td> <?php echo $correspondance->getCategorie(); ?> </td>
                    <td> <?php echo $correspondance->getLibelleCourt(); ?> </td>
                    <td> <?php echo $correspondance->getLibelleLong(); ?> </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

<div class="main">
    <h2>
        Liste des catégorie historisées
        <span class="badge">
        <?php echo count($correspondances_historisees); ?>
    </span>
    </h2>

    <?php if (count($correspondances_historisees) > 0) : ?>
        <table class="table table-condensed">
            <thead>
            <tr>
                <th> Categorie </th>
                <th> Libellé court </th>
                <th> Libellé long </th>
                <th> Historisation </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($correspondances_historisees as $correspondance) : ?>
                <tr>
                    <td> <?php echo $correspondance->getCategorie(); ?> </td>
                    <td> <?php echo $correspondance->getLibelleCourt(); ?> </td>
                    <td> <?php echo $correspondance->getLibelleLong(); ?> </td>
                    <td> <?php echo $correspondance->getHisto(); ?> </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>