<?php

/**
 * @var \Application\Entity\Db\Domaine[] $domaines
 */

use Application\Provider\Privilege\RessourceRhPrivileges;

$this->headTitle('Index des domaines');

$canAjouterRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::AJOUTER));
$canEditerRessource     = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::MODIFIER));
$canEffacerRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::EFFACER));

?>

<h1 class="page-header">
    Index des domaines
</h1>

<div class="main">
    <div class="col-md-8">
        <h2>
            Liste des domaines
            <span class="badge">
            <?php echo count($domaines); ?>
        </span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/domaine/ajouter', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un domaine
            </a>
        <?php endif;?>
    </div>
    <?php if (count($domaines) > 0) : ?>
        <table class="table table-condensed">
            <thead>
            <tr>
                <th> Id </th>
                <th> Libelle </th>
                <th class="action"> Action </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($domaines as $domaine) : ?>
                <tr>
                    <td> <?php echo $domaine->getId(); ?> </td>
                    <td> <?php echo $domaine->getLibelle(); ?> </td>
                    <td>
                        <?php if ($canEditerRessource) : ?>
                            <a href="<?php echo $this->url('ressource-rh/domaine/modifier', ['domaine' => $domaine->getId()], [], true); ?>"
                               data-event="modification"
                               class="ajax-modal"
                            >
                                <span class="icon editer" title="Éditer le domaine"></span></a>
                        <?php else : ?>
                                <span class="icon editer" style="color: lightgrey;"></span>
                        <?php endif; ?>
                        <?php if ($canEffacerRessource) : ?>
                            <a href="<?php echo $this->url('ressource-rh/domaine/supprimer', ['domaine' => $domaine->getId()], [], true); ?>" >
                                <span class="icon detruire" title="Effacer le domaine"></span></a>
                            <?php else : ?>
                                <span class="icon detruire" style="color: lightgrey;"></span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
