<?php

/**
 * @var \Application\Entity\Db\AgentStatus[] $status
 * @var \Application\Entity\Db\Corps[] $corps
 * @var \Application\Entity\Db\Grade[] $grades
 */

use Application\Provider\Privilege\RessourceRhPrivileges;

$this->headTitle('Index des corps, grades et status des agents');

$canAjouterRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::AJOUTER));
$canEditerRessource     = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::MODIFIER));
$canEffacerRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::EFFACER));

?>

<h1 class="page-header">
    Index des corps, grades et status des agents
</h1>

<a href="<?php echo $this->url('ressource-rh', [], ['fragment' => 'status']); ?>" class="btn btn-primary action">Status</a>
<a href="<?php echo $this->url('ressource-rh', [], ['fragment' => 'corps']); ?>" class="btn btn-primary action">Corps</a>
<a href="<?php echo $this->url('ressource-rh', [], ['fragment' => 'grade']); ?>" class="btn btn-primary action">Grade</a>

<div class="main">

    <a name="status"></a>
    <div class="col-md-8">
        <h2>
            Status des agents
            <span class="badge">
                <?php echo count($status); ?>
            </span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a
                href="<?php echo $this->url('ressource-rh/agent-status/creer', [], [], true); ?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un status
            </a>
        <?php endif; ?>
    </div>
    <?php if (count($status) > 0) : ?>
        <table class="table table-condensed">
            <thead>
            <tr>
                <th> Id </th>
                <th> Libelle </th>
                <th class="action"> Action </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($status as $item) : ?>
                <tr>
                    <td> <?php echo $item->getId(); ?> </td>
                    <td> <?php echo $item->getLibelle(); ?> </td>
                    <td>
                        <?php if ($canEditerRessource) : ?>
                            <a href="<?php echo $this->url('ressource-rh/agent-status/modifier', ['id' => $item->getId()], [], true); ?>"
                               data-event="modification"
                               class="ajax-modal"
                            >
                                <span class="icon editer" title="Éditer le status"></span></a>
                        <?php else : ?>
                                <span class="icon editer" style="color:lightgrey;"></span>
                        <?php endif; ?>

                        <?php if ($canEffacerRessource) : ?>
                            <a href="<?php echo $this->url('ressource-rh/agent-status/effacer', ['id' => $item->getId()], [], true); ?>" >
                                <span class="icon detruire" title="Effacer le status"></span></a>
                        <?php else : ?>
                            <span class="icon detruire" style="color:lightgrey;"></span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

<div class="main">
    <a name="corps"></a>
    <div class="col-md-8">
        <h2>
            Liste des corps
            <span class="badge">
            <?php echo count($corps); ?>
        </span>
        </h2>
    </div>

    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/corps/creer', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un corps
            </a>
        <?php endif;?>
    </div>

    <br/>

    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Id</th>
            <th> Code</th>
            <th> Libelle</th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($corps as $corp): ?>
            <tr>
                <td> <?php echo $corp->getId(); ?> </td>
                <td> <?php echo $corp->getCode(); ?> </td>
                <td> <?php echo $corp->getLibelle(); ?> </td>
                <td>
                    <?php if ($canEditerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/corps/modifier', ['id' => $corp->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Éditer le corps"></span></a>
                    <?php else : ?>
                            <span class="icon editer" style="color: lightgrey;"></span>
                    <?php endif; ?>
                    <?php if ($canEffacerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/corps/effacer', ['id' => $corp->getId()], [], true); ?>">
                            <span class="icon detruire"  title="Supprimer le corps"></span></a>
                    <?php else : ?>
                            <span class="icon detruire" style="color: lightgrey;"></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>

<div class="main">
    <a name="grade"></a>
    <div class="col-md-8">
        <h2>
            Liste des grades
            <span class="badge">
            <?php echo count($grades); ?>
        </span>
        </h2>
    </div>

    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/grade/ajouter', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un grade
            </a>
        <?php endif;?>
    </div>

    <br/>

    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Id</th>
            <th> Corps</th>
            <th> Libelle</th>
            <th> Progression</th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($grades as $grade): ?>
            <tr>
                <td> <?php echo $grade->getId(); ?> </td>
                <td> <?php echo $grade->getCorps()->getLibelle(); ?> </td>
                <td> <?php echo $grade->getLibelle(); ?> </td>
                <td> <?php echo $grade->getRang(); ?> </td>
                <td>
                    <?php if ($canEditerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/grade/modifier', ['grade' => $grade->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Éditer le grade"></span></a>
                    <?php else : ?>
                            <span class="icon editer" style="color: lightgrey;"></span>
                    <?php endif; ?>
                    <?php if ($canEffacerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/grade/supprimer', ['grade' => $grade->getId()], [], true); ?>">
                            <span class="icon detruire"  title="Supprimer le grade"></span></a>
                    <?php else : ?>
                        <span class="icon detruire" style="color: lightgrey;"></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>



<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
