<?php

/**
 * @var Application\Entity\Db\Corps[] $corps
 */

use Application\Entity\Db\Grade;
use Application\Provider\Privilege\RessourceRhPrivileges;

$this->headTitle('Index des corps et grades');

$canAjouterRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::AJOUTER));
$canEditerRessource     = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::MODIFIER));
$canEffacerRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::EFFACER));

?>

<h1 class="page-header">
    Index des corps et des grades
</h1>

<div class="main">
    <a name="corps"></a>
    <div class="col-md-8">
        <h2>
            Liste des corps et des grades associés
            <span class="badge">
            <?php echo count($corps); ?>
        </span>
        </h2>
    </div>

    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/corps/creer', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un corps
            </a>
        <?php endif;?>

        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/grade/ajouter', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un grade
            </a>
        <?php endif;?>
    </div>

    <br/>

    <table class="table table-condensed">
        <thead>
        <tr>
            <th colspan="2"> Libelle</th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($corps as $corp): ?>
            <tr>
                <td colspan="2"> <?php echo $corp->getLibelle(); ?> (<?php echo $corp->getCode(); ?>)</td>

                <td>
                    <?php if ($canEditerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/corps/modifier', ['id' => $corp->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Éditer le corps"></span></a>
                    <?php else : ?>
                            <span class="icon editer" style="color: lightgrey;"></span>
                    <?php endif; ?>
                    <?php if ($canEffacerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/corps/effacer', ['id' => $corp->getId()], [], true); ?>">
                            <span class="icon detruire"  title="Supprimer le corps"></span></a>
                    <?php else : ?>
                            <span class="icon detruire" style="color: lightgrey;"></span>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td></td>
                <td colspan="2">
                    <table class="table table-condensed">
                        <thead>
                            <th>Libellé</th>
                            <th>Progression</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            <?php
                                $grades = $corp->getGrades();
                                usort($grades, function(Grade $a, Grade $b) { return $a->getRang() > $b->getRang();});
                            ?>
                            <?php foreach($grades as $grade) : ?>
                                <tr>
                                    <td> <?php echo $grade->getLibelle(); ?> </td>
                                    <td> <?php echo $grade->getRang(); ?> </td>
                                    <td>
                                        <?php if ($canEditerRessource) : ?>
                                            <a href="<?php echo $this->url('ressource-rh/grade/modifier', ['grade' => $grade->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                                                <span class="icon editer" title="Éditer le grade"></span></a>
                                        <?php else : ?>
                                            <span class="icon editer" style="color: lightgrey;"></span>
                                        <?php endif; ?>
                                        <?php if ($canEffacerRessource) : ?>
                                            <a href="<?php echo $this->url('ressource-rh/grade/supprimer', ['grade' => $grade->getId()], [], true); ?>">
                                                <span class="icon detruire"  title="Supprimer le grade"></span></a>
                                        <?php else : ?>
                                            <span class="icon detruire" style="color: lightgrey;"></span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
