<?php

/**
 * @var \Application\Entity\Db\Metier[] $metiers
 * @var \Application\Entity\Db\MetierFamille[] $familles
 */

use Application\Provider\Privilege\RessourceRhPrivileges;

$this->headTitle('Index des métiers et familles de métiers');

$canAjouterRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::AJOUTER));
$canEditerRessource     = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::MODIFIER));
$canEffacerRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::EFFACER));

?>

<h1 class="page-header">
    Index des métiers et familles professionnelles
</h1>

<a href="<?php echo $this->url('ressource-rh', [], ['fragment' => 'metier']); ?>" class="btn btn-primary action">Métier</a>
<a href="<?php echo $this->url('ressource-rh', [], ['fragment' => 'famille']); ?>" class="btn btn-primary action">Famille professionnelle</a>


<div class="main">
    <a name="metier"></a>
    <div class="col-md-8">
        <h2>
            Liste des métiers
            <span class="badge">
            <?php echo count($metiers); ?>
        </span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/metier/creer', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un métier
            </a>
        <?php endif;?>
    </div>
    <br/>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Id</th>
            <th> Libelle </th>
            <th> Famille </th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($metiers as $metier): ?>
            <tr>
                <td> <?php echo $metier->getId(); ?> </td>
                <td> <?php echo $metier->getLibelle(); ?> </td>
                <td> <?php echo $metier->getFamille()->getLibelle(); ?> </td>
                <td>
                    <?php if ($canEditerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/metier/modifier', ['id' => $metier->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Éditer l'application"></span></a>
                    <?php else : ?>
                            <span class="icon editer" style="color: lightgrey;"></span>
                    <?php endif; ?>
                    <?php if ($canEffacerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/metier/effacer', ['id' => $metier->getId()], [], true); ?>">
                            <span class="icon detruire"  title="Supprimer l'application"></span></a>
                    <?php else : ?>
                        <span class="icon detruire" style="color: lightgrey;"></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="main">
    <a name="famille"></a>
    <div class="col-md-8">
        <h2>
            Liste des familles professionnelles
            <span class="badge">
            <?php echo count($familles); ?>
        </span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/famille/creer', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter une famille professionnelle
            </a>
        <?php endif;?>
    </div>
    <br/>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Id</th>
            <th> Libelle </th>
            <th> #metiers </th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($familles as $famille): ?>
            <tr>
                <td> <?php echo $famille->getId(); ?> </td>
                <td> <?php echo $famille->getLibelle(); ?> </td>
                <td>
                    <?php echo count($famille->getMetiers()); ?>
                </td>
                <td>
                    <?php if ($canEditerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/famille/modifier', ['id' => $famille->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Éditer l'application"></span></a>
                    <?php else : ?>
                        <span class="icon editer" style="color: lightgrey;"></span>
                    <?php endif; ?>
                    <?php if ($canEffacerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/famille/effacer', ['id' => $famille->getId()], [], true); ?>">
                            <span class="icon detruire"  title="Supprimer l'application"></span></a>
                    <?php else : ?>
                        <span class="icon detruire" style="color: lightgrey;"></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
