<?php

/**
 * @var FamilleProfessionnelle[] $familles
 * @var Domaine[] $domaines
 * @var Fonction[] $fonctions
 * @var Metier[] $metiers
 */

use Application\Entity\Db\Domaine;
use Application\Entity\Db\FamilleProfessionnelle;
use Application\Entity\Db\Fonction;
use Application\Entity\Db\Metier;
use Application\Provider\Privilege\RessourceRhPrivileges;

$this->headTitle('Métiers, familles professionnelles et domaines');

$canAjouterRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::AJOUTER));
$canEditerRessource     = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::MODIFIER));
$canEffacerRessource    = $this->isAllowed(RessourceRhPrivileges::getResourceId(RessourceRhPrivileges::EFFACER));

?>

<h1 class="page-header">
    Métiers, familles professionnelles et domaines
</h1>

<a href="<?php echo $this->url('ressource-rh', [], ['fragment' => 'famille']); ?>" class="btn btn-primary action">Famille professionnelle</a>
<a href="<?php echo $this->url('ressource-rh', [], ['fragment' => 'domaine']); ?>" class="btn btn-primary action">Domaine</a>
<!--<a href="--><?php //echo $this->url('ressource-rh', [], ['fragment' => 'fonction']); ?><!--" class="btn btn-primary action">Fonction</a>-->
<a href="<?php echo $this->url('ressource-rh', [], ['fragment' => 'metier']); ?>" class="btn btn-primary action">Métier</a>

<div class="main">
    <a name="famille"></a>
    <div class="col-md-8">
        <h2>
            Liste des familles professionnelles
            <span class="badge">
            <?php echo count($familles); ?>
        </span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/famille/creer', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter une famille professionnelle
            </a>
        <?php endif;?>
    </div>
    <br/>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Libelle </th>
            <th> #domaines </th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($familles as $famille): ?>
            <tr>
                <td> <?php echo $famille->getLibelle(); ?> </td>
                <td>
                    <?php echo count($famille->getDomaines()); ?>
                </td>
                <td>
                    <?php if ($canEditerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/famille/modifier', ['id' => $famille->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Modifier l'application"></span></a>
                    <?php else : ?>
                        <span class="icon editer" style="color: lightgrey;"></span>
                    <?php endif; ?>
                    <?php if ($canEffacerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/famille/effacer', ['id' => $famille->getId()], [], true); ?>">
                            <span class="icon detruire"  title="Supprimer l'application"></span></a>
                    <?php else : ?>
                        <span class="icon detruire" style="color: lightgrey;"></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<br/>

<div class="main">
    <a name="domaine"></a>
    <div class="col-md-8">
        <h2>
            Liste des domaines
            <span class="badge">
            <?php echo count($domaines); ?>
        </span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/domaine/ajouter', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un domaine
            </a>
        <?php endif;?>
    </div>
    <br/>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Libelle </th>
            <th> Famille professionnelle </th>
            <th> #metier </th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($domaines as $domaine): ?>
            <tr>
                <td> <?php echo $domaine->getLibelle(); ?> </td>
                <td> <?php echo $domaine->getFamille(); ?> </td>
                <td>
                    <?php echo count($domaine->getMetiers()); ?>
                </td>
                <td>
                    <?php if ($canEditerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/domaine/modifier', ['domaine' => $domaine->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Modifier le domaine"></span></a>
                    <?php else : ?>
                        <span class="icon editer" style="color: lightgrey;"></span>
                    <?php endif; ?>
                    <?php if ($canEffacerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/domaine/supprimer', ['domaine' => $domaine->getId()], [], true); ?>">
                            <span class="icon detruire"  title="Supprimer le domaine"></span></a>
                    <?php else : ?>
                        <span class="icon detruire" style="color: lightgrey;"></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<br/>

<!--<div class="main">-->
<!--    <a name="fonction"></a>-->
<!--    <div class="col-md-8">-->
<!--        <h2>-->
<!--            Liste des fonctions-->
<!--            <span class="badge">-->
<!--            --><?php //echo count($fonctions); ?>
<!--        </span>-->
<!--        </h2>-->
<!--    </div>-->
<!--    <div class="pull-right">-->
<!--        <div class="alert alert-info"><em> Importer depuis Octopus</em></div>-->
<!--    </div>-->
<!--    <br/>-->
<!--    <table class="table table-condensed">-->
<!--        <thead>-->
<!--        <tr>-->
<!--            <th> Id </th>-->
<!--            <th> Parent </th>-->
<!--            <th> Code </th>-->
<!--            <th> Libellés </th>-->
<!--            <th> Domaine </th>-->
<!--            <th> #métier </th>-->
<!--            <th> Action </th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--        --><?php //foreach($fonctions as $fonction) : ?>
<!--            <tr>-->
<!--                <td> --><?php //echo $fonction->getId(); ?><!-- </td>-->
<!--                <td> --><?php //echo ($fonction !== $fonction->getParent())?$fonction->getParent()->getId():""; ?><!-- </td>-->
<!--                <td> --><?php //echo $fonction->getCode(); ?><!-- </td>-->
<!--                <td>-->
<!--                    <ul>-->
<!--                        --><?php //foreach($fonction->getLibelles() as $libelle) : ?>
<!--                            <li>-->
<!--                                <span class="badge" --><?php //if ($libelle->getDefaut() === 'O') echo 'style="background-color:green;"'; ?><!-- >-->
<!--                                    --><?php //echo $libelle->getGenre(); ?>
<!--                                </span>-->
<!--                                --><?php //echo $libelle->getLibelle(); ?>
<!--                            </li>-->
<!--                        --><?php //endforeach; ?>
<!--                    </ul>-->
<!--                </td>-->
<!--                <td> --><?php //echo $fonction->getDomaine(); ?><!-- </td>-->
<!--                <td> --><?php //echo count($fonction->getMetiers()); ?><!-- </td>-->
<!--                <td>-->
<!--                    --><?php //if ($canEditerRessource) : ?>
<!--                        <a href="--><?php //echo $this->url('ressource-rh/fonction/modifier', ['fonction' => $fonction->getId()], [], true); ?><!--"  class="ajax-modal" data-event="modification">-->
<!--                            <span class="icon editer" title="Modifier l'application"></span></a>-->
<!--                    --><?php //else : ?>
<!--                        <span class="icon editer" style="color: lightgrey;"></span>-->
<!--                    --><?php //endif; ?>
<!--                </td>-->
<!--            </tr>-->
<!--        --><?php //endforeach; ?>
<!--        </tbody>-->
<!--    </table>-->
<!--</div>-->
<!---->
<!--<br/>-->

<div class="main">
    <a name="metier"></a>
    <div class="col-md-8">
        <h2>
            Liste des métiers
            <span class="badge">
            <?php echo count($metiers); ?>
        </span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterRessource) : ?>
            <a href="<?php echo $this->url('ressource-rh/metier/creer', [], [], true);?>"
               class="btn btn-primary action ajax-modal"
               data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter un métier
            </a>
        <?php endif;?>
    </div>
    <br/>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th> Libelle </th>
            <th> Domaine </th>
            <th> Fonction </th>
            <th class="action"> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($metiers as $metier): ?>
            <tr>
                <td> <?php echo $metier->getLibelle(); ?> </td>
                <td> <?php echo $metier->getDomaine(); ?> </td>
                <td> <?php echo $metier->getFonction(); ?> </td>
                <td>
                    <?php if ($canEditerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/metier/modifier', ['id' => $metier->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                            <span class="icon editer" title="Modifier l'application"></span></a>
                    <?php else : ?>
                            <span class="icon editer" style="color: lightgrey;"></span>
                    <?php endif; ?>
                    <?php if ($canEffacerRessource) : ?>
                        <a href="<?php echo $this->url('ressource-rh/metier/effacer', ['id' => $metier->getId()], [], true); ?>">
                            <span class="icon detruire"  title="Supprimer l'application"></span></a>
                    <?php else : ?>
                        <span class="icon detruire" style="color: lightgrey;"></span>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>





<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
