<?php

/**
 * @see \Element\Controller\ApplicationThemeController::indexAction()
 * @var ApplicationTheme[] $themes;
 */

use Element\Entity\Db\ApplicationTheme;
use Element\Provider\Privilege\ApplicationPrivileges;
use Element\Provider\Privilege\ApplicationthemePrivileges;

$this->headTitle("Liste des thèmes d'application");

$canAfficher = $this->isAllowed(ApplicationthemePrivileges::getResourceId(ApplicationthemePrivileges::APPLICATIONTHEME_AFFICHER));
$canAjouter = $this->isAllowed(ApplicationthemePrivileges::getResourceId(ApplicationthemePrivileges::APPLICATIONTHEME_AJOUTER));
$canModifier = $this->isAllowed(ApplicationthemePrivileges::getResourceId(ApplicationthemePrivileges::APPLICATIONTHEME_MODIFIER));
$canHistoriser = $this->isAllowed(ApplicationthemePrivileges::getResourceId(ApplicationthemePrivileges::APPLICATIONTHEME_HISTORISER));
$canSupprimer = $this->isAllowed(ApplicationthemePrivileges::getResourceId(ApplicationthemePrivileges::APPLICATIONTHEME_EFFACER));

$canApplicationIndex = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::APPLICATION_INDEX));

?>

<h1 class="page-header">
    Liste des thèmes d'application
</h1>

<div class="row">
    <div class="col-md-6">
        <?php if ($canAjouter) : ?>
            <a  <?php /** @see \Element\Controller\ApplicationThemeController::ajouterAction() */?>
                    href="<?php echo $this->url('element/application-theme/ajouter', [], [], true);?>"
                    class="btn btn-primary ajax-modal"
                    data-event="modification"
            >
                <span class="icon icon-ajouter"></span>
                Ajouter un thème
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <?php if ($canApplicationIndex) : ?>
            <a href="<?php echo $this->url('element/application'); ?>"
               class="btn btn-secondary"
            >
                <span class="icon icon-listing"></span>
                Accéder aux applications
            </a>
        <?php endif; ?>
    </div>
</div>


<table id="application_themes" class="table table-condensed table-hover">
    <thead>
    <tr>
        <th class="col-md-8 "> Libelle</th>
        <th class="col-md-2 "> #Application</th>
        <th class="col-md-2 action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($themes as $theme): ?>
        <tr class="<?php if ($theme->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $theme->getLibelle(); ?> </td>
            <td>
                <?php echo count($theme->getApplications()); ?>
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Element\Controller\ApplicationThemeController::afficherAction() */?>
                    <a href="<?php echo $this->url('element/application-theme/afficher', ['application-groupe' => $theme->getId()], [], true); ?>"
                       class="ajax-modal action secondary">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br/>
                    <?php /** @see \Element\Controller\ApplicationThemeController::modifierAction() */?>
                    <a href="<?php echo $this->url('element/application-theme/editer', ['application-groupe' => $theme->getId()], [], true); ?>"
                       class="ajax-modal action primary" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($theme->estNonHistorise()) : ?>
                        <?php /** @see \Element\Controller\ApplicationThemeController::historiserAction() */?>
                        <a href="<?php echo $this->url('element/application-theme/historiser', ['application-groupe' => $theme->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Element\Controller\ApplicationThemeController::restaurerAction() */?>
                        <a href="<?php echo $this->url('element/application-theme/restaurer', ['application-groupe' => $theme->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \Element\Controller\ApplicationThemeController::detruireAction() */?>
                    <a href="<?php echo $this->url('element/application-theme/detruire', ['application-groupe' => $theme->getId()], [], true); ?>"
                            class="ajax-modal action danger" data-event="modification">
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>



<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('table#application_themes').DataTable({
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                {targets: [2], orderable: false}
            ]
        });
    });
</script>