<?php

/**
 * @var EntretienProfessionnel $entretien
 */
$DEBUG = true;


use Application\Entity\Db\EntretienProfessionnel;

$formulaire = $entretien->getFormulaireInstance();
$reponses = $formulaire->getReponses();
$retour = $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId()], ['force_canonical' => false], true);

$now = new DateTime();
?>

<h2> Formulaire d'entretien  </h2>

<?php if ($DEBUG) : ?>
    <div class="alert alert-warning">
        <strong> Débug : </strong> <br/>

        <dl class='dl-horizontal'>
            <dt> Date de l'entretien dépassé </dt>
            <dd> <strong><?php echo ($entretien->getDateEntretien() > $now)?"Non dépassé":"Dépassé"; ?></strong> <?php echo $entretien->getDateEntretien()->format('d/m/Y  H:i:s'); ?>
                    &lt;?&lt; <?php echo $now->format('d/m/Y H:i:s'); ?>
            </dd>
            <dt> Validé par le responsable </dt>
            <dd>
                <?php if ($entretien->getValidationResponsable() !== null AND $entretien->getValidationResponsable()->estNonHistorise()) : ?>
                    <strong>Validé</strong>
                    <?php echo $entretien->getValidationResponsable()->getHistoModificateur()->getDisplayName(); ?>
                    <?php echo $entretien->getValidationResponsable()->getHistoModification()->format('d/m/Y H:i:s') ?>
                <?php else : ?>
                    <strong>Non validé</strong> null
                <?php endif; ?>
            </dd>
        </dl>

        <?php if (($entretien->getDateEntretien() > $now) AND ($entretien->getValidationResponsable() === null OR $entretien->getValidationResponsable()->estHistorise())) : ?>
            <span class="icon editer"></span> Modification
        <?php else : ?>
            <span class="icon voir"></span> Affichage
        <?php endif; ?>
        <?php //var_dump(($entretien->getDateEntretien() < $now)); ?>
        <?php //var_dump(($entretien->getValidationResponsable())); ?>
    </div>
<?php endif; ?>

<?php if (($entretien->getDateEntretien() > $now) AND ($entretien->getValidationResponsable() === null OR $entretien->getValidationResponsable()->estHistorise())) : ?>
    MODIFIABLE
    <?php echo $this->instanceAsFormulaire()->render($formulaire, $retour, $reponses); ?>
<?php else : ?>
    NON MODIF
<!--    $url = $this->url('autoform/formulaire/afficher-formulaire', ['formulaire' => $formulaire->getId(), 'instance' => $entretien->getFormulaireInstance()->getId()], ['query' => ['retour' => $retour], 'force_canonical' => false], true);-->
<?php endif; ?>
