<?php

/**
 * @var EntretienProfessionnelCampagne[] $campagnes
 */

use Application\Entity\Db\EntretienProfessionnelCampagne;
use Application\Provider\Privilege\CampagnePrivileges;

$canAfficher    = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_AFFICHER));
$canAjouter     = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_AJOUTER));
$canModifier    = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_MODIFIER));
$canHistoriser  = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_HISTORISER));
$canDetruire    = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_DETRUIRE));

?>

<?php if ($canAjouter) : ?>
    <a
        <?php /** @see \Application\Controller\EntretienProfessionnelController::ajouterCampagneAction() */?>
        href="<?php echo $this->url('entretien-professionnel/campagne/ajouter', [], [], true); ?>"
        class="btn btn-primary action ajax-modal" data-event="modification"
        >
        <span class="icon ajouter"></span>
        Ajouter une campagne
    </a>
<?php endif; ?>

<table class="table table-condensed">
    <thead>
        <tr>
            <th>Année</th>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Précède</th>
            <th>#Entretiens</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($campagnes as $campagne) : ?>
            <tr>
                <td> <?php echo $campagne->getAnnee(); ?> </td>
                <td> <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?> </td>
                <td> <?php echo $campagne->getDateFin()->format('d/m/Y'); ?> </td>
                <td> <?php echo ($campagne->getPrecede())?$campagne->getPrecede()->getAnnee():"---"; ?> </td>
                <td> <?php echo count($campagne->getEntretiensProfessionnels()); ?> </td>
                <td>
                    <?php if ($canModifier) : ?>
                        <a
                            <?php /** @see \Application\Controller\EntretienProfessionnelController::modifierCampagneAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/campagne/modifier', ['campagne' => $campagne->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                            data-toggle="tooltip" data-html="true"
                            title="Modification de la campagne <span class='highlight campagne'><?php echo $campagne->getAnnee(); ?></span>"
                        >
                        <span class="icon editer"></span></a>
                    <?php endif; ?>
                    <?php if ($canHistoriser) : ?>
                        <?php if ($campagne->estNonHistorise()) : ?>
                            <a
                                <?php /** @see \Application\Controller\EntretienProfessionnelController::historiserCampagneAction() */?>
                                    href="<?php echo $this->url('entretien-professionnel/campagne/historiser', ['campagne' => $campagne->getId()], [], true); ?>"
                                    data-toggle="tooltip" data-html="true"
                                    title="Historisation de la campagne <span class='highlight campagne'><?php echo $campagne->getAnnee(); ?></span>"
                            >
                            <span class="icon historiser"></span></a>
                        <?php else : ?>
                            <a
                                <?php /** @see \Application\Controller\EntretienProfessionnelController::restaurerCampagneAction() */?>
                                    href="<?php echo $this->url('entretien-professionnel/campagne/restaurer', ['campagne' => $campagne->getId()], [], true); ?>"
                                    data-toggle="tooltip" data-html="true"
                                    title="Restauration de la campagne <span class='highlight campagne'><?php echo $campagne->getAnnee(); ?></span>"
                            >
                            <span class="icon restaurer"></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canDetruire) : ?>
                        <a
                            <?php /** @see \Application\Controller\EntretienProfessionnelController::detruireCampagneAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/campagne/detruire', ['campagne' => $campagne->getId()], [], true); ?>"
                                class="ajax-modal" data-event="modification"
                                data-toggle="tooltip" data-html="true"
                                title="Suppression de la campagne <span class='highlight campagne'><?php echo $campagne->getAnnee(); ?></span>"
                        >
                        <span class="icon detruire"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
