<?php

/**
 * @var EntretienProfessionnel $entretien
 * @var ParcoursDeFormation $parcours
 * @var array $options
 */

use Application\Entity\Db\AgentApplication;
use Application\Entity\Db\AgentCompetence;
use Application\Entity\Db\AgentFormation;
use Application\Entity\Db\EntretienProfessionnel;
use Application\Entity\Db\ParcoursDeFormation;
use Application\Provider\Privilege\AgentPrivileges;
use Application\Provider\Privilege\EntretienproPrivileges;

$canVoir        = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VOIR);
$canAjouter     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_AJOUTER);
$canModifier    = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_MODIFIER);
$canHistoriser  = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_HISTORISER);
$canDetruire    = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_DETRUIRE);
$canValider     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VALIDER);

$droits = [
    'afficher' => $canVoir,
    'ajouter' => $canAjouter,
    'modifier' => $canModifier,
    'historiser' => $canHistoriser,
    'detruire' => $canDetruire,
    'valider' => $canValider,
];
$options = [];
$options['droits'] = $droits;
$options['retour'] = $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId()], ['fragment' => 'parcours'], true);

$agent = $entretien->getAgent();

/** @var AgentApplication $agentApplication */
/** @var AgentCompetence $agentCompetence */
/** @var AgentFormation $agentFormation */

$DEBUG = false;
$now = new DateTime();
?>

<?php if ($DEBUG) : ?>
    <div class="alert alert-warning">
        <strong> Débug : </strong> <br/>

        <dl class='dl-horizontal'>
            <dt> Date de l'entretien dépassé </dt>
            <dd> <strong><?php echo ($entretien->getDateEntretien() > $now)?"Non dépassé":"Dépassé"; ?></strong> <?php echo $entretien->getDateEntretien()->format('d/m/Y  H:i:s'); ?>
                &lt;?&lt; <?php echo $now->format('d/m/Y H:i:s'); ?>
            </dd>
            <dt> Validé par le responsable </dt>
            <dd>
                <?php if ($entretien->getValidationResponsable() !== null AND $entretien->getValidationResponsable()->estNonHistorise()) : ?>
                    <strong>Validé</strong>
                    <?php echo $entretien->getValidationResponsable()->getHistoModificateur()->getDisplayName(); ?>
                    <?php echo $entretien->getValidationResponsable()->getHistoModification()->format('d/m/Y H:i:s') ?>
                <?php else : ?>
                    <strong>Non validé</strong> null
                <?php endif; ?>
            </dd>
        </dl>

        <?php if (($entretien->getDateEntretien() > $now) AND ($entretien->getValidationResponsable() === null OR $entretien->getValidationResponsable()->estHistorise())) : ?>
            <span class="icon editer"></span> Modification
        <?php else : ?>
            <span class="icon voir"></span> Affichage
        <?php endif; ?>
        <?php //var_dump(($entretien->getDateEntretien() < $now)); ?>
        <?php //var_dump(($entretien->getValidationResponsable())); ?>
    </div>
<?php endif; ?>

<h2> Parcours de formation </h2>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <?php if ($parcours[ParcoursDeFormation::TYPE_CATEGORIE] AND !empty($parcours[ParcoursDeFormation::TYPE_CATEGORIE])) : ?>
            <?php foreach ($parcours[ParcoursDeFormation::TYPE_CATEGORIE] as $categorieId => $parcour) : ?>
                <?php echo $this->parcoursDeFormation($parcour, $agent, $options); ?>
            <?php endforeach; ?>
        <?php else: ?>
            <span class="icon attention">Pas de parcours de formation associé à la catégorie.</span>
        <?php endif; ?>
    </div>
<!--    <div class="col-md-6">-->
<!--        --><?php //if ($parcours[ParcoursDeFormation::TYPE_METIER] AND !empty($parcours[ParcoursDeFormation::TYPE_METIER])) : ?>
<!--            --><?php //foreach ($parcours[ParcoursDeFormation::TYPE_METIER] as $metierId => $parcour) : ?>
<!--                --><?php //echo $this->parcoursDeFormation($parcour, $agent, $options); ?>
<!--            --><?php //endforeach; ?>
<!--        --><?php //else: ?>
<!--            <span class="icon attention">Pas de parcours de formation associé au métier.</span>-->
<!--        --><?php //endif; ?>
<!--    </div>-->
</div>

<h2> Acquis de l'agent </h2>

<!-- APPLICATION ------------------------------------------------------------------------------------------------------>

<?php
    /** @see \Application\View\Helper\AgentApplicationViewHelper */
    echo $this->agentApplication($agent, $options);
?>

<!-- COMPETENCE ------------------------------------------------------------------------------------------------------->

<?php
    /** @see \Application\View\Helper\AgentCompetenceViewHelper */
    echo $this->agentCompetence($agent, $options);
    ?>

<!-- FORMATIONS ------------------------------------------------------------------------------------------------------->

<?php
    /** @see \Application\View\Helper\AgentFormationViewHelper */
    echo $this->agentFormation($agent, $options);
?>
