<?php

/**
 * @see ImportController::importAction()
 *
 * @var array $info
 * @var array $warning
 * @var array $error
 * @var array $data
 * @var array $file
 * @var string $filename
 * @var string $filepath
 * @var Referentiel[] $referentiels
 * @var bool $displayCodeFonction
 *
 * @var FicheMetier[] $fiches
 */

use Application\Provider\Privilege\FicheMetierPrivileges;
use Element\Entity\Db\Competence;
use FicheMetier\Controller\ImportController;
use FicheMetier\Entity\Db\FicheMetier;
use Referentiel\Entity\Db\Referentiel;

$canFicheMetier = $this->isAllowed(FicheMetierPrivileges::getResourceId(FicheMetierPrivileges::FICHEMETIER_INDEX));

$this->headTitle("Importation des fiches métiers");

?>

<script xmlns="http://www.w3.org/1999/html">
    function reset() {
        console.log('click');
        window.location.href="../fiche-metier/import";
    }
</script>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Importation des fiches métiers
        </h1>
    </div>
    <div class="col-md-4">
        <?php if ($canFicheMetier) : ?>
            <?php /** @see \FicheMetier\Controller\FicheMetierController::indexAction() */ ?>
            <a href="<?php echo $this->url('fiche-metier', [], [], true); ?>"
               class="btn btn-secondary float-end">
                <span class="icon icon-listing"></span>
                Accéder aux fiches métiers
            </a>
        <?php endif; ?>
    </div>
</div>

<br>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Importation de fiche métier depuis un CSV</div>
            <div class="card-body">
                <form enctype="multipart/form-data"
                      action="<?php echo $this->url("fiche-metier/import", ['path' => null], [], true); ?>"
                      method="post">
                    <?php if ($filepath !== null) : ?>
                        <span class="form-label">Fichier téléversé : </span><br>
                        <div style="padding:0.5rem;border:solid 1px lightgrey;width:100%; border-radius:6px;">
                            <div class='row'>
                                <div class='col-md-9'> <?php echo $filename; ?> </div>
                                <div class='col-md-3'>
                                    <div class='float-end'>
                            <span class="action text-danger" style="cursor: pointer;" onclick="reset()">
                                <span class='icon icon-unchecked' id='remove_file' title='Retirer le fichier'></span> Retirer
                            </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="filepath" id="filepath" value="<?php echo $filepath; ?>">
                        <input type="hidden" name="filename" id="filename" value="<?php echo $filename; ?>">
                    <?php else : ?>
                        <label for="file">Fichier à importer <span class="icon icon-obligatoire"
                                                                   title="Champ obligatoire"></span></label>
                        <input type="file" name="file" id="file" class="form-control" accept=".csv"/>
                    <?php endif; ?>
                    <label for="referentiel"> Référentiel <span class="icon icon-obligatoire"
                                                                title="Champ obligatoire"></span> </label>
                    <select class="selectpicker show-tick form-control" id="referentiel" name="referentiel">
                        <option value="">Sélectionnez un référentiel</option>
                        <?php foreach ($referentiels as $referentiel): ?>
                            <option value="<?php echo $referentiel->getId(); ?>"
                                    <?php if (isset($data["referentiel"]) and $data["referentiel"] == $referentiel->getId()) : ?>
                                        selected
                                    <?php endif; ?>
                            >
                                <?php echo $referentiel->getLibelleCourt(); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <label for="format"> Format <span class="icon icon-obligatoire" title="Champ obligatoire"></span>
                    </label>
                    <select class="selectpicker show-tick form-control" id="format" name="format">
                        <option value="">Sélectionnez un format</option>
                        <?php foreach (ImportController::FORMATS as $key => $libelle): ?>
                            <option value="<?php echo $key; ?>"
                                    <?php if (isset($data["format"]) and $data["format"] == $key) : ?>
                                        selected
                                    <?php endif; ?>
                            >
                                <?php echo $libelle; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <br>
                    <label for="mode"> Mode de traitement <span class="icon icon-obligatoire"
                                                                title="Champ obligatoire"></span></label>
                    <select class="selectpicker show-tick form-control" id="mode" name="mode">
                        <option value="preview"
                                <?php if (isset($data["mode"]) and $data["mode"] === "preview") : ?>
                                    selected
                                <?php endif; ?>
                        >Prévisualisation
                        </option>
                        <option value="import"
                                <?php if (isset($data["mode"]) and $data["mode"] === "import") : ?>
                                    selected
                                <?php endif; ?>
                        >Importation
                        </option>
                    </select>
                    <br>
                    <button type='submit' class="btn btn-success">
                        <span class="icon icon-csv"></span>
                        Traiter le fichier
                    </button>

                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="alert alert-info">
            <p>
                Importez vos fiches métiers depuis un référentiel (<code>REFERENS3</code>
                <a href="<?php echo $this->url('home',[],['force_canonical' => true], true); ?>exemples/referentiel/fichemetier_referens3.csv"><span class="icon icon-csv"></span> référentiel des fiches métiers REFERENS3</a>
                ou <code>RMFP</code> <a href="<?php echo $this->url('home',[],['force_canonical' => true], true); ?>exemples/referentiel/fichemetier_rmfp.csv"> <span class="icon icon-csv"></span> référentiel des fiches métiers RMFP</a>).<br>
                Construisez votre référentiel fiche métier via la trame <code>EMC2</code>  <a href="../exemples/trame_csv/import_fichemetier_emc2.csv"> <span class="icon icon-csv"></span> trame vierge EMC2 </a>.
            </p>


                Pour la trame EMC2 :
                <ul>
                    <li><code><?php echo ImportController::HEADER_EMC2_CODE; ?></code> <span class="icon icon-obligatoire"></span> : identifiant unique de la fiche métier.</li>
                    <li><code><?php echo ImportController::HEADER_EMC2_LIBELLE; ?></code> <span class="icon icon-obligatoire"></span>.</li>
                    <li><code><?php echo ImportController::HEADER_EMC2_SPECIALITE_TYPE; ?></code> : <a href="<?php echo $this->url('carriere/correspondance-type',[],[],true); ?>" target="_blank">Code associé au type de la spécialité</a> ; par exemple <code>BAP</code>, <code>CNU</code>.</li>
                    <li><code><?php echo ImportController::HEADER_EMC2_SPECIALITE_CODE; ?></code> : <a href="<?php echo $this->url('correspondance',[],[],true); ?>" target="_blank">Code de la spécialité</a> ; par exemple <code>A</code>, <code>37</code>.</li>
                    <li><code><?php echo ImportController::HEADER_EMC2_SPECIALITE_LIBELLE; ?></code> : créée si non connue et cohérente avec la famille professionnelle.</li>
                    <li><code><?php echo ImportController::HEADER_EMC2_FAMILLE_LIBELLE; ?></code> : la <a href="<?php echo $this->url('famille-professionnelle',[],[],true); ?>" target="_blank">famille professionnelle</a> est créée si non existante.</li>
                    <?php if ($displayCodeFonction): ?>
                        <li><code><?php echo ImportController::HEADER_EMC2_FAMILLE_POSITION; ?></code> : Correspond à la position de la FAP dans la spécialité et utilisée dans le code fonction (fonctionnalité AMU). </li>
                    <?php endif; ?>
                    <?php if ($displayCodeFonction): ?>
                        <li><code><?php echo ImportController::HEADER_CODE_FONCTION; ?></code> : créé si non existant, attention le <a href="<?php echo $this->url('niveau-fonction',[],[],true); ?>" target="_blank">niveau de fonction</a> doit exister.</li>
                    <?php endif; ?>
                    <li><code><?php echo ImportController::HEADER_EMC2_NIVEAU_CARRIERE; ?></code> : étiquette du <a href="<?php echo $this->url('niveau',[],[],true); ?>" target="_blank">niveau de carrière</a> ; par exemple <code>TECH</code>, <code>IGE</code>.</li>
                    <li><code><?php echo ImportController::HEADER_CODE_EMPLOITYPE; ?></code> : la liste des codes emplois types (référentiels). </li>
                    <li><code><?php echo ImportController::HEADER_EMC2_RAISON; ?></code> : texte simple. </li>
                    <li><code><?php echo ImportController::HEADER_EMC2_MISSION; ?></code> <span class="icon icon-obligatoire"></span> : Liste des missions (séparateur <code>|</code>). Exemple : Mission 1 | Mission 2.</li>
                    <li><code><?php echo ImportController::HEADER_EMC2_ACTIVITE; ?></code> : Liste des activités (séparateur <code>|</code>). Exemple : Activité 1 | Activité 2.</li>
                    <li><code><?php echo ImportController::HEADER_EMC2_COMPETENCE; ?></code> : identifiant des compétences de tous types importées dans EMC2 (séparateur <code>|</code>). Peut contenir différents référentiels ; par exemple <code>REFERENS3-0002|REFERENS-0004|RMFP-487</code>.</li>
                    <li><code><?php echo ImportController::HEADER_EMC2_APPLICATION; ?></code> : intitulé exact des applications déjà connues dans EMC2.</li>
                    <li>Module "Contexte et environnement" <br>
                        Pour importer les données liées aux champs de ce module, créez une colonne par champ existant dans le <a href="<?php echo $this->url('fiche-metier/thematique-type', [], [], true); ?>" target="_blank">back-office</a>
                        <ul>
                            <li>En-tête de la colonne : le libellé exact du champ.</li>
                            <li>Valeur : le libellé niveau de maîtrise associée ; par exemple Modéré, Fort.</li>
                        </ul>
                    <li> Module "Tendances d'évolution"<br>
                        Pour importer les données liées aux champs de ce module, créez une colonne par champ existant dans le <a href="<?php echo $this->url('fiche-metier/tendance-type', [], [], true); ?>" target="_blank">back-office</a>
                        <ul>
                            <li>En-tête de la colonne : le libellé exact du champ.</li>
                            <li>Valeur : texte simple.</li>
                        </ul>
                </ul>


            <strong><u>Remarques :</u></strong>
            <ul>
                <li>Le fichier importé doit être enregistré en <strong style="color:red;">CSV UTF8</strong> (et non CSV).</li>
                <li> <span class="icon icon-obligatoire"></span> indique un champ obligatoire </li>
                <li>L'intitulé des colonnes doit être exactement celui spécifié (majuscule et accent).</li>
                <li>L'ordre des colonnes n'a pas besoin d'être respecté.</li>
                <li>Pour EMC2 et REFERENS3 le séparateur est <code>|</code>.</li>
                <li>Pour RMFP le séparateur est le saut de ligne.</li>
            </ul>

        </div>
    </div>
</div>

<?php if ($data !== null) : ?>
    <?php if (!empty($error)) : ?>
        <div class="alert alert-danger">
            <?php foreach ($error as $line): ?>
                <?php echo $line ?>
                <br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if (!empty($info)) : ?>
        <div class="alert alert-info">
            <?php foreach ($info as $line): ?>
                <?php echo $line ?>
                <br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if (!empty($warning)) : ?>
        <div class="alert alert-warning">
            <?php foreach ($warning as $line): ?>
                <?php echo $line ?>
                <br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php foreach ($fiches as $fiche) : ?>
    <div class="card" style="padding: 0.25rem">
        <div class="row">
            <div class="col-md-8">
                <h3> <?php echo $fiche->printReference(); ?> <?php echo $fiche->getLibelle(); ?> </h3>
                <?php if ($fiche->getRaison()) : ?>
                    <strong>Raison d'être :</strong> <?php echo $fiche->getRaison(); ?>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <?php if ($fiche->getNiveauCarriere()): ?> <strong>Niveau de carrière</strong> <?php echo $fiche->getNiveauCarriere()->getLibelle(); ?> <br> <?php endif; ?>
                <?php if ($fiche->getCodeFonction()): ?> <strong>Code fonction</strong> <?php echo $fiche->getCodeFonction()->computeCode(); ?> <br> <?php endif; ?>
                <?php if ($fiche->getCodesEmploiType()): ?> <strong>Codes emploi type</strong> <?php echo $fiche->getCodesEmploiType(); ?> <br> <?php endif; ?>
                <?php if ($fiche->getFamilleProfessionnelle()): ?>
                    <strong>Famille professionnelle</strong>
                    <?php echo $fiche->getFamilleProfessionnelle()->getLibelle(); ?>
                    <?php echo $fiche->getFamilleProfessionnelle()->computeCode(); ?>
                    <br>
                <?php endif; ?>

                <?php if ($fiche->getFamilleProfessionnelle()?->getCorrespondance()): ?> <strong>Spécialité </strong> <?php echo $fiche->getFamilleProfessionnelle()->getCorrespondance()->getLibelleLong(); ?> <?php endif; ?>
            </div>
        </div>


        <?php $missions = $fiche->getMissions(); ?>
        <?php if (!empty($missions)) : ?>
            <strong>Missions</strong>
            <ul>
            <?php foreach ($missions as $mission) : ?>
                <li>
                    <?php echo $mission->getMission()->getLibelle(); ?>
                    <?php //if ($mission->getId() === null) echo "<span style='color:darkred;font-variant: small-caps;font-size:small;padding-left: 1rem;font-weight: bold;'>NEW</span>"; ?>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php $activites = $fiche->getActivites(); ?>
        <?php if (!empty($activites)) : ?>
            <strong>Activités</strong>
            <ul>
            <?php foreach ($fiche->getActivites() as $activite) : ?>
                <li>
                    <?php echo $activite->getActivite()->getLibelle(); ?>
                    <?php //if ($activite->getId() === null) echo "<span style='color:darkred;font-variant: small-caps;font-size:small;padding-left: 1rem;font-weight: bold;'>NEW</span>"; ?>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>


    <?php
    $competences = $fiche->getCompetenceCollection();
    $dictionnaires = [];
    foreach ($competences as $competence) {
        $type = $competence->getCompetence()->getType();
        $dictionnaires[$type->getLibelle()][$competence->getCompetence()->getReference()] = $competence->getCompetence();
    }
    ?>

    <div class="row">
        <?php foreach ($dictionnaires as $type => $competences_) : ?>
            <div class="col-md-4">
                <strong><?php echo $type; ?></strong><br>
                <?php /** @var Competence $competence */ ?>
                <?php foreach ($competences_ as $competence) : ?>
                    <?php echo $competence->getLibelle(); ?>
                    <?php echo $competence->printReference(); ?>
                    <br>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php $applications = $fiche->getApplicationCollection(); ?>
    <strong>Applications</strong>
    <ul>
    <?php foreach ($applications as $application) : ?>

        <li><?php echo $application->getLibelle(); ?></li>
    <?php endforeach; ?>
    </ul>

<!--    <strong> Tendances d'évolution  </strong> <br>-->
    <?php foreach ($fiche->getTendances() as $tendance) : ?>
        <strong><?php echo $tendance->getType()->getLibelle(); ?></strong>
        <?php echo $tendance->getTexte(); ?>
        <br>
    <?php endforeach; ?>

<!--    <strong> Contexte et environnement de travail </strong> <br>-->
    <?php foreach ($fiche->getThematiques() as $thematique) : ?>
        <strong><?php echo $thematique->getType()->getLibelle(); ?></strong>
        <?php echo $thematique->getNiveauMaitrise()?->getLibelle(); ?>
        <?php if ($thematique->getComplement()) : ?>
            <br> <?php echo $thematique->getComplement(); ?>
        <?php endif; ?>
        <br>
    <?php endforeach; ?>
    </div>
<?php endforeach; ?>
