<?php

$navigationHelper = $this->navigation('navigation');
$env = getenv('APPLICATION_ENV') ?: 'production';

?>

<script>
    function generateAdresse(name, domaine) {
        document.write("<a href=" + "mail" + "to:" + name + "@" + domaine + ">" + name + "@"+ domaine + "</a>");
    }
</script>

<?php echo $this->doctype(); ?>
<html lang="fr">
<head>
    <!-- Meta -->
    <meta charset="utf-8">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('description', '')
        ->appendHttpEquiv("X-UA-Compatible", "IE=edge,chrome=1") ?>
    <!-- Title -->
    <?php echo $this->headTitle($this->appInfos()->nom)->setSeparator(' - ')->setAutoEscape(false) ?>
    <!-- Links -->
    <?php echo $this->headLink(array(
        'rel'   => 'shortcut icon',
        'type'  => 'image/vnd.microsoft.icon',
        'href'  => '//www.unicaen.fr/favicon.ico')) ?>
    <!-- Scripts -->
    <?php echo $this->headScript(); ?>
</head>

<body class="<?php  echo getenv('APPLICATION_ENV'); ?>">
    <header>
    <div id="navbar" class="navbar" >
        <?php $connecte = $this->appConnection()->getView()->plugin('userCurrent')->getIdentity(); ?>
        <div class="navbar-element" id="navbar-logo"
             <?php if ($connecte !== null) : ?>
                style="display:none;"
             <?php endif; ?>
        >
            <img src='/img/unicaen-logo-blanc.svg' alt='Logo UniCaen' class='navbar-logo-unicaen' />
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <?= $this->appLink($this->appInfos()->nom);?>
            <br/>
            <?php if ($env !== 'production') echo $env; ?>
        </div>

        <div class="navbar-collapse bs-navbar-collapse collapse">
            <?php echo $navigationHelper
                ->menu()
                ->setUlClass('nav navbar-nav')
                ->setPartial('layout/navigation-octopus.phtml');
            ?>
            <p class="navbar-element navbar-connection">
                <?php echo $this->appConnection(); ?>
            </p>
        </div>
</div>
</header>

<div style="display: flex; flex-wrap: nowrap;">
    <div id="contenu-principal" class="container">
        <?php echo $this->content; ?>
    </div>
</div>

    <footer>
        <div>
            <?php $options = $this->navigation('navigation'); ?>
            <a class="footer-logo-normandie-universite" target="_blank" href="http://normandie-univ.fr/">
                <img src="/img/normandie-universite-logo.svg" alt="Logo Nomandie Université" class="footer-logo-normandie-universite" />
            </a>
            <div id="menu-footer">
                <?php echo $navigationHelper->menuPiedDePage('navigation'); ?>
            </div>
            <img src="/img/republique-francaise-logo.svg" alt="Logo République française" class="footer-logo-republique-francaise" />
            <a class="footer-logo-unicaen" target="_blank" href="http://www.unicaen.fr/">
                <img src="/img/unicaen-logo-noir.svg" alt="Logo UniCaen" class="footer-logo-unicaen" />
            </a>
        </div>
    </footer>


<?php echo $this->inlineScript(); ?>

</body>
</html>

<script>
    $(function () {
        $('[data-toggle="popover"]').popover({ html: true});
    });
    $(function () {
        $('[data-toggle="tooltip"]').tooltip({});
    });
</script>