<?php

use Missionspecifique\Provider\Privilege\MissionspecifiquePrivileges;
use Missionspecifique\Provider\Privilege\MissionspecifiquethemePrivileges;
use Missionspecifique\Provider\Privilege\MissionspecifiquetypePrivileges;
use MissionSpecifique\Entity\Db\MissionSpecifiqueTheme;

/**
 * @see \MissionSpecifique\Controller\MissionSpecifiqueThemeController::indexAction()
 * @var MissionSpecifiqueTheme[] $themes
 */

$this->headTitle("Thèmes de mission spécifique");

$canIndexMissionSpecifique = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_INDEX));
$canIndexMissionSpecifiqueType = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_INDEX));

$canAfficher = $this->isAllowed(MissionspecifiquethemePrivileges::getResourceId(MissionspecifiquethemePrivileges::MISSIONSPECIFIQUETHEME_AFFICHER));
$canAjouter = $this->isAllowed(MissionspecifiquethemePrivileges::getResourceId(MissionspecifiquethemePrivileges::MISSIONSPECIFIQUETHEME_AJOUTER));
$canModifier = $this->isAllowed(MissionspecifiquethemePrivileges::getResourceId(MissionspecifiquethemePrivileges::MISSIONSPECIFIQUETHEME_MODIFIER));
$canHistoriser = $this->isAllowed(MissionspecifiquethemePrivileges::getResourceId(MissionspecifiquethemePrivileges::MISSIONSPECIFIQUETHEME_HISTORISER));
$canEffacer = $this->isAllowed(MissionspecifiquethemePrivileges::getResourceId(MissionspecifiquethemePrivileges::MISSIONSPECIFIQUETHEME_DETRUIRE));

?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Thèmes de mission spécifique
        </h1>

        <?php if ($canAjouter) : ?>
            <?php  /** @see \MissionSpecifique\Controller\MissionSpecifiqueThemeController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('mission-specifique-theme/ajouter', [], [], true); ?>"
               class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un thème de mission
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-3">
        <?php if ($canIndexMissionSpecifique) : ?>
            <?php  /** @see \MissionSpecifique\Controller\MissionSpecifiqueController::indexAction() */ ?>
            <a href="<?php echo $this->url("mission-specifique"); ?>" class="btn btn-secondary">
                <span class="icon icon-listing"></span>
                Accéder aux missions
            </a>
        <?php endif; ?>
        <?php if ($canIndexMissionSpecifiqueType) : ?>
            <?php  /** @see \MissionSpecifique\Controller\MissionSpecifiqueTypeController::indexAction() */ ?>
            <a href="<?php echo $this->url("mission-specifique-type"); ?>" class="btn btn-secondary">
                <span class="icon icon-listing"></span>
                Accéder aux types
            </a>
        <?php endif; ?>
    </div>
</div>

<br/>

<table class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Libellé</th>
        <th> #Missions</th>
        <th class="action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($themes as $theme) : ?>
        <tr class="<?php if ($theme->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $theme->getLibelle(); ?> </td>
            <td> <?php echo count($theme->getMissions()); ?> </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php  /** @see \MissionSpecifique\Controller\MissionSpecifiqueThemeController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('mission-specifique-theme/afficher', ['theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal action secondary"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php  /** @see \MissionSpecifique\Controller\MissionSpecifiqueThemeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('mission-specifique-theme/modifier', ['theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal action primary" data-event="modification"
                    >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($theme->estNonHistorise()) : ?>
                        <?php  /** @see \MissionSpecifique\Controller\MissionSpecifiqueThemeController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('mission-specifique-theme/historiser', ['theme' => $theme->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php  /** @see \MissionSpecifique\Controller\MissionSpecifiqueThemeController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('mission-specifique-theme/restaurer', ['theme' => $theme->getId()], [], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <br>
                    <?php  /** @see \MissionSpecifique\Controller\MissionSpecifiqueThemeController::detruireAction() */ ?>
                    <a href="<?php echo $this->url('mission-specifique-theme/detruire', ['theme' => $theme->getId()], [], true); ?>"
                       class="ajax-modal action danger" data-event="modification"
                    >
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });

        $('.datatable').DataTable({
            autoWidth: false,
            paging: false,
            order: [[0, 'asc'], [1, 'asc']],
            columnDefs: [{
                "targets": 2,
                "orderable": false
            }],
            language: {
                url: '/js/datatables_fr.json'
            }
        });
    });
</script>