<?php

/**
 * @var Structure $structure
 * @var Contact[] $contacts
 */

use Structure\Entity\Db\Structure;
use UnicaenContact\Entity\Db\Contact;
use UnicaenContact\Provider\Privilege\ContactPrivileges;

$canAjouterContact = $this->isAllowed(ContactPrivileges::getResourceId(ContactPrivileges::CONTACT_AJOUTER));
$canModifierContact = $this->isAllowed(ContactPrivileges::getResourceId(ContactPrivileges::CONTACT_MODIFIER));
$canHistoriserContact = $this->isAllowed(ContactPrivileges::getResourceId(ContactPrivileges::CONTACT_HISTORISER));
$canSupprimerContact = $this->isAllowed(ContactPrivileges::getResourceId(ContactPrivileges::CONTACT_SUPPRIMER));

$sortedContacts = [];
$sortedTypes = [];
foreach ($contacts as $contact) {
    $type = $contact->getType();
    $sortedTypes[$type->getId()] = $type;
    $sortedContacts[$type->getId()][] = $contact;
}
usort($sortedTypes, function (Type $a, Type $b) {
    return $a->getLibelle() <=> $b->getLibelle();
});


?>
<h2>
    Contact·s
    <?php if ($canAjouterContact): ?>
        <?php /**  @see \Structure\Controller\ContactController::ajouterAction() * */ ?>
        <a href="<?php echo $this->url('structure/contact/ajouter', ['structure' => $structure->getId()], [], true); ?>"
           class="ajax-modal" data-event="modification">
            <span class="icon icon-ajouter" title="Ajouter un contact pour la structure"></span></a>
        <?php /**  @see \Structure\Controller\ContactController::associerAction() * */ ?>
        <a href="<?php echo $this->url('structure/contact/associer', ['structure' => $structure->getId()], [], true); ?>"
           class="ajax-modal" data-event="modification">
            <span class="icon icon-link" title="Associer un contact existant"></span></a>
    <?php endif; ?>
</h2>

<?php if (empty($contacts)) : ?>
    <span class="text-warning">
                        <span class="icon icon-attention"></span>
                        Aucun contact de désigné pour cette structure.
                    </span>
<?php else : ?>
    <?php foreach ($sortedTypes as $type) : ?>
        <h3> <?php echo $type->getLibelle(); ?> </h3>

        <?php
        $contacts_ = $sortedContacts[$type->getId()];
        $res = usort($contacts_, function ($a, $b) {
            return Contact::sort($a, $b);
        });
        ?>
        <?php foreach ($contacts_ as $contact) : ?>
            <?php if ($contact->estNonHistorise() or $canModifierContact) : ?>
                <div class="row">
                    <div class="col-md-8">
                        <?php echo $this->contact($contact); ?>
                    </div>
                    <div class="col-md-4 action">
                        <?php if ($canModifierContact) : ?>
                            <?php /** @see \UnicaenContact\Controller\ContactController::modifierAction() */ ?>
                            <a href="<?php echo $this->url("unicaen-contact/contact/modifier", ['contact' => $contact->getId()], [], true); ?>"
                               class="action primary ajax-modal" data-event="modification"
                            >
                                <span class="icon icon-editer"></span>
                                Modifier
                            </a>
                        <?php endif; ?>
                        <?php if ($canModifierContact) : ?>
                            <br>
                            <?php /** @see \Structure\Controller\ContactController::desassocierAction() */ ?>
                            <a href="<?php echo $this->url("structure/contact/desassocier", ['structure' => $structure->getId(), 'contact' => $contact->getId()], [], true); ?>"
                               class="action warning"
                            >
                                <span class="icon icon-unlink"></span>
                                Dissocier
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif; ?>