<?php

use Structure\Entity\Db\Observateur;
use Structure\Entity\Db\Structure;
use Structure\Provider\Privilege\StructureobservateurPrivileges;

/**
 * @var Structure $structure
 * @var Observateur[] $observateurs
 */

$canAjouter = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_AJOUTER));
$canModifier = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_MODIFIER));
$canHistoriser = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_HISTORISER));
$canSupprimer = $this->isAllowed(StructureobservateurPrivileges::getResourceId(StructureobservateurPrivileges::STRUCTUREOBSERVATEUR_SUPPRIMER));


?>

<div class="card" style="margin-bottom: 0.5rem;">
    <div class="card-header bg-default">
        <div>
            <h2>Observateur·trices</h2>
        </div>
        <div>
            <?php if ($canAjouter) : ?>
                <?php /** @see \Structure\Controller\ObservateurController::ajouterAction() */ ?>
                <a href="<?php echo $this->url('structure/observateur/ajouter', ['structure' => $structure->getId()], [], true); ?>"
                   class="ajax-modal action primary" data-event="modification">
                    <span class="icon icon-ajouter"></span>
                    Ajouter un·e observateur·trice
                </a>
            <?php endif; ?>
        </div>
    </div>
    <div class="card-body">
        <?php if (empty($observateurs)) : ?>
            Aucun·e observateur·trice de désigné·e pour cette structure.
        <?php else : ?>
            <ul style="margin-bottom: 0;">
                <?php foreach ($observateurs as $observateur) : ?>
                    <li>
                        <?php echo $observateur->getUtilisateur()->getDisplayName(); ?>
                        <?php if ($observateur->getDescription()) : ?>
                            <span class="icon icon-information" data-bs-toggle="tooltip" data-bs-html="true"
                                  title="<?php echo $observateur->getDescription(); ?>"></span>
                        <?php endif; ?>


                        <?php if ($canModifier) : ?>
                            <?php /** @see \Structure\Controller\ObservateurController::modifierAction() */ ?>
                            <a href="<?php echo $this->url("structure/observateur/modifier", ['observateur' => $observateur->getId(), 'structure' => $structure->getId()], [], true); ?>"
                               class="action primary ajax-modal" data-event="modification">
                                <span class="icon icon-editer"></span>
                                Modifier
                            </a>
                        <?php endif; ?>
                        <?php if (false AND $canHistoriser): ?>
                            <?php if ($observateur->estNonHistorise()) : ?>
                                <?php /** @see \Structure\Controller\ObservateurController::historiserAction() */ ?>
                                <a href="<?php echo $this->url("structure/observateur/historiser", ['observateur' => $observateur->getId()], ['query' => ['retour' => $this->url('structure/description', ['structure' => $structure->getId()], [], true)]], true); ?>"
                                   class="action warning"
                                >
                                    <span class="icon icon-historiser"></span>
                                    Historiser
                                </a>
                            <?php else : ?>
                                <?php /** @see \Structure\Controller\ObservateurController::restaurerAction() */ ?>
                                <a href="<?php echo $this->url("structure/observateur/restaurer", ['observateur' => $observateur->getId()], ['query' => ['retour' => $this->url('structure/description', ['structure' => $structure->getId()], [], true)]], true); ?>"
                                   class="action warning"
                                >
                                    <span class="icon icon-restaurer"></span>
                                    Restaurer
                                </a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canSupprimer): ?>
                            <?php /** @see \Structure\Controller\ObservateurController::supprimerAction() */ ?>
                            <a href="<?php echo $this->url("structure/observateur/supprimer", ['observateur' => $observateur->getId()], [], true); ?>"
                               class="action danger ajax-modal" data-event="modification">
                                <span class="icon icon-unchecked"></span>
                                Supprimer
                        </a>
                        <?php endif; ?>

                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>

