<?php

/**
 * @var Structure $structure
 */

use Structure\Entity\Db\Structure;
use Structure\Provider\Privilege\StructurePrivileges;

$canEditerDescription = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_DESCRIPTION);
?>

<h2> Présentation de la structure</h2>

<?php if ($canEditerDescription) : ?>
    <a
        <?php /** @see \Structure\Controller\StructureController::editerDescriptionAction() */ ?>
        href="<?php echo $this->url('structure/editer-description', ['structure' => $structure->getId()], [], true); ?>"
        class="btn btn-primary ajax-modal"
        data-event="modification"
    >
                    <span class="icon icon-editer" data-bs-toggle="tooltip" data-bs-html="true"
                          title="Modifier la description de la structure <span class='highlight structure'><?php echo $structure->getLibelleLong(); ?></span>"></span>
        Modifier le résumé
    </a>
    <a
        <?php /** @see \Structure\Controller\StructureController::toggleResumeMereAction() */ ?>
        href="<?php echo $this->url('structure/toggle-resume-mere', ['structure' => $structure->getId()], ['query' => ['retour' => $this->url('structure/description', ['structure' => $structure->getId()], [], true)]], true); ?>"
        class="btn btn-<?php echo $structure->getRepriseResumeMere() ? 'danger' : 'success'; ?>"
    >
        <?php if ($structure->getRepriseResumeMere()) : ?>
            <span class="icon icon-unchecked" data-bs-toggle="tooltip" data-bs-html="true"
                  title="Ne plus réutiliser le résumé de la structure mère"></span>
            Ne plus utiliser le résumé de la structure mère
        <?php else : ?>
            <span class="icon icon-checked" data-bs-toggle="tooltip" data-bs-html="true"
                  title="Réutiliser le résumé de la structure mère"></span>
            Utiliser le résumé de la structure mère
        <?php endif; ?>
    </a>

<?php endif; ?>

<br>

<?php if ($structure->getRepriseResumeMere()) : ?>
    <!--            <div class="alert alert-info">-->
    <!--                <span class="icon icon-information"></span>-->
    <!--                Reprise du résumé de la structure mère.-->
    <!--            </div>-->
<?php endif; ?>
<?php if ($structure->getDescriptionComplete()) : ?>
    <?php echo $structure->getDescriptionComplete(); ?>
<?php else : ?>
    <span class="text-warning">
                <span class="icon icon-attention"></span>
                Aucune description
            </span>
<?php endif; ?>
