<?php

/**
 * @var Structure $structure
 */

use Structure\Entity\Db\Structure;

$niveau2 = $structure->getNiv2();

?>

<h3> Rattachement </h3>

<?php if ($structure->getNiv2() === null) : ?>
    <span class="text-warning">
                <span class="icon icon-attention"></span>
                Pas de structure de rattachement
            </span>
<?php else : ?>
    Structure rattachée à <?php echo $niveau2->getLibelleLong(); ?>
<?php endif; ?>
