<?php

/**
 * @see MissionSpecifiqueAffectationController::afficherAction()
 * @var AgentMissionSpecifique $affectation
 */

use Application\Entity\Db\AgentMissionSpecifique;

?>

<div class="row">
    <div class="col-md-6">
        <dl>
            <dt> Agent </dt>
            <dd> <?php echo $affectation->getAgent()->getDenomination(); ?> </dd>

            <dt> Mission </dt>
            <dd> <?php echo $affectation->getMission()->getLibelle(); ?> </dd>

            <dt> Structure </dt>
            <dd>
                <?php if ($affectation->getStructure()) : ?>
                    <?php echo $affectation->getStructure()->getLibelleLong(); ?>
                <?php else : ?>
                    Aucune Structure
                <?php endif; ?>
            </dd>

            <dt> Période </dt>
            <dd>
                Du
                <?php echo ($affectation->getDateDebut()?$affectation->getDateDebut()->format('d/m/Y'):"---"); ?>
                au
                <?php echo ($affectation->getDateFin()?$affectation->getDateFin()->format('d/m/Y'):"---"); ?>
            </dd>

            <dt> Volume horaire associé à la mission pour une année complète</dt>
            <dd>
                <?php if ($affectation->getDecharge()) : ?>
                    <?php echo $affectation->getDecharge(); ?> h.
                <?php else: ?>
                    Aucune
                <?php endif; ?>
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl>
            <dt>Dernière modification </dt>
            <dd>
                <?php echo $affectation->getHistoModification()->format('d/m/Y à H:i:s'); ?> <br/>
                <?php echo $affectation->getHistoModificateur()->getDisplayName(); ?>
            </dd>
        </dl>

        <?php if ($affectation->estHistorise()) : ?>
            <dl>
                <dt>Historisée  </dt>
                <dd>
                    <?php echo $affectation->getHistoDestruction()->format('d/m/Y à H:i:s'); ?> <br/>
                    <?php echo $affectation->getHistoDestructeur()->getDisplayName(); ?>
                </dd>
            </dl>
        <?php endif; ?>
    </div>
</div>