<?php

/**
 * @see MissionSpecifiqueAffectationController::indexAction()
 *
 * @var array $missions
 * @var MissionSpecifiqueTheme[] $themes
 * @var MissionSpecifiqueType[] $types
 * @var array $params
 *
 * @var AgentMissionSpecifique[] $affectations
 */

use Application\Entity\Db\AgentMissionSpecifique;
use Application\Provider\Privilege\MissionspecifiqueaffectationPrivileges;
use MissionSpecifique\Entity\Db\MissionSpecifiqueTheme;
use MissionSpecifique\Entity\Db\MissionSpecifiqueType;

$this->headTitle("Affectations de missions spécifiques");

$canVoir = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_AFFICHER));
$canLettre = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_AFFICHER));
$canAjouter = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_AJOUTER));
$canEditer = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_MODIFIER));
$canhistoriser = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_HISTORISER));
$canDetruire = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_DETRUIRE));

?>

<h1 class="page-header">
    Affectations de missions spécifiques
</h1>

<div class="filter">
    <?php echo $this->partial('partial/filtre', ['params' => $params, 'themes' => $themes, 'types' => $types, 'missions' => $missions], [], true); ?>
</div>

<div class="main">
    <?php if ($canAjouter) : ?>
        <?php /** @see MissionSpecifiqueAffectationController::ajouterAction */ ?>
        <a href="<?php echo $this->url('mission-specifique-affectation/ajouter', [], ["query" => $params], true); ?>"
           class="btn btn-primary ajax-modal" data-event="modification"
        >
            <span class="icon icon-ajouter"></span>
            Ajouter une mission spécifique
        </a>
    <?php endif; ?>

    <?php if ($affectations === null or empty($affectations)) : ?>
        <br>
        <br>
        <div class="alert alert-info">
            Aucune affectations de trouvés.
        </div>
    <?php else : ?>
        <?php echo $this->affectationsMissionSpecifique($affectations); ?>
    <?php endif; ?>
</div>



<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


