<?php

/**
 * @var string[] $variables
 * @var array $params
 */

?>


<div class="panel panel-default">
    <div class="panel-heading">
        <span class="icon filtrer"></span> Filtre des macros
    </div>
    <div class="panel-body">
        <form method="get" id="filtre" action="<?php echo $this->url(); ?>">
            <div class="row">
                <!-- Variable -------------------------------------------------------- -->
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="variable">Variable associée :</label>
                        <select id="variable" name="variable" class="selectpicker">
                            <option value=""> Tous les variables </option>
                            <?php foreach($variables as $variable) : ?>
                                <option
                                    value="<?php echo $variable; ?>"
                                    <?php if ($variable == $params['variable']) echo " selected "; ?>
                                >
                                    <?php echo $variable; ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <!-- BOUTON -->
                <div class="col-md-3">
                    <br/>
                    <div class="pull-right">
                        <button class="btn btn-primary" id="clear">
                            <span class="icon effacer"></span>
                        </button>

                        <button class="btn btn-primary" id="filter" style="width:20rem;">
                            <span class="icon filtrer"></span>
                            Filtrer
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
    $("form#filtre").submit(function(e){
        e.preventDefault();
    });

    $('button#clear').click(function() {
        window.location.href = 'macro';
    });

    $('button#filter').click(function() {
        let variableId = $('select#variable option:selected').val();
        console.log( "variable=" + variableId);

        let query = "";
        query += "&variable=" + variableId;
        window.location.href = 'macro?'+ query;
    });
</script>