<?php

/**
 * @var FicheMetier $fiche
 */

use Application\Entity\Db\Application;
use Application\Entity\Db\Competence;
use Application\Entity\Db\CompetenceType;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FicheMetierTypeActivite;
use Application\Entity\Db\Formation;

?>

<style>
    h1, h2 {
        color: #123456;
    }

    h1 {
        font-size: 18pt;
    }

    h2 {
        font-size: 16pt;
    }

    h3 {
        font-size: 14pt;
    }

    h4 {
        font-size: 12pt;
    }

    body {
        font-size: 10pt;
    }

    div.activite {
        border-left : 2px solid #123456;
        border-bottom : 1px solid #123456;
        padding-left: 1rem;
        margin-bottom: 1rem;
    }
</style>

<?php
    $activites = $fiche->getActivites();
    usort($activites, function (FicheMetierTypeActivite $a, FicheMetierTypeActivite $b) { return $a->getPosition() < $b->getPosition();});
?>

<h1>
    <?php echo $fiche->getMetier()->getLibelle(); ?>
</h1>

<?php if ($fiche->getMetier()->getEmploiType()) : ?>
    Emploi-type (REFERENS) : <?php echo $fiche->getMetier()->getEmploiType(); ?>
<?php endif; ?>

<h2>Missions principales</h2>
<?php echo $fiche->getMissionsPrincipales(); ?>

<h2>Activités</h2>

<?php foreach($activites as $activite) : ?>
    <?php if ($activite->getActivite()->estNonHistorise()) : ?>
        <div class="activite">
            <h3> <?php echo $activite->getActivite()->getLibelle(); ?> </h3>
            <ul>
            <?php foreach ($activite->getActivite()->getDescriptions() as $description) : ?>
                <li> <?php echo $description->getLibelle(); ?> </li>
            <?php endforeach; ?>
            </ul>
        </div>
    <?php endif ;?>
<?php endforeach; ?>

<h2>Parcours de formation pour la prise de poste</h2>



<?php
$competences = $fiche->getCompetences();
usort($competences, function (Competence $a, Competence $b) { return $a->getLibelle() > $b->getLibelle();});

$types = [];
foreach($competences as $competence) {
    $type = $competence->getType();
    $types[$type->getId()] = $type;
}
usort($types, function(CompetenceType $a, CompetenceType $b) { return $a->getOrdre() > $b->getOrdre();});

$dictionnaire = [];
foreach ($types as $type) $dictionnaire[$type->getLibelle()] = [];
foreach ($competences as $competence) {
    $dictionnaire[$competence->getType()->getLibelle()][] = $competence;
}
?>

<?php if (! empty($competences)) : ?>
    <h3> Compétences </h3>

    <div class="activite">
        <?php foreach ($dictionnaire as $type => $listing) : ?>

            <h4> <?php echo $type; ?> </h4>

            <ul>
                <?php foreach($listing as $item): ?>
                    <li> <?php echo $item->getLibelle(); ?> </li>
                <?php endforeach; ?>
            </ul>

        <?php endforeach; ?>
    </div>
<?php endif; ?>

<?php
$applications = $fiche->getApplications();
usort($applications, function (Application $a, Application $b) { return $a->getLibelle() > $b->getLibelle();});
?>

<?php if (! empty($applications)) : ?>
    <h3> Applications </h3>

    <div class="activite">
        <ul>
            <?php foreach ($applications as $application) : ?>
                <li> <?php echo $application->getLibelle(); ?> </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php
$formations = $fiche->getFormations();
usort($formations, function (Formation $a, Formation $b) { return $a->getLibelle() > $b->getLibelle();});
?>

<?php if (! empty($formations)) : ?>
<h3> Formations </h3>
    <div class="activite">
        <ul>
            <?php foreach ($formations as $formation) : ?>
                <li> <?php echo $formation->getLibelle(); ?> </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
