<?php

/**
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent $agent
 */

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;

// TODO /!\ modification ad'hoc /!\ à supprimer plus tard
//$entretiens = array_filter($entretiens, function (EntretienProfessionnel $e) {
//    return (
//        $e->getEtat()->getCode() !== EntretienProfessionnel::ETAT_ACCEPTATION
//    AND $e->getEtat()->getCode() !== EntretienProfessionnel::ETAT_ACCEPTER) ;
//});
?>

<h2>
    Entretiens professionnels
</h2>

<table class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Annee </th>
        <th> Date </th>
        <th> Responsable </th>
        <th> État </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($entretiens as $entretien) : ?>
        <?php
            $canVoir       = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_AFFICHER);
            $canHistoriser = $this->isAllowed($entretien, EntretienproPrivileges::ENTRETIENPRO_HISTORISER);
            $canSupprimer  = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_DETRUIRE));
        ?>
        <tr>
            <td> <?php echo $entretien->getAnnee(); ?> </td>
            <td> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </td>
            <td> <?php echo $entretien->getResponsable()->getDenomination(); ?> </td>
            <td>
                <?php echo $this->etatbadge($entretien->getEtat()); ?>
            </td>
            <td>
                <?php if ($canVoir) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::renseignerAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <?php if ($entretien->getValidationResponsable() === null OR $entretien->getValidationResponsable()->estHistorise()) : ?>
                            <span class="icon editer" title="Renseigner l'entretien professionnel"></span>
                        <?php else: ?>
                            <span class="icon voir" title="Voir l'entretien professionnel"></span>
                        <?php endif; ?>
                    </a>
                <?php endif; ?>

                <?php if ($canVoir) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::exporterAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/exporter', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon pdf" title="Exporter l'entretien professionnel"></span></a>
                <?php endif; ?>

                <?php if ($canHistoriser AND $entretien->getValidationResponsable() === null) : ?>
                    <?php if ($entretien->estNonHistorise()) : ?>
                        <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::historiserAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/historiser', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser l'entretien professionnel'"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::historiserAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/restaurer', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer l'entretien professionnel"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::detruireAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/detruire', ['entretien' => $entretien->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer définitivement l'entretien professionnel"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>