<?php

/**
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent $agent
 * @var array $droits
 */

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;


$canVoirEntretienPro         = $droits['voir'];
//$canAjouterEntretienPro      = $droits['ajouter'];
//$canModifierEntretienPro     = $droits['modifier'];
$canHistoriserEntretienPro   = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_HISTORISER));
$canDetruireEntretienPro     = $droits['detruire'];
?>

<h2>
    Entretiens professionnels
</h2>

<table class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Annee </th>
        <th> Date </th>
        <th> Responsable </th>
        <th> État </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($entretiens as $entretien) : ?>
        <tr>
            <td> <?php echo $entretien->getAnnee(); ?> </td>
            <td> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </td>
            <td> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </td>
            <td>
                <?php if ($entretien->getValidationResponsable() !== null AND $entretien->getValidationResponsable()->estNonHistorise()) : ?>
                    <span
                            data-toggle="tooltip"
                            data-html="true"
                            title="<?php echo $entretien->getValidationResponsable()->generateTooltipText(); ?>"
                    >
                        <span class="badge" style="background-color:darkgreen">Validé</span>
                    </span>
                <?php else : ?>
                    <?php if ($entretien->getValidationAgent() !== null AND $entretien->getValidationAgent()->estHistorise()) : ?>
                        <span
                                data-toggle="tooltip"
                                data-html="true"
                                title="<?php echo $entretien->getValidationAgent()->generateTooltipText(); ?>"
                        >
                            <span class="badge" style="background-color:darkorange">En attente de validation responsable </span>
                        </span>
                    <?php else : ?>
                        <span class="badge" style="background-color:orangered">En attente de validation agent </span>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirEntretienPro) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::renseignerAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <?php if ($entretien->getValidationResponsable() === null OR $entretien->getValidationResponsable()->estHistorise()) : ?>
                            <span class="icon editer" title="Renseigner l'entretien professionnel"></span></a>
                        <?php else: ?>
                            <span class="icon voir" title="Voir l'entretien professionnel"></span></a>
                        <?php endif; ?>
                <?php endif; ?>

                <?php if ($canVoirEntretienPro) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::exporterAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/exporter', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon pdf" title="Exporter l'entretien professionnel"></span></a>
                <?php endif; ?>

                <?php if ($canHistoriserEntretienPro AND $entretien->getValidationResponsable() === null) : ?>
                    <?php if ($entretien->estNonHistorise()) : ?>
                        <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::historiserAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/historiser', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser l'entretien professionnel'"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::historiserAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/restaurer', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer l'entretien professionnel"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruireEntretienPro) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::detruireAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/detruire', ['entretien' => $entretien->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer définitivement l'entretien professionnel"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>