<?php

/**
 * @var EntretienProfessionnel[] $entretiens
 * @var boolean $isAgent
 * @var Agent $agent
 * @var User $user
 * @var Role $role
 */

use Application\Constant\RoleConstant;
use Application\Entity\Db\Agent;
use Application\Entity\Db\EntretienProfessionnel;
use Application\Provider\Privilege\AgentPrivileges;
use UnicaenUtilisateur\Entity\Db\Role;
use UnicaenUtilisateur\Entity\Db\User;


$canVoirEntretienPro         = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VOIR);
$canAjouterEntretienPro      = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_AJOUTER_EPRO);
$canModifierEntretienPro     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_MODIFIER);
$canHistoriserEntretienPro   = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_HISTORISER);
$canDetruireEntretienPro     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_DETRUIRE);
?>

<h2>
    Entretiens professionnels
    <?php if ($canAjouterEntretienPro) : ?>
        <a
            <?php /** @see \Application\Controller\EntretienProfessionnelController::creerAction() */?>
            href="<?php echo $this->url('entretien-professionnel/creer', [], ['query' => ['agent' => $agent->getId()]], true); ?>" class="ajax-modal" data-event="modification">
            <span class="icon ajouter" title="Ajouter un entretien professionnel pour l'agent"></span>
        </a>
    <?php endif; ?>
</h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Annee </th>
        <th> Date </th>
        <th> Responsable </th>
        <th> État </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($entretiens as $entretien) : ?>
        <tr>
            <td> <?php echo $entretien->getAnnee(); ?> </td>
            <td> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </td>
            <td> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </td>
            <td>
                <?php if ($entretien->getValidationResponsable() !== null) : ?>
                    <span
                            data-toggle="tooltip"
                            data-html="true"
                            title="<?php echo $entretien->getValidationResponsable()->generateTooltipText(); ?>"
                    >
                        <span class="badge" style="background-color:darkgreen">Validé</span>
                    </span>
                <?php else : ?>
                    <?php if ($entretien->getValidationAgent() !== null) : ?>
                        <span
                                data-toggle="tooltip"
                                data-html="true"
                                title="<?php echo $entretien->getValidationAgent()->generateTooltipText(); ?>"
                        >
                            <span class="badge" style="background-color:darkorange">En attente de validation responsable </span>
                        </span>
                    <?php else : ?>
                        <span class="badge" style="background-color:orangered">En attente de validation agent </span>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirEntretienPro) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::afficherAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/afficher', ['entretien' => $entretien->getId()], [], true); ?>"
                        target="_blank"
                    >
                        <span class="icon voir" title="Afficher l'entretien professionnel"></span></a>
                <?php endif; ?>

                <?php if ($canVoirEntretienPro) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::exporterAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/exporter', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon pdf" title="Exporter l'entretien professionnel"></span></a>
                <?php endif; ?>

                <?php if ($canModifierEntretienPro AND $entretien->getValidationResponsable() === null) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::modifierAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], [], true); ?>"
                        target="_blank"
                    >
                        <span class="icon editer" title="Modifier l'entretien professionnel"></span></a>
                <?php endif; ?>

                <?php if ($canHistoriserEntretienPro AND $entretien->getValidationResponsable() === null) : ?>
                    <?php if ($entretien->estNonHistorise()) : ?>
                        <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::historiserAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/historiser', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser l'entretien professionnel'"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::historiserAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/restaurer', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer l'entretien professionnel"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruireEntretienPro) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::detruireAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/detruire', ['entretien' => $entretien->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer définitivement l'entretien professionnel"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>