<?php

/**
 * @var string $url
 * @var Boolean[] $filtres $url
 */
?>

<div class="filtre">
    <form method="get" action="<?php echo $url; ?>">
    <div class="row">
        <div class="col-md-7">
            <label for="titulaire">Titulaire </label>
            <input id="titulaire" name="titulaire" type="checkbox" <?php if ($filtres['titulaire']) echo " checked "; ?>/>
            <label for="cdi">C.D.I. </label>
            <input id="cdi" name="cdi" type="checkbox" <?php if ($filtres['cdi']) echo " checked "; ?>/>
            <label for="cdd">C.D.D. </label>
            <input id="cdd" name="cdd" type="checkbox" <?php if ($filtres['cdd']) echo " checked "; ?>/>
            <br/>
            <label for="administratif">Administratif </label>
            <input id="administratif" name="administratif" type="checkbox" <?php if ($filtres['administratif']) echo " checked "; ?>/>
            <label for="chercheur">Chercheur </label>
            <input id="chercheur" name="chercheur" type="checkbox" <?php if ($filtres['chercheur']) echo " checked "; ?>/>
            <label for="enseignant">Enseignant </label>
            <input id="enseignant" name="enseignant" type="checkbox" <?php if ($filtres['enseignant']) echo " checked "; ?>/>
            <label for="vacataire">Vacataire </label>
            <input id="vacataire" name="vacataire" type="checkbox" <?php if ($filtres['vacataire']) echo " checked "; ?>/>
        </div>
        <div class="col-md-3">
            <button class="btn btn-primary action">
                <span class="icon filtrer"></span>
                Filtrer
            </button>
        </div>
    </div>
    </form>
</div>

<style>
    div.filtre {
        border: 1px #123456 solid;
        background: whitesmoke;
        border-radius : 1rem;
        padding : 1rem;
        margin: 1rem;
    }
    label {
        padding-left: 2rem;
    }
</style>