<?php

/**
 * @var Agent $agent
 * @var AgentStatut[] $statuts
 * @var AgentAffectation[] $affectations
 * @var AgentGrade[] $grades
 * @var AgentEchelon[] $echelons
 * @var Agent[] $superieures
 * @var Agent[] $autorites
 * @var AgentQuotite $quotite
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentAffectation;
use Application\Entity\Db\AgentEchelon;
use Application\Entity\Db\AgentGrade;
use Application\Entity\Db\AgentQuotite;
use Application\Entity\Db\AgentStatut;
use Application\Provider\Privilege\AgentaffichagePrivileges;

// TODO fix that >>>  on rentre dans la mauvaise assertion ... AgentAssertion et non AgentAffichageAssertion
$canAfficherAutorite = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_AUTORITE);
$canAfficherSuperieure = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_SUPERIEUR);
$canAfficherCarriereComplete = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_CARRIERECOMPLETE);
$canAfficherCarriereDate = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_DATERESUME);
$canAfficherInfoSource = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_COMPTE);
$canAfficherTemoinAffectation = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_TEMOIN_AFFECTATION);
$canAfficherTemoinStatut = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_TEMOIN_STATUT);


?>
<h2> Informations générales sur l'agent </h2>

<div class="row">
    <div class="col-md-4">
        <dl>
            <dt> Prénom </dt>
            <dd>
                <?php echo $agent->getPrenom(); ?>
            </dd>
            <dt> Nom </dt>
            <dd>
                <?php echo $agent->getNomUsuel(); ?>
            </dd>
            <dt> Quotité travaillée </dt>
            <dd>
                <?php if($quotite) : ?>
                    <?php echo $quotite->getQuotite(); ?>%
                <?php else: ?>
                    100%
                <?php endif; ?>
            </dd>
        </dl>

        <?php if ($agent->isContratLong() !== true) : ?>
            <div class="alert alert-warning">
                <span class="icon icon-attention"></span> En contrat de moins de 12 mois.
            </div>
        <?php endif; ?>
    </div>
    <div class="col-md-4">
        <?php
            $affectation = $agent->getAffectationPrincipale();
            $structure = ($affectation)?$affectation->getStructure():null;
            $niveau2   = ($structure)?$structure->getNiv2():null;
        ?>
        <?php if ($structure) : ?>
        <dl>
            <dt> Affectation principale </dt>
            <dd>
                <?php echo $structure->getLibelleLong(); ?> <br/>
                <?php if ($niveau2 !== $structure) : ?>
                    Rattaché&middot;e à <?php echo ($niveau2)?$niveau2->getLibelleLong():"aucune structure de renseignée"; ?>
                <?php endif; ?>
            </dd>

            <?php if ($canAfficherAutorite) : ?>
                <dt> Autorité hiérarchique </dt>
                <dd>
                    <?php if ($niveau2) : ?>
                        <?php if ($autorites AND !empty($autorites)) : ?>
                            <ul>
                            <?php foreach ($autorites as $key => $autorite) : ?>
                                <li>
                                    <?php echo $autorite->getDenomination(); ?>
                                    <?php if (substr($key, 0, 10) === "complement") : ?>
                                        <span class="icon icon-information" title="Complément non déduit de la structure"></span>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        <?php else : ?>
                            <span class="probleme">
                                <span class="icon icon-attention"></span>
                                Aucune responsable pour la structure de niveau 2 <?php echo $affectation->getStructure()->getNiv2()->getLibelleLong(); ?>
                            </span>
                        <?php endif; ?>
                    <?php else : ?>
                        <span class="probleme">
                            <span class="icon icon-attention"></span>
                            Aucun·e autorité hiérarchique
                        </span>
                    <?php endif; ?>
                </dd>
            <?php endif; ?>
            <?php if ($canAfficherSuperieure) : ?>
                <dt> Supérieur&middot;e hiérarchique direct&middot;e</dt>
                <dd>
                    <?php if (!empty($superieures)) : ?>
                        <ul>
                            <?php foreach ($superieures as $key => $superieure) : ?>
                                <li> <?php echo $superieure->getDenomination(); ?>
                                    <?php if (substr($key, 0, 10) === "complement") : ?>
                                        <span class="icon icon-information" title="Complément non déduit de la structure"></span>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else : ?>
                        <span class="probleme">
                            <span class="icon icon-attention"></span>
                            Aucun·e supérieur·e hiérarchique direct·e
                        </span>
                    <?php endif; ?>
                </dd>
            <?php endif; ?>
        </dl>
        <?php else : ?>
            <div class="alert alert-danger"> Aucune affectation principale </div>
        <?php endif; ?>
    </div>

    <div class="col-md-4">
        <?php if ($canAfficherInfoSource) : ?>
            <dl>
                <dt> Identifiant sources </dt>
                <dd>
                    <?php echo $agent->getId(); ?> <br/>
                <dt> Compte associé </dt>
                <dd>
                    Agent : <?php echo $agent->getLogin(); ?> <br/> &Rightarrow; <?php echo $agent->getEmail(); ?> <br/>
                    <?php if($agent->getUtilisateur()) : ?>
                        Utilisateur : <?php echo $agent->getUtilisateur()->getUsername(); ?> <br/> &Rightarrow;<?php echo $agent->getUtilisateur()->getEmail(); ?>
                    <?php else: ?>
                        <span class="probleme">
                                <span class="icon icon-attention"></span>
                                Aucun compte lié à l'agent
                            </span>
                    <?php endif; ?>
                </dd>
            </dl>
        <?php endif; ?>
    </div>
</div>

<h2>Carrière et positionnement dans la structure</h2>

<div class="row">
    <div class="col-md-3">
        <h3>Affectation</h3>
        <?php foreach ($affectations as $affectation) : ?>
            <?php echo $this->agentAffectation($affectation, ['structure' => true, 'periode' => $canAfficherCarriereDate, 'temoin' => $canAfficherTemoinAffectation]); ?>
        <?php endforeach; ?>
    </div>
    <div class="col-md-3">
        <h3>Statut</h3>
        <?php foreach ($statuts as $statut) : ?>
            <?php echo $this->agentStatut($statut, ['structure' => true, 'periode' => $canAfficherCarriereDate, 'temoin' => $canAfficherTemoinStatut]); ?>
        <?php endforeach; ?>
    </div>
    <div class="col-md-6">
        <h3>Grade</h3>
        <?php foreach ($grades as $grade) : ?>
            <?php echo $this->agentGrade($grade, ['echelons' => $echelons, 'structure' => true, 'periode' => $canAfficherCarriereDate, 'temoin' => true]); ?>
        <?php endforeach; ?>
    </div>
</div>

<?php if ($canAfficherCarriereComplete) : ?>
<a
    <?php /** @see \Application\Controller\AgentController::afficherStatutsGradesAction() */?>
    href="<?php echo $this->url('agent/afficher-statuts-grades', ['agent' => $agent->getId()], [], true); ?>"
    class="ajax-modal"
>
    <span class="icon icon-voir"></span> Listing de toutes les affectations, statuts et grades
</a>
<?php endif; ?>