<?php

/**
 * @var Agent $agent
 * @var AgentStatut[] $statuts
 * @var AgentAffectation[] $affectations
 * @var AgentGrade[] $grades
 * @var AgentEchelon[] $echelons
 * @var AgentQuotite $quotite
 *
 * @var ChaineAssertion $chaineAssertion
 */

use Agent\Entity\Db\AgentAffectation;
use Agent\Entity\Db\AgentEchelon;
use Agent\Entity\Db\AgentGrade;
use Agent\Entity\Db\AgentQuotite;
use Agent\Entity\Db\AgentStatut;
use Application\Assertion\ChaineAssertion;
use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentAutorite;
use Application\Entity\Db\AgentSuperieur;
use Application\Provider\Privilege\AgentaffichagePrivileges;
use Application\Provider\Privilege\ChainePrivileges;

// TODO fix that >>>  on rentre dans la mauvaise assertion ... AgentAssertion et non AgentAffichageAssertion
$canAfficherAutorite = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_AUTORITE);
$canAfficherSuperieure = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_SUPERIEUR);
$canAfficherCarriereComplete = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_CARRIERECOMPLETE);
$canAfficherCarriereDate = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_DATERESUME);
$canAfficherInfoSource = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_COMPTE);
$canAfficherTemoinAffectation = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_TEMOIN_AFFECTATION);
$canAfficherTemoinStatut = $this->isAllowed($agent, AgentaffichagePrivileges::AGENTAFFICHAGE_TEMOIN_STATUT);

$chaine = new AgentSuperieur();
$chaine->setAgent($agent);

$canModifierChaine = $this->isAllowed(ChainePrivileges::getResourceId(ChainePrivileges::CHAINE_GERER));
$canModifierChaine = $canModifierChaine && $chaineAssertion->computeAssertion($chaine, ChainePrivileges::CHAINE_GERER);
?>
    <h2> Informations générales sur l'agent </h2>

    <div class="row">
        <div class="col-md-4">
            <dl>
                <dt> Prénom</dt>
                <dd>
                    <?php echo $agent->getPrenom(); ?>
                </dd>
                <dt> Nom</dt>
                <dd>
                    <?php echo $agent->getNomUsuel(); ?>
                </dd>
                <dt> Modalité de service</dt>
                <dd>
                    <?php echo $agent->toStringModaliteDeService(); ?>
                </dd>
            </dl>

            <?php if ($agent->isContratLong() !== true) : ?>
                <div class="alert alert-warning">
                    <span class="icon icon-attention"></span> En contrat de moins de 12 mois.
                </div>
            <?php endif; ?>
        </div>
        <div class="col-md-4">
            <?php
            $affectation = $agent->getAffectationPrincipale();
            $structure = ($affectation) ? $affectation->getStructure() : null;
            $niveau2 = ($structure) ? $structure->getNiv2() : null;
            ?>
            <?php if ($structure) : ?>
                <dl>
                    <dt> Affectation principale</dt>
                    <dd>
                        <?php echo $structure->getLibelleLong(); ?> <br/>
                        <?php if ($niveau2 !== $structure) : ?>
                            Rattaché&middot;e à <?php echo ($niveau2) ? $niveau2->getLibelleLong() : "aucune structure de renseignée"; ?>
                        <?php endif; ?>
                    </dd>
                </dl>
            <?php else : ?>
                <div class="alert alert-danger"> Aucune affectation principale</div>
            <?php endif; ?>
        </div>

        <div class="col-md-4">
            <?php if ($canAfficherInfoSource) : ?>
                <dl>
                    <dt> Identifiant source</dt>
                    <dd>
                        <?php echo $agent->getId(); ?>
                    </dd>
                    <dt> Compte associé</dt>
                    <dd>
                        Agent : <?php echo $agent->getLogin(); ?> (<?php echo $agent->getEmail(); ?>)
                        <br/>
                        <?php if ($agent->getUtilisateur()) : ?>
                            Utilisateur : <?php echo $agent->getUtilisateur()->getUsername(); ?>
                            (<?php echo $agent->getUtilisateur()->getEmail(); ?>)
                        <?php else: ?>
                            <span class="probleme">
                                <span class="icon icon-attention"></span>
                                Aucun compte lié à l'agent
                            </span>
                        <?php endif; ?>
                    </dd>
                    <dt> Références</dt>
                    <dd>
                        <?php foreach ($agent->getRefs() as $ref) : ?>
                            <span class="badge"> <?php echo $ref->getSource(); ?>&nbsp;<?php echo $ref->getIdSource(); ?> </span>
                        <?php endforeach; ?>
                    </dd>
                </dl>
            <?php endif; ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?php if ($canAfficherAutorite) : ?>
                <dl>
                    <dt> Autorité hiérarchique</dt>
                    <dd>
                        <?php if ($canModifierChaine) : ?>
                            <a href="<?php echo $this->url('agent/hierarchie/ajouter', ['agent' => $agent->getId(), 'type' => "autorite"], [], true); ?>"
                               class="ajax-modal btn btn-primary" data-event="modification"
                            >
                                <span class="icon icon-ajouter"></span>
                                Ajouter une autorité
                            </a>
                        <?php endif; ?>
                        <?php $autorites = $agent->getAutorites($canModifierChaine); ?>
                        <?php usort($autorites, function (AgentAutorite $a, AgentAutorite $b) { return $a->getAutorite()->getDenomination() <=> $b->getAutorite()->getDenomination(); }); ?>
                        <?php if (!empty($autorites)) : ?>
                            <ul>
                                <?php foreach ($autorites as $autorite) : ?>
                                    <li>
                                        <span class=" <?php if ($autorite->estHistorise()) echo " historise "; ?> ">
                                            <span class="badge"> <?php echo $autorite->getSourceId(); ?> </span>
                                            <?php echo $autorite->getAutorite()->getDenomination(); ?>
                                        </span>

                                        <?php if ($canModifierChaine) : ?>
                                            <?php if ($autorite->getSourceId() === 'EMC2') : ?>
                                                <?php /** @see \Application\Controller\AgentHierarchieController::modifierAction() */ ?>
                                                <a href="<?php echo $this->url('agent/hierarchie/modifier', ['chaine' => $autorite->getId(), 'type' => 'autorite'], [], true); ?>"
                                                   class="ajax-modal action primary" data-event="modification">
                                                    <span class="icon icon-modifier"></span>
                                                    Modifier
                                                </a>
                                                <?php /** @see \Application\Controller\AgentHierarchieController::supprimerAction() */ ?>
                                                <a href="<?php echo $this->url('agent/hierarchie/supprimer', ['chaine' => $autorite->getId(), 'type' => 'autorite'], [], true); ?>"
                                                   class="ajax-modal action danger" data-event="modification">
                                                    <span class="icon icon-unchecked"></span>
                                                    Supprimer
                                                </a>
                                            <?php else : ?>
                                                <?php if ($autorite->estHistorise()) : ?>
                                                    <?php /** @see \Application\Controller\AgentHierarchieController::restaurerAction() */ ?>
                                                    <a href="<?php echo $this->url('agent/hierarchie/restaurer', ['chaine' => $autorite->getId(), 'type' => 'autorite'], [], true); ?>"
                                                       class="action warning">
                                                        <span class="icon icon-restaurer"></span>
                                                        Ré-établir
                                                    </a>
                                                <?php else : ?>
                                                    <?php /** @see \Application\Controller\AgentHierarchieController::historiserAction() */ ?>
                                                    <a href="<?php echo $this->url('agent/hierarchie/historiser', ['chaine' => $autorite->getId(), 'type' => 'autorite'], [], true); ?>"
                                                       class="action warning">
                                                        <span class="icon icon-historiser"></span>
                                                        Révoquer
                                                    </a>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else : ?>
                            <div class="alert alert-warning">
                                <span class="icon icon-attention"></span>
                                Aucun·e autorité hiérarchique
                            </div>
                        <?php endif; ?>
                    </dd>
                </dl>
            <?php endif; ?>
        </div>
        <div class="col-md-6">
            <?php if ($canAfficherSuperieure) : ?>
                <dl>
                    <dt> Supérieur&middot;e hiérarchique direct&middot;e</dt>
                    <dd>
                        <?php if ($canModifierChaine) : ?>
                            <a href="<?php echo $this->url('agent/hierarchie/ajouter', ['agent' => $agent->getId(), 'type' => "superieur"], [], true); ?>"
                               class="ajax-modal btn btn-primary" data-event="modification"
                            >
                                <span class="icon icon-ajouter"></span>
                                Ajouter un·e supérieur·e
                            </a>
                        <?php endif; ?>
                        <?php $superieures = $agent->getSuperieurs($canModifierChaine); ?>
                        <?php usort($superieures, function (AgentSuperieur $a, AgentSuperieur $b) { return $a->getSuperieur()->getDenomination() <=> $b->getSuperieur()->getDenomination(); }); ?>
                        <?php if (!empty($superieures)) : ?>
                            <ul>
                                <?php foreach ($superieures as $superieure) : ?>
                                    <li>
                                        <span class=" <?php if ($superieure->estHistorise()) echo " historise "; ?> ">
                                            <span class="badge"> <?php echo $superieure->getSourceId(); ?> </span>
                                            <?php echo $superieure->getSuperieur()->getDenomination(); ?>
                                        </span>

                                        <?php if ($canModifierChaine) : ?>
                                            <?php if ($superieure->getSourceId() === 'EMC2') : ?>
                                                <?php /** @see \Application\Controller\AgentHierarchieController::modifierAction() */ ?>
                                                <a href="<?php echo $this->url('agent/hierarchie/modifier', ['chaine' => $superieure->getId(), 'type' => 'superieur'], [], true); ?>"
                                                   class="ajax-modal action primary" data-event="modification">
                                                    <span class="icon icon-modifier"></span>
                                                    Modifier
                                                </a>
                                                <?php /** @see \Application\Controller\AgentHierarchieController::supprimerAction() */ ?>
                                                <a href="<?php echo $this->url('agent/hierarchie/supprimer', ['chaine' => $superieure->getId(), 'type' => 'superieur'], [], true); ?>"
                                                   class="ajax-modal action danger" data-event="modification">
                                                    <span class="icon icon-unchecked"></span>
                                                    Supprimer
                                                </a>
                                            <?php else : ?>
                                                <?php if ($superieure->estHistorise()) : ?>
                                                    <?php /** @see \Application\Controller\AgentHierarchieController::restaurerAction() */ ?>
                                                    <a href="<?php echo $this->url('agent/hierarchie/restaurer', ['chaine' => $superieure->getId(), 'type' => 'superieur'], [], true); ?>"
                                                       class="action warning">
                                                        <span class="icon icon-restaurer"></span>
                                                        Ré-établir
                                                    </a>
                                                <?php else : ?>
                                                    <?php /** @see \Application\Controller\AgentHierarchieController::historiserAction() */ ?>
                                                    <a href="<?php echo $this->url('agent/hierarchie/historiser', ['chaine' => $superieure->getId(), 'type' => 'superieur'], [], true); ?>"
                                                       class="action warning">
                                                        <span class="icon icon-historiser"></span>
                                                        Révoquer
                                                    </a>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else : ?>
                            <div class="alert alert-warning">
                                <span class="icon icon-attention"></span>
                                Aucun·e supérieur·e hiérarchique direct·e
                            </div>
                        <?php endif; ?>
                    </dd>
                </dl>
            <?php endif; ?>
        </div>
    </div>

    <h2>Carrière et positionnement dans la structure</h2>

    <div class="row">
        <div class="col-md-3">
            <h3>Affectation</h3>
            <?php foreach ($affectations as $affectation) : ?>
                <?php echo $this->agentAffectation($affectation, ['structure' => true, 'periode' => $canAfficherCarriereDate, 'temoin' => $canAfficherTemoinAffectation]); ?>
            <?php endforeach; ?>
        </div>
        <div class="col-md-3">
            <h3>Statut</h3>
            <?php foreach ($statuts as $statut) : ?>
                <?php echo $this->agentStatut($statut, ['structure' => true, 'periode' => $canAfficherCarriereDate, 'temoin' => $canAfficherTemoinStatut]); ?>
            <?php endforeach; ?>
        </div>
        <div class="col-md-6">
            <h3>Grade</h3>
            <?php foreach ($grades as $grade) : ?>
                <?php echo $this->agentGrade($grade, ['echelons' => $echelons, 'structure' => true, 'periode' => $canAfficherCarriereDate, 'temoin' => true]); ?>
            <?php endforeach; ?>
        </div>
    </div>

<?php if ($canAfficherCarriereComplete) : ?>
    <a
        <?php /** @see \Application\Controller\AgentController::afficherStatutsGradesAction() */ ?>
            href="<?php echo $this->url('agent/afficher-statuts-grades', ['agent' => $agent->getId()], [], true); ?>"
            class="ajax-modal"
    >
        <span class="icon icon-voir"></span> Listing de toutes les affectations, statuts et grades
    </a>
<?php endif; ?>