<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentMissionSpecifique;
use Application\Provider\Privilege\MissionspecifiqueaffectationPrivileges;

/**
 * @var AgentMissionSpecifique[] $missions
 * @var Agent $agent
 */

$canVoirMission         = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_AFFICHER));
$canExporterMission     = $canVoirMission;
$canAjouterMission      = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_MODIFIER));
$canModifierMission     = $canAjouterMission;
$canHistoriserMission   = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_HISTORISER));
$canDetruireMission     = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_DETRUIRE));

?>

<span id="mission_specifique"></span>
<br/>
<br/>

<div class="row">
    <div class="col-md-8">
        <h2> Missions spécifiques </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterMission) : ?>
            <br/>
            <a
                <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::ajouterAction() */?>
                href="<?php echo $this->url('mission-specifique-affectation/ajouter', [], ['query' => ['agent' => $agent->getId()]], true); ?>"
                class="ajax-modal btn btn-primary action"
                data-event="modification"
            >
                <span class="icon icon-ajouter"></span>
                Ajouter une mission spécifique
            </a>
        <?php endif; ?>
    </div>
</div>

<div class="alert alert-info">
    <span class="icon icon-information"></span>
    Les missions spécifiques appartiennent à un référentiel déterminé par la Direction des Ressources Humaines.<br/>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Elles sont affectées aux agents par leurs responsables hiérarchiques.
</div>
<br/>

<table class="table table-condensed datatable">
    <thead>
    <tr>
        <th> Missions </th>
        <th> Structure </th>
        <th> Début </th>
        <th> Fin </th>
        <th> Volume horaire </th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php $cumulDecharge = 0; ?>
    <?php foreach ($missions as $mission) : ?>
        <?php if ($canDetruireMission OR $mission->estNonHistorise()) : ?>
            <tr class="
            <?php if (!$mission->estEnCours()) echo " termine "; ?>
            <?php if ($mission->estHistorise()) echo " historise "; ?>
            "
        >
            <td> <?php echo $mission->getMission()->getLibelle(); ?> </td>
            <td>
                <?php if ($mission->getStructure() === null) : ?>
                    Aucune structure
                <?php else : ?>
                    <?php echo $mission->getStructure()->getLibelleLong(); ?>
                <?php endif; ?>
            </td>
            <td> <?php echo ($mission->getDateDebut())?$mission->getDateDebut()->format('d/m/Y'):"---"; ?> </td>
            <td> <?php echo ($mission->getDateFin())?$mission->getDateFin()->format('d/m/Y'):"---"; ?> </td>
            <td>
                <?php if ($mission->getDecharge() !== null) : ?>
                    <?php echo $mission->getDecharge(); ?> h.
                    <?php if ($mission->estEnCours()) $cumulDecharge += $mission->getDecharge(); ?>
                <?php else : ?>
                    Aucun
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirMission) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::afficherAction() */?>
                        href="<?php echo $this->url('mission-specifique-affectation/afficher', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                        class="ajax-modal"
                    >
                        <span class="icon icon-voir"></span></a>
                <?php endif; ?>
                <?php if ($canExporterMission /**AND $mission->estEnCours()**/) : ?>
                    <?php /** @see MissionSpecifiqueAffectationController::genererLettreTypeAction() */ ?>
                    <a href="<?php echo $this->url('mission-specifique-affectation/generer-lettre-type', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                       target="_blank"
                    >
                        <span class="icon icon-pdf"  data-bs-toggle="tooltip" data-bs-html="true"
                              title="Générer la lettre type associée l'affectation"></span></a>
                <?php endif; ?>
                <?php if ($canModifierMission) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::modifierAction() */?>
                        href="<?php echo $this->url('mission-specifique-affectation/modifier', ['agent-mission-specifique' => $mission->getId()], ['query' => ['agent' => $agent->getId()]], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon icon-editer"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriserMission) : ?>
                    <?php if ($mission->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::historiserAction() */?>
                            href="<?php echo $this->url('mission-specifique-affectation/historiser', ['agent-mission-specifique' => $mission->getId()], ["query" => ["retour" => $this->url('agent/afficher', ['agent' => $agent->getId()], ['fragment' => 'mission_specifique'], true)]], true); ?>"
                        >
                            <span class="icon icon-historiser"></span></a>
                    <?php else : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::restaurerAction() */?>
                            href="<?php echo $this->url('mission-specifique-affectation/restaurer', ['agent-mission-specifique' => $mission->getId()], ["query" => ["retour" => $this->url('agent/afficher', ['agent' => $agent->getId()], ['fragment' => 'mission_specifique'], true)]], true); ?>"
                        >
                            <span class="icon icon-restaurer"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruireMission) : ?>
                    <a
                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::detruireAction() */?>
                        href="<?php echo $this->url('mission-specifique-affectation/detruire', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon icon-retirer"></span></a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<?php if ($cumulDecharge !== 0) : ?>
    <u>Cumul des décharges associées aux missions spécifiques :</u> &nbsp;
    <?php echo $cumulDecharge; ?> heures
<?php endif; ?>