<?php

/**
 * @var string $current
 * @var Campagne|null $campagne
 */

use EntretienProfessionnel\Entity\Db\Campagne;

?>


<div class="nav nav-tabs" id="nav-tab" role="tablist">
    <?php /** @see \Application\Controller\AgentController::mesAgentsAction() */ ?>
    <button class="nav-link" id="agents-tab"
            data-bs-toggle="tab" data-bs-target="#agents"
            type="button" role="tab" aria-controls="agents" aria-selected="true"
            onclick="location.href='<?php echo $this->url('mes-agents', [],[], true); ?>'"
    >
        Liste des Agent·es
    </button>
    <?php /** @see \Structure\Controller\StructureController::fichesDePosteAction() */ ?>
    <button class="nav-link" id="fiches-de-poste-tab"
            data-bs-toggle="tab" data-bs-target="#fiches-de-poste"
            type="button" role="tab" aria-controls="fiches-de-poste" aria-selected="true"
            onclick="location.href='<?php echo $this->url('mes-fiches-postes', [],[], true); ?>'"
    >
        Fiches de poste
    </button>
    <?php /** @see \Structure\Controller\StructureController::mesMissionsSpecifiquesAction() */ ?>
    <button class="nav-link" id="mission-specifique-tab"
            data-bs-toggle="tab" data-bs-target="#mission-specifique"
            type="button" role="tab" aria-controls="mission-specifique" aria-selected="true"
            onclick="location.href='<?php echo $this->url('mes-missions-specifiques', [],[], true); ?>'"
    >
        Missions spécifiques
    </button>
    <?php /** @see \EntretienProfessionnel\Controller\CampagneController::superieurAction()Action() */ ?>
    <button class="nav-link" id="campagnes-precedentes-tab"
            data-bs-toggle="tab" data-bs-target="#campagnes-precedentes"
            type="button" role="tab" aria-controls="campagnes-precedentes" aria-selected="true"
            onclick="location.href='<?php //echo $this->url('entretien-professionnel/campagne/structure', ['structure' => $structure->getId(), 'campagne' => $campagne->getId()],[],true); ?>'"
    >
        Campagnes précédentes
    </button>
    <?php if ($campagne !== null) : ?>
        <?php /** @see \EntretienProfessionnel\Controller\CampagneController::structureAction() */ ?>
        <button class="nav-link" id="campagne<?php echo $campagne->getId(); ?>-tab"
                data-bs-toggle="tab" data-bs-target="#campagne-active"
                type="button" role="tab" aria-controls="campagne-active" aria-selected="true"
                onclick="location.href='<?php //echo $this->url('entretien-professionnel/campagne/structure', ['structure' => $structure->getId(), 'campagne' => $campagne->getId()],[],true); ?>'"
        >
            Campagne active
        </button>
    <?php endif; ?>
</div>

<script>
    $('button[aria-controls="<?php echo $current; ?>"]').addClass('active');
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
    //$(function() {
    //    $('select#structure-selecteur').change(function() {
    //        let id = $('select#structure-selecteur option:selected').val();
    //        if (id !== "" && id !== "<?php //echo $structure->getId(); ?>//") {
    //            window.location.href = './' + id;
    //        }
    //    });
    //});

</script>
