<?php

/**
 * @var Agent $agent
 * @var array $parcoursArray ('type' => ParcoursDeFormation[])
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\ParcoursDeFormation;
use Application\Provider\Privilege\AgentPrivileges;

$canValidate = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VALIDER);
?>

<div class="row" style="margin: 1rem;">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <?php ksort($parcoursArray); ?>
        <?php foreach ($parcoursArray as $subparcours) : ?>
            <?php foreach ($subparcours as $parcours) : ?>
                <?php echo $this->parcoursDeFormation($parcours, $agent, ['mode' => 'modification', 'modification' => $canValidate]); ?>
            <?php endforeach; ?>
        <?php endforeach; ?>

        <?php
        $fiche = $agent->getFichePosteActif();
        if($fiche !== null) : ?>
            <?php echo $this->parcoursApplication($fiche, $agent, ['mode' => 'modification', 'modification' => $canValidate]); ?>
        <?php endif; ?>
    </div>
</div>