<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentAccompagnement;
use Application\Entity\Db\AgentTutorat;
use Application\Provider\Privilege\AgentPrivileges;

/**
 * @var Agent $agent
 * @var AgentTutorat[] $tutorats
 * @var AgentAccompagnement[] $accompagnements
 */

$canAjouterPPP      = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_GESTION_CCC));
$canModifierPPP     = $canAjouterPPP;
$canHistoriserPPP   = $canAjouterPPP;
$canDetruirePPP     = $canAjouterPPP;

?>

<!-- TUTORATS --------------------------------------------------------------------------------------------------------->

<div class="row">
    <div class="col-md-8">
        <h2>
            Tutorats
            <span class="badge"><?php echo count($tutorats); ?></span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterPPP) : ?>
            <?php /** @see \Application\Controller\AgentController::ajouterTutoratAction() */ ?>
            <a href="<?php echo $this->url('agent/tutorat/ajouter', ['agent' => $agent->getId()], [], true); ?>"
               class="btn btn-primary action ajax-modal" data-event="modification"
            >
                <span class="icon icon-ajouter"> </span>
                Ajouter un tutorat
            </a>
        <?php endif; ?>
    </div>
</div>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Agent </th>
        <th> Métier </th>
        <th> Période </th>
        <th> Compléments </th>
        <th> Formation </th>
        <th> État </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($tutorats as $accompagnement) : ?>
        <tr <?php if ($accompagnement->estHistorise()) echo " class='historise' "; ?>>
            <td> <?php echo $accompagnement->getCible()->getDenomination(); ?> </td>
            <td> <?php echo ($accompagnement->getMetier())?$accompagnement->getMetier()->getLibelle():"Aucun"; ?> </td>
            <td>
                <?php echo $accompagnement->getDateDebutToString(); ?>
                &rightarrow;
                <?php echo $accompagnement->getDateFintoString(); ?>
            </td>
            <td> <?php echo $accompagnement->getComplement(); ?> </td>
            <td>
                <?php if ($accompagnement->getFormation() !== null) : ?>
                        <?php if ($accompagnement->getFormation() === true) : ?>
                            <span style="color:darkgreen;"><span class="icon icon-checked" ></span> Formé&middot;e</span>
                        <?php else: ?>
                            <span style="color:darkred;"><span class="icon icon-unchecked" ></span> Non formé&middot;e</span>
                        <?php endif; ?>
                <?php else : ?>
                    Non renseigné
                <?php endif; ?>
            </td>
            <td> <?php echo $this->etatbadge($accompagnement->getEtat()); ?> </td>
            <td>
                <?php if ($canModifierPPP) : ?>
                    <?php /** @see \Application\Controller\AgentController::modifierTutoratAction() */ ?>
                    <a href="<?php echo $this->url('agent/tutorat/modifier', ['tutorat' => $accompagnement->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-editer"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriserPPP) : ?>
                    <?php if ($accompagnement->estNonHistorise()) : ?>
                        <?php /** @see \Application\Controller\AgentController::historiserTutoratAction() */ ?>
                        <a href="<?php echo $this->url('agent/tutorat/historiser', ['tutorat' => $accompagnement->getId()], [], true); ?>"
                        >
                            <span class="icon icon-historiser"></span></a>
                    <?php else : ?>
                        <?php /** @see \Application\Controller\AgentController::restaurerTutoratAction() */ ?>
                        <a href="<?php echo $this->url('agent/tutorat/restaurer', ['tutorat' => $accompagnement->getId()], [], true); ?>"
                        >
                            <span class="icon icon-restaurer"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruirePPP) : ?>
                    <?php /** @see \Application\Controller\AgentController::detruireTutoratAction() */ ?>
                    <a href="<?php echo $this->url('agent/tutorat/detruire', ['tutorat' => $accompagnement->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-unchecked"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<!-- ACCOMPAGNEMENT --------------------------------------------------------------------------------------------------->

<div class="row">
    <div class="col-md-8">
        <h2>
            Accompagnements
            <span class="badge"><?php echo count($accompagnements); ?></span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterPPP) : ?>
            <?php /** @see \Application\Controller\AgentController::ajouterAccompagnementAction() */ ?>
            <a href="<?php echo $this->url('agent/accompagnement/ajouter', ['agent' => $agent->getId()], [], true); ?>"
               class="btn btn-primary action ajax-modal" data-event="modification"
            >
                <span class="icon icon-ajouter"> </span>
                Ajouter un accompagnement
            </a>
        <?php endif; ?>
    </div>
</div>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Agent </th>
        <th> Correspondance </th>
        <th> Corps </th>
        <th> Période </th>
        <th> Compléments </th>
        <th> Résultat </th>
        <th> État </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($accompagnements as $accompagnement) : ?>
        <tr <?php if ($accompagnement->estHistorise()) echo " class='historise' "; ?>>
            <td> <?php echo $accompagnement->getCible()->getDenomination(); ?> </td>
            <td>
                <?php if ($accompagnement->getBap()) : ?>
                    <?php echo $this->correspondance($accompagnement->getBap()); ?>
                <?php else : ?>
                    Aucun
                <?php endif; ?>
            </td>>
            <td> <?php echo ($accompagnement->getCorps())?$accompagnement->getCorps()->getLibelleCourt():"Aucun"; ?> </td>
            <td>
                <?php echo $accompagnement->getDateDebutToString(); ?>
                &rightarrow;
                <?php echo $accompagnement->getDateFintoString(); ?>
            </td>
            <td> <?php echo $accompagnement->getComplement(); ?> </td>
            <td>
                <?php if ($accompagnement->getResultat() !== null) : ?>
                    <?php if ($accompagnement->getResultat() === true) : ?>
                        <span style="color:darkgreen;"><span class="icon icon-checked" ></span> Réussi</span>
                    <?php else: ?>
                        <span style="color:darkred;"><span class="icon icon-unchecked" ></span> Échoué</span>
                    <?php endif; ?>
                <?php else : ?>
                    Non renseigné
                <?php endif; ?>
            </td>
            <td> <?php echo $this->etatbadge($accompagnement->getEtat()); ?> </td>
            <td>
                <?php if ($canModifierPPP) : ?>
                    <?php /** @see \Application\Controller\AgentController::modifierAccompagnementAction() */ ?>
                    <a href="<?php echo $this->url('agent/accompagnement/modifier', ['accompagnement' => $accompagnement->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-editer"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriserPPP) : ?>
                    <?php if ($accompagnement->estNonHistorise()) : ?>
                        <?php /** @see \Application\Controller\AgentController::historiserAccompagnementAction() */ ?>
                        <a href="<?php echo $this->url('agent/accompagnement/historiser', ['accompagnement' => $accompagnement->getId()], [], true); ?>"
                        >
                            <span class="icon icon-historiser"></span></a>
                    <?php else : ?>
                        <?php /** @see \Application\Controller\AgentController::restaurerAccompagnementAction() */ ?>
                        <a href="<?php echo $this->url('agent/accompagnement/restaurer', ['accompagnement' => $accompagnement->getId()], [], true); ?>"
                        >
                            <span class="icon icon-restaurer"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruirePPP) : ?>
                    <?php /** @see \Application\Controller\AgentController::detruireAccompagnementAction() */ ?>
                    <a href="<?php echo $this->url('agent/accompagnement/detruire', ['accompagnement' => $accompagnement->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-unchecked"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
