<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentTutorat;
use Application\Provider\Privilege\AgentPrivileges;

/**
 * @var Agent $agent
 * @var AgentTutorat[] $tutorats
 * @var AgentAccompagent[] $accompagnements
 */

$canAjouterPPP      = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_GESTION_CCC));
$canModifierPPP     = $canAjouterPPP;
$canHistoriserPPP   = $canAjouterPPP;
$canDetruirePPP     = $canAjouterPPP;

?>

<div class="row">
    <div class="col-md-8">
        <h2>
            Tutorats
            <span class="badge"><?php echo count($tutorats); ?></span>
        </h2>
    </div>
    <div class="pull-right">
        <?php if ($canAjouterPPP) : ?>
            <?php /** @see \Application\Controller\AgentController::ajouterTutoratAction() */ ?>
            <a href="<?php echo $this->url('agent/tutorat/ajouter', ['agent' => $agent->getId()], [], true); ?>"
               class="btn btn-primary action ajax-modal" data-event="modification"
            >
                <span class="icon ajouter"> </span>
                Ajouter un tutorat
            </a>
        <?php endif; ?>
    </div>
</div>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Agent </th>
        <th> Métier </th>
        <th> Période </th>
        <th> Compléments </th>
        <th> Formation </th>
        <th> État </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($tutorats as $tutorat) : ?>
        <tr <?php if ($tutorat->estHistorise()) echo " class='historise' "; ?>>
            <td> <?php echo $tutorat->getCible()->getDenomination(); ?> </td>
            <td> <?php echo ($tutorat->getMetier())?$tutorat->getMetier()->getLibelle():"Aucun"; ?> </td>
            <td>
                <?php echo $tutorat->getDateDebutToString(); ?>
                &rightarrow;
                <?php echo $tutorat->getDateFintoString(); ?>
            </td>
            <td> <?php echo $tutorat->getComplement(); ?> </td>
            <td>
                <?php if ($tutorat->getFormation() !== null) : ?>
                        <?php if ($tutorat->getFormation() === true) : ?>
                            <span style="color:darkgreen;"><span class="icon ok" ></span> Formé&middot;e</span>
                        <?php else: ?>
                            <span style="color:darkred;"><span class="icon ko" ></span> Non formé&middot;e</span>
                        <?php endif; ?>
                <?php else : ?>
                    Non renseigné
                <?php endif; ?>
            </td>
            <td> <?php echo $this->etatbadge($tutorat->getEtat()); ?> </td>
            <td>
                <?php if ($canModifierPPP) : ?>
                    <?php /** @see \Application\Controller\AgentController::modifierTutoratAction() */ ?>
                    <a href="<?php echo $this->url('agent/tutorat/modifier', ['tutorat' => $tutorat->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                    >
                        <span class="icon editer"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriserPPP) : ?>
                    <?php if ($tutorat->estNonHistorise()) : ?>
                        <?php /** @see \Application\Controller\AgentController::historiserTutoratAction() */ ?>
                        <a href="<?php echo $this->url('agent/tutorat/historiser', ['tutorat' => $tutorat->getId()], [], true); ?>"
                        >
                            <span class="icon historiser"></span></a>
                    <?php else : ?>
                        <?php /** @see \Application\Controller\AgentController::restaurerTutoratAction() */ ?>
                        <a href="<?php echo $this->url('agent/tutorat/restaurer', ['tutorat' => $tutorat->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruirePPP) : ?>
                    <?php /** @see \Application\Controller\AgentController::detruireTutoratAction() */ ?>
                    <a href="<?php echo $this->url('agent/tutorat/detruire', ['tutorat' => $tutorat->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
