<?php

/**
 * @see \Application\Controller\ConfigurationController::indexAction()
 * @var ConfigurationFicheMetier[] $applications
 * @var ConfigurationFicheMetier[] $competences
 * @var ConfigurationFicheMetier[] $formations
 * @var ConfigurationEntretienProfessionnel[] $recopies
 * @var Champ[] $champsCREP
 * @var Champ[] $champsCREF
 */

use Application\Entity\Db\ConfigurationEntretienProfessionnel;
use Application\Entity\Db\ConfigurationFicheMetier;
use Application\Provider\Privilege\ConfigurationPrivileges;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use UnicaenAutoform\Entity\Db\Champ;

$canAjouter     = $this->isAllowed(ConfigurationPrivileges::getResourceId(ConfigurationPrivileges::CONFIGURATION_AJOUTER));
$canModifier     = $this->isAllowed(ConfigurationPrivileges::getResourceId(ConfigurationPrivileges::CONFIGURATION_AJOUTER));
$canDetruire    = $this->isAllowed(ConfigurationPrivileges::getResourceId(ConfigurationPrivileges::CONFIGURATION_DETRUIRE));
$canReappliquer = $this->isAllowed(ConfigurationPrivileges::getResourceId(ConfigurationPrivileges::CONFIGURATION_REAPPLIQUER));

$this->headTitle("Configuration de l'application");
?>

<h1 class="page-header">
    Configuration de l'application
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="fiche-metier-tab"
                data-bs-toggle="tab" data-bs-target="#fiche-metier"
                type="button" role="tab" aria-controls="fiche-metier" aria-selected="true">
            Fiche métier
        </button>
        <button class="nav-link" id="mail-tab"
                data-bs-toggle="tab" data-bs-target="#entretien-pro"
                type="button" role="tab" aria-controls="entretien-pro" aria-selected="true">
            Entretien Professionnel
        </button>
    </div>


    <div class="tab-content">
                <!-- ONGLET FICHE METIER ------------------------------------------------------------------------------>
                <div id="fiche-metier" class="tab-pane " role="tabpanel">
                    <h2> Configuration des fiches métiers</h2>

                    <?php if ($canReappliquer) : ?>
                        <?php /** @see \Application\Controller\ConfigurationController::reappliquerConfigurationFicheMetierAction() */ ?>
                        <a href="<?php echo $this->url('configuration/reappliquer-configuration-fiche-metier', [], [], true); ?>" class="btn btn-primary action">
                            <span class="icon icon-synchroniser"></span>
                            Ré-appliquer sur toutes les fiches
                        </a>
                    <?php endif; ?>

                    <?php echo $this->partial('partial/configuration-fiche-metier', ['display' => 'Applications', 'type' => 'application', 'configurations' => $applications, 'canAjouter' => $canAjouter, 'canDetruire' => $canDetruire]); ?>
                    <?php echo $this->partial('partial/configuration-fiche-metier', ['display' => 'Compétences',  'type' => 'competence',  'configurations' => $competences , 'canAjouter' => $canAjouter, 'canDetruire' => $canDetruire]); ?>
                </div>

                <!-- ONGLET ENTRETIEN PROFESSIONNEL ------------------------------------------------------------------->
                <div id="entretien-pro" class="tab-pane " role="tabpanel">
                    <h2> Configuration des entretiens professionnels.</h2>

                    <div class="alert alert-info">
                        Les éléments paramètrables de l'entretien professionnel sont :
                        <ul>
                            <li> la période durant laquelle l'agent peut modifier son entretien <span class="todo">TODO</span> ; </li>
                            <li> les champs qui sont repris d'une année à l'autre ; </li>
                            <li> les conditions pour la reprise de donnée ;</li>
                            <li> integerface de configuration<span class="todo">TODO</span>.</li>
                        </ul>
                    </div>

                    <h3> Période durant laquel un agent peut modifier un entretien </h3>

                    <ul>
                        <li>Un agent peut modifier un de ses entretiens professionnels de <em>sa date de création jusqu'à la date de l'entretien</em>.</li>
                        <li>Le <em>responsable de l'entretien peut empécher toute modification</em> via une option de l'entretien professionnel<span class="todo">TODO</span>.</li>
                    </ul>

                    <h3> Règle de reprise des données </h3>

                    <ul>
                        <li>Les données du plus récent entretien (par rapport à l'entretien courant) seront reprises.</li>
                    </ul>

                    <p>
                        <u>NB:</u> On peut imaginer plus de chose comme seulement entretien de l'an passé, verifier qu'il n'y a pas eu de changement de poste, ... <span class="todo">TODO</span>
                    </p>

                    <h3> Champs transferables d'un entretien professionnel à un autre </h3>

                    <p>
                        Possibilité lors de la création d'un entretien profesionnel de reprendre des données d'un champ A et de les insérer dans un champ B.
                    </p>

                    <?php if ($canAjouter): ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\ConfigurationController::ajouterRecopieAction() */ ?>
                                href="<?php echo $this->url("configuration/ajouter-recopie", ['formulaire' => EntretienProfessionnel::FORMULAIRE_CREP], [], true); ?>"
                                class="btn btn-primary ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon icon-ajouter"></span> Ajouter une recopie pour la partie CREP
                        </a>
                    <?php endif; ?>

                    <?php if ($canAjouter): ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\ConfigurationController::ajouterRecopieAction() */ ?>
                                href="<?php echo $this->url("configuration/ajouter-recopie", ['formulaire' => EntretienProfessionnel::FORMULAIRE_CREF], [], true); ?>"
                                class="btn btn-primary ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon icon-ajouter"></span> Ajouter une recopie pour la partie CREF
                        </a>
                    <?php endif; ?>

                    <table class="table table-condensed datatable" id="recopies">
                        <thead>
                        <tr>
                            <th> Formulaire </th>
                            <th> Précédent entretien </th>
                            <th> Entretien courant </th>
                            <th> Action </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($recopies as $recopie) : ?>
                            <?php
                            [$form, $ids] = explode("|",$recopie->getValeur());
                            $champs = [];
                            switch($form) {
                                case 'CREP': $champs = $champsCREP; break;
                                case 'CREF': $champs = $champsCREF; break;
                            }
                            [$previousId, $currentId] = explode(";", $ids);
                            $previous = null;

                            if (isset($champs[$previousId])) $previous = $champs[$previousId];
                            $current = null;
                            if (isset($champs[$currentId])) $current = $champs[$currentId];
                            ?>
                            <tr>
                                <td>
                                    <?php echo $form; ?>
                                </td>
                                <td>
                                    <?php if ($previous !== null) : ?>
                                        <?php echo $previous->getCategorie()->getLibelle()." > ".$previous->getLibelle() ; ?>
                                    <?php else : ?>
                                        Id: <?php echo $previousId; ?> non connu;
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php if ($current !== null) : ?>
                                        <?php echo $current->getCategorie()->getLibelle()." > ".$current->getLibelle() ; ?>
                                    <?php else : ?>
                                        Id: <?php echo $currentId; ?> non connu;
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php if ($canModifier): ?>
                                        <a
                                            <?php /** @see \EntretienProfessionnel\Controller\ConfigurationController::modifierRecopieAction() */ ?>
                                                href="<?php echo $this->url("configuration/modifier-recopie", ['recopie' => $recopie->getId(), 'formulaire' => $form], [], true); ?>"
                                                title="Modifier la recopie"
                                                class="ajax-modal" data-event="modification"
                                        >
                                            <span class="icon icon-editer"></span></a>
                                    <?php endif; ?>
                                    <?php if ($canDetruire): ?>
                                        <a
                                            <?php /** @see \EntretienProfessionnel\Controller\ConfigurationController::supprimerRecopieAction() */ ?>
                                                href="<?php echo $this->url("configuration/supprimer-recopie", ['recopie' => $recopie->getId()], [], true); ?>"
                                                title="Supprimer la recopie"
                                        >
                                            <span class="icon icon-unchecked"></span></a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>



                </div>

            </div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(document).ready(function() {
        $('#recopies').DataTable( {
            "paging":   false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function () {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "fiche-metier";

        $('button').removeClass('active');
        $('button#' + name + '-tab').addClass('active');
        $('div.tab-pane').hide().removeClass('active');
        $('div#' + name).show().addClass('active');

        //$('#' + name + '-tab').tab("show");
        $('button.nav-link').on("click",function (e) {
            let anchor = $(this).attr('aria-controls');
            $('div.tab-pane').hide().removeClass('active');
            $('div#' + anchor).show().addClass('active');
            $('button').removeClass('active');
            $('button#' + anchor + '-tab').addClass('active');
            // console.log(anchor);
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#" + anchor);
        });
    });
</script>
