<?php

/**
 * @var Structure $structure
 * @var Agent[] $agents
 * @var array $options
 *
 * @var AgentSuperieur[] $superieurs
 * @var AgentAutorite[] $autorites
 * @var AgentAffectation[] $affectations
 *
 * @var string[] $raison
 */

use Agent\Entity\Db\AgentAffectation;
use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentAutorite;
use Application\Entity\Db\AgentSuperieur;
use Application\Provider\Privilege\AgentPrivileges;
use Structure\Entity\Db\Structure;
use Structure\Entity\Db\StructureAgentForce;
use Structure\Provider\Privilege\StructurePrivileges;

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canAjouterAgentForce       = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_AGENT_FORCE);
$canRetirerAgentForce       = $canAjouterAgentForce;

$isForce = (isset($options['force']) AND $options['force'] === true);

?>

<span class="btn btn-secondary" id="administatif_masquer">
    Masquer non administratif
</span>
<span class="btn btn-secondary" id="administatif_afficher" style="display: none;">
    Afficher non administratif
</span>

<table class="datatable table table-condensed" id="<?php echo $options['id']; ?>" style="font-size: 14px;">
    <thead>
        <tr>
            <th data-type="string"> Dénomination</th>
            <th> Structures fines</th>
            <th> Supérieur&middot;e hiérarchique direct&middot;e </th>
            <th> Autorité hiérarchique </th>
            <th style="width:5rem; min-width: 5rem;"> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) :?>
        <?php
            if ($agent instanceof StructureAgentForce) $agent = $agent->getAgent();
//            /** @var AgentAffectation[] $affectations */
//            $affectations = $agent->getAffectationsActifs();
//            $affectations = array_filter($affectations, function (AgentAffectation $a) { return $a->isPrincipale(); });
        ?>
        <tr class="<?php if ($agent->isAdministratif()) echo " administratif "; ?>">
            <td data-order="<?php echo $agent->getDenomination(); ?>">
                <?php if ($canVoirAgent) : ?>
                        <?php echo $agent->getDenomination(true); ?>
                <?php else : ?>
                    <?php echo $agent->getDenomination(); ?>
                <?php endif; ?>
                <?php if (isset($raison[$agent->getId()]) AND $raison[$agent->getId()] !== "<ul></ul>") : ?>
                    <span class="icon icon-information" title="<?php echo $raison[$agent->getId()]; ?>"
                        data-bs-toggle="tooltip" data-bs-html="true"></span>
                <?php endif; ?>
            </td>
            <td>
                <!-- STRUCTURE --------------------------------------------------------------------------------------->
                <?php /** @var AgentAffectation $affectation */ ?>
                <?php if (isset($affectations[$agent->getId()]) AND !empty($affectations[$agent->getId()])):?>
                    <?php foreach($affectations[$agent->getId()] as $affectation) :?>
                        <?php $structureA = $affectation->getStructure(); ?>
                        <?php if ($affectation->isPrincipale()) : ?>
                            <strong title="Affectation principale"> <?php echo $structureA->getLibelleCourt(); ?> </strong>
                        <?php else : ?>
                            <?php echo $structureA->getLibelleCourt(); ?>
                        <?php endif ; ?>
                        <br>

                    <?php endforeach; ?>
                <?php else : ?>
                    <span class="text-danger">
                        <span class="icon icon-attention"></span>
                        Affectation fine inconnue
                    </span>
                <?php endif; ?>
            </td>
            <td> <!-- RESPONSABLE HIERARCHIQUE ------------------------------------------------------------------------>
                <?php /** @var AgentSuperieur $superieur */ ?>
                <?php if (isset($superieurs[$agent->getId()]) AND !empty($superieurs[$agent->getId()])):?>
                    <?php foreach($superieurs[$agent->getId()] as $superieur) :?>
                        <?php echo $superieur->getSuperieur()->getDenomination(true); ?><br/>
                    <?php endforeach; ?>
                <?php else : ?>
                    <span class="text-danger">
                        <span class="icon icon-attention"></span>
                        Supérieur·e hiérarchique manquant·e
                    </span>
                <?php endif; ?>
            </td>
            <td> <!-- AUTORITE HIERARCHIQUE --------------------------------------------------------------------------->
                <?php /** @var AgentAutorite $autorite */ ?>
                <?php if (isset($autorites[$agent->getId()]) AND !empty($autorites[$agent->getId()])):?>
                    <?php foreach($autorites[$agent->getId()] as $autorite) :?>
                        <?php echo $autorite->getAutorite()->getDenomination(true); ?><br/>
                    <?php endforeach; ?>
                <?php else : ?>
                    <span class="text-danger">
                        <span class="icon icon-attention"></span>
                        Autorité hiérarchique manquante
                    </span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirAgent) : ?>
                    <a
                        <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                            href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon icon-user" data-bs-toggle="tooltip" data-bs-html="true" title="Voir les renseignements de <span class='highlight agent'><?php echo $agent->getDenomination(); ?></span>"></span></a>
                <?php endif; ?>

                <?php if ($isForce AND $canRetirerAgentForce) : ?>
                    <?php /** @see \Structure\Controller\StructureController::retirerManuellementAgentAction() */ ?>
                    <a  class="ajax-modal" data-event="modification"
                        href="<?php echo $this->url('structure/retirer-manuellement-agent', [ 'structure' => $structure->getId(), 'agent' => $agent->getId()], [], true); ?>"
                    >
                        <span class="icon icon-utilisateur-supprimer"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>

<script>
    $('span#administatif_masquer').on('click', function() {
        $("tbody tr:not(.administratif)").hide();
        $("span#administatif_masquer").hide();
        $("span#administatif_afficher").show();
    });
    $('span#administatif_afficher').on('click', function() {
        $("tbody tr:not(.administratif)").show();
        $("span#administatif_masquer").show();
        $("span#administatif_afficher").hide();
    });

    $(document).ready(function() {
        $("table#<?php echo $options['id']; ?>").DataTable( {
            paging: false,
            info: false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [4], orderable: false }
            ]
        });
    });
</script>