<?php

/**
 * @var Structure $structure
 * @var Agent[] $agents
 * @var array $options
 *
 * @var Agent[] $superieurs
 * @var Agent[] $autorites
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentAutorite;
use Application\Entity\Db\AgentSuperieur;
use Application\Provider\Privilege\AgentPrivileges;
use Structure\Entity\Db\Structure;
use Structure\Entity\Db\StructureAgentForce;
use Structure\Provider\Privilege\StructurePrivileges;

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canAjouterAgentForce       = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_AGENT_FORCE);
$canRetirerAgentForce       = $canAjouterAgentForce;

$isForce = (isset($options['force']) AND $options['force'] === true);

?>

<span class="btn btn-secondary" id="administatif_masquer">
    Masquer non administratif
</span>
<span class="btn btn-secondary" id="administatif_afficher" style="display: none;">
    Afficher non administratif
</span>

<table class="datatable table table-condensed" id="<?php echo $options['id']; ?>" style="font-size: 14px;">
    <thead>
        <tr>
            <th> Dénomination</th>
            <th> Structures fines</th>
            <th> Supérieur&middot;e hiérarchique direct&middot;e </th>
            <th> Autorité hiérarchique </th>
            <th style="width:5rem; min-width: 5rem;"> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) :?>
        <?php
            if ($agent instanceof StructureAgentForce) $agent = $agent->getAgent();
            $structureAgent =  ($agent->getAffectationPrincipale())?$agent->getAffectationPrincipale()->getStructure():null;
            $niveau2   =  ($structureAgent AND $structureAgent->getNiv2())?$structureAgent->getNiv2():null;
        ?>
        <tr class="<?php if ($agent->isAdministratif()) echo " administratif "; ?>">
            <td>
                <?php if ($canVoirAgent) : ?>
                    <a
                        <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                        href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                        target="_blank"
                        title="Voir les renseignements de <span class='highlight agent'><?php echo $agent->getDenomination(); ?></span>" data-bs-toggle="tooltip" data-bs-html="true"
                    >
                        <?php echo $agent->getDenomination(); ?></a>
                <?php else : ?>
                    <?php echo $agent->getDenomination(); ?>
                <?php endif; ?>
            </td>
            <td>
                <!-- STRUCTURE --------------------------------------------------------------------------------------->
                <?php if ($structureAgent) : ?>
                    <span class="icon application" title="Déterminé par EMC2"></span>
                    <?php echo $structureAgent->getLibelleCourt(); ?><br/>
                <?php else : ?>
                    Pas de structure fines<br/>
                <?php endif ?>
            </td>
            <td> <!-- RESPONSABLE HIERARCHIQUE ------------------------------------------------------------------------>
                <?php $superieurs = $agent->getSuperieurs(); ?>
                <?php if (empty($superieurs)) : ?>
                    <span class="text-danger">
                        <span class="icon icon-attention"></span>
                        Supérieur·e hiérarchique manquante
                    </span>
                    <br/>
                <?php else : ?>
                    <?php
                        $superieurs = $agent->getSuperieurs();
                        usort($superieurs, function (AgentSuperieur $a, AgentSuperieur $b) { return $a->getSuperieur()->getNomUsuel()." ".$a->getSuperieur()->getPrenom() > $b->getSuperieur()->getNomUsuel()." ".$b->getSuperieur()->getPrenom();});
                        $asString = implode("<br>", array_map(function (AgentSuperieur $a) { return $a->getSuperieur()->getDenomination();}, $superieurs));
                        echo $asString;
                    ?>
                <?php endif; ?>
            </td>
            <td> <!-- AUTORITE HIERARCHIQUE --------------------------------------------------------------------------->
                <?php $autorites = $agent->getAutorites(); ?>
                <?php if (empty($autorites)) : ?>
                    <span class="text-danger">
                        <span class="icon icon-attention"></span>
                        Autorité hiérarchique manquante
                    </span>
                    <br/>
                <?php else : ?>
                    <?php
                        $autorites = $agent->getAutorites();
                        usort($autorites, function (AgentAutorite $a, AgentAutorite $b) { return $a->getAutorite()->getNomUsuel()." ".$a->getAutorite()->getPrenom() > $b->getAutorite()->getNomUsuel()." ".$b->getAutorite()->getPrenom();});
                        $asString = implode("<br>", array_map(function (AgentAutorite $a) { return $a->getAutorite()->getDenomination();}, $autorites));
                        echo $asString;
                    ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirAgent) : ?>
                    <a
                        <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                            href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon personnel" data-bs-toggle="tooltip" data-bs-html="true" title="Voir les renseignements de <span class='highlight agent'><?php echo $agent->getDenomination(); ?></span>"></span></a>
                <?php endif; ?>

                <?php if ($isForce AND $canRetirerAgentForce) : ?>
                    <?php /** @see \Application\Controller\StructureController::retirerManuellementAgentAction() */ ?>
                    <a  class="ajax-modal" data-event="modification"
                        href="<?php echo $this->url('structure/retirer-manuellement-agent', [ 'structure' => $structure->getId(), 'agent' => $agent->getId()], [], true); ?>"
                    >
                        <span class="icon icon-utilisateur-supprimer"></span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>

<script>
    $('span#administatif_masquer').on('click', function() {
        $("tbody tr:not(.administratif)").hide();
        $("span#administatif_masquer").hide();
        $("span#administatif_afficher").show();
    });
    $('span#administatif_afficher').on('click', function() {
        $("tbody tr:not(.administratif)").show();
        $("span#administatif_masquer").show();
        $("span#administatif_afficher").hide();
    });

    $(document).ready(function() {
        $("table#<?php echo $options['id']; ?>").DataTable( {
            'paging' : false,
        });
    });
</script>