<?php

use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Etat\EntretienProfessionnelEtats;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use EntretienProfessionnel\Provider\Privilege\SursisPrivileges;
use Structure\Entity\Db\Structure;

/**
 * @var Campagne $campagne
 * @var Structure $structure
 * @var Agent[] $agents
 * @var array{agentId:int, entretien:EntretienProfessionnel} $entretiens
 */

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canAjouterEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AJOUTER));
$canVoirEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AFFICHER));
$canModifierEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_MODIFIER));
$canHistoriserEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_HISTORISER));
$canDetruireEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_DETRUIRE));

$canSursisAjouter = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_AJOUTER));
$canSursisModifier = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_MODIFIER));
$canSursisSupprimer = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_SUPPRIMER));

$complete = [];
$encours = [];
$sans = [];
$facultatifs = [];

foreach ($agents as $agent) {
    $entretien = $entretiens[$agent->getId()]??null;

    if ($entretien === null) {
        $date = $campagne->getDateFin();
        $date = DateTime::createFromFormat('d/m/Y', $campagne->getDateFin()->format('d/m/Y'));
        $date = $date->sub(new DateInterval('P12M'));
        if ($agent->isContratLong() AND !empty($agent->getAffectationsActifs($date))) {
            $sans[$agent->getDenomination()] = $agent;
        } else {
            $facultatifs[$agent->getDenomination()] = $agent;
        }
    } else {
        if ($entretien->isComplete()) {
            $complete[$agent->getDenomination()] = $entretien;
        } else {
            $encours[$agent->getDenomination()] = $entretien;
        }
    }
}

$enCours = $campagne->estEnCours();


$planifie = [];
$fait = [];
foreach ($encours as $epro) {
    if ($epro->getEtat()->getCode() === EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTATION OR
        $epro->getEtat()->getCode() === EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTER) {
        $planifie[] = $epro;
    } else {
        $fait[] = $epro;
    }
}
?>

<h2> Informations sur la campagne </h2>


<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-3"> Année </dt>
            <dd class="col-md-3"> <?php echo $campagne->getAnnee(); ?> </dd>
            <dt class="col-md-3"> En cours </dt>
            <dd class="col-md-3">
                <?php if ($campagne->estEnCours()) : ?>
                    <span style="color:darkgreen;"><span class="icon icon-checked"></span>Oui</span>
                <?php else : ?>
                    <span style="color:darkred;"><span class="icon icon-retirer"></span>Non</span>
                <?php endif; ?>
            </dd>
            <dt class="col-md-6"> Début de la campagne </dt>
            <dd class="col-md-6"> <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?></dd>
            <dt class="col-md-6"> Fin de la campagne </dt>
            <dd  class="col-md-6"> <?php echo $campagne->getDateFin()->format('d/m/Y'); ?></dd>

        </dl>
    </div>

    <div class="col-md-6">
        <h3> Progression de la campagne</h3>

        <?php
            $nbComplete = count($complete);
            $nbEncours = count($encours);
            $nbSans = count($sans);
            $nbTotal =  $nbComplete + $nbEncours + $nbSans;
        ?>

        <?php if ($nbTotal !== 0) : ?>

            <?php
                $ratioComplete =  $nbComplete / $nbTotal * 100;
                $ratioPlanifie = count($planifie) / $nbTotal * 100;
                $ratioFait = count($fait) / $nbTotal * 100;
                $ratioSans = 100 - ($ratioComplete + $ratioPlanifie + $ratioFait);
            ?>

            <div class="progress">
                <div class="progress-bar complete" role="progressbar" style="width: <?php echo $ratioComplete; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens complétés <?php echo $nbComplete; ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioComplete); ?>%</div>
                <div class="progress-bar fait" role="progressbar" style="width: <?php echo $ratioFait; ?>%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens effectués <?php echo count($fait); ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioFait); ?>%</div>
                <div class="progress-bar planifie" role="progressbar" style="width: <?php echo $ratioPlanifie; ?>%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens en cours <?php echo count($planifie); ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioPlanifie); ?>%</div>
                <div class="progress-bar sans"   role="progressbar" style="width: <?php echo $ratioSans; ?>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens non planifiés <?php echo $nbSans; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioSans); ?>%</div>
            </div>
        <?php endif; ?>
        
    </div>
</div>


<h2>
    Entretiens professionnels complétés
    <span class="badge">
        <?php echo count($complete); ?>
    </span>
</h2>

<?php echo $this->entretienProfessionnelArray($complete,[
        'affichages' => ['annee' => false, 'structure' => false, 'lieu' => false],
        'droits' => ['renseigner' => false, 'modifier' => false, 'sursis' => false],
]); ?>


<!-- Enrtetiens professtionnels en cours ------------------------------------------------------------------------------>
<h2>
    Entretiens professionnels en cours
    <span class="badge">
        <?php echo count($encours); ?>
    </span>
</h2>

<?php echo $this->entretienProfessionnelArray($encours,[
    'affichages' => ['annee' => false, 'structure' => false, 'lieu' => false],
    'droits' => [],
]); ?>

<h2>
    Agents sans entretien professionnel pour la campagne
    <span class="badge">
        <?php echo count($sans); ?>
    </span>
</h2>

<?php echo $this->convocationArray($sans, $campagne); ?>

<h2>
    Agents sans obligation d'entretien professionnel
    <span class="badge">
        <?php echo count($facultatifs); ?>
    </span>
</h2>

<?php echo $this->convocationArray($facultatifs, $campagne); ?>

<style>
    span.texte-sursis {
        color:darkred;
        font-style: italic;
    }

    div.complete {
        background-color: #009600;
    }
    div.sans {
        background-color: #960000;
    }
    div.planifie {
        background-color: #ff6c0a;
    }
    div.fait {
        background-color: #9dc500;
    }
</style>

<script>
    $(function() {
        $("body").on("entretien", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>