<?php

use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\Delegue;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Etat\EntretienProfessionnelEtats;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use EntretienProfessionnel\Provider\Privilege\SursisPrivileges;
use Structure\Entity\Db\Structure;
use Structure\Provider\Privilege\StructurePrivileges;

/**
 * @var Campagne $campagne
 * @var Structure $structure
 * @var Agent[] $agents
 * @var Delegue[] $delegues
 */

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canAjouterEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AJOUTER));
$canVoirEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AFFICHER));
$canModifierEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_MODIFIER));
$canHistoriserEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_HISTORISER));
$canDetruireEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_DETRUIRE));

$canSursisAjouter = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_AJOUTER));
$canSursisModifier = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_MODIFIER));
$canSursisSupprimer = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_SUPPRIMER));

$canGererDelegue = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_GESTIONNAIRE);

$deleguesCampagne = array_filter($delegues, function (Delegue $a) use ($campagne) { return $a->getCampagne() === $campagne;});

$complete = [];
$encours = [];
$sans = [];
$facultatifs = [];

foreach ($agents as $agent) {
    //todo déplcer cela dans campagne ou dans le service de la campagne
    $entretien = null;
    foreach ($campagne->getEntretiensProfessionnels() as $e) {
        if ($e->getAgent() === $agent) {
            $entretien = $e;
            break;
        }
    }

    if ($entretien === null) {
        $date = $campagne->getDateFin();
        $date = DateTime::createFromFormat('d/m/Y', $campagne->getDateFin()->format('d/m/Y'));
        $date = $date->sub(new DateInterval('P12M'));
        if ($agent->isContratLong() AND !empty($agent->getAffectationsActifs($date))) {
            $sans[$agent->getDenomination()] = $agent;
        } else {
            $facultatifs[$agent->getDenomination()] = $agent;
        }
    } else {
        if ($entretien->isComplete()) {
            $complete[$agent->getDenomination()] = $entretien;
        } else {
            $encours[$agent->getDenomination()] = $entretien;
        }
    }
}

$enCours = $campagne->estEnCours();


$planifie = [];
$fait = [];
foreach ($encours as $epro) {
    if ($epro->getEtat()->getCode() === EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTATION OR
        $epro->getEtat()->getCode() === EntretienProfessionnelEtats::ETAT_ENTRETIEN_ACCEPTER) {
        $planifie[] = $epro;
    } else {
        $fait[] = $epro;
    }
}
?>

<h2> Informations sur la campagne </h2>

<div class="row">
    <div class="col-md-6">
            <dl class="dl-horizontal">
        <dt> Année </dt>
        <dd> <?php echo $campagne->getAnnee(); ?> </dd>
        <dt> Début de la campagne </dt>
        <dd> <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?></dd>
        <dt> Fin de la campagne </dt>
        <dd> <?php echo $campagne->getDateFin()->format('d/m/Y'); ?></dd>
        <dt> En cours </dt>
        <dd>
            <?php if ($enCours) : ?>
                <span style="color:darkgreen;"><span class="icon icon-checked"></span>Oui</span>
            <?php else : ?>
                <span style="color:darkred;"><span class="icon icon-retirer"></span>Non</span>
            <?php endif; ?>
        </dd>
    </dl>

        <h3>Délégué&middot;e&middot;s pour la campagne
            <span class="badge"><?php echo count($deleguesCampagne); ?></span>
            <?php if ($canGererDelegue AND $enCours) : ?>
                <?php /** @see \EntretienProfessionnel\Controller\DelegueController::ajouterAction() */ ?>
                <a href="<?php echo $this->url('entretien-professionnel/ajouter-delegue', ['structure' => $structure->getId(), 'campagne' => $campagne->getId()], [], true); ?>"
                   data-bs-toggle="tooltip" data-bs-html="true" class="ajax-modal" data-event="modification"
                >
                    <span class="icon icon-ajouter"></span>
                </a>
            <?php endif; ?>
        </h3>

        <?php if(empty($deleguesCampagne)) : ?>
            <i>Aucun délégué pour la campagne</i>
        <?php else : ?>
            <ul>
                <?php foreach ($deleguesCampagne as $delegue) : ?>
                    <li>
                        <span title="<?php echo $delegue->getDescription(); ?>" data-bs-toggle="tooltip" data-bs-html="true">
                            <?php echo $delegue->getAgent()->getDenomination(); ?>
                        </span>
                        <?php if ($canGererDelegue AND $enCours) : ?>
                            <?php /** @see \EntretienProfessionnel\Controller\DelegueController::retirerAction() */ ?>
                            <a href="<?php echo $this->url('entretien-professionnel/retirer-delegue', ['delegue' => $delegue->getId()], [], true); ?>">
                                <span class="icon icon-retirer"></span>
                            </a>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>


    </div>
    <div class="col-md-6">
        <h3> Progression de la campagne</h3>

        <?php
            $nbComplete = count($complete);
            $nbEncours = count($encours);
            $nbSans = count($sans);
            $nbTotal =  $nbComplete + $nbEncours + $nbSans;
        ?>

        <?php if ($nbTotal !== 0) : ?>

            <?php
                $ratioComplete =  $nbComplete / $nbTotal * 100;
                $ratioPlanifie = count($planifie) / $nbTotal * 100;
                $ratioFait = count($fait) / $nbTotal * 100;
                $ratioSans = 100 - ($ratioComplete + $ratioPlanifie + $ratioFait);
            ?>

            <div class="progress">
                <div class="progress-bar complete" role="progressbar" style="width: <?php echo $ratioComplete; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens complétés <?php echo $nbComplete; ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioComplete); ?>%</div>
                <div class="progress-bar fait" role="progressbar" style="width: <?php echo $ratioFait; ?>%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens effectués <?php echo count($fait); ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioFait); ?>%</div>
                <div class="progress-bar planifie" role="progressbar" style="width: <?php echo $ratioPlanifie; ?>%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens en cours <?php echo count($planifie); ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioPlanifie); ?>%</div>
                <div class="progress-bar sans"   role="progressbar" style="width: <?php echo $ratioSans; ?>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens non planifiés <?php echo $nbSans; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioSans); ?>%</div>
            </div>
        <?php endif; ?>
        
    </div>
</div>


<h2>
    Entretiens professionnels complétés
    <span class="badge">
        <?php echo count($complete); ?>
    </span>
</h2>

<?php echo $this->entretienProfessionnelArray($complete,[
        'affichages' => ['annee' => false, 'structure' => false, 'lieu' => false],
        'droits' => ['renseigner' => false, 'modifier' => false, 'sursis' => false],
]); ?>


<!-- Enrtetiens professtionnels en cours ------------------------------------------------------------------------------>
<h2>
    Entretiens professionnels en cours
    <span class="badge">
        <?php echo count($encours); ?>
    </span>
</h2>

<?php echo $this->entretienProfessionnelArray($encours,[
    'affichages' => ['annee' => false, 'structure' => false, 'lieu' => false],
    'droits' => [],
]); ?>

<h2>
    Agents sans entretien professionnel pour la campagne
    <span class="badge">
        <?php echo count($sans); ?>
    </span>
</h2>

<table class="table table-condensed">
    <thead>
        <tr>
           <th> Dénomination</th>
           <th> Structure </th>
           <th> Grade </th>
           <?php if ($enCours === true) : ?>
                <th style="width:13rem;"> Action </th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($sans as $denomination => $agent): ?>
            <tr>
                <td> <?php echo $denomination; ?> </td>
                <td>
                    <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                        <?php echo $grade->getStructure()->getLibelleLong(); ?>
                    <?php endforeach; ?>
                </td>
                <td>
                    <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                        <?php echo ($grade->getGrade())?$grade->getGrade()->getLibelleLong():"N.C."; ?>
                    <?php endforeach; ?>
                </td>
                <?php if ($enCours === true) : ?>
                    <td>
                        <?php if ($canVoirAgent) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                                href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                                target="_blank"
                                title="Affiche la fiche <span class='highlight agent'><?php echo $denomination; ?>"
                                data-bs-toggle="tooltip" data-bs-html="true"
                            >
                                <span class="icon personnel"></span></a>
                        <?php endif; ?>
                        <?php if ($canAjouterEntretien) : ?>
                            <a
                                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::creerAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/creer', ['campagne' => $campagne->getId()], ["query" => ['structure' => $structure->getId(), 'agent' => $agent->getId()]], [], true); ?>"
                                title="Créer un entretien professionnel pour <span class='highlight agent'><?php echo $denomination; ?>"
                                class="ajax-modal" data-event="entretien"
                                data-bs-toggle="tooltip" data-bs-html="true"
                            >
                                <span class="icon icon-ajouter"></span></a>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<h2>
    Agents sans obligation d'entretien professionnel
    <span class="badge">
        <?php echo count($facultatifs); ?>
    </span>
</h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Dénomination</th>
        <th> Structure </th>
        <th> Grade </th>
        <?php if ($enCours === true) : ?>
            <th style="width:13rem;"> Action </th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($facultatifs as $denomination => $agent): ?>
        <tr>
            <td> <?php echo $denomination; ?> </td>
            <td>
                <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                    <?php echo $grade->getStructure()->getLibelleLong(); ?>
                <?php endforeach; ?>
            </td>
            <td>
                <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                    <?php echo ($grade->getGrade())?$grade->getGrade()->getLibelleLong():"N.C."; ?>
                <?php endforeach; ?>
            </td>
            <?php if ($enCours === true) : ?>
                <td>
                    <?php if ($canVoirAgent) : ?>
                        <a
                            <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                                href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                                target="_blank"
                                title="Affiche la fiche <span class='highlight agent'><?php echo $denomination; ?>"
                                data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon personnel"></span></a>
                    <?php endif; ?>
                    <?php if ($canAjouterEntretien) : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::creerAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/creer', ['campagne' => $campagne->getId()], ["query" => ['structure' => $structure->getId(), 'agent' => $agent->getId()]], [], true); ?>"
                                title="Créer un entretien professionnel pour <span class='highlight agent'><?php echo $denomination; ?>"
                                class="ajax-modal" data-event="entretien"
                                data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon icon-ajouter"></span></a>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<style>
    span.texte-sursis {
        color:darkred;
        font-style: italic;
    }

    div.complete {
        background-color: #009600;
    }
    div.sans {
        background-color: #960000;
    }
    div.planifie {
        background-color: #ff6c0a;
    }
    div.fait {
        background-color: #9dc500;
    }
</style>

<script>
    $(function() {
        $("body").on("entretien", function (event) {
            //let content = event.div.html();
            //let match_regex = content.match(/#[0-9]*/g)[0];
            //let id = match_regex.split('#')[1];
            //event.div.modal('hide');
            //let win = window.open('../../entretien-professionnel/acceder/' + id + '?structure=' + <?php //echo ($structure)?$structure->getId():0; ?>//, '_blank');
            //if (win) {
            //    //Browser has allowed it to be opened
            //    win.focus();
            //} else {
            //    //Browser has blocked it
            //    alert('Please allow popups for this website');
            //}
            //console.log("entretien pro: " + id);
            //window.location.reload();
            // alert("L'entretien vien d'être créer");
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>