<?php

use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\FormationInstanceInscrit;
use Formation\Provider\Etat\DemandeExterneEtats;
use Formation\Provider\Etat\InscriptionEtats;
use Formation\Provider\Privilege\DemandeexternePrivileges;
use Formation\Provider\Privilege\FormationinstanceinscritPrivileges;

/**
 * @var FormationInstanceInscrit[] $inscriptions
 * @var DemandeExterne[] $demandes
 */

$canValiderResponsable = $this->isAllowed(FormationinstanceinscritPrivileges::getResourceId(FormationinstanceinscritPrivileges::INSCRIPTION_VALIDER_SUPERIEURE));

$array = [];
foreach ($inscriptions as $inscription) {
    if ($inscription->estNonHistorise()) {
        $formation = $inscription->getInstance()->getFormation();
        $instance = $inscription->getInstance();
        $array[$formation->getId()]["formation"] = $formation;
        $array[$formation->getId()]["instances"][$instance->getId()]['instance'] = $instance;
        $array[$formation->getId()]["instances"][$instance->getId()]['inscriptions'][] = $inscription;
    }
}

$attentes = [];
foreach ($inscriptions as $inscription) {
    if ($inscription->estNonHistorise() AND $inscription->getEtat()->getCode() === InscriptionEtats::ETAT_DEMANDE) {
        $formation = $inscription->getInstance()->getFormation();
        $instance = $inscription->getInstance();
        $attentes[$formation->getId()]["formation"] = $formation;
        $attentes[$formation->getId()]["instances"][$instance->getId()]['instance'] = $instance;
        $attentes[$formation->getId()]["instances"][$instance->getId()]['inscriptions'][] = $inscription;
    }
}
?>


<div class="row">
    <div class="col-md-6">

    <h2> Demandes de formations en attentes de validation </h2>

    <div>
        <h3>Demande de formation du plan de formation</h3>
        <?php foreach ($attentes as $formationId => $dFormation) : ?>
            <h4><?php echo $dFormation["formation"]->getLibelle(); ?></h4>

            <?php foreach ($dFormation["instances"] as $instanceId => $dInstance) : ?>
                Session du <?php echo $dInstance["instance"]->getPeriode(); ?>

                <ul>
                <?php foreach ($dInstance["inscriptions"] as $dInscription) : ?>
                    <li>
                        <?php echo $this->etatbadge($dInscription->getEtat()); ?>
                        <?php echo $dInscription->getAgent()->getDenomination(); ?>
                        <?php if ($canValiderResponsable ) : ?>
                            <?php  /** @see \Formation\Controller\FormationInstanceInscritController::validerResponsableAction() */ ?>
                            <a href="<?php echo $this->url('formation-instance/valider-responsable', ['inscrit' => $dInscription->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon validation-do text-success">Valider</span></a>
                            <?php  /** @see \Formation\Controller\FormationInstanceInscritController::refuserResponsableAction() */ ?>
                            <a href="<?php echo $this->url('formation-instance/refuser-responsable', ['inscrit' => $dInscription->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon validation-undo text-danger">Refuser</span></a>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </div>

    <div>
        <h3>Demande de formation hors plan de formation</h3>

        <?php if (empty($demandes)) : ?>
            Aucune demande de formation hors plan de formation
        <?php else : ?>

            <?php foreach ($demandes as $demande) : ?>
                <?php $canDemandeAfficher = $this->isAllowed($demande, DemandeexternePrivileges::DEMANDEEXTERNE_AFFICHER); ?>

                <?php echo $demande->getLibelle(); ?> (du <?php echo $demande->getDebut()->format('d/m/Y'); ?> au <?php echo $demande->getFin()->format('d/m/Y'); ?>)
                <ul>
                <li>
                    <?php echo $this->etatbadge($demande->getEtat()); ?>
                    <?php echo $demande->getAgent()->getDenomination(); ?>
                    <?php if ($canDemandeAfficher ) : ?>
                    <?php  /** @see \Formation\Controller\DemandeExterneController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('formation/demande-externe/afficher', ['demande-externe' => $demande->getId()], [], true); ?>"
                       class="ajax-modal"> <span class="icon icon-voir"></span>Afficher</a>
                    <?php endif; ?>
                    <?php if ($demande->getEtat()->getCode() === DemandeExterneEtats::ETAT_VALIDATION_AGENT) : ?>
                        <?php if ($canValiderResponsable ) : ?>
                            <?php  /** @see \Formation\Controller\DemandeExterneController::validerResponsableAction() */ ?>
                            <a href="<?php echo $this->url('formation/demande-externe/valider-responsable', ["demande-externe" => $demande->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon validation-do text-success">Valider</span></a>
                            <?php  /** @see \Formation\Controller\DemandeExterneController::refuserResponsableAction() */ ?>
                            <a href="<?php echo $this->url('formation/demande-externe/refuser-responsable', ["demande-externe" => $demande->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon validation-undo text-danger">Refuser</span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                </li>
                </ul>
            <?php endforeach; ?>

        <?php endif; ?>
    </div>
    </div>



    <div class="col-md-6">
    <h2> Listes des inscriptions </h2>

    <?php usort($array, function ($a,$b) { return $a['formation']->getLibelle() > $b['formation']->getLibelle();}); ?>
    <?php foreach ($array as $item) : ?>
        <h3> <?php echo $item['formation']->getLibelle(); ?> </h3>

        <ul>
        <?php foreach($item['instances'] as $instance) : ?>
            <li>
                Instance du <?php echo $instance['instance']->getDebut(); ?> au <?php echo $instance['instance']->getFin(); ?> (<?php echo $instance['instance']->getDuree(); ?>).
                <ul>
                    <?php foreach ($instance['inscriptions'] as $inscription) : ?>
                        <li>
                            <?php echo $this->etatbadge($inscription->getEtat()); ?>
                            <?php echo $inscription->getAgent()->getDenomination(); ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php endforeach; ?>

    </div>
</div>
