<?php

use Structure\Entity\Db\Structure;

/**
 * @var Structure $structure
 * @var string $current <i> onglet actif pour mise en forme
 */

?>

<h1 class="page-header">
    <strong><?php echo $structure->getLibelleLong(); ?></strong>
    <br>
    <?php echo $structure->getType()->getLibelle(); ?>
</h1>

Description
Agent·es
Fiches de poste
Missions complémentaires
Campagne XXX
Campagne XXX
Extraction

ONGLET