<?php

/**
 * @see \Application\Controller\StructureController::afficherAction()
 * @var Structure $structure
 * @var FichePoste[] $fichesCompletes
 * @var FichePoste[] $fichesIncompletes
 */

use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FichePostePrivileges;
use Structure\Entity\Db\Structure;

$canVoirFichePoste          = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER));
$canAjouterFichePoste       = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AJOUTER));
$canModifierFichePoste      = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));
$canHistoriserFichePoste    = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_HISTORISER));
$canDetruireFichePoste      = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_DETRUIRE));
?>


<h2>
    Fiches de postes complètes
    <span class="badge">
            <?php echo count($fichesCompletes); ?>
        </span>
</h2>

<?php echo $this->fichesPostesAsArray($fichesCompletes, $structure, ['retour' => $this->url("structure/afficher", ["structure" => $structure->getId()])]); ?>

<h2>
    Fiches de postes incomplètes
    <span class="badge">
            <?php echo count($fichesIncompletes); ?>
        </span>
</h2>

<?php echo $this->fichesPostesAsArray($fichesIncompletes, $structure, ['retour' => $this->url("structure/afficher", ["structure" => $structure->getId()])]); ?>

