<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use Structure\Entity\Db\Structure;

/**
 * @var Structure $structure
 * @var Campagne $campagne
 * @var Agent[] $agents
 * @var EntretienProfessionnel[] $entretiens
 */

?>

<h2> Informations sur la campagne </h2>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-3"> Année </dt>
            <dd class="col-md-3"> <?php echo $campagne->getAnnee(); ?> </dd>
            <dt class="col-md-3"> En cours </dt>
            <dd class="col-md-3">
                <?php if ($campagne->estEnCours()) : ?>
                    <span style="color:darkgreen;"><span class="icon icon-checked"></span>Oui</span>
                <?php else : ?>
                    <span style="color:darkred;"><span class="icon icon-retirer"></span>Non</span>
                <?php endif; ?>
            </dd>
            <dt class="col-md-6"> Début de la campagne </dt>
            <dd class="col-md-6"> <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?></dd>
            <dt class="col-md-6"> Fin de la campagne </dt>
            <dd  class="col-md-6"> <?php echo $campagne->getDateFin()->format('d/m/Y'); ?></dd>

        </dl>
    </div>
</div>

<h2> Entretiens professionnels des agents actuellements dans la structure </h2>

<?php
    echo $this->entretienProfessionnelArray($entretiens, [
        'affichages' => ['annee' => false, 'structure' => true, 'lieu' => false, 'width' => '8rem'],
        'droits' => ['modifier' => false, 'sursis' => false, 'historiser' => false, 'supprimer' => false],
    ]);
?>

