<?php

use Formation\Entity\Db\Formateur;
use UnicaenApp\Form\Element\SearchAndSelect;

/**
 * @var array $params;
 */

$typeSelected = $params['type']??null;
$formateurId = isset($params['formateur'])?$params['formateur']['id']:null;
$formateurDenomination = isset($params['formateur'])?$params['formateur']['label']:null;
$rattachement = isset($params['rattachement'])?$params['rattachement']['label']:null;
?>

<div class="card card-default">
    <div class="card-header">
        <span class="icon icon-filtrer"></span>
        Filtre des forçages
    </div>
    <div class="card-body">

        <form id="filtre" action="<?php echo $this->url(); ?>" method="get">
            <div class="row">
                <div class="col-md-2">
                    <label for="type">Type : </label><br>
                    <select id="type" name="type" class="selectpicker" data-live-search="true">
                        <option value=""> Tous les types</option>
                        <?php foreach (Formateur::TYPES as $clef => $type): ?>
                            <option value="<?php echo $clef; ?>" <?php if ($clef === $typeSelected) echo " selected "; ?>>
                                <?php echo $type; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="denomination"> Dénomination : </label>
                    <?php
                    /** @see  \Formation\Controller\FormateurController::rechercherAction() */
                    $formateurF = new SearchAndSelect('formateur');
                    $formateurF
                        ->setAutocompleteSource($this->url('formation/formateur/rechercher'))
                        ->setSelectionRequired(true)
                        ->setAttributes([
                            'id' => 'formateur',
                            'placeholder' => "Sélectionner un·e formateur·trice",
                        ]);
                    ?>
                    <?php echo $this->formControlGroup($formateurF); ?>
                </div>
                <div class="col-md-4">
                    <label for="rattachement"> Rattachement : </label>
                    <?php
                    /** @see  \Formation\Controller\FormateurController::rechercherRattachementAction() */
                    $rattachementF = new SearchAndSelect('rattachement');
                    $rattachementF
                        ->setAutocompleteSource($this->url('formation/formateur/rechercher-rattachement'))
                        ->setSelectionRequired(true)
                        ->setAttributes([
                            'id' => 'rattachement',
                            'placeholder' => "Sélectionner un rattachement",
                        ]);
                    ?>
                    <?php echo $this->formControlGroup($rattachementF); ?>
                </div>
                <!-- BOUTON -->
                <div class="col-md-2">
                    <div class="pull-right">
                        <button class="btn btn-primary action" id="clear">
                            <span class="icon icon-gommer"></span>
                            R.A.Z.
                        </button>

                        <button class="btn btn-primary action" id="filter">
                            <span class="icon icon-filtrer"></span>
                            Filtrer
                        </button>
                    </div>
                </div>
        </form>
    </div>
</div>
</div>

<script>
    $("form#filtre").submit(function (e) {
        e.preventDefault();
    });

    $('button#clear').on("click", function (e) {
        e.preventDefault();
        window.location.href = '?';
    });

    $('button#filter').click(function () {
        let type = $('select#type option:selected').val();
        let formateurId = $('input[name="formateur[id]"]').val();
        let formateurDenomination = $('input[name="formateur[label]"]').val();
        let rattachement = $('input[name="rattachement[label]"]').val();

        let query = "";
        query += "&type=" + type;
        query += "&rattachement[label]=" + rattachement;
        query += "&formateur[id]=" + formateurId;
        query += "&formateur[label]=" + formateurDenomination;
        window.location.href = '?'+ query;
    });

    $(function () {
        <?php if ($formateurId !== null) :?>
            $('input[name="formateur[id]"]').val("<?php echo $formateurId; ?>");
            $('input[name="formateur[label]"]').val("<?php echo $formateurDenomination; ?>");
        <?php endif; ?>
        <?php if ($rattachement !== null) :?>
        //$('input[name="formateur[id]"]').val("<?php //echo $formateurId; ?>//");
        $('input[name="rattachement[label]"]').val("<?php echo $rattachement; ?>");
        <?php endif; ?>
    });
</script>
