<?php

use Referentiel\Entity\Db\Referentiel;
use Referentiel\Provider\Privilege\ReferentielPrivileges;

/**
 * @see \Referentiel\Controller\ReferentielController::indexAction()
 * @var Referentiel[] $referentiels
 */

$canAfficher = $this->isAllowed(ReferentielPrivileges::getResourceId(ReferentielPrivileges::REFERENTIEL_AFFICHER));
$canAjouter = $this->isAllowed(ReferentielPrivileges::getResourceId(ReferentielPrivileges::REFERENTIEL_AJOUTER));
$canModifier = $this->isAllowed(ReferentielPrivileges::getResourceId(ReferentielPrivileges::REFERENTIEL_MODIFIER));
$canHistoriser = $this->isAllowed(ReferentielPrivileges::getResourceId(ReferentielPrivileges::REFERENTIEL_HISTORISER));
$canSupprimer = $this->isAllowed(ReferentielPrivileges::getResourceId(ReferentielPrivileges::REFERENTIEL_SUPPRIMER));

$this->headTitle("Référentiels");

?>

<h1 class="page-header">
    Référentiels
</h1>

<?php if ($canAjouter): ?>
    <?php /** @see \Referentiel\Controller\ReferentielController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('referentiel/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un référentiel
    </a>
<?php endif; ?>

<table class="table table-condensed" id="referentiels">
    <thead>
        <tr>
            <th class="col-md-2"> Libellé court </th>
            <th class="col-md-8"> Libellé long et description </th>
            <th class="col-md-2 action"> Action</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($referentiels as $referentiel): ?>
        <tr>
            <td data-column-id="Libellé court">
                <span class="badge" style="background:<?php echo $referentiel->getCouleur(); ?>;">
                    <?php echo $referentiel->getLibelleCourt(); ?>
                </span>
            </td>
            <td data-column-id="Libellé long">
                <?php echo $referentiel->getLibelleLong(); ?>
                <br>
                <?php if ($referentiel->getDescription() !== null) : ?>
                    <?php echo $referentiel->getDescription(); ?>
                <?php else : ?>
                    <span class="missing-data">Aucune description</span><br><br>
                <?php endif; ?>

                <?php $nbActivites = count($referentiel->getActivites()); ?>
                <?php if ($nbActivites > 0) : ?>
                    <?php /** @see \FicheMetier\Controller\ActiviteController::indexAction()  */ ?>
                    <a href="<?php echo $this->url('activite', [], ['query' => ['referentiel' => $referentiel->getId()]], true); ?>">
                        <span class="badge activite"> <?php echo $nbActivites; ?> activité·s </span></a>
                <?php endif; ?>
                <?php $nbMissions = count($referentiel->getMissions()); ?>
                <?php if ($nbMissions > 0) : ?>
                    <?php /** @see \FicheMetier\Controller\MissionPrincipaleController::indexAction()  */ ?>
                    <a href="<?php echo $this->url('mission-principale', [], ['query' => ['referentiel' => $referentiel->getId()]], true); ?>">
                        <span class="badge mission"> <?php echo $nbMissions; ?> mission·s </span></a>
                <?php endif; ?>
                <?php $nbCompetences = count($referentiel->getCompetences()); ?>
                <?php if ($nbCompetences > 0) : ?>
                    <?php /** @see \Element\Controller\CompetenceController::listingAction()  */ ?>
                    <a href="<?php echo $this->url('element/competence/listing', [], ['query' => ['referentiel' => $referentiel->getId()]], true); ?>">
                        <span class="badge competence"> <?php echo $nbCompetences; ?> compétence·s </span></a>
                <?php endif; ?>
                <?php $nbFichesMetiers = count($referentiel->getFichesMetiers()); ?>
                <?php if ($nbFichesMetiers > 0) : ?>
                    <?php /** @see \FicheMetier\Controller\FicheMetierController::indexAction()  */ ?>
                    <a href="<?php echo $this->url('fiche-metier', [], ['query' => ['referentiel' => $referentiel->getId()]], true); ?>">
                        <span class="badge fichemetier"> <?php echo $nbFichesMetiers; ?> fiche·s métier·s</span></a>
                <?php endif; ?>
            </td>
            <td class="action">
<!--                --><?php //if ($canAfficher): ?>
<!--                    --><?php ///** @see \Referentiel\Controller\ReferentielController::afficherAction() */ ?>
<!--                    <a href="--><?php //echo $this->url('referentiel/afficher', ['referentiel' => $referentiel->getId()], [], true); ?><!--"-->
<!--                       class="action secondary ajax-modal" >-->
<!--                        <span class="icon icon-voir"></span>-->
<!--                        Afficher-->
<!--                    </a>-->
<!--                --><?php //endif; ?>
                <?php if ($canModifier): ?>
<!--                    <br/>-->
                    <?php /** @see \Referentiel\Controller\ReferentielController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('referentiel/modifier', ['referentiel' => $referentiel->getId()], [], true); ?>"
                       class="action primary ajax-modal" data-event="modification">
                        <span class="icon icon-modifier"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser): ?>
                    <br/>
                    <?php if ($referentiel->estNonHistorise()) : ?>
                        <?php /** @see \Referentiel\Controller\ReferentielController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('referentiel/historiser', ['referentiel' => $referentiel->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else: ?>
                        <?php /** @see \Referentiel\Controller\ReferentielController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('referentiel/restaurer', ['referentiel' => $referentiel->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer): ?>
                    <br/>
                    <?php /** @see \Referentiel\Controller\ReferentielController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('referentiel/supprimer', ['referentiel' => $referentiel->getId()], [], true); ?>"
                       class="action danger ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>



<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>