<?php

/**
 * @var FamilleProfessionnelle[] $familles
 * @var array[] $types
 *
 * @var string $famille
 * @var string $type
 * @var string $historise
 */

use Metier\Entity\Db\FamilleProfessionnelle;

?>

<div class="card">
    <div class="card-header bg-default">
        <span class="icon icon-filtrer"></span>
        Filtrage de la liste des métiers
    </div>
    <div class="card-body">
        <form id="filter" method="get" action="<?php echo $this->url(); ?>">
        <div class="row">
        <div class="col-md-3">
            <label for="famille">Famille professionnelle associée :  </label>
            <select id="famille" name="famille" class="selectpicker" data-live-search="true">
                <option value=" ">Peu importe</option>
                <?php foreach ($familles as $famille_) : ?>
                    <option value="<?php echo $famille_->getId(); ?>">  <?php echo $famille_->getLibelle(); ?> </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-md-3">
            <label for="type">Type de fonction associé :  </label>
            <select id="type" name="type" class="selectpicker" data-live-search="true">
                <option value=" ">Peu importe</option>
                <?php foreach ($types as $type_) : ?>
                    <option value="<?php echo $type_; ?>">  <?php echo $type_; ?> </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-md-3">
            <label for="historise">Domaines historisés :  </label>
            <select id="historise" name="historise" class="selectpicker">
                <option value=" ">Peu importe</option>
                <option value="1">Oui</option>
                <option value="0">Non</option>
            </select>
        </div>

        <div class="col-md-3">
        <div class="pull-right">
            <button type="button" id="filter" class="btn btn-primary filter-action">
                <span class="icon icon-filtrer" aria-hidden="true"></span> Filtrer
            </button>
            <br/>
            <button type="button" id="reset" class="btn btn-primary filter-action">
                <span class="icon icon-gommer" aria-hidden="true"></span> R.A.Z.
            </button>
        </div>
        </div>
        </div>
        </form>
    </div>
</div>


<script>
    $('button#reset').click(function (e) {
        e.preventDefault();
        window.location = '?';
    });
    $('button#filter').click(function () {
        $('form#filter').submit();
    });

    $('select#famille option[value=<?php echo $famille; ?>]').prop('selected', true);
    $('select#type option[value=<?php echo $type; ?>]').prop('selected', true);
    $('select#historise option[value=<?php echo $historise; ?>]').prop('selected', true);
</script>