<?php

use EmploiRepere\Entity\Db\EmploiRepere;
use EmploiRepere\Entity\Db\EmploiRepereCodeFonctionFicheMetier;
use EmploiRepere\Provider\Privilege\EmploireperePrivileges;

/**
 * @see \EmploiRepere\Controller\EmploiRepereController::indexAction()
 * @var EmploiRepere[] $emploisReperes
 */

$this->headTitle('Emploi-repères');


$canAjouter = $this->isAllowed(EmploireperePrivileges::getResourceId(EmploireperePrivileges::EMPLOIREPERE_AJOUTER));
$canAfficher = $this->isAllowed(EmploireperePrivileges::getResourceId(EmploireperePrivileges::EMPLOIREPERE_AFFICHER));
$canModifier = $this->isAllowed(EmploireperePrivileges::getResourceId(EmploireperePrivileges::EMPLOIREPERE_MODIFIER));
$canHistoriser = $this->isAllowed(EmploireperePrivileges::getResourceId(EmploireperePrivileges::EMPLOIREPERE_HISTORISER));
$canSupprimer = $this->isAllowed(EmploireperePrivileges::getResourceId(EmploireperePrivileges::EMPLOIREPERE_SUPPRIMER));

?>

<h1 class="page-header">
    Emploi-repères
</h1>

<?php if ($canAjouter) : ?>
    <?php /** @see \EmploiRepere\Controller\EmploiRepereController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('emploi-repere/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un emploi-repère
    </a>
<?php endif; ?>

<table class="table table-condensed" id="emploisreperes">
    <thead>
        <tr>
            <th class="col-md-6" data-column-id="Libellé"> Libellé </th>
            <th class="col-md-2" data-column-id="Code"> Code </th>
            <th class="col-md-2" data-column-id="Codes fonctions associés"> Codes fonctions associés</th>
            <th class="col-md-2 action" data-column-id="Action"> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($emploisReperes as $emploiRepere) : ?>
        <tr class=" <?php if ($emploiRepere->estHistorise()) echo 'historise'; ?>">
            <td data-column-id="Libellé">
                <?php echo $emploiRepere->getLibelle(); ?>
                <?php if ($emploiRepere->getDescription()) : ?>
                    <span class="icon icon-info" title="<?php echo $emploiRepere->getDescription(); ?>" data-bs-toggle="tooltip" data-bs-html="true"></span>
                <?php endif; ?>
            </td>
            <td data-column-id="Code"> <code><?php echo $emploiRepere->getCode(); ?></code> </td>
            <td data-column-id="Codes fonctions associés">
                <?php $associtions = $emploiRepere->getCodesFonctionsFichesMetiers(); ?>
                <?php if (empty($associations)) : ?>
                    <span class="missing-data"> Aucune association </span>
                <?php else : ?>
                    <?php /** @var EmploiRepereCodeFonctionFicheMetier $association */ ?>
                    <?php foreach ($associations as $association) : ?>
                        <code><?php echo $association->getCodeFonction()->getCode(); ?></code>
                        <?php echo $association->getFicheMetier()->getLibelle(); ?><br>
                        <?php if ($canModifier) : ?>
                            <a href="" class="action primary">
                                <span class="icon icon-modifier"></span> Ajouter
                            </a>
                            <a href="" class="action danger">
                                <span class="icon icon-unchecked"></span> Supprimer
                            </a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <br>
                <?php if ($canModifier) : ?>
                    <?php /** @see \EmploiRepere\Controller\EmploiRepereCodeFonctionFicheMetierController::ajouterAction() */ ?>
                    <a href="<?php echo $this->url('emploi-repere/emploi-repere-code-fonction-fiche-metier/ajouter', ['emploi-repere' => $emploiRepere->getId()], [], true); ?>"
                       class="action primary ajax-modal" data-event="modification">
                        <span class="icon icon-ajouter"></span> Ajouter
                    </a>
                <?php endif; ?>

            </td>
            <td class="action" data-column-id="Action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \EmploiRepere\Controller\EmploiRepereController::ajouterAction() */ ?>
                    <a href="<?php echo $this->url('emploi-repere/afficher', ['emploi-repere' => $emploiRepere->getId()], [], true); ?>"
                       class="action secondary ajax-modal">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \EmploiRepere\Controller\EmploiRepereController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('emploi-repere/modifier', ['emploi-repere' => $emploiRepere->getId()], [], true); ?>"
                       class="action primary">
                        <span class="icon icon-edit"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($emploiRepere->estNonHistorise()) : ?>
                        <?php /** @see \EmploiRepere\Controller\EmploiRepereController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('emploi-repere/historiser', ['emploi-repere' => $emploiRepere->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \EmploiRepere\Controller\EmploiRepereController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('emploi-repere/restaurer', ['emploi-repere' => $emploiRepere->getId()], [], true); ?>"
                           class="action warning">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \EmploiRepere\Controller\EmploiRepereController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('emploi-repere/supprimer', ['emploi-repere' => $emploiRepere->getId()], [], true); ?>"
                       class="action danger ajax-modal" data-event="modification">
                        <span class="icon icon-unchecked"></span>
                        Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });

        $('#emploisreperes').DataTable({
            autoWidth: false,
            columnDefs: [{
                "targets": 3,
                "orderable": false
            }],
            language: {
                url: '/js/datatables_fr.json'
            }
        });
    });
</script>