<?php

/**
 * @var string $title
 * @var string $text
 * @var string $action
 * @var bool $complement
 */

?>

<p class="lead">
<?php echo $text; ?>
</p>

<div class="row">
    <div class="col-md-4">
        <form method="post" action="<?php echo $action; ?>">
<table>
    <tr><td>
        <input type="hidden" name="reponse" value="oui">
        <input type="submit" name="oui" class="btn btn-success action" value="Oui, je suis sûr&middot;e">
        <?php if ($complement === 'oui') : ?>
            </td><td>
                <label for="complement">Compléments liés à l'acceptation</label>
                <textarea id="complement" name="complement" class="type2 form-control" style="width: 100%;"></textarea>
        <?php endif; ?>

    </td></tr>
</table>
</form>
    </div>
    <div class="col-md-4">
        <form method="post" action="<?php echo $action; ?>">
<table>
    <tr><td>
                <input type="hidden" name="reponse" value="non">
                <input type="submit" id="non" name="non" class="btn btn-danger action"  value="Non, je ne veux pas">
                <?php if ($complement === 'non') : ?>
        </td><td>
                    <label for="complement">Compléments liés au refus</label>
                    <textarea id="complement" name="complement" class="type2 form-control" style="width: 100%;"></textarea>
                <?php endif; ?>

        </td></tr>
</table>
</form>
    </div>
</div>

<?php if ($complement !== true) : ?>
    <script>
        $(function() {
            $("input#non").click(function(e){
                $('div.modal').modal('hide');
                e.preventDefault();
            });
        });
    </script>
<?php else : ?>
    <script>
        $(document).ready(function() {
            tinymce.remove();
            tinymce.init({
                selector: '.type2',
                toolbar: 'newdocument undo redo | bold italic underline removeformat | bullist',
                resize: true,
                language: 'fr_FR',
                plugins: 'lists',
                statusbar: true,
                browser_spellcheck : true,
                branding: false,
                menu: {},
                body_id: 'complement',
                setup: function (editor) {
                    editor.on("focusout", function () {
                        console.log(tinymce.get('complement').getContent());
                        $('textarea').val(tinymce.get('complement').getContent());
                    });
                }
            });
        });

        $('select').selectpicker();
    </script>
<?php endif; ?>

