<?php

/**
 * @see \Application\Controller\CorpsController::afficherAgentsAvecCorrespondanceAction();
 * @var Correspondance $correspondance
 */

use Application\Entity\Db\AgentGrade;
use Application\Entity\Db\Correspondance;

$now = new DateTime();

/** @var  AgentGrade[] $agents */
$agents = $correspondance->getAgentGrades();
usort($agents, function(AgentGrade $a, AgentGrade $b) {return $a->getAgent()->getDenomination() > $b->getAgent()->getDenomination();});
?>

<dl class="dl-horizontal">
    <dt> Correspondance </dt>
    <dd>[#<?php echo $correspondance->getId(); ?>] <?php echo $correspondance->getLibelleLong(); ?></dd>
    <dt> #AgentGrade </dt>
    <dd> <?php echo count($agents); ?></dd>
</dl>

<table class="table table-condensed">
    <thead>
        <tr>
            <th> Id </th>
            <th> Agent </th>
            <th> Début </th>
            <th> Fin </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($agents as $agent) : ?>
        <tr <?php if ($agent->estFini($now)) echo 'class="historise"'; ?> >
            <td> <?php echo $agent->getId(); ?> </td>
            <td> <?php echo $agent->getAgent()->getDenomination(); ?> </td>
            <td> <?php echo ($agent->getDateDebut()) ? $agent->getDateDebut()->format('d/m/Y') : "---"; ?> </td>
            <td> <?php echo ($agent->getDateFin()) ? $agent->getDateFin()->format('d/m/Y') : "---"; ?> </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>



