<?php
/**
 * @var Champ $champ
 * @var string $reponse
 */

use Autoform\Entity\Db\Champ;

$annees = [];
$annee_Y = (new DateTime())->format('Y');
$debut   = 2010;
$fin     = (((int)$annee_Y) + 10);
for ($annee = $debut ; $annee < $fin ; $annee++) {
    $option = $annee . '/' . ($annee + 1);
    $annees[] = $option;
}

?>

<div class="form-group row">
    <label for="textarea_<?php echo $champ->getId()?>" class="col-sm-2 control-label">
        <?php echo $champ->getLibelle()?>&nbsp;:
    </label>
    <div class="col-sm-10">
        <select class="form-control" name="<?php echo $champ->getId()?>">
            <option value="null"></option>
            <?php foreach ($annees as $item)  : ?>
                <option value="<?php echo $item; ?>"
                <?php if ($item === $reponse) : ?>
                    selected
                <?php endif; ?>
                >
                    <?php echo $item; ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>