<?php
/**
 * @var Champ $champ
 * @var string $reponse
 */

use Autoform\Entity\Db\Champ;

$isBalisee = false;
$date1 = null;
$date2 = null;

$periode = ["Année entière", "Premier semestre", "Second semestre", "Balisée"];

?>


<div class="form-group row">
    <label for="textarea_<?php echo $champ->getId(); ?>" class="col-sm-2 control-label">
        <?php echo $champ->getLibelle();?>&nbsp;:
    </label>
    <div class="col-sm-10">
        <select class='periode' name="select_<?php echo $champ->getId(); ?>">
            <option value="null"></option>
                <?php foreach ($periode as $item) : ?>
                    <option value="<?php echo $item; ?>"
                    <?php if ($item === $reponse)  : ?>
                        selected
                    <?php endif;?>
                    <?php if ($item === 'Balisée' && substr($reponse, 0,3) === 'Du ' && substr($reponse, 13,4) === ' au ') : ?>
                        <?php $isBalisee = true; ?>
                        selected
                    <?php endif; ?>
            >
                <?php echo $item; ?>
            </option>
            <?php endforeach; ?>
        </select>

        <?php
            if ($isBalisee) {
                $splits = explode(' ', $reponse);
                $splits1 = explode('/', $splits[1]);
                $date1 = $splits1[2]. "-" . $splits1[1] . "-" .$splits1[0];
                $splits2 = explode('/', $splits[3]);
                $date2 = $splits2[2]. "-" . $splits2[1] . "-" .$splits2[0];
            }
        ?>

        <span id="datation_<?php echo $champ->getId(); ?>">
         du
        <input  type="date" name="debut_<?php echo $champ->getId(); ?>"
        <?php if ($isBalisee) : ?>
            value="<?php echo $date1; ?>"
        <?php endif; ?>
        />
         au
        <input  type="date" name="fin_<?php echo $champ->getId(); ?>"
        <?php if ($isBalisee) : ?>
            value="<?php echo $date2; ?>"
        <?php endif; ?>
        />
        </span>
    </div>
</div>