<?php

/**
 * @see \UnicaenParametre\Controller\CategorieController::indexAction()
 * @var Parametre[] $parametres
 * @var Categorie[] $categories
 * @var Categorie $selection
 */

use UnicaenParametre\Entity\Db\Categorie;
use UnicaenParametre\Entity\Db\Parametre;
use UnicaenParametre\Provider\Privilege\ParametrecategoriePrivileges;

$canAjouterCategorie = $this->isAllowed(ParametrecategoriePrivileges::getResourceId(ParametrecategoriePrivileges::PARAMETRECATEGORIE_AJOUTER));

$array_categorie = [];
$array_parametre = [];
foreach ($parametres as $parametre) {
    $array_categorie[$parametre->getCategorie()->getId()] = $parametre->getCategorie();
    $array_parametre[$parametre->getCategorie()->getId()][] = $parametre;
}

$this->headTitle("Affichage des paramètres");

if ($selection !== null) $categories = [ $selection ];
?>

<h1 class="page-header">
    Affichage des paramètres
</h1>

<?php if ($selection === null AND $canAjouterCategorie) : ?>
    <a
        <?php /** @see \Application\Controller\ParametreCategorieController::ajouterAction() */ ?>
        href="<?php echo $this->url('parametre/categorie/ajouter', ['categorie' => -1], [], true); ?>"
        class="btn btn-primary ajax-modal" data-event="modification">
        <i class="fas fa-plus"></i> Ajouter une catégorie
    </a>
<?php endif; ?>

<?php foreach ($categories as $categorie) : ?>
    <?php $id = $categorie->getId(); ?>

    <div class="row">
        <div class="col-md-6">
            <h2 title="<?php echo $categorie->getDescription(); ?>" data-toggle="tooltip" data-html="true" style="cursor: help;"> Catégorie : <?php echo $categorie->getLibelle(); ?> </h2>
        </div>
        <div class="col-md-6">
            <br/>
            <a  <?php /** @see \Application\Controller\ParametreController::ajouterAction() */?>
                href="<?php echo $this->url('parametre/ajouter', ['categorie' => $categorie->getId()], [], true); ?>"
                class="btn btn-primary ajax-modal" data-event="modification">
                <i class="fas fa-plus"></i> Ajouter un paramètre
            </a>
            <?php if ($selection === null) : ?>
                <a  <?php /** @see \Application\Controller\ParametreCategorieController::modifierAction() */?>
                    href="<?php echo $this->url('parametre/categorie/modifier', ['categorie' => $categorie->getId()], [], true); ?>"
                    class="btn btn-primary ajax-modal" data-event="modification">
                    <i class="fas fa-pencil-alt"></i> Modifier la catégorie
                </a>
                <?php if (!isset($array_parametre[$id]) OR empty ($array_parametre[$id])) : ?>
                    <a  <?php /** @see \Application\Controller\ParametreCategorieController::supprimerAction() */?>
                        href="<?php echo $this->url('parametre/categorie/supprimer', ['categorie' => $categorie->getId()], [], true); ?>"
                        class="btn btn-danger ajax-modal" data-event="modification">
                        <i class="fas fa-times"></i> Supprimer la catégorie
                    </a>
                <?php else : ?>
                    <span class="btn btn-danger disabled" data-toggle="tooltip" data-html="true"
                          title="La catégorie est non vide et ne peut être supprimer"
                    >
                    <i class="fas fa-times"></i> Supprimer la catégorie
                </span>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>

    <?php if (!isset($array_parametre[$id])) : ?>
        Aucun paramètre pour cette catégorie
    <?php else : ?>
        <table class="table table-condensed">
            <thead>
            <tr>
                <th style="width:60%; min-width:20rem;">
                    Paramètre
                </th>
                <th style="width:30%; min-width:10rem;">
                    Valeur
                </th>
                <th>
                    Action
                </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($array_parametre[$id] as $parametre) : ?>
                <tr>
                    <td>
                        <span title="<?php echo $parametre->getDescription(); ?>" data-toggle="tooltip" data-html="true" style="cursor: help;">
                            <?php echo $parametre->getLibelle(); ?>
                        </span>
                    </td>
                    <td>
                        <?php $valeur = $parametre->getValeur(); ?>
                        <?php switch ($valeur) {
                            case 'true' :
                                echo '<i class="fas fa-check" style="color:darkgreen;"></i>';
                                break;
                            case 'false' :
                                echo '<i class="fas fa-times" style="color:darkred;"></i>';
                                break;
                            case null :
                                echo '<em style="color: lightcoral">Aucune valeur</em>';
                                break;
                            default :
                                echo $valeur;
                                break;
                        }
                        ?>
                    </td>
                    <td>
                        <a  <?php /** @see \Application\Controller\ParametreController::modifierValeurAction() */?>
                            href="<?php echo $this->url('parametre/modifier-valeur', ['parametre' => $parametre->getId()], [], true); ?>" title="Modifier la valeur du paramètre <strong><?php echo $parametre->getCode(); ?></strong"
                            class="ajax-modal" data-event="modification" data-toggle="tooltip" data-html="true">
                            <i class="fas fa-pencil-alt"></i></a>
                        <a  <?php /** @see \Application\Controller\ParametreController::modifierAction() */?>
                            href="<?php echo $this->url('parametre/modifier', ['parametre' => $parametre->getId()], [], true); ?>" title="Modifier le paramètre <strong><?php echo $parametre->getCode(); ?></strong"
                            class="ajax-modal" data-event="modification" data-toggle="tooltip" data-html="true">
                            <i class="fas fa-cog"></i></a>
                        <a  <?php /** @see \Application\Controller\ParametreController::supprimerAction() */?>
                            href="<?php echo $this->url('parametre/supprimer', ['parametre' => $parametre->getId()], [], true); ?>" title="Supprimer le paramètre <strong><?php echo $parametre->getCode(); ?></strong"
                            class="ajax-modal disabled" data-event="modification" data-toggle="tooltip" data-html="true" disabled>
                            <i class="fas fa-times disabled"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif;?>
<?php endforeach; ?>

<script>
    $(function () {
        $('body')
            .on("modification", function (event) {
                event.div.modal('hide');
                window.location.reload();
            })
            .tooltip({
                selector: '[data-toggle="tooltip"]',
                placement: "bottom",
                html: true
            });
    });
</script>

