-- select
--     concat(
--             'insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES (',
--             concat('(select id from unicaen_utilisateur_role urr where urr.role_id = ''', uur.role_id, ''')'),
--             ',',
--             concat('(select id from unicaen_privilege_privilege upp where upp.code = ''', upp.code, ''' and upp.categorie_id = (select id from unicaen_privilege_categorie where code =''', upc.code , '''))'),
--             ');'
--     )
-- from unicaen_privilege_privilege_role_linker l
--          join unicaen_privilege_privilege upp on l.privilege_id = upp.id
--          join unicaen_privilege_categorie upc on upp.categorie_id = upc.id
--          join unicaen_utilisateur_role uur on l.role_id = uur.id
-- where upc.namespace = 'MissionSpecifique\Provider\Privilege';

-- MODULE MISSION SPECIFIQUE
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_detruire' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifique_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifique')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_detruire' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetheme_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetheme')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_detruire' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'missionspecifiquetype_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='missionspecifiquetype')));
