-- select
--     concat(
--             'insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES (',
--             concat('(select id from unicaen_utilisateur_role urr where urr.role_id = ''', uur.role_id, ''')'),
--             ',',
--             concat('(select id from unicaen_privilege_privilege upp where upp.code = ''', upp.code, ''' and upp.categorie_id = (select id from unicaen_privilege_categorie where code =''', upc.code , '''))'),
--             ');'
--     )
-- from unicaen_privilege_privilege_role_linker l
--          join unicaen_privilege_privilege upp on l.privilege_id = upp.id
--          join unicaen_privilege_categorie upc on upp.categorie_id = upc.id
--          join unicaen_utilisateur_role uur on l.role_id = uur.id
-- where upc.namespace = 'FichePoste\Provider\Privilege';

-- MODULE FICHE DE POSTE
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_responsable' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_responsable' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_responsable' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_responsable' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_responsable' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_responsable' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_agent' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_agent' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_agent' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_valider_agent' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier_poste' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier_poste' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_modifier_poste' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_associeragent' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_associeragent' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_associeragent' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_graphique' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_graphique' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_graphique' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_graphique' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_detruire' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_etat' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_etat' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_etat' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher_poste' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher_poste' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher_poste' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_afficher_poste' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'ficheposte_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='ficheposte')));
