<?php

/**
 * @see \UnicaenGlossaire\View\Helper\DictionnaireGenerationViewHelper
 * @var Definition[] $definitions
 * @var array $options
 */

use UnicaenGlossaire\Entity\Db\Definition;

$useHistorisee = (isset($options['historise']) AND $options['historise'] === true);
?>
<script id="dictionnaire">
    let dictionnary = {};
    <?php /** Ajouter des termes  */?>
    <?php $alreadyInDictionnaire = []; ?>
    <?php foreach ($definitions as $definition) : ?>
        <?php
        $alreadyInDictionnaire[$definition->getTerme()] = true;
        $libelle = $definition->getDefinition();
        $libelle = str_replace("\t", "", $libelle);
        $libelle = str_replace("\r", "", $libelle);
        $libelle = str_replace("\n", "", $libelle);
        $libelle = htmlentities($libelle, ENT_QUOTES);
        ?>
        <?php if ($useHistorisee OR $definition->estNonHistorise()) : ?>
            dictionnary["<?php echo strtolower($definition->getTerme()); ?>"] = "<?php echo $libelle; ?>";
        <?php endif; ?>
    <?php endforeach; ?>

    <?php /** Ajouter des écritures alternatives  */?>
    <?php foreach ($definitions as $definition) : ?>
        <?php
        if ($definition->getAlternatives()) {
            $split = explode(';',$definition->getAlternatives());
            foreach ($split as $terme) {
                if ($useHistorisee or $definition->estNonHistorise()) {
                    if (!isset($alreadyInDictionnaire[$terme])) : ?>
                        dictionnary["<?php echo strtolower($terme); ?>"] = dictionnary["<?php echo strtolower($definition->getTerme()); ?>"];
                <?php endif;
                }
                $alreadyInDictionnaire[$terme] = true;
            }
        }
        ?>
    <?php endforeach; ?>

    function display_definition(text) {
        let definition = dictionnary[text.toLowerCase()];
        if (definition === undefined) {
            definition = "Aucune définition pour ce terme.";
            // return text;
        }
        return "<abbr title='"+definition+"' data-toggle='tooltip' data-html='true'>" + text + "</abbr>";
    }
</script>