<?php return array(
    'root' => array(
        'name' => 'unicaen/preecog',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '529b552e5de8233237e35dc2c7ddb7a5fe52bfea',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'beberlei/assert' => array(
            'pretty_version' => 'v2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'reference' => '124317de301b7c91d5fce34c98bba2c6925bec95',
            'type' => 'library',
            'install_path' => __DIR__ . '/../beberlei/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/varexporter' => array(
            'pretty_version' => '0.3.7',
            'version' => '0.3.7.0',
            'reference' => '3e263cd718d242594c52963760fee2059fd5833c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/varexporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cboden/ratchet' => array(
            'pretty_version' => 'v0.4.4',
            'version' => '0.4.4.0',
            'reference' => '5012dc954541b40c5599d286fd40653f5716a38f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cboden/ratchet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/package-versions-deprecated' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'b4f54f74ef3453349c24a845d22392cd31e65f1d',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./package-versions-deprecated',
            'aliases' => array(
                0 => '1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'container-interop/container-interop' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^1.2.0',
            ),
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.14.x-dev',
            'version' => '1.14.9999999.9999999-dev',
            'reference' => '2273d90f6d32b9fcb526c9394b214fd7abf7435b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '1.13.x-dev',
            'version' => '1.13.9999999.9999999-dev',
            'reference' => '56cd022adb5514472cb144c087393c1821911d09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '1.7.x-dev',
            'version' => '1.7.9999999.9999999-dev',
            'reference' => 'd84715fa080a32f76a68200eb015587d99f4675e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '2.13.x-dev',
            'version' => '2.13.9999999.9999999-dev',
            'reference' => 'f3812c026e557892c34ef37f6ab808a6b567da7f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.13.9',
            'version' => '2.13.9.0',
            'reference' => 'c480849ca3ad6706a39c970cdfe6888fa8a058b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-laminas-hydrator' => array(
            'pretty_version' => '2.2.x-dev',
            'version' => '2.2.9999999.9999999-dev',
            'reference' => '526d3ac3dd087869ef6107e986cff3c353fee018',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/doctrine-laminas-hydrator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-module' => array(
            'pretty_version' => '4.1.1',
            'version' => '4.1.1.0',
            'reference' => 'f9cf0986ea70655d23e10fbf0d9198cb3e1eda1d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/doctrine-module',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-orm-module' => array(
            'pretty_version' => '4.0.x-dev',
            'version' => '4.0.9999999.9999999-dev',
            'reference' => '6f82725c260b30423059736e9650a60ddf7cfc52',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/doctrine-orm-module',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'reference' => 'c0b86635f580c8153751b8b4303203484c491b85',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '1.4.x-dev',
            'version' => '1.4.9999999.9999999-dev',
            'reference' => '4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.x-dev',
            'version' => '1.5.9999999.9999999-dev',
            'reference' => '10dcfce151b967d20fde1b34ae6640712c3891bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.3.x-dev',
            'version' => '1.3.9999999.9999999-dev',
            'reference' => 'ff0bfc39c3cce1cc0aa69471235194c6f104384d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/orm' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'reference' => '01187c9260cd085529ddd1273665217cae659640',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/orm',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '1.4.x-dev',
            'version' => '1.4.9999999.9999999-dev',
            'reference' => '7faf8b78ee3d7421fa57855e54cac6ed8c429983',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/reflection' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '2213dd03ce67b9bbf8c599522fc4e93f5743462a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/reflection',
            'aliases' => array(
                0 => '1.3.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'evenement/evenement' => array(
            'pretty_version' => 'v3.0.1',
            'version' => '3.0.1.0',
            'reference' => '531bfb9d15f8aa57454f5f0285b18bec903b8fb7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../evenement/evenement',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.x-dev',
            'version' => '6.5.9999999.9999999-dev',
            'reference' => 'a52f0440530b54fa079ce76e8c5d196a42cad981',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '43453bfd44284ccb73d1beb16f3d30ea888097c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(
                0 => '1.5.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => 'e98e3e6d4f86621a9b75f623996e6bbdeb4b9318',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jasig/phpcas' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => 'd6f5797fb568726f34c8e48741776d81e4a2646b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jasig/phpcas',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-authentication' => array(
            'pretty_version' => '2.11.x-dev',
            'version' => '2.11.9999999.9999999-dev',
            'reference' => '51815691d862b82b749a4aa9c4f6ec078d579f74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-authentication',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache' => array(
            'pretty_version' => '2.13.x-dev',
            'version' => '2.13.9999999.9999999-dev',
            'reference' => 'fc3255833c1c687ed2c5312e9663ef062be155c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-apc' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'reference' => '374742d687b0bcfdc1f0c9ce04c4b2bde23a2cd9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-apc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-apcu' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'reference' => 'f46a34fa1064106bd194e533340ebf7ac149e69a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-apcu',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-blackhole' => array(
            'pretty_version' => '1.3.x-dev',
            'version' => '1.3.9999999.9999999-dev',
            'reference' => 'ad91945b708d92fbab9b8d2b830102e132cf0b62',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-blackhole',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-dba' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'reference' => '56bf20d1f65502da0e06b99bb6ad5887a139c98e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-dba',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-ext-mongodb' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'reference' => '72f68589cc8323fa688167a4720b795dd0907f4e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-ext-mongodb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-filesystem' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'reference' => 'a5846beaa6743c843476564bde6cf3eb26ff87b0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-memcache' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'reference' => '6f43bc0ce00bfb18f0783da65b8e68c530c2f848',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-memcache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-memcached' => array(
            'pretty_version' => '1.3.x-dev',
            'version' => '1.3.9999999.9999999-dev',
            'reference' => 'd05f33e43a352b85c6d0208e9cfbf2a59f02ede3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-memcached',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-memory' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'reference' => '31849bf952451772a816f4cd72d53192335a5549',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-memory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-mongodb' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'reference' => '7fa4b48bcb8ccf22e95fd48cc5d48b1ab26c81a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-mongodb',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-redis' => array(
            'pretty_version' => '1.3.x-dev',
            'version' => '1.3.9999999.9999999-dev',
            'reference' => 'de8a63d4a0ef1ccead401eb7fb6d75b57fa3f9ee',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-redis',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-session' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'reference' => 'c088940acb81741b32af68434d2403f794b34a7b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-session',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-wincache' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'reference' => '63835697f3c7cc3de551a54175ab77decff111aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-wincache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-xcache' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'reference' => '42fb8a6c0248cd7069e6f99c0185b526c0239c2a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-xcache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-adapter-zend-server' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'reference' => 'e2db90f67fbeccc29910e0923a053aa93c9b2a4f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-cache-storage-adapter-zend-server',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-cache-storage-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'laminas/laminas-code' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'reference' => '889ba6f34788eee250b5e8f895ca87dc0d685da2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-code',
            'aliases' => array(
                0 => '3.5.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'laminas/laminas-config' => array(
            'pretty_version' => '3.8.x-dev',
            'version' => '3.8.9999999.9999999-dev',
            'reference' => 'fd01b73840dd6a6a0d7ef771bf614fac42a9d5ac',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-console' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'reference' => '9a5e8cf0076f44840892599fcf2a3d2b249a008a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-console',
            'aliases' => array(
                0 => '2.9.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'laminas/laminas-crypt' => array(
            'pretty_version' => '3.9.x-dev',
            'version' => '3.9.9999999.9999999-dev',
            'reference' => '0972bb907fd555c16e2a65309b66720acf2b8699',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-crypt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-db' => array(
            'pretty_version' => '2.16.x-dev',
            'version' => '2.16.9999999.9999999-dev',
            'reference' => 'ab0c87068014a789aea1021c39b0870ece4f6f4f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-db',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-dependency-plugin' => array(
            'pretty_version' => '2.2.x-dev',
            'version' => '2.2.9999999.9999999-dev',
            'reference' => '78f177818c26b452a60b14509a1f075cfb9ee2a7',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../laminas/laminas-dependency-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-developer-tools' => array(
            'pretty_version' => '2.4.x-dev',
            'version' => '2.4.9999999.9999999-dev',
            'reference' => '2e3fc0ef0835aac766b6ecf4e767a85591153597',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-developer-tools',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laminas/laminas-escaper' => array(
            'pretty_version' => '2.11.x-dev',
            'version' => '2.11.9999999.9999999-dev',
            'reference' => '155e5ae9f2576a10416988d02ded10e92a27805f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-escaper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-eventmanager' => array(
            'pretty_version' => '3.6.x-dev',
            'version' => '3.6.9999999.9999999-dev',
            'reference' => '3f90c39141bcac350ba8ecde155f6e29615442b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-eventmanager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-filter' => array(
            'pretty_version' => '2.18.x-dev',
            'version' => '2.18.9999999.9999999-dev',
            'reference' => '0398d5e32866cb0d5335747c1bf73aecbbeb20ce',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-filter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-form' => array(
            'pretty_version' => '2.18.x-dev',
            'version' => '2.18.9999999.9999999-dev',
            'reference' => '882fc090e565eeded4c1d5013daca8a973b0e40c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-form',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-http' => array(
            'pretty_version' => '2.16.x-dev',
            'version' => '2.16.9999999.9999999-dev',
            'reference' => 'b1ec4879c5ad153c3a940695e4e56e6a5ffe4f0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-http',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-hydrator' => array(
            'pretty_version' => '3.2.x-dev',
            'version' => '3.2.9999999.9999999-dev',
            'reference' => '2b18cbf0cc37d419550fe2ef6941fbe2ac5a0107',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-hydrator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-i18n' => array(
            'pretty_version' => '2.17.x-dev',
            'version' => '2.17.9999999.9999999-dev',
            'reference' => '855d90c553553b385312da2e551079c16b746795',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-i18n',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-i18n-resources' => array(
            'pretty_version' => '2.9.x-dev',
            'version' => '2.9.9999999.9999999-dev',
            'reference' => 'd56a4f7e9482700e37637cb0f10fcdeb9d6b3341',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-i18n-resources',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-inputfilter' => array(
            'pretty_version' => '2.20.x-dev',
            'version' => '2.20.9999999.9999999-dev',
            'reference' => 'f570c504bbecf81eda13e2cee45c1e945d07f1ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-inputfilter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-json' => array(
            'pretty_version' => '3.4.x-dev',
            'version' => '3.4.9999999.9999999-dev',
            'reference' => '9874aa22a5d060ff51aa04978fc0e788441ffeea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-json',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-ldap' => array(
            'pretty_version' => '2.14.x-dev',
            'version' => '2.14.9999999.9999999-dev',
            'reference' => '09f975691d7dd8c241ff033f4b12fbf084f1fdb1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-ldap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-loader' => array(
            'pretty_version' => '2.9.x-dev',
            'version' => '2.9.9999999.9999999-dev',
            'reference' => 'f6d1c7feb93a87fe1b9b39a3602517947eb22a71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-loader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-log' => array(
            'pretty_version' => '2.16.x-dev',
            'version' => '2.16.9999999.9999999-dev',
            'reference' => '8cc86ed16b377f215ccbe0d07502e242d7652d8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mail' => array(
            'pretty_version' => '2.17.x-dev',
            'version' => '2.17.9999999.9999999-dev',
            'reference' => '6f33c46f6c22cdb4c63d5f7f9e131472100dba8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-math' => array(
            'pretty_version' => '3.6.x-dev',
            'version' => '3.6.9999999.9999999-dev',
            'reference' => 'ffd0da0b7c45edf608268d9dfeeedd5ae0c1b24f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mime' => array(
            'pretty_version' => '2.10.x-dev',
            'version' => '2.10.9999999.9999999-dev',
            'reference' => '12124303be35f3bc351a77714e11a7abed4e3665',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-modulemanager' => array(
            'pretty_version' => '2.12.x-dev',
            'version' => '2.12.9999999.9999999-dev',
            'reference' => '2a3d94306987a484a4b65bbb590df86e100ca88c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-modulemanager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mvc' => array(
            'pretty_version' => '3.4.x-dev',
            'version' => '3.4.9999999.9999999-dev',
            'reference' => 'f2febe11fbcf7dd93ccc669adbd16c31002348fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mvc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mvc-console' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'reference' => '90338c7b61a5fa8445c0a41925a4ae351459fa79',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mvc-console',
            'aliases' => array(
                0 => '1.3.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mvc-i18n' => array(
            'pretty_version' => '1.4.x-dev',
            'version' => '1.4.9999999.9999999-dev',
            'reference' => '06dfa3e4e6707841ec2be5acbf5b4d432f6e42eb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mvc-i18n',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mvc-plugin-fileprg' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'reference' => '2d6a64bf916b3f5f26a062b9c62d06af26ee483f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mvc-plugin-fileprg',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mvc-plugin-flashmessenger' => array(
            'pretty_version' => '1.9.x-dev',
            'version' => '1.9.9999999.9999999-dev',
            'reference' => '86bb1c654e5fafaf34d4deaa7dc9af721fbcb42d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mvc-plugin-flashmessenger',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mvc-plugin-identity' => array(
            'pretty_version' => '1.4.x-dev',
            'version' => '1.4.9999999.9999999-dev',
            'reference' => '135373213a1bec6176d5190e260c4d9e0b2c4df3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mvc-plugin-identity',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-mvc-plugin-prg' => array(
            'pretty_version' => '1.6.x-dev',
            'version' => '1.6.9999999.9999999-dev',
            'reference' => 'd8653b6fa77d249d4f994d5725617e90f8822dd8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mvc-plugin-prg',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-navigation' => array(
            'pretty_version' => '2.14.x-dev',
            'version' => '2.14.9999999.9999999-dev',
            'reference' => 'b73ffcc26af47336dcb69bcfb1fdb22f295a1f3a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-navigation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-paginator' => array(
            'pretty_version' => '2.14.x-dev',
            'version' => '2.14.9999999.9999999-dev',
            'reference' => 'd239c423d2fb6a6b7e2cf4881a437b57f1717d45',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-paginator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-permissions-acl' => array(
            'pretty_version' => '2.10.x-dev',
            'version' => '2.10.9999999.9999999-dev',
            'reference' => 'e302c43414360224959a07fb090330f8633c805f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-permissions-acl',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-router' => array(
            'pretty_version' => '3.8.x-dev',
            'version' => '3.8.9999999.9999999-dev',
            'reference' => '3279ee684cf877dc92551891acf8daa71bbe90b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-router',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-serializer' => array(
            'pretty_version' => '2.14.x-dev',
            'version' => '2.14.9999999.9999999-dev',
            'reference' => 'aa72a694d79f01ef1252b276ca9930158c3b877d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-servicemanager' => array(
            'pretty_version' => '3.16.x-dev',
            'version' => '3.16.9999999.9999999-dev',
            'reference' => '851c0321f8dfe7d8e45507e4ad9990f757cdbe66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-servicemanager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-session' => array(
            'pretty_version' => '2.13.x-dev',
            'version' => '2.13.9999999.9999999-dev',
            'reference' => 'e4f0b1ca605824072c2aaeb925912a78de07d9ca',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-session',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-stdlib' => array(
            'pretty_version' => '3.11.x-dev',
            'version' => '3.11.9999999.9999999-dev',
            'reference' => 'ce95a2924cce2ebcd73ccf7196776ab7c1480dab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-stdlib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-text' => array(
            'pretty_version' => '2.10.x-dev',
            'version' => '2.10.9999999.9999999-dev',
            'reference' => 'a3de48acd4942202f58ef6815bb9369cf4bc3235',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-text',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-uri' => array(
            'pretty_version' => '2.10.x-dev',
            'version' => '2.10.9999999.9999999-dev',
            'reference' => 'b553be02ac95ffe9c1a503a9ed20d863c64b00d1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-uri',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-validator' => array(
            'pretty_version' => '2.21.x-dev',
            'version' => '2.21.9999999.9999999-dev',
            'reference' => '9fa954d60065913c165318b0c1957050794867ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-view' => array(
            'pretty_version' => '2.23.x-dev',
            'version' => '2.23.9999999.9999999-dev',
            'reference' => 'ae32391bdec45ca9fc73dd0882cd7301ab07ecf3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-view',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-zendframework-bridge' => array(
            'pretty_version' => '1.7.x-dev',
            'version' => '1.7.9999999.9999999-dev',
            'reference' => 'a24d4f7242ea9b7fecfabd5cb95728c56ea93a46',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-zendframework-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'reference' => '5579edf28aee1190a798bfa5be8bc16c563bd524',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpdf/mpdf' => array(
            'pretty_version' => 'v8.1.1',
            'version' => '8.1.1.0',
            'reference' => 'e511e89a66bdb066e3fbf352f00f4734d5064cbf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/mpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '14daed4296fae74d9e3201d2c4925d1acb7aa614',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => '4.x-dev',
            'version' => '4.9999999.9999999.9999999-dev',
            'reference' => '2d589921f23d869846a52c541247e0bafca61ab3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ocramius/package-versions' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.11.99',
            ),
        ),
        'ocramius/proxy-manager' => array(
            'pretty_version' => '2.10.x-dev',
            'version' => '2.10.9999999.9999999-dev',
            'reference' => '13b37152a00a1237a45104c270eb750508bcfa87',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ocramius/proxy-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '597f30e6dfd32a85fd7dbe58cb47554b5bad910e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'efd67d1dc14a7ef4fc4e518e7dee91c271d524e4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0.0 || 2.0.0 || 3.0.0',
                2 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '3.x-dev',
            'version' => '3.9999999.9999999.9999999-dev',
            'reference' => '7201bafdb2c5bff4136ab1e7b32fb02392cedca3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ratchet/rfc6455' => array(
            'pretty_version' => 'v0.3.1',
            'version' => '0.3.1.0',
            'reference' => '7c964514e93456a52a99a20fcfa0de242a43ccdb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ratchet/rfc6455',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/cache' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '161426edd093aa825d3f93b62a7f6091be7cfca2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/dns' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => 'c0902edd16ba2167af9866fa225f80483e153307',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/dns',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/event-loop' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '1c57f7904595b3d6afda25c9a947435ee6a96dd6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/event-loop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => '2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'reference' => '3320514e2621f57c11772d6571f7f637fb29550d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise-timer' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '790ce7505ae11571766b7c1119d18307e1c8fbc0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise-timer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/socket' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => '12baa6cc7e818dcb1893e6516ae002756f6916c3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/socket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/stream' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'reference' => 'f2a84c10f23a32491a4cbda03d6466628dc5d84b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/stream',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.x-dev',
            ),
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'v2.3.6',
            'version' => '2.3.6.0',
            'reference' => '6231e315f73e4f62d72b73f3d6d78ff0eed93c31',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => 'd81a3988cc2c8c32569596247830a717268dcefb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '0a5868e0999e9d47859ba3d918548ff6943e6389',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '6fd1b9a79f6e3cf65f9e679b23af304cd9e010d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(
                0 => '1.26.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '433d05519ce6990bf3530fba6957499d327395c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(
                0 => '1.26.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '59a8d271f00dd0e4c2e518104cc7963f655a1aa8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(
                0 => '1.26.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '219aa369ceff116e673852dce47c3a41794c14bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(
                0 => '1.26.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '9344f9cb97f3b19424af1a21a3b0e75b0a7d8d7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(
                0 => '1.26.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'bf44a9fd41feaac72b074de600314a93e2ae78e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(
                0 => '1.26.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'e440d35fa0286f77fb45b79a03fedbeda9307e85',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(
                0 => '1.26.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'cfa0ae98841b9e461207c13ab093d76b0fa7bace',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(
                0 => '1.26.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '3e01ccd9b2a3a4167ba2b3c53612762300300226',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'reference' => '4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => '9091cb2b47dce39480b6e9c9911b4def8756f886',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'reference' => 'b8f306d7b8ef34fb3db3305be97ba8e088fb4861',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'unicaen/aide' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '99fecbfdc5b9f90a692074d49f58e632712631e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/aide',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/alerte' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => 'c62169489cabb0603b616f824b3fad465b73f9d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/alerte',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/app' => array(
            'pretty_version' => '5.1.3',
            'version' => '5.1.3.0',
            'reference' => 'fb33a4851da9ed5a58e14458c5bc2c866ba61756',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/app',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/authentification' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '888a9129e98a260c442eaf16832b16ed1e40ffb7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/authentification',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/autoform' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'dfd0634c5541fc0638f9313218501f6499c9e160',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/autoform',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/bjy-authorize' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => 'd7097ef757303a3306d61cc375407e1e82f88652',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/bjy-authorize',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/db-import' => array(
            'pretty_version' => 'dev-utilisateur',
            'version' => 'dev-utilisateur',
            'reference' => '2a2972ff29067806694835d664d2ae119f687052',
            'type' => 'module',
            'install_path' => __DIR__ . '/../unicaen/db-import',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/evenement' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '1ad69ef37b18f778b31e153488f3d35b5e591c6f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/evenement',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/indicateur' => array(
            'pretty_version' => '0.0.4',
            'version' => '0.0.4.0',
            'reference' => 'a17e0dadb846659a21069580233916446de50d74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/indicateur',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/ldap' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => 'e3ae05c101143b8439a546533743dc14c75b90cc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/ldap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/livelog' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '84772dbb1b747f65eba834e5ac63f20d24d0009e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/livelog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/mail' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'e5404506861d825194e36d32f10a99581d99e3de',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/mail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/octopus' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'ef173987a255ab97de24d7784cf0064b2c5ca66b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/octopus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/parametre' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '04311ff04b56bda07cb67eeed3d0757f0e50027a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/parametre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/pdf' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '18497c10f122c9483cb5186bd51815391caf3014',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/pdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/preecog' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '529b552e5de8233237e35dc2c7ddb7a5fe52bfea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/privilege' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '987a499ee896f74f6973e3880cd6fd94aacecf99',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/privilege',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/renderer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '2fac10cd89dbd5d36a64411f7e44df9ca9a831c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/renderer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/utilisateur' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '599c17daaf69d1f5fb482e80984355092d04cd7e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/utilisateur',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'unicaen/zfc-user' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => 'dfef6dfba649c0a6cee7e2938f32948fe93576ff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../unicaen/zfc-user',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webimpress/safe-writer' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'reference' => 'f06fc5fb526980819d01549a86b5288d0c94aa50',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webimpress/safe-writer',
            'aliases' => array(
                0 => '2.3.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '11cb2199493b2f8a3b53e7f19068fc6aac760991',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zendframework/zend-cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.9.0',
            ),
        ),
        'zendframework/zend-code' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^3.4.1',
            ),
        ),
        'zendframework/zend-console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.8.0',
            ),
        ),
        'zendframework/zend-form' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.14.3',
            ),
        ),
        'zendframework/zend-hydrator' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^3.0.2',
            ),
        ),
        'zendframework/zend-mvc-console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^1.2.0',
            ),
        ),
        'zendframework/zend-mvc-plugin-fileprg' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^1.1.0',
            ),
        ),
    ),
);
