<?php

use UnicaenNote\Entity\Db\Type;
use UnicaenNote\Provider\Privilege\TypePrivileges;

/**
 * @see TypeController::indexAction()
 * @var Type[] $types
 */

$this->headTitle("Index des types de notes");

$canAfficher = $this->isAllowed(TypePrivileges::getResourceId(TypePrivileges::TYPE_AFFICHER));
$canAjouter = $this->isAllowed(TypePrivileges::getResourceId(TypePrivileges::TYPE_AJOUTER));
$canModifier = $this->isAllowed(TypePrivileges::getResourceId(TypePrivileges::TYPE_MODIFIER));
$canHistoriser = $this->isAllowed(TypePrivileges::getResourceId(TypePrivileges::TYPE_HISTORISER));
$canSupprimer = $this->isAllowed(TypePrivileges::getResourceId(TypePrivileges::TYPE_SUPPRIMER));

?>

<h1 class="page-header">
    Index des types de notes
</h1>

<div class="main">

    <?php if ($canAjouter) : ?>
        <?php /** @see \UnicaenNote\Controller\TypeController::ajouterAction() */?>
        <a href="<?php echo $this->url('unicaen-note/type/ajouter', [], [], true); ?>"
           class="btn btn-primary ajax-modal action" data-event="modification"
       >
            <span class="icon ajouter"></span>
            Ajouter un type de note
        </a>

    <br/><br/>
    <?php endif; ?>

    <table class="datatable table table-condensed">
        <thead>
            <tr>
                <th> Code </th>
                <th> Libelle </th>
                <th> Style </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($types as $type) : ?>
                <tr <?php if ($type->estHistorise()) echo "class='historise'"; ?> >
                    <td> <?php echo $type->getCode(); ?> </td>
                    <td>
                        <?php echo $type->getLibelle(); ?>
                        <?php if ($type->getDescription() !== null) : ?>
                            <span class="icon information" title="<?php echo $type->getDescription(); ?>" data-toggle="tooltip" data-html="true"></span>
                        <?php endif; ?>
                    </td>
                    <td> <?php echo $type->getStyle(); ?> </td>
                    <td>
                        <?php if ($canAfficher): ?>
                            <?php /** @see \UnicaenNote\Controller\TypeController::afficherAction() */?>
                            <a href="<?php echo $this->url('unicaen-note/type/afficher', ['type' => $type->getId()], [], true); ?>"
                               class="ajax-modal"
                               title="Afficher le type <?php echo $type->getCode(); ?>" data-toggle="tooltip" data-html="true"
                            >
                                <span class="icon voir"></span></a>
                        <?php endif; ?>
                        <?php if ($canModifier): ?>
                            <?php /** @see \UnicaenNote\Controller\TypeController::modifierAction() */?>
                            <a href="<?php echo $this->url('unicaen-note/type/modifier', ['type' => $type->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification"
                               title="Modifier le type <?php echo $type->getCode(); ?>" data-toggle="tooltip" data-html="true"
                            >
                                <span class="icon editer"></span></a>
                        <?php endif; ?>
                        <?php if ($canHistoriser): ?>
                            <?php if ($type->estNonHistorise()) : ?>
                                <?php /** @see \UnicaenNote\Controller\TypeController::historiserAction() */?>
                                <a href="<?php echo $this->url('unicaen-note/type/historiser', ['type' => $type->getId()], [], true); ?>"
                                   title="Historiser le type <?php echo $type->getCode(); ?>" data-toggle="tooltip" data-html="true"
                                >
                                    <span class="icon historiser"></span></a>
                            <?php else: ?>
                                <?php /** @see \UnicaenNote\Controller\TypeController::restaurerAction() */?>
                                <a href="<?php echo $this->url('unicaen-note/type/restaurer', ['type' => $type->getId()], [], true); ?>"
                                   title="Restaurer le type <?php echo $type->getCode(); ?>" data-toggle="tooltip" data-html="true"
                                >
                                    <span class="icon restaurer"></span></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canSupprimer): ?>
                            <?php /** @see \UnicaenNote\Controller\TypeController::supprimerAction() */?>
                            <a href="<?php echo $this->url('unicaen-note/type/supprimer', ['type' => $type->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification"
                               title="Supprimer le type <?php echo $type->getCode(); ?>" data-toggle="tooltip" data-html="true"
                            >
                                <span class="icon detruire"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>