<?php
 /**
 * @var Role $role
 * @var User $utilisateur
 */

use Application\Entity\Db\Role;
use Application\Entity\Db\User;

?>
<h1> Ajout du role <?php echo $role->getRoleId(); ?> à <?php echo $utilisateur->getDisplayName();?>  </h1>

<ol>
<?php
    $utilisateurs = $role->getUser();

    foreach ($utilisateurs as $user) {
        /** @var User $user */
        echo "<li>" .  $user->getDisplayName() . "</li>";
    }
?>
</ol>
