<?php

/**
 * @see \Carriere\Controller\CategorieController::afficherMetiersAction();
 * @var Categorie $categorie
 */

use Carriere\Entity\Db\Categorie;
use Metier\Entity\Db\Metier;

$now = new DateTime();

/** @var  Metier[] $metiers */
$metiers = $categorie->getMetiers();
?>

<dl class="dl-horizontal">
    <dt> Categorie </dt>
    <dd>[#<?php echo $categorie->getCode(); ?>] <?php echo $categorie->getLibelle(); ?></dd>
    <dt> #Métiers </dt>
    <dd> <?php echo count($metiers); ?></dd>
</dl>

<table class="table table-condensed">
    <thead>
        <tr>
            <th> Id </th>
            <th> Métier </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($metiers as $metier) : ?>
        <tr <?php if ($metier->estHistorise($now)) echo 'class="historise"'; ?> >
            <td> <?php echo $metier->getId(); ?> </td>
            <td> <?php echo $metier->getLibelle(); ?> </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>