<?php

use Carriere\Provider\Privilege\CorpsPrivileges;
use Carriere\Entity\Db\Categorie;

/**
 * @see \Carriere\Controller\CategorieController::indexAction()
 * @var Categorie[] $categories
 */

$canAfficher    = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_AFFICHER));
$canAjouter     = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_MODIFIER));
$canModifier    = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_MODIFIER));
$canHistoriser  = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_MODIFIER));
$canDetruire    = $this->isAllowed(CorpsPrivileges::getResourceId(CorpsPrivileges::CORPS_MODIFIER));

$canAction = ($canAfficher OR $canAjouter OR $canModifier OR $canHistoriser OR $canDetruire);

$this->headTitle("Liste des catégories");
?>

<h1 class="page-header">
    Liste des catégories
</h1>

<?php if ($canAjouter) : ?>
    <a
            <?php /** @see \Application\Controller\CategorieController::ajouterAction() */ ?>
            href="<?php echo $this->url('categorie/ajouter', [], [], true); ?>"
            class="btn btn-primary action ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter une catégorie
    </a>
<?php endif; ?>

<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th> Code </th>
            <th> Libelle </th>
            <th> #Métier </th>
            <?php if ($canAction) : ?>
                <th class="action"> Action </th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($categories as $categorie) : ?>
        <tr <?php if ($categorie->estHistorise()) echo " class='historise'"; ?>>
            <td>
                <?php echo $categorie->getCode(); ?>
            </td>
            <td>
                <?php echo $categorie->getLibelle(); ?>
            </td>
            <td>
                <?php echo count($categorie->getMetiers()); ?>
            </td>
            <?php if ($canAction) : ?>
                <td class="action">
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Application\Controller\CategorieController::afficherMetiersAction() */ ?>
                            href="<?php echo $this->url('categorie/afficher-metiers', ['categorie' => $categorie->getId()], [], true); ?>"
                            title="Afficher la liste des métiers" data-bs-toggle="tooltip" data-bs-html="true"
                            class="ajax-modal"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br/>
                    <a
                            <?php /** @see \Application\Controller\CategorieController::modifierAction() */ ?>
                            href="<?php echo $this->url('categorie/modifier', ['categorie' => $categorie->getId()], [], true); ?>"
                            title="Modification de la catégorie" data-bs-toggle="tooltip" data-bs-html="true"
                            class="ajax-modal" data-event="modification"
                        >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br/>
                    <?php if ($categorie->estHistorise()) : ?>
                        <a
                            <?php /** @see \Application\Controller\CategorieController::restaurerAction() */ ?>
                                href="<?php echo $this->url('categorie/restaurer', ['categorie' => $categorie->getId()], [], true); ?>"
                                title="Restauration de la catégorie" data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php else: ?>
                        <a
                            <?php /** @see \Application\Controller\CategorieController::historiserAction() */ ?>
                                href="<?php echo $this->url('categorie/historiser', ['categorie' => $categorie->getId()], [], true); ?>"
                                title="Historisation de la catégorie" data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <br/>
                    <a
                        <?php /** @see \Application\Controller\CategorieController::supprimerAction() */ ?>
                            href="<?php echo $this->url('categorie/supprimer', ['categorie' => $categorie->getId()], [], true); ?>"
                            title="Destruction de la catégorie" data-bs-toggle="tooltip" data-bs-html="true"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>