<?php
/**
 * @var Champ $champ
 * @var string $reponse
 */

use Autoform\Entity\Db\Champ;

$options = explode(';', $champ->getOptions());
?>

<div class="row">
<div class="form-group">
    <label for="textarea_<?php echo $champ->getId(); ?>" class="col-sm-2 control-label">
        <?php echo $champ->getLibelle(); ?>&nbsp;:
    </label>
    <div class="col-sm-10">
        <textarea class="form-control autoform-textarea" id="textarea_<?php echo $champ->getId(); ?>" name="<?php echo $champ->getId(); ?>" >
                <?php if (trim($reponse) !== ''): ?>
                    <?php echo $reponse; ?>
                <?php endif; ?>
                </textarea>
        </div>
</div>
</div>

<style>
    textarea {
        margin-bottom : 10px;
    }
</style>

<script>

</script>