<?php

use Observation\Entity\Db\ObservationType;

/** @see \Observation\Controller\ObservationTypeController::afficherAction()
 * @var ObservationType $type
 * */

$this->headTitle("Affichage d'un type observation");

?>

<dl class="row">
    <dt class="col-md-4"> Code </dt>
    <dd class="col-md-8"> <?php echo $type->getCode(); ?> </dd>
    <dt class="col-md-4"> Libellé </dt>
    <dd class="col-md-8"> <?php echo $type->getLibelle(); ?> </dd>
    <dt class="col-md-4"> Catégorie </dt>
    <dd class="col-md-8"> <?php echo $type->getCategorie(); ?> </dd>
</dl>
