<?php

use Observation\Entity\Db\ObservationType;
use Observation\Provider\Privilege\ObservationinstancePrivileges;
use Observation\Provider\Privilege\ObservationtypePrivileges;

/**
 * @see \Observation\Controller\ObservationTypeController::indexAction()
 * @var ObservationType[] $types
 * @var string[] $categories
 * @var array $params
 */

$this->headTitle("Type d'observation");

$canAfficher = $this->isAllowed(ObservationtypePrivileges::getResourceId(ObservationtypePrivileges::OBSERVATIONTYPE_AFFICHER));
$canAjouter = $this->isAllowed(ObservationtypePrivileges::getResourceId(ObservationtypePrivileges::OBSERVATIONTYPE_AJOUTER));
$canModifier = $this->isAllowed(ObservationtypePrivileges::getResourceId(ObservationtypePrivileges::OBSERVATIONTYPE_MODIFIER));
$canHistoriser = $this->isAllowed(ObservationtypePrivileges::getResourceId(ObservationtypePrivileges::OBSERVATIONTYPE_HISTORISER));
$canSupprimer = $this->isAllowed(ObservationtypePrivileges::getResourceId(ObservationtypePrivileges::OBSERVATIONTYPE_SUPPRIMER));


$canIndexInstance = $this->isAllowed(ObservationinstancePrivileges::getResourceId(ObservationinstancePrivileges::OBSERVATIONINSTANCE_INDEX));
?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Types d'observation
        </h1>
    </div>
    <div class="col-md-4">
        <?php if ($canIndexInstance) : ?>
            <a href="<?php echo $this->url('observation/instance', [], [], true); ?>"
               class="btn btn-secondary"
            >
                <span class="icon icon-listing"></span>
                Instances d'observation

            </a>
        <?php endif; ?>
    </div>

<div class='filtes'>
    <?php echo $this->partial('partial/filtre.phtml'); ?>
</div>

<div id="actions-generales">
    <?php if ($canAjouter): ?>
        <?php /** @see \Observation\Controller\ObservationTypeController::ajouterAction() */ ?>
        <a href="<?php echo $this->url('observation/otype/ajouter'); ?>"
           class="btn btn-primary ajax-modal" data-event="modification">
            <span class="icon icon-ajouter"></span>
            Ajouter un type d'observation
        </a>
    <?php endif; ?>
</div>

<table class="table table-condensed datatable">
    <thead>
        <tr>
            <th> Code </th>
            <th> Libellé </th>
            <th> Catégorie </th>
            <th> #Observation </th>
            <th class="action"> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($types as $type) : ?>
        <tr class="<?php if ($type->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $type->getCode(); ?> </td>
            <td> <?php echo $type->getLibelle(); ?> </td>
            <td> <?php echo $type->getCategorie(); ?> </td>
            <td> <?php echo count($type->getObservations()); ?> </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Observation\Controller\ObservationTypeController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('observation/otype/afficher', ['observation-type' => $type->getId()], [], true); ?>"
                       class="ajax-modal">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \Observation\Controller\ObservationTypeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('observation/otype/modifier', ['observation-type' => $type->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-modifier"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($type->estNonHistorise()) : ?>
                        <?php /** @see \Observation\Controller\ObservationTypeController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('observation/otype/historiser', ['observation-type' => $type->getId()], [], true); ?>"
                           >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Observation\Controller\ObservationTypeController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('observation/otype/restaurer', ['observation-type' => $type->getId()], [], true); ?>"
                           >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \Observation\Controller\ObservationTypeController::restaurerAction() */ ?>
                    <a href="<?php echo $this->url('observation/otype/supprimer', ['observation-type' => $type->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
