<?php

/**
 * @see \Application\Controller\MetierController::indexAction()
 * @var FamilleProfessionnelle[] $familles
 * @var Domaine[] $domaines
 * @var Metier[] $metiers
 * @var MetierReferentiel[] $referentiels
 */


use Application\Entity\Db\Domaine;
use Application\Entity\Db\FamilleProfessionnelle;
use Application\Entity\Db\Metier;
use Application\Entity\Db\MetierReferentiel;
use Application\Provider\Privilege\MetierPrivileges;

$this->headTitle('Métiers, familles professionnelles et domaines');

$canAjouter        = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_AJOUTER));
$canEditer         = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_MODIFIER));
$canHistoriser     = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_HISTORISER));
$canEffacer        = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_DETRUIRE));
$canCarto          = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_CARTOGRAPHIE));

?>

<h1 class="page-header">
    Métiers, familles professionnelles et domaines
</h1>

<?php if ($canCarto) : ?>
    <a
            <?php /** @see \Application\Controller\MetierController::cartographieAction() */?>
            href="<?php echo $this->url('metier/cartographie', [], [], true); ?>"
            class="btn btn-primary action"
        >
            Aller vers la cartographie
    </a>
<?php endif; ?>

<br/>
<br/>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">

        <li role="famille">
            <a href="#famille" aria-controls="famille" role="tab" data-toggle="tabz">
                Familles professionnelles &nbsp;
                <span class="badge">
                    <?php echo count($familles); ?>
                </span>
            </a>
        </li>

        <li role="domaine">
            <a href="#domaine" aria-controls="domaine" role="tab" data-toggle="tabz">
                Domaines &nbsp;
                <span class="badge">
                    <?php echo count($domaines); ?>
                </span>
            </a>
        </li>

        <li role="metier">
            <a href="#metier" aria-controls="metier" role="tab" data-toggle="tabz" >
                Métiers &nbsp;
                <span class="badge">
                    <?php echo count($metiers); ?>
                </span>
            </a>
        </li>

        <li role="referentiel">
            <a href="#referentiel" aria-controls="referentiel" role="tab" data-toggle="tabz" >
                Référentiels métiers &nbsp;
                <span class="badge">
                    <?php echo count($referentiels); ?>
                </span>
            </a>
        </li>
    </ul>

    <div class="main-with-tab">

        <div class="tab-content">

            <!-- FAMILLE ---------------------------------------------------------------------------------------------->
            <div id="famille" class="tab-pane " role="tabpanel">

                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Familles professionnelles
                        </h2>
                    </div>
                    <div class="pull-right">
                        <br/>
                        <?php if ($canAjouter) : ?>
                            <a
                                <?php /** @see \Application\Controller\MetierController::ajouterFamilleAction() */?>
                                href="<?php echo $this->url('metier/ajouter-famille', [], [], true);?>"
                                class="btn btn-primary action ajax-modal"
                                data-event="modification"
                            >
                                <span class="icon ajouter"></span>
                                Ajouter une famille professionnelle
                            </a>
                        <?php endif;?>
                    </div>
                    <br/>
                </div>
                <br/>
                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libelle </th>
                        <th> #domaines </th>
                        <th class="cell-action"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($familles as $famille): ?>
                        <tr <?php if ($famille->estHistorise()) echo ' class="historise" '; ?>>
                            <td> <?php echo $famille->getLibelle(); ?> </td>
                            <td>
                                <?php echo count($famille->getDomaines()); ?>
                            </td>
                            <td>
                                <?php if ($canEditer) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MetierController::modifierFamilleAction() */?>
                                        href="<?php echo $this->url('metier/modifier-famille', ['famille' => $famille->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier la famille professionnelle"></span></a>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($famille->estNonHistorise()) : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::historiserFamilleAction() */ ?>
                                                href="<?php echo $this->url('metier/historiser-famille', ['famille' => $famille->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser la famille professionnelle"></span></a>
                                    <?php else : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::restaurerFamilleAction() */ ?>
                                                href="<?php echo $this->url('metier/restaurer-famille', ['famille' => $famille->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer la famille professionnelle"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canEffacer) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MetierController::effacerFamilleAction() */?>
                                        href="<?php echo $this->url('metier/effacer-famille', ['famille' => $famille->getId()], [], true); ?>"
                                        class="ajax-modal" data-event="modification"
                                    >
                                        <span class="icon detruire"  title="Supprimer la famille professionnelle"></span></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <!-- DOMAINE ---------------------------------------------------------------------------------------------->
            <div id="domaine" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Domaines
                        </h2>
                    </div>
                    <div class="pull-right"><br/>
                        <?php if ($canAjouter) : ?>
                            <a
                                <?php /** @see \Application\Controller\MetierController::ajouterDomaineAction() */ ?>
                                href="<?php echo $this->url('metier/ajouter-domaine', [], [], true);?>"
                                class="btn btn-primary action ajax-modal"
                                data-event="modification"
                            >
                                <span class="icon ajouter"></span>
                                Ajouter un domaine
                            </a>
                        <?php endif;?>
                    </div>
                </div>
                <br/>
                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libelle </th>
                        <th> Famille professionnelle </th>
                        <th> #metier </th>
                        <th class="cell-action"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($domaines as $domaine): ?>
                        <tr <?php if ($domaine->estHistorise()) echo ' class="historise" '; ?>>
                            <td> <?php echo $domaine->getLibelle(); ?> </td>
                            <td> <?php echo $domaine->getFamille(); ?> </td>
                            <td>
                                <?php echo count($domaine->getMetiers()); ?>
                            </td>
                            <td>
                                <?php if ($canEditer) : ?>
                                    <a  <?php /** @see \Application\Controller\MetierController::modifierDomaineAction() */ ?>
                                        href="<?php echo $this->url('metier/modifier-domaine', ['domaine' => $domaine->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier le domaine"></span></a>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($domaine->estNonHistorise()) : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::historiserDomaineAction() */ ?>
                                                href="<?php echo $this->url('metier/historiser-domaine', ['domaine' => $domaine->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser le domaine"></span></a>
                                    <?php else : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::restaurerDomaineAction() */ ?>
                                                href="<?php echo $this->url('metier/restaurer-domaine', ['domaine' => $domaine->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer le domaine"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canEffacer) : ?>
                                    <a  <?php /** @see \Application\Controller\MetierController::effacerDomaineAction() */ ?>
                                        href="<?php echo $this->url('metier/effacer-domaine', ['domaine' => $domaine->getId()], [], true); ?>"
                                        class="ajax-modal" data-event="modification"
                                    >
                                        <span class="icon detruire"  title="Supprimer le domaine"></span></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <!-- METIER ----------------------------------------------------------------------------------------------->
            <div id="metier" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Liste des métiers
                        </h2>
                    </div>
                    <div class="pull-right">
                        <br/>
                        <?php if ($canAjouter) : ?>
                            <a  <?php /** @see \Application\Controller\MetierController::ajouterMetierAction() */ ?>
                                href="<?php echo $this->url('metier/ajouter-metier', [], [], true);?>"
                                class="btn btn-primary action ajax-modal"
                                data-event="modification"
                            >
                                <span class="icon ajouter"></span>
                                Ajouter un métier
                            </a>
                        <?php endif;?>
                    </div>
                </div>
                <br/>
                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libelle </th>
                        <th> Domaines </th>
                        <th> Fonction </th>
                        <th> Références </th>
                        <th> Expertise </th>
                        <th class="cell-action"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($metiers as $metier): ?>
                        <tr <?php if ($metier->estHistorise()) echo ' class="historise" '; ?>>
                            <td> <?php echo $metier->getLibelle(); ?> </td>
                            <td>
                                <ul>
                                <?php foreach ($metier->getDomaines() as $domaine) : ?>
                                    <li> <?php echo $domaine; ?> </li>
                                <?php endforeach; ?>
                                </ul>
                            </td>
                            <td> <?php echo $metier->getFonction(); ?> </td>
                            <td>
                                <?php $references =  $metier->getReferences(); ?>
                                <?php if (empty($references)) : ?>
                                    Aucune
                                <?php else: ?>
                                    <?php foreach ($references as $reference) : ?>
                                        <a href="<?php echo $reference->getUrl(); ?>" target="_blank" title="<?php echo $reference->getTitre(); ?>">
                                            <?php echo $reference->getCode(); ?>
                                        </a>
                                        <?php if ($canEditer) : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::modifierReferenceAction() */ ?>
                                            href="<?php echo $this->url('metier/modifier-reference', ['reference' => $reference->getId()], [], true); ?>"
                                            class="ajax-modal" data-event="modification"
                                        >
                                            <span class="icon editer" title="Modifier la référence"></span></a>
                                        <a href="">
                                            <a  <?php /** @see \Application\Controller\MetierController::effacerReferenceAction() */ ?>
                                                    href="<?php echo $this->url('metier/effacer-reference', ['reference' => $reference->getId()], [], true); ?>"
                                                    class="ajax-modal" data-event="modification"
                                            >
                                            <span class="icon detruire" title="Supprimer la référence"></span></a>
                                        <?php endif; ?>
                                        <br/>
                                    <?php endforeach ?>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if ($metier->hasExpertise()) : ?>
                                    <span class="icon ok" style="color:darkgreen;"></span>
                                <?php else: ?>
                                    <span class="icon ko" style="color:darkred;"></span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if ($canEditer) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MetierController::modifierMetierAction() */ ?>
                                        href="<?php echo $this->url('metier/modifier-metier', ['metier' => $metier->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier le métier"></span></a>
                                <?php endif; ?>
                                <?php if ($canEditer) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MetierController::ajouterReferenceAction() */ ?>
                                            href="<?php echo $this->url('metier/ajouter-reference', ['metier' => $metier->getId()], [], true); ?>"
                                            class="ajax-modal"
                                            data-event="modification"
                                    >
                                        <span class="icon ajouter" title="ajouter une référence"></span></a>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($metier->estNonHistorise()) : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::historiserMetierAction() */ ?>
                                                href="<?php echo $this->url('metier/historiser-metier', ['metier' => $metier->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser le métier"></span></a>
                                    <?php else : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::restaurerMetierAction() */ ?>
                                                href="<?php echo $this->url('metier/restaurer-metier', ['metier' => $metier->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer le métier"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canEffacer) : ?>
                                    <a  <?php /** @see \Application\Controller\MetierController::effacerMetierAction() */ ?>
                                        href="<?php echo $this->url('metier/effacer-metier', ['metier' => $metier->getId()], [], true); ?>"
                                        class="ajax-modal" data-event="modification"
                                    >
                                        <span class="icon detruire"  title="Supprimer l'application"></span></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <!-- REFERENTIEL ----------------------------------------------------------------------------------------------->
            <div id="referentiel" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Liste des référentiels metiers
                        </h2>
                    </div>
                    <div class="pull-right">
                        <br/>
                        <?php if ($canAjouter) : ?>
                            <a  <?php /** @see \Application\Controller\MetierController::ajouterReferentielAction() */ ?>
                                    href="<?php echo $this->url('metier/ajouter-referentiel', [], [], true);?>"
                                    class="btn btn-primary action ajax-modal"
                                    data-event="modification"
                            >
                                <span class="icon ajouter"></span>
                                Ajouter un référentiel
                            </a>
                        <?php endif;?>
                    </div>
                </div>
                <br/>
                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libelle court</th>
                        <th> Libelle long </th>
                        <th> Préfix </th>
                        <th class="cell-action"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($referentiels as $referentiel) : ?>
                        <tr <?php if ($referentiel->estHistorise()) echo 'class="historise"'; ?>>
                            <td> <?php echo $referentiel->getLibelleCourt(); ?> </td>
                            <td> <?php echo $referentiel->getLibelleLong(); ?> </td>
                            <td>
                                <?php if ($referentiel->getPrefix()) : ?>
                                    <span class="icon ok" style="color:darkgreen" title="<?php echo $referentiel->getPrefix(); ?>"></span>
                                <?php else: ?>
                                    <span class="icon ko" style="color:darkred"></span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if ($canEditer) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MetierController::modifierReferentielAction() */ ?>
                                            href="<?php echo $this->url('metier/modifier-referentiel', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                            class="ajax-modal"
                                            data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier le référentiel métier"></span></a>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($referentiel->estNonHistorise()) : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::historiserReferentielAction() */ ?>
                                                href="<?php echo $this->url('metier/historiser-referentiel', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser le référentiel métier"></span></a>
                                    <?php else : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::restaurerReferentielAction() */ ?>
                                                href="<?php echo $this->url('metier/restaurer-referentiel', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer le référentiel métier"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canEffacer) : ?>
                                    <a  <?php /** @see \Application\Controller\MetierController::effacerReferentielAction() */ ?>
                                            href="<?php echo $this->url('metier/effacer-referentiel', ['referentiel' => $referentiel->getId()], [], true); ?>"
                                            class="ajax-modal" data-event="modification"
                                    >
                                        <span class="icon detruire"  title="Supprimer le référentiel métier"></span></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>



</div>


<script>
    $(document).ready(function() {
        $('.datatable').DataTable( {
            sorting: false,
            // paging: false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "metier";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
