<?php

/**
 * @see \Application\Controller\MetierController::indexAction()
 * @var FamilleProfessionnelle[] $familles
 * @var Domaine[] $domaines
 * @var Metier[] $metiers
 */


use Application\Entity\Db\Domaine;
use Application\Entity\Db\FamilleProfessionnelle;
use Application\Entity\Db\Metier;
use Application\Provider\Privilege\MetierPrivileges;

$this->headTitle('Métiers, familles professionnelles et domaines');

$canAjouter        = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_AJOUTER));
$canEditer         = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_MODIFIER));
$canHistoriser     = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_HISTORISER));
$canEffacer        = $this->isAllowed(MetierPrivileges::getResourceId(MetierPrivileges::METIER_DETRUIRE));

?>

<h1 class="page-header">
    Métiers, familles professionnelles et domaines
</h1>

<div role="tabpanel">
    <ul class="nav nav-tabs" role="tablist">

        <li role="famille">
            <a href="#famille" aria-controls="famille" role="tab" data-toggle="tabz">
                Familles professionnelles &nbsp;
                <span class="badge">
                    <?php echo count($familles); ?>
                </span>
            </a>
        </li>

        <li role="domaine">
            <a href="#domaine" aria-controls="domaine" role="tab" data-toggle="tabz">
                Domaines &nbsp;
                <span class="badge">
                    <?php echo count($domaines); ?>
                </span>
            </a>
        </li>

        <li role="metier">
            <a href="#metier" aria-controls="metier" role="tab" data-toggle="tabz" >
                Métiers &nbsp;
                <span class="badge">
                    <?php echo count($metiers); ?>
                </span>
            </a>
        </li>
    </ul>

    <div class="main-with-tab">

        <div class="tab-content">

            <!-- FAMILLE ---------------------------------------------------------------------------------------------->
            <div id="famille" class="tab-pane " role="tabpanel">

                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Familles professionnelles
                        </h2>
                    </div>
                    <div class="pull-right">
                        <br/>
                        <?php if ($canAjouter) : ?>
                            <a
                                <?php /** @see \Application\Controller\MetierController::ajouterFamilleAction() */?>
                                href="<?php echo $this->url('metier/ajouter-famille', [], [], true);?>"
                                class="btn btn-primary action ajax-modal"
                                data-event="modification"
                            >
                                <span class="icon ajouter"></span>
                                Ajouter une famille professionnelle
                            </a>
                        <?php endif;?>
                    </div>
                    <br/>
                </div>
                <br/>
                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libelle </th>
                        <th> #domaines </th>
                        <th class="action"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($familles as $famille): ?>
                        <tr <?php if ($famille->estHistorise()) echo ' class="historise" '; ?>>
                            <td> <?php echo $famille->getLibelle(); ?> </td>
                            <td>
                                <?php echo count($famille->getDomaines()); ?>
                            </td>
                            <td>
                                <?php if ($canEditer) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MetierController::modifierFamilleAction() */?>
                                        href="<?php echo $this->url('metier/modifier-famille', ['famille' => $famille->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier la famille professionnelle"></span></a>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($famille->estNonHistorise()) : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::historiserFamilleAction() */ ?>
                                                href="<?php echo $this->url('metier/historiser-famille', ['famille' => $famille->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser la famille professionnelle"></span></a>
                                    <?php else : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::restaurerFamilleAction() */ ?>
                                                href="<?php echo $this->url('metier/restaurer-famille', ['famille' => $famille->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer la famille professionnelle"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canEffacer) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MetierController::effacerFamilleAction() */?>
                                        href="<?php echo $this->url('metier/effacer-famille', ['famille' => $famille->getId()], [], true); ?>"
                                        class="ajax-modal" data-event="modification"
                                    >
                                        <span class="icon detruire"  title="Supprimer la famille professionnelle"></span></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <!-- DOMAINE ---------------------------------------------------------------------------------------------->
            <div id="domaine" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Domaines
                        </h2>
                    </div>
                    <div class="pull-right"><br/>
                        <?php if ($canAjouter) : ?>
                            <a
                                <?php /** @see \Application\Controller\MetierController::ajouterDomaineAction() */ ?>
                                href="<?php echo $this->url('metier/ajouter-domaine', [], [], true);?>"
                                class="btn btn-primary action ajax-modal"
                                data-event="modification"
                            >
                                <span class="icon ajouter"></span>
                                Ajouter un domaine
                            </a>
                        <?php endif;?>
                    </div>
                </div>
                <br/>
                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libelle </th>
                        <th> Famille professionnelle </th>
                        <th> #metier </th>
                        <th class="action"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($domaines as $domaine): ?>
                        <tr <?php if ($domaine->estHistorise()) echo ' class="historise" '; ?>>
                            <td> <?php echo $domaine->getLibelle(); ?> </td>
                            <td> <?php echo $domaine->getFamille(); ?> </td>
                            <td>
                                <?php echo count($domaine->getMetiers()); ?>
                            </td>
                            <td>
                                <?php if ($canEditer) : ?>
                                    <a  <?php /** @see \Application\Controller\MetierController::modifierDomaineAction() */ ?>
                                        href="<?php echo $this->url('metier/modifier-domaine', ['domaine' => $domaine->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier le domaine"></span></a>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($domaine->estNonHistorise()) : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::historiserDomaineAction() */ ?>
                                                href="<?php echo $this->url('metier/historiser-domaine', ['domaine' => $domaine->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser le domaine"></span></a>
                                    <?php else : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::restaurerDomaineAction() */ ?>
                                                href="<?php echo $this->url('metier/restaurer-domaine', ['domaine' => $domaine->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer le domaine"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canEffacer) : ?>
                                    <a  <?php /** @see \Application\Controller\MetierController::effacerDomaineAction() */ ?>
                                        href="<?php echo $this->url('metier/effacer-domaine', ['domaine' => $domaine->getId()], [], true); ?>"
                                        class="ajax-modal" data-event="modification"
                                    >
                                        <span class="icon detruire"  title="Supprimer le domaine"></span></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <!-- METIER ----------------------------------------------------------------------------------------------->
            <div id="metier" class="tab-pane " role="tabpanel">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            Liste des métiers
                        </h2>
                    </div>
                    <div class="pull-right">
                        <br/>
                        <?php if ($canAjouter) : ?>
                            <a  <?php /** @see \Application\Controller\MetierController::ajouterMetierAction() */ ?>
                                href="<?php echo $this->url('metier/ajouter-metier', [], [], true);?>"
                                class="btn btn-primary action ajax-modal"
                                data-event="modification"
                            >
                                <span class="icon ajouter"></span>
                                Ajouter un métier
                            </a>
                        <?php endif;?>
                    </div>
                </div>
                <br/>
                <table class="datatable table table-condensed">
                    <thead>
                    <tr>
                        <th> Libelle </th>
                        <th> Domaine </th>
                        <th> Fonction </th>
                        <th class="action"> Action </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($metiers as $metier): ?>
                        <tr <?php if ($metier->estHistorise()) echo ' class="historise" '; ?>>
                            <td> <?php echo $metier->getLibelle(); ?> </td>
                            <td> <?php echo $metier->getDomaine(); ?> </td>
                            <td> <?php echo $metier->getFonction(); ?> </td>
                            <td>
                                <?php if ($canEditer) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MetierController::modifierMetierAction() */ ?>
                                        href="<?php echo $this->url('metier/modifier-metier', ['metier' => $metier->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                    >
                                        <span class="icon editer" title="Modifier le métier"></span></a>
                                <?php endif; ?>
                                <?php if ($canHistoriser) : ?>
                                    <?php if ($metier->estNonHistorise()) : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::historiserMetierAction() */ ?>
                                                href="<?php echo $this->url('metier/historiser-metier', ['metier' => $metier->getId()], [], true); ?>"
                                        >
                                            <span class="icon historiser" title="Historiser le métier"></span></a>
                                    <?php else : ?>
                                        <a  <?php /** @see \Application\Controller\MetierController::restaurerMetierAction() */ ?>
                                                href="<?php echo $this->url('metier/restaurer-metier', ['metier' => $metier->getId()], [], true); ?>"
                                        >
                                            <span class="icon restaurer" title="Restaurer le métier"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($canEffacer) : ?>
                                    <a  <?php /** @see \Application\Controller\MetierController::effacerMetierAction() */ ?>
                                        href="<?php echo $this->url('metier/effacer-metier', ['metier' => $metier->getId()], [], true); ?>"
                                        class="ajax-modal" data-event="modification"
                                    >
                                        <span class="icon detruire"  title="Supprimer l'application"></span></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

        </div>
    </div>



</div>


<script>
    $(document).ready(function() {
        $('.datatable').DataTable( {
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "metier";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-tabs a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });

        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
