<?php

/**
 * @see \Application\Controller\AgentHierarchieController::autoriteAction()
 * @var AgentSuperieur[] $chaines
 */

use Agent\Entity\Db\AgentSuperieur;
use Agent\Provider\Privilege\ChainePrivileges;

$this->headTitle("Gestion des chaînes hiérarchiques - autorités");

$canAfficherChaine = $this->isAllowed(ChainePrivileges::getResourceId(ChainePrivileges::CHAINE_AFFICHER));
?>

<h1 class="page-header">
    Chaînes hiérarchiques
</h1>

<?php echo $this->partial('partial/onglet', ['current' => 'autorite']); ?>

<h2>
    Liste des autorités hiérarchiques
</h2>


<?php if (empty($chaines)) : ?>
    <span class="missing-data">Aucun·e supérieur·e hiérarchique direct·e</span>
<?php else : ?>
    <table class="table table-condensed" id="chaines">
        <thead>
        <tr>
            <th class="col-md-8"> Supérieur·e</th>
            <th class="col-md-2"> Responsabilités</th>
            <th class="col-md-2 action">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($chaines as $superieur) : ?>
            <?php
            /** @var Agent $agent */
            $agent = $superieur['agent'];
            $nb = count($superieur['chaines']);
            ?>
            <tr>
                <td> <?php echo $agent->getDenomination(); ?> </td>
                <td> <?php echo $nb; ?> </td>
                <td class="action">
                    <?php if ($canAfficherChaine) : ?>
                        <?php /** @see \Application\Controller\AgentHierarchieController::afficherChaineAction() */ ?>
                        <a href="<?php echo $this->url('agent/hierarchie/afficher-chaine', ['type' => "AUTORITE", 'agent' => $agent->getId()], [], true); ?>"
                           class='action secondary ajax-modal'
                        >
                            <span class="icon icon-voir"></span>
                            Afficher
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>


<script>
    $(function() {
        $('#chaines').DataTable({
            autoWidth : false,
            language: {
                "url": "/js/datatables_fr.json",
            }
        });
    });
</script>