<?php

/**
 * @see \Application\Controller\FichePosteController::afficherAction()
 * @var FichePoste $fiche
 * @var Competence[] $competences
 * @var Application[] $applications
 * @var AgentPoste[] $postes
 * @var Parametre[] $parametres
 */

use Application\Entity\Db\AgentPoste;
use Element\Entity\Db\Application;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\FicheTypeExterne;
use Application\Provider\Privilege\FichePostePrivileges;
use Element\Entity\Db\Competence;
use Structure\Entity\Db\Structure;
use UnicaenParametre\Entity\Db\Parametre;

$date = new DateTime();
$this->headTitle("Fiche de poste #" . $fiche->getId());

$canAfficher = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_AFFICHER);
$canExport   = $canAfficher;

?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">

        <!--    Fiche de poste #--><?php //echo $fiche->getId(); ?><!-- <br/>-->
            <?php echo $this->partial('partial/intitule', ['ficheposte' => $fiche], [], true); ?>
        </h1>
    </div>

    <div class="pull-right">
        <br/>
        <br/>
        <?php if ($canExport) : ?>
            <a href="<?php echo $this->url('fiche-poste/exporter', ['fiche-poste' => $fiche->getId()], [], true); ?>"
               class="btn btn-primary action" target="_blank"
            ><span
                        data-bs-toggle="tooltip" data-bs-html="true"
                        title="Exporter en PDF la fiche de poste"
                        class="icon icon-pdf"></span> Exporter au format PDF </a>
        <?php endif; ?>
    </div>
</div>

<?php echo $this->partial("partial/validations.phtml"); ?>


<?php if (! $canAfficher) : ?>

    <div class="alert alert-danger col-md-8">
        <p class="lead">
            <span class="icon icon-attention"></span>
            Vous n'êtes pas habilité&middot;e à visualiser cette fiche de poste.
        </p>
    </div>

<?php else : ?>

    <div class="card panel-info">
        <div class="card-header">
            <h2> Agent occupant le poste </h2>
        </div>

        <div class="card-body">

            <?php $agent = $fiche->getAgent(); ?>

            <?php if($agent === null) : ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucun agent d'associé à ce poste
                </div>
            <?php else : ?>
                <?php
                    $retour = $this->url('fiche-poste/afficher', ['fiche-poste' => $fiche->getId()], [], true);
                    echo $this->agent($agent, 'affichage', ["retour" => $retour]);
                ?>
            <?php endif; ?>
        </div>
    </div>

    <?php echo $this->partial('partial/environnement-poste', ['fiche' => $fiche, 'agent' => $agent, 'mode' => 'affichage']); ?>
    <?php echo $this->partial('partial/informations-poste', ['postes' => $postes, 'mode' => 'affichage', 'parametres' => $parametres, 'fiche' => $fiche ]); ?>

    <!-- FICHES TYPES ----------------------------------------------------------------------------------------------------->

    <?php
        $principal = $fiche->getFicheTypeExternePrincipale();

        $fichesMetiers = $fiche->getFichesMetiers();
        $fichesMetiers = array_filter($fichesMetiers, function (FicheTypeExterne $a) { return !$a->getPrincipale(); });
        usort($fichesMetiers, function (FicheTypeExterne $a, FicheTypeExterne $b) { return ($a->getQuotite() > $b->getQuotite()); });
    ?>

    <?php /** @var FicheTypeExterne $ficheType **/ ?>
    <div class="card panel-default">
        <div class="card-header">
            <div class="row">
                <h2>Fiche composée de <?php echo count($fiche->getFichesMetiers()); ?> fiche(s) type(s).</h2>
                <ul>
                    <?php if ($principal) : ?>
                            <li> <strong> <?php echo $principal->getFicheType()->getMetier()->getLibelleGenre($agent) ?> à <?php echo $principal->getQuotite(); ?>%</strong></li>
                    <?php endif; ?>

                    <?php foreach ($fichesMetiers as $ficheType) : ?>
                        <li> <?php echo $ficheType->getFicheType()->getMetier()->getLibelleGenre($agent); ?> à <?php echo $ficheType->getQuotite(); ?>% </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>

    <?php if ($principal) echo $this->ficheMetierExterne($principal, ['mode' => 'affichage']);  ?>
    <?php foreach ($fichesMetiers as $ficheType) : ?>
        <?php echo $this->ficheMetierExterne($ficheType, ['mode' => 'affichage']);  ?>
    <?php endforeach; ?>

    <!-- REGROUPE DES COMPETENCES, APPLICATIONS ET DES FORMATIONS ----------------------------------------------------->
    <div class="card panel-info">
        <div class="card-header">
            <h2>Compétences et applications attendues</h2>
        </div>
        <div class="card-body">
            <?php echo $this->partial('partial/competences',  ['fiche' => $fiche, 'competences' => $competences,   'mode' => 'affichage'], [], true); ?>
            <?php echo $this->partial('partial/applications', ['fiche' => $fiche, 'applications' => $applications, 'mode' => 'affichage'], [], true); ?>
<!--            --><?php //echo $this->partial('partial/formations',   ['fiche' => $fiche, 'formations' => $formations,     'mode' => 'affichage'], [], true); ?>
        </div>
    </div>

    <!-- GRAPH -------------------------------------------------------------------------------------------------------->

<!--    <div class="row">-->
<!--        <div class="col-md-6">-->
<!--            --><?php //echo $this->fichePosteGraph($fiche,
//                ["applications" => $applications, "competences" => $competences, "formations" => $formations, "activites" => $activites],
//                'radar', $date); ?>
<!--        </div>-->
<!--        <div class="col-md-6">-->
<!--            --><?php //echo $this->fichePosteGraph($fiche,
//                ["applications" => $applications, "competences" => $competences, "formations" => $formations, "activites" => $activites],
//                'bar', $date); ?>
<!--        </div>-->
<!--    </div>-->

    <!-- EXPERTISES LIEES A LA FICHE DE POSTE ------------------------------------------------------------------------->
    <?php echo $this->partial('partial/expertise', ['fiche' => $fiche, 'mode' => 'affichage'], [], true); ?>

    <!-- RIFSEEP et NBI ----------------------------------------------------------------------------------------------->
    <?php echo $this->partial('partial/rifseep', ['fiche' => $fiche, 'mode' => 'affichage'], [], true); ?>

    <!-- SPECIFICITE DU POSTE ----------------------------------------------------------------------------------------->
    <?php echo $this->partial('partial/specificite', ['fiche' => $fiche, 'mode' => 'affichage'], [], true); ?>


<?php endif; ?>
