<?php

/**
 * @var FichePoste $fiche
 * @var Structure $structure
 */

use Application\Entity\Db\FichePoste;
use Application\Entity\Db\FicheTypeExterne;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\FichePostePrivileges;

$canAssocierAgent = true;
$canAssocierMetierType = true;

$canEditerSpecificte = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::EDITER));
$canEditer = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::EDITER));
?>

<style>
    a.action {width: 18em;}
</style>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Fiche métier <br/>
            <strong> <?php echo $fiche->getLibelle(); ?> </strong>
        </h1>
    </div>
    <div class="pull-right">
        <br/>
        <br/>
        <br/>
        <br/>
        <a href=""
           class="btn btn-primary action"
           data-event="modification"
        >
            <span class="icon editer"></span>
            Modifier le titre
        </a>
    </div>
</div>


<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2> Agent occupant le poste </h2>
            </div>
            <div class="col-md-6">
                <?php if($canAssocierAgent) : ?>
                    <a href="<?php echo $this->url('fiche-poste/associer-agent',['fiche-poste' => $fiche->getId()], ["query" => ["structure" => ($structure)?$structure->getId():null]], true); ?>"
                       class="btn btn-primary action ajax-modal pull-right"
                       data-event="modification"
                    >
                        <span class="icon selectionner"></span>
                        Associer un agent
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="panel-body">


        <?php $agent = $fiche->getAgent(); ?>

        <?php if($agent === null) : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucun agent d'associé à ce poste
            </div>
        <?php else : ?>
            <?php echo $this->agent($agent); ?>
        <?php endif; ?>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2> Environnement du poste de travail </h2>
            </div>
            <div class="col-md-6">
                <?php if($canAssocierAgent) : ?>
                    <a href="<?php echo $this->url('fiche-poste/associer-poste',['fiche-poste' => $fiche->getId()], ["query" => ["structure" => ($structure)?$structure->getId():null]], true); ?>"
                       class="btn btn-primary action ajax-modal pull-right"
                       data-event="modification"
                    >
                        <span class="icon selectionner"></span>
                        Associer un poste
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
            <h3> Affectation du poste </h3>
            <?php if ($fiche->getPoste() !== null && $fiche->getPoste()->getStructure() !== null) : ?>
                <?php if ($fiche->getPoste()->getStructure()->getDescription() !== null) :?>
                    <?php echo $fiche->getPoste()->getStructure()->getDescription(); ?>
                <?php else: ?>
                    <div class="alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i>
                        Aucune description de fournie pour l'affectation <em><?php echo $fiche->getPoste()->getStructure()->getLibelleCourt(); ?></em>.
                    </div>
                <?php endif; ?>
            <?php else : ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucune affectation de renseignée.
                </div>
            <?php endif; ?>

            <h3> Positionnement dans l'établissement</h3>
            <?php if ($fiche->getPoste() === null) : ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucun poste n'est attaché à ce poste
                </div>
            <?php else: ?>
                <?php echo $this->poste($fiche->getPoste()); ?>
            <?php endif; ?>
    </div>
</div>

<!-- FICHES TYPES ----------------------------------------------------------------------------------------------------->

<?php
$principal = $fiche->getFicheTypeExternePrincipale();

$fichesMetiers = $fiche->getFichesMetiers();
$fichesMetiers = array_filter($fichesMetiers, function (FicheTypeExterne $a) { return !$a->getPrincipale(); });
usort($fichesMetiers, function (FicheTypeExterne $a, FicheTypeExterne $b) { return ($a->getQuotite() > $b->getQuotite()); });
?>


<?php /** @var \Application\Entity\Db\FicheTypeExterne $ficheType **/ ?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
            <h2>Fiche composée de <?php echo count($fiche->getFichesMetiers()); ?> fiche(s) type(s).</h2>
            <ul>
                <?php if ($principal) : ?>
                    <li> <strong> <?php echo $principal->getFicheType()->getMetier() ?> à <?php echo $principal->getQuotite(); ?>%</strong></li>
                <?php endif; ?>
                <?php foreach ($fichesMetiers as $ficheType) : ?>
                    <li> <?php echo $ficheType->getFicheType()->getMetier(); ?> à <?php echo $ficheType->getQuotite(); ?>% </li>
                <?php endforeach; ?>
            </ul>
            </div>
            <div class="col-md-4">
                <a href="<?php echo $this->url('fiche-poste/ajouter-fiche-metier', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                   class="btn btn-primary action ajax-modal pull-right"
                   data-event="modification"
                >
                    <span class="icon ajouter"></span>
                    Ajouter une fiche type
                    </a>
            </div>
        </div>
    </div>
</div>

<?php if ($principal) echo $this->ficheMetierExterne($principal, true);  ?>
<?php foreach ($fichesMetiers as $ficheType) : ?>
    <?php echo $this->ficheMetierExterne($ficheType, true);  ?>
<?php endforeach; ?>

<!-- SPECIFICITE DU POSTE --------------------------------------------------------------------------------------------->
<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h2> Spécificité du poste </h2>
            </div>
            <div class="col-md-6">
                <?php if($canEditerSpecificte) : ?>
                    <a href="<?php echo $this->url('fiche-poste/editer-specificite',['fiche-poste' => $fiche->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal pull-right"
                       data-event="modification"
                    >
                        <span class="icon editer"></span>
                        Renseigner les spécificités
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <?php if ($fiche->getSpecificite() === null) : ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                Aucune spécificité attachée à ce poste.
            </div>
        <?php else: ?>
            <?php echo $this->specificitePoste($fiche->getSpecificite()); ?>
        <?php endif; ?>
    </div>
</div>



<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>