<?php

/**
 * @var FichePoste $fiche
 * @var Structure $structure
 * @var boolean $sousstructure
 */

$sousstructure = true;

use Application\Entity\Db\FichePoste;
use Application\Entity\Db\FicheTypeExterne;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\FichePostePrivileges;


$canAssocierMetierType = true;

$canEditerSpecificte = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));
$canEditer = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));
$canEditerExpertise = true || $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));

$mode = 'edition';
$date = new DateTime();

$canModifier = $this->isAllowed($fiche, FichePostePrivileges::FICHEPOSTE_MODIFIER);

$this->headTitle("Modification de la fiche de poste #".$fiche->getId());
?>

<h1 class="page-header">
    Modification de la fiche de poste #<?php echo $fiche->getId(); ?>
</h1>

<?php if (! $canModifier ) : ?>

    <div class="alert alert-danger col-md-8">
        <p class="lead">
            <span class="icon attention"></span>
            Vous n'êtes pas habilité&middot;e à modifier cette fiche de poste.
        </p>
    </div>


<?php else : ?>

    <style>
        a.action {width: 18em;}
    </style>

    <div class="row">
        <div class="col-md-8">
            <h1 class="page-header">
                Fiche de poste #<?php echo $fiche->getId(); ?><br/>
                <strong>
                    <?php echo ($fiche->getFicheTypeExternePrincipale())?$fiche->getFicheTypeExternePrincipale()->getFicheType()->getMetier()->getLibelle():"<span class='icon attention' style='color:darkred;'></span> Aucun fiche principale"; ?>
                    <?php if($fiche->getLibelle() !== null) : ?>
                        (<?php echo $fiche->getLibelle(); ?>)
                    <?php endif; ?>
                </strong>
            </h1>
        </div>
        <div class="pull-right">
            <br/>
            <br/>
            <br/>
            <br/>
            <a
                <?php /** @see \Application\Controller\FichePosteController::associerTitreAction() */ ?>
                href="<?php echo $this->url('fiche-poste/associer-titre', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification"
            >
                <span class="icon editer"></span>
                Modifier le titre
            </a>
        </div>
    </div>


    <?php echo $this->partial("partial/retour-structure.phtml"); ?>

    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-6">
                    <h2> Agent occupant le poste </h2>
                </div>
                <div class="col-md-6">
                    <?php if($canAssocierAgent) : ?>
                        <?php /** @see \Application\Controller\FichePosteController::associerAgentAction() */ ?>
                        <a href="<?php echo $this->url('fiche-poste/associer-agent',['fiche-poste' => $fiche->getId()], ["query" => ["structure" => ($structure)?$structure->getId():null, "sous-structure" => $sousstructure]], true); ?>"
                           class="btn btn-primary action ajax-modal pull-right"
                           data-event="modification"
                        >
                            <span class="icon selectionner"></span>
                            Associer un agent
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="panel-body">


            <?php $agent = $fiche->getAgent(); ?>

            <?php if($agent === null) : ?>
                <div class="alert alert-warning">
                    <i class="fas fa-exclamation-triangle"></i>
                    Aucun agent d'associé à ce poste
                </div>
            <?php else : ?>
                <?php
                    $retour = $this->url('fiche-poste/editer', ['fiche-poste' => $fiche->getId()], [], true);
                    echo $this->agent($agent, 'edition', ["retour" => $retour]);
                ?>
            <?php endif; ?>
        </div>
    </div>

    <?php echo $this->partial('partial/environnement-poste', ['fiche' => $fiche, 'mode' => 'edition']); ?>

    <!-- FICHES TYPES ----------------------------------------------------------------------------------------------------->

    <?php
    $principal = $fiche->getFicheTypeExternePrincipale();

    $fichesMetiers = $fiche->getFichesMetiers();
    $fichesMetiers = array_filter($fichesMetiers, function (FicheTypeExterne $a) { return !$a->getPrincipale(); });
    usort($fichesMetiers, function (FicheTypeExterne $a, FicheTypeExterne $b) { return ($a->getQuotite() > $b->getQuotite()); });
    ?>


    <?php /** @var FicheTypeExterne $ficheType **/ ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-8">
                <h2>Fiche de poste composée de <?php echo count($fiche->getFichesMetiers()); ?> fiche(s) métier(s).</h2>
                <ul>
                    <?php if ($principal) : ?>
                        <li> <strong> <?php echo $principal->getFicheType()->getMetier() ?> à <?php echo $principal->getQuotite(); ?>%</strong></li>
                    <?php endif; ?>
                    <?php foreach ($fichesMetiers as $ficheType) : ?>
                        <li> <?php echo $ficheType->getFicheType()->getMetier(); ?> à <?php echo $ficheType->getQuotite(); ?>% </li>
                    <?php endforeach; ?>
                </ul>
                </div>
                <div class="col-md-4">
                    <?php /**  @see \Application\Controller\FichePosteController::ajouterFicheMetierAction() */ ?>
                    <a href="<?php echo $this->url('fiche-poste/ajouter-fiche-metier', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                       class="btn btn-primary action ajax-modal pull-right"
                       data-event="modification"
                    >
                        <span class="icon ajouter"></span>
                        Ajouter une fiche métier
                        </a>
                </div>
            </div>
        </div>
    </div>

    <?php if ($principal) echo $this->ficheMetierExterne($principal, ['mode' => 'edition-fiche-poste']);  ?>
    <?php foreach ($fichesMetiers as $ficheType) : ?>
        <?php echo $this->ficheMetierExterne($ficheType, ['mode' => 'edition-fiche-poste']);  ?>
    <?php endforeach; ?>

    <!-- GRAPH ------------------------------------------------------------------------------------------------------------>

    <div class="row">
        <div class="col-md-6">
            <?php echo $this->fichePosteGraph($fiche, 'radar', $date); ?>
        </div>
        <div class="col-md-6">
            <?php echo $this->fichePosteGraph($fiche, 'bar', $date); ?>
        </div>
    </div>

    <!-- EXPERTISES LIEES A LA FICHE DE POSTE ----------------------------------------------------------------------------->
    <?php echo $this->partial('partial/expertise', ['fiche' => $fiche, 'mode' => 'edition'], [], true); ?>

    <!-- SPECIFICITE DU POSTE --------------------------------------------------------------------------------------------->
    <?php echo $this->partial('partial/specificite', ['fiche' => $fiche, 'mode' => 'edition'], [], true); ?>

<?php endif; ?>

<?php echo $this->partial("partial/retour-structure.phtml"); ?>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>