<?php

use Application\Controller\FichePosteController;
use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FichePostePrivileges;

/**
 * @see FichePosteController::indexAction()
 * @var FichePoste[] $fiches
 * @var FichePoste[] $fichesIncompletes
 * @var FichePoste[] $fichesVides
 * @var FichePoste[] $fichesCompletes
 */

$this->headTitle('Index des fiches de postes');

$canVoir        = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER));
$canHistoriser  = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_HISTORISER));
$canEditer      = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));
$canDetruire    = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_DETRUIRE));

?>

<h1 class="page-header">
    Fiches de poste
    <span class="badge">
        <?php echo count($fiches); ?>
    </span>
</h1>


<h2>
    Fiches complètes
    <span class="badge">
        <?php echo count($fichesCompletes); ?>
    </span>
</h2>

<?php echo $this->fichesPostesAsArray($fichesCompletes); ?>

<h2>
    Fiches incomplètes
    <span class="badge">
        <?php echo count($fichesIncompletes); ?>
    </span>
</h2>

<?php echo $this->fichesPostesAsArray($fichesIncompletes); ?>

<h2>
    Fiches vides
    <span class="badge">
        <?php echo count($fichesVides); ?>
    </span>
</h2>

<?php echo $this->fichesPostesAsArray($fichesVides); ?>


<?php $ficheId=791; ?>
<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" onclick="setActions(<?php echo $ficheId; ?>)">
        <span class="icon actions" title="Actions possible pour la fiche de poste #<?php echo $ficheId; ?>"></span>
    </button>
    <ul id="drop_791" class="dropdown-menu" aria-labelledby="dropdownMenu1">
    </ul>
</div>


<script>
    function setActions(ficheId) {
        let url = 'fiche-poste/action/' + ficheId;
        // console.log(url);
        $.ajax({
            type: "POST",
            url: url,
            success:
                function (retour) {
                    // console.log(retour);
                    $("ul#drop_"+ficheId).html(retour);
                }
        });
        // alert(ficheId);
    }

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function() {
        $("body").on("edition", function (event) {
            event.div.modal('hide');
            window.location.href = 'fiche-poste/editer';
        });
    });

    $(document).ready(function() {
        $('.datatable').DataTable( {
            language: {
                url: '/localisation/fr_FR.json'
            }
        });
    });
</script>
