<?php

use Application\Controller\FichePosteController;
use Application\Entity\Db\FichePoste;
use Application\Provider\Privilege\FichePostePrivileges;

/**
 * @see FichePosteController::indexAction()
 * @var FichePoste[] $fiches
 */

$this->headTitle('Index des fiches de postes');

$canVoir        = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER));
$canHistoriser  = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_HISTORISER));
$canEditer      = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));
$canDetruire    = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_DETRUIRE));

?>

<h1 class="page-header">
    Fiches de poste
    <span class="badge">
        <?php echo count($fiches); ?>
    </span>
</h1>


<?php echo $this->fichesPostesAsArray($fiches, null, ['id' => 'fichescompletes']); ?>


<script>
    function setActions(ficheId) {
        let url = 'fiche-poste/action/' + ficheId;
        // console.log(url);
        $.ajax({
            type: "POST",
            url: url,
            success:
                function (retour) {
                    // console.log(retour);
                    $("ul#drop_"+ficheId).html(retour);
                }
        });
        // alert(ficheId);
    }

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

    $(function() {
        $("body").on("edition", function (event) {
            event.div.modal('hide');
            window.location.href = 'fiche-poste/editer';
        });
    });
</script>
