<?php

/**
 * @var \Application\Entity\Db\FichePoste $fichePoste
 * @var \Application\Entity\Db\FicheTypeExterne $ficheTypeExterne
 */

$idActivites = explode(";",$ficheTypeExterne->getActivites());
?>

<span id="tous_cocher" class="faux-bouton action">   Tous cocher</span>
<span id="tous_decocher" class="faux-bouton action"> Tous décocher</span>

<form method="post" action="<?php echo $this->url('fiche-poste/selectionner-activite', ['fiche-poste' => $fichePoste->getId(), 'fiche-type-externe' => $ficheTypeExterne->getId()], [], true); ?>">

    <?php $missions = $ficheTypeExterne->getFicheType()->getMissions() ; ?>
    <?php foreach ($missions as $mission) : ?>
        <div class="form-group">
            <div class="checkbox">
                <label>
                    <input type="checkbox"
                           id="<?php echo $mission->getMission()->getId(); ?>"
                           name="<?php echo $mission->getMission()->getId(); ?>"
                           <?php if (array_search($mission->getMission()->getId(), $idActivites) !== false) echo " checked "; ?>
                    >
                    <?php echo $mission->getMission()->getLibelle(); ?>
                </label>
            </div>
    <?php endforeach; ?>

    <input type="submit" class="btn btn-primary" value="Valider la sélection">
</form>

<script>
    $( "#tous_cocher" ).click(function() {
        $("input[type=checkbox]").prop('checked', true);
    });

    $( "#tous_decocher" ).click(function() {
        $("input[type=checkbox]").prop('checked', false);
    });
</script>

<style>
    span.faux-bouton {
        background-color: rgb(51, 122, 183);
        background-image: none;
        border-radius: 4px;
        border-color: rgb(46, 109, 164);
        border-style: solid;
        border-width: 1px;
        box-sizing: border-box;
        color: rgb(255, 255, 255);
        cursor: pointer;
        font-family: ubuntu, arial, sans-serif;
        font-size: 14px;
        font-weight: 400;
        line-height: 20px;
        margin: 1px;
        padding: 6px;
        text-align: center;
        vertical-align: middle;
        width:20em;

    }
    span.faux-bouton:hover{
        background-color: #275a8b;
    }
</style>