<?php

/**
 * @see \Application\Controller\FichePosteController::selectionnerFormationsRetireesAction()
 *
 * @var FichePoste $ficheposte
 * @var array $formations
 */

use Application\Entity\Db\FichePoste;

?>


<form
        action="<?php echo $this->url('fiche-poste/selectionner-formations-retirees', ['fiche-poste' => $ficheposte->getId()], [], true); ?>"
        method="post"
>

    <?php foreach ($formations as $item) : ?>
        <div class="checkbox">
            <label>
                <input
                        type="checkbox"
                        id="<?php echo $item['object']->getId(); ?>"
                        name="<?php echo $item['object']->getId(); ?>"
                    <?php if ($item['conserve']) echo "checked"; ?>
                />
                <?php echo $item['object']->getLibelle(); ?>
            </label>
        </div>
    <?php endforeach; ?>

    <input type="submit" class="btn btn-primary action" value="Enregistrer"/>
</form>