<?php

use Formation\Entity\Db\Domaine;
use Formation\Provider\Privilege\FormationdomainePrivileges;

/**
 * @see \Formation\Controller\DomaineController::indexAction()
 * @var Domaine[] $domaines
 * // * @var string $historise
 * // * @var string $source
 */

$canAfficher = $this->isAllowed(FormationdomainePrivileges::getResourceId(FormationdomainePrivileges::FORMATIONDOMAINE_AFFICHER));
$canAjouter = $this->isAllowed(FormationdomainePrivileges::getResourceId(FormationdomainePrivileges::FORMATIONDOMAINE_AJOUTER));
$canEditer = $this->isAllowed(FormationdomainePrivileges::getResourceId(FormationdomainePrivileges::FORMATIONDOMAINE_MODIFIER));
$canHistoriser = $this->isAllowed(FormationdomainePrivileges::getResourceId(FormationdomainePrivileges::FORMATIONDOMAINE_HISTORISER));
$canDetruire = $this->isAllowed(FormationdomainePrivileges::getResourceId(FormationdomainePrivileges::FORMATIONDOMAINE_SUPPRIMER));

$this->headTitle("Domaines de formation");
?>

<h1 class="page-header">
    Domaines de formation
</h1>

<?php if ($canAjouter) : ?>
    <br/>
    <a
        <?php /** @see \Formation\Controller\DomaineController::ajouterAction() */ ?>
            href="<?php echo $this->url('formation-domaine/ajouter', [], [], true); ?>"
            class="btn btn-primary ajax-modal"
            data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un domaine
    </a>
<?php endif; ?>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<table class="datatable table table-condensed table-hover" id="domaines">
    <thead>
    <tr>
        <th> Libellé</th>
        <th> Ordre</th>
        <th style="width: 10rem;"> #Formation</th>
        <th class="action"> Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($domaines as $domaine) : ?>
        <tr id="<?php echo $domaine->getId(); ?>" class="<?php if ($domaine->estHistorise()) echo "historise"; ?>">

            <td> <!-- LIBELLE -->
                <span class="badge" style="background: <?php echo $domaine->getCouleur(); ?>">&nbsp;</span>
                <?php echo $domaine->getLibelle(); ?>
                <?php if ($domaine->getDescription() !== null) : ?>
                    <span class="icon icon-info" title="<?php echo $domaine->getDescription(); ?>"
                          data-bs-toggle="tooltip" data-bs-html="true">
                    </span>
                <?php endif; ?>
            </td>
            <td> <!-- ORDRE -->
                <?php echo $domaine->getOrdre(); ?>
            </td>
            <td> <!-- NB THEME -->
                <?php echo count($domaine->getFormations()); ?>
            </td>
            <!-- SOURCE -->
<!--            <td> -->
<!--                <span class="badge source --><?php //echo $domaine->getSource(); ?><!--" id="--><?php //echo $domaine->getSource(); ?><!--">-->
<!--                    --><?php //echo $domaine->getSource(); ?>
<!--                    --><?php //echo $domaine->getIdSource(); ?>
<!--                </span>-->
<!--            </td>-->
            <td class="action"> <!-- ACTION -->
                <?php if ($canAfficher) : ?>
                    <a <?php /** @see \Formation\Controller\DomaineController::afficherAction() */ ?>
                            href="<?php echo $this->url('formation-domaine/afficher', ['domaine' => $domaine->getId()], [], true); ?>"
                    >
<!--                            class="ajax-modal"-->
                        <span class="icon icon-voir" title="Afficher le domaine"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <br>
                    <a
                        <?php /** @see \Formation\Controller\DomaineController::modifierAction() */ ?>
                            href="<?php echo $this->url('formation-domaine/modifier', ['domaine' => $domaine->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon icon-editer" title="Modifier le domaine"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($domaine->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \Formation\Controller\DomaineController::historiserAction() */ ?>
                                href="<?php echo $this->url('formation-domaine/historiser', ['domaine' => $domaine->getId()], [], true); ?>"
                        >
                            <span class="icon icon-historiser" title="Historiser le domaine"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <a
                            <?php /** @see \Formation\Controller\DomaineController::restaurerAction() */ ?>
                                href="<?php echo $this->url('formation-domaine/restaurer', ['domaine' => $domaine->getId()], [], true); ?>"
                        >
                            <span class="icon icon-restaurer" title="Restaurer le domaine"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire and $domaine->estHistorise()) : ?>
                    <br>
                    <a
                        <?php /** @see \Formation\Controller\DomaineController::supprimerAction() */ ?>
                            href="<?php echo $this->url('formation-domaine/supprimer', ['domaine' => $domaine->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked text-danger" title="Supprimer définitivement le domaine"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
