<?php

use Application\Entity\Db\FichePoste;
use Application\Entity\Db\FicheposteActiviteDescriptionRetiree;
use Element\Entity\Db\ApplicationElement;
use Element\Entity\Db\CompetenceElement;
use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Entity\Db\FicheMetierMission;
use FicheMetier\Entity\Db\Mission;
use FicheMetier\Entity\Db\MissionActivite;

/**
 * @see \Application\View\Helper\ActiviteViewHelper
 *
 * Provient de l'appel de l'aide de vue
 * @var Mission|FicheMetierMission $mission
 * @var string $mode
 * @var array $options
 *
 * Récupéré du tableau d'options
 * @var FichePoste $ficheposte
 * @var FicheMetier $fichemetier
 */

$canModifier = true;

$type = null;
if ($mission instanceof FicheMetierMission) {
    $type = $mission;
    $mission = $mission->getMission();
}

$ficheposte = (isset($options['ficheposte'])) ? $ficheposte = $options['ficheposte'] : null;
$fichemetier = (isset($options['fichemetier'])) ? $fichemetier = $options['fichemetier'] : null;
$retirees = (isset($options['retirees'])) ? $retirees = $options['retirees'] : null;

?>

<div>
    <!-- TITRE -------------------------------------------------------------------------------------------------------->
    <?php if ($mode !== 'modifier-activite') : ?>
        <div class="titre-bloc">
            <?php if ($mode === "edition-fiche-poste" or $mode === "edition-fiche-metier") : ?>
                <div class="row">
                    <div class="col-md-8">
                        <h3> <?php echo $mission->getLibelle(); ?> </h3>
                    </div>
                    <div class="col-md-4">
                        <div class="float-end">
                            <?php if ($mode == 'edition-fiche-metier') : ?>
                                <span class="refresh-move action primary" data-fichemetier="<?php echo $fichemetier->getId(); ?>" data-mission="<?php echo $mission->getId(); ?>" data-direction="up">
                                    <span class="icon icon-monter"></span>
                                    Remonter
                                </span>
                                <span class="refresh-move action primary" data-fichemetier="<?php echo $fichemetier->getId(); ?>" data-mission="<?php echo $mission->getId(); ?>" data-direction="down">
                                    <span class="icon icon-descendre"></span>
                                    Descendre
                                </span>
                            <?php endif; ?>
                            <?php if ($mode === "edition-fiche-poste") : ?>
                                <?php /** @see \Application\Controller\FichePosteController::selectionnerDescriptionsRetireesAction() */ ?>
                                <a href="<?php echo $this->url('fiche-poste/selectionner-descriptions-retirees', ['fiche-poste' => $ficheposte->getId(), 'fiche-metier' => $fichemetier->getId(), 'mission-principale' => $mission->getId()], [], true); ?>"
                                   class="btn btn-primary ajax-modal" data-event="modification">
                                    Sélectionner des descriptions
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php else : ?>
                <h3><?php echo $mission->getLibelle(); ?></h3>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <!-- description -------------------------------------------------------------------------------------------------->

    <?php
    $activites = $mission->getActivites();
    usort($activites, function (MissionActivite $a, MissionActivite $b) {
        return $a->getOrdre() <=> $b->getOrdre();
    });

    //        var_dump("INIT");
    //        foreach ($activites as $activite) {
    //            var_dump($activite->getId() . " - ".$activite->getLibelle());
    //        }

    if ($ficheposte !== null) {
        $removed = array_map(function (FicheposteActiviteDescriptionRetiree $a) {
            return $a->getActivite()->getId();
        }, $ficheposte->getDescriptionsRetireesByFicheMetierAndActivite($fichemetier, $mission));

//            var_dump("TO REMOVE :");
//            foreach ($removed as $retrait) {
//                var_dump($retrait);
//            };

        $activites = array_filter($activites, function (MissionActivite $d) use ($removed) {
            return (!in_array($d->getId(), $removed));
        });

//            foreach ($activites as $activite) {
//                var_dump($activite->getId() . " - ".$activite->getLibelle());
//            }
    }
    ?>
    <ul>
        <?php foreach ($activites as $activite) : ?>
            <li>
                <?php echo $activite->getLibelle(); ?>
                <?php if ($canModifier and $mode === 'modifier-activite') : ?>
                    <a <?php /** @see ActiviteController::modifierDescriptionAction() */ ?>
                            href="<?php echo $this->url('activite/modifier-description', ['description' => $activite->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon icon-editer" title="Modifier la description"></span></a>
                    <a <?php /** @see ActiviteController::supprimerDescriptionAction() */ ?>
                            href="<?php echo $this->url('activite/supprimer-description', ['description' => $activite->getId()], [], true); ?>"
                    >
                        <span class="icon icon-historiser" title="Historiser la description"></span></a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<script>
    $(function () {
        let mode = <?php echo "'" . $mode . "'"; ?>;
        // console.log(mode);
        if (<?php echo "'" . $mode . "'"; ?> === 'modifier-activite')
        {
            $('ul#descriptions').sortable({
                update: function (event, ui) {
                    let ordre = "";
                    $('ul#descriptions li').each(function () {
                        if (ordre !== "") ordre += "_";
                        ordre += $(this)[0].id;
                    });
                    <?php /** @see ActiviteController::updateOrdreDescriptionAction() */ ?>
                    let url = '../update-ordre-description/' + <?php echo "'" . $mission->getId() . "'"; ?> +'/' + ordre;
                    // console.log(url);
                    $.ajax({
                        type: "POST",
                        url: url,
                        beforeSend:
                            function () {
                                $("ul#descriptions").sortable("option", "disabled", true);
                            },
                        success:
                            function (retour) {
                                $("ul#descriptions").sortable("option", "disabled", false);
                            }
                    });
                }
            }).disableSelection();
        }
    });
</script>