<?php

use Application\Controller\ActiviteController;
use Application\Controller\FicheMetierController;
use Application\Entity\Db\Activite;
use Application\Entity\Db\ActiviteDescription;
use Application\Entity\Db\ApplicationElement;
use Application\Entity\Db\CompetenceElement;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FicheMetierTypeActivite;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\FicheposteActiviteDescriptionRetiree;

/**
 * @see \Application\View\Helper\ActiviteViewHelper
 *
 * Provient de l'appel de l'aide de vue
 * @var Activite|FicheMetierTypeActivite $activite
 * @var string $mode
 * @var array $options
 *
 * Récupéré du tableau d'options
 * @var FichePoste $ficheposte
 * @var FicheMetier $fichemetier
 * @var FicheposteActiviteDescriptionRetiree[] $retirees
 */

$canModifier = true;

$type = null;
if ($activite instanceof FicheMetierTypeActivite) {
    $type = $activite;
    $activite  = $activite->getActivite();
}

$ficheposte  = (isset($options['ficheposte'])) ?   $ficheposte  = $options['ficheposte'] : null;
$fichemetier = (isset($options['fichemetier'])) ?  $fichemetier = $options['fichemetier'] : null;
$retirees    = (isset($options['retirees'])) ?     $retirees    = $options['retirees'] : null;

$competencesListe   = $activite->getCompetenceListe();
usort($competencesListe, function (CompetenceElement $a, CompetenceElement $b) { return $a->getCompetence()->getLibelle() > $b->getCompetence()->getLibelle();});
$nbCompetence  = count($competencesListe);
$applicationsListe  = $activite->getApplicationListe();
usort($applicationsListe, function (ApplicationElement $a, ApplicationElement $b) { return $a->getApplication()->getLibelle() > $b->getApplication()->getLibelle();});
$nbApplication = count($applicationsListe);
$formations    = $activite->getFormations();
$nbFormation   = count($formations);

$nbObject      = $nbCompetence + $nbFormation + $nbApplication;
?>

<!-- NOM DE L'ACTVITE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div class="row">
    <div class="col-md-11" style="background-color:#d9edf7; margin-left: 2rem;">
        <div class="row">
            <div class="col-md-8">
                <h3 style="color:#3c6c8b;">
                    <?php echo $activite->getLibelle(); ?>
                    <?php if ($canModifier AND $mode === 'modifier-activite') : ?>
                        <a
                            <?php /** @see ActiviteController::modifierLibelleAction() */?>
                                href="<?php echo $this->url("activite/modifier-libelle", ["activite" => $activite->getId()], [], true); ?>"
                                class="ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon editer" title="Modifier le libellé associé à la mission"></span></a>
                    <?php endif; ?>
                </h3>
            </div>
            <!-- DEPLACEMENT ET MANIPULATION DE LA LISTE DES ACTIVITES ------------------------------------------------>
            <?php if ($mode == 'edition-fiche-metier') : ?>
                <div class="col-md-4 pull-right">
                    <?php /** @see ActiviteController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('activite/modifier', ['activite' => $activite->getId()], [], true); ?>"
                       class="btn btn-default"
                       style="width:5rem; margin: 5px;"
                       target="_blank"
                    >
                        <span class="icon editer"></span><br/>
                    </a>

                    <?php /** @see FicheMetierController::retirerActiviteAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier-type/retirer-activite', ['id' => $type->getId()], [], true); ?>"
                       class="btn btn-default"
                       style="width:5rem; margin: 5px;">
                        <span class="icon detruire"></span><br/>
                    </a>

                    <?php /** @see FicheMetierController::deplacerActiviteAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier-type/deplacer-activite', ['id' => $type->getId(), 'direction' => 'up'], [], true); ?>"
                       class="btn btn-default"
                       style="width:5rem; margin: 5px;">
                        <span class="icon monter"></span><br/>
                    </a>

                    <?php /** @see FicheMetierController::deplacerActiviteAction() */ ?>
                    <a href="<?php echo $this->url('fiche-metier-type/deplacer-activite', ['id' => $type->getId(), 'direction' => 'down'], [], true); ?>"
                       class="btn btn-default"
                       style="width:5rem; margin: 5px;">
                        <span class="icon descendre"></span><br/>
                    </a>
                </div>
            <?php endif; ?>
            <!-- SELECTION DES ACTIVITES ------------------------------------------------>
            <?php if ($mode == 'edition-fiche-poste') : ?>
                <div class="col-md-1 pull-right">
                    <?php if ($ficheposte !== null AND $fichemetier !== null AND !empty($activite->getDescriptions())) : ?>
                        <a      <?php /** @see \Application\Controller\FichePosteController::selectionnerDescriptionsRetireesAction() */ ?>
                                href="<?php echo $this->url('fiche-poste/selectionner-descriptions-retirees', ['fiche-poste' => $ficheposte->getId(), 'fiche-metier' => $fichemetier->getId(), 'activite' => $activite->getId()], [], true); ?>"
                                class="ajax-modal" data-event="modification">
                            <span class="icon listing" title="Sélection des sous-activités"></span></a>
                    <?php else: ?>
                        <span class="icon listing" style="color:darkred;" title="Pas de fiche de poste, ou de fiche métier, ou pas de sous-activités"></span>
                    <?php endif; ?>
                </div>
            <?php endif ; ?>
        </div>
    </div>
</div>

<div class="row">

<!-- AFFICHAGE DES SOUS ACTIVITE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<div class="col-md-7">
    <h4>
        <?php if ($canModifier AND $mode === "modifier-activite") : ?>
            Description
            <a  <?php /** @see ActiviteController::ajouterDescriptionAction() */?>
                href="<?php echo $this->url('activite/ajouter-description', ['activite' => $activite->getId()], [], true); ?>"
                class="ajax-modal"
                data-event="modification"
            >
                <span class="icon ajouter" title="Ajouter une description"></span></a>

<!--                    <span class="icon ajouter-plusieurs"></span>-->
        <?php endif; ?>
        <?php if ($canModifier AND $mode === "modifier-activite") : ?>
            <a  <?php /** @see ActiviteController::ajouterDescriptionsAction() */?>
                    href="<?php echo $this->url('activite/ajouter-descriptions', ['activite' => $activite->getId()], [], true); ?>"
                    class="ajax-modal"
                    data-event="modification"
            >
                <span class="icon ajouter-plusieurs" title="Ajouter plusieurs descriptions en une seule fois"></span></a>
        <?php endif; ?>
    </h4>
    <?php
        $descriptions = $activite->getDescriptions();
        usort($descriptions, function (ActiviteDescription $a, ActiviteDescription $b) { return $a->getOrdre() > $b->getOrdre();});
    ?>
    <?php if (! empty($descriptions)) : ?>
        <ul id="descriptions">
            <?php foreach ($descriptions as $description) : ?>
                <?php
                    $display = true;
                    if ($retirees !== null) {
                        foreach ($retirees as $retiree) {
                            if ($retiree->getDescription()->getId() === $description->getId()) {
                                $display = false;
                                break;
                            }
                        }
                    }
                ?>
                <?php if ($display) : ?>
                <li id="<?php echo $description->getId(); ?>">
                    <span class="activite-bloc" id="<?php echo $description->getId(); ?>">
                        <?php echo $description->getDescription(); ?>
                    </span>
                    <?php if ($canModifier AND $mode === "modifier-activite") : ?>
                        <a  <?php /** @see ActiviteController::modifierDescriptionAction() */?>
                                href="<?php echo $this->url('activite/modifier-description', ['description' => $description->getId()], [], true); ?>"
                                class="ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon editer" title="Modifier la description"></span></a>
                    <a  <?php /** @see ActiviteController::supprimerDescriptionAction() */?>
                            href="<?php echo $this->url('activite/supprimer-description', ['description' => $description->getId()], [], true); ?>"
                    >
                        <span class="icon historiser" title="Historiser la description"></span></a>
                    <?php endif; ?>
                </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php else : ?>
        <span class="probleme"> <?php echo $activite->getDescription(); ?> </span>
    <?php endif; ?>
</div>

<!-- CARTOUCHE LATERAL ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<?php if ($mode === 'modifier-activite' OR $nbObject !== 0) : ?>
    <div class="col-md-4" style="border:1px lightblue solid; margin: 1rem; ">
        <small>
        <?php if ($mode === 'modifier-activite' OR $nbCompetence > 0) : ?>
            <h4>
                <span class="icon competence"></span>
                Compétences
                <span class="badge"> <?php echo $nbCompetence; ?></span>
                <?php if ($canModifier AND $mode === 'modifier-activite') : ?>
                    <a
                        <?php /** @see ActiviteController::modifierCompetenceAction() */?>
                        href="<?php echo $this->url("activite/modifier-competence", ["activite" => $activite->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon editer" title="Modifier les compétences associées à la mission"></span></a>
                <?php endif; ?>
            </h4>

            <ul>
                <?php foreach ($competencesListe as $competenceElement) : ?>
                    <li title="<?php if ($competenceElement->getCommentaire()) echo $competenceElement->getCommentaire(); ?>">
                        <?php echo $competenceElement->getCompetence()->getLibelle(); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php if ($mode === 'modifier-activite' OR $nbApplication > 0) : ?>
            <h4>
                <span class="icon application"></span>
                Applications
                <span class="badge"> <?php echo $nbApplication; ?></span>
                <?php if ($canModifier AND $mode === 'modifier-activite') : ?>
                    <a
                        <?php /** @see ActiviteController::modifierApplicationAction() */?>
                            href="<?php echo $this->url("activite/modifier-application", ["activite" => $activite->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon editer" title="Modifier les applications associées à la mission"></span></a>
                <?php endif; ?>
            </h4>

            <ul>
                <?php foreach ($applicationsListe as $applicationElement) : ?>
                    <li title="<?php if ($applicationElement->getCommentaire()) echo $applicationElement->getCommentaire(); ?>">
                        <?php echo $applicationElement->getApplication()->getLibelle(); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php if ($mode === 'modifier-activite' OR $nbFormation > 0) : ?>
            <h4>
                <span class="icon formation"></span>
                Formations
                <span class="badge"> <?php echo $nbFormation; ?></span>
                <?php if ($canModifier AND $mode === 'modifier-activite') : ?>
                    <a
                        <?php /** @see ActiviteController::modifierFormationAction() */?>
                            href="<?php echo $this->url("activite/modifier-formation", ["activite" => $activite->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon editer" title="Modifier les formations associées à la mission"></span></a>
                <?php endif; ?>
            </h4>

            <ul>
                <?php foreach ($formations as $formation) : ?>
                    <li>
                        <?php echo $formation->getLibelle(); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        </small>
    </div>
<?php endif; ?>

</div>
<style>
    a.btn-default {
        background-color: lightgrey;
    }
    a.btn-default:hover {
        background-color: #aaaaaa;
    }
</style>

<script>
    $(function() {
        let mode = <?php echo "'".$mode."'"; ?>;
        // console.log(mode);
        if (<?php echo "'".$mode."'"; ?> === 'modifier-activite') {
            $('ul#descriptions').sortable({
                update: function( event, ui ) {
                    let ordre = "";
                    $('ul#descriptions li').each(function () {
                        if (ordre !== "") ordre += "_";
                        ordre += $(this)[0].id ;
                    });
                    <?php /** @see ActiviteController::updateOrdreDescriptionAction() */ ?>
                    let url = '../update-ordre-description/' + <?php echo "'".$activite->getId()."'"; ?> + '/' + ordre;
                    // console.log(url);
                    $.ajax({
                       type: "POST",
                       url: url,
                       beforeSend:
                           function () {
                               $( "ul#descriptions" ).sortable( "option", "disabled", true );
                           },
                       success:
                           function (retour) {
                               $( "ul#descriptions" ).sortable( "option", "disabled", false );
                           }
                    });
                }
            });
            $('ul#descriptions').disableSelection();
        }
    });
</script>