<?php


/**
 * @see \Application\View\Helper\AgentGradeViewHelper
 * @var AgentGrade $grade
 * @var array $options
 */

use Application\Entity\Db\AgentEchelon;
use Application\Entity\Db\AgentGrade;

$debug = false;

/** @var AgentEchelon $echelon */
$echelon            = ($options['echelon'])??null;
$displayStructure   = (isset($options['structure']) AND $options['structure'] !== false);
$displayPeriode     = (isset($options['periode']) AND $options['periode'] !== false);
$displayIdentifiant = (isset($options['identifiant']) AND $options['identifiant'] !== false);
$displayAgent       = (isset($options['agent']) AND $options['agent'] !== false);
$displayTemoin      = (isset($options['temoin']) AND $options['temoin'] !== false);
$displayCorrespondance      = (isset($options['correspondance']) AND $options['correspondance'] !== false);
?>

<?php if($debug) : ?>
    <div class="alert alert-warning">
        <ul>
            <li>Display Structure =  <?php echo $displayStructure; ?></li>
            <li>Display Periode =  <?php echo $displayPeriode; ?></li>
            <li>Display Identifiant =  <?php echo $displayIdentifiant; ?></li>
            <li>Display Agent =  <?php echo $displayAgent; ?></li>
            <li>Display Témoin =  <?php echo $displayTemoin; ?></li>
        </ul>
    </div>
<?php endif; ?>

<div class="agent-grade">
    <?php if ($displayStructure) : ?>
        <span class="badge structure" title="<?php echo $grade->getStructure()->getLibelleLong(); ?>">
            <?php echo $grade->getStructure()->getLibelleCourt(); ?>
        </span> <br/>
    <?php endif; ?>

    <?php if ($displayPeriode) : ?>
        <?php
        $debut  = ($grade->getDateDebut())?$grade->getDateDebut()->format('d/m/Y'):'---';
        $fin    = ($grade->getDateFin() && $grade->getDateFin()->format('d/m/Y') !== '31/12/1999')?$grade->getDateFin()->format('d/m/Y'):'---';
        ?>
        <?php echo $debut; ?> &rarr; <?php echo $fin; ?>
    <?php endif; ?>


    <?php if ($displayIdentifiant) : ?>
        <span class="badge">
            <?php echo $grade->getId(); ?>
        </span>
    <?php endif; ?>

    <?php if ($displayAgent) : ?>
        <span class="badge">
            <?php echo $grade->getAgent()->getDenomination(); ?>
        </span>
    <?php endif; ?>

    <?php if ($displayCorrespondance) : ?>
        <?php echo $grade->getBap()->getCategorie(); ?>
    <?php endif; ?>

    <?php if ($displayTemoin) : ?>
    <dl class="dl-horizontal">

            <dt> Corps </dt>
            <dd>
                <?php $corps = $grade->getCorps(); ?>
                <?php if ($corps !== null) : ?>
                    <?php $niveaux = $corps->getNiveaux(); ?>
                    <?php if ($niveaux) : ?>
                        <span data-toggle="tooltip" data-html="true" title="<strong>[ <?php echo $niveaux->getBorneInferieure()->getLibelle(); ?> <?php echo $niveaux->getBorneInferieure()->getNiveau(); ?>: <?php echo $niveaux->getBorneSuperieure()->getLibelle(); ?> <?php echo $niveaux->getBorneSuperieure()->getNiveau(); ?>]</strong>">
                    <?php endif; ?>
                    <?php echo $corps->getLibelleLong(); ?>
                    <?php if ($niveaux) : ?>
                        </span>
                    <?php endif; ?>
                <?php else : ?>
                    Corps inconnu
                <?php endif; ?>
            </dd>
                <dt> Grade </dt>
                <dd>
                    <?php if ($grade->getGrade() !== null) : ?>
                        <?php echo $grade->getGrade()->getLibelleLong(); ?>
                    <?php else : ?>
                        Grade inconnu
                    <?php endif; ?>
                </dd>
            <dt> Correspondance </dt>
            <dd>
                <?php if ($grade->getBap()) : ?>
                    BAP
                    <?php echo $grade->getBap()->getCategorie(); ?> -
                    <?php echo $grade->getBap()->getLibelleLong(); ?>
                <?php else : ?>
                    Non renseignée
                <?php endif; ?>
            </dd>
            <?php if ($echelon) : ?>
                <dt> Échelon </dt>
                <dd> <?php echo $echelon->getEchelon(); ?> (date de passage : <?php echo $echelon->getDate()->format('d/m/Y'); ?>)</dd>
            <?php endif; ?>
    </dl>
    <?php endif; ?>
</div>

<style>
    div.agent-grade {
        border: solid lightblue 1px;
        margin: 1rem;
        padding: 1rem;
        /*border-radius: 5px;*/
    }
</style>
