<?php

/**
 * @var Agent $agent
 * @var string $mode
 * @var array $options
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentMissionSpecifique;
use Application\Provider\Privilege\MissionspecifiqueaffectationPrivileges;

$canVoirMission         = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_AFFICHER));
$canLettre              = $canVoirMission;
$canAjouterMission      = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_MODIFIER));
$canModifierMission     = $canAjouterMission;
$canHistoriserMission   = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_HISTORISER));
$canDetruireMission     = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_DETRUIRE));

$now = new DateTime();

$query = [];
if (isset($options["retour"])) $query["retour"] = $options["retour"];
?>

<?php
?>

<dl class="dl-horizontal">
    <dt> Prénom </dt>
    <dd> <?php echo $agent->getPrenom(); ?> </dd>
    <dt> Nom </dt>
    <dd> <?php echo $agent->getNomUsuel(); ?> </dd>
    <dt> Quotité travaillée </dt>
    <dd>
        <?php if($quotite = $agent->getQuotiteCourante()) : ?>
            <?php echo $quotite->getQuotite(); ?>%
        <?php else: ?>
            100%
        <?php endif; ?>
    </dd>
</dl>

<div class="row">
    <div class="col-md-3">
        <h3> Affectations actives</h3>
        <?php foreach ($agent->getAffectationsActifs() as $affectation) : ?>
            <?php echo $this->agentAffectation($affectation, ['structure' => true, 'periode' => false, 'temoin' => true]); ?>
        <?php endforeach; ?>
    </div>
    <div class="col-md-3">
        <h3> Statuts actifs</h3>
        <?php foreach ($agent->getStatutsActifs() as $statut) : ?>
            <?php echo $this->agentStatut($statut, ['structure' => true, 'periode' => false, 'temoin' => true]); ?>
        <?php endforeach; ?>
    </div>
    <div class="col-md-6">
        <h3> Grades actifs</h3>
        <?php foreach ($agent->getGradesActifs() as $grade) : ?>
            <?php echo $this->agentGrade($grade, ['structure' => true, 'periode' => false, 'temoin' => true, 'echelon' => $agent->getEchelonActif()]); ?>
        <?php endforeach; ?>
    </div>
</div>

<?php if (!empty($agent->getMissionsSpecifiques()) OR $mode==='edition') : ?>
    <div class="row">
        <div class="col-md-7">
            <h2>
                Missions spécifiques
            </h2>
        </div>
        <div class="col-md-4">
        <?php if ($mode === 'edition') : ?>
            <?php if ($canAjouterMission) : ?>
                <a
                    <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::ajouterAction() */?>
                    href="<?php echo $this->url('mission-specifique-affectation/ajouter', [], ['query' => ['agent' => $agent->getId()]], true); ?>"
                    class="ajax-modal btn btn-primary action pull-right"
                    data-event="modification"
                >
                    <span class="icon ajouter"></span>Ajouter une mission spécifique</a>
            <?php endif; ?>
        <?php endif; ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-11">
            <table class="table table-condensed">
            <thead>
            <tr>
                <th> Mission </th>
                <th> Structure </th>
                <th> Début </th>
                <th> Fin </th>
                <th> Volume horaire </th>
                <?php if ($mode === 'edition' || $mode === 'affichage') : ?>
                    <th class="cell-action"> Action </th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody>
            <?php $cumulDecharge = 0; ?>
            <?php
                /** @var AgentMissionSpecifique $mission */
            foreach ($agent->getMissionsSpecifiques() as $mission) :
                $structure = $mission->getStructure();
            ?>
                <?php if ($canDetruireMission OR $mission->estNonHistorise()) : ?>
                        <tr class="
                        <?php if (!$mission->estEnCours()) echo " termine "; ?>
                        <?php if ($mission->estHistorise()) echo " historise "; ?>
                    ">
                        <td> <?php echo $mission->getMission()->getLibelle(); ?> </td>
                        <td> <?php echo ($structure)?$structure->getLibelleLong():"Aucune structure"; ?> </td>
                        <td> <?php echo ($mission->getDateDebut())?$mission->getDateDebut()->format('d/m/Y'):"---"; ?> </td>
                        <td> <?php echo ($mission->getDateFin())?$mission->getDateFin()->format('d/m/Y'):"---"; ?> </td>
                        <td>
                            <?php if ($mission->getDecharge() !== null) : ?>
                                <?php echo $mission->getDecharge(); ?> h.
                                <?php if ($mission->estEnCours()) $cumulDecharge += $mission->getDecharge(); ?>
                            <?php else : ?>
                                Aucun
                            <?php endif; ?>
                        </td>
                        <?php if ($mode === 'edition' OR $mode === 'affichage') : ?>
                            <td>
                                <?php if ($canVoirMission) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::afficherAction() */?>
                                            href="<?php echo $this->url('mission-specifique-affectation/afficher', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                                            class="ajax-modal"
                                    >
                                        <span class="icon voir"></span></a>
                                    <?php if ($canLettre AND $mission->estEnCours()) : ?>
                                        <?php /** @see MissionSpecifiqueAffectationController::genererLettreTypeAction() */ ?>
                                        <a href="<?php echo $this->url('mission-specifique-affectation/generer-lettre-type', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                                           target="_blank"
                                        >
                                        <span class="icon pdf"  data-toggle="tooltip" data-html="true"
                                              title="Générer la lettre type associée l'affectation"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($mode === 'edition' AND$canModifierMission) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::ajouterAction() */?>
                                            href="<?php echo $this->url('mission-specifique-affectation/modifier', ['agent-mission-specifique' => $mission->getId()], ['query' => ['agent' => $agent->getId()]], true); ?>"
                                            class="ajax-modal"
                                            data-event="modification"
                                    >
                                        <span class="icon editer"></span></a>
                                <?php endif; ?>
                                <?php if ($mode === 'edition' AND $canHistoriserMission) : ?>
                                    <?php if ($mission->estNonHistorise()) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::historiserAction() */?>
                                                href="<?php echo $this->url('mission-specifique-affectation/historiser', ['agent-mission-specifique' => $mission->getId()], ["query" => ["retour" => $options["retour"]]], true); ?>"
                                        >
                                            <span class="icon historiser"></span></a>
                                    <?php else : ?>
                                        <a
                                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::restaurerAction() */?>
                                                href="<?php echo $this->url('mission-specifique-affectation/restaurer', ['agent-mission-specifique' => $mission->getId()], ["query" => ["retour" => $options["retour"]]], true); ?>"
                                        >
                                            <span class="icon restaurer"></span></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($mode === 'edition' AND $canDetruireMission) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::detruireAction() */?>
                                            href="<?php echo $this->url('mission-specifique-affectation/detruire', ['agent-mission-specifique' => $mission->getId()], [], true); ?>"
                                            class="ajax-modal"
                                            data-event="modification"
                                    >
                                        <span class="icon detruire"></span></a>
                                <?php endif; ?>
                            </td>
                        <?php endif;?>
                    </>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
            </table>
        </div>
    </div>

<?php endif; ?>