<?php


/**
 * @var AgentAffectation $affectation
 * @var array $options
 */

use Application\Entity\Db\AgentAffectation;

$debug = false;

$displayStructure   = (isset($options['structure']) AND $options['structure'] !== false);
$displayPeriode     = (isset($options['periode']) AND $options['periode'] !== false);
$displayIdentifiant = (isset($options['identifiant']) AND $options['identifiant'] !== false);
$displayAgent       = (isset($options['agent']) AND $options['agent'] !== false);
$displayTemoin      = (isset($options['temoin']) AND $options['temoin'] !== false);

$structure = null;
$niveau2 = null;
if ($affectation !== null) {
    $structure = $affectation->getStructure();
    if ($structure !== null) {
        if ($structure->getNiv2() !== null and $structure->getNiv2() !== $structure) {
            $niveau2 = $structure->getNiv2();
        }
    }
}
?>

<?php if($debug) : ?>
    <div class="alert alert-warning">
        <ul>
            <li>Display Structure =  <?php echo $displayStructure; ?></li>
            <li>Display Période =  <?php echo $displayPeriode; ?></li>
            <li>Display Identifiant =  <?php echo $displayIdentifiant; ?></li>
            <li>Display Agent =  <?php echo $displayAgent; ?></li>
            <li>Display Témoin =  <?php echo $displayTemoin; ?></li>
        </ul>
    </div>
<?php endif; ?>

<div class="agent-status">
    <div>
    <?php if ($displayStructure) : ?>
        <?php if ($affectation === null) : ?>
            Aucune affectation
        <?php else: ?>
            <?php if ($structure === null) : ?>
                Aucune structure
            <?php else : ?>
                <?php
                    $texte = ""; if ($niveau2) $texte = $niveau2->getLibelleCourt() . " > "; $texte .= $structure->getLibelleCourt();
                    $tooltip = "<strong>".$structure->getLibelleLong()."</strong>"; if ($niveau2) $tooltip .= "<br/> rattachée à <br/><strong>" . $niveau2->getLibelleLong() ."</strong>";
                ?>
                <span class="badge structure" title="<?php echo $tooltip; ?>" data-bs-toggle="tooltip" data-bs-html="true">
                    <?php echo $texte; ?>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
    </div>

    <div>
        <?php if ($displayPeriode) : ?>
            <?php
                $debut  = ($affectation->getDateDebut())?$affectation->getDateDebut()->format('d/m/Y'):'---';
                $fin    = ($affectation->getDateFin() && $affectation->getDateFin()->format('d/m/Y') !== '31/12/1999')?$affectation->getDateFin()->format('d/m/Y'):'---';
            ?>
            <?php echo $debut; ?> &rarr; <?php echo $fin; ?>
        <?php endif; ?>
    </div>

    <div>
        <?php if ($displayIdentifiant) : ?>
            <strong> Identifiant </strong> <br/>
                <span class="badge">
                    <?php echo $affectation->getIdOrig(); ?>
                </span>
        <?php endif; ?>

        <?php if ($displayAgent) : ?>
            <strong> Agent  : </strong> <br/>
                <span class="badge">
                    <?php echo $affectation->getAgent()->getDenomination(); ?>
                </span>
        <?php endif; ?>

        <?php if ($displayTemoin) : ?>
                <ul>
                <?php
                    if ($affectation !== null AND $affectation->isPrincipale())        echo '<li>Principale</li>';
                    if ($affectation !== null AND $affectation->isHierarchique())      echo '<li>Hiérarchique</li>';
                    if ($affectation !== null AND $affectation->isFonctionnelle())     echo '<li>Fonctionnelle</li>';
                ?>
                </ul>
        <?php endif; ?>

        <?php if ($affectation->getQuotite() !== null) : ?>
        Quotité : <?php echo $affectation->getQuotite(); ?>%
        <?php endif; ?>

    </div>
</div>

<style>
    div.agent-status {
        border: solid lightblue 1px;
        margin: 1rem;
        padding: 1rem;
        /*border-radius: 5px;*/
    }
</style>