<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentCompetence;

/**
 * @see \Application\View\Helper\AgentCompetenceViewHelper
 * @var Agent $agent
 * @var array $options
 */

$canVoir        = (isset($options['droits']) AND isset($options['droits']['afficher']))     ? $options['droits']['afficher']    : false;
$canAjouter     = (isset($options['droits']) AND isset($options['droits']['ajouter']))      ? $options['droits']['ajouter']     : false;
$canModifier    = (isset($options['droits']) AND isset($options['droits']['modifier']))     ? $options['droits']['modifier']    : false;
$canHistoriser  = (isset($options['droits']) AND isset($options['droits']['historiser']))   ? $options['droits']['historiser']  : false;
$canDetruire    = (isset($options['droits']) AND isset($options['droits']['detruire']))     ? $options['droits']['detruire']    : false;
$canValider     = (isset($options['droits']) AND isset($options['droits']['valider']))      ? $options['droits']['valider']     : false;

$retour         = (isset($options['retour'])) ? $options['retour'] : null;

?>
<div class="row">
    <div class="col-md-8" style="border-bottom: 1px solid #31708f">
        <h3> <span class="icon competence"></span> Compétences liées</h3>
    </div>
    <div class="pull-right">
        <br/>
        <?php if ($canAjouter) : ?>
            <a
                <?php /** @see \Application\Controller\AgentController::ajouterAgentCompetenceAction() */?>
                    href="<?php echo $this->url('agent/ajouter-agent-competence', ['agent' => $agent->getId()], [], true); ?>"
                    class="ajax-modal btn btn-primary action"
                    data-event="modification"
            >
                <span class="icon ajouter" title="Ajouter une compétence pour l'agent"></span>
                Ajouter une compétence
            </a>
        <?php endif; ?>
    </div>
</div>
<br/>
<?php
$noGroupe = "ZZZZ";
$dictionnaire = [];
foreach ($agent->getCompetences(true) as $agentCompetence) {
    $competence = $agentCompetence->getCompetence();
    $groupe = $competence->getType();
    $libelle = ($groupe)?$groupe->getLibelle():$noGroupe;
    $dictionnaire[$libelle][] = $agentCompetence;
}
ksort($dictionnaire);
?>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <?php if ($canModifier) : ?>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="competences-historisees"> Afficher les compétences historisées
                    </label>
                </div>
            </div>
        <?php endif; ?>
        <table class="parcours-de-formation" id="competences">
            <tbody>
            <?php foreach ($dictionnaire as $key => $liste) : ?>
                <?php usort($liste, function(AgentCompetence $a, AgentCompetence $b) {return $a->getCompetence()->getLibelle() > $b->getCompetence()->getLibelle();}); ?>
                <?php
                $allHisto = true;
                foreach ($liste as $agentCompetence) {
                    if ($agentCompetence->estNonHistorise()) {
                        $allHisto = false;
                        break;
                    }
                }
                ?>
                <tr>
                    <?php if ($key !== $noGroupe) : ?>
                        <?php $groupe = $liste[0]->getCompetence()->getType(); ?>
                        <th colspan="4" style="background: <?php echo $groupe->getCouleur(); ?>;" <?php if ($allHisto) echo 'class="historise"'; ?>>
                            <?php echo $groupe->getLibelle(); ?>
                        </th>
                    <?php else :?>
                        <th colspan="4" style="background: gray;" <?php if ($allHisto) echo 'class="historise"'; ?>> Sans groupe ...</th>
                    <?php endif; ?>
                </tr>
                <?php foreach ($liste as $agentCompetence) : ?>
                    <tr <?php if ($agentCompetence->estHistorise()) echo 'class="historise"'; ?>>
                        <td> <?php echo $agentCompetence->getCompetence()->getLibelle(); ?> </td>
                        <td> <?php echo $agentCompetence->getNiveau() ?> </td>
                        <td>
                            <?php if ($agentCompetence->getValidation()) : ?>
                            <?php $validation = $agentCompetence->getValidation(); ?>
                            <?php if ($validation->getValeur() === null) : ?>
                                <span
                                        style="color:darkgreen;"
                                        title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                <span class="icon ok"></span>
                                Validée
                            </span>
                            <?php else: ?>
                            <span
                                    style="color:darkred;"
                                    title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                <span class="icon ko"></span>
                            Refusée
                        <?php endif; ?>
                                <?php else : ?>
                                    Aucune validation
                                <?php endif; ?>
                        </td>
                        <td>
                            <?php if ($canVoir) : ?>
                                <a
                                    <?php /** @see \Application\Controller\AgentController::afficherAgentCompetenceAction() */?>
                                        href="<?php echo $this->url('agent/afficher-agent-competence', ['agent-competence' => $agentCompetence->getId()], [], true); ?>"
                                        class="ajax-modal"
                                >
                                    <span class="icon voir" title="Afficher une compétence liées à l'agent"></span></a>
                            <?php endif; ?>
                            <?php if ($canModifier) : ?>
                                <a
                                    <?php /** @see \Application\Controller\AgentController::modifierAgentCompetenceAction() */?>
                                        href="<?php echo $this->url('agent/modifier-agent-competence', ['agent-competence' => $agentCompetence->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                >
                                    <span class="icon editer" title="Modifier une compétence liées à l'agent"></span></a>
                            <?php endif; ?>
                            <?php if ($canHistoriser) : ?>
                                <?php if ($agentCompetence->estNonHistorise()) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\AgentController::historiserAgentCompetenceAction() */?>
                                            href="<?php echo $this->url('agent/historiser-agent-competence', ['agent-competence' => $agentCompetence->getId()], ['query' => ['retour' => $retour]], true); ?>"
                                    >
                                        <span class="icon historiser" title="Historiser une compétence liées à l'agent"></span></a>
                                <?php else: ?>
                                    <a
                                        <?php /** @see \Application\Controller\AgentController::restaurerAgentCompetenceAction() */?>
                                            href="<?php echo $this->url('agent/restaurer-agent-competence', ['agent-competence' => $agentCompetence->getId()], ['query' => ['retour' => $retour]], true); ?>"
                                    >
                                        <span class="icon restaurer" title="Restaurer une compétence liées à l'agent"></span></a>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($canDetruire) : ?>
                                <a
                                    <?php /** @see \Application\Controller\AgentController::detruireAgentCompetenceAction() */?>
                                        href="<?php echo $this->url('agent/detruire-agent-competence', ['agent-competence' => $agentCompetence->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                >
                                    <span class="icon detruire" title="Supprimer définitivement une compétence liées à l'agent"></span>
                                </a>
                            <?php endif; ?>
                            <?php if ($canValider) : ?>
                                <?php if ($agentCompetence->getValidation() === null) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\AgentController::validerElementAction() */ ?>
                                            href="<?php echo $this->url('agent/valider-element', ['type' => "AgentCompetence", 'id' => $agentCompetence->getId()], [], true); ?>"
                                            class="ajax-modal"
                                            data-event="modification"
                                    >
                                        <span class="icon validation-do" title="Valider la compétence"></span></a>
                                <?php else: ?>
                                    <a
                                        <?php /** @see \Application\Controller\AgentController::revoquerElementAction() */ ?>
                                            href="<?php echo $this->url('agent/revoquer-element', ['validation' => $agentCompetence->getValidation()->getId()], ['query' => ['retour' => $retour]], true); ?>"
                                    >
                                        <span class="icon validation-undo" title="Dévalider la compétence"></span></a>
                                <?php endif; ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script>

    function toogleCompetencesHistorisees() {
        let checked = $('input#competences-historisees').prop('checked');
        if (checked === true) {
            $('table#competences  th.historise').show();
            $('table#competences  tr.historise').show();
        } else {
            $('table#competences  th.historise').hide();
            $('table#competences  tr.historise').hide();
        }
    }

    $(document).ready(function() {
        toogleCompetencesHistorisees();
    });

    $('input#competences-historisees').change(function() {
        toogleCompetencesHistorisees();
    });

</script>