<?php

/**
 * @var Agent $agent
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentMissionSpecifique;

$now = new DateTime();
?>

<h2> Présentation de l'agent </h2>

<?php
?>

<dl class="dl-horizontal">
    <dt> Prénom </dt>
    <dd> <?php echo $agent->getPrenom(); ?> </dd>
    <dt> Nom </dt>
    <dd> <?php echo $agent->getNomUsuel(); ?> </dd>
    <dt> Quotité travaillée </dt>
    <dd>
        <?php if ($agent->getQuotite() !== null) : ?>
            <?php echo $agent->getQuotite(); ?>%
        <?php else : ?>
            <span style="color:darkred; font-style: italic;">Quotité travaillée non renseignée</span>
        <?php endif; ?>
    </dd>
</dl>

<div class="row">
    <div class="col-md-4">
        <h3> Statuts actifs</h3>
        <?php foreach ($agent->getStatutsActifs() as $statut) : ?>
            <?php echo $this->agentStatut($statut, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
        <?php endforeach; ?>
    </div>
    <div class="col-md-8">
        <h3> Grades actifs</h3>
        <?php foreach ($agent->getGradesActifs() as $grade) : ?>
            <?php echo $this->agentGrade($grade, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
        <?php endforeach; ?>
    </div>
</div>

<?php if (!empty($agent->getMissionsSpecifiques())) : ?>
    <h2> Missions spécifiques </h2>

    <ul>
        <?php /** @var AgentMissionSpecifique $mission */ ?>
        <?php foreach ($agent->getMissionsSpecifiques() as $mission) : ?>
            <li>
                <?php echo $mission->getMission()->getLibelle(); ?>
                <?php if ($mission->getStructure()) echo  " pour ".$mission->getStructure()->getLibelleCourt(); ?>
                 du
                <?php echo ($mission->getDateDebut()?$mission->getDateDebut()->format('d/m/Y'):"---"); ?>
                au
                <?php echo ($mission->getDateFin()?$mission->getDateFin()->format('d/m/Y'):"---"); ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>