<?php

use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FicheMetierTypeActivite;

/**
 * @var array $applications
 * @var array $options
 *
 * la sutrcture de application est la suivante :
 *
 * $applications = [
 *      ID => [
 *          'entite' => Application,
 *          'display' => true|false,
 *          'raison' => [
 *                  [ 'source', SourceEntity ],
 *                  [ 'source', SourceEntity ],
 *                  ...
 *              ]
 *          ],
 *      ...
 *  ]
 */

$groupes = [];
$sansGroupe = "zzz";
foreach ($applications as $item) {
    $application = $item['entite'];
    if ($application) {
        $libelleGroupe = ($application->getGroupe()) ? $application->getGroupe()->getLibelle() : $sansGroupe;
        if ($item['conserve'] === true) $groupes[$libelleGroupe][] = $item;
    }
}

ksort($groupes);

?>

<ul>
<?php foreach ($groupes as $libelle => $groupe) : ?>
    <li class="groupe-libelle">
    <?php if ($libelle !== $sansGroupe) : ?>
            <?php echo $groupe[0]['entite']->getGroupe()->getLibelle(); ?>
    <?php else : ?>
        Sans groupe ...
    <?php endif; ?>
    </li>
    <ul>
    <?php usort ($groupe, function($a, $b) { return $a['entite']->getLibelle() > $b['entite']->getLibelle();}); ?>
    <?php foreach ($groupe as $application) : ?>
        <li class="element-libelle">
            <?php echo $application['entite']->getLibelle(); ?>
            <?php echo $this->raisons($application['raison']); ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endforeach; ?>
</ul>
