<?php

/**
 * @see \Application\View\Helper\FormationGroupeViewHelper
 * @var ApplicationGroupe $groupe
 */

use Application\Entity\Db\ApplicationGroupe;

?>

<span class="label groupe-<?php echo $groupe->getId(); ?>">
<!--    <span class="icon application"></span>-->
    <?php echo $groupe->getLibelle(); ?>
</span>

<style>
    span.label.<?php echo "groupe-".$groupe->getId(); ?> {
        /*background-color: */<?php //echo $groupe->getCouleur(); ?>/*;*/
        min-width: 10rem;
        display: inline-block;
    }
</style>
