<?php

use Application\Entity\Db\Activite;
use Application\Entity\Db\FicheMetier;

/**
 * @var array $applications
 * @var array $options
 *
 * la sutrcture de application est la suivante :
 *
 * $applications = [
 *      ID => [
 *          'entite' => Application,
 *          'display' => true|false,
 *          'raison' => [
 *                  [ 'source', SourceEntity ],
 *                  [ 'source', SourceEntity ],
 *                  ...
 *              ]
 *          ],
 *      ...
 *  ]
 */

$groupes = [];
$sansGroupe = "zzz";
foreach ($applications as $item) {
    $application = $item['entite'];
    if ($application) {
        $libelleGroupe = ($application->getGroupe()) ? $application->getGroupe()->getLibelle() : $sansGroupe;
        if ($item['conserve'] === true) $groupes[$libelleGroupe][] = $item;
    }
}

ksort($groupes);

?>

<table class="applications">
    <?php foreach ($groupes as $libelle => $groupe) : ?>

        <tr>
            <?php if ($libelle !== $sansGroupe) : ?>
            <th style="background:<?php echo $groupe[0]['entite']->getGroupe()->getCouleur(); ?>">
                <?php echo $groupe[0]['entite']->getGroupe()->getLibelle(); ?>
            </th>
            <?php else : ?>
                <th style="background:gray"> Sans groupe ... </th>
            <?php endif; ?>
        </tr>

        <?php usort ($groupe, function($a, $b) { return $a['entite']->getLibelle() > $b['entite']->getLibelle();}); ?>

            <?php foreach ($groupe as $application) : ?>
                <tr>
                    <td class="libelle">
                        <?php echo $application['entite']->getLibelle(); ?>
                        <?php foreach ($application['raison'] as $raison) : ?>
                            <?php $text = "";
                            switch ($raison) {
                                case $raison instanceof FicheMetier :
                                    $fm = $raison;
                                    $text = $fm->getMetier()->getLibelle();
                                    $label = "F";
                                    $class = 'fiche-metier';
                                    break;
                                case $raison instanceof Activite :
                                    $ac = $raison;
                                    $text = $ac->getLibelle();
                                    $label = "A";
                                    $class = 'activite';
                            }
                            ?>
                            <span class="<?php echo $class; ?>" title="<?php echo $text; ?>"><?php echo $label; ?></span>
                        <?php endforeach; ?>
                    </td>
                </tr>
            <?php endforeach; ?>

    <?php endforeach; ?>
</table>

<!--        <ul>-->
<!--            --><?php //foreach ($applications as $id => $bloc) : ?>
<!--                --><?php //if ($bloc['display'] === true) : ?>
<!--                    <li>-->
<!--                        --><?php //echo $bloc['entity']->getLibelle(); ?>

<!--                    </li>-->
<!--                --><?php //endif; ?>
<!--            --><?php //endforeach; ?>
<!--        </ul>-->
<!--    </div>-->
<!--</div>-->

<style>
    table.applications {
        width:95%;
    }

    table.applications th {
        padding: 0.5rem;
        color: white;
    }
    table.applications td.libelle {
        padding-left: 1rem;
    }
    table.applications td.formation {
        text-align: center;
    }
</style>