<?php

use Application\Entity\Db\Competence;

/**
 * @var array $competences
 * @var array $options
 *
 * la sutrcture de application est la suivante :
 *
 * $applications = [
 *      ID => [
 *          'entite' => Application,
 *          'display' => true|false,
 *          'raison' => [
 *                  [ 'source', SourceEntity ],
 *                  [ 'source', SourceEntity ],
 *                  ...
 *              ]
 *          ],
 *      ...
 *  ]
 */

$groupes = [];
$sansGroupe = "zzz";
foreach ($competences as $item) {
    /** @var Competence $competence */
    $competence = $item['entite'];
    if ($competence) {
        $libelleGroupe = ($competence->getType()) ? $competence->getType()->getLibelle() : $sansGroupe;
        if ($item['conserve'] === true) $groupes[$libelleGroupe][] = $item;
    }
}

ksort($groupes);

?>

<ul>
    <?php foreach ($groupes as $libelle => $groupe) : ?>
        <li class="groupe-libelle">
            <?php if ($libelle !== $sansGroupe) : ?>
                <?php echo $groupe[0]['entite']->getType()->getLibelle(); ?>
            <?php else : ?>
                Sans groupe ...
            <?php endif; ?>
        </li>
        <ul>
            <?php usort ($groupe, function($a, $b) { return $a['entite']->getLibelle() > $b['entite']->getLibelle();}); ?>
            <?php foreach ($groupe as $competence) : ?>
                <li class="element-libelle">
                    <?php echo $competence['entite']->getLibelle(); ?>
                    <?php echo $this->raisons($competence['raison']); ?>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endforeach; ?>
</ul>


