<?php

use Application\Entity\Db\Activite;
use Application\Entity\Db\Competence;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FicheMetierTypeActivite;

/**
 * @var array $competences
 * @var array $options
 *
 * la sutrcture de application est la suivante :
 *
 * $applications = [
 *      ID => [
 *          'entite' => Application,
 *          'display' => true|false,
 *          'raison' => [
 *                  [ 'source', SourceEntity ],
 *                  [ 'source', SourceEntity ],
 *                  ...
 *              ]
 *          ],
 *      ...
 *  ]
 */

$groupes = [];
$sansGroupe = "zzz";
foreach ($competences as $item) {
    /** @var Competence $competence */
    $competence = $item['entite'];
    if ($competence) {
        $libelleGroupe = ($competence->getType()) ? $competence->getType()->getLibelle() : $sansGroupe;
        if ($item['conserve'] === true) $groupes[$libelleGroupe][] = $item;
    }
}

ksort($groupes);

?>

<table class="competences">
    <?php foreach ($groupes as $libelle => $groupe) : ?>

        <tr>
            <?php if ($libelle !== $sansGroupe) : ?>
            <th class="titre">
                <?php echo $groupe[0]['entite']->getType()->getLibelle(); ?>
            </th>
            <?php else : ?>
                <th class="titre"> Sans groupe ... </th>
            <?php endif; ?>
        </tr>

        <?php usort ($groupe, function($a, $b) { return $a['entite']->getLibelle() > $b['entite']->getLibelle();}); ?>

            <?php foreach ($groupe as $item) : ?>
                <tr>
                    <td class="libelle">
                        <?php echo $item['entite']->getLibelle(); ?>
                        <?php foreach ($item['raison'] as $raison) : ?>
                            <?php $text = "";
                            switch ($raison) {
                                case $raison instanceof FicheMetier :
                                    $fm = $raison;
                                    $text = $fm->getMetier()->getLibelle();
                                    $label = "F";
                                    $class = 'fiche-metier';
                                    break;
                                case $raison instanceof FicheMetierTypeActivite :
                                    $ac = $raison;
                                    $text = $ac->getActivite()->getLibelle();
                                    $label = "A";
                                    $class = 'activite';
                                    break;
                                default :
                                    $text = "Provenance inconnue";
                                    $label = "?";
                                    $class = 'inconnue';
                            }
                            ?>
                            <span class="<?php echo $class; ?>" title="<?php echo $text; ?>"><?php echo $label; ?></span>
                        <?php endforeach; ?>
                    </td>
                </tr>
            <?php endforeach; ?>

    <?php endforeach; ?>
</table>

<style>
    table.competences {
        width:95%;
    }

    table.applications th {
        padding: 0.5rem;
        color: white;
    }
    table.applications td.libelle {
        padding-left: 1rem;
    }
    table.applications td.formation {
        text-align: center;
    }
</style>