<?php

use FicheMetier\Entity\Db\FicheMetier;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\FicheTypeExterne;

/**
 * @see \Application\View\Helper\FicheMetierViewHelper
 * @var FicheMetier $fichemetier
 * @var FichePoste $ficheposte
 * @var FicheTypeExterne $ficheexterne
 * @var array $options
 */

//$metier = $fichemetier->getMetier();
//$agent = ($ficheposte)?$ficheposte->getAgent():null;
//
///**
// * @var FicheMetierActivite[] $activites
// */
//$activites = $fichemetier->getActivites();
//
//$activitesListe = [];
//if (isset($options['activite-liste'])) {
//    $activitesListe = explode(';', $options['activite-liste']);
//} else {
//    foreach ($activites as $activite) $activitesListe[] = $activite->getActivite()->getId();
//}
//
//$sansTitre = (isset($options['sans-titre']) AND $options['sans-titre']);
//$mode = $options['mode'];
//
//if ($options['popup']) $options['actions']['afficher'] = false;
//?>

<?php /** Watermark de l'identifiant de la fiche qui peut être utilisée pour des redirections **********************/ ?>
<span style="visibility:hidden;">
    Fiche métier #<?php echo $fichemetier->getId(); ?>
</span>

<?php /** DEBUG *****************************************************************************************************/?>

<?php
//    $DEBUG = false;
//    if ($DEBUG) :
//?>
<!---->
<!--<div class="alert alert-warning">-->
<!--    <h3> Debug de l'aide de vue FicheMetierViewHelper </h3>-->
<!---->
<!--    <dl class="dl-horizontal">-->
<!--        <dt> FicheMetier.Id</dt>-->
<!--        <dd> --><?php //echo $fichemetier->getId(); ?><!-- </dd>-->
<!--        <dt>Mode</dt>-->
<!--        <dd>--><?php //echo $mode; ?><!--</dd>-->
<!--        <dt>Titre</dt>-->
<!--        <dd>--><?php //echo ($options['sans-titre'])?"Sans":"Avec"; ?><!--</dd>-->
<!--    </dl>-->
<!--</div>-->
<!---->
<?php //endif; ?>

<?php /** FICHE || ENTETE *******************************************************************************************/?>

<?php //if ($sansTitre !== true) : ?>
<?php //echo $this->ficheMetierEntete($fichemetier); ?>

<hr/>

<div class="row">
<div class="pull-right" style="margin:0 1rem;">
<!--    --><?php //if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier') : ?>
<!--        --><?php ///** @see FicheMetierController::editerLibelleAction() */ ?>
<!--        <a  class="btn btn-primary action ajax-modal" data-event="modification"-->
<!--            href="--><?php //echo $this->url('fiche-metier-type/editer-libelle', ['id' => $fichemetier->getId()], [] , true); ?><!--">-->
<!--            <span class="icon icon-editer"></span>-->
<!--            Modifier libellé-->
<!--        </a>-->
<!---->
<!--        <a-->
<!--            --><?php ///** @see FicheMetierController::changerExpertiseAction() */?>
<!--                href="--><?php //echo $this->url('fiche-metier-type/changer-expertise', ['fiche' => $fichemetier->getId()], [], true); ?><!--"-->
<!--                class="btn btn-primary action"-->
<!--        >-->
<!--            --><?php //if ($fichemetier->hasExpertise()) : ?>
<!--                <span class="icon retirer"></span>-->
<!--                Retirer expertise-->
<!--            --><?php //else: ?>
<!--                <span class="icon icon-ajouter"></span>-->
<!--                Ajouter expertise-->
<!--            --><?php //endif; ?>
<!--        </a>-->
<!--    --><?php //endif; ?>
<!--</div>-->
<!--</div>-->
<!---->
<!---->
<?php //endif; ?>


<?php ///** FICHE || ACTIVITES / MISSIONS PRINCIPALES *****************************************************************/?>
<!---->
<?php
//    $activitesRestantes = $activites;
//    if ($ficheposte !== null) {
//        $activitesRestantes = [];
//        foreach ($activites as $activite) {
//            if (array_search($activite->getActivite()->getId(), $activitesListe) !== false) {
//                $activitesRestantes[] = $activite;
//            }
//        }
//    }
//?>
<!--<div class="main">-->
<!--    --><?php //if ($ficheposte === null) : ?>
<!--    <br/>-->
<!--    <div class="card panel-info">-->
<!--        <div class="card-header">-->
<!--            <h2>-->
<!--                Missions principales-->
<!--                <span class="badge"> --><?php //echo count($activitesRestantes); ?><!--/--><?php //echo count($activites); ?><!-- </span>-->
<!--            </h2>-->
<!--        </div>-->
<!--        <div class="card-body">-->
<!--            <div class="row">-->
<!--                --><?php //if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier') : ?>
<!--                    --><?php ///** @see FicheMetierController::ajouterNouvelleActiviteAction() */ ?>
<!--                    <a  class="btn btn-primary action ajax-modal pull-right"-->
<!--                        href="--><?php //echo $this->url('fiche-metier-type/ajouter-nouvelle-activite', ['id' => $fichemetier->getId()], [] , true); ?><!--"-->
<!--                        data-event="modification"-->
<!--                    >-->
<!--                        <span class="icon icon-ajouter"></span>-->
<!--                        Ajouter une nouvelle activité-->
<!--                    </a>-->
<!--                    --><?php ///** @see FicheMetierController::ajouterActiviteExistanteAction() */ ?>
<!--                    <a  class="btn btn-primary action ajax-modal pull-right"-->
<!--                        data-event="modification"-->
<!--                        href="--><?php //echo $this->url('fiche-metier-type/ajouter-activite-existante', ['id' => $fichemetier->getId()], [] , true); ?><!--">-->
<!--                        <span class="icon selectionner"></span>-->
<!--                        Ajouter une activité existante-->
<!--                    </a>-->
<!--                --><?php //endif; ?>
<!--            </div>-->
<!--        --><?php //else : ?>
<!--            <div>-->
<!--                <div class="row">-->
<!--                    <div class="col-md-8">-->
<!--                        Missions principales-->
<!--                        <span class="badge"> --><?php //echo count($activitesRestantes); ?><!--/--><?php //echo count($activites); ?><!-- </span>-->
<!--                    </div>-->
<!--                    <div class="pull-right">-->
<!--                        --><?php //if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-poste') : ?>
<!--                            <br/>-->
<!--                            <a-->
<!--                                --><?php ///** @see \Application\Controller\FichePosteController::selectionnerActiviteAction() */ ?>
<!--                                    href="--><?php //echo $this->url('fiche-poste/selectionner-activite', ['fiche-poste' => $ficheposte->getId(), 'fiche-type-externe' => $ficheexterne->getId()], [], true); ?><!--"-->
<!--                                    class="ajax-modal" data-event="modification"-->
<!--                            >-->
<!--                                <span class="icon icon-listing" title="Sélectionner les activités associées"></span></a>-->
<!--                        --><?php //endif; ?>
<!--                    </div>-->
<!--                </div>-->
<!--                <div>-->
<!--        --><?php //endif; ?>
<!--            --><?php //foreach ($activitesRestantes as $ficheActivite): ?>
<!--                --><?php
//                    $retirees = [];
//                    if ($ficheposte) $retirees = FicheposteActiviteDescriptionRetiree::filtrer($ficheActivite->getActivite(), $ficheposte->getDescriptionsRetirees()->toArray());
//                ?>
<!--                --><?php //echo $this->activite($ficheActivite, $options['mode'], ['ficheposte' => $ficheposte, 'fichemetier' => $fichemetier, 'retirees' => $retirees]); ?>
<!--            --><?php //endforeach;?>
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<!-- AUTRE INFO --------------------------------------------------------------------------------------------------->

<?php //if ($ficheposte === null) : ?>
<!--    <div class="main">-->

<!-- COMPETENCES -------------------------------------------------------------------------------------------------->

<!--        --><?php //if (! isset($options['competences'])) : ?>
<!--            <div class="alert alert-danger">-->
<!--                Le dictionnaire des compétences n'est pas fourni.-->
<!--            </div>-->
<!--        --><?php //else : ?>
<!--            --><?php //$dictionnaireCompetence = $options['competences']; ?>
<!--            <div class="card panel-info">-->
<!--                <div class="card-header">-->
<!--                    <div class="row">-->
<!--                        <div class="col-md-8">-->
<!--                            <h2>-->
<!--                                <span class="icon competence"></span>-->
<!--                                Compétences-->
<!--                                <span class="badge">-->
<!--                                    --><?php //echo count($dictionnaireCompetence); ?>
<!--                                </span>-->
<!--                            </h2>-->
<!--                        </div>-->
<!--                        <div class="pull-right">-->
<!--                            --><?php //if ($options['popup'] !== true) : ?>
<!--                                --><?php ///** @see FicheMetierController::graphiqueCompetencesAction() */ ?>
<!--                                <a href="--><?php //echo $this->url('fiche-metier-type/graphique-competences', ['fiche-metier' => $fichemetier->getId(), 'agent' => ($agent)?$agent->getId():null], [], true); ?><!--"-->
<!--                                   class="btn btn-primary action ajax-modal"-->
<!--                                >-->
<!--                                    <span class="icon icon-diagramme"></span>-->
<!--                                    Afficher les compétences-->
<!--                                </a>-->
<!--                            --><?php //endif; ?>
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="card-body">-->
<!--                    <div class="row">-->
<!--                    <div class="pull-right">-->
<!--                        --><?php //if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier') : ?>
<!--                            --><?php ///** @see \Application\Controller\CompetenceController::ajouterCompetenceElementAction() */ ?>
<!--                            <a href="--><?php //echo $this->url('competence/ajouter-competence-element', ['type' => FicheMetier::class, 'id' => $fichemetier->getId()], [], true); ?><!--"-->
<!--                               class="btn btn-primary action ajax-modal"-->
<!--                               data-event="modification"-->
<!--                            >-->
<!--                                <span class="icon icon-ajouter"></span>-->
<!--                                Ajouter une compétence-->
<!--                            </a>-->
<!--                        --><?php //endif; ?>
<!---->
<!--                    </div>-->
<!--                    </div>-->
<!--                    --><?php //echo $this->competenceBloc($dictionnaireCompetence, $fichemetier,
//                            ['display' => ['titre' => false, 'validation' => false, 'raison' => false],
//                            'actions' => $options['actions']]); ?>
<!--                </div>-->
<!--            </div>-->
<!--        --><?php //endif; ?>

<!-- APPLICATION -------------------------------------------------------------------------------------------------->
<!--        --><?php //if (! isset($options['applications'])) : ?>
<!--            <div class="alert alert-danger">-->
<!--                Le dictionnaire des applications n'est pas fourni.-->
<!--            </div>-->
<!--        --><?php //else : ?>
<!--            --><?php //$dictionnaireApplication = $options['applications']; ?>
<!--            <div class="card panel-info">-->
<!--                <div class="card-header">-->
<!--                    <div class="row">-->
<!--                        <div class="col-md-8">-->
<!--                            <h2>-->
<!--                                <span class="icon application"></span>-->
<!--                                Applications-->
<!--                                <span class="badge">-->
<!--                                    --><?php //echo count($dictionnaireApplication); ?>
<!--                                </span>-->
<!--                            </h2>-->
<!--                        </div>-->
<!--                        <div class="pull-right">-->
<!--                            --><?php //if ($options['popup'] !== true) : ?>
<!--                                --><?php ///** @see FicheMetierController::graphiqueApplicationsAction() */ ?>
<!--                                <a href="--><?php //echo $this->url('fiche-metier-type/graphique-applications', ['fiche-metier' => $fichemetier->getId(), 'agent' => ($agent)?$agent->getId():null], [], true); ?><!--"-->
<!--                                   class="btn btn-primary action ajax-modal"-->
<!--                                >-->
<!--                                    <span class="icon icon-diagramme"></span>-->
<!--                                    Afficher les applications-->
<!--                                </a>-->
<!--                            --><?php //endif; ?>
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="card-body">-->
<!--                    <div class="row">-->
<!--                        <div class="pull-right">-->
<!--                        --><?php //if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier'): ?>
<!--                            --><?php ///** @see \Application\Controller\ApplicationController::ajouterApplicationElementAction() */ ?>
<!--                            <a href="--><?php //echo $this->url('application/ajouter-application-element', ['type' => FicheMetier::class, 'id' => $fichemetier->getId()], [], true); ?><!--"-->
<!--                               class="btn btn-primary action ajax-modal"-->
<!--                               data-event="modification"-->
<!--                            >-->
<!--                                <span class="icon icon-ajouter"></span>-->
<!--                                Ajouter une application-->
<!--                            </a>-->
<!--                        --><?php //endif; ?>
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                    --><?php //echo $this->applicationBloc($dictionnaireApplication,$fichemetier,
//                            ['display' => ['titre' => false, 'validation' => false, 'raison' => false],
//                            'actions' => $options['actions']]); ?>
<!--                </div>-->
<!--            </div>-->
<!--        --><?php //endif; ?>
<!---->
    <!-- FORMATION ---------------------------------------------------------------------------------------------------->
<!---->
<!--        --><?php //if (! isset($options['parcours'])) : ?>
<!--            <div class="alert alert-danger">-->
<!--                Le parcours de formation n'est pas fourni.-->
<!--            </div>-->
<!--        --><?php //else : ?>
<!--            <div class="card panel-info">-->
<!--            <div class="card-header">-->
<!--                <h2>-->
<!--                    <span class="icon formation"></span>-->
<!--                    Parcours de formation-->
<!--                </h2>-->
<!--            </div>-->
<!--            <div class="card-body">-->
<!--                <div class="row">-->
<!--                    <div class="col-md-1"></div>-->
<!--                    <div class="col-md-10">-->
<!--            --><?php
//                $arrays = $options['parcours'];
//                ksort($arrays);
//                foreach ( $arrays as $type => $array) : ?>
<!--                --><?php //$parcours = $array; ?>
<!--                    --><?php //foreach ($parcours as $parcour) : ?>
<!--                        --><?php //echo $this->parcoursDeFormation($parcour); ?>
<!--                    --><?php //endforeach; ?>
<!--                --><?php //endforeach; ?>
<!---->
<!--                    --><?php //echo $this->parcoursApplication($fichemetier); ?>
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--            </div>-->
<!--            </div>-->
<!--        --><?php //endif; ?>
<!--    </div>-->
<?php //else : ?>
<!--        --><?php ///** @see FicheMetierController::graphiqueCompetencesAction() */ ?>
<!--        <a href="--><?php //echo $this->url('fiche-metier-type/graphique-competences', ['fiche-metier' => $fichemetier->getId(), 'agent' => ($agent)?$agent->getId():null], [], true); ?><!--"-->
<!--           class="btn btn-primary action ajax-modal"-->
<!--        >-->
<!--            <span class="icon icon-diagramme"></span>-->
<!--            Afficher les compétences-->
<!--        </a>-->
<!---->
<!--        --><?php ///** @see FicheMetierController::graphiqueApplicationsAction() */ ?>
<!--        <a href="--><?php //echo $this->url('fiche-metier-type/graphique-applications', ['fiche-metier' => $fichemetier->getId(), 'agent' => ($agent)?$agent->getId():null], [], true); ?><!--"-->
<!--           class="btn btn-primary action ajax-modal"-->
<!--        >-->
<!--            <span class="icon icon-diagramme"></span>-->
<!--            Afficher les applications-->
<!--        </a>-->
<?php //endif; ?>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
