<?php

use Application\Entity\Db\FichePoste;
use Application\Provider\Etat\FichePosteEtats;
use Application\Provider\Privilege\FichePostePrivileges;
use Structure\Entity\Db\Structure;

/**
 * @see \Application\View\Helper\FichesPostesAsArrayViewHelper
 * @var FichePoste[] $fiches
 * @var boolean[] $displays
 * @var Structure|null $structure
 */

$canAjouter     = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AJOUTER));
$canVoir        = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER));

$canDetruire    = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_DETRUIRE));

$retour = null;
if (isset($options['retour'])) $retour = $options['retour'];

if ($retour)    $query['retour'] = $retour;

?>


<table class="table table-condensed table-hover datatable">
    <thead>
    <tr>
        <?php if ($displays['id']) : ?>
            <th> Id </th>
        <?php endif; ?>
        <?php if ($displays['agent']) : ?>
            <th> Agent </th>
        <?php endif; ?>
        <?php if ($displays['structure']) : ?>
            <th> Structure(s) </th>
        <?php endif; ?>
        <?php if ($displays['poste']) : ?>
            <th> Poste </th>
        <?php endif; ?>
        <?php if ($displays['fiche-principale']) : ?>
            <th> Fiche principale </th>
        <?php endif; ?>
        <?php if ($displays['en-cours'] AND $displays['validite']) : ?>
            <th style="min-width: 8rem;width: 8rem;"> Validité </th>
        <?php endif; ?>
        <?php if ($displays['modification']) : ?>
            <th> Modification </th>
        <?php endif; ?>
        <?php if ($displays['etat']) : ?>
            <th style="min-width: 5rem;width: 5rem;"> État </th>
        <?php endif; ?>
        <?php if ($displays['action']) : ?>
            <th class="cell-action" style="width: 11rem;"> Action </th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($fiches as $fiche) : ?>
        <?php
        if ($fiche instanceof FichePoste) {
            $id = $fiche->getId();
            $etat = $fiche->getEtat()->getCode();
            $destruction = $fiche->getHistoDestruction();
            $agentId = ($fiche->getAgent())?$fiche->getAgent()->getId():null;
            $agent = ($fiche->getAgent())?$fiche->getAgent()->getDenomination():null;
            $structureId = ($fiche->getAgent() AND $fiche->getAgent()->getAffectationPrincipale())?$fiche->getAgent()->getAffectationPrincipale()->getStructure()->getId():null;
            $structure = ($fiche->getAgent() AND $fiche->getAgent()->getAffectationPrincipale())?$fiche->getAgent()->getAffectationPrincipale()->getStructure()->getLibelleCourt():null;
            $fichePrincipale = ($fiche->toStringFicheMetierPrincipal() !== '')?$fiche->toStringFicheMetierPrincipal():null;
            $ficheLibelle = ($fiche->getLibelle() !== '')?$fiche->getLibelle():null;
            $isEnCours = $fiche->isEnCours();

            $canAfficher    = $this->isAllowed($fiche,FichePostePrivileges::FICHEPOSTE_AFFICHER);
            $canExporter    = $canAfficher;
            $canModifier    = $this->isAllowed($fiche,FichePostePrivileges::FICHEPOSTE_MODIFIER);
            $canHistoriser  = $this->isAllowed($fiche,FichePostePrivileges::FICHEPOSTE_HISTORISER);
            $canDetruire    = $this->isAllowed($fiche,FichePostePrivileges::FICHEPOSTE_DETRUIRE);

        } else {
            $id = $fiche['id'];
            $etat = $fiche['etat_code'];
            $destruction = $fiche['histo_destruction'];
            $agentId = $fiche['agent_id'];
            $agent = $fiche['prenom'] . " " . $fiche['nom_usage'];
            $structureId = $fiche['structure_id'];
            $structure = $fiche['structure'];
            $fichePrincipale = $fiche['fiche_principale'];
            $ficheLibelle = $fiche['fiche_libelle'];
            $isEnCours = ($fiche['en_cours'] === true) ? true : false;

            $canAfficher   = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER));
            $canExporter   = $canAfficher;
            $canModifier   = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));;
            $canHistoriser = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_HISTORISER));;
            $canDetruire   = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_DETRUIRE));;
        }

        ?>
        <?php if ($etat !== FichePosteEtats::ETAT_CODE_MASQUEE AND $canAfficher) : ?>
            <tr class="
                <?php if ($destruction !== null) echo ' historise '; ?>
                <?php if ($isEnCours === false AND $displays['validite']) echo ' termine '; ?>
            ">
                <?php if ($displays['id']) : ?>
                    <td>
                        <?php echo $id; ?>
                    </td>
                <?php endif; ?>
                <?php if ($displays['agent']) : ?>
                    <td>
                        <?php if ($agentId !== null ) : ?>
                            <?php echo $agent; ?>
                        <?php else : ?>
                            <span class="probleme">
                               <span class="icon icon-attention"></span>
                                Aucun agent
                            </span>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
                <?php if ($displays['structure']) : ?>
                    <td>
                        <?php if ($structure !== null ) : ?>
                            <?php echo $structure ?>
                        <?php else : ?>
                            <span class="probleme">
                               <span class="icon icon-attention"></span>
                                Aucune structure
                            </span>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>

                <?php if ($displays['poste']) : ?>
                    <td>
                        <?php if ($fiche->getPoste()) : ?>
                            <?php echo $fiche->getPoste()->getStructure()->getLibelleCourt(); ?>
                             -
                            <?php echo $fiche->getPoste()->getNumeroPoste(); ?>
                        <?php else : ?>
                            <span class="probleme">
                               <span class="icon icon-attention"></span>
                                Aucun poste
                            </span>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>

                <?php if ($displays['fiche-principale']) : ?>
                    <td>
                        <?php if ($fichePrincipale) : ?>
                            <?php echo $fichePrincipale; ?>
                            <?php if ($ficheLibelle !== null) : ?>
                                <br/>
                                <?php echo $ficheLibelle; ?>
                            <?php endif; ?>
                        <?php else :?>
                            <span class="probleme">
                               <span class="icon icon-attention"></span>
                                Aucun métier principal
                            </span>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
                <?php if ($displays['en-cours'] AND $displays['validite']) : ?>
                    <td style="text-align: center;">
                        <?php if ($etat === FichePosteEtats::ETAT_CODE_SIGNEE) : ?>
                            <?php if ($isEnCours) : ?>
                                <span class="icon icon-checked" style="color:darkgreen;" title="Fiche en cours de validité"></span>
                            <?php else : ?>
                                <?php if ($fiche instanceof FichePoste) : ?>
                                    <span style="color:darkred;"><?php echo $fiche->getFinValidite()->format('d/m/Y'); ?></span>
                                <?php else : ?>
                                    <span class="icon icon-retirer" style="color: darkred;" title="Fiche plus valide (remplacée)"></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php else : ?>
                            <span class="icon sursis" style="color:cadetblue;" title="Fiche non totalement validée"></span>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>

                <?php if ($displays['modification']) : ?>
                    <td>
                            <?php echo $fiche->getHistoModificateur()->getDisplayName(); ?> <br/>
                            <?php echo $fiche->getHistoModification()->format('d/m/Y à H:i:s'); ?>
                    </td>
                <?php endif; ?>

                <?php if ($displays['etat']) : ?>
                    <td>
                            <?php echo $this->etatbadge($etat); ?>
                    </td>
                <?php endif; ?>

                <?php if ($displays['action']) : ?>
                    <td>
                        <!--  AFFICHAGE ------------------------------------------------------------------------------->
                        <?php if ($canAfficher) : ?>
                            <?php /** @see \Application\Controller\FichePosteController::afficherAction() */ ?>
                            <a href="<?php echo $this->url('fiche-poste/afficher', ['fiche-poste' => $id], [], true); ?>"
                                    target="_blank"
                            ><span class="icon icon-voir"
                                   data-bs-toggle="tooltip" data-bs-html="true"
                                   title="Afficher la fiche de poste"></span></a>
                        <?php else : ?>
                            <span class="icon icon-voir nope" ></span>
                        <?php endif; ?>

                        <!--  EXPORTATION ----------------------------------------------------------------------------->
                        <?php if ($canExporter) : ?>
                            <?php /** @see \Application\Controller\FichePosteController::exporterAction() */ ?>
                            <a href="<?php echo $this->url('fiche-poste/exporter', ['fiche-poste' =>  $id], [], true); ?>"
                               target="_blank"
                            ><span
                                        data-bs-toggle="tooltip" data-bs-html="true"
                                        title="Exporter en PDF la fiche de poste"
                                        class="icon icon-pdf"></span><span class="lettrine">P</span></a>
                        <?php else : ?>
                            <span class="icon icon-pdf nope" ></span><span class="lettrine nope">P</span>
                        <?php endif; ?>

                        <!-- MODIFICATION ----------------------------------------------------------------------------->
                        <?php if ($canModifier) : ?>
                            <?php /** @see \Application\Controller\FichePosteController::editerAction() */ ?>
                            <a href="<?php echo $this->url('fiche-poste/editer', ['fiche-poste' =>  $id], ['query' => ['structure' =>  $structureId??null]], true); ?>"
                                    target="_blank"
                            ><span class="icon icon-editer"
                                   data-bs-toggle="tooltip" data-bs-html="true"
                                   title="Modifier la fiche de poste"></span></a>
                        <?php else : ?>
                            <span class="icon icon-editer" style="color:lightgrey;"></span>
                        <?php endif; ?>

                        <!-- HISTORISER ------------------------------------------------------------------------------->
                        <?php if ($canHistoriser) : ?>
                            <?php if ($destruction === null) : ?>
                                <?php /** @see \Application\Controller\FichePosteController::historiserAction() */ ?>
                                <a href="<?php echo $this->url('fiche-poste/historiser', ['fiche-poste' =>  $id], ["query" => $query], true); ?>">
                                    <span class="icon icon-historiser"
                                       data-bs-toggle="tooltip" data-bs-html="true"
                                       title="Historiser la fiche de poste"></span></a>
                            <?php else : ?>
                                <?php /** @see \Application\Controller\FichePosteController::restaurerAction() */ ?>
                                <a href="<?php echo $this->url('fiche-poste/restaurer', ['fiche-poste' =>  $id], ["query" => $query], true); ?>">
                                            <span class="icon icon-restaurer"
                                                  data-bs-toggle="tooltip" data-bs-html="true"
                                                  title="Restaurer la fiche de poste"></span></a>
                            <?php endif; ?>
                        <?php else : ?>
                            <?php if ($destruction === null) : ?>
                                <span class="icon icon-historiser nope"></span>
                            <?php else : ?>
                                <span class="icon icon-restaurer nope"></span>
                            <?php endif; ?>
                        <?php endif; ?>

                        <!-- DETRUIRE ------------------------------------------------------------------------------->
                        <?php if ($canDetruire) : ?>
                            <?php /** @see \Application\Controller\FichePosteController::detruireAction() */ ?>
                            <a href="<?php echo $this->url('fiche-poste/detruire', ['fiche-poste' =>  $id], [], true); ?>"
                               class="ajax-modal" data-event="modification"
                        ><span class="icon icon-retirer"
                               data-bs-toggle="tooltip" data-bs-html="true"
                               title="Supprimer la fiche de poste"></span></a>
                        <?php else : ?>
                            <span class="icon icon-retirer nope"></span>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
    </tbody>
</table>

<style>
    span.nope { color: lightgrey; }
</style>