<?php

use Application\Controller\FicheMetierController;
use Application\Entity\Db\Application;
use Application\Entity\Db\Competence;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FicheMetierTypeActivite;
use Application\Entity\Db\FichePoste;
use Application\Entity\Db\FicheposteActiviteDescriptionRetiree;
use Application\Entity\Db\FicheposteApplicationRetiree;
use Application\Entity\Db\FicheposteCompetenceRetiree;
use Application\Entity\Db\ParcoursDeFormation;

/**
 * @var FicheMetier $fichemetier
 * @var FichePoste $ficheposte
 */


$metier = $fichemetier->getMetier();
/**
 * @var FicheMetierTypeActivite[] $activites
 */
$activites = $fichemetier->getActivites();
usort($activites, function (FicheMetierTypeActivite $a, FicheMetierTypeActivite $b) { return $a->getPosition() > $b->getPosition();});

$activitesListe = [];
if (isset($options['activite-liste'])) {
    $activitesListe = explode(';', $options['activite-liste']);
} else {
    foreach ($activites as $activite) $activitesListe[] = $activite->getActivite()->getId();
}

$sansTitre = false;
if (isset($options['sans-titre'])) $sansTitre = ($options['sans-titre'] === true);

$parcours = (isset($options['parcours']))?$options['parcours']:null;

$a=1;
?>

<?php if ($sansTitre !== true) : ?>
    <div class="row">
        <div class="col-md-8">
            <h1 class="page-header">
                Fiche métier #<?php echo $fichemetier->getId(); ?> <br/>
                <strong><?php echo $metier->getLibelle(); ?></strong>
            </h1>
        </div>
        <div class="col-md-4">
            <?php if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier') : ?>
                <br/>
                <br/>
                <br/>
            <div class="pull-right" style="margin-right:1rem;">
                <?php /** @see FicheMetierController::editerLibelleAction() */ ?>
                <a  class="btn btn-primary action ajax-modal pull-right"
                    data-event="modification"
                    href="<?php echo $this->url('fiche-metier-type/editer-libelle', ['id' => $fichemetier->getId()], [] , true); ?>">
                    <span class="icon editer"></span>
                    Modifier libellé
                </a>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <div class="row">
    <div class="col-md-8">
    <?php if ($fichemetier->hasExpertise()) : ?>
        <span class="label" style="background-color: darkgreen;"> Expertise </span>
    <?php else: ?>
        <span class="label" style="background-color: darkred;"> Pas d'expertise </span>
    <?php endif; ?>

        &nbsp;

    <?php if ($metier) : ?>
        <?php foreach($metier->getReferences() as $reference) : ?>
            <span class="badge" style="background-color: #dfc4b2"><a href="<?php echo $reference->getUrl(); ?>"> <?php echo $reference->getTitre(); ?> </a></span>
        <?php endforeach; ?>
    <?php endif; ?>
    </div>
    <div class="col-md-4">
        <div class="pull-right" style="margin-right:1rem;">
            <?php if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier') : ?>
                <a
                    <?php /** @see FicheMetierController::changerExpertiseAction() */?>
                    href="<?php echo $this->url('fiche-metier-type/changer-expertise', ['fiche' => $fichemetier->getId()], [], true); ?>"
                    class="btn btn-primary action"
                >
                    <?php if ($fichemetier->hasExpertise()) : ?>
                        <span class="icon retirer"></span>
                        Retirer expertise
                    <?php else: ?>
                        <span class="icon ajouter"></span>
                        Ajouter expertise
                <?php endif; ?>
                </a>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endif; ?>
<br/>

<div class="main">

<!-- LIENS REFERENCE -------------------------------------------------------------------------------------------------->



<!-- MISSIONS PRINCIPALE ---------------------------------------------------------------------------------------------->

    <h2> Missions principales</h2>
    <?php $nb = 0; ?>

    <ul>
        <?php foreach ($activites as $activite) : ?>
            <?php if (array_search($activite->getActivite()->getId(), $activitesListe) !== false) : ?>
                <li>
                    <?php
                        $nb += 1;
                        echo $activite->getActivite()->getLibelle();
                    ?>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>

<!-- ACTIVITES ASSOCIEES ------------------------------------------------------------------------------------------>
<div class="main">
    <div class="row">
        <div class="col-md-5">
            <h2>
                Activités associées
                <span class="badge"> <?php echo $nb; ?>/<?php echo count($activites); ?> </span>
            </h2>
        </div>
        <div class="pull-right" style="margin-right:1rem;">
            <br/>
            <?php if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier') : ?>
                <?php /** @see FicheMetierController::ajouterNouvelleActiviteAction() */ ?>
                <a  class="btn btn-primary action ajax-modal pull-right"
                    href="<?php echo $this->url('fiche-metier-type/ajouter-nouvelle-activite', ['id' => $fichemetier->getId()], [] , true); ?>"
                    data-event="modification"
                >
                    <span class="icon ajouter"></span>
                    Ajouter une nouvelle activité
                </a>
                <?php /** @see FicheMetierController::ajouterActiviteExistanteAction() */ ?>
                <a  class="btn btn-primary action ajax-modal pull-right"
                    data-event="modification"
                    href="<?php echo $this->url('fiche-metier-type/ajouter-activite-existante', ['id' => $fichemetier->getId()], [] , true); ?>">
                    <span class="icon selectionner"></span>
                    Ajouter une activité existante
                </a>
            <?php endif; ?>
        </div>
    </div>

    <?php foreach ($activites as $ficheActivite): ?>
        <?php if (array_search($ficheActivite->getActivite()->getId(), $activitesListe) !== false) : ?>
            <?php
                $retirees = [];
                if ($ficheposte) {
                    $allRetirees = $ficheposte->getDescriptionsRetirees();
                    /** @var FicheposteActiviteDescriptionRetiree $retiree */
                    foreach ($allRetirees as $retiree) {
                        if ($retiree->getHistoDestruction() === null AND $retiree->getActivite() === $activite->getActivite()) $retirees[] = $retiree;
                    }
                }
            ?>
            <?php echo $this->activite($ficheActivite, $options['mode'], ['ficheposte' => $ficheposte, 'fichemetier' => $fichemetier, 'retirees' => $retirees]); ?>
        <?php endif; ?>
    <?php endforeach;?>
</div>

<!-- AUTRE INFO --------------------------------------------------------------------------------------------------->

<?php if ($ficheposte === null) : ?>
    <div class="main">
        <h2>
            Parcours de formation pour la prise de poste
        </h2>

        <!-- COMPETENCES -------------------------------------------------------------------------------------------------->

        <?php /** @var Competence $competence */ ?>
        <?php
        $dictionnaireCompetence = [];
        foreach($fichemetier->getCompetences() as $competence) {
            if ($ficheposte === null) {
                $dictionnaireCompetence[$competence->getId()]['competence'] = $competence;
                $dictionnaireCompetence[$competence->getId()]['source'][]  = 'fiche|'. $metier->getLibelle();
            }
            else {
                $conservees = $ficheposte->getCompetencesRetirees();
                $found = null;
                /** @var FicheposteCompetenceRetiree $conservee */
                foreach ($conservees as $conservee) {
                    if ($conservee->getHistoDestruction() === null AND $conservee->getCompetence() === $competence) {
                        $found = $conservee;
                        break;
                    }
                }
                if ($found === null) {
                    $dictionnaireCompetence[$competence->getId()]['competence'] = $competence;
                    $dictionnaireCompetence[$competence->getId()]['source'][] = 'fiche|'. $metier->getLibelle();
                }
            }
        }
        foreach($fichemetier->getActivites() as $element) {
            if (array_search($element->getActivite()->getId(), $activitesListe) !== false) {
                foreach ($element->getActivite()->getCompetences() as $competence) {
                    $dictionnaireCompetence[$competence->getId()]['competence'] = $competence;
                    $dictionnaireCompetence[$competence->getId()]['source'][] = 'activite|' . $element->getActivite()->getLibelle();
                }
            }
        }
        ?>

        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            <span class="icon competence"></span>
                            Compétences
                            <span class="badge">
                                <?php echo count($dictionnaireCompetence); ?>
                            </span>
                        </h2>
                    </div>
                    <?php if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier') : ?>
                        <div class="pull-right" style="margin-right:1rem;">
                            <?php /** @see FicheMetierController::gererCompetencesAction() */ ?>
                            <a href="<?php echo $this->url('fiche-metier-type/gerer-competences', ['fiche' => $fichemetier->getId()], [], true); ?>"
                               class="btn btn-primary action ajax-modal"
                               data-event="modification"
                            >
                                <span class="icon ajouter"></span>
                                Gérer les compétences
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php echo $this->competences($dictionnaireCompetence, ['type' => false, 'theme' => false]); ?>
                </div>
            </div>
        </div>

        <!-- APPLICATION -------------------------------------------------------------------------------------------------->

        <?php /** @var Application $application */ ?>
        <?php
        $dictionnaireApplication = [];
        foreach($fichemetier->getApplications() as $application) {
            if ($ficheposte === null) $dictionnaireApplication[$application->getLibelle()][] = 'fiche|'. $metier->getLibelle();
            else {
                $conservees = $ficheposte->getApplicationsRetirees();
                $found = null;
                /** @var FicheposteApplicationRetiree $conservee */
                foreach ($conservees as $conservee) {
                    if ($conservee->getHistoDestruction() === null AND $conservee->getApplication() === $application) {
                        $found = $conservee;
                        break;
                    }
                }
                if ($found === null) {
                    $dictionnaireApplication[$application->getLibelle()][] = 'fiche|'. $metier->getLibelle();
                }
            }
        }
        foreach($fichemetier->getActivites() as $element) {
            if (array_search($element->getActivite()->getId(), $activitesListe) !== false) {
                foreach ($element->getActivite()->getApplications() as $application) {
                    $dictionnaireApplication[$application->getLibelle()][] = 'activite|' . $element->getActivite()->getLibelle();
                }
            }
        }
        ?>

        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-8">
                        <h2>
                            <span class="icon application"></span>
                            Applications
                            <span class="badge">
                                <?php echo count($dictionnaireApplication); ?>
                            </span>
                        </h2>
                    </div>
                    <?php if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier'): ?>
                    <div class="pull-right" style="margin-right:1rem;">
                        <?php /** @see FicheMetierController::modifierApplicationAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier-type/modifier-application', ['id' => $fichemetier->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="modification"
                        >
                            <span class="icon ajouter"></span>
                            Gérer les applications
                        </a>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="panel-body">
                <ul>
                    <?php ksort($dictionnaireApplication); ?>
                    <?php foreach($dictionnaireApplication as $application => $source) : ?>
                        <li>
                            <?php echo $application; ?>
                            <sup>
                                <?php foreach($source as $item) : ?>
                                    <?php $split = explode('|', $item); ?>
                                    <?php if($split[0] === 'fiche') : ?>
                                        <span class="fiche-metier" title="Associée à la fiche métier [<?php echo $split[1]; ?>]">F</span>
                                    <?php endif; ?>
                                    <?php if($split[0] === 'activite') : ?>
                                        <span class="activite" title="Associée à l'activité [<?php echo $split[1]; ?>]">A</span>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </sup>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

        <!-- FORMATION ---------------------------------------------------------------------------------------------------->

<!--        --><?php ///** @var Formation $formation */ ?>
<!--        --><?php
//        $dictionnaireFormation = [];
//        foreach($fichemetier->getFormations() as $formation) {
//            if ($ficheposte === null) $dictionnaireFormation[$formation->getLibelle()][] = 'fiche|'. $metier->getLibelle();
//            else {
//                $conservees = $ficheposte->getFormationsRetirees();
//                $found = null;
//                /** @var FicheposteFormationRetiree $conservee */
//                foreach ($conservees as $conservee) {
//                    if ($conservee->getHistoDestruction() === null AND $conservee->getFormation() === $formation) {
//                        $found = $conservee;
//                        break;
//                    }
//                }
//                if ($found === null) {
//                    $dictionnaireFormation[$formation->getLibelle()][] = 'fiche|'. $metier->getLibelle();
//                }
//            }
//        }
//        foreach($fichemetier->getActivites() as $element) {
//            if (array_search($element->getActivite()->getId(), $activitesListe) !== false) {
//                foreach ($element->getActivite()->getFormations() as $formation) {
//                    $dictionnaireFormation[$formation->getLibelle()][] = 'activite|' . $element->getActivite()->getLibelle();
//                }
//            }
//        }
//        ?>

<!--        <div class="panel panel-info">-->
<!--            <div class="panel-heading">-->
<!--                <div class="row">-->
<!--                    <div class="col-md-8">-->
<!--                        <h2>-->
<!--                            <span class="icon formation"></span>-->
<!--                            Formations-->
<!--                            <span class="badge">-->
<!--                                --><?php //echo count($dictionnaireFormation); ?>
<!--                            </span>-->
<!--                        </h2>-->
<!--                    </div>-->
<!--                    --><?php //if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-metier') : ?>
<!--                    <div class="pull-right" style="margin-right:1rem;">-->
<!--                        --><?php ///** @see FicheMetierController::modifierFormationAction() */ ?>
<!--                        <a href="--><?php //echo $this->url('fiche-metier-type/modifier-formation', ['id' => $fichemetier->getId()], [], true); ?><!--"-->
<!--                           class="btn btn-primary action ajax-modal"-->
<!--                           data-event="modification"-->
<!--                        >-->
<!--                            <span class="icon ajouter"></span>-->
<!--                            Gérer les formations-->
<!--                        </a>-->
<!--                    </div>-->
<!--                    --><?php //endif; ?>
<!--                </div>-->
<!--            </div>-->
<!--            <div class="panel-body">-->
<!--                <ul>-->
<!--                    --><?php //ksort($dictionnaireFormation); ?>
<!--                    --><?php //foreach($dictionnaireFormation as $formation => $source) : ?>
<!--                        <li>-->
<!--                            --><?php //echo $formation; ?>
<!--                            <sup>-->
<!--                                --><?php //foreach($source as $item) : ?>
<!--                                    --><?php //$split = explode('|', $item); ?>
<!--                                    --><?php //if($split[0] === 'fiche') : ?>
<!--                                        <span class="fiche-metier" title="Associée à la fiche métier [--><?php //echo $split[1]; ?><!--]">F</span>-->
<!--                                    --><?php //endif; ?>
<!--                                    --><?php //if($split[0] === 'activite') : ?>
<!--                                        <span class="activite" title="Associée à l'activité [--><?php //echo $split[1]; ?><!--]">A</span>-->
<!--                                    --><?php //endif; ?>
<!--                                --><?php //endforeach; ?>
<!--                            </sup>-->
<!--                        </li>-->
<!--                    --><?php //endforeach; ?>
<!--                </ul>-->
<!--            </div>-->
<!--        </div>-->

        <!-- Parcours de formations -->
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2>
                    <span class="icon formation"></span>
                    Parcours de formation
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <?php if ($parcours[ParcoursDeFormation::TYPE_CATEGORIE] AND !empty($parcours[ParcoursDeFormation::TYPE_CATEGORIE])) : ?>
                            <?php foreach ($parcours[ParcoursDeFormation::TYPE_CATEGORIE] as $categorieId => $parcour) : ?>
                                <?php echo $this->parcoursDeFormation($parcour, $options); ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <span class="icon attention">Pas de parcours de formation associé à la catégorie <?php echo $fichemetier->getMetier()->getCategorie()->getLibelle(); ?>.</span>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-6">
                        <?php if ($parcours[ParcoursDeFormation::TYPE_METIER] AND !empty($parcours[ParcoursDeFormation::TYPE_METIER])) : ?>
                            <?php foreach ($parcours[ParcoursDeFormation::TYPE_METIER] as $metierId => $parcour) : ?>
                                <?php echo $this->parcoursDeFormation($parcour, $options); ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <span class="icon attention">Pas de parcours de formation associé au métier <?php echo $fichemetier->getMetier()->getLibelle(); ?>.</span>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });

</script>

<style>
    h2 {
        color: #3c6c8b;
        text-decoration: none;
        margin-bottom: 2rem;
    }
</style>