<?php

use Application\Controller\FicheMetierController;
use Application\Entity\Db\FicheMetier;
use Application\Entity\Db\FicheTypeExterne;

/**
 * @see \Application\View\Helper\FicheMetierViewHelper
 * @var FicheMetier|FicheTypeExterne $fichemetier
 * @var array $options
 */

$fiche = $fichemetier;
$remove = false;
if ($fichemetier instanceof FicheTypeExterne) {
    $remove = true;
    $fiche = $fichemetier->getFicheType();
}

$activites = $fiche->getActivites();

$sansTitre = (isset($options['sans-titre']) and $options['sans-titre']);
$mode = ($options['mode']) ?? "affichage";
if ($options['popup']) $options['actions']['afficher'] = false;

?>

<?php /** Watermark de l'identifiant de la fiche qui peut être utilisée pour des redirections **********************/ ?>
<span style="visibility:hidden;">
    Fiche métier #<?php echo $fiche->getId(); ?>
</span>

<?php /** FICHE || ENTETE *******************************************************************************************/ ?>

<?php if ($sansTitre !== true) : ?>
    <?php echo $this->ficheMetierEntete($fiche); ?>

    <hr/>

    <div>
        <?php if ($mode === 'edition-fiche-metier') : ?>
            <?php /** @see FicheMetierController::editerLibelleAction() */ ?>
            <a class="btn btn-primary action ajax-modal" data-event="modification"
               href="<?php echo $this->url('fiche-metier-type/editer-libelle', ['id' => $fiche->getId()], [], true); ?>">
                <span class="icon editer"></span>
                Modifier libellé
            </a>

            <a
                <?php /** @see FicheMetierController::changerExpertiseAction() */ ?>
                    href="<?php echo $this->url('fiche-metier-type/changer-expertise', ['fiche' => $fiche->getId()], [], true); ?>"
                    class="btn btn-primary action"
            >
                <?php if ($fiche->hasExpertise()) : ?>
                    <span class="icon retirer"></span>
                    Retirer expertise
                <?php else: ?>
                    <span class="icon ajouter"></span>
                    Ajouter expertise
                <?php endif; ?>
            </a>
        <?php endif; ?>
    </div>
<?php endif; ?>


<?php ///** FICHE || ACTIVITES / MISSIONS PRINCIPALES *****************************************************************/?>


<?php if (!$remove) : ?>
    <div class="panel panel-info">
    <div class="panel-heading">
        <h2>
            Missions principales
        </h2>
    </div>
    <div class="panel-body" style="color:rgb(80,80,80);">
<?php endif; ?>
        <div class="row">
            <?php if ($mode === 'edition-fiche-metier') : ?>
                <?php /** @see FicheMetierController::ajouterNouvelleActiviteAction() */ ?>
                <a class="btn btn-primary action ajax-modal pull-right"
                   href="<?php echo $this->url('fiche-metier-type/ajouter-nouvelle-activite', ['id' => $fiche->getId()], [], true); ?>"
                   data-event="modification"
                >
                    <span class="icon ajouter"></span>
                    Ajouter une nouvelle activité
                </a>
                <?php /** @see FicheMetierController::ajouterActiviteExistanteAction() */ ?>
                <a class="btn btn-primary action ajax-modal pull-right"
                   data-event="modification"
                   href="<?php echo $this->url('fiche-metier-type/ajouter-activite-existante', ['id' => $fiche->getId()], [], true); ?>">
                    <span class="icon selectionner"></span>
                    Ajouter une activité existante
                </a>
            <?php endif; ?>
        </div>

        <?php foreach ($activites as $activite): ?>
            <?php echo $this->activite($activite, $options['mode'], ['fichemetier' => $fiche]); ?>
        <?php endforeach; ?>

<?php if (!$remove) : ?>
        </div>
    </div>
<?php endif; ?>

<!-- COMPETENCES -------------------------------------------------------------------------------------------------->
<?php if (isset($options['competences'])) : ?>
    <?php $dictionnaireCompetence = $options['competences']; ?>
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-8">
                    <h2>
                        <span class="icon competence"></span>
                        Compétences
                        <span class="badge">
                                <?php echo count($dictionnaireCompetence); ?>
                            </span>
                    </h2>
                </div>
                <div class="pull-right">
                    <?php if ($options['popup'] !== true) : ?>
                        <?php /** @see FicheMetierController::graphiqueCompetencesAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier-type/graphique-competences', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                        >
                            <span class="icon graphique"></span>
                            Afficher les compétences
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="pull-right">
                    <?php if (isset($options['mode']) and $options['mode'] === 'edition-fiche-metier') : ?>
                        <?php /** @see \Application\Controller\CompetenceController::ajouterCompetenceElementAction() */ ?>
                        <a href="<?php echo $this->url('competence/ajouter-competence-element', ['type' => FicheMetier::class, 'id' => $fiche->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="modification"
                        >
                            <span class="icon ajouter"></span>
                            Ajouter une compétence
                        </a>
                    <?php endif; ?>

                </div>
            </div>
            <?php echo $this->competenceBloc($dictionnaireCompetence, $fiche,
                ['display' => ['titre' => false, 'validation' => false, 'raison' => false],
                    'actions' => $options['actions']]); ?>
        </div>
    </div>
<?php endif; ?>

<!-- APPLICATION -------------------------------------------------------------------------------------------------->
<?php if (isset($options['applications'])) : ?>
    <?php $dictionnaireApplication = $options['applications']; ?>
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-8">
                    <h2>
                        <span class="icon application"></span>
                        Applications
                        <span class="badge">
                                <?php echo count($dictionnaireApplication); ?>
                            </span>
                    </h2>
                </div>
                <div class="pull-right">
                    <?php if ($options['popup'] !== true) : ?>
                        <?php /** @see FicheMetierController::graphiqueApplicationsAction() */ ?>
                        <a href="<?php echo $this->url('fiche-metier-type/graphique-applications', ['fiche-metier' => $fiche->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                        >
                            <span class="icon graphique"></span>
                            Afficher les applications
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="pull-right">
                    <?php if (isset($options['mode']) and $options['mode'] === 'edition-fiche-metier'): ?>
                        <?php /** @see \Application\Controller\ApplicationController::ajouterApplicationElementAction() */ ?>
                        <a href="<?php echo $this->url('application/ajouter-application-element', ['type' => FicheMetier::class, 'id' => $fiche->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal"
                           data-event="modification"
                        >
                            <span class="icon ajouter"></span>
                            Ajouter une application
                        </a>
                    <?php endif; ?>
                </div>
            </div>

            <?php echo $this->applicationBloc($dictionnaireApplication, $fiche,
                ['display' => ['titre' => false, 'validation' => false, 'raison' => false],
                    'actions' => $options['actions']]); ?>
        </div>
    </div>
<?php endif; ?>

<!-- FORMATION ---------------------------------------------------------------------------------------------------->
<?php if (isset($options['parcours'])) : ?>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h2>
                <span class="icon formation"></span>
                Parcours de formation
            </h2>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <?php
                    $arrays = $options['parcours'];
                    ksort($arrays);
                    foreach ($arrays as $type => $array) : ?>
                        <?php $parcours = $array; ?>
                        <?php foreach ($parcours as $parcour) : ?>
                            <?php echo $this->parcoursDeFormation($parcour); ?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>

                    <?php echo $this->parcoursApplication($fiche); ?>
                </div>
            </div>

        </div>
    </div>
<?php endif; ?>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
