<?php

/**
 * @var FicheTypeExterne $fiche
 * @var array $options
 */

use Application\Entity\Db\FicheTypeExterne;
use Application\Provider\Privilege\FichePostePrivileges;
use FicheMetier\Entity\Db\MissionElement;

$fichemetier = $fiche->getFicheType();
$ficheposte = $fiche->getFichePoste();

$agent = $ficheposte->getAgent();

$activitesConservees = explode(FicheTypeExterne::ACTIVITE_SEPARATOR, $fiche->getMissions());
?>

<div class="card panel-info">
    <div class="card-header">
        <div class="row">
            <div class="col-md-5">
                <h2> <?php echo $fiche->getFicheType()->getLibelle(); ?> </h2>
            </div>
            <div class="col-md-7">
                <div class="col-md-6">
                    <u> Répartition par métier</u>
                    <?php if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-poste') : ?>
                        <a
                            <?php /** @see \Application\Controller\FichePosteController::modifierFicheMetierAction() */ ?>
                                href="<?php echo $this->url('fiche-poste/modifier-fiche-metier', ['fiche-poste' => $fiche->getFichePoste()->getId(), 'fiche-type-externe' => $fiche->getId()], [], true); ?>"
                                class="ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-editer" title="Modifier la fiche métier"></span></a>
                        <a
                            <?php /** @see \Application\Controller\FichePosteController::retirerFicheMetierAction() */ ?>
                                href="<?php echo $this->url('fiche-poste/retirer-fiche-metier', ['fiche-poste' => $fiche->getFichePoste()->getId(), 'fiche-type-externe' => $fiche->getId()], [], true); ?>"
                        >
                            <span class="icon icon-unchecked" title="Retirer la fiche métier"></span></a>
                    <?php endif; ?>
                    <ul>
                        <li>
                            <?php echo $fiche->getQuotite(); ?> %
                            <?php if ($fiche->getPrincipale()) : ?>
                                <strong>Principale</strong>
                            <?php endif ;?>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <?php if ($this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_GRAPHIQUE)) AND $agent) : ?>
            <div class="pull-right">
                <a href="<?php echo $this->url('graphique/competences', ['fiche-metier' => $fichemetier->getId(), 'agent' => $agent->getId()], [], true); ?>" class="btn btn-primary ajax-modal">Compétences métier/agent</a>
            </div>
        <?php endif; ?>
    </div>
    <div class="card-body">
<!--        --><?php //if (isset($options['mode']) AND $options['mode'] === 'edition-fiche-poste') : ?>
<!--            --><?php ///** @see \Application\Controller\FichePosteController::selectionnerActiviteAction() */ ?>
<!--            <a href="--><?php //echo $this->url("fiche-poste/selectionner-activite", ["fiche-poste" => $ficheposte->getId(), "fiche-type-externe" => $fiche->getId()], [], true); ?><!--"-->
<!--               class="ajax-modal btn btn-primary" data-event="modification"-->
<!--            >-->
<!--                Sélectionner des activités-->
<!--            </a>-->
<!--        --><?php //endif; ?>
        <?php
            //TODO retirer les missions retirées
            $missions  = $fichemetier->getMissions();
            $missionsConservees = $fiche->getMissions()?explode(";",$fiche->getMissions()):[];
            $missions = array_filter($missions, function (MissionElement $mission) use ($missionsConservees) {
                return in_array($mission->getMission()->getId(), $missionsConservees);
            });
        ?>
        <?php if (!empty($missions)) : ?>
            <h3> Missions </h3>
            <ul>
            <?php foreach ($missions as $mission) : ?>
                <li><?php echo $mission->getMission()->getLibelle(); ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <?php
            //TODO retirer les activités retirées
            $activites  = $fichemetier->getActivites(); ?>
        <?php if (!empty($activites)) : ?>
            <h3> Activités </h3>
            <ul>
                <?php foreach ($activites as $activite) : ?>
                    <li><?php echo $activite->getActivite()->getLibelle(); ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>