<?php

/**
 * @var FicheMetierEtat $etat
 */

use Application\Entity\Db\FicheMetierEtat;

?>

<span class="label <?php echo $etat->getCode(); ?>">
    <?php echo $etat->getLibelle(); ?>
</span>

<style>
    span.label.REDACTION {
        background-color: darkorange;
    }

    span.label.VALIDE {
        background-color: darkgreen;
    }

    span.label.SECRET {
        background-color: hotpink;
    }
</style>
