<?php

use Application\Controller\ElementController;
use Application\Entity\Db\CompetenceType;
use Application\View\Helper\CompetenceBlocViewHelper;
use Formation\Entity\Db\Formation;
use Formation\Entity\Db\FormationElement;
use Formation\Entity\Db\Interfaces\HasFormationCollectionInterface;

/**
 * @see \Application\View\Helper\FormationBlocViewHelper
 * @var array $formations
 * @var HasFormationCollectionInterface $objet
 * @var array $options
 *
 * la sutrcture de application est la suivante :
 *
 * $applications = [
 *      ID => [
 *          'entite' => Application,
 *          'display' => true|false,
 *          'raison' => [
 *                  [ 'source', SourceEntity ],
 *                  [ 'source', SourceEntity ],
 *                  ...
 *              ]
 *          ],
 *      ...
 *  ]
 */

$canAfficher        = (CompetenceBlocViewHelper::isActionActivee($options, 'afficher') AND true);
$canAjouter         = (CompetenceBlocViewHelper::isActionActivee($options, 'ajouter') AND true);
$canModifier        = (CompetenceBlocViewHelper::isActionActivee($options, 'modifier') AND true);
$canSupprimer       = (CompetenceBlocViewHelper::isActionActivee($options, 'supprimer') AND true);
$canValider         = (CompetenceBlocViewHelper::isActionActivee($options, 'valider') AND true);

$displayTitre       = CompetenceBlocViewHelper::isDisplayed($options,'titre');
$displayValidation  = CompetenceBlocViewHelper::isDisplayed($options,'validation');

$groupes = [];
$sansGroupe = "zzz";
foreach ($formations as $item) {
    /** @var Formation $formation */
    $entite = $item['entite'];
    $formation = $entite;
    if ($entite instanceof FormationElement) $formation = $entite->getFormation();
    if ($formation) {
        $libelleGroupe = ($formation->getGroupe()) ? $formation->getGroupe()->getLibelle() : $sansGroupe;
        if ($item['conserve'] === true) $groupes[$libelleGroupe][] = $item;
    }
}

ksort($groupes);

?>

<!-- TITRE DU BLOC ---------------------------------------------------------------------------------------------------->

<?php if ($displayTitre) : ?>
<div class="titre">
    <div class="row">
        <div class="col-md-8" style="border-bottom: 1px solid #31708f">
            <h3> <span class="icon formation"></span> Formations </h3>
        </div>
        <div class="pull-right">
            <?php if ($canAjouter) : ?>
                <br/>
                <a
                    <?php /** @see \Formation\Controller\FormationController::ajouterFormationElement() */?>
                        <?php //todo provient de agent-fomation ... ?>
                        href="<?php
                            //echo $this->url('competence/ajouter-competence-element', ['type' => Agent::class, 'id' => $objet->getId(), 'clef' => ($objet instanceof FicheMetier)?'afficher':'masquer'], [], true);
                            echo $this->url('agent/ajouter-formation', ['agent' => $objet->getId()], [], true);
                        ?>"
                        class="ajax-modal btn btn-primary action"
                        data-event="modification"
                >
                    <span class="icon ajouter" title="Ajouter une formation"></span>
                    Ajouter une formation
                </a>
            <?php endif; ?>
        </div>
    </div>
    <br/>
</div>
<?php endif; ?>

<div class="listing">
    <table class="listing">
    <?php foreach ($groupes as $libelle => $groupe) : ?>
        <?php if ($groupe !== null AND !empty($groupe)) : ?>
            <tr>
                <th colspan="5">
                    <?php echo $libelle; ?>
                </th>
            </tr>
            <?php usort($groupe, function ($a, $b) { return $a['entite']->getLibelle() > $b['entite']->getLibelle(); }); ?>
            <?php foreach ($groupe as $element) : ?>
                <?php
                    $entite = $element['entite'];
                    $formation = $entite;
                    $isClef = false;
                    if ($formation instanceof FormationElement) {
                        $formation = $formation->getFormation();
                    }
                ?>
                <tr>
                    <td class="libelle">
                        <?php echo $formation->getLibelle(); ?>
                        <?php echo $this->raisons($element['raison']); ?>
                    </td>
                    <td class="niveau">
                        <?php if ($entite instanceof FormationElement) : ?>
                            <?php echo explode(" - ",$entite->getCommentaire())[0]; ?>
                        <?php endif; ?>
                    </td>
                    <td class="clef">
                    </td>
                    <?php if ($displayValidation) : ?>
                        <td class="validation">
                            <?php if ($entite instanceof FormationElement) : ?>
                                <?php echo $this->validationBadge($entite->getValidation(),$options); ?>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                    <td class="action">
                        <?php if ($entite instanceof FormationElement) : ?>
                            <?php if ($canAfficher) : ?>
                                <a  <?php /** @see \Application\Controller\ElementController::afficherAction() */ ?>
                                    href="<?php echo $this->url("element/afficher", ['type' => ElementController::TYPE_FORMATION, 'id' => $entite->getId()], [], true); ?>"
                                    class="ajax-modal" data-toggle="tooltip" data-html="true"
                                    title="Afficher l'application <span class='highlight formation'><?php echo $entite->getLibelle(); ?></span>">
                                <span class="icon voir"></span></a>
                            <?php endif; ?>
                            <?php if ($canModifier) : ?>
                                <a <?php /** TODO provient de l'ancien agent-formation  */?>
                                    <?php /** @see \Application\Controller\AgentController::modifierFormationAction() */?>
                                        href="<?php echo $this->url('agent/modifier-formation', ['formation-element' => $entite->getId(), 'agent' => $objet->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                >
                                    <span class="icon editer" title="Modifier une formation liée à l'agent"></span></a>
                            <?php endif; ?>
                            <?php if ($canSupprimer) : ?>
                                <a
                                    <?php /** @see \Application\Controller\ElementController::supprimerAction() */?>
                                        href="<?php echo $this->url('element/supprimer', ['type' => ElementController::TYPE_FORMATION, 'id' => $entite->getId()], [], true); ?>"
                                        class="ajax-modal"
                                        data-event="modification"
                                >
                                    <span class="icon detruire" title="Supprimer définitivement une formation liées à l'agent"></span>
                                </a>
                            <?php endif; ?>
                            <?php if ($canValider) : ?>
                                <?php if ($entite->getValidation() === null) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\AgentController::validerElementAction() */ ?>
                                            href="<?php echo $this->url('agent/valider-element', ['type' => "AgentFormation", 'id' => $entite->getId()], [], true); ?>"
                                            class="ajax-modal" data-event="modification"
                                    >
                                        <span class="icon validation-do" title="Valider la formation"></span></a>
                                <?php else: ?>
                                    <a
                                        <?php /** @see \Application\Controller\AgentController::revoquerElementAction() */ ?>
                                            href="<?php echo $this->url('agent/revoquer-element', ['validation' => $entite->getValidation()->getId()], ['query' => ['retour' => $options['retour']]], true); ?>"
                                    >
                                        <span class="icon validation-undo" title="Dévalider la formation"></span></a>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif; ?>

                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</table>
</div>




