<?php

use Application\Entity\Db\Agent;
use Element\Entity\Db\Application;
use Formation\Entity\Db\Formation;

/**
 * @see \Application\View\Helper\ParcoursDeFormationViewHelper
 * @var Application[] $applications
 * @var Formation[] $formations
 * @var Agent $agent
 * @var array $option
 */

/** Dans le tableau options, on retrouve une clef 'mode'.
 *  Si cette clef est omise alors la valeur par défaut "affichage" est utilisée.
 *  Valeur possible :
 *  - "affichage" ne fait que l'affichage (aucune interaction possible)
 *      >> Si un agent est renseigné affiche le "statut" du parcours de formation
 *  - "création" permet d'ajouter ou de retirer des formations au parcours
 *  - "modification" permet de valider le suivi d'une formations du parcours
 *      >> Si un agent est renseigné affiche le "statut" du parcours de formation
 */

$modesAutorises = ['affichage', 'creation', 'modification'];
$nogroup = "Sans Groupe";

/** Tri pour bonne affichage ******************************************************************************************/
$applicationsArray = [];
foreach ($applications as $application) {
    $groupe = ($application->getGroupe())?$application->getGroupe()->getLibelle():$nogroup;
    $applicationsArray[$groupe][] = $application;
}

ksort($applicationsArray);

?>

<?php /** Récupération du mode ****************************************************************************************/
    $mode = (isset($options['mode']))?$options['mode']:"affichage";
?>

<?php if (!in_array($mode, $modesAutorises)) : ?>
<div class="alert alert-danger">
    Le <strong>mode</strong> [<?php echo $mode; ?>] est non géré par l'aide de vue [ParcoursDeFormationViewHelper].
</div>
<?php endif; ?>

<?php /** Récupération du droit associé à la modification *************************************************************/
    $canModifier = $options['modification'] ?? false;
?>

<div class="parcours">

    <div class="listing">
        <table>
            <?php foreach($applicationsArray as $groupe => $applicationArray) : ?>
                <?php usort($applicationArray, function ($a, $b) {return $a->getLibelle() > $b->getLibelle();}); ?>
                    <tr>
                        <th colspan="2">
                            <?php echo $groupe; ?>
                        </th>
                    </tr>
                    <?php  foreach($applicationArray as $application) : ?>
                        <tr>
                            <td class="libelle">
                                <?php echo $application->getLibelle(); ?>
                            </td>
                            <td class="validation">
                                <?php $hasApplication = ($agent)?$agent->hasApplication($application):null; ?>
                                <?php if ($hasApplication === null) : ?>
                                    <?php if ($canModifier) : ?>
                                        <a
                                            <?php /** @see \Application\Controller\ApplicationController::ajouterApplicationElementAction() */?>
                                                href="<?php echo $this->url('application/ajouter-application-element', ['type' => Agent::class, 'id' => $agent->getId(), 'clef' => 'masquer'], ["query" => ['application' => $application->getId()]], true); ?>"
                                                class="ajax-modal"
                                                data-event="modification"
                                        >
                                            <span class="icon icon-ajouter"
                                                  data-bs-toggle="tooltip" data-bs-html="true"
                                                  title="Ajouter une application"
                                            ></span>
                                        </a>
                                    <?php endif; ?>
                                <?php else : ?>
                                    <span class="todo">Restaurer avec UnicaenValidation </span>
<!--                                    --><?php //$validation = ($hasApplication AND $hasApplication->getValidationActiveByTypeCode())?$hasApplication->getValidation():null; ?>
<!--                                    --><?php //if ($validation) : ?>
<!--                                        --><?php //echo $this->validationBadge($validation); ?>
<!--                                    --><?php //else : ?>
<!--                                        --><?php //if ($canModifier) : ?>
<!--                                            <a-->
<!--                                            --><?php ///** @see \Application\Controller\AgentController::validerElementAction() */ ?>
<!--                                            href="--><?php //echo $this->url('agent/valider-element', ['type' => "AGENT_APPLICATION", 'id' => $hasApplication->getId()], [], true); ?><!--"-->
<!--                                            class="ajax-modal"-->
<!--                                            data-event="modification"-->
<!--                                            >-->
<!--                                        --><?php //endif; ?>
<!--                                        <span class="icon icon-question" style="color: cornflowerblue;"-->
<!--                                              data-bs-toggle="tooltip" data-bs-html="true"-->
<!--                                              title="Application en attente de validation"-->
<!--                                        ></span>-->
<!--                                        --><?php //if ($canModifier) : ?>
<!--                                            </a>-->
<!--                                        --><?php //endif; ?>
<!--                                    --><?php //endif; ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
            <?php endforeach; ?>
        </table>
    </div>
</div>