<?php

use Application\Entity\Db\Agent;
use Carriere\Entity\Db\Categorie;
use Metier\Entity\Db\Metier;
use Application\Entity\Db\ParcoursDeFormation;
use Formation\Entity\Db\FormationGroupe;

/**
 * @see \Application\View\Helper\ParcoursDeFormationViewHelper
 * @var ParcoursDeFormation $parcours
 * @var Categorie|Metier $reference
 * @var Agent $agent
 * @var array $options
 */

/** Dans le tableau options, on retrouve une clef 'mode'.
 *  Si cette clef est omise alors la valeur par défaut "affichage" est utilisée.
 *  Valeur possible :
 *  - "affichage" ne fait que l'affichage (aucune interaction possible)
 *      >> Si un agent est renseigné affiche le "statut" du parcours de formation
 *  - "création" permet d'ajouter ou de retirer des formations au parcours
 *  - "modification" permet de valider le suivi d'une formations du parcours
 *      >> Si un agent est renseigné affiche le "statut" du parcours de formation
 */

$modesAutorises = ['affichage', 'creation', 'modification'];

/** Tri pour bonne affichage ******************************************************************************************/
$nogroup = "ZZZZ";
$formationArray = [];
foreach ($parcours->getFormations() as $formation) {
    $groupe = ($formation->getFormation()->getGroupe())?$formation->getFormation()->getGroupe()->getLibelle():$nogroup;
    $formationArray[$groupe][] = $formation;
}

usort($formationArray,
    function($a, $b) {
        $ordre_a = ($a[0]->getFormation()->getGroupe())?$a[0]->getFormation()->getGroupe()->getOrdre():9999;
        $ordre_b = ($b[0]->getFormation()->getGroupe())?$b[0]->getFormation()->getGroupe()->getOrdre():9999;
        return $ordre_a <=> $ordre_b;
    });
?>

<?php /** Récupération du mode ****************************************************************************************/
    $mode = (isset($options['mode']))?$options['mode']:"affichage";
?>

<?php if (!in_array($mode, $modesAutorises)) : ?>
<div class="alert alert-danger">
    Le <strong>mode</strong> [<?php echo $mode; ?>] est non géré par l'aide de vue [ParcoursDeFormationViewHelper].
</div>
<?php endif; ?>

<?php /** Récupération du droit associé à la modification *************************************************************/
    $canModifier = $options['modification'] ?? false;
?>

<div class="parcours">
    <?php if ($mode === 'creation') : ?>
        <div class="pull-right">
            <?php if ($canModifier AND $mode === 'creation') : ?>
                <?php /** @see \Application\Controller\ParcoursDeFormationController::ajouterFormationAction() */?>
                <a href="<?php echo $this->url('parcours-de-formation/ajouter-formation', ['parcours-de-formation' => $parcours->getId()], [], true); ?>"
                   class="btn btn-primary action ajax-modal" data-event="modification">
                    <span class="icon icon-ajouter"></span>Ajouter des formations </a>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <div class="listing">
        <table>
            <?php foreach ($formationArray as $groupe => $formationSubarray) : ?>
                <?php usort($formationSubarray, function ($a, $b) {return $a->getOrdre() <=> $b->getOrdre();}); ?>
                <tr>
                    <th colspan="2">
                        <?php /** @var FormationGroupe $groupe */ $groupe = $formationSubarray[0]->getFormation()->getGroupe(); ?>
                        <?php if ($groupe !== $nogroup) : ?>
                            <?php echo ($groupe !== null)?$groupe->getLibelle():"Sans groupe ..."; ?>
                        <?php else : ?>
                            Sans groupe ...
                        <?php endif; ?>
                    </th>
                </tr>

                <?php
                    $position = 0;
                    $nbElement = count($formationSubarray);
                ?>

                <?php  foreach($formationSubarray as $formationP) : ?>
                <tr>
                    <?php
                        $position++;
                        $formation = $formationP->getFormation(); ?>
                    <td class="libelle"> <?php echo $formation->getLibelle(); ?> </td>
                    <?php if ($mode === 'modification' OR $mode === 'affichage') : ?>
                        <td class="validation">
                            <?php
                                $agentFormation = ($agent !== null AND $agent->hasFormation($formation)) ? $agent->hasFormation($formation):null;
                            ?>
                            <?php if ($mode === 'modification' or $mode === 'affichage') : ?>
                            <?php if ($agentFormation !== null) : ?>
<!--                                <span class="todo"> A restaurer avec UnicaenValidation</span>-->
<!--                                --><?php //$agentValidation = ($agentFormation !== null AND $agentFormation->getValidation() !== null) ? $agentFormation->getValidation():null; ?>
<!--                                --><?php //if ($agentValidation !== null) : ?>
<!--                                           --><?php //echo $this->validationBadge($agentValidation); ?>
<!--                                --><?php //else : ?>
<!--                                    --><?php //if ($canModifier AND $mode === 'modification') : ?>
<!--                                        <a-->
<!--                                            --><?php ///** @see \Application\Controller\AgentController::validerElementAction() */ ?>
<!--                                            href="--><?php //echo $this->url('agent/valider-element', ['type' => "AGENT_FORMATION", 'id' => $agentFormation->getId()], [], true); ?><!--"-->
<!--                                            class="ajax-modal"-->
<!--                                            data-event="modification"-->
<!--                                        >-->
<!--                                    --><?php //endif; ?>
<!--                                    <span class="icon icon-question" style="color: cornflowerblue;"-->
<!--                                          data-bs-toggle="tooltip" data-bs-html="true"-->
<!--                                          title="Formation en attente de validation"-->
<!--                                    ></span>-->
<!--                                    --><?php //if ($canModifier) : ?>
<!--                                        </a>-->
<!--                                    --><?php //endif; ?>
<!--                                --><?php //endif; ?>
                            <?php else : ?>
                                <?php if ($canModifier) : ?>
                                    <a
                                        <?php /** @see \Application\Controller\AgentController::ajouterFormationAction() todo provient de agent formation ... */?>
                                            href="<?php echo $this->url('agent/ajouter-formation', ['agent' => $agent->getId(), 'formation' => $formation->getId()], [], true); ?>"
                                            class="ajax-modal"
                                            data-event="modification"
                                    >
                                        <span class="icon icon-ajouter"
                                              data-bs-toggle="tooltip" data-bs-html="true"
                                              title="Ajouter une formation"
                                        ></span>
                                    </a>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <?php endif; ?>
                    <?php if ($mode === 'creation') : ?>
                        <td>
                        <?php if ($canModifier AND $mode === 'creation') : ?>
                            <?php if ($nbElement > 1) : ?>
                                <?php if ($position !== 1) : ?>
                                    <?php /** @see \Application\Controller\ParcoursDeFormationController::bougerFormationAction() */ ?>
                                    <a href="<?php echo $this->url('parcours-de-formation/bouger-formation', ['parcours-de-formation' => $parcours->getId(), 'formation' => $formationP->getId(), 'direction' => 'up'], [], true); ?>"
                                    >
                                        <span class="icon icon-monter" data-toogle="tooltip" data-bs-html="true" title="Bouger vers le haut la formation"></span>
                                    </a>
                                <?php else : ?>
                                    <span class="icon icon-monter" style="color:white;"></span>
                                <?php endif ?>
                                <?php if ($position !== $nbElement) : ?>
                                    <?php /** @see \Application\Controller\ParcoursDeFormationController::bougerFormationAction() */ ?>
                                    <a href="<?php echo $this->url('parcours-de-formation/bouger-formation', ['parcours-de-formation' => $parcours->getId(), 'formation' => $formationP->getId(), 'direction' => 'down'], [], true); ?>"
                                    >
                                        <span class="icon icon-descendre" data-toogle="tooltip" data-bs-html="true" title="Bouger vers le bas la formation"></span>
                                    </a>
                                <?php else : ?>
                                    <span class="icon icon-descendre" style="color:white;"></span>
                                <?php endif; ?>
                            <?php else : ?>
                                <span class="icon icon-monter" style="color:white;"></span>
                                <span class="icon icon-descendre" style="color:white;"></span>
                            <?php endif; ?>

                            <?php /** @see \Application\Controller\ParcoursDeFormationController::retirerFormationAction() */ ?>
                            <a href="<?php echo $this->url('parcours-de-formation/retirer-formation', ['parcours-de-formation' => $parcours->getId(), 'formation' => $formationP->getId()], [], true); ?>"
                            >
                                <span class="icon icon-unchecked" data-toogle="tooltip" data-bs-html="true" title="Retirer la formation"></span>
                            </a>

                        <?php endif; ?>
                    </td>
                    <?php endif; ?>
                </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </table>
    </div>
</div>