<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\Application;
use Formation\Entity\Db\Formation;

/**
 * @see \Application\View\Helper\ParcoursDeFormationViewHelper
 * @var Application[] $applications
 * @var Formation[] $formations
 * @var Agent $agent
 * @var array $option
 */

/** Dans le tableau options, on retrouve une clef 'mode'.
 *  Si cette clef est omise alors la valeur par défaut "affichage" est utilisée.
 *  Valeur possible :
 *  - "affichage" ne fait que l'affichage (aucune interaction possible)
 *      >> Si un agent est renseigné affiche le "statut" du parcours de formation
 *  - "création" permet d'ajouter ou de retirer des formations au parcours
 *  - "modification" permet de valider le suivi d'une formations du parcours
 *      >> Si un agent est renseigné affiche le "statut" du parcours de formation
 */

$modesAutorises = ['affichage', 'creation', 'modification'];
$nogroup = "Sans Groupe";

/** Tri pour bonne affichage ******************************************************************************************/
$applicationsArray = [];
foreach ($applications as $application) {
    $groupe = ($application->getGroupe())?$application->getGroupe()->getLibelle():$nogroup;
    $applicationsArray[$groupe][] = $application;
}

ksort($applicationsArray);

?>

<?php /** Récupération du mode ****************************************************************************************/
    $mode = (isset($options['mode']))?$options['mode']:"affichage";
?>

<?php if (array_search($mode, $modesAutorises) === false) : ?>
<div class="alert alert-danger">
    Le <strong>mode</strong> [<?php echo $mode; ?>] est non géré par l'aide de vue [ParcoursDeFormationViewHelper].
</div>
<?php endif; ?>

<?php /** Récupération du droit associé à la modification *************************************************************/
    $canModifier = isset($options['modification'])?$options['modification']:false;
?>

<?php /** Titre du parcours de formation  *****************************************************************************/ ?>

<div class="parcours-de-formation">

<div class="row">
    <div class="col-md-8">
        <h4>Parcours de formation lié aux applications</h4>
    </div>
<!--    <div class="pull-right">-->
<!--        --><?php //if ($canModifier AND $mode === 'creation') : ?>
<!--            --><?php ///** @see \Application\Controller\ParcoursDeFormationController::ajouterFormationAction() */?>
<!--            <a href="--><?php //echo $this->url('parcours-de-formation/ajouter-formation', ['parcours-de-formation' => $parcours->getId()], [], true); ?><!--"-->
<!--               class="btn btn-primary action ajax-modal" data-event="modification">-->
<!--                <span class="icon ajouter"></span>Ajouter des formations </a>-->
<!--        --><?php //endif; ?>
<!--    </div>-->
</div>

<br/>

<?php /** Affichage du tableau ****************************************************************************************/ ?>

    <div>
    <table class="parcours-de-formation">
        <?php foreach($applicationsArray as $groupe => $applicationArray) : ?>
            <?php usort($applicationArray, function ($a, $b) {return $a->getLibelle() > $b->getLibelle();}); ?>

            <?php /** Barre de groupe de formation  *******************************************************************/ ?>
                <tr>
                    <th class="titre" colspan="3">
                        <?php echo $groupe; ?>
                    </th>
                </tr>

            <?php /** Barre de formation ******************************************************************************/ ?>

            <?php  foreach($applicationArray as $application) : ?>
                <tr>
                    <td class="libelle">
                        <?php echo $application->getLibelle(); ?>
                    </td>
                    <td class="formation"></td>
                    <td class="action"></td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </table>
</div>
</div>

<style>

    div.parcours-de-formation {
        padding-top: 2rem;
    }

    div.parcours-de-formation h4 {
        text-decoration: underline;
    }

    table.parcours-de-formation {
        width:95%;
    }

    table.parcours-de-formation th {
        padding: 0.5rem;
        color: white;
    }
    table.parcours-de-formation td.libelle {
        padding-left: 1rem;
        width:80%;
    }
    table.parcours-de-formation td.formation {
        text-align: center;
    }
</style>