<?php

/**
 * @see \Application\View\Helper\RaisonsViewHelper
 * @var array $raisons
 * @var array $options
 */

use Application\Entity\Db\Agent;
use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Entity\Db\FicheMetierMission;
use Formation\Entity\Db\Formation;


?>
<?php if ($raisons !== null) : ?>
    <?php foreach ($raisons as $raison) : ?>
        <?php $text = "";
        switch ($raison) {
            case $raison instanceof FicheMetier :
                $text = $raison->getMetier()->getLibelle();
                $label = "FicheMétier";
                $class = 'fiche-metier';
                break;
            case $raison instanceof FicheMetierMission :
                $text = $raison->getMission()->getLibelle();
                $label = "Activité";
                $class = 'activite';
                break;
            case $raison instanceof Formation :
                $text = "Obtenue grâce à la formation <span class='highlight formation'>" . $raison->getLibelle() . "</span>";
                $label = "Formation";
                $class = 'raison formation';
                break;
            case $raison instanceof Agent :
                $text = "Liée à l'agent <span class='highlight formation'>" . $raison->getDenomination() . "</span>";
                $label = "Agent";
                $class = 'agent';
                break;
            default :
//                var_dump($raison);
                $text = "Provenance inconnue";
                $label = "???";
                $class = 'inconnue';

        }
        ?>
        <span class="<?php echo $class; ?>" title="<?php echo $text; ?>" data-bs-toggle="tooltip" data-bs-html="true"><?php echo $label; ?></span>
    <?php endforeach;?>
<?php endif; ?>