<?php

/**
 * @see \Application\View\Helper\RaisonsViewHelper
 * @var array $raisons
 * @var array $options
 */

use Application\Entity\Db\Agent;
use FicheMetier\Entity\Db\FicheMetier;
use FicheMetier\Entity\Db\FicheMetierMission;
use FicheMetier\Entity\Db\Mission;
use Formation\Entity\Db\Formation;


?>
<?php if ($raisons !== null) : ?>
    <?php foreach ($raisons as $raison) : ?>
        <?php $text = "";
        switch ($raison) {
            case $raison instanceof FicheMetier :
                $text = "Obtenue grâce à la fiche métier [".$raison->getMetier()->getLibelle()."]";
                $label = "FicheMétier";
                $class = 'fiche-metier';
                break;
            case $raison instanceof FicheMetierMission :
                $text = $raison->getMission()->getLibelle();
                $label = "Mission";
                $class = 'activite';
                break;
            case $raison instanceof Mission :
                $text = "Obtenue grâce à la mission [" . $raison->getLibelle()."]";
                $label = "Mission";
                $class = 'mission';
                break;
            case $raison instanceof Formation :
                $text = "Obtenue grâce à la formation <span class='highlight formation'>" . $raison->getLibelle() . "</span>";
                $label = "Formation";
                $class = 'raison formation';
                break;
            case $raison instanceof Agent :
                $text = "Liée à l'agent <span class='highlight agent'>" . $raison->getDenomination(true) . "</span>";
                $label = "Agent";
                $class = 'agent';
                break;
            default :
//                var_dump($raison);
                $text = "Provenance inconnue : (".get_class($raison).")";
                $label = "???";
                $class = 'inconnue';

        }
        ?>
        <span data-bs-toggle='tooltip' data-bs-html='true' class="raison <?php echo $class; ?>" title="<?php echo $text; ?>" ><?php echo $label; ?></span>
    <?php endforeach;?>
<?php endif; ?>

<style>
    span.raison {
        font-variant-position: super;
        font-weight: bold;
    }

    span.raison.agent {
        color: darkgoldenrod;
    }

    span.raison.fiche-metier {
        color: purple;
    }

    span.raison.activite {
        color: darkslateblue;
    }

    span.raison.mission {
        color: darkred;
    }

    span.raison.formation {
        color: darkgreen;
    }

    span.raison.inconnue {
        color: gray;
    }
</style>


