<?php

use Application\Entity\Db\ActiviteDescription;
use Application\Entity\Db\SpecificiteActivite;
use Application\Provider\Privilege\FichePostePrivileges;
use Metier\Entity\Db\Domaine;

/**
 * @see \Application\View\Helper\SpecificitePosteViewHelper;
 * @var SpecificiteActivite $specificiteActivite
 * @var array $options
 */

$activite = $specificiteActivite->getActivite();
$mode = 'affichage';
if (isset($options["mode"])) $mode = $options["mode"];

$descriptions = $activite->getDescriptions();
usort($descriptions, function (ActiviteDescription $a, ActiviteDescription $b) { return $a->getOrdre() > $b->getOrdre();});

$retrait = explode(";",$specificiteActivite->getRetrait());
$retraits = [];
foreach ($retrait as $item) $retraits[$item] = true;

$canRetirerActivite = $this->isAllowed($specificiteActivite->getSpecificite()->getFiche(), FichePostePrivileges::FICHEPOSTE_MODIFIER);
$canGererActivite = $canRetirerActivite;

$agent = $specificiteActivite->getSpecificite()->getFiche()->getAgent();
$delta = ($activite->getNiveaux())?$activite->getNiveaux()->getDeltaWithAgent($agent):null;
?>

<div class="specificite-activite">
    <div class="activite-titre delta_<?php echo $delta; ?>">
        <div class="row">
            <div class="col-md-10">
                <h3><?php echo $activite->getLibelle(); ?>
                    <?php if ($delta AND $delta !== 0) : ?>
                        <span class="icon icon-attention" title="Il existe un écart de <?php echo $delta; ?> niveau(x) entre l'agent et l'activité"></span>
                    <?php endif; ?>
                </h3>
            </div>
            <?php if($mode === 'edition') : ?>
                <div class="pull-right activite-action">
                    <?php if ($canGererActivite) : ?>
                        <?php /** @see \Application\Controller\SpecificiteController::gererActiviteAction() */ ?>
                        <a href="<?php echo $this->url('specificite/gerer-activite', ['specificite-activite' => $specificiteActivite->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-listing"></span></a>
                    <?php endif; ?>
                    <?php if ($canRetirerActivite) : ?>
                        <?php /** @see \Application\Controller\SpecificiteController::retirerActiviteAction() */ ?>
                        <a href="<?php echo $this->url('specificite/retirer-activite', ['specificite-activite' => $specificiteActivite->getId()], [], true); ?>">
                            <span class="icon icon-retirer"></span></a>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
        <?php $domaines = $activite->getDomaines(); ?>
        <?php if (!empty($domaines)) : ?>
        <?php foreach ($domaines as $domaine) : ?>
            <?php /** @var Domaine $domaine */ ?>
            <span class="label" style="background: lightskyblue;">
                <?php echo $domaine->getLibelle(); ?>
            </span>
        <?php endforeach; ?>
        <br/>
        <br/>
        <?php endif; ?>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="activite-description">
                Description de l'activité :
                <ul>
                    <?php foreach ($descriptions as $description) : ?>
                        <?php if (!isset($retraits[$description->getId()])) : ?>
                            <li>
                                <?php echo $description->getLibelle(); ?>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <div class="col-md-4" style="margin-top: 0.5rem;">

            <div class="card panel-default">
                <div class="card-header">
                    Métiers associés
                </div>
                <div class="card-body">
                    <?php $count = 0; ?>
                    <ul>
                        <?php foreach ($activite->getFichesMetiers() as $ficheMetier) : ?>
                            <?php $metier = $ficheMetier->getFiche()->getMetier(); ?>
                            <li>
                                <?php $count++; ?>
                                <?php echo $metier->getLibelle(); ?>
                                <?php foreach ($metier->getReferences() as $reference) : ?>
                                    <span class="badge" style="background-color: #dfc4b2"><a href="<?php echo $reference->getUrl(); ?>"> <?php echo $reference->getTitre(); ?> </a></span>
                                <?php endforeach; ?>
                            </li>
                        <?php endforeach; ?>
                        <?php if ($count === 0) echo "Aucun"; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>


</div>

<style>
    div.specificite-activite div.activite-titre {
        border: 1px solid black;
        padding-left: 2rem;
    }

    div.specificite-activite div.activite-action {
        padding-top: 2rem;
        padding-right: 1rem;
    }
</style>