<?php

use Application\Provider\Privilege\FichePostePrivileges;
use FichePoste\Entity\Db\MissionAdditionnelle;

/**
 * @see \Application\View\Helper\SpecificiteActiviteViewHelper;
 * @var MissionAdditionnelle $missionAdditionnelle
 * @var array $options
 */

$mission = $missionAdditionnelle->getMission();
$mode = 'affichage';
if (isset($options["mode"])) $mode = $options["mode"];

$retrait = explode(";",$missionAdditionnelle->getRetraits()??"");
$retraits = [];
foreach ($retrait as $item) $retraits[$item] = true;

$canRetirerActivite = $this->isAllowed($missionAdditionnelle->getFicheposte(), FichePostePrivileges::FICHEPOSTE_MODIFIER);
$canGererActivite = $canRetirerActivite;

$agent = $missionAdditionnelle->getFicheposte()->getAgent();
$delta = ($mission->getNiveau())?$mission->getNiveau()->getDeltaWithAgent($agent):null;
?>

<li>
    <?php echo $missionAdditionnelle->getMission()->getLibelle(); ?>
    <?php if ($canRetirerActivite) : ?>
        <?php /** @see \Application\Controller\SpecificiteController::retirerActiviteAction() */ ?>
        <a href="<?php echo $this->url('specificite/retirer-activite', ['specificite-activite' => $missionAdditionnelle->getId()], [], true); ?>"
           class="ajax-modal" data-event="modification"
        >
                            <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Retirer
                            </span>
        </a>
    <?php endif; ?>
</li>
