<?php

/**
 * @see \Application\View\Helper\SpecificitePosteViewHelper
 * @var FichePoste $fichePoste
 * @var SpecificitePoste|null $specificite
 * @var array $options
 */

use Application\Entity\Db\FichePoste;
use Application\Entity\Db\SpecificitePoste;
use FichePoste\Provider\Privilege\FichePostePrivileges;
use FichePoste\Entity\Db\MissionAdditionnelle;

$mode = "affichage";
if (isset($options["mode"])) $mode = $options["mode"];
?>

<!-- PARTIE SPECIFITE PURE -------------------------------------------------------------------------------------------->
<?php if ($specificite) : ?>
    <?php if ($specificite->getSpecificite()) : ?>
        <h3> Spécificités du poste </h3>
        <?php echo $specificite->getSpecificite(); ?>
    <?php endif; ?>

    <?php if ($specificite->getEncadrement()) : ?>
        <h3> Encadrement </h3>
        <?php echo $specificite->getEncadrement(); ?>
    <?php endif; ?>

    <?php if ($specificite->getRelationsInternes()) : ?>
        <h3> Relations internes à l'université </h3>
        <?php echo $specificite->getRelationsInternes(); ?>
    <?php endif; ?>

    <?php if ($specificite->getRelationsExternes()) : ?>
        <h3> Relations externes à l'université </h3>
        <?php echo $specificite->getRelationsExternes(); ?>
    <?php endif; ?>

    <?php if ($specificite->getContraintes()) : ?>
        <h3>  Sujétions ou conditions particulières </h3>
        <?php echo $specificite->getContraintes(); ?>
    <?php endif; ?>

    <?php if ($specificite->getMoyens()) : ?>
        <h3> Moyens et outils mis à disposition </h3>
        <?php echo $specificite->getMoyens(); ?>
    <?php endif; ?>

    <?php if ($specificite->getFormations()) : ?>
        <h3> Formations ou qualifations nécessaires </h3>
        <?php echo $specificite->getFormations(); ?>
    <?php endif; ?>
<?php else : ?>
        <div class="alert alert-warning">
            <i class="fas fa-exclamation-triangle"></i>
            Aucune spécificité attachée à ce poste.
        </div>
<?php endif; ?>

<?php
    $canAjouterActivite = $this->isAllowed($fichePoste, FichePostePrivileges::FICHEPOSTE_MODIFIER);
    $missionsAdditionnelles = $fichePoste->getMissionsAdditionnelles();
    usort($missionsAdditionnelles, function (MissionAdditionnelle $a, MissionAdditionnelle $b) { return $a->getMission()->getLibelle() <=> $b->getMission()->getLibelle();});
?>
