<?php

/**
 * @var Domaine $domaine
 */

use Metier\Entity\Db\Domaine;

$type = $domaine->getTypeFonction();
?>

<span class="label <?php echo $type; ?>">
    <?php echo $type; ?>
</span>

<style>
    span.label.Support {
        display: inline-block;
        background-color: seagreen;
    }
    span.label.Soutien {
        display: inline-block;
        background-color: darkslateblue;
    }
</style>