<?php

use UnicaenApp\Exception\RuntimeException;

/**
 * @var array $options
 */

//$icon = $options['icone'];
//if ($icon === null) throw new RuntimeException("<strong>ActionIcon</strong> ne possèdent pas d'icone ! <br/> Veuillez renseigner l'option 'icone' ");
//
//$url = $options['url'];
//if ($url === null) throw new RuntimeException("<strong>ActionIcon</strong> ne possèdent pas d'url ! <br/> Veuillez renseigner l'option 'url' ");
//
//
//$titre = '';
//if (isset($options['titre'])) $titre = $options['titre'];
//
//$isAllowed = true;
//if (isset($options['isAllowed'])) $class = $options['isAllowed'];
//$displayOff = true;
//if (isset($options['displayOff'])) $displayOff = $options['displayOff'];
//
//$class = '';
//if (isset($options['class'])) $class = $options['class'];
//$event = '';
//if (isset($options['event'])) $event = $options['event'];
?>

<span class="badge">
    Validation
</span>