<?php

use Application\Entity\Db\Validation;
use Application\Entity\Db\ValidationValeur;
use UnicaenApp\Exception\RuntimeException;

/**
 * @var Validation $validation
 * @var array $options
 */

//$icon = $options['icone'];
//if ($icon === null) throw new RuntimeException("<strong>ActionIcon</strong> ne possèdent pas d'icone ! <br/> Veuillez renseigner l'option 'icone' ");
//
//$url = $options['url'];
//if ($url === null) throw new RuntimeException("<strong>ActionIcon</strong> ne possèdent pas d'url ! <br/> Veuillez renseigner l'option 'url' ");
//
//
//$titre = '';
//if (isset($options['titre'])) $titre = $options['titre'];
//
//$isAllowed = true;
//if (isset($options['isAllowed'])) $class = $options['isAllowed'];
//$displayOff = true;
//if (isset($options['displayOff'])) $displayOff = $options['displayOff'];
//
//$class = '';
//if (isset($options['class'])) $class = $options['class'];
//$event = '';
//if (isset($options['event'])) $event = $options['event'];
?>

<?php
    $vclass = "";
    $etiquette = "";
    $texte = "Date: ".$validation->getHistoModification()->format('d/m/Y à H:i:s')."\nValidateur: ".$validation->getHistoModificateur()->getDisplayName();
    $valeur = ($validation->getValeur())?$validation->getValeur()->getCode():null;
    switch($valeur) {
        case ValidationValeur::VALIDER :
            $vclass='validation-badge-valider';
            $etiquette = 'Validée';
            break;
        case ValidationValeur::REJETER :
            $vclass='validation-badge-rejeter';
            $etiquette = 'Rejetée';
            break;
        //case ValidationValeur::A_MODIFIER :
        default :
            $vclass='validation-badge-a_modifier';
            $etiquette = 'À modifier';
            break;
    }
?>
<a href="<?php echo $this->url('validation/afficher', ["validation" => $validation->getId()], [], true); ?>" class="ajax-modal">
    <span class="badge <?php echo $vclass; ?>" title="<?php echo $texte; ?>">
        <?php echo $etiquette; ?>
    </span>
</a>

<style>
    span.validation-badge-valider {
        background-color: darkgreen;
    }
    span.validation-badge-rejeter {
        background-color: darkred;
    }
    span.validation-badge-a_modifier {
        background-color: darkorange;
    }
</style>