<?php

use Agent\Entity\Db\Agent;
use Element\Entity\Db\ApplicationElement;
use Element\Entity\Db\CompetenceElement;

/**
 * @see \Agent\Controller\AgentController::acquisAction()
 * @var Agent $agent
 * @var ApplicationElement[] $applications
 * @var CompetenceElement[] $competences
 *
 */

$options['retour'] = $this->url('agent/acquis', ['agent' => $agent->getId()], [], true);

?>

<?php echo $this->agentOnglet($agent, 'acquis'); ?>

<div class="alert alert-info">
    <strong><span
                class="icon icon-attention"> Affichage des applications et compétences directement liées à l'agent.</strong>
    <br/>
    Dans ces listes, les applications et compétences associées aux fiches de postes d'un
    agent ne sont pas mentionnées.
</div>

<!--                --><?php //if ($displayAcquis === true) : ?>
<!-- APPLICATION ------------------------------------------------------------------------------------------------------>
<?php echo $this->applicationBloc($applications, $agent, $options); ?>

<!-- COMPETENCE ------------------------------------------------------------------------------------------------------->
<?php echo $this->competenceBloc($competences, $agent, $options); ?>
<!--                --><?php //endif; ?>

<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>


