<?php

/**
 * @var EntretienProfessionnel $entretien
 */

use Application\Entity\Db\EntretienProfessionnel;
use Autoform\Entity\Db\Categorie;
use Autoform\Entity\Db\Champ;

?>

<style>
    h1, h2 {
        color: #123456;
    }

    h1 {
        font-size: 18pt;
    }

    h2 {
        font-size: 16pt;
    }

    h3 {
        font-size: 14pt;
    }

    h4 {
        font-size: 12pt;
    }

    body {
        font-size: 10pt;
    }

    div.activite {
        border-left : 2px solid #123456;
        border-bottom : 1px solid #123456;
        padding-left: 1rem;
        margin-bottom: 1rem;
    }
</style>

<h1>
    Compte-rendu de l'entretien professionnel
</h1>

<?php
    $responses = $entretien->getFormulaireInstance()->getReponses();
    $reponses = [];
    foreach ($responses as $response) {
        $reponses[$response->getChamp()->getId()] = $response->getReponse();
    }

?>

<!-- GENERALITE ------------------------------------------------------------------------------------------------------->
<dl>
    <dt>Agent</dt>
    <dd> <?php echo $entretien->getAgent()->getDenomination(); ?> </dd>
    <dt>Responsable de l'entretien</dt>
    <dd> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </dd>
    <dt>Date </dt>
    <dd> <dd> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </dd>
</dl>

<!-- AUTOFORM --------------------------------------------------------------------------------------------------------->
<?php
    $categories = $entretien->getFormulaireInstance()->getFormulaire()->getCategories();
    usort($categories, function (Categorie $a, Categorie $b) { return $a->getOrdre() > $b->getOrdre();});
?>

<?php foreach ($categories as $categorie) : ?>
    <?php if ($categorie->estNonHistorise()) : ?>
        <h3> <?php echo $categorie->getLibelle();?> </h3>

        <?php
            $champs = $categorie->getChamps();
            usort($champs, function (Champ $a, Champ $b) { return $a->getOrdre() > $b->getOrdre(); });
        ?>

        <ul>
        <?php foreach ($champs as $champ) : ?>
            <?php if ($champ->estNonHistorise()) : ?>
                <?php if (isset($reponses[$champ->getId()]) AND $reponses[$champ->getId()] !== null) : ?>
                    <?php echo $this->champAsResult()->render($champ, $reponses[$champ->getId()]); ?>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>


    <?php endif; ?>

<?php endforeach; ?>

<!-- VALIDATION-------------------------------------------------------------------------------------------------------->

<h2> Validations </h2>

<table>
    <tr>
        <td width="50%">
            <h3>Validation de l'agent</h3>
        </td>
        <td width="50%">
            <h3>Validation du responsable</h3>
        </td>
    </tr>
    <tr>
        <td>
            <?php if ($entretien->getValidationAgent()) : ?>
                <?php echo $entretien->getValidationAgent()->getHistoModificateur()->getDisplayName(); ?> <br/>
                <?php echo $entretien->getValidationAgent()->getHistoModification()->format('d/m/Y'); ?>
            <?php else : ?>
                L'agent n'a pas encore validé&middot;e l'entretien professionnel.
            <?php endif; ?>
        </td>
        <td>
            <?php if ($entretien->getValidationResponsable()) : ?>
                <?php echo $entretien->getValidationResponsable()->getHistoModificateur()->getDisplayName(); ?> <br/>
                <?php echo $entretien->getValidationResponsable()->getHistoModification()->format('d/m/Y'); ?>
            <?php else : ?>
                Le responsable n'a pas encore validé&middot;e l'entretien professionnel.
            <?php endif; ?>
        </td>
    </tr>
</table>

