<?php

/**
 * @see \Application\Controller\AgentMobiliteController::indexAction()
 * @var AgentMobilite[] $mobilites
 * @var ?Agent $agent
 * @var ?Mobilite $mobilite
 * @var ?Structure $structure
 * @var Mobilite[] $types
 */

use Agent\Entity\Db\AgentMobilite;
use Agent\Provider\Privilege\AgentmobilitePrivileges;
use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use Carriere\Entity\Db\Mobilite;
use Structure\Entity\Db\Structure;

$this->headTitle("Gestion des statuts de mobilité des agent·es");

$canAjouter = $this->isAllowed(AgentmobilitePrivileges::getResourceId(AgentmobilitePrivileges::AGENTMOBILITE_AJOUTER));
?>

<h1 class="page-header">
    Gestion des statuts de mobilité des agent·es
</h1>

<?php echo $this->partial('partial/filtre', ['mobilites' => $types, 'agent' => $agent, 'mobilite' => $mobilite, 'structure' => $structure]); ?>

<?php if ($canAjouter): ?>
    <a href="<?php echo $this->url('agent/mobilite/ajouter', [], [], true); ?>"
       class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Déclarer un statut de mobilité
    </a>
<?php endif; ?>

<table class="table table-condensed datatable" id="mobilites">
    <thead>
    <tr>
        <th data-type="string">Agent</th>
        <th>Affectation</th>
        <th>Statut</th>
        <th data-type="num">Date</th>
        <th class="action">Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($mobilites as $amobilite): ?>
        <?php
        $agent = $amobilite->getAgent();
        $mobilite = $amobilite->getMobilite();

        $canAfficher = $this->isAllowed($agent, AgentPrivileges::AGENT_AFFICHER);
        $canModifier = $this->isAllowed(AgentmobilitePrivileges::getResourceId(AgentmobilitePrivileges::AGENTMOBILITE_MODIFIER));
        $canHistoriser = $this->isAllowed(AgentmobilitePrivileges::getResourceId(AgentmobilitePrivileges::AGENTMOBILITE_HISTORISER));
        $canSupprimer = $this->isAllowed(AgentmobilitePrivileges::getResourceId(AgentmobilitePrivileges::AGENTMOBILITE_SUPPRIMER));

        ?>
        <tr>
            <td data-order="<?php echo $agent->getDenomination(); ?>"> <?php echo $agent->getDenomination(true); ?> </td>
            <td>
                <?php $affectations = $agent->getAffectationsActifs(); ?>
                <?php if (empty($affectations)) : ?>
                    <em> Aucune affectation </em>
                <?php else : ?>
                    <?php foreach ($affectations as $affectation): ?>
                        <span <?php if ($affectation->isPrincipale()): ?> class=" principale "<?php endif; ?>>
                                <?php echo $affectation->getStructure()->getLibelleLong(); ?>
                            </span><br>
                    <?php endforeach; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php echo $mobilite->getLibelle(); ?>
                <?php if ($amobilite->getCommentaire()): ?>
                    <span class="icon icon-information" data-bs-toggle="tooltip" data-bs-html="true"
                          title="<?php echo $amobilite->getCommentaire(); ?>"></span>
                <?php endif; ?>
            </td>
            <td data-order="<?php echo $amobilite->getHistoCreation()->getTimestamp(); ?>">
                <?php echo $amobilite->getHistoCreation()->format('d/m/Y à H:i'); ?>
            </td>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Application\Controller\AgentController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], ['fragment' => 'mobilite'], true); ?>"
                       class="action secondary"
                    >
                        <span class="icon icon-user"></span> Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \Application\Controller\AgentMobiliteController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('agent/mobilite/modifier', ['agent-mobilite' => $amobilite->getId()], [], true); ?>"
                       class="ajax-modal action primary" data-event="modification"
                    >
                        <span class="icon icon-editer"></span> Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br>
                    <?php if ($amobilite->estNonHistorise()) : ?>
                        <?php /** @see \Application\Controller\AgentMobiliteController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('agent/mobilite/historiser', ['agent-mobilite' => $amobilite->getId()], [], true); ?>"
                           class="ajax-modal action warning" data-event="modification"
                        >
                            <span class="icon icon-historiser"></span> Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Application\Controller\AgentMobiliteController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('agent/mobilite/restaurer', ['agent-mobilite' => $amobilite->getId()], ['query' => ['retour' => $this->url('agent/mobilite', [], [], true)]], true); ?>"
                           class="action warning"
                        >
                            <span class="icon icon-restaurer"></span> Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canSupprimer) : ?>
                    <br>
                    <?php /** @see \Application\Controller\AgentMobiliteController::supprimerAction() */ ?>
                    <a href="<?php echo $this->url('agent/mobilite/supprimer', ['agent-mobilite' => $amobilite->getId()], [], true); ?>"
                       class="ajax-modal action danger" data-event="modification"
                    >
                        <span class="icon icon-unchecked"></span> Supprimer
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<style>
    span.principale {
        font-weight: bold;
    }
</style>


<script>
    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
        $('table#mobilites').dataTable({
            paging: false,
            info: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [4], orderable: false }
            ]
        });
    });

</script>