<?php

//@formatter:off

return [
    'schema'      => 'public',
    'name'        => 'unicaen_alerte_alerte',
    'temporary'   => FALSE,
    'logging'     => TRUE,
    'commentaire' => 'Messages d\'alerte',
    'sequence'    => 'unicaen_alerte_alerte_id_seq',
    'columns'     => [
        'code'        => [
            'name'        => 'code',
            'type'        => 'string',
            'bdd-type'    => 'character varying',
            'length'      => 64,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 2,
            'commentaire' => 'Code littéral unique de cette alerte',
        ],
        'dismissible' => [
            'name'        => 'dismissible',
            'type'        => 'bool',
            'bdd-type'    => 'boolean',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => 'true',
            'position'    => 7,
            'commentaire' => 'Indique si cette alerte peut être fermée par l\'utilisateur',
        ],
        'duration'    => [
            'name'        => 'duration',
            'type'        => 'int',
            'bdd-type'    => 'smallint',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => 2,
            'nullable'    => FALSE,
            'default'     => '0',
            'position'    => 6,
            'commentaire' => 'Durée d\'affichage de cette alerte en millisecondes (0 = infini)',
        ],
        'id'          => [
            'name'        => 'id',
            'type'        => 'int',
            'bdd-type'    => 'integer',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => 4,
            'nullable'    => FALSE,
            'default'     => 'nextval(\'unicaen_alerte_alerte_id_seq\'::regclass)',
            'position'    => 1,
            'commentaire' => NULL,
        ],
        'severity'    => [
            'name'        => 'severity',
            'type'        => 'string',
            'bdd-type'    => 'character varying',
            'length'      => 64,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 5,
            'commentaire' => 'Sévérité (classe CSS) associée à cette alerte : success, info, warning, danger',
        ],
        'text'        => [
            'name'        => 'text',
            'type'        => 'clob',
            'bdd-type'    => 'text',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 4,
            'commentaire' => 'Texte de cette alerte',
        ],
        'title'       => [
            'name'        => 'title',
            'type'        => 'clob',
            'bdd-type'    => 'text',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 3,
            'commentaire' => 'Titre/intitulé de cette alerte',
        ],
    ],
];

//@formatter:on
