<?php

//@formatter:off

return [
    'schema'      => 'public',
    'name'        => 'unicaen_alerte_alerte_planning',
    'temporary'   => FALSE,
    'logging'     => TRUE,
    'commentaire' => 'Plannings d\'affichage des alertes',
    'sequence'    => 'unicaen_alerte_alerte_planning_id_seq',
    'columns'     => [
        'alerte_id'  => [
            'name'        => 'alerte_id',
            'type'        => 'int',
            'bdd-type'    => 'bigint',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => 8,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 2,
            'commentaire' => 'Identifiant de l\'alerte concernée',
        ],
        'end_date'   => [
            'name'        => 'end_date',
            'type'        => 'date',
            'bdd-type'    => 'timestamp without time zone',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => 6,
            'nullable'    => FALSE,
            'default'     => NULL,
            'position'    => 4,
            'commentaire' => 'Date et heure de fin de la période d\'affichage de l\'alerte',
        ],
        'id'         => [
            'name'        => 'id',
            'type'        => 'int',
            'bdd-type'    => 'integer',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => 4,
            'nullable'    => FALSE,
            'default'     => 'nextval(\'unicaen_alerte_alerte_planning_id_seq\'::regclass)',
            'position'    => 1,
            'commentaire' => NULL,
        ],
        'severity'   => [
            'name'        => 'severity',
            'type'        => 'string',
            'bdd-type'    => 'character varying',
            'length'      => 64,
            'scale'       => NULL,
            'precision'   => NULL,
            'nullable'    => TRUE,
            'default'     => NULL,
            'position'    => 5,
            'commentaire' => 'Sévérité remplaçant celle de l\'alerte sur cette période',
        ],
        'start_date' => [
            'name'        => 'start_date',
            'type'        => 'date',
            'bdd-type'    => 'timestamp without time zone',
            'length'      => 0,
            'scale'       => NULL,
            'precision'   => 6,
            'nullable'    => FALSE,
            'default'     => 'CURRENT_TIMESTAMP',
            'position'    => 3,
            'commentaire' => 'Date et heure de début de la période d\'affichage de l\'alerte',
        ],
    ],
];

//@formatter:on
