<?php

/**
 * @see \Formation\Controller\AdministrationController::etatAction()
 * @var EtatType[] $etatTypes
 */


use UnicaenEtat\Entity\Db\EtatType;

/** @var EtatType[] $types */
$types = []; $categories = [];
foreach ($etatTypes as $type => $etattypes) {
    $types = array_merge($types, $etattypes);
    if (!empty($etattypes)) $categories[] = current($etattypes)->getCategorie();
}
?>
<h1 class="page-header">
    Index des types d'état
</h1>

<div class="main">

    <h2>
        Catégorie d'états
        <span class="badge"><?php echo count($etatTypes); ?></span>
    </h2>

    <br/>

    <table id="etat-type" class="datatable table table-condensed">
        <thead>
        <tr>
            <th>Badge</th>
            <th>Code</th>
            <th>Libelle</th>
            <th style="width: 8rem;">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($categories as $categorie) : ?>
            <tr>
                <td> <?php echo $this->etatcategorie($categorie); ?> </td>
                <td> <?php echo $categorie->getCode(); ?> </td>
                <td> <?php echo $categorie->getLibelle(); ?> </td>
                <td class="action">
                    <?php /** @see \UnicaenEtat\Controller\EtatCategorieController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('unicaen-etat/etat-categorie/modifier', ['categorie' => $categorie->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>

<!--                    <br>-->
<!---->
<!--                    --><?php ///** @see \UnicaenEtat\Controller\EtatCategorieController::supprimerAction() */ ?>
<!--                    <a href="--><?php //echo $this->url('unicaen-etat/etat-categorie/supprimer', ['categorie' => $categorie->getId()], [], true); ?><!--"-->
<!--                       class="ajax-modal" data-event="modification">-->
<!--                            <span class="text-danger">-->
<!--                                <span class="icon icon-unchecked"></span>-->
<!--                                Supprimer-->
<!--                            </span>-->
<!--                    </a>-->
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <h2>
        États types
        <span class="badge"><?php echo count($types); ?></span>
    </h2>
    <?php /** @see \UnicaenEtat\Controller\EtatTypeController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('unicaen-etat/etat-type/ajouter', [], [], true); ?>"
       class="btn btn-primary action ajax-modal" data-event="modification">
        <span class="icon icon-ajouter"></span>
        Ajouter un d'état
    </a>

    <table id="etat" class="datatable table table-condensed">
        <thead>
        <tr>
            <th>Badge</th>
            <th>Code</th>
            <th>Libelle</th>
            <th>Ordre</th>
            <th>Catégorie</th>
            <th style="width: 8rem;">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($types as $type) : ?>
            <tr>
                <td> <?php echo $this->etattype($type); ?>  </td>
                <td> <?php echo $type->getCode(); ?> </td>
                <td> <?php echo $type->getLibelle(); ?> </td>
                <td> <?php echo $type->getOrdre(); ?> </td>
                <td> <?php echo $this->etatcategorie($type->getCategorie()); ?>  </td>
                <td class="action">
                    <?php /** @see \UnicaenEtat\Controller\EtatTypeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('unicaen-etat/etat-type/modifier', ['type' => $type->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                    <br>
                        <?php /** @see \UnicaenEtat\Controller\EtatTypeController::supprimerAction() */ ?>
                        <a href="<?php echo $this->url('unicaen-etat/etat-type/supprimer', ['type' => $type->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification">
                                <span class="text-danger">
                                    <span class="icon icon-unchecked"></span>
                                    Supprimer
                                </span>
                        </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>