<?php

/**
 * @see \Formation\Controller\ImportationLagafController::actionAction()
 * @var string $report
 * @var Formation[] $formations
 * @var FormationGroupe[] $groupes
 * @var FormationGroupe[] $themes
 */

use Formation\Entity\Db\Formation;
use Formation\Entity\Db\FormationGroupe;

?>

<h1 class="page-header">
    Importation des actions de formation depuis LAGAF
</h1>

<div class="report">
    <h2> Nouveaux éléments</h2>
    <dl>
        <dt> #Formation </dt>
        <dd> <?php echo count($formations); ?> </dd>
        <dt> #Groupe </dt>
        <dd> <?php echo count($groupes); ?> </dd>
        <dt> #Theme </dt>
        <dd> <?php echo count($themes); ?> </dd>
    </dl>

    <h2> Report </h2>

    <span class="verbatim">
        <?php echo $report; ?>
    </span>
</div>


<style>
    span.verbatim {
        white-space: pre-line;
    }
</style>
