<?php

use Carriere\Provider\Privilege\MobilitePrivileges;
use Carriere\Entity\Db\Mobilite;

/**
 * @see \Carriere\Controller\MobiliteController::indexAction()
 * @var Mobilite[] $mobilites
 */

$canAfficher    = $this->isAllowed(MobilitePrivileges::getResourceId(MobilitePrivileges::MOBILITE_AFFICHER));
$canAjouter     = $this->isAllowed(MobilitePrivileges::getResourceId(MobilitePrivileges::MOBILITE_AJOUTER));
$canModifier    = $this->isAllowed(MobilitePrivileges::getResourceId(MobilitePrivileges::MOBILITE_MODIFIER));
$canHistoriser  = $this->isAllowed(MobilitePrivileges::getResourceId(MobilitePrivileges::MOBILITE_HISTORISER));
$canDetruire    = $this->isAllowed(MobilitePrivileges::getResourceId(MobilitePrivileges::MOBILITE_SUPPRIMER));

$canAction = ($canAfficher OR $canAjouter OR $canModifier OR $canHistoriser OR $canDetruire);

$this->headTitle("Liste des mobilités");
?>

<h1 class="page-header">
    Liste des types de mobilité
</h1>

<?php if ($canAjouter) : ?>
    <a
        <?php /** @see \Carriere\Controller\MobiliteController::ajouterAction() */ ?>
        href="<?php echo $this->url('mobilite/ajouter', [], [], true); ?>"
        class="btn btn-primary ajax-modal" data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter un type de mobilité
    </a>
<?php endif; ?>

<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th> Code </th>
            <th> Libelle </th>
            <?php if ($canAction) : ?>
                <th class="action"> Action </th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($mobilites as $mobilite) : ?>
        <tr <?php if ($mobilite->estHistorise()) echo " class='historise'"; ?>>
            <td>
                <?php echo $mobilite->getCode(); ?>
            </td>
            <td>
                <?php echo $mobilite->getLibelle(); ?>
                <?php if ($mobilite->getDescription()) : ?>
                    <span class="icon icon-information" title="<?php echo $mobilite->getDescription(); ?>" data-bs-toggle="tooltip" data-bs-html="true"></span>
                <?php endif; ?>
            </td>
            <?php if ($canAction) : ?>
                <td class="action">
                <?php if ($canAfficher) : ?>
                    <a
                        <?php /** @see \Carriere\Controller\MobiliteController::afficherAction() */ ?>
                            href="<?php echo $this->url('mobilite/afficher', ['mobilite' => $mobilite->getId()], [], true); ?>"
                            title="Afficher" data-bs-toggle="tooltip" data-bs-html="true"
                            class="ajax-modal"
                    >
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br/>
                    <a
                            <?php /** @see \Carriere\Controller\MobiliteController::modifierAction() */ ?>
                            href="<?php echo $this->url('mobilite/modifier', ['mobilite' => $mobilite->getId()], [], true); ?>"
                            title="Modification" data-bs-toggle="tooltip" data-bs-html="true"
                            class="ajax-modal" data-event="modification"
                        >
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <br/>
                    <?php if ($mobilite->estHistorise()) : ?>
                        <a
                            <?php /** @see \Carriere\Controller\MobiliteController::restaurerAction() */ ?>
                                href="<?php echo $this->url('mobilite/restaurer', ['mobilite' => $mobilite->getId()], [], true); ?>"
                                title="Restauration" data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php else: ?>
                        <a
                            <?php /** @see \Carriere\Controller\MobiliteController::historiserAction() */ ?>
                                href="<?php echo $this->url('mobilite/historiser', ['mobilite' => $mobilite->getId()], [], true); ?>"
                                title="Historisation" data-bs-toggle="tooltip" data-bs-html="true"
                        >
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <br/>
                    <a
                        <?php /** @see \Carriere\Controller\MobiliteController::supprimerAction() */ ?>
                            href="<?php echo $this->url('mobilite/supprimer', ['mobilite' => $mobilite->getId()], [], true); ?>"
                            title="Destruction" data-bs-toggle="tooltip" data-bs-html="true"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="text-danger">
                            <span class="icon icon-unchecked"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>