<?php

namespace FicheMetier\Provider\Parametre;

class FicheMetierParametres {

    const TYPE = 'FICHE_METIER';

    const DISPLAY_TITRE = 'DISPLAY_TITRE';
    const DISPLAY_RESUME = 'DISPLAY_RESUME';
    const DISPLAY_RAISON = 'DISPLAY_RAISON';
    const DISPLAY_MISSION = 'DISPLAY_MISSION';
    const DISPLAY_ACTIVITE = 'DISPLAY_ACTIVITE';
    const DISPLAY_COMPETENCE = 'DISPLAY_COMPETENCE';
    const DISPLAY_COMPETENCE_SPECIFIQUE = 'DISPLAY_COMPETENCE_SPECIFIQUE';
    const DISPLAY_APPLICATION = 'DISPLAY_APPLICATION';
    const DISPLAY_CONTEXTE = 'DISPLAY_CONTEXTE';
    const DISPLAY_TENDANCE = 'DISPLAY_TENDANCE';

    const CODE_FONCTION = 'CODE_FONCTION';


}