<?php

use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\Formation;
use Formation\Entity\Db\Inscription;
use Formation\Provider\Etat\DemandeExterneEtats;
use Formation\Provider\Etat\InscriptionEtats;
use Formation\Provider\Privilege\DemandeexternePrivileges;
use Formation\Provider\Privilege\FormationinstanceinscritPrivileges;

/**
 * @var Inscription[] $inscriptions
 * @var DemandeExterne[] $demandes
 */

$canValiderResponsable = $this->isAllowed(FormationinstanceinscritPrivileges::getResourceId(FormationinstanceinscritPrivileges::INSCRIPTION_VALIDER_SUPERIEURE));

$array = [];
foreach ($inscriptions as $inscription) {
    if ($inscription->estNonHistorise()) {
        $formation = $inscription->getSession()->getFormation();
        $instance = $inscription->getSession();
        $array[$formation->getId()]["formation"] = $formation;
        $array[$formation->getId()]["instances"][$instance->getId()]['instance'] = $instance;
        $array[$formation->getId()]["instances"][$instance->getId()]['inscriptions'][] = $inscription;
    }
}

$attentes = [];
foreach ($inscriptions as $inscription) {
    if ($inscription->estNonHistorise() && $inscription->isEtatActif(InscriptionEtats::ETAT_DEMANDE)) {
        $formation = $inscription->getSession()->getFormation();
        $instance = $inscription->getSession();
        $attentes[$formation->getId()]["formation"] = $formation;
        $attentes[$formation->getId()]["instances"][$instance->getId()]['instance'] = $instance;
        $attentes[$formation->getId()]["instances"][$instance->getId()]['inscriptions'][] = $inscription;
    }
}

$dictionnaryInscriptions = [];
foreach ($inscriptions as $inscription) {
    $dictionnaryInscriptions[$inscription->getAgent()->getId()][] = $inscription;
}
usort($dictionnaryInscriptions,
    function ($a, $b) {
        /** @var Inscription[] $a */
        $aaa = $a[0]->getAgent()->getNomUsuel(). " " .$a[0]->getAgent()->getPrenom();
        $bbb = $b[0]->getAgent()->getNomUsuel(). " " .$b[0]->getAgent()->getPrenom();
        return $aaa > $bbb;
    }
);

$dictionnaryDemandes = [];
foreach ($demandes as $demande) {
    $dictionnaryDemandes[$demande->getAgent()->getId()][] = $demande;
}
usort($dictionnaryDemandes,
    function ($a, $b) {
        /** @var DemandeExterne[] $a */
        $aaa = $a[0]->getAgent()->getNomUsuel(). " " .$a[0]->getAgent()->getPrenom();
        $bbb = $b[0]->getAgent()->getNomUsuel(). " " .$b[0]->getAgent()->getPrenom();
        return $aaa > $bbb;
    }
);
?>

<h2> Demandes des formations en attente de validations <?php echo Formation::getAnnee(); ?>/<?php echo Formation::getAnnee()+1; ?> </h2>

<div class="row">
    <div class="col-md-6">
        <h3> Formations du plan de formation </h3>

        <?php /** @var Inscription[] $ds */ ?>
        <ul>
            <?php foreach ($dictionnaryInscriptions as $id => $ds) : ?>
                <li>
                    <?php echo $ds[0]->getAgent()->getDenomination(); ?>

                    <?php foreach ($ds as $d) : ?>
                        <br/>
                        <?php echo $this->etatinstance($d->getEtatActif()); ?>
                        <?php echo $d->getSession()->getFormation()->getLibelle(); ?>
                        (<?php echo $d->getSession()->getPeriode(); ?>)
                        <br/>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <?php if ($canValiderResponsable ) : ?>
                            <?php  /** @see \Formation\Controller\InscriptionController::validerResponsableAction() */ ?>
                            <a href="<?php echo $this->url('formation/inscription/valider-responsable', ['inscrit' => $d->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon icon-checked text-success">Valider</span></a>
                            <?php  /** @see \Formation\Controller\InscriptionController::refuserResponsableAction() */ ?>
                            <a href="<?php echo $this->url('formation/inscription/refuser-responsable', ['inscrit' => $d->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon icon-unchecked text-danger">Refuser</span></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="col-md-6">
        <h3>Demandes de stage externe</h3>

        <?php /** @var DemandeExterne[] $ds */ ?>
        <ul>
            <?php foreach ($dictionnaryDemandes as $id => $ds) : ?>
                <?php usort($ds, function (DemandeExterne $a, DemandeExterne $b) { return $a->getDebut() > $b->getDebut(); }); ?>
                <li>
                    <?php echo $ds[0]->getAgent()->getDenomination(); ?>

                    <?php foreach ($ds as $d) : ?>
                        <?php $canDemandeAfficher = $this->isAllowed($d, DemandeexternePrivileges::DEMANDEEXTERNE_AFFICHER); ?>
                        <br/>
                        <?php echo $this->etatinstance($d->getEtatActif()); ?>
                        <?php echo $d->getLibelle(); ?>
                        (<?php echo $d->getPeriodeAsString(); ?>)
                    <br>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <?php if ($canDemandeAfficher ) : ?>
                            <?php  /** @see \Formation\Controller\DemandeExterneController::afficherAction() */ ?>
                            <a href="<?php echo $this->url('formation/demande-externe/afficher', ['demande-externe' => $d->getId()], [], true); ?>" class="ajax-modal"> <span class="icon icon-voir"></span>Afficher</a>
                        <?php endif; ?>
                        <?php if ($d->isEtatActif(DemandeExterneEtats::ETAT_VALIDATION_AGENT)) : ?>
                            <?php if ($canValiderResponsable ) : ?>
                                <?php  /** @see \Formation\Controller\DemandeExterneController::validerResponsableAction() */ ?>
                                <a href="<?php echo $this->url('formation/demande-externe/valider-responsable', ["demande-externe" => $d->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon icon-checked text-success">Valider</span></a>
                                <?php  /** @see \Formation\Controller\DemandeExterneController::refuserResponsableAction() */ ?>
                                <a href="<?php echo $this->url('formation/demande-externe/refuser-responsable', ["demande-externe" => $d->getId()], [], true); ?>" class="ajax-modal" data-event="modification"> <span class="icon icon-unchecked text-danger">Refuser</span></a>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
