<?php

/**
 * @var Poste[] $postes
 */

use Application\Entity\Db\Poste;
use Application\Provider\Privilege\PostePrivileges;

$canAjouterPoste    = $this->isAllowed(PostePrivileges::getResourceId(PostePrivileges::AJOUTER));
$canAfficherPoste   = $this->isAllowed(PostePrivileges::getResourceId(PostePrivileges::AFFICHER));
$canModifierPoste   = $this->isAllowed(PostePrivileges::getResourceId(PostePrivileges::EDITER));
$canSupprimerPoste  = $this->isAllowed(PostePrivileges::getResourceId(PostePrivileges::EDITER));

$this->headTitle("Index des postes")
?>

<h1 class="page-header">
   Postes
   <span class="badge">
       <?php echo count($postes); ?>
    </span>
</h1>


<div class="main">

    <?php if ($canAjouterPoste) : ?>
        <a href="<?php echo $this->url('poste/ajouter', [], [], true); ?>"
           class="btn btn-primary action ajax-modal"
           data-event="modification"
        >
            <i class="fas fa-plus"></i>
            Ajouter un poste
        </a>

    <br/><br/>
    <?php endif; ?>


    <table class="table table-extra-condensed">
        <thead>
        <tr>
            <th> Numero de poste </th>
            <th> Fonction </th>
            <th> Domaine </th>
            <th> Affectation </th>
            <th> Action </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($postes as $poste) : ?>
            <tr>
                <td> <?php echo $poste->getNumeroPoste(); ?> </td>
                <td> <?php echo $poste->getFonction(); ?> </td>
                <td> <?php echo $poste->getDomaine(); ?> </td>
                <td>
                    <?php echo $poste->getStructure()->getLibelleCourt(); ?>
                </td>
                <td>
                    <?php if($canAfficherPoste) : ?>
                        <a href="<?php echo $this->url('poste/afficher', ['poste' => $poste->getId()], [], true); ?>"
                           class="ajax-modal"
                        >
                            <span class="icon voir" title="Afficher le poste"></span>
                        </a>
                    <?php endif; ?>
                    <?php if($canModifierPoste) : ?>
                        <a href="<?php echo $this->url('poste/modifier', ['poste' => $poste->getId()], [], true); ?>"
                           class="ajax-modal"
                           data-event="modification"
                        >
                            <span class="icon editer" title="Modifier le poste"></span>
                        </a>
                    <?php endif; ?>
                    <?php if($canSupprimerPoste) : ?>
                        <a href="<?php echo $this->url('poste/supprimer', ['poste' => $poste->getId()], [], true); ?>">
                            <span class="icon detruire" title="Supprimer le poste"></span>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

