<?php

/**
 * @var Agent $agent
 * @var Inscription[] $inscriptions
 */


use Application\Entity\Db\Agent;
use Formation\Entity\Db\Inscription;
use Formation\Provider\Etat\SessionEtats;

$formationValidees = [];
foreach ($inscriptions as $inscription) {
    if ($inscription->getSession()->estPrete() and $inscription->getListe() === Inscription::PRINCIPALE) $formationValidees[] = $inscription;
}

$formationsAttentes = [];
foreach ($inscriptions as $inscription) {
    if ($inscription->getSession()->estPrete() and $inscription->getListe() !== Inscription::PRINCIPALE) $formationsAttentes[] = $inscription;
    if ($inscription->getSession()->estPreparation()) $formationsAttentes[] = $inscription;
}

?>

<h2> Inscriptions validées </h2>


<?php if (empty($formationValidees)) : ?>
    <em> Aucune formation validée </em>
<?php else : ?>
    <?php foreach ($formationValidees as $inscription) : ?>
        <?php
        $instance = $inscription->getSession();
        $nbPlace = ($instance->getNbPlacePrincipale() + $instance->getNbPlaceComplementaire()) - (count($instance->getListePrincipale()) + count($instance->getListeComplementaire()));
        ?>
        <div class="row formation-inscription">
            <div class="col-md-8 description">
                <?php echo $this->sessionInformations($instance, 'bloc'); ?>
                <br/>
                <strong> Inscrit en liste <?php echo $inscription->getListe(); ?></strong>
            </div>
                <div class="col-md-4">
                    <a
                        <?php /** @see \Formation\Controller\InscriptionController::desinscriptionAction() */?>
                            href="
        <?php echo $this->url('formation/inscription/annuler-inscription', ['inscription' => $inscription->getId()], [], true); ?>"
                            class="btn btn-danger action ajax-modal" data-event="modification"
                    >
                        <span class="icon icon-unchecked"> J'annule mon inscription </span>
                    </a>
                    <?php if ($instance->isEtatActif(SessionEtats::ETAT_FORMATION_CONVOCATION) && $inscription->getListe() === Inscription::PRINCIPALE) : ?>
                        <br/>
                        <a
                            <?php /** @see \Formation\Controller\FormationInstanceDocumentController::genererConvocationAction() */?>
                                href="<?php echo $this->url('formation-instance/generer-convocation', ['inscription' => $inscription->getId()], [], true); ?>" class="btn btn-primary action"
                        >
                            <span class="icon icon-pdf"> Je télécharge ma convocation</span>
                        </a>
                    <?php endif; ?>
                </div>
        </div>
        <br/>
    <?php endforeach; ?>
<?php endif; ?>

<h2> Inscriptions en attentes </h2>


<?php if (empty($formationsAttentes)) : ?>
    <em> Aucune formation en attente de validation </em>
<?php else : ?>
    <?php foreach ($formationsAttentes as $inscription) : ?>
        <?php
        $instance = $inscription->getSession();
        $nbPlace = ($instance->getNbPlacePrincipale() + $instance->getNbPlaceComplementaire()) - (count($instance->getListePrincipale()) + count($instance->getListeComplementaire()));
        ?>
        <div class="row formation-inscription">
            <div class="col-md-8 description">
                <?php echo $this->sessionInformations($instance, 'bloc'); ?>
                <br/>
            </div>
                    <div class="col-md-4">
                        <a
                            <?php /** @see \Formation\Controller\InscriptionController::desinscriptionAction() */?>
                                href="
        <?php echo $this->url('formation/inscription/annuler-inscription', ['inscription' => $inscription->getId()], [], true); ?>"
                                class="btn btn-danger action ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-unchecked"> J'annule mon inscription </span>
                        </a>
                        <?php if ($instance->isEtatActif(SessionEtats::ETAT_FORMATION_CONVOCATION) && $inscription->getListe() === Inscription::PRINCIPALE) : ?>
                            <br/>
                            <a
                                <?php /** @see \Formation\Controller\FormationInstanceDocumentController::genererConvocationAction() */?>
                                    href="
        <?php echo $this->url('formation-instance/generer-convocation', ['inscription' => $inscription->getId()], [], true); ?>" class="btn btn-primary action"
                            >
                                <span class="icon icon-pdf"> Je télécharge ma convocation</span>
                            </a>
                        <?php endif; ?>
                    </div>
        </div>
        <br/>
    <?php endforeach; ?>
<?php endif; ?>
