<?php

/**
 * @var Agent $agent
 * @var DemandeExterne[] $stages
 */


use Application\Entity\Db\Agent;
use Formation\Entity\Db\DemandeExterne;
use Formation\Provider\Etat\DemandeExterneEtats;

$demandesValidees = [];
$demandesAttentes = [];
foreach ($stages as $demande) {
    if ($demande->isEtatActif(DemandeExterneEtats::ETAT_VALIDATION_DRH)) {
        $demandesValidees[] = $demande;
    } else {
        $demandesAttentes[] = $demande;
    }
}
?>

<h2> Foramtions hors plan de formation validées </h2>

<?php if (empty($demandesValidees)) : ?>
    <em> Aucune formation validée </em>
<?php else : ?>
    <?php foreach ($demandesValidees as $stage) : ?>
        <?php echo $this->demandeExterne($stage, ['action' => false]); ?>
    <?php endforeach; ?>
<?php endif; ?>

<h2> Formations hors plan de formation en attentes </h2>


<?php if (empty($demandesAttentes)) : ?>
    <em> Aucune formation en attente de validation </em>
<?php else : ?>
    <?php foreach ($demandesAttentes as $stage) : ?>
        <?php echo $this->demandeExterne($stage, ['action' => false]); ?>
    <?php endforeach; ?>
<?php endif; ?>
