<?php

use Application\Entity\Db\Agent;
use Formation\Entity\Db\Inscription;

/**
 * @see \Formation\Controller\AgentController::historiqueAction()
 * @var Agent $agent
 * @var Inscription[] $inscriptions
 */

$this->headTitle("Historique des formations de ". $agent->getDenomination(true));


usort($inscriptions, function (Inscription $a, Inscription $b) { return $a->getSession()->getDebut(true) <=> $b->getSession()->getDebut(true);});
?>

<?php foreach ($inscriptions as $inscription) : ?>
    <?php echo $this->inscription($inscription); ?>
<?php endforeach; ?>
