<?php

use Application\Entity\Db\Agent;
use Formation\Entity\Db\DemandeExterne;
use Formation\Entity\Db\FormationInstanceInscrit;
use UnicaenUtilisateur\Entity\Db\Role;
use UnicaenUtilisateur\Entity\Db\User;

/**
 * @see \Formation\Controller\AgentController::mesAgentsAction()
 * @var Agent[] $agents
 * @var User $user
 * @var Role $role
 *
 * @var FormationInstanceInscrit[] $inscriptionsValidees
 * @var DemandeExterne[] $demandesValidees
 * @var FormationInstanceInscrit[] $inscriptionsNonValidees
 * @var DemandeExterne[] $demandesNonValidees
 */

$nbAgent = count($agents)
?>

<h1 class="page-header">
    Mes agents
</h1>

<div class="row">
    <div class="col-md-7">
        Vous êtes le <?php echo $role->getLibelle(); ?> de <?php echo $nbAgent; ?> agent·s.
    </div>
    <div class="col-md-5">
        <?php /** @see \Formation\Controller\AgentController::listerMesAgentsAction() */ ?>
        <a href="<?php echo $this->url('formation/mes-agents/lister', [], [], true); ?>"
           class="btn btn-secondary ajax-modal">
            <span class="icon icon-lister"></span>
            Lister les agents dont je suis responsable
        </a>
    </div>
</div>

<div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="formation-demande-tab"
            data-bs-toggle="tab" data-bs-target="#formation-demande"
            type="button" role="tab" aria-controls="formation-demande" aria-selected="true">
        Demandes de formations
    </button>
    <button class="nav-link" id="formation-liste-tab"
            data-bs-toggle="tab" data-bs-target="#formation-liste"
            type="button" role="tab" aria-controls="formation-liste" aria-selected="true">
        Listes des formations
    </button>
</div>

<div class="tab-content">
    <div id="formation-demande" class="tab-pane">
        <?php echo $this->partial('partial/demande-formation', ['inscriptions' => $inscriptionsNonValidees, 'demandes' => $demandesNonValidees]); ?>
    </div>

    <div id="formation-liste" class="tab-pane">
        <?php echo $this->partial('partial/liste-formation', ['inscriptions' => $inscriptionsValidees, 'demandes' => $demandesValidees]); ?>
    </div>

    <!-- Extraction ------------------------------------------------------------------------------------->
    <div id="extraction" class="tab-pane">
<!--        --><?php //echo $this->partial('partial/extraction', ['structure' => $structure]); ?>
    </div>
</div>

<script>
    $(function () {
        let hash = $(location).attr('hash');
        let name = hash.substr(1);
        if (name === undefined || name === "") name = "formation-demande";

        $('button').removeClass('active');
        $('button#' + name + '-tab').addClass('active');
        $('div.tab-pane').hide().removeClass('active');
        $('div#' + name).show().addClass('active');

        //$('#' + name + '-tab').tab("show");
        $('button.nav-link').on('click', function (e) {
            let anchor = $(this).attr('aria-controls');
            $('div.tab-pane').hide().removeClass('active');
            $('div#' + anchor).show().addClass('active');
            $('button').removeClass('active');
            $('button#' + anchor + '-tab').addClass('active');
            // console.log(anchor);
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#" + anchor);
        });
    });

    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

