<?php

/**
 * @var Etat[] $etats
 * @var MailType[] $types
 * @var array $params
 */

use Mailing\Model\Db\MailType;
use UnicaenApp\Form\Element\SearchAndSelect;
use UnicaenEtat\Entity\Db\Etat;

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="icon filtrer"></span>
        Filtre des mails
    </div>
    <div class="panel-body">
        <form method="get" id="filtre" action="<?php echo $this->url(); ?>">
            <div class="row">
                <div class="col-md-3">
                    <?php
                    $structureF = new SearchAndSelect('adresse', ['label' => "Destinatires du mail :"]);
                    $structureF
                        ->setAutocompleteSource($this->url('mailing/rechercher-adresse'))
                        ->setSelectionRequired(true)
                        ->setAttributes([
                            'id' => 'adresse',
                            'placeholder' => "Adresse électronique",
                        ]);
                    ?>
                    <?php echo $this->formControlGroup($structureF); ?>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="etat">État du mail :</label>
                        <select id="etat" name="etat" class="selectpicker">
                            <option value=""> Tous les états </option>
                            <?php foreach($etats as $etat) : ?>
                            <option
                                    value="<?php echo $etat->getId(); ?>"
                                    data-content='<?php  echo $this->etatbadge($etat); ?> <?php echo str_replace("'", "", $etat->getLibelle()); ?>'
                                <?php if ($etat->getId() == $params['etat']) echo " selected "; ?>
                            >
                                <?php echo $etat->getLibelle(); ?>
                            </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label for="type">Type de mail :</label>
                        <select id="type" name="type" class="selectpicker">
                            <option value=""> Pas de typage particulière </option>
                            <?php foreach($types as $type) : ?>
                            <option value="<?php echo $type->getId(); ?>"
                                <?php if ($type->getId() == $params['type']) echo " selected "; ?>
                            >
                                <?php echo $type->getCode(); ?>
                            </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div class="zcol-md-3">
                    <br/>
                    <div class="pull-right">
                        <button class="btn btn-primary" id="clear">
                            <span class="icon effacer"></span>
                        </button>

                        <button class="btn btn-primary" id="filter" style="width:20rem;">
                            <span class="icon filtrer"></span>
                            Filtrer
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $("form#filtre").submit(function(e){
        e.preventDefault();
    });

    $('button#clear').click(function() {
        window.location.href = 'mailing';
    });

    $('button#filter').click(function() {
        let adresseId = $('input[name="adresse[id]').val();
        let adresseLabel = $('input[name="adresse[label]').val();
        let etatId = $('select#etat option:selected').val();
        let typeId = $('select#type option:selected').val();
        console.log("adresse=" + adresseLabel + " | " + "etat=" + etatId + " | " + "type=" + typeId);

        let query = "";
        query += "&adresse[id]=" + adresseId;
        query += "&adresse[label]=" + adresseLabel;
        query += "&etat=" + etatId;
        query += "&type=" + typeId;
        window.location.href = 'mailing?'+ query;
    });

    <?php if ($params['adresse'] !== null) :?>
    $('input[name="adresse[label]').val(" <?php echo $params['adresse']; ?> ");
    $('input[name="adresse[id]').val(<?php echo "1"; ?>);
    <?php endif; ?>
</script>