<?php

/**
 * @var MailType[] $types
 */

use Mailing\Model\Db\MailType;

$canVoirType            = true;
$canModifierType        = true;
$canHistoriserType      = true;
$canDetruireType        = true;
$canModifierContenu     = true;
?>


<a
    <?php /** @see  \Mailing\Controller\MailTypeController::ajouterAction() */ ?>
    href="<?php echo $this->url('mailing/type/ajouter', [], [], true); ?>"
    class="btn btn-primary ajax-modal action" data-event="modification"
>
    <span class="glyphicon glyphicon-plus"></span>
    Ajouter un Mail Type
</a>

<table class="table table-condensed">
    <thead>
        <tr>
            <th> Code </th>
            <th> Libellé</th>
            <th style="width: 5rem;"> Actif</th>
            <th style="width: 5rem;"> Content</th>
            <th style="width: 11rem;"> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($types as $type) : ?>
            <tr <?php if ($type->estHistorise()) echo " class='historisee'"; ?>>
                <td> <?php echo $type->getCode(); ?> </td>
                <td>
                    <?php echo $type->getLibelle(); ?>
                    <?php if ($type->getDescription() !== null) : ?>
                        <span class="glyphicon glyphicon-info-sign"
                              data-toggle="tooltip" data-html="true"
                              title="<?php echo $type->getDescription(); ?>"
                              >
                        </span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($type->isActif()) : ?>
                        <span class="badge" style="background-color: darkgreen;">&nbsp;</span>
                    <?php else: ?>
                        <span class="badge" style="background-color: darkred;">&nbsp;</span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($type->getContenu() !== null) : ?>
                        <span class="badge" style="background-color: darkgreen;"
                              title="<?php echo $type->getContenu()->getId(); ?> - <?php echo $type->getContenu()->getCode(); ?>"
                        >&nbsp;</span>
                    <?php else: ?>
                        <span class="badge" style="background-color: darkred;">&nbsp;</span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($canVoirType) : ?>
                        <a
                            <?php /** @see \Mailing\Controller\MailTypeController::afficherAction() */?>
                            href="<?php echo $this->url('mailing/type/afficher', ['mail-type' => $type->getId()], [], true); ?>"
                            data-toggle="tooltip" data-html="true"
                            class="ajax-modal"
                            title="Afficher les informations du mail type"
                            >
                            <span class="glyphicon glyphicon-eye-open"></span></a>
                    <?php endif; ?>

                    <?php if ($canModifierType) : ?>
                        <a
                            <?php /** @see \Mailing\Controller\MailTypeController::modifierAction() */?>
                                href="<?php echo $this->url('mailing/type/modifier', ['mail-type' => $type->getId()], [], true); ?>"
                                data-toggle="tooltip" data-html="true"
                                title="Modifier les informations du mail type"
                                class="ajax-modal" data-event="modification"
                        >
                            <span class="glyphicon glyphicon-pencil"></span></a>
                    <?php endif; ?>

                    <?php if ($canModifierContenu) : ?>
                        <a
                            <?php /** @see \Mailing\Controller\MailTypeController::modifierMailAction() */?>
                                href="<?php echo $this->url('mailing/type/modifier-mail', ['mail-type' => $type->getId()], [], true); ?>"
                                data-toggle="tooltip" data-html="true"
                                title="Modifier le contenu du mail type"
                                class="ajax-modal" data-event="modification"
                        >
                            <span class="glyphicon glyphicon-file"></span></a>
                    <?php endif; ?>

                    <?php if ($canHistoriserType) : ?>
                        <?php if ($type->estNonHistorise()) : ?>
                            <a
                                <?php /** @see \Mailing\Controller\MailTypeController::historiserAction() */?>
                                    href="<?php echo $this->url('mailing/type/historiser', ['mail-type' => $type->getId()], [], true); ?>"
                                    data-toggle="tooltip" data-html="true"
                                    title="Historiser les informations du mail type"
                            >
                                <span class="glyphicon glyphicon-trash"></span></a>
                        <?php else : ?>
                            <a
                                <?php /** @see \Mailing\Controller\MailTypeController::restaurerAction()  */?>
                                    href="<?php echo $this->url('mailing/type/restaurer', ['mail-type' => $type->getId()], [], true); ?>"
                                    data-toggle="tooltip" data-html="true"
                                    title="Restaurer les informations du mail type"
                            >
                                <span class="glyphicon glyphicon-leaf"></span></a>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if ($canDetruireType) : ?>
                        <a
                            <?php /** @see \Mailing\Controller\MailTypeController::detruireAction()  */?>
                                href="<?php echo $this->url('mailing/type/detruire', ['mail-type' => $type->getId()], [], true); ?>"
                                data-toggle="tooltip" data-html="true"
                                class="ajax-modal" data-event="modification"
                                title="Détruire le mail type"
                        >
                            <span class="glyphicon glyphicon-remove"></span></a>
                    <?php endif; ?>

                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
