<?php

/**
 * @var Mail[] $mails
 * @var Etat[] $etats
 * @var MailType[] $types
 * @var array $params
 */

use Mailing\Model\Db\Mail;
use Mailing\Model\Db\MailType;
use Mailing\Provider\Privilege\MailingPrivileges;
use UnicaenEtat\Entity\Db\Etat;

$canTest        = $this->isAllowed(MailingPrivileges::getResourceId(MailingPrivileges::MAILING_TEST));
$canAfficher    = $this->isAllowed(MailingPrivileges::getResourceId(MailingPrivileges::MAILING_AFFICHER));
$canReEnvoi     = $this->isAllowed(MailingPrivileges::getResourceId(MailingPrivileges::MAILING_REENVOI));
$canEffacer     = $this->isAllowed(MailingPrivileges::getResourceId(MailingPrivileges::MAILING_EFFACER));

$typeListe = [];
foreach ($types as $type) $typeListe[$type->getId()] = $type->getLibelle();
?>

<br/>
<?php echo $this->partial('partial/filtre', ['params' => $params, 'etats' => $etats, 'types' => $types ], [], true); ?>

<?php if ($canTest) : ?>
    <a
        <?php /** @see \Mailing\Controller\MailingController::mailTestAction() */?>
        href="<?php echo $this->url('mailing/mail-test', [], [] ,true);?>"
        class="btn btn-primary action"
    >
        <i class="far fa-envelope"></i>
        Envoie d'un mail de test
    </a>
<?php endif; ?>

<table class="table table-extra-condensed">
    <thead>
    <tr>
        <th> Status </th>
        <th> Date d'envoi </th>
        <th> Destinataires </th>
        <th> Typé </th>
        <th> Redir </th>
        <th> Lié </th>
        <th> Sujet </th>
        <th> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($mails as $mail) : ?>
        <tr>
            <td> <?php echo $this->etatbadge($mail->getStatusEnvoi()); ?> </td>
            <td> <?php echo $mail->getDateEnvoi()->format("H:i:s d/m/Y"); ?> </td>
            <td> <small><?php echo implode("<br/>",explode(",",$mail->getDestinatires())); ?></small> </td>
            <td>
                <?php if ($mail->getMailtypeId()) : ?>
                    <span class="icon ok" style="color:darkgreen;" data-toggle="tooltip" data-html="true" title="<?php echo $typeListe[$mail->getMailtypeId()]; ?>"></span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($mail->isRedirection()) : ?>
                    <span class="icon ok" style="color:darkgreen;" data-toggle="tooltip" data-html="true" title="A été redirigé"></span>
                <?php else : ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($mail->getAttachementType()) : ?>
                    <span class="icon ok" style="color:darkgreen;" data-toggle="tooltip" data-html="true" title="Lié à <?php echo $mail->getAttachementType(); ?>-<?php echo $mail->getAttachementId(); ?>"></span>
                <?php else : ?>
                <?php endif; ?>
            </td>
            <td> <small><?php echo $mail->getSujet(); ?> </small> </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <a class="ajax-modal" href="<?php echo $this->url('mailing/afficher', ['id' => $mail->getId()], [], true); ?>">
                        <i class="fas fa-eye"        title="Voir le mail"></i>
                    </a>
                <?php endif; ?>
                <?php if ($canReEnvoi) : ?>
                    <a  href="<?php echo $this->url('mailing/re-envoi', ['id' => $mail->getId()], [], true); ?>">
                        <i class="far fa-envelope"   title="Envoyer à nouveau le mail"></i>
                    </a>
                <?php endif; ?>
                <?php if ($canEffacer) : ?>
                    <a  href="<?php echo $this->url('mailing/effacer', ['id' => $mail->getId()], [], true); ?>">
                        <i class="fas fa-trash-alt"  title="Supprimer le mail de l'historique"></i>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
