<?php

/**
 * @var Seance $journee
 */

use Formation\Entity\Db\Inscription;
use Formation\Entity\Db\Seance;

$inscrits = $journee->getInstance()->getListePrincipale();
usort($inscrits, function (Inscription $a, Inscription $b) { return $a->getStagiaireDenomination(false) <=> $b->getStagiaireDenomination(false);});
$formation = $journee->getInstance()->getFormation();
?>

<h1>
    Feuille d'émargement
</h1>

<table>
    <tr>
        <th style="width:8rem; text-align:left; "> Intitulé </th>
        <td> <?php echo $formation->getLibelle(); ?> </td>
    </tr><tr>
        <th style="width:8rem; text-align:left; "> Date </th>

        <td>
            <?php if ($journee->getType() === Seance::TYPE_SEANCE) : ?>
                <?php echo $journee->getJour()->format('d/m/Y'); ?> de <?php echo $journee->getDebut(); ?> à <?php echo $journee->getFin(); ?>
            <?php else : ?>
                <?php echo $journee->getVolumeDebut()->format('d/m/Y'); ?> au <?php echo $journee->getVolumeFin()->format('d/m/Y'); ?>
            <?php endif; ?>
        </td>
    </tr><tr>
        <th style="width:8rem; text-align:left; ">Lieu </th>
        <td><?php echo $journee->getLieu(); ?></td>
    </tr>
</table>

<br/>

<h3> Inscriptions </h3>
<table class="emargement">
    <?php /** @var Inscription $inscrit */ ?>
    <?php foreach ($inscrits as $inscrit) : ?>
        <tr>
            <td>
                <strong> <?php echo $inscrit->getStagiaireDenomination(); ?> </strong> <br/>
                <?php echo $inscrit->getStagiaireStructure()?>
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<style>
    table.emargement {
        border: 1px solid black;
        border-collapse: collapse;
        width:100%;
    }

    table.emargement td {
        border: 1px solid black;
        width:50%;
    }
</style>