<?php

/**
 * @var Seance $journee
 */

use Formation\Entity\Db\FormationInstanceInscrit;
use Formation\Entity\Db\Seance;

$inscrits = $journee->getInstance()->getListePrincipale();
$formation = $journee->getInstance()->getFormation();
?>

<h1>
    Feuille d'émargement
</h1>

<table>
    <tr>
        <th style="width:8rem; text-align:left; "> Intitulé </th>
        <td> <?php echo $formation->getLibelle(); ?> </td>
    </tr><tr>
        <th style="width:8rem; text-align:left; "> Date </th>
        <td> <?php echo $journee->getJour()->format('d/m/Y'); ?> de <?php echo $journee->getDebut(); ?> à <?php echo $journee->getFin(); ?> </td>
    </tr><tr>
        <th style="width:8rem; text-align:left; ">Lieu </th>
        <td><?php echo $journee->getLieu(); ?></td>
    </tr>
</table>

<br/>

<table class="emargement">
    <?php /** @var FormationInstanceInscrit $inscrit */ ?>
    <?php foreach ($inscrits as $inscrit) : ?>
        <tr>
            <td>
                <strong> <?php echo $inscrit->getAgent()->getDenomination(); ?> </strong> <br/>
                <?php echo ($inscrit->getAgent()->getAffectationPrincipale() !== null)?$inscrit->getAgent()->getAffectationPrincipale()->getStructure()->getLibelleLong():"N.C."; ?>
            </td>
            <td>
                &nbsp;
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<style>
    table.emargement {
        border: 1px solid black;
        border-collapse: collapse;
        width:100%;
    }

    table.emargement td {
        border: 1px solid black;
        width:50%;
    }
</style>