<?php

use Formation\Entity\Db\ActionCoutPrevisionnel;
use Formation\Entity\Db\Formation;
use Formation\Entity\Db\PlanDeFormation;
use Formation\Provider\Privilege\CoutprevisionnelPrivileges;
use Formation\Provider\Privilege\FormationPrivileges;
use Formation\Provider\Privilege\PlanformationPrivileges;

/**
 * @see \Formation\Controller\ActionCoutPrevisionnelController::indexAction();
 * @var ActionCoutPrevisionnel[] $actionsCoutsPrevisionnels
 * @var PlanDeFormation[] $plans
 * @var Formation[] $actions
 * @var array $params
 */

$this->headTitle("Coûts prévisionnels associés aux actions de formations");

?>

<h1 class="page-header">
    Coûts prévisionnels associés aux actions de formations
</h1>

<?php echo $this->partial('partial/filtre', ['plans' => $plans, 'actions' => $actions, 'params' => $params]); ?>


<?php echo $this->coutsPrevisionnels($actionsCoutsPrevisionnels); ?>



