<?php


/**
 * @var ApplicationTheme[] $groupes
 * @var ApplicationTheme $groupe
 * @var string $activite
 */

use Element\Entity\Db\ApplicationTheme;

$actifId = "-";
if ($activite === "1") $actifId=1;
if ($activite === "0") $actifId=0;
?>

<div class="panel panel-default">
    <div class="panel panel-heading">
        <span class="icon icon-filtrer"></span>
        Filtre des applications
    </div>
    <div class="panel panel-body">

        <form id="filtre" action="<?php echo $this->url(); ?>" method="get">
            <div class="col-md-4">
                <label for="groupe">Groupe de l'application : </label>
                <select id="groupe" name="groupe" class="selectpicker" data-live-search="true">
                    <option value=""> Tous les groupes </option>
                    <?php foreach ($groupes as $groupe_) : ?>
                        <option value="<?php echo $groupe_->getId(); ?>" <?php if ($groupe_->getId() === $groupe) echo " selected "; ?>>
                            <?php echo $groupe_->getLibelle(); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-md-4">
                <label for="activite">État de l'application : </label>
                <select id="activite" name="activite" class="selectpicker">
                    <option value=""> Tous les états </option>
                    <option value="1" <?php if ($activite === "1") echo " selected "; ?>> Actif </option>
                    <option value="0" <?php if ($activite === "0") echo " selected "; ?>> Inactif </option>
                </select>
            </div>
            <!-- BOUTON -->
            <div class="col-md-4">
                <div class="pull-right">
                    <button class="btn btn-primary action" id="clear">
                        <span class="icon effacer"></span>
                    </button>

                    <button class="btn btn-primary action" id="filter">
                        <span class="icon icon-filtrer"></span>
                        Filtrer
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $("form#filtre").submit(function(e){
        e.preventDefault();
    });

    $('button#clear').click(function() {
        window.location.href = '?#application';
    });

    $('button#filter').click(function() {
        let groupeId = $('select#groupe option:selected').val();
        console.log( "groupe=" + groupeId);
        let activiteId = $('select#activite option:selected').val();
        console.log( "activite=" + activiteId);

        let query = "";
        query += "&groupe=" + groupeId;
        query += "&activite=" + activiteId;
        window.location.href = 'application?'+ query + '#application';
    });

    $('select#groupe option[value=<?php echo $groupe; ?>]').prop('selected', true);
    $('select#activite option[value=<?php echo $actifId; ?>]').prop('selected', true);
    console.log('<?php echo $groupe; ?>');
    console.log('<?php echo $actifId; ?>');

</script>
