<?php

use Indicateur\Entity\Db\Abonnement;

/**
 * @see \Indicateur\Controller\IndexController::indexAction()
 * @var Abonnement[] $abonnements
 * @var int[] $result
 */

$canLister = true;
$canAfficher = true;
$canDesabonnement = true;

?>

<h1 class="page-header">
    Mes abonnements à des indicateurs.
</h1>

<?php if ($canLister) : ?>
    <a href="<?php echo $this->url('mes-indicateurs/abonnement', [], [], true); ?>"
       class="btn btn-primary action ajax-modal" data-event="modification">
        <span class="icon ajouter"></span>
        S'abonner à un indicateur
    </a>
<?php endif; ?>

<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th> Indicateurs </th>
            <th> Effectifs </th>
            <th> Dernière maj </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($abonnements as $abonnement) : ?>
        <tr>
            <td> <?php echo $abonnement->getIndicateur()->getTitre(); ?> </td>
            <td> <?php echo $result[$abonnement->getIndicateur()->getId()]; ?> </td>
            <td> <?php echo $abonnement->getIndicateur()->getDernierRafraichissement()->format('d/m/Y à H:i'); ?> </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Indicateur\Controller\IndicateurController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('indicateur/afficher', ['indicateur' => $abonnement->getIndicateur()->getId()], [], true); ?>">
                        <span class="icon voir"></span></a>
                <?php endif; ?>
                <?php if ($canDesabonnement) : ?>
                    <?php /** @see \Indicateur\Controller\AbonnementController::resilierAction() */ ?>
                    <a href="<?php echo $this->url('abonnement/resilier', ['indicateur' => $abonnement->getIndicateur()->getId()], ['query' => ['retour' => $this->url('mes-indicateurs', [], [], true)]], true); ?>">
                        <span class="icon detruire"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>