-- select
--     concat(
--             'insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES (',
--             concat('(select id from unicaen_utilisateur_role urr where urr.role_id = ''', uur.role_id, ''')'),
--             ',',
--             concat('(select id from unicaen_privilege_privilege upp where upp.code = ''', upp.code, ''' and upp.categorie_id = (select id from unicaen_privilege_categorie where code =''', upc.code , '''))'),
--             ');'
--     )
-- from unicaen_privilege_privilege_role_linker l
--          join unicaen_privilege_privilege upp on l.privilege_id = upp.id
--          join unicaen_privilege_categorie upc on upp.categorie_id = upc.id
--          join unicaen_utilisateur_role uur on l.role_id = uur.id
-- where upc.namespace = 'Metier\Provider\Privilege';

-- MODULE METIER
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_supprimer' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_lister_agents' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_lister_agents' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_lister_agents' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_lister_agents' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_cartographie' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_cartographie' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_cartographie' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_cartographie' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice de la structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice (Entretien Professionnel)'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'metier_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='metier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice de la structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice (Entretien Professionnel)'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'reference_supprimer' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referenceMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_supprimer' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice de la structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice (Entretien Professionnel)'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'referentiel_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='referentielMetier')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice de la structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice (Entretien Professionnel)'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_supprimer' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'domaine_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='domaine')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_supprimer' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_ajouter' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Agent'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Autorité hiérarchique'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Responsable de structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Supérieur·e hiérarchique direct·e'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice de la structure'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice (Entretien Professionnel)'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_afficher' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Observateur·trice'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_index' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_modifier' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice technique'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Administrateur·trice fonctionnel·le'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
insert into unicaen_privilege_privilege_role_linker (role_id, privilege_id) VALUES ((select id from unicaen_utilisateur_role urr where urr.role_id = 'Directeur·trice des ressources humaines'),(select id from unicaen_privilege_privilege upp where upp.code = 'famille_professionnelle_historiser' and upp.categorie_id = (select id from unicaen_privilege_categorie where code ='familleProfessionnelle')));
