<?php

/**
 * @see \EntretienProfessionnel\Controller\CampagneController::indexAction()
 * @var Campagne[] $campagnes
 */

use EntretienProfessionnel\Provider\Privilege\CampagnePrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;

$canAfficher    = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_AFFICHER));
$canAjouter     = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_AJOUTER));
$canModifier    = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_MODIFIER));
$canHistoriser  = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_HISTORISER));
$canDetruire    = $this->isAllowed(CampagnePrivileges::getResourceId(CampagnePrivileges::CAMPAGNE_DETRUIRE));

?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Campagnes d'entretien professionnel
        </h1>

        <?php if ($canAjouter) : ?>
            <a
                <?php /** @see \EntretienProfessionnel\Controller\CampagneController::ajouterAction() */?>
                    href="<?php echo $this->url('entretien-professionnel/campagne/ajouter', [], [], true); ?>"
                    class="btn btn-primary action ajax-modal" data-event="modification"
            >
                <span class="icon icon-ajouter"></span>
                Ajouter une campagne
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-3">
        <a
            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::indexAction() */?>
                href="<?php echo $this->url('entretien-professionnel', [], [], true); ?>"
                class="btn btn-primary action"
        >
            <span class="icon icon-listing"></span>
            Accéder aux entretiens
        </a>
    </div>
</div>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th>Année</th>
        <th>Date de début</th>
        <th>Date de fin</th>
        <th>Précède</th>
        <th>#Entretiens</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($campagnes as $campagne) : ?>
        <tr class="<?php echo ($campagne->estHistorise())?"historise":""; ?>">
            <td> <?php echo $campagne->getAnnee(); ?> </td>
            <td> <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?> </td>
            <td> <?php echo $campagne->getDateFin()->format('d/m/Y'); ?> </td>
            <td> <?php echo ($campagne->getPrecede())?$campagne->getPrecede()->getAnnee():"---"; ?> </td>
            <td> <?php echo count($campagne->getEntretiensProfessionnels()); ?> </td>
            <td>
                <?php if ($canModifier) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\CampagneController::modifierAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/campagne/modifier', ['campagne' => $campagne->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                        data-bs-toggle="tooltip" data-bs-html="true"
                        title="Modification de la campagne <span class='highlight campagne'><?php echo $campagne->getAnnee(); ?></span>"
                    >
                        <span class="icon icon-editer"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($campagne->estNonHistorise()) : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\CampagneController::historiserAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/campagne/historiser', ['campagne' => $campagne->getId()], [], true); ?>"
                            data-bs-toggle="tooltip" data-bs-html="true"
                            title="Historisation de la campagne <span class='highlight campagne'><?php echo $campagne->getAnnee(); ?></span>"
                        >
                            <span class="icon icon-historiser"></span></a>
                    <?php else : ?>
                        <a
                            <?php /** @see \EntretienProfessionnel\Controller\CampagneController::restaurerAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/campagne/restaurer', ['campagne' => $campagne->getId()], [], true); ?>"
                            data-bs-toggle="tooltip" data-bs-html="true"
                            title="Restauration de la campagne <span class='highlight campagne'><?php echo $campagne->getAnnee(); ?></span>"
                        >
                            <span class="icon icon-restaurer"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <a
                        <?php /** @see \EntretienProfessionnel\Controller\CampagneController::detruireAction() */?>
                        href="<?php echo $this->url('entretien-professionnel/campagne/detruire', ['campagne' => $campagne->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                        data-bs-toggle="tooltip" data-bs-html="true"
                        title="Suppression de la campagne <span class='highlight campagne'><?php echo $campagne->getAnnee(); ?></span>"
                    >
                        <span class="icon icon-retirer"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $("body").on("modification", function (event) {
        event.div.modal('hide');
        window.location.reload();
    });
</script>
