<?php

use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\CampagneProgressionStructure;
use Structure\Entity\Db\Structure;

/**
 * @see \EntretienProfessionnel\Controller\CampagneController::progressionParStructuresAction()
 * @var Campagne $campagne
 * @var Structure $structure
 * @var CampagneProgressionStructure $progression
 */

$debug = true;
$displayLegende = true;
$onlyLegende = false;
$mode = 'div';

$this->headTitle();

$nbTotal = $progression->getNbTotal();
$nbValiderAgent = $progression->getNbComplet(); $ratioAgent = 0;
$nbValiderAutorite = $progression->getNbAutorite(); $ratioAutorite = 0;
$nbValiderObservation = $progression->getNbObservation(); $ratioObservation = 0;
$nbValiderSuperieur = $progression->getNbSuperieur(); $ratioSuperieur = 0;
$nbEncours = $progression->getNbPlanifier();
$nbSans = $progression->getNbManquant();


// duplicata du VH
if ($nbTotal !== 0) {
    $ratioAgent = $nbValiderAgent / $nbTotal * 100.0;
    $ratioAutorite = $nbValiderAutorite / $nbTotal * 100.0;
    $ratioSuperieur = $nbValiderSuperieur / $nbTotal * 100.0;
    $ratioObservation = $nbValiderObservation / $nbTotal * 100.0;
//    $ratioPlanifie = count($encours) / $nbTotal * 100.0;
    $ratioPlanifie = $nbEncours / $nbTotal * 100.0;
    $ratioSans = 100.0 - ($ratioAgent + $ratioAutorite + $ratioSuperieur + $ratioPlanifie + $ratioObservation);
}
?>

<h1 class="page-header">
    Affichage de l'avancement de la campagne <?php echo $campagne->getDate(); ?> <br>
    pour la structure <?php echo $structure->getLibelleLong(); ?>
</h1>



<?php if ($mode === 'div' AND !$onlyLegende) : ?>
    <?php if ($nbTotal !== 0) : ?>
        <div class="progress">
            <?php if ($ratioAgent > 0) : ?>
                <div class="progress-bar entretien-agent" role="progressbar" style="width: <?php echo $ratioAgent; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens complétés <?php echo $nbValiderAgent; ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioAgent); ?>%</div>
            <?php endif; ?>
            <?php if ($ratioAutorite > 0) : ?>
                <div class="progress-bar entretien-autorite" role="progressbar" style="width: <?php echo $ratioAutorite; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens validés par l'autorité hiérarchique <?php echo $nbValiderAutorite; ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioAutorite); ?>%</div>
            <?php endif; ?>
            <?php if ($ratioObservation > 0) : ?>
                <div class="progress-bar entretien-observation" role="progressbar" style="width: <?php echo $ratioObservation; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens avec des observations émises par l'agent·e <?php echo $nbValiderObservation; ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioObservation); ?>%</div>
            <?php endif; ?>
            <?php if ($ratioSuperieur > 0) : ?>
                <div class="progress-bar entretien-superieur" role="progressbar" style="width: <?php echo $ratioSuperieur; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens validés par le ou la supérieure hierarchique <?php echo $nbValiderSuperieur; ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioSuperieur); ?>%</div>
            <?php endif; ?>
            <?php if ($ratioPlanifie > 0) : ?>
                <div class="progress-bar planifie" role="progressbar" style="width: <?php echo $ratioPlanifie; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens planifiés <?php echo $nbEncours; ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioPlanifie); ?>%</div>
            <?php endif; ?>
            <?php if ($ratioSans > 0) : ?>
                <div class="progress-bar sans"   role="progressbar" style="width: <?php echo $ratioSans; ?>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
                     title="Entretiens non planifiés <?php echo $nbSans; ?>/<?php echo $nbTotal; ?>">
                    <?php echo round($ratioSans); ?>%</div>
            <?php endif; ?>
        </div>
    <?php else : ?>
        Aucun entretien professionnel obligatoire
    <?php endif; ?>
<?php endif; ?>
<?php if ($mode === 'table') : ?>
    <table style="width:100%;border:1px solid black;border-collapse: collapse;">
        <tr>
            <?php if ($ratioAgent > 0) : ?>
                <td class="entretien-agent" style="border:1px solid black;width: <?php echo $ratioAgent; ?>%;">
                    <?php echo round($ratioAgent); ?>%
                </td>
            <?php endif; ?>
            <?php if ($ratioAutorite > 0) : ?>
                <td class="entretien-autorite" style="border:1px solid black;width: <?php echo $ratioAutorite; ?>%;">
                    <?php echo round($ratioAutorite); ?>%
                </td>
            <?php endif; ?>
            <?php if ($ratioSuperieur > 0) : ?>
                <td class="entretien-superieur" style="border:1px solid black;width: <?php echo $ratioSuperieur; ?>%;">
                    <?php echo round($ratioSuperieur); ?>%
                </td>
            <?php endif; ?>
            <?php if ($ratioPlanifie > 0) : ?>
                <td class="planifie" style="border:1px solid black;width: <?php echo $ratioPlanifie; ?>%;">
                    <?php echo round($ratioPlanifie); ?>%
                </td>
            <?php endif; ?>
            <?php if ($ratioSans > 0) : ?>
                <td class="sans" style="border:1px solid black;width: <?php echo $ratioSans; ?>%;">
                    <?php echo round($ratioSans); ?>%
                </td>
            <?php endif; ?>
        </tr>
    </table>
<?php endif; ?>


<?php if ($displayLegende) : ?>
    <div style="margin:0.25rem;">
        <span class="legende entretien-agent">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens complétés <br/>
        <span class="legende entretien-autorite">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens validés par l'autorité hiérarchique <br/>
        <span class="legende entretien-observation">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens avec des observations de l'agent·e<br/>
        <span class="legende entretien-superieur">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens validés par le ou la supérieur·e hiérarchique <br/>
        <span class="legende planifie">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens planifiés <br/>
        <span class="legende sans">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> Entretiens non planifiés <br/>
    </div>
<?php endif; ?>


<?php if ($debug) : ?>
    <div class="row">
        <div class="col-md-6">
            <h4> Entretiens</h4>
            <ol>
                <?php foreach ($entretiens as $entretien): ?>
                    <li>
                        <?php echo $entretien->getAgent()->getDenomination(); ?>
                        <?php echo $this->etatinstance($entretien->getEtatActif()); ?>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
        <div class="col-md-6">
            <h4> Agents ayant obligations </h4>
            <ol>
                <?php foreach ($agents as $agent): ?>
                    <li>
                        <?php echo $agent->getDenomination(); ?>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>

<style>
    .sans {
        background-color: #960000;
    }
    .planifie {
        background-color: #ff6c0a;
    }
    .entretien-superieur {
        background-color: #ffcc01;
    }
    .entretien-observation {
        background-color: rgb(183,182,12);
    }
    .entretien-autorite {
        background-color: rgb(110,161,23);
    }
    .entretien-agent {
        background-color: rgb(34,139,34);
    }

    span.legende {
        border:1px solid black;
        border-radius: 0.25rem;
        min-width: 3rem;
        margin-right: 2rem;
    }
</style>
