<?php

/**
 * @see \EntretienProfessionnel\Controller\CampagneController::structureProgressionAction()
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent[] $obligatoires
 */

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;

?>

<?php /** @see \EntretienProfessionnel\View\Helper\CampagneAvancementViewHelper */ ?>
<?php echo $this->campagneAvancement($entretiens, $obligatoires, null, ['display-legende' => false]); ?>
