<?php

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use EntretienProfessionnel\Provider\Template\TexteTemplates;
use Structure\Entity\Db\Structure;
use UnicaenRenderer\Entity\Db\Rendu;
use UnicaenRenderer\Provider\Privilege\DocumenttemplatePrivileges;

/**
 * @see \EntretienProfessionnel\Controller\CampagneController::structureAction()
 * @var Campagne $campagne
 * @var Campagne[] $campagnes
 * @var Campagne[] $campagnesFutures
 *
 * @var Structure $structure
 * @var Structure[] $structures
 * @var Structure[] $selecteur
 *
 * @var Agent[] $agents
 * @var Agent[] $obligatoires
 * @var Agent[] $facultatifs
 *
 * @var EntretienProfessionnel[] $entretiens
 * @var EntretienProfessionnel[] $encours
 * @var EntretienProfessionnel[] $finalises
 * @var string[] $raison
 *
 * @var Rendu[] $templates
 */

$sansObligatoires = [];
$sansFacultatifs = [];
foreach ($obligatoires as $obligatoire) {
    if (!isset($entretiens[$obligatoire->getId()])) $sansObligatoires[] = $obligatoire;
}
foreach ($facultatifs as $facultatif) {
    if (!isset($entretiens[$facultatif->getId()])) $sansFacultatifs[] = $facultatif;
}

$canTemplateModifier = $this->isAllowed(DocumenttemplatePrivileges::getResourceId(DocumenttemplatePrivileges::DOCUMENTTEMPLATE_MODIFIER));

$this->headTitle("Campagne d'entretien professionnel " . $campagne->getAnnee() . " - " . $structure->getLibelleLong())
?>

<?php echo $this->partial('structure/structure/partial/entete', ['structure' => $structure, 'campagnes' => $campagnes, 'campagnesFutures' => [], 'current' => 'campagne_' . $campagne->getId(), 'selecteur' => $selecteur]); ?>

<div class="row">
    <div class="col-md-8">
        <h1 class="page-header">
            Campagne d'entretien professionnel <?php echo $campagne->getAnnee(); ?>
            <br>
            <?php echo $structure->getLibelleLong(); ?>
        </h1>
    </div>
    <div class="col-md-4">
        <label for="campagne">Sélectionner une campagne</label>
        <select id="campagne" name="campagne">
            <?php foreach ($campagnes as $campagne_) : ?>
                <option value="<?php echo $campagne_->getId(); ?>" <?php if ($campagne_ === $campagne) echo " selected "; ?>><?php echo $campagne_->getAnnee(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<div class="row">
    <div class="col-md-6">
        <h3> Information sur la campagne</h3>
        <?php echo $this->campagneInformation($campagne); ?>
    </div>
    <div class="col-md-6">
        <h3> Complétion de la campagne</h3>
        <?php echo $this->campagneAvancement($entretiens, $obligatoires); ?>
    </div>
</div>

<?php if (!empty($finalises)) : ?>
    <h2>
        Entretiens professionnels finalisés
        <span class="badge"> <?php echo count($finalises); ?> </span>
    </h2>

    <?php echo $this->entretienProfessionnelArray($finalises, ['affichages' => ['annee' => false], 'id' => 'complet', 'from-structure' => $structure->getId()]); ?>
<?php endif; ?>


<?php if (!empty($encours)) : ?>
    <h2>
        Entretiens professionnels en cours d'évaluation
        <span class="badge"> <?php echo count($encours); ?> </span>
    </h2>

    <?php echo $this->entretienProfessionnelArray($encours, ['affichages' => ['annee' => false], 'id' => 'encours', 'from-structure' => $structure->getId()]); ?>
<?php endif; ?>

<?php if (!empty($obligatoires)) : ?>
    <h2>
        Agent·es en attente d'entretien professionnel
        <span class="badge"> <?php echo count($sansObligatoires); ?> </span>
    </h2>
    <?php echo $this->convocationArray($sansObligatoires, $campagne, ['id' => 'sansentretien', 'raison' => $raison]); ?>
<?php endif; ?>

<?php if (!empty($facultatifs)) : ?>
    <h2>
        Agent·es sans obligation d'entretien professionnel
        <span class="badge"> <?php echo count($sansFacultatifs); ?> </span>
    </h2>

    <div class="alert alert-info">
        <div class="row">
            <div class="col-md-10">
                <?php echo $templates[TexteTemplates::EP_EXPLICATION_SANS_OBLIGATION]->getCorps(); ?>
            </div>
            <div class="col-md-2">
                <?php if ($canTemplateModifier) : ?>
                    <?php /** @see \UnicaenRenderer\Controller\TemplateController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('contenu/template/modifier', ['template' => $templates[TexteTemplates::EP_EXPLICATION_SANS_OBLIGATION]->getTemplate()->getId()], [], true); ?>"
                       class="action primary">
                        <span class="icon icon-editer"></span> Modifier
                    </a>
                <?php endif; ?>
            </div>

        </div>
    </div>
    <?php echo $this->convocationArray($sansFacultatifs, $campagne, ['id' => 'sansobligation', 'raison' => $raison]); ?>
<?php endif; ?>


<script>
    $('button#campagne<?php echo $campagne->getId(); ?>-tab').addClass('active');


    <?php /** @see \EntretienProfessionnel\Controller\CampagneController::structureAction() */ ?>
    let baseUrl = <?php echo "'" . $this->url('entretien-professionnel/campagne/structure', ['structure' => $structure->getId()], [], false) . "'"; ?>;

    $(document).ready(function () {
        $('#campagne').on('change', function () {
            window.location.href = baseUrl + '/' + $(this).val();
        });
    });

</script>