<?php

/**
 * @see \Application\Controller\ApplicationController::afficherApplicationElementAction()
 * @var ApplicationElement $applicationElement
 */

use Application\Entity\Db\ApplicationElement;

?>

<dl class="dl-horizontal">
    <dt> Libellé </dt>
    <dd> <?php echo $applicationElement->getApplication()->getLibelle(); ?> </dd>
    <dt> Niveau </dt>
    <dd> <?php echo ($applicationElement->getNiveauMaitrise())?$applicationElement->getNiveauMaitrise()->getLibelle():"Non précisé"; ?> </dd>
    <dt> Est compétence clef </dt>
    <dd> <?php echo ($applicationElement->isClef())?"Oui":"Non"; ?> </dd>
    <?php if ($applicationElement->getApplication()->getDescription() !== null) : ?>
        <dt> Description de <br/>la compétence </dt>
        <dd> <?php echo $applicationElement->getApplication()->getDescription(); ?> </dd>
    <?php endif; ?>
    <dt> Modificateur </dt>
    <dd> <?php echo $applicationElement->getHistoModificateur()->getDisplayName() ; ?> le <?php echo $applicationElement->getHistoModification()->format('d/m/Y à H:i:s'); ?> </dd>
    <?php if ($applicationElement->estHistorise()) : ?>
        <dt> Historisation </dt>
        <dd> <?php echo $applicationElement->getHistoDestructeur()->getDisplayName() ; ?> le <?php echo $applicationElement->getHistoDestruction()->format('d/m/Y à H:i:s'); ?> </dd>
    <?php endif; ?>
</dl>
