<?php

use Application\Entity\Db\Application;
use Application\Provider\Privilege\ApplicationPrivileges;

/**
 * @var Application[] $applications
 */

$canAfficher    = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::AFFICHER));
$canAjouter     = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::AJOUTER));
$canEditer      = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::EDITER));
$canEffacer     = $this->isAllowed(ApplicationPrivileges::getResourceId(ApplicationPrivileges::EFFACER));

$this->headTitle("Index des applications");
?>

<h1 class="page-header">
    Applications
    <span class="badge">
        <?php echo count($applications); ?>
    </span>
</h1>

<div class="main">
    <?php if ($canAjouter) : ?>
        <a  href="<?php echo $this->url('application/creer', [], [], true);?>"
            class="btn btn-primary action ajax-modal"
            data-event="modification"
        >
            <span class="icon ajouter"></span>
            Ajouter une application
        </a>
        <br/><br/>
    <?php endif; ?>

    <table id="datatable" class="table table-condensed">
        <thead>
            <tr>
                <th> Libelle</th>
                <th> Liens </th>
                <th> Actif </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($applications as $application): ?>
                <tr>
                    <td> <?php echo $application->getLibelle(); ?> </td>
                    <td> <a href="<?php echo $application->getUrl(); ?>"><?php echo $application->getUrl(); ?></a> </td>
                    <td>
                        <?php if ($application->isActif()) : ?>
                            <span class="badge" style="background-color: darkgreen;">&nbsp;</span>
                        <?php endif;?>
                    </td>
                    <td>
                        <?php if ($canAfficher) : ?>
                            <a href="<?php echo $this->url('application/afficher', ['id' => $application->getId()], [], true); ?>" class="ajax-modal">
                                <span class="icon voir"        title="Voir l'application"></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($canEditer) : ?>
                            <a href="<?php echo $this->url('application/editer', ['id' => $application->getId()], [], true); ?>"  class="ajax-modal" data-event="modification">
                                <span class="icon editer" title="Éditer l'application"></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($canEditer) : ?>
                            <a href="<?php echo $this->url('application/changer-status', ['id' => $application->getId()], [], true); ?>">
                                <span class="icon power"  title="Activer/Desactiver l'application"></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($canEffacer) : ?>
                            <a href="<?php echo $this->url('application/effacer', ['id' => $application->getId()], [], true); ?>">
                                <span class="icon detruire"  title="Supprimer l'application"></span>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>

<script>
    $(document).ready(function() {
        $('#datatable').DataTable( {
            language: {
                url: '/localisation/fr_FR.json'
            }
        });
    });

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>
