<?php

use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use UnicaenUtilisateur\Entity\Db\User;

/**
 * @see AgentController::afficherAction()
 * @var Agent   $agent
 * @var EntretienProfessionnel[] $entretiens
 * @var User[]  $responsables
 * @var array $parcoursArray
 */

$canVoir        = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VOIR);
$canAjouter     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_AJOUTER);
$canModifier    = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_MODIFIER);
$canHistoriser  = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_HISTORISER);
$canDetruire    = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_DETRUIRE);
$canValider     = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VALIDER);
$canInfoSource  = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_INFO_SOURCE));

$droits = [
    'afficher'        =>      $canVoir,
    'voir'            =>      $canVoir,
    'ajouter'         =>      $canAjouter,
    'modifier'        =>      $canModifier,
    'historiser'      =>      $canHistoriser,
    'detruire'        =>      $canDetruire,
    'valider'         =>      $canValider,
    'voirHistorique'  =>      $canDetruire,
];

$options  = [];
$options['texte'] = true;
$options['droits'] = $droits;
$options['retour'] = $this->url('agent/afficher', ['agent' => $agent->getId()], [], true);

$this->headTitle("Affichage de l'agent : " . $agent->getDenomination());

?>

<h1 class="page-header">
    Affichage de l'agent <br/>
    <strong><?php echo $agent->getDenomination(); ?></strong>
</h1>

<h2> Informations générales sur l'agent </h2>


    <div class="row">
        <div class="col-md-6">
             Informations générales "publiques"
            <dl>
                <dt> Prénom </dt>
                <dd>
                    <?php echo $agent->getPrenom(); ?>
                </dd>
                <dt> Nom </dt>
                <dd>
                    <?php echo $agent->getNomUsuel(); ?>
                </dd>
                <dt> Quotité travaillée </dt>
                <dd>
                    <?php if($quotite = $agent->getQuotiteCourante()) : ?>
                        <?php echo $quotite->getQuotite(); ?>%
                    <?php else: ?>
                        100%
                    <?php endif; ?>
                </dd>
            </dl>
        </div>
        <div class="col-md-6">
            <?php if ($canInfoSource) : ?>
                 Informations générales "application"
                <dl>
                    <dt> Identifiant sources </dt>
                    <dd>
                        OCTOPUS - <?php echo $agent->getId(); ?> <br/>
                        HARPEGE - <?php echo $agent->getHarpId(); ?>
                    <dt> Compte associé </dt>
                    <dd>
                        Agent : <?php echo $agent->getLogin(); ?> (<?php echo $agent->getEmail(); ?>) <br/>
                        <?php if($agent->getUtilisateur()) : ?>
                            Utilisateur : <?php echo $agent->getUtilisateur()->getUsername(); ?> (<?php echo $agent->getUtilisateur()->getEmail(); ?>)
                        <?php else: ?>
                            <span class="probleme">
                                <span class="icon attention"></span>
                                <em> Aucun compte lié à l'agent </em>
                            </span>
                        <?php endif; ?>
                    </dd>
                    <dt> Responsables hiérarchiques</dt>
                    <dd>
                        <?php if ($responsables !== null AND !empty($responsables)) : ?>
                            <ul>
                                <?php foreach ($responsables as $responsable) : ?>
                                    <li> <?php echo $responsable->getDisplayName(); ?> </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else : ?>
                            <span class="probleme">
                                <span class="icon attention"></span>
                                <em> Aucun responsable de remonté </em>
                            </span>

                        <?php endif; ?>
                    </dd>
                </dl>
            <?php endif; ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <h2>Affectation(s)</h2>
            <?php foreach ($agent->getAffectationsActifs() as $affectation) : ?>
                <?php echo $this->agentAffectation($affectation, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
            <?php endforeach; ?>
        </div>
        <div class="col-md-3">
            <h2>Statut(s)</h2>
            <?php foreach ($agent->getStatutsActifs() as $statut) : ?>
                <?php echo $this->agentStatut($statut, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
            <?php endforeach; ?>
        </div>
        <div class="col-md-6">
            <h2>Grade(s)</h2>
        <?php foreach ($agent->getGradesActifs() as $grade) : ?>
            <?php echo $this->agentGrade($grade, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
        <?php endforeach; ?>
        </div>
    </div>
    <a
        <?php /** @see \Application\Controller\AgentController::afficherStatutsGradesAction() */?>
        href="<?php echo $this->url('agent/afficher-statuts-grades', ['agent' => $agent->getId()], [], true); ?>"
        class="ajax-modal"
    >
        <span class="icon voir"></span> Listing de tous les affectations, statuts et grades
    </a>

    <?php echo $this->partial('partial/fiche-poste', ['fichespostes' => $agent->getFiches()], []); ?>

    <?php echo $this->partial('partial/entretien-professionnel',
        ['entretiens' => $entretiens, 'agent' => $agent, "droits" => $droits]
    , []); ?>

    <?php echo $this->partial('partial/mission-specifique', ['missions' => $agent->getMissionsSpecifiques(), 'agent' => $agent,  "droits" => $droits], []); ?>

    <!-- Parcours de formation -------------------------------------------------------------------------------------------->

    <h2>
        Parcours de formation
    </h2>

    <div class="alert alert-info">
        <strong><span class="icon attention"></span> Affichage des parcours de formations attachés à votre catégorie, domaines professionnels et métier.</strong> <br/>
        Il est possible qu'un domaine ou un métier ne possède pas de parcours.

    </div>

    <?php
    echo $this->partial('partial/parcours-de-formation.phtml', ['parcoursArray' => $parcoursArray, 'agent' => $agent], [], true);
    ?>


    <h2> Applications, compétences et formations</h2>

    <div class="alert alert-info">
        <strong><span class="icon attention"> Affichage des applications, compétences et formations directement liées à l'agent.</strong> <br/>
        Dans ces listes, les applications, compétences et formations associées aux fiches de postes d'un agent ne sont pas mentionnées.
    </div>

    <!-- APPLICATION ------------------------------------------------------------------------------------------------------>
    <?php echo $this->applicationBloc($agent->getApplicationDictionnaire(), $agent, $options); ?>

    <!-- COMPETENCE ------------------------------------------------------------------------------------------------------->
    <?php echo $this->competenceBloc($agent->getCompetenceDictionnaire(), $agent, $options); ?>

    <!-- FORMATIONS ------------------------------------------------------------------------------------------------------->

    <?php
    /** @see \Application\View\Helper\AgentFormationViewHelper */
    echo $this->agentFormation($agent, $options);
    ?>

    <?php echo $this->partial('partial/portfolio', ['fichiers' => $agent->getFichiers(), 'agent' => $agent, 'droits' => $droits], []); ?>




<style>
    table.parcours-de-formation {
        width:95%;
    }

    table.parcours-de-formation th {
        padding: 0.5rem;
        color: white;
    }
    table.parcours-de-formation td.libelle {
        padding-left: 1rem;
        width:80%;
    }
    table.parcours-de-formation td.formation {
        text-align: center;
    }
</style>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>