<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentGrade;
use Application\Entity\Db\AgentStatut;

/**
 * @see \Application\Controller\AgentController::afficherStatutsGradesAction()
 * @var string $title
 * @var Agent $agent
 * @var AgentStatut[] $statuts
 * @var AgentGrade[] $grades
 */

$this->headTitle($title)

?>

<div class="row">
    <div class="col-md-4">
        <h2> Statuts </h2>
        <?php foreach ($statuts as $statut) : ?>
            <?php echo $this->agentStatut($statut, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
        <?php endforeach; ?>
    </div>
    <div class="col-md-8">
        <h2> Grades </h2>
        <?php foreach ($grades as $grade) : ?>
            <?php echo $this->agentGrade($grade, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
        <?php endforeach; ?>
    </div>
</div>


