<?php

/**
 * @see AgentController::afficherFormationAction()
 * @var FormationElement $formationElement
 * @var Agent $agent
 */

use Application\Entity\Db\Agent;
use Formation\Entity\Db\FormationElement;

$type = null;
$annee = null;
if ($formationElement->getCommentaire() !== null) {
    $split = explode(" - ", $formationElement->getCommentaire());
    $type = $split[1];
    $annee = $split[0];
}
?>

<div class="row">
    <div class="col-md-6">
        <dl>
            <dt> Agent </dt>
            <dd> <?php echo $agent->getDenomination(); ?></dd>
            <dt> Formation </dt>
            <dd> <?php echo $formationElement->getFormation()->getLibelle(); ?></dd>
            <dt> Type de formation </dt>
            <dd> <?php echo ($type)?:"Non renseigné"; ?></dd>
            <dt> Année de formation </dt>
            <dd> <?php echo ($annee)?:"Non renseignée"; ?></dd>
            <dt> Validation </dt>
            <dd>
                <?php if ($formationElement->getValidation() === null) : ?>
                    Aucune validation
                <?php else: ?>
                    <?php $validation = $formationElement->getValidation(); ?>
                    <?php if ($validation->getValeur() === null) : ?>
                        <span
                            style="color:darkgreen;"
                            title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                    <span class="icon ok"></span>
                                    Validée
                                </span>
                    <?php else: ?>
                    <span
                        style="color:darkred;"
                        title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                    <span class="icon ko"></span>
                                Refusée
                    <?php endif; ?>
                <?php endif; ?>
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl>
            <dt> Dernière modification </dt>
            <dd>
                <?php echo $formationElement->getHistoModification()->format('d/m/Y à H:i:s'); ?>
                <br/>
                <?php echo $formationElement->getHistoModificateur()->getDisplayName(); ?>
            </dd>
        </dl>

        <?php if ($formationElement->estHistorise()) : ?>
            <dl>
                <dt> Historisée </dt>
                <dd>
                    <?php echo $formationElement->getHistoDestruction()->format('d/m/Y à H:i:s'); ?>
                    <br/>
                    <?php echo $formationElement->getHistoDestructeur()->getDisplayName(); ?>
                </dd>
            </dl>
        <?php endif; ?>
    </div>
</div>
