<?php

use Agent\Entity\Db\AgentAffectation;
use Agent\Entity\Db\AgentGrade;
use Agent\Entity\Db\AgentQuotite;
use Agent\Entity\Db\AgentStatut;
use Application\Entity\Db\Agent;
use Agent\Entity\Db\AgentEchelon;
use Application\Entity\Db\AgentMissionSpecifique;
use Application\Entity\Db\AgentMobilite;
use Application\Entity\Db\FichePoste;
use Application\Provider\Parametre\AgentParametres;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;
use UnicaenParametre\Entity\Db\Parametre;

/**
 * @see Application\Controller\AgentController::afficherAction()
 * @var Agent $agent
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent[] $superieures
 * @var Agent[] $autorites
 * @var FichePoste[] $fichespostes
 * @var FichePoste $ficheposte
 * @var AgentMissionSpecifique[] $missions
 * @var AgentAffectation[] $affectations
 * @var AgentStatut[] $statuts
 * @var AgentGrade[] $grades
 * @var AgentQuotite|null $quotite
 * @var AgentEchelon[] $echelons
 *
 * @var array $applications
 * @var string $intranet
 *
 * @var AgentMobilite[] $mobilites
 * @var Parametre[] $parametres
 *
 */

$displayAcquis = false;

if ($agent !== null) {
    $canVoir = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
    $canAjouter = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_AJOUTER);
    $canModifier = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_MODIFIER);
    $canHistoriser = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_HISTORISER);
    $canDetruire = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_DETRUIRE);
    $canValider = $this->isAllowed($agent, AgentPrivileges::AGENT_ELEMENT_VALIDER);
    $canAfficherMission = $canVoir;

    $droits = [
        'afficher' => $canVoir,
        'voir' => $canVoir,
        'ajouter' => $canAjouter,
        'modifier' => $canModifier,
        'historiser' => $canHistoriser,
        'detruire' => $canDetruire,
        'valider' => $canValider,
        'voirHistorique' => $canDetruire,
        'afficherMission' => $canAfficherMission,
    ];

    $options = [];
    $options['acquis'] = true;
    $options['texte'] = true;
    $options['droits'] = $droits;
    $options['retour'] = $this->url('agent/afficher', ['agent' => $agent->getId()], [], true);
    $options['actions'] = [
        'afficher' => true, 'ajouter' => $canAjouter, 'modifier' => $canModifier, 'supprimer' => $canDetruire, 'valider' => $canValider
    ];

    $this->headTitle("Affichage de l'agent : " . $agent->getDenomination());
}
?>

<?php if ($agent !== null) : ?>
    <h1 class="page-header">
        Affichage de l'agent <br/>
        <strong><?php echo $agent->getDenomination(); ?></strong>
    </h1>

    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <?php if (!isset($parametres[AgentParametres::ONGLET_INFORMATIONS]) || $parametres[AgentParametres::ONGLET_INFORMATIONS]->getValeur() !== "false") : ?>
            <button class="nav-link active" id="informations-tab"
                    data-bs-toggle="tab" data-bs-target="#informations"
                    type="button" role="tab" aria-controls="informations" aria-selected="true">
                Informations <br/> générales
            </button>
        <?php endif; ?>
        <?php if (!isset($parametres[AgentParametres::ONGLET_FICHES]) || $parametres[AgentParametres::ONGLET_FICHES]->getValeur() !== "false") : ?>
            <button class="nav-link" id="fiches-tab"
                    data-bs-toggle="tab" data-bs-target="#fiches"
                    type="button" role="tab" aria-controls="fiches" aria-selected="true">
                Fiches de poste et <br/> missions spécifiques
            </button>
        <?php endif; ?>
        <?php if (!isset($parametres[AgentParametres::ONGLET_ACQUIS]) || $parametres[AgentParametres::ONGLET_ACQUIS]->getValeur() !== "false") : ?>
            <button class="nav-link" id="acquis-tab"
                    data-bs-toggle="tab" data-bs-target="#acquis"
                    type="button" role="tab" aria-controls="acquis" aria-selected="true">
                Acquis de l'agent <br/> &nbsp;
            </button>
        <?php endif; ?>
        <?php if (!isset($parametres[AgentParametres::ONGLET_PORTFOLIO]) || $parametres[AgentParametres::ONGLET_PORTFOLIO]->getValeur() !== "false") : ?>
            <button class="nav-link" id="portfolio-tab"
                    data-bs-toggle="tab" data-bs-target="#portfolio"
                    type="button" role="tab" aria-controls="portfolio" aria-selected="true">
                Portfolio <br/> &nbsp;
            </button>
        <?php endif; ?>
        <?php if (!isset($parametres[AgentParametres::ONGLET_MOBILITES]) || $parametres[AgentParametres::ONGLET_MOBILITES]->getValeur() !== "false") : ?>
            <button class="nav-link" id="mobilite-tab"
                    data-bs-toggle="tab" data-bs-target="#mobilite"
                    type="button" role="tab" aria-controls="mobilite" aria-selected="true">
                Déclaration de <br/> mobilités
            </button>
        <?php endif; ?>
    </div>

    <div>
        <div class="tab-content">
            <?php if (!isset($parametres[AgentParametres::ONGLET_INFORMATIONS]) || $parametres[AgentParametres::ONGLET_INFORMATIONS]->getValeur() !== "false") : ?>
                <div id="informations" class="tab-pane fade show" role="tabpanel" aria-labelledby="informations-tab">

                    <?php echo $this->partial('partial/informations-generales',
                        ['agent' => $agent,
                            'affectations' => $affectations,
                            'superieures' => $superieures, 'autorites' => $autorites,
                            'statuts' => $statuts, 'echelons' => $echelons, 'grades' => $grades, 'quotite' => $quotite]); ?>
                </div>

            <?php endif; ?>
            <?php if (!isset($parametres[AgentParametres::ONGLET_FICHES]) || $parametres[AgentParametres::ONGLET_FICHES]->getValeur() !== "false") : ?>

                <div id="fiches" class="tab-pane " role="tabpanel">
                    <?php echo $this->partial('partial/fiche-poste',
                        ['fichespostes' => $fichespostes, 'agent' => $agent, 'droits' => $droits], []); ?>
                    <?php echo $this->partial('partial/mission-specifique', ['missions' => $missions, 'agent' => $agent, "options" => $options['actions']], []); ?>
                </div>


            <?php endif; ?>
            <?php if (!isset($parametres[AgentParametres::ONGLET_ACQUIS]) || $parametres[AgentParametres::ONGLET_ACQUIS]->getValeur() !== "false") : ?>

                <div id="acquis" class="tab-pane " role="tabpanel">
                    <h2> Applications, compétences et formations</h2>

                    <div class="alert alert-info">
                        <strong><span class="icon icon-attention"> Affichage des applications, compétences et formations directement liées à l'agent.</strong>
                        <br/>
                        Dans ces listes, les applications, compétences et formations associées aux fiches de postes d'un
                        agent ne sont pas mentionnées.
                    </div>

                    <!--                --><?php //if ($displayAcquis === true) : ?>
                    <!-- APPLICATION ------------------------------------------------------------------------------------------------------>
                    <?php echo $this->applicationBloc($agent->getApplicationDictionnaireComplet(), $agent, $options); ?>

                    <!-- COMPETENCE ------------------------------------------------------------------------------------------------------->
                    <?php echo $this->competenceBloc($agent->getCompetenceDictionnaireComplet(), $agent, $options); ?>
                    <!--                --><?php //endif; ?>

                </div>
            <?php endif; ?>
            <?php if (!isset($parametres[AgentParametres::ONGLET_PORTFOLIO]) || $parametres[AgentParametres::ONGLET_PORTFOLIO]->getValeur() !== "false") : ?>
                <div id="portfolio" class="tab-pane " role="tabpanel">
                    <?php echo $this->partial('partial/portfolio', ['fichiers' => $agent->getFichiers(), 'agent' => $agent, 'droits' => $droits], []); ?>
                </div>
            <?php endif; ?>
            <?php if (!isset($parametres[AgentParametres::ONGLET_MOBILITES]) || $parametres[AgentParametres::ONGLET_MOBILITES]->getValeur() !== "false") : ?>
                <div id="mobilite" class="tab-pane " role="tabpanel">
                    <?php echo $this->partial('partial/mobilite', ['agent' => $agent, 'mobilites' => $mobilites], []); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>


<script>
    $(function () {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "informations";

        $('button').removeClass('active');
        $('button#' + name + '-tab').addClass('active');
        $('div.tab-pane').hide().removeClass('active');
        $('div#' + name).show().addClass('active');

        //$('#' + name + '-tab').tab("show");
        $('button.nav-link').on('click', function (e) {
            let anchor = $(this).attr('aria-controls');
            $('div.tab-pane').hide().removeClass('active');
            $('div#' + anchor).show().addClass('active');
            $('button').removeClass('active');
            $('button#' + anchor + '-tab').addClass('active');
            // console.log(anchor);
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#" + anchor);
        });
    });

    $(function () {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>