<?php

use Application\Entity\Db\Agent;
use UnicaenUtilisateur\Entity\Db\Role;
use UnicaenUtilisateur\Entity\Db\User;

/**
 * @see AgentController::afficherAction()
 * @var Agent   $agent
 * @var User    $user
 * @var Role    $role
 */

$canVoir = true;
$canAjouter = true;
$canModifier = true;
$canHistoriser = true;
$canDetruire = true;
$canValider = true;

$this->headTitle("Affichage de l'agent : " . $agent->getDenomination());
?>

<h1 class="page-header">
    Affichage de l'agent <br/>
    <strong><?php echo $agent->getDenomination(); ?></strong>
</h1>

<div class="main">

    <h2> Informations générales sur l'agent </h2>

    <div class="row">
        <div class="col-md-8">
            <!-- Information générale "public" -->
            <dl>
                <dt> Prénom </dt>
                <dd>
                    <?php echo $agent->getPrenom(); ?>
                </dd>
                <dt> Nom </dt>
                <dd>
                    <?php echo $agent->getNomUsuel(); ?>
                </dd>
                <dt> Quotité travaillée
                    <?php if ($canModifier): ?>
                        <a
                            <?php /** @see \Application\Controller\AgentController::modifierAction() */?>
                            href="<?php echo $this->url('agent/modifier', ['agent' => $agent->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                        >
                            <span class="icon editer" data-toggle="tooltip" title="Modifier la quotité travaillée"></span></a>
                    <?php endif; ?>
                </dt>
                <dd>
                    <?php if($agent->getQuotite()) : ?>
                        <?php echo $agent->getQuotite(); ?>%
                    <?php else: ?>
                        <span class="probleme">
                            <span class="icon attention"></span>
                            <em> Aucune quotité de renseignée </em>
                        </span>
                    <?php endif; ?>
                </dd>
        </div>
        <div class="col-md-4">
            <!-- Information générale "application" -->
            <dl>
                <dt> Identifiant source </dt>
                <dd>
                    <?php if($agent->getSourceId()) : ?>
                        <?php echo $agent->getSourceName(); ?>
                    -
                        <?php echo $agent->getSourceId(); ?>
                    <?php else: ?>
                        <span class="probleme">
                            <span class="icon attention"></span>
                            <em> Aucune source pour cet agent </em>
                        </span>
                    <?php endif; ?>
                <dt> Compte associé </dt>
                <dd>
                    <?php if($agent->getUtilisateur()) : ?>
                        <?php echo $agent->getUtilisateur()->getUsername(); ?>
                    <?php else: ?>
                        <span class="probleme">
                            <span class="icon attention"></span>
                            <em> Aucun compte lié à l'agent </em>
                        </span>
                    <?php endif; ?>
                </dd>
            </dl>
        </div>
    </div>

    <h2> Statuts et grades </h2>

    <div class="row">
        <div class="col-md-4">
            <?php foreach ($agent->getStatutsActifs() as $statut) : ?>
                <?php echo $this->agentStatut($statut, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
            <?php endforeach; ?>
        </div>
        <div class="col-md-8">
        <?php foreach ($agent->getGradesActifs() as $grade) : ?>
            <?php echo $this->agentGrade($grade, ['structure' => true, 'periode' => true, 'temoin' => true]); ?>
        <?php endforeach; ?>
        </div>
    </div>

    <a
        <?php /** @see \Application\Controller\AgentController::afficherStatutsGradesAction() */?>
        href="<?php echo $this->url('agent/afficher-statuts-grades', ['id' => $agent->getId()], [], true); ?>"
        class="ajax-modal"
    >
        Listing de tous les statuts et grades
    </a>

    <?php echo $this->partial('partial/fiche-poste', ['fichespostes' => $agent->getFiches()], []); ?>

    <?php echo $this->partial('partial/entretien-professionnel',
        ['entretiens' => $agent->getEntretiensProfessionnels(), 'user' => $user, 'role' => $role]
    , []); ?>

    <?php echo $this->partial('partial/mission-specifique', ['missions' => $agent->getMissionsSpecifiques(), 'agent' => $agent], []); ?>

    <h2> Applications, compétences et formations</h2>

    <div class="alert alert-info">
        <strong><span class="icon attention"> Affichage des applications, compétences et formations directement liées à l'agent.</strong> <br/>
        Dans ces listes, les applications, compétences et formations associées aux fiches de postes d'un agent ne sont pas mentionnées.
    </div>

    <div class="blocs">
        <div class="bloc">
            <h3>
                <span class="icon application"></span>
                Applications
                <?php if ($canAjouter) : ?>
                    <a
                            <?php /** @see \Application\Controller\AgentController::ajouterAgentApplicationAction() */?>
                            href="<?php echo $this->url('agent/ajouter-agent-application', ['agent' => $agent->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon ajouter" title="Ajouter une application maîtriser par l'agent"></span>
                    </a>
                <?php endif; ?>
            </h3>
            <ul>
            <?php foreach ($agent->getApplications() as $application) : ?>
                <li>
                    <?php echo $application->getApplication()->getLibelle(); ?>
                    <br/>
                    <?php echo $application->getType(); ?>
                    - &nbsp;
                    <?php if ($application->getValidation()) : ?>
                        <?php $validation = $application->getValidation(); ?>
                        <?php if ($validation->getValeur() === null) : ?>
                            <span
                                    style="color:darkgreen;"
                                    title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                <span class="icon ok"></span>
                                Validée
                            </span>
                        <?php else: ?>
                            <span
                                style="color:darkred;"
                                title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                <span class="icon ko"></span>
                            Refusée
                        <?php endif; ?>
                    <?php else : ?>
                        Aucune validation
                    <?php endif; ?>
                    <br/>
                    <?php if ($canModifier) : ?>
                        <a
                            <?php /** @see \Application\Controller\AgentController::modifierAgentApplicationAction() */?>
                                href="<?php echo $this->url('agent/modifier-agent-application', ['agent-application' => $application->getId()], [], true); ?>"
                                class="ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon editer" title="Modifier une application maîtriser par l'agent"></span></a>
                    <?php endif; ?>
                    <?php if ($canHistoriser) : ?>
                        <?php if ($application->estNonHistorise()) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::historiserAgentApplicationAction() */?>
                                    href="<?php echo $this->url('agent/historiser-agent-application', ['agent-application' => $application->getId()], [], true); ?>"
                            >
                                <span class="icon historiser" title="Historiser une application maîtriser par l'agent"></span></a>
                        <?php else: ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::restaurerAgentApplicationAction() */?>
                                    href="<?php echo $this->url('agent/restaurer-agent-application', ['agent-application' => $application->getId()], [], true); ?>"
                            >
                                <span class="icon restaurer" title="Restaurer une application maîtriser par l'agent"></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canDetruire) : ?>
                        <a
                            <?php /** @see \Application\Controller\AgentController::detruireAgentApplicationAction() */?>
                                href="<?php echo $this->url('agent/detruire-agent-application', ['agent-application' => $application->getId()], [], true); ?>"
                                class="ajax-modal"
                                data-event="modification"
                        >
                            <span class="icon detruire" title="Supprimer définitivement une application maîtriser par l'agent"></span>
                        </a>
                    <?php endif; ?>
                    <?php if ($canValider) : ?>
                        <?php if ($application->getValidation() === null) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::validerElementAction() */ ?>
                                href="<?php echo $this->url('agent/valider-element', ['type' => "AgentApplication", 'id' => $application->getId()], [], true); ?>"
                                class="ajax-modal"
                                data-event="modification"
                            >
                                <span class="icon validation-do" title="Valider l'application"></span></a>
                        <?php else: ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::revoquerElementAction() */ ?>
                                    href="<?php echo $this->url('agent/revoquer-element', ['validation' => $application->getValidation()->getId()], [], true); ?>"
                            >
                                <span class="icon validation-undo" title="Dévalider l'application"></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
        <div class="bloc">
            <h3>
                <span class="icon competence"></span>
                Compétences
                <?php if ($canAjouter) : ?>
                    <a
                        <?php /** @see \Application\Controller\AgentController::ajouterAgentCompetenceAction() */?>
                            href="<?php echo $this->url('agent/ajouter-agent-competence', ['agent' => $agent->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon ajouter" title="Ajouter une compétence liée à l'agent"></span>
                    </a>
                <?php endif; ?>
            </h3>

            <ul>
                <?php foreach ($agent->getCompetences() as $competence) : ?>
                    <li>
                        <?php echo $competence->getCompetence()->getLibelle(); ?>
                        <br/>
                        <?php echo $competence->getNiveau(); ?>
                        - &nbsp;
                        <?php if ($competence->getValidation()) : ?>
                        <?php $validation = $competence->getValidation(); ?>
                        <?php if ($validation->getValeur() === null) : ?>
                            <span
                                    style="color:darkgreen;"
                                    title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                <span class="icon ok"></span>
                                Validée
                            </span>
                        <?php else: ?>
                        <span
                                style="color:darkred;"
                                title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                <span class="icon ko"></span>
                            Refusée
                        <?php endif; ?>
                            <?php else : ?>
                                Aucune validation
                            <?php endif; ?>
                    <br/>
                        <?php if ($canModifier) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::modifierAgentCompetenceAction() */?>
                                    href="<?php echo $this->url('agent/modifier-agent-competence', ['agent-competence' => $competence->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    data-event="modification"
                            >
                                <span class="icon editer" title="Modifier une compétence liée à l'agent"></span></a>
                        <?php endif; ?>
                        <?php if ($canHistoriser) : ?>
                            <?php if ($application->estNonHistorise()) : ?>
                                <a
                                    <?php /** @see \Application\Controller\AgentController::historiserAgentCompetenceAction() */?>
                                        href="<?php echo $this->url('agent/historiser-agent-competence', ['agent-competence' => $competence->getId()], [], true); ?>"
                                >
                                    <span class="icon historiser" title="Historiser une compétence liée à l'agent"></span></a>
                            <?php else: ?>
                                <a
                                    <?php /** @see \Application\Controller\AgentController::restaurerAgentCompetenceAction() */?>
                                        href="<?php echo $this->url('agent/restaurer-agent-competence', ['agent-competence' => $competence->getId()], [], true); ?>"
                                >
                                    <span class="icon restaurer" title="Restaurer une compétence liée à l'agent"></span></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canDetruire) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::detruireAgentCompetenceAction() */?>
                                    href="<?php echo $this->url('agent/detruire-agent-competence', ['agent-competence' => $competence->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    data-event="modification"
                            >
                                <span class="icon detruire" title="Supprimer définitivement une compétence liée à l'agent"></span>
                            </a>
                        <?php endif; ?>
                            <?php if ($canValider) : ?>
                                <?php if ($competence->getValidation() === null) : ?>
                                    <a
                                <?php /** @see \Application\Controller\AgentController::validerElementAction() */ ?>
                                href="<?php echo $this->url('agent/valider-element', ['type' => "AgentCompetence", 'id' => $competence->getId()], [], true); ?>"
                                class="ajax-modal"
                                data-event="modification"
                                    >
                                <span class="icon validation-do" title="Valider la compétence"></span></a>
                                <?php else: ?>
                                    <a
                                <?php /** @see \Application\Controller\AgentController::revoquerElementAction() */ ?>
                                    href="<?php echo $this->url('agent/revoquer-element', ['validation' => $competence->getValidation()->getId()], [], true); ?>"
                                    >
                                <span class="icon validation-undo" title="Dévalider la compétence"></span></a>
                                <?php endif; ?>
                            <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="bloc">
            <h3>
                <span class="icon formation"></span>
                Formations
                <?php if ($canAjouter) : ?>
                    <a
                        <?php /** @see \Application\Controller\AgentController::ajouterAgentFormationAction() */?>
                            href="<?php echo $this->url('agent/ajouter-agent-formation', ['agent' => $agent->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon ajouter" title="Ajouter une formation liée à l'agent"></span>
                    </a>
                <?php endif; ?>
            </h3>

            <ul>
                <?php foreach ($agent->getFormations() as $formation) : ?>
                    <li>
                        <?php echo $formation->getFormation()->getLibelle(); ?> <br/>
                        <?php echo $formation->getDate()->format('d/m/Y'); ?>
                        - &nbsp;
                        <?php if ($formation->getValidation()) : ?>
                        <?php $validation = $formation->getValidation(); ?>
                        <?php if ($validation->getValeur() === null) : ?>
                            <span
                                    style="color:darkgreen;"
                                    title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                <span class="icon ok"></span>
                                Validée
                            </span>
                        <?php else: ?>
                        <span
                                style="color:darkred;"
                                title=" Par <?php echo $validation->getHistoModificateur()->getDisplayName(); ?> le <?php echo $validation->getHistoModification()->format("d/m/Y"); ?>">
                                <span class="icon ko"></span>
                            Refusée
                        <?php endif; ?>
                            <?php else : ?>
                                Aucune validation
                            <?php endif; ?>
                    <br/>
                        <?php if ($canModifier) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::modifierAgentFormationAction() */?>
                                    href="<?php echo $this->url('agent/modifier-agent-formation', ['agent-formation' => $formation->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    data-event="modification"
                            >
                                <span class="icon editer" title="Modifier une formation liée à l'agent"></span></a>
                        <?php endif; ?>
                        <?php if ($canHistoriser) : ?>
                            <?php if ($application->estNonHistorise()) : ?>
                                <a
                                    <?php /** @see \Application\Controller\AgentController::historiserAgentFormationAction() */?>
                                        href="<?php echo $this->url('agent/historiser-agent-formation', ['agent-formation' => $formation->getId()], [], true); ?>"
                                >
                                    <span class="icon historiser" title="Historiser une formation liée à l'agent"></span></a>
                            <?php else: ?>
                                <a
                                    <?php /** @see \Application\Controller\AgentController::restaurerAgentFormationAction() */?>
                                        href="<?php echo $this->url('agent/restaurer-agent-formation', ['agent-formation' => $formation->getId()], [], true); ?>"
                                >
                                    <span class="icon restaurer" title="Restaurer une formation liée à l'agent"></span></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($canDetruire) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::detruireAgentFormationAction() */?>
                                    href="<?php echo $this->url('agent/detruire-agent-formation', ['agent-formation' => $formation->getId()], [], true); ?>"
                                    class="ajax-modal"
                                    data-event="modification"
                            >
                                <span class="icon detruire" title="Supprimer définitivement une formation liée à l'agent"></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($canValider) : ?>
                            <?php if ($formation->getValidation() === null) : ?>
                                <a
                            <?php /** @see \Application\Controller\AgentController::validerElementAction() */ ?>
                            href="<?php echo $this->url('agent/valider-element', ['type' => "AgentFormation", 'id' => $formation->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                                >
                            <span class="icon validation-do" title="Valider la formation"></span></a>
                            <?php else: ?>
                                <a
                            <?php /** @see \Application\Controller\AgentController::revoquerElementAction() */ ?>
                                href="<?php echo $this->url('agent/revoquer-element', ['validation' => $formation->getValidation()->getId()], [], true); ?>"
                                >
                            <span class="icon validation-undo" title="Dévalider la formation"></span></a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <?php echo $this->partial('partial/porte-folio', ['fichiers' => $agent->getFichiers(), 'agent' => $agent], []); ?>

</div>



<style>
    div.bloc {
        border: solid lightblue 1px;
        margin: 0.5rem;
        padding: 0.5rem;
        width: 32%;
        min-width: 200px;
        float: left;
    }

    .blocs {
        display: flex;
        flex-wrap: wrap;
    }
</style>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>