<?php

/**
 * @see \Application\Controller\AgentController::indexAction()
 * @var Agent[] $agents
 * @var array $params
 * @var ?string $error
 */

use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;

$canAfficher = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));

$this->headTitle("Index des agents");
$nbAgent = count($agents);
?>

<div class="row">
    <div class="col-md-6">
    <h1 class="page-header">
        Index des agents
        <span class="badge bg-secondary">
               <?php echo $nbAgent; ?>
           </span>
    </h1>
    </div>
    <div class="pull-right col-md-5">
        <br/>
        <div class=" alert alert-info">
            <span class="icon icon-synchroniser"></span>
            Les agents sont synchronisés.
        </div>
    </div>
</div>

<div class="main">

    <div class="card">
        <div class="card-header">
            Filtre de recherche des agents
        </div>
        <div class="card-body">
<!--            <h4> Recherche directe </h4>-->
            <?php echo $this->partial('partial/filtre-nominatif', ['params' => $params], [], true); ?>
            <hr>
<!--            <h3> Filtrage </h3>-->
            <?php echo $this->partial('partial/filtre', ['params' => $params], [], true); ?>
        </div>
    </div>

    <?php if ($error) : ?>
        <div class="alert alert-danger">
            <span class="icon icon-unchecked"></span>
            <?php echo $error; ?>
        </div>
    <?php endif; ?>

    <?php if ($params === null or $params === []) : ?>
        <div class="alert alert-info">
            <span class="icon icon-information"></span>
            Aucun critère de recherche.
        </div>
    <?php else : ?>
        <?php if ($nbAgent > 0 AND $nbAgent < 500) : ?>
        <table id="agents" class="datatable table table-condensed table-hover">
            <thead>
            <tr>
                <th> Source Id </th>
                <th> Dénomination </th>
                <th> Affectations </th>
                <th> <span title="Lié à un utilisateur de l'application">Lié</span> </th>
                <th class="action"> Action </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($agents as $agent) : ?>
                <tr>
                    <td>
                        <span class="badge"><?php echo $agent->getId(); ?>
                    </td>
                    <td>
                        <?php echo $agent->getDenomination(); ?>
                    </td>
                    <td>
                        <?php $affectations = $agent->getAffectationsActifs(); ?>
                        <ul>
                        <?php foreach ($affectations as $affectation) : ?>
                            <li>
                                <?php if ($affectation->isPrincipale()) { echo "<strong>"; } ?>
                                <?php echo $affectation->getStructure()->getLibelleCourt(); ?>
                                <?php if ($affectation->isPrincipale()) { echo "</strong>"; } ?>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                    </td>
                    <td>
                        <?php if ($agent->getUtilisateur() !== null) : ?>
                            <span class="icon icon-checked" style="color:darkgreen;" title="<?php echo $agent->getUtilisateur()->getDisplayName(); ?>"></span>
                            <?php echo $agent->getUtilisateur()->getUsername(); ?>
                        <?php else: ?>
                            <span class="icon icon-unchecked" style="color:darkred;"></span>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($canAfficher) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                                href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                                class="action secondary"
                                title="Accéder à la fiche de <span class='highlight agent'><?php echo $agent->getDenomination(true); ?></span>"
                                data-bs-html="true" data-bs-toggle="tooltip"
                            >
                                <span class="icon icon-voir"></span>
                                Accéder
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else : ?>
        <?php if ($nbAgent === 0) : ?>
        <div class="alert alert-warning">
            <span class="icon icon-information"></span>
            Aucun résultat pour votre réquête
        </div>
        <?php endif; ?>
        <?php if ($nbAgent > 500) : ?>
        <div class="alert alert-warning">
            <span class="icon icon-attention"></span>
            Plus de 500 agents de remontés. Pas d'affichage sous formes de tableaux
        </div>
        <?php endif; ?>
    <?php endif; ?>
    <?php endif; ?>

</div>

<script>
    $(document).ready(function() {
        $('#agents').DataTable({
            "sorting":   false,
            autoWidth: false,
            language: {
                "url": "/js/datatables_fr.json",
            },
            columnDefs: [
                { targets: [4], orderable: false }
            ]
        } );
    } );
</script>

