<?php

/**
 * @var Agent[] $agents
 */

use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;

$canAfficher = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));

?>

<div class="row">
    <div class="col-md-6">
    <h1 class="page-header">
        Agents
        <span class="badge">
               <?php echo count($agents); ?>
           </span>
    </h1>
    </div>
    <div class="pull-right col-md-5">
        <br/>
        <div class=" alert alert-info">
            <span class="icon synchoniser"></span>
            Les agents sont synchronisés depuis Octopus.
        </div>
    </div>
</div>

<div class="main">

    <?php if (count($agents) > 0) : ?>
        <table id="agents" class="table table-condensed">
            <thead>
            <tr>
                <th> Source Id </th>
                <th> Dénomination </th>
                <th> <span title="Lié à un utilisateur de l'application">Lié</span> </th>
                <th class="action"> Action </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($agents as $agent) : ?>
                <tr>
                    <td> <span class="badge"><?php echo $agent->getSourceName(); ?> - <?php echo $agent->getSourceId(); ?></span></td>
                    <td> <?php echo $agent->getDenomination(); ?></td>
                    <td>
                        <?php if ($agent->getUtilisateur() !== null) : ?>
                            <span class="icon ok" style="color:darkgreen;" title="<?php echo $agent->getUtilisateur()->getUsername(); ?>"></span>
                        <?php else: ?>
                            <span class="icon ko" style="color:darkred;"></span>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($canAfficher) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                                href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                            >
                                <span class="icon voir"  title="Afficher l'agent"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>

</div>

<script>
    $(document).ready(function() {
        $('#agents').DataTable( {
            "sorting":   false,
            language: {
                url: '/localisation/fr_FR.json'
            }
        } );
    } );

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
    $(function() {
        $("body").on("modification-noreload", function (event) {
            event.div.modal('hide');
        });
    });
</script>

