<?php

use Application\Provider\Privilege\MissionspecifiqueaffectationPrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use MissionSpecifique\Entity\Db\MissionSpecifique;

/**
 * @see \Application\Controller\AgentController::mesMissionsSpecifiquesAction()
 * @var MissionSpecifique[] $missions
 * @var Campagne $campagne
 */

$canAjouter  =  $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_MODIFIER));

?>

<?php echo $this->partial('partial/onglets', ['current' => 'mission-specifique', 'campagne' => $campagne]); ?>

<h1 class="page-header">  Liste des missions spécifiques des Agent·es dont je suis responsable </h1>


<?php if ($canAjouter) : ?>
    <a
        <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::ajouterAction() */?>
            href="<?php echo $this->url('mission-specifique-affectation/ajouter', [], [], true); ?>"
            class="ajax-modal btn btn-primary"
            data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Ajouter une mission spécifique
    </a>
<?php endif; ?>

<?php echo $this->affectationsMissionSpecifique($missions, ['retour' => $this->url('mes-missions-specifiques', [], [], true)]); ?>

<script>
    $(function () {
        $('#agents').DataTable({
            autoWidth: false,
            paging: false,
            columnDefs: [{
                "targets": 3,
                "orderable": false,
            }],
            language: {
                url: '/js/datatables_fr.json'
            }
        });
    });
</script>
