<?php
    echo $this->form($form);
?>

<script>
    $(document).ready(function() {
        // tinymce.remove();
        tinymce.init({
            selector: '.type2',
            toolbar: 'newdocument undo redo | bold italic underline | bullist',
            resize: true,
            language: 'fr_FR',
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck : true,
            branding: false,
            menu: {},
            body_id: 'description',
            setup: function (editor) {
                editor.on("focusout", function () {
                    console.log(tinymce.get('description').getContent());
                    $('textarea').val(tinymce.get('description').getContent());
                });
            }
        });
    });

    adaptForm();

    $('select#corps').change(function() {
        // console.log("Changement de corps : " + $(this).val());
        adaptForm();
    });

    function adaptForm() {
        let requestUrl = '<?php echo $this->url('ressource-rh/grade/get-grades'); ?>';

        $.ajax({
            url: requestUrl,
        }).done(function(data) {
            let corps = $('select#corps').find(":selected").val();
            let selected = $('select#grade').find(":selected").val();
            $('select#grade').find('option:not(:first)').remove();
            $.each(data, function(index, value) {
                if (value['corps'] == corps) {
                    if (value['id'] == selected) {
                        $("select#grade").append(new Option(value['libelle'], value['id'], false, true));
                    } else {
                        $("select#grade").append(new Option(value['libelle'], value['id'], false, false));
                    }
                }
            });
       });
    }

</script>
