<?php

use Application\Entity\Db\MissionSpecifiqueType;

/**
 * @see \Application\Controller\MissionSpecifiqueTypeController::afficherAction()
 * @var MissionSpecifiqueType $type
 */

$modificateur = ($type->getHistoModificateur())?:$type->getHistoCreateur();
$date = ($type->getHistoModification())?:$type->getHistoCreation();
?>

<div class="row">
    <div class="col-md-6">
        <dl>
            <dt> Libellé </dt>
            <dd> <?php echo $type->getLibelle(); ?></dd>
            <dt> Missions de ce type </dt>
            <dd>
                Nombre de missions : <?php echo count($type->getMissions()); ?> <br>
                <ul>
                    <?php foreach ($type->getMissions() as $mission) : ?>
                        <li> <?php echo $mission->getLibelle(); ?> </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl>
            <dt> Dernière modification </dt>
            <dd>
                <?php echo $date->format('d/m/Y à H:i:s'); ?> <br/>
                <?php echo $modificateur->getDisplayName(); ?>
            </dd>
        </dl>

        <?php if ($type->estHistorise()) : ?>
            <dl>
                <dt> Historisé </dt>
                <dd>
                    <?php echo $type->getHistoDestruction()->format('d/m/Y à H:i:s'); ?> <br/>
                    <?php echo $type->getHistoDestructeur()->getDisplayName(); ?>
                </dd>
            </dl>
        <?php endif; ?>
    </div>
</div>
