<?php

use Application\Entity\Db\MissionSpecifiqueType;
use Application\Provider\Privilege\MissionspecifiquePrivileges;
use Application\Provider\Privilege\MissionspecifiquethemePrivileges;
use Application\Provider\Privilege\MissionspecifiquetypePrivileges;

/**
 * @see \Application\Controller\MissionSpecifiqueTypeController::indexAction()
 * @var MissionSpecifiqueType[] $types
 */

$this->headTitle("Liste des types de mission spécifique");

$canIndexMissionSpecifique = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_INDEX));
$canIndexMissionSpecifiqueTheme = $this->isAllowed(MissionspecifiquethemePrivileges::getResourceId(MissionspecifiquethemePrivileges::MISSIONSPECIFIQUETHEME_INDEX));

$canAfficher = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_AFFICHER));
$canAjouter = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_MODIFIER));
$canModifier = $canAjouter;
$canHistoriser = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_HISTORISER));
$canEffacer = $this->isAllowed(MissionspecifiquetypePrivileges::getResourceId(MissionspecifiquetypePrivileges::MISSIONSPECIFIQUETYPE_DETRUIRE));

?>

<div class="row">
    <div class="col-md-9">
        <h1 class="page-header">
            Liste des types de mission spécifique
        </h1>

        <?php if ($canAjouter) : ?>
            <a href="<?php echo $this->url('mission-specifique-type/ajouter', [], [], true); ?>" class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un type de mission
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-3">
        <?php if ($canIndexMissionSpecifique) : ?>
            <a href="<?php echo $this->url("mission-specifique"); ?>" class="btn btn-primary">
                <span class="icon icon-listing"></span>
                Accéder aux missions
            </a>
        <?php endif; ?>
        <?php if ($canIndexMissionSpecifiqueTheme) : ?>
            <a href="<?php echo $this->url("mission-specifique-theme"); ?>" class="btn btn-primary">
                <span class="icon icon-listing"></span>
                Accéder aux thèmes
            </a>
        <?php endif; ?>
    </div>
</div>

<br/>

<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th> Libellé </th>
            <th> #Missions </th>
            <th style="width:10rem;"> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($types as $type) : ?>
            <tr class="<?php if ($type->estHistorise()) echo " historise "; ?>">
                <td> <?php echo $type->getLibelle(); ?> </td>
                <td> <?php echo count($type->getMissions()); ?> </td>
                <td>
                    <?php if ($canAfficher) : ?>
                        <a href="<?php echo $this->url('mission-specifique-type/afficher', ['type' => $type->getId()], [], true); ?>"
                           class="ajax-modal"
                        >
                            <span class="icon icon-voir" title="Afficher le type de mission spécifique"></span></a>
                    <?php endif; ?>
                    <?php if ($canModifier) : ?>
                        <a href="<?php echo $this->url('mission-specifique-type/modifier', ['type' => $type->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-editer" title="Modifier le type de mission spécifique"></span></a>
                    <?php endif; ?>
                    <?php if ($canHistoriser) : ?>
                        <?php if ($type->estNonHistorise()) : ?>
                            <a href="<?php echo $this->url('mission-specifique-type/historiser', ['type' => $type->getId()], [], true); ?>"
                                >
                                <span class="icon icon-historiser" title="Historiser le type de mission spécifique"></span></a>
                        <?php else : ?>
                            <a href="<?php echo $this->url('mission-specifique-type/restaurer', ['type' => $type->getId()], [], true); ?>"
                               >
                                <span class="icon icon-restaurer" title="Restaurer le type de mission spécifique"></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canEffacer) : ?>
                        <a href="<?php echo $this->url('mission-specifique-type/detruire', ['type' => $type->getId()], [], true); ?>"
                           class="ajax-modal" data-event="modification"
                        >
                            <span class="icon icon-unchecked" title="Supprimer le type de mission spécifique"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            tinyMCE.editors=[];
            window.location.reload();
        });
    });
</script>