<?php

/**
 * @var Note $note
 */

use UnicaenNote\Entity\Db\Note;

?>

<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt> Porte-notes </dt>
            <dd> <?php echo $note->getPortenote()->getId(); ?></dd>
            <dt> Type </dt>
            <dd> <?php echo $note->getType()->getLibelle(); ?></dd>
            <dt> Texte</dt>
            <dd> <?php echo $note->getTexte(); ?></dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>Modification </dt>
            <dd>
                <?php if ($note->getHistoModification()) : ?>
                    <?php echo $note->getHistoModification()->format('d/m/y à H:i:s'); ?> <br/>
                    par <?php echo $note->getHistoModificateur()->getDisplayName(); ?>
                <?php else : ?>
                    <?php echo $note->getHistoCreation()->format('d/m/y à H:i:s'); ?> <br/>
                    par <?php echo $note->getHistoCreateur()->getDisplayName(); ?>
                <?php endif; ?>
            </dd>
            <?php if ($note->getHistoDestruction()) : ?>
                <dt>Historisation</dt>
                <dd>
                    <?php echo $note->getHistoDestruction()->format('d/m/y à H:i:s'); ?> <br/>
                    par <?php echo $note->getHistoDestructeur()->getDisplayName(); ?>
                </dd>
            <?php endif; ?>
        </dl>
    </div>
</div>


