<?php

/**
 * @var ApplicationGroupe[] $groupes
 * @var boolean[] $droits
 */

$canAfficher = $droits['canAfficher'];
$canAjouter = $droits['canAjouter'];
$canEditer = $droits['canEditer'];
$canHistoriser = $droits['canEditer'];
$canDetruire = $droits['canEffacer'];

use Application\Entity\Db\ApplicationGroupe;

?>

<div class="row">
    <div class="col-md-8">
        <h2>
            Groupes d'applications
        </h2>
    </div>
    <div class="col-md-4">
        <?php if ($canAjouter) : ?>
            <br/>
            <a
                <?php /** @see ApplicationGroupeController::ajouterAction() */ ?>
                href="<?php echo $this->url('application/groupe/ajouter', [], [], true); ?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification">
                <span class="icon ajouter"></span>
                Ajouter un groupe
            </a>
        <?php endif; ?>
    </div>
</div>

<br/>

<div class="alert alert-info">
    Les groupes d'application permettent de rassembler les applications par ensemble notamment dans :
    <ul>
        <li> les fiches métiers et les fiches de postes; </li>
        <li> l'entretien professionnel. </li>
    </ul>
</div>

<br/>

<table class="datatable table table-condensed">
    <thead>
    <tr>
        <th> Libellé </th>
        <th style="width:12rem;"> #Application </th>
        <th style="width:12rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($groupes as $groupe) : ?>
        <tr <?php if ($groupe->estHistorise()) echo "class='historise'"; ?>>
            <td> <?php echo $groupe->getLibelle(); ?> </td>
            <td> <?php echo count($groupe->getApplications()); ?> </td>
            <td>
                <?php if ($canAfficher) : ?>
                    <a  <?php /** @see ApplicationGroupeController::afficherAction() */ ?>
                        href="<?php echo $this->url('application/groupe/afficher', ['application-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal">
                        <span class="icon voir" title="Afficher le groupe"></span></a>
                <?php else : ?>
                    <span class="icon voir" style="color:lightgrey;"></span>
                <?php endif; ?>
                <?php if ($canEditer) : ?>
                    <a
                        <?php /** @see ApplicationGroupeController::modifierAction() */ ?>
                        href="<?php  echo $this->url('application/groupe/editer', ['application-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal"
                        data-event="modification"
                    >
                        <span class="icon editer" title="Modifier le groupe"></span></a>
                <?php else : ?>
                    <span class="icon editer" style="color:lightgrey;"></span>
                <?php endif; ?>
                <?php if ($canHistoriser) : ?>
                    <?php if ($groupe->estNonHistorise()) : ?>
                        <a
                            <?php /** @see ApplicationGroupeController::historiserAction() */ ?>
                            href="<?php  echo $this->url('application/groupe/historiser', ['application-groupe' => $groupe->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser le groupe"></span></a>
                    <?php else : ?>

                        <a
                            <?php /** @see ApplicationGroupeController::restaurerAction() */ ?>
                            href="<?php  echo $this->url('application/groupe/restaurer', ['application-groupe' => $groupe->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer le groupe"></span></a>
                    <?php endif; ?>
                <?php else : ?>
                    <?php if ($groupe->estNonHistorise()) : ?>
                        <span class="icon historiser" style="color:lightgrey;"></span>
                    <?php else : ?>
                        <span class="icon restaurer" style="color:lightgrey;"></span>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <a
                        <?php /** @see ApplicationGroupeController::detruireAction() */ ?>
                        href="<?php  echo $this->url('application/groupe/detruire', ['application-groupe' => $groupe->getId()], [], true); ?>"
                        class="ajax-modal" data-event="modification"
                    >
                        <span class="icon detruire" title="Afficher le groupe"></span></a>
                <?php else : ?>
                    <span class="icon detruire" style="color:lightgrey;"></span>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>