<?php

/**
 * @see \Application\Controller\IndexController::indexSuperieurAction()
 * @var Agent $connectedAgent
 * @var Agent[] $agents
 * @var Campagne $campagnePrevious
 * @var Campagne $campagnesCurrents
 */
use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use Application\Provider\Privilege\FichePostePrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
?>

<h1 class="card-header">
    Liste des agents dont vous êtes le supérieur hiérarchique direct
</h1>

<div class="alert alert-info">
    <span class="icon icon-attention"></span>
    Ici ne figurent que les agents pour lesquels vous avez été désigné manuellement en tant que supérieur&middot;e hiérarchique direct&middot;e
</div>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<table class="table table-condensed table-hover">
    <thead>
    <tr>
        <th> Agent & Affectation </th>
        <th> Fiche de poste </th>
        <th> Entretien professionnel </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) : ?>
        <tr>
            <td>
                <?php echo $agent->getDenomination(); ?>
                <?php if ($canVoirAgent) : ?>
                    <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>">
                        <span class="icon icon-voir" title="Afficher les informations de l'agent"></span>
                    </a>
                <?php endif; ?>
                <br/>
                <?php $affectation = $agent->getAffectationPrincipale(); ?>
                <?php if ($affectation) : ?>
                    <?php $niveau2 = $affectation->getStructure()->getNiv2(); ?>
                    <?php if ($niveau2 !== null) : ?>
                        [<?php echo $niveau2->getLibelleCourt(); ?>]
                    <?php endif; ?>
                    <?php echo $affectation->getStructure()->getLibelleLong(); ?>
                <?php else : ?>
                    Aucune affectation principale
                <?php endif; ?>
            </td>
            <td>
                <?php $fichePoste = $agent->getFichePosteBest(); ?>
                <?php $canVoirFichePoste = $this->isAllowed($fichePoste, FichePostePrivileges::FICHEPOSTE_AFFICHER); ?>
                <?php if ($fichePoste) : ?>
                    <?php echo $this->etatbadge($fichePoste->getEtat()); ?>
                    <?php echo $fichePoste->getLibelleMetierPrincipal(); ?>
                    <?php if ($fichePoste->getLibelle()) : ?>
                        <br/>
                        <?php echo $fichePoste->getLibelle; ?>
                    <?php endif; ?>
                <?php else : ?>
                    Aucune fiche de poste
                <?php endif; ?>
                <br/>
                <?php if ($canVoirAgent) : ?>
                    <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], ['fragment' => 'fiches'], true); ?>">
                        <span class="icon gerer" title="Accéder à la gestion des fiches postes"></span>
                        <span class="small-lettrine">FP</span></a>
                <?php endif; ?>
                <?php if ($fichePoste AND $canVoirFichePoste) : ?>
                    <a href="<?php echo $this->url('fiche-poste/afficher', ['fiche-poste' => $fichePoste->getId()],[], true); ?>">
                        <span class="icon icon-voir" title="Afficher la fiche de poste"></span>
                        <span class="small-lettrine">FP</span></a>
                    <a href="<?php echo $this->url('fiche-poste/exporter', ['fiche-poste' => $fichePoste->getId()],[], true); ?>">
                        <span class="icon icon-pdf" title="Exporter la fiche de poste"></span>
                        <span class="small-lettrine">FP</span></a>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($campagnePrevious === null) : ?>
                    Aucune campagne précédente
                <?php else : ?>
                    Précédent (<?php echo $campagnePrevious->getAnnee(); ?>):
                    <?php $entretien = $agent->getEntretienProfessionnelByCampagne($campagnePrevious); ?>
                    <?php if ($entretien !== null) : ?>
                        Entretien du <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?>
                        <a href="<?php echo $this->url('entretien-professionnel/acceder', ['entretien' => $entretien->getId()], [], true); ?>"
                           target="_blank">
                            <span class="icon icon-voir"></span></a>
                        <a href="<?php echo $this->url('entretien-professionnel/exporter-crep', ['entretien' => $entretien->getId()], [], true); ?>"
                           target="_blank">
                            <span class="icon icon-pdf"></span><span class="small-lettrine">CREP</span></a>
                        <a href="<?php echo $this->url('entretien-professionnel/exporter-cref', ['entretien' => $entretien->getId()], [], true); ?>"
                           target="_blank">
                            <span class="icon icon-pdf"></span><span class="small-lettrine">CREF</span></a>
                    <?php else : ?>
                        Aucun entretien
                    <?php endif; ?>
                <?php endif; ?>
                <br/>

                <?php if ($campagnesCurrents !== null or $campagnesCurrents !== []) : ?>
                    <?php /** @var Campagne $campagneCurrent */ ?>
                    <?php foreach ($campagnesCurrents as $campagneCurrent) : ?>
                        Courant (<?php echo $campagneCurrent->getAnnee(); ?>):
                        <?php $entretien = $agent->getEntretienProfessionnelByCampagne($campagneCurrent); ?>
                        <?php if ($entretien !== null) : ?>
                            Entretien du <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?>
                            <a href="<?php echo $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon gerer"></span></a>
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::accederAction() */ ?>
                            <a href="<?php echo $this->url('entretien-professionnel/acceder', ['entretien-professionnel' => $entretien->getId()], [], true); ?>"
                               target="_blank">
                                <span class="icon icon-editer"></span></a>
                            <a href="<?php echo $this->url('entretien-professionnel/exporter-crep', ['entretien' => $entretien->getId()], [], true); ?>"
                               target="_blank">
                                <span class="icon icon-pdf"></span><span class="small-lettrine">CREP</span></a>
                            <a href="<?php echo $this->url('entretien-professionnel/exporter-cref', ['entretien' => $entretien->getId()], [], true); ?>"
                               target="_blank">
                                <span class="icon icon-pdf"></span><span class="small-lettrine">CREF</span></a>
                        <?php else : ?>
                            Aucun entretien
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::creerAction() */?>
                            <a href="<?php echo $this->url('entretien-professionnel/creer', ["campagne" => $campagneCurrent->getId()], ["query" => ["agent" => $agent->getId(), 'structure' => ($affectation AND $affectation->getStructure())?$affectation->getStructure()->getId():null]], true); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon icon-ajouter"></span></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <br/>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

