<?php

/**
 * @see \Application\Controller\IndexController::indexAction()
 * @var string $texte
 */

?>
<br>
<div>
    <?php echo $texte; ?>
</div>

<button>
    Button
</button>


<script>
    $('button').on("click", function () {
        // alert('clicked');
        const url = '<?php echo $this->url('entretien-professionnel/action', ['entretien-professionnel' => 1], [], true); ?>';

        $.ajax({
            url: url,
            method: 'GET',
            success: function (data) {
                // Mise à jour dynamique du contenu du popover
                // popover.setContent({content: data});
                console.log(data);
            },
            error: function () {
                console.error('Erreur lors de la récupération des données');
                // popover.setContent({content: 'Erreur lors du chargement des données.'});
            }
        });
    });
</script>
