<?php

/**
 * @see \Application\Controller\IndexController::indexSuperieurAction()
 * @var Agent $connectedAgent
 * @var Agent[] $agents
 * @var Campagne $campagnePrevious
 * @var Campagne $campagnesCurrents
 */
use Application\Entity\Db\Agent;
use Application\Provider\Privilege\AgentPrivileges;
use Application\Provider\Privilege\FichePostePrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
?>

<h1 class="panel-heading">
    Liste des agents dont vous êtes l'autorite hiérarchique
</h1>

<div class="alert alert-info">
    <span class="icon attention"></span>
    Ici ne figurent que les agents pour lesquels vous avez été désigné manuellement en tant qu'autorité hiérarchique
</div>

<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th> Agent </th>
            <th> Affectation </th>
            <th> Fiche de poste </th>
            <th> Entretien professionnel </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) : ?>
        <tr>
            <td>
                <?php echo $agent->getDenomination(); ?>
                <?php if ($canVoirAgent) : ?>
                    <a href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>">
                        <span class="icon voir" title="Afficher les informations de l'agent"></span>
                    </a>
                <?php endif; ?>
            </td>
            <td>
                <?php $affectation = $agent->getAffectationPrincipale(); ?>
                <?php if ($affectation) : ?>
                    <?php $niveau2 = $affectation->getStructure()->getNiv2(); ?>
                    <?php if ($niveau2 !== null) : ?>
                        <?php echo $niveau2->getLibelleLong(); ?> <br/>
                    <?php endif; ?>
                    <?php echo $affectation->getStructure()->getLibelleLong(); ?>
                <?php else : ?>
                    Aucune affectation principale
                <?php endif; ?>
            </td>
            <td>
                <?php $fichePoste = $agent->getFichePosteActive(true); ?>
                <?php if ($fichePoste) : ?>
                    <?php
                        $canVoirFichePoste = $this->isAllowed($fichePoste, FichePostePrivileges::FICHEPOSTE_AFFICHER);
                        $canExporterFichePoste = $canVoirFichePoste;
                        $canModifierFichePoste = $this->isAllowed($fichePoste, FichePostePrivileges::FICHEPOSTE_MODIFIER);
                        $canHistoriserFichePoste = $this->isAllowed($fichePoste, FichePostePrivileges::FICHEPOSTE_HISTORISER);
                    ?>
                    <?php echo ($fichePoste->getLibelleMetierPrincipal())?:"Aucune fiche métier principale"; ?>
                    <?php if ($canVoirFichePoste) : ?>
                        <a href="<?php echo $this->url('fiche-poste/afficher', ['fiche-poste' => $fichePoste->getId()], [], true); ?>" target="_blank">
                            <span class="icon voir"></span></a>
                    <?php endif; ?>
                    <?php if ($canExporterFichePoste) : ?>
                        <a href="<?php echo $this->url('fiche-poste/exporter', ['fiche-poste' => $fichePoste->getId()], [], true); ?>" target="_blank">
                            <span class="icon pdf"></span></a>
                    <?php endif; ?>
                    <?php if ($canExporterFichePoste) : ?>
                        <a href="<?php echo $this->url('fiche-poste/editer', ['fiche-poste' => $fichePoste->getId()], [], true); ?>" target="_blank">
                            <span class="icon editer"></span></a>
                    <?php endif; ?>
                    <?php if ($canExporterFichePoste) : ?>
                      <a href="<?php echo $this->url('fiche-poste/historiser', ['fiche-poste' => $fichePoste->getId()], ['query' => ['retour' => $this->url()]], true); ?>">
                          <span class="icon historiser"></span></a>
                    <?php endif; ?>
                <?php else : ?>
                    Aucune fiche de poste
                    <?php
                        $canAjouterFichePoste = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AJOUTER));
                        $isResponsable = $agent->hasSuperieurHierarchique($connectedAgent);
                    ?>

                    <?php if ( $canAjouterFichePoste AND $isResponsable) : ?>
                        <a href="<?php echo $this->url('fiche-poste/ajouter', ['agent' => $agent->getId()], [], true); ?>"
                           title="Ajouter une fiche de poste"
                        >
                            <span class="icon ajouter"></span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($campagnePrevious === null) : ?>
                    Aucune campagne précédente
                <?php else : ?>
                    Précédent (<?php echo $campagnePrevious->getAnnee(); ?>):
                    <?php $entretien = $agent->getEntretienProfessionnelByCampagne($campagnePrevious); ?>
                    <?php if ($entretien !== null) : ?>
                        Entretien du <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?>
                        <a href="<?php echo $this->url('entretien-professionnel/afficher', ['entretien' => $entretien->getId()], [], true); ?>"
                           target="_blank">
                            <span class="icon voir"></span></a>
                        <a href="<?php echo $this->url('entretien-professionnel/exporter-crep', ['entretien' => $entretien->getId()], [], true); ?>"
                           target="_blank">
                            <span class="icon pdf"></span><span class="small-lettrine">CREP</span></a>
                        <a href="<?php echo $this->url('entretien-professionnel/exporter-cref', ['entretien' => $entretien->getId()], [], true); ?>"
                           target="_blank">
                            <span class="icon pdf"></span><span class="small-lettrine">CREF</span></a>
                    <?php else : ?>
                        Aucun entretien
                    <?php endif; ?>
                <?php endif; ?>
                <br/>

                <?php if ($campagnesCurrents !== null or $campagnesCurrents !== []) : ?>
                    <?php /** @var Campagne $campagneCurrent */ ?>
                    <?php foreach ($campagnesCurrents as $campagneCurrent) : ?>
                        Courant (<?php echo $campagneCurrent->getAnnee(); ?>):
                        <?php $entretien = $agent->getEntretienProfessionnelByCampagne($campagneCurrent); ?>
                        <?php if ($entretien !== null) : ?>
                            Entretien du <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?>
                            <a href="<?php echo $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], [], true); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon gerer"></span></a>
                            <a href="<?php echo $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId()], [], true); ?>"
                               target="_blank">
                                <span class="icon editer"></span></a>
                            <a href="<?php echo $this->url('entretien-professionnel/exporter-crep', ['entretien' => $entretien->getId()], [], true); ?>"
                               target="_blank">
                                <span class="icon pdf"></span><span class="small-lettrine">CREP</span></a>
                            <a href="<?php echo $this->url('entretien-professionnel/exporter-cref', ['entretien' => $entretien->getId()], [], true); ?>"
                               target="_blank">
                                <span class="icon pdf"></span><span class="small-lettrine">CREF</span></a>
                        <?php else : ?>
                            Aucun entretien
                            <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::creerAction() */?>
                            <a href="<?php echo $this->url('entretien-professionnel/creer', ["campagne" => $campagneCurrent->getId()], ["query" => ["agent" => $agent->getId(), 'structure' => $affectation->getStructure()->getId()]]); ?>"
                               class="ajax-modal" data-event="modification">
                                <span class="icon ajouter"></span></a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <br/>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

