<?php

/**
 * @see \Application\Controller\IndexController::indexSuperieurAction()
 * @var Agent $connectedAgent
 * @var Agent[] $agents
 * @var Campagne[] $campagnes
 * @var EntretienProfessionnel[] $entretiens
 * @var Agent[] $agentsByCampagne
 * @var array $fichesDePoste
 * @var array $fichesDePostePdf
 */

use Application\Entity\Db\Agent;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;

?>

<h1 class="page-header">
    Liste des agents dont vous êtes le supérieur hiérarchique direct
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>


<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" href="#agent" aria-controls="agent" role="tab"   data-toggle="tabz">
        Liste des <br/> Agent·es
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#ficheposte" aria-controls="ficheposte" role="tab"   data-toggle="tabz">
            Fiches de  <br/> poste
        </a>
    </li>
    <?php foreach ($campagnes as $campagne) : ?>
        <li class="nav-item" >
            <a class="nav-link" href="#entretien_<?php echo $campagne->getId(); ?>" aria-controls="entretien_<?php echo $campagne->getId(); ?>" role="tab"   data-toggle="tabz">
                Entretiens professionnels <br/> <?php echo $campagne->getAnnee(); ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>


<div class="tab-content">
    <div id="agent" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/agents', ['agents' => $agents], [], true); ?>
    </div>
    <div id="ficheposte" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/ficheposte', ['agents' => $agents, 'fichesDePoste' => $fichesDePoste, 'fichesDePostePdf' => $fichesDePostePdf], [], true); ?>
    </div>
    <?php foreach ($campagnes as $campagne) : ?>
        <div id="entretien_<?php echo $campagne->getId(); ?>" class="tab-pane " role="tabpanel">
            <?php echo $this->partial('partial/entretien', ['campagne' => $campagne, 'agents' => $agentsByCampagne[$campagne->getId()], 'entretiens' => $entretiens[$campagne->getId()]], [], true); ?>
        </div>
    <?php endforeach; ?>
</div>


<script>
    $(function() {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "agent";

        $('a[aria-controls=' + name + ']').tab('show');

        $('.nav-item a').click(function (e) {
            // No e.preventDefault() here
            $(this).tab('show');
        });
    });

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

