<?php

/**
 * @see \Application\Controller\IndexController::indexAutoriteAction()
 * @var Agent $connectedAgent
 * @var Agent[] $agents
 * @var Campagne[] $campagnes
 * @var EntretienProfessionnel[] $entretiens
 * @var AgentMissionSpecifique[] $missionsSpecifiques
 * @var array $fichesDePoste
 * @var array $fichesDePostePdf
 * @var array $agentsByCampagne
 *
 * @var array $templates
 *
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentMissionSpecifique;
use Application\Provider\Privilege\MissionspecifiqueaffectationPrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\EntretienProfessionnel;

$canOngletMission = $this->isAllowed(MissionspecifiqueaffectationPrivileges::getResourceId(MissionspecifiqueaffectationPrivileges::MISSIONSPECIFIQUEAFFECTATION_ONGLET));
?>

<h1 class="page-header">
    Liste des agents dont vous êtes l'autorité hiérarchique direct·e
</h1>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>

<div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="agent-tab"
            data-bs-toggle="tab" data-bs-target="#agent"
            type="button" role="tab" aria-controls="agent" aria-selected="true">
        Liste des <br/> Agent·es
    </button>
    <button class="nav-link" id="ficheposte-tab"
            data-bs-toggle="tab" data-bs-target="#ficheposte"
            type="button" role="tab" aria-controls="ficheposte" aria-selected="true">
        Fiches de  <br/> poste
    </button>
    <?php if ($canOngletMission) : ?>
        <button class="nav-link" id="missionspecifique-tab"
                data-bs-toggle="tab" data-bs-target="#missionspecifique"
                type="button" role="tab" aria-controls="missionspecifique" aria-selected="true">
            Missions  <br/> spécifiques
        </button>
    <?php endif; ?>
    <?php foreach ($campagnes as $campagne) : ?>
        <button class="nav-link" id="entretien_<?php echo $campagne->getId(); ?>-tab"
                data-bs-toggle="tab" data-bs-target="#entretien_<?php echo $campagne->getId(); ?>"
                type="button" role="tab" aria-controls="entretien_<?php echo $campagne->getId(); ?>" aria-selected="true">
            Entretiens professionnels <br/> <?php echo $campagne->getAnnee(); ?>
        </button>
    <?php endforeach; ?>
</div>


<div class="tab-content">
    <div id="agent" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/agents', ['agents' => $agents], [], true); ?>
    </div>
    <div id="ficheposte" class="tab-pane " role="tabpanel">
        <?php echo $this->partial('partial/ficheposte', ['agents' => $agents, 'fichesDePoste' => $fichesDePoste, 'fichesDePostePdf' => $fichesDePostePdf], [], true); ?>
    </div>
    <?php if ($canOngletMission) : ?>
        <div id="missionspecifique" class="tab-pane " role="tabpanel">
            <?php echo $this->partial('partial/missionspecifique', ['agents' => $agents, 'missionsSpecifiques' => $missionsSpecifiques], [], true); ?>
        </div>
    <?php endif; ?>
    <?php foreach ($campagnes as $campagne) : ?>
        <div id="entretien_<?php echo $campagne->getId(); ?>" class="tab-pane " role="tabpanel">
            <?php echo $this->partial('partial/entretien', ['campagne' => $campagne,  'connectedAgent' => $connectedAgent, 'agents' => $agentsByCampagne[$campagne->getId()], 'entretiens' => $entretiens[$campagne->getId()], 'templates' => $templates[$campagne->getId()]], [], true); ?>
        </div>
    <?php endforeach; ?>
</div>


<script>
    $(function () {
        let hash = $(location).attr('hash');
        let name = hash.substring(1);
        if (name === undefined || name === "") name = "agent";

        $('button').removeClass('active');
        $('button#' + name + '-tab').addClass('active');
        $('div.tab-pane').hide().removeClass('active');
        $('div#' + name).show().addClass('active');

        //$('#' + name + '-tab').tab("show");
        $('button.nav-link').on('click', function (e) {
            let anchor = $(this).attr('aria-controls');
            $('div.tab-pane').hide().removeClass('active');
            $('div#' + anchor).show().addClass('active');
            $('button').removeClass('active');
            $('button#' + anchor + '-tab').addClass('active');
            // console.log(anchor);
            e.preventDefault(); // >> bloque le scrolling, mais aussi la ré-écriture de l'url "#info" ...
            history.replaceState(null, null, "#" + anchor);
        });
    });

    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>

