<?php

/**
 * @var Agent $agent
 */

use Application\Entity\Db\Agent;
use Formation\Provider\Privilege\DemandeexternePrivileges;

$canAjouterDemande      = $this->isAllowed(DemandeexternePrivileges::getResourceId(DemandeexternePrivileges::DEMANDEEXTERNE_AJOUTER));

?>

<h2>
    Formuler une demande de formation
</h2>

<div>
    Afin de réaliser une demande de formation hors plan de formation, vous devez trouver au <em>moins trois</em> organismes et déposer les devis.
</div>

    <?php /** @see \Formation\Controller\DemandeExterneController::ajouterAction() */ ?>
    <a href="<?php echo $this->url('formation/demande-externe/ajouter', ['agent' => $agent->getId()], [], true); ?>"
       class="btn btn-primary ajax-modal <?php if (!$canAjouterDemande) echo " disabled "; ?> " data-event="modification"
    >
        <span class="icon icon-ajouter"></span>
        Je remplis le formulaire
    </a>
