<?php

/**
 * @var FormationInstanceInscrit[] $formations
 * @var Agent $agent
 */

use Application\Entity\Db\Agent;
use Formation\Entity\Db\FormationInstanceInscrit;
use Formation\Provider\Privilege\FormationinstancedocumentPrivileges;

$realisees  = array_filter($formations, function (FormationInstanceInscrit $a) { return $a->getInstance()->estRealisee();} );

$canHistorique = $this->isAllowed(FormationinstancedocumentPrivileges::getResourceId(FormationinstancedocumentPrivileges::FORMATIONINSTANCEDOCUMENT_HISTORIQUE));

?>

<h2>
    Formations réalisées
</h2>


<?php if ($canHistorique) : ?>
<?php /**  @see \Formation\Controller\FormationInstanceDocumentController::genererHistoriqueAction() */ ?>
<a href="<?php echo $this->url('formation-instance/generer-historique', ['agent' => $agent->getId()], [], true); ?>"
   class="btn btn-primary" target="_blank"
>
    <span class="icon icon-pdf"></span>
    Générer l'historique de formation
</a>
<?php endif; ?>

<?php if (empty($realisees)) : ?>
    <em> Aucune formation en attente de retour </em>
<?php else : ?>
    <?php foreach ($realisees as $inscription) : ?>
        <div class="row formation-inscription">
            <div class="col-md-8 description">
                <?php echo $this->formationInstanceInformations($inscription->getInstance(), 'bloc'); ?>
                <br/>
                <br/>
            </div>
            <div class="col-md-4">
                <a
                    <?php /** @see \Formation\Controller\FormationInstanceController::renseignerQuestionnaireAction() */?>
                        href="<?php echo $this->url('formation-instance/renseigner-questionnaire', ['inscrit' => $inscription->getId()], [], true); ?>"
                        class="btn btn-primary action"
                >
                    <span class="icon icon-editer"> Je complète le formulaire</span>
                </a>
                <br/>
                <a
                    <?php /** @see \Formation\Controller\FormationInstanceDocumentController::genererAttestationAction() */?>
                        href="<?php echo $this->url('formation-instance/generer-attestation', ['inscrit' => $inscription->getId()], [], true); ?>"
                        class="btn btn-primary action <?php if ($inscription->getQuestionnaire() === null) echo " disabled "; ?>"
                >
                    <span class="icon icon-pdf"> Je télécharge mon attestation</span>
                </a>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
