<?php

/**
 * @var FormationInstanceInscrit[] $formations
 * @var Agent $agent
 * @var string|null $mailcontact
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\Interfaces\HasSourceInterface;
use Formation\Entity\Db\FormationInstanceInscrit;
use Formation\Provider\Privilege\FormationinstancedocumentPrivileges;

$realisees  = array_filter($formations, function (FormationInstanceInscrit $a) { return $a->getInstance()->estRealisee();} );
usort($realisees, function (FormationInstanceInscrit $a, FormationInstanceInscrit $b) { return $a->getInstance()->getDebut(true) < $b->getInstance()->getDebut(true); });

$canHistorique = $this->isAllowed(FormationinstancedocumentPrivileges::getResourceId(FormationinstancedocumentPrivileges::FORMATIONINSTANCEDOCUMENT_HISTORIQUE));

?>

<h2>
    Formations réalisées
</h2>

<div class="alert alert-info">
    <span class="icon icon-attention"></span> Vous ne pourrez récupérer l'attestation pour une formation qu'une fois l'enquête associée saisie et validée.
</div>

<?php if ($canHistorique) : ?>
<?php /**  @see \Formation\Controller\FormationInstanceDocumentController::genererHistoriqueAction() */ ?>
<a href="<?php echo $this->url('formation-instance/generer-historique', ['agent' => $agent->getId()], [], true); ?>"
   class="btn btn-primary" target="_blank"
>
    <span class="icon icon-pdf"></span>
    Générer l'historique de formation
</a>
<?php endif; ?>

<?php if (empty($realisees)) : ?>
    <em> Aucune formation en attente de retour </em>
<?php else : ?>
    <?php foreach ($realisees as $inscription) : ?>
        <div class="row formation-inscription">
            <div class="col-md-7 description">
                <?php echo $this->formationInstanceInformations($inscription->getInstance(), 'bloc'); ?>
                <br/>
                <br/>
            </div>
            <div class="col-md-5">
                <?php if ($inscription->getSource()->getCode() === HasSourceInterface::SOURCE_LAGAF) : ?>
                    <div class="alert alert-warning">
                        <span class="icon icon-information"></span>
                        Formation gérée par LAGAF, pour obtenir votre attestion veuillez contacter
                        <?php if ($mailcontact === null) : ?>
                            la DRH
                        <?php else : ?>
                            <a href="mailto:<?php echo $mailcontact; ?>"><?php echo $mailcontact; ?></a>
                        <?php endif; ?>
                    </div>
                <?php else : ?>
                    <?php if ($inscription->getInstance()->getParametre() AND $inscription->getInstance()->getParametre()->isEnqueteActive() AND $inscription->getValidationEnquete() === null) : ?>
                    <a
                        <?php /** @see \Formation\Controller\EnqueteQuestionController::repondreQuestionsAction() */?>
                            href="<?php echo $this->url('formation/enquete/repondre-questions', ['inscrit' => $inscription->getId()], [], true); ?>"
                            class="btn btn-primary action <?php if ($inscription->getValidationEnquete() !== null) echo " disabled "; ?>"
                    >
                        <span class="icon icon-editer"> Je complète l'enquête</span>
                    </a>
                    <br/>
                    <a
                        <?php /** @see \Formation\Controller\EnqueteQuestionController::validerQuestionsAction() */?>
                            href="<?php echo $this->url('formation/enquete/valider-questions', ['inscrit' => $inscription->getId()], [], true); ?>"
                            class="btn btn-primary ajax-modal action <?php if (empty($inscription->getReponsesEnquete())) echo " disabled "; ?>"
                            data-event="modification"
                    >
                        <span class="icon icon-checked"> Je valide mes réponses</span>
                    </a>

                <br/>
                <?php else : ?>
                <a
                    <?php /** @see \Formation\Controller\FormationInstanceDocumentController::genererAttestationAction() */?>
                        href="<?php echo $this->url('formation-instance/generer-attestation', ['inscrit' => $inscription->getId()], [], true); ?>"
                        class="btn btn-primary action <?php //if ($inscription->getValidationEnquete() === null) echo " disabled "; ?>"
                >
                    <span class="icon icon-pdf"> Je télécharge mon attestation</span>
                </a>
                <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
