<?php

/**
 * @var FormationInstance[] $instances
 * @var FormationInstanceInscrit[] $inscriptions
 * @var Agent $agent
 */

use Application\Entity\Db\Agent;
use Formation\Entity\Db\FormationInstance;
use Formation\Entity\Db\FormationInstanceInscrit;

$canInscrire = true;



?>

<h2>
    S'inscrire à une session de formation du plan de formation
</h2>

<?php echo $this->messenger()->addMessagesFromFlashMessenger(); ?>


<?php foreach ($instances as $instance) : ?>
    <?php
        $nbPlace = ($instance->getNbPlacePrincipale() + $instance->getNbPlaceComplementaire()) - (count($instance->getListePrincipale()) + count($instance->getListeComplementaire()));
        $dejaInscrit = !empty(array_filter($inscriptions, function (FormationInstanceInscrit $a) use ($instance) { return $a->estNonHistorise() AND $a->getInstance() === $instance;}));
    ?>
    <div class="row formation-instance">
        <div class="col-md-8 description">
            <?php echo $this->formationInstanceInformations($instance, 'bloc'); ?>
        </div>
        <div class="col-md-4">
            <?php if ($dejaInscrit) : ?>
                <span class="alert alert-success"> <span class="icon icon-checked"></span>Demande d'inscription effectuée.</span>
            <?php else: ?>
                <?php if ($nbPlace <= 0) : ?>
                    <span class="alert alert-danger">Action de formation complète.</span>
                <?php else: ?>
                    <?php if ($canInscrire) : ?>
                        <?php /**  @see \Formation\Controller\FormationInstanceInscritController::inscriptionAction() */ ?>
                        <a href="<?php echo $this->url('formation-instance/inscription', ['formation-instance' => $instance->getId(), 'agent' => $agent->getId()], [], true); ?>"
                           class="btn btn-primary action ajax-modal" data-event="modification">
                            <span class="icon inscription-ouverture"> Je m'inscris</span>
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>