<?php

/**
 * @var string[] $categories
 * @var array $params
 */


?>

<div class="card">
    <div class="card-header bg-default">
        Filtre des types d'observation
    </div>
    <div class="card-body">
        <form method="get" action="<?php echo $this->url(); ?>">
            <div class="row">
                <div class="col-md-10">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="categorie"> Categorie : </label>
                            <select class="selectpicker" id="categorie" name="categorie"  data-live-search="true">
                                <option> Toutes les catégories </option>
                                <?php foreach ($categories as $categorie): ?>
                                    <option value="<?php echo $categorie; ?>"
                                        <?php if (isset($params['categorie']) && $params['categorie'] === $categorie) echo " selected "; ?>
                                    >
                                        <?php echo $categorie; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-primary" id="filter">
                        <span class="icon icon-filtrer"></span>
                        Filtrer
                    </button>
                    <br>
                    <button class="btn btn-primary" id="clear">
                        <span class="icon icon-gommer"></span>
                        R.A.Z.
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $('button#clear').on("click",function(e) {
        e.preventDefault();
        window.location.href = 'type';
    });

</script>