<?php

/**
 * @var Structure $structure
 * @var Agent[] $agents
 */

use Application\Entity\Db\Agent;
use Application\Entity\Db\AgentGrade;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\AgentPrivileges;
use Application\Provider\Privilege\FichePostePrivileges;

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canVoirFichePoste          = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER));
$canAjouterFichePoste       = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AJOUTER));
$canModifierFichePoste      = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));
$canHistoriserFichePoste    = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_HISTORISER));
$canDetruireFichePoste      = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_DETRUIRE));

?>

<h2>
    Agents
    <span class="badge">
                    <?php echo count($agents); ?>
                </span>
</h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th>Dénomination</th>
        <th>Statut</th>
        <th>Grade</th>
<!--        <th>Poste</th>-->
        <th>Fiche</th>
        <th class="cell-action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($agents as $agent) :?>
        <tr>
            <td>
                <?php if ($canVoirAgent) : ?>
                    <a
                        <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                        href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                        target="_blank"
                    >
                        <?php echo $agent->getDenomination(); ?></a>
                <?php else : ?>
                    <?php echo $agent->getDenomination(); ?>
                <?php endif; ?>
            </td>
            <td>
                <?php $temoins = []; ?>
                <?php foreach ($agent->getStatutsActifs() as $statut) : ?>
                    <?php $temoins['Administratif'] = $statut->isAdministratif(); ?>
                    <?php $temoins['Titulaire'] = $statut->isTitulaire(); ?>
                    <?php $temoins['C.D.I.'] = $statut->isCdi(); ?>
                    <?php $temoins['C.D.D.'] = $statut->isCdd(); ?>
                <?php endforeach; ?>
                <ul>
                    <?php foreach ($temoins as $temoin => $valeur) : ?>
                        <?php if ($valeur === true) : ?>
                            <li> <?php echo $temoin; ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </td>
            <td>
                <?php /** @var AgentGrade $grade */ ?>
                <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                    <?php echo $grade->getStructure()->getLibelleCourt(); ?> <br/>
                    BAP <?php echo ($grade->getBap())?$grade->getBap()->getCategorie():"???"; ?> -
                    <?php echo $grade->getGrade()->getLibelleCourt(); ?>
                <?php endforeach; ?>
            </td>
<!--            <td>-->
<!--                --><?php //$posteA = $agent->getPosteActif(); ?>
<!--                --><?php //if ($posteA != null ) : ?>
<!--                    <span-->
<!--                        class="icon ok" style="color:darkgreen;"-->
<!--                        data-toggle="tooltip" data-html="true"-->
<!--                        title="--><?php //echo $posteA->getNumeroPoste(); ?><!--"-->
<!--                    >-->
<!---->
<!--                                    </span>-->
<!--                --><?php //else : ?>
<!--                    <span class="icon ko" style="color:darkred;"></span>-->
<!--                --><?php //endif; ?>
<!--            </td>-->
            <td>
                <?php $fiche = $agent->getFichePosteActif(); ?>
                <?php if ($fiche !== null) : ?>
                <?php if ($fiche->isComplete()) : ?>
                    <span
                        class="icon ok" style="color:darkgreen;"
                        data-toggle="tooltip" data-html="true"
                        title="<?php echo $fiche->getLibelleMetierPrincipal(); ?>"
                    >

                                        </span>
                <?php else: ?>
                <span
                    class="icon question" style="color:orangered;"
                    data-toggle="tooltip" data-html="true"
                    title="Fiche incomplète"
                >
                                    <?php endif; ?>
                    <?php else : ?>
                        <span class="icon ko" style="color:darkred;"></span>
                    <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirAgent) : ?>
                    <a
                        <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                            href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon personnel" data-toggle="tooltip" data-html="true" title="Voir les renseignements de <span class='highlight agent'><?php echo $agent->getDenomination(); ?></span>"></span></a>
                <?php endif; ?>
                <?php if($fiche === null) : ?>
                    <?php if ($canAjouterFichePoste) : ?>
                        <a
                            <?php /** @see \Application\Controller\FichePosteController::ajouterAction() */ ?>
                            href="<?php echo $this->url('fiche-poste/ajouter', ['agent' => $agent->getId()], [], true); ?>"
                            target="_blank"
                        ><span class="icon ajouter"
                               data-toggle="tooltip" data-html="true"
                               title="Ajouter la fiche de poste"></span></a>
                    <?php endif; ?>
                    <?php if ($canAjouterFichePoste) : ?>
                        <a
                            <?php /** @see \Application\Controller\FichePosteController::dupliquerAction() */ ?>
                            href="<?php echo $this->url('fiche-poste/dupliquer', ['structure' => $structure->getId(), 'agent' => $agent->getId()], [], true); ?>"
                            class="ajax-modal" data-event="duplication"
                        ><span class="icon cloner"
                               data-toggle="tooltip" data-html="true"
                               title="Dupliquer une fiche existante"></span></a>
                    <?php endif; ?>
                <?php else  :?>
                    <?php if ($canVoirFichePoste) : ?>
                        <a
                            <?php /** @see \Application\Controller\FichePosteController::afficherAction() */ ?>
                            href="<?php echo $this->url('fiche-poste/afficher', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                            target="_blank"
                        ><span class="icon fiche-poste"
                               data-toggle="tooltip" data-html="true"
                               title="Afficher la fiche de poste"></span></a>
                    <?php endif; ?>

                    <?php if ($canModifierFichePoste) : ?>
                        <a
                            <?php /** @see \Application\Controller\FichePosteController::editerAction() */ ?>
                            href="<?php echo $this->url('fiche-poste/editer', ['fiche-poste' => $fiche->getId()], [], true); ?>"
                            target="_blank"
                        ><span class="icon editer"
                               data-toggle="tooltip" data-html="true"
                               title="Modifier la fiche de poste"></span></a>
                    <?php endif; ?>

                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>

</table>