<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\AgentPrivileges;
use Application\Provider\Privilege\StructurePrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Entity\Db\Delegue;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;
use EntretienProfessionnel\Provider\Privilege\SursisPrivileges;

/**
 * @var Campagne $campagne
 * @var Structure $structure
 * @var Agent[] $agents
 * @var Delegue[] $delegues
 */

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canAjouterEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AJOUTER));
$canVoirEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AFFICHER));
$canModifierEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_MODIFIER));
$canHistoriserEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_HISTORISER));
$canDetruireEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_DETRUIRE));

$canSursisAjouter = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_AJOUTER));
$canSursisModifier = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_MODIFIER));
$canSursisSupprimer = $this->isAllowed(SursisPrivileges::getResourceId(SursisPrivileges::SURSIS_SUPPRIMER));

$canGererDelegue = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_GESTIONNAIRE);

$deleguesCampagne = array_filter($delegues, function (Delegue $a) use ($campagne) { return $a->getCampagne() === $campagne;});

$complete = [];
$encours = [];
$sans = [];

foreach ($agents as $agent) {
    //todo déplcer cela dans campagne ou dans le service de la campagne
    $entretien = null;
    foreach ($campagne->getEntretiensProfessionnels() as $e) {
        if ($e->getAgent() === $agent) {
            $entretien = $e;
            break;
        }
    }

    if ($entretien === null) {
        if ($agent->isContratLong()) $sans[$agent->getDenomination()] = $agent;
    } else {
        if ($entretien->isComplete()) {
            $complete[$agent->getDenomination()] = $entretien;
        } else {
            $encours[$agent->getDenomination()] = $entretien;
        }
    }
}

$enCours = $campagne->estEnCours();
?>

<h2> Informations sur la campagne </h2>

<div class="row">
    <div class="col-md-6">
            <dl class="dl-horizontal">
        <dt> Année </dt>
        <dd> <?php echo $campagne->getAnnee(); ?> </dd>
        <dt> Début de la campagne </dt>
        <dd> <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?></dd>
        <dt> Fin de la campagne </dt>
        <dd> <?php echo $campagne->getDateFin()->format('d/m/Y'); ?></dd>
        <dt> En cours </dt>
        <dd>
            <?php if ($enCours) : ?>
                <span style="color:darkgreen;"><span class="icon ok"></span>Oui</span>
            <?php else : ?>
                <span style="color:darkred;"><span class="icon ko"></span>Non</span>
            <?php endif; ?>
        </dd>
    </dl>

        <h3>Délégué&middot;e&middot;s pour la campagne
            <span class="badge"><?php echo count($deleguesCampagne); ?></span>
            <?php /** @see \EntretienProfessionnel\Controller\DelegueController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('entretien-professionnel/ajouter-delegue', ['structure' => $structure->getId(), 'campagne' => $campagne->getId()], [], true); ?>"
               data-toggle="tooltip" data-html="true" class="ajax-modal" data-event="modification"
            >
                <span class="icon ajouter"></span>
            </a>
        </h3>

        <?php if(empty($deleguesCampagne)) : ?>
            <i>Aucun délégué pour la campagne</i>
        <?php else : ?>
            <ul>
                <?php foreach ($deleguesCampagne as $delegue) : ?>
                    <li>
                        <span title="<?php echo $delegue->getDescription(); ?>" data-toggle="tooltip" data-html="true">
                            <?php echo $delegue->getAgent()->getDenomination(); ?>
                        </span>
                        <?php if ($canGererDelegue) : ?>
                            <?php /** @see \EntretienProfessionnel\Controller\DelegueController::retirerAction() */ ?>
                            <a href="<?php echo $this->url('entretien-professionnel/retirer-delegue', ['delegue' => $delegue->getId()], [], true); ?>">
                                <span class="icon detruire"></span>
                            </a>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>


    </div>
    <div class="col-md-6">
        <h3> Progression de la campagne</h3>

        <?php
            $nbComplete = count($complete);
            $nbEncours = count($encours);
            $nbSans = count($sans);
            $nbTotal =  $nbComplete + $nbEncours + $nbSans;

            $ratioComplete =  $nbComplete / $nbTotal * 100;
            $ratioEncours = $nbEncours / $nbTotal * 100;
            $ratioSans = 100 - ($ratioComplete + $ratioEncours);
        ?>

        <div class="progress">
            <div class="progress-bar complete" role="progressbar" style="width: <?php echo $ratioComplete; ?>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens complétés <?php echo $nbComplete; ?>/<?php echo $nbTotal; ?>">
                <?php echo round($ratioComplete); ?>%</div>
            <div class="progress-bar encours" role="progressbar" style="width: <?php echo $ratioEncours; ?>%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens en cours <?php echo $nbEncours; ?>/<?php echo $nbTotal; ?>">
            <?php echo round($ratioEncours); ?>%</div>
            <div class="progress-bar sans"   role="progressbar" style="width: <?php echo $ratioSans; ?>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
                 title="Entretiens non planifiés <?php echo $nbSans; ?>/<?php echo $nbTotal; ?>">
            <?php echo round($ratioSans); ?>%</div>
        </div>

    </div>
</div>

<?php echo $this->portenote('StructureController::afficherAction()>entretien', '', []); ?>

<h2>
    Entretiens professionnels complétés
    <span class="badge">
        <?php echo count($complete); ?>
    </span>
</h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Agent</th>
        <th> Responsable </th>
        <th> Date </th>
        <th> État </th>
        <th style="width:13rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($complete as $denomination => $entretien): ?>
        <tr>
            <td> <?php echo $entretien->getAgent()->getDenomination(); ?></td>
            <td> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </td>
            <td> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </td>
            <td>
                <?php echo $this->etatbadge($entretien->getEtat()); ?>
            </td>
            <td>
                <?php if ($canVoirEntretien) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::afficherAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/afficher', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon voir" title="Afficher l'entretien professionnel"></span></a>
                <?php endif; ?>
                <?php if ($canVoirEntretien) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::exporterAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/exporter', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon pdf" title="Exporter l'entretien professionnel"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<!-- Enrtetiens professtionnels en cours ------------------------------------------------------------------------------>
<h2>
    Entretiens professionnels en cours
    <span class="badge">
        <?php echo count($encours); ?>
    </span>
</h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Agent</th>
        <th> Responsable </th>
        <th> Date </th>
        <th> État </th>
        <th style="width:13rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($encours as $denomination => $entretien): ?>
        <tr>
            <td> <?php echo $entretien->getAgent()->getDenomination(); ?></td>
            <td> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </td>
            <td>
                <?php $sursis = $entretien->getSursisActif(); ?>
                <?php if ($sursis === null) : ?>
                    <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?>
                    <?php if ($canSursisAjouter) : ?>
                        <a      <?php /** @see \EntretienProfessionnel\Controller\SursisController::modifierAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/sursis/ajouter', ['entretien-professionnel' => $entretien->getId()], [], true); ?>"
                                class="ajax-modal" data-event="modification"
                        >
                            <span class="icon sursis"></span></a>
                    <?php endif; ?>
                <?php else : ?>
                    <span class="texte-sursis" title="<?php echo $sursis->getDescription(); ?>">
                        <?php echo $sursis->getSursis()->format('d/m/Y'); ?>
                    </span>
                    <?php if ($canSursisModifier) : ?>
                    <a      <?php /** @see \EntretienProfessionnel\Controller\SursisController::modifierAction() */ ?>
                            href="<?php echo $this->url('entretien-professionnel/sursis/modifier', ['sursis' => $sursis->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="icon sursis"></span></a>
                    <?php endif; ?>
                    <?php if ($canSursisSupprimer) : ?>
                        <a      <?php /** @see \EntretienProfessionnel\Controller\SursisController::supprimerAction() */ ?>
                                href="<?php echo $this->url('entretien-professionnel/sursis/supprimer', ['sursis' => $sursis->getId()], [], true); ?>"
                                class="ajax-modal" data-event="modification"
                        >
                            <span class="icon detruire"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php echo $this->etatbadge($entretien->getEtat()); ?>
            </td>
            <td>
                <?php if ($canVoirEntretien) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::afficherAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/afficher', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon voir" title="Afficher l'entretien professionnel"></span></a>
                <?php endif; ?>
                <?php if ($canModifierEntretien) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::renseignerAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon editer" title="Modifier l'entretien professionnel"></span></a>
                <?php endif; ?>
                <?php if ($canModifierEntretien) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::modifierAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="icon gerer" title="Modifier les paramètres de l'entretien professionnel"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriserEntretien) : ?>
                    <?php if ($entretien->estNonHistorise()) : ?>
                        <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::historiserAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/historiser', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser l'entretien professionnel'"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::historiserAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/restaurer', ['entretien' => $entretien->getId(), 'structure' => $structure->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer l'entretien professionnel"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruireEntretien) : ?>
                    <a  <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::detruireAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/detruire', ['entretien' => $entretien->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer définitivement l'entretien professionnel"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<h2>
    Agents sans entretien professionnel pour la campagne
    <span class="badge">
        <?php echo count($sans); ?>
    </span>
</h2>

<table class="table table-condensed">
    <thead>
        <tr>
           <th> Dénomination</th>
           <th> Structure </th>
           <th> Grade </th>
           <?php if ($enCours === true) : ?>
                <th style="width:13rem;"> Action </th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($sans as $denomination => $agent): ?>
            <tr>
                <td> <?php echo $denomination; ?> </td>
                <td>
                    <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                        <?php echo $grade->getStructure()->getLibelleLong(); ?>
                    <?php endforeach; ?>
                </td>
                <td>
                    <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                        <?php echo ($grade->getGrade())?$grade->getGrade()->getLibelleLong():"N.C."; ?>
                    <?php endforeach; ?>
                </td>
                <?php if ($enCours === true) : ?>
                    <td>
                        <?php if ($canVoirAgent) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                                href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                                target="_blank"
                                title="Affiche la fiche <span class='highlight agent'><?php echo $denomination; ?>"
                                data-toggle="tooltip" data-html="true"
                            >
                                <span class="icon personnel"></span></a>
                        <?php endif; ?>
                        <?php if ($canAjouterEntretien) : ?>
                            <a
                                <?php /** @see \EntretienProfessionnel\Controller\EntretienProfessionnelController::creerAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/creer', ['campagne' => $campagne->getId()], ["query" => ['structure' => $structure->getId(), 'agent' => $agent->getId()]], [], true); ?>"
                                title="Créer un entretien professionnel pour <span class='highlight agent'><?php echo $denomination; ?>"
                                class="ajax-modal" data-event="entretien"
                                data-toggle="tooltip" data-html="true"
                            >
                                <span class="icon ajouter"></span></a>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<style>
    span.texte-sursis {
        color:darkred;
        font-style: italic;
    }

    div.complete {
        background-color: #009600;
    }
    div.sans {
        background-color: #960000;
    }
    div.encours {
        background-color: #db9a00;
    }
</style>

<script>
    $(function() {
        $("body").on("entretien", function (event) {
            //let content = event.div.html();
            //let match_regex = content.match(/#[0-9]*/g)[0];
            //let id = match_regex.split('#')[1];
            //event.div.modal('hide');
            //let win = window.open('../../entretien-professionnel/renseigner/' + id + '?structure=' + <?php //echo ($structure)?$structure->getId():0; ?>//, '_blank');
            //if (win) {
            //    //Browser has allowed it to be opened
            //    win.focus();
            //} else {
            //    //Browser has blocked it
            //    alert('Please allow popups for this website');
            //}
            //console.log("entretien pro: " + id);
            //window.location.reload();
            // alert("L'entretien vien d'être créer");
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>