<?php

use Application\Entity\Db\Agent;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\AgentPrivileges;
use EntretienProfessionnel\Entity\Db\Campagne;
use EntretienProfessionnel\Provider\Privilege\EntretienproPrivileges;

/**
 * @var Campagne $campagne
 * @var Structure $structure
 * @var Agent[] $agents
 */

$canVoirAgent = $this->isAllowed(AgentPrivileges::getResourceId(AgentPrivileges::AGENT_AFFICHER));
$canAjouterEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AJOUTER));
$canVoirEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_AFFICHER));
$canModifierEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_MODIFIER));
$canHistoriserEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_HISTORISER));
$canDetruireEntretien = $this->isAllowed(EntretienproPrivileges::getResourceId(EntretienproPrivileges::ENTRETIENPRO_DETRUIRE));

$complete = [];
$encours = [];
$sans = [];

foreach ($agents as $agent) {
    //todo déplcer cela dans campagne ou dans le service de la campagne
    $entretien = null;
    foreach ($campagne->getEntretiensProfessionnels() as $e) {
        if ($e->getAgent() === $agent) {
            $entretien = $e;
            break;
        }
    }

    if ($entretien === null) {
        $sans[$agent->getDenomination()] = $agent;
    } else {
        //todo faire une fonction pour tester la completion
        if ($entretien->getValidationAgent() and $entretien->getValidationResponsable()) {
            $complete[$agent->getDenomination()] = $entretien;
        } else {
            $encours[$agent->getDenomination()] = $entretien;
        }
    }
}


?>


<h2> Informations sur la campagne </h2>

<dl class="dl-horizontal">
    <dt> Année </dt>
    <dd> <?php echo $campagne->getAnnee(); ?> </dd>
    <dt> Début de la campagne </dt>
    <dd> <?php echo $campagne->getDateDebut()->format('d/m/Y'); ?></dd>
    <dt> Fin de la campagne </dt>
    <dd> <?php echo $campagne->getDateFin()->format('d/m/Y'); ?></dd>
</dl>

<h2>
    Entretiens professionnels complétés
    <span class="badge">
        <?php echo count($complete); ?>
    </span>
</h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Agent</th>
        <th> Responsable </th>
        <th> Date </th>
        <th> État </th>
        <th style="width:13rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($complete as $denomination => $entretien): ?>
        <tr>
            <td> <?php echo $entretien->getAgent()->getDenomination(); ?></td>
            <td> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </td>
            <td> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </td>
            <td>
                <?php if ($entretien->getValidationResponsable() !== null) : ?>
                    <span
                        data-toggle="tooltip"
                        data-html="true"
                        title="<?php echo $entretien->getValidationResponsable()->generateTooltipText(); ?>"
                    >
                        <span class="badge" style="background-color:darkgreen">Validé</span>
                    </span>
                <?php else : ?>
                    <?php if ($entretien->getValidationAgent() !== null) : ?>
                        <span
                            data-toggle="tooltip"
                            data-html="true"
                            title="<?php echo $entretien->getValidationAgent()->generateTooltipText(); ?>"
                        >
                            <span class="badge" style="background-color:darkorange">En attente de validation responsable </span>
                        </span>
                    <?php else : ?>
                        <span class="badge" style="background-color:orangered">En attente de validation agent </span>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirEntretien) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::afficherAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/afficher', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon voir" title="Afficher l'entretien professionnel"></span></a>
                <?php endif; ?>
                <?php if ($canVoirEntretien) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::exporterAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/exporter', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon pdf" title="Exporter l'entretien professionnel"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<h2>
    Entretiens professionnels en cours
    <span class="badge">
        <?php echo count($encours); ?>
    </span>
</h2>

<table class="table table-condensed">
    <thead>
    <tr>
        <th> Agent</th>
        <th> Responsable </th>
        <th> Date </th>
        <th> État </th>
        <th style="width:13rem;"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($encours as $denomination => $entretien): ?>
        <tr>
            <td> <?php echo $entretien->getAgent()->getDenomination(); ?></td>
            <td> <?php echo $entretien->getResponsable()->getDisplayName(); ?> </td>
            <td> <?php echo $entretien->getDateEntretien()->format('d/m/Y'); ?> </td>
            <td>
                <?php if ($entretien->getValidationResponsable() !== null) : ?>
                    <span
                        data-toggle="tooltip"
                        data-html="true"
                        title="<?php echo $entretien->getValidationResponsable()->generateTooltipText(); ?>"
                    >
                        <span class="badge" style="background-color:darkgreen">Validé</span>
                    </span>
                <?php else : ?>
                    <?php if ($entretien->getValidationAgent() !== null) : ?>
                        <span
                            data-toggle="tooltip"
                            data-html="true"
                            title="<?php echo $entretien->getValidationAgent()->generateTooltipText(); ?>"
                        >
                            <span class="badge" style="background-color:darkorange">En attente de validation responsable </span>
                        </span>
                    <?php else : ?>
                        <span class="badge" style="background-color:orangered">En attente de validation agent </span>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($canVoirEntretien) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::afficherAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/afficher', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon voir" title="Afficher l'entretien professionnel"></span></a>
                <?php endif; ?>
                <?php if ($canModifierEntretien) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::renseignerAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/renseigner', ['entretien' => $entretien->getId()], [], true); ?>"
                            target="_blank"
                    >
                        <span class="icon editer" title="Modifier l'entretien professionnel"></span></a>
                <?php endif; ?>
                <?php if ($canModifierEntretien) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::modifierAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/modifier', ['entretien' => $entretien->getId()], [], true); ?>"
                            class="ajax-modal" data-event="modification"
                    >
                        <span class="icon gerer" title="Modifier les paramètres de l'entretien professionnel"></span></a>
                <?php endif; ?>
                <?php if ($canHistoriserEntretien) : ?>
                    <?php if ($entretien->estNonHistorise()) : ?>
                        <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::historiserAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/historiser', ['entretien' => $entretien->getId()], [], true); ?>"
                        >
                            <span class="icon historiser" title="Historiser l'entretien professionnel'"></span></a>
                    <?php else : ?>
                        <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::historiserAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/restaurer', ['entretien' => $entretien->getId(), 'structure' => $structure->getId()], [], true); ?>"
                        >
                            <span class="icon restaurer" title="Restaurer l'entretien professionnel"></span></a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruireEntretien) : ?>
                    <a  <?php /** @see \Application\Controller\EntretienProfessionnelController::detruireAction() */?>
                            href="<?php echo $this->url('entretien-professionnel/detruire', ['entretien' => $entretien->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                    >
                        <span class="icon detruire" title="Supprimer définitivement l'entretien professionnel"></span></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<h2>
    Agents sans entretien professionnel pour la campagne
    <span class="badge">
        <?php echo count($sans); ?>
    </span>
</h2>

    <table class="table table-condensed">
        <thead>
            <tr>
               <th> Dénomination</th>
                <th> Structure </th>
               <th> Grade </th>
               <th style="width:13rem;"> Action </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($sans as $denomination => $agent): ?>
                <tr>
                    <td> <?php echo $denomination; ?> </td>
                    <td>
                        <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                            <?php echo $grade->getStructure()->getLibelleLong(); ?>
                        <?php endforeach; ?>
                    </td>
                    <td>
                        <?php foreach ($agent->getGradesActifs() as $grade) : ?>
                            <?php echo $grade->getGrade()->getLibelleLong(); ?>
                        <?php endforeach; ?>
                    </td>
                    <td>
                        <?php if ($canVoirAgent) : ?>
                            <a
                                <?php /** @see \Application\Controller\AgentController::afficherAction() */?>
                                href="<?php echo $this->url('agent/afficher', ['agent' => $agent->getId()], [], true); ?>"
                                target="_blank"
                                title="Affiche la fiche <span class='highlight agent'><?php echo $denomination; ?>"
                                data-toggle="tooltip" data-html="true"
                            >
                                <span class="icon personnel"></span></a>
                        <?php endif; ?>
                        <?php if ($canAjouterEntretien) : ?>
                            <a
                                <?php /** @see \Application\Controller\EntretienProfessionnelController::creerAction() */?>
                                href="<?php echo $this->url('entretien-professionnel/creer', ['campagne' => $campagne->getId()], ["query" => ['structure' => $structure->getId(), 'agent' => $agent->getId()]], [], true); ?>"
                                title="Créer un entretien professionnel pour <span class='highlight agent'><?php echo $denomination; ?>"
                                class="ajax-modal" data-event="entretien"
                                data-toggle="tooltip" data-html="true"
                            >
                                <span class="icon ajouter"></span></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

<script>
    $(function() {
        $("body").on("entretien", function (event) {
            //let content = event.div.html();
            //let match_regex = content.match(/#[0-9]*/g)[0];
            //let id = match_regex.split('#')[1];
            //event.div.modal('hide');
            //let win = window.open('../../entretien-professionnel/renseigner/' + id + '?structure=' + <?php //echo ($structure)?$structure->getId():0; ?>//, '_blank');
            //if (win) {
            //    //Browser has allowed it to be opened
            //    win.focus();
            //} else {
            //    //Browser has blocked it
            //    alert('Please allow popups for this website');
            //}
            //console.log("entretien pro: " + id);
            //window.location.reload();
            // alert("L'entretien vien d'être créer");
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>