<?php

use Application\Entity\Db\Structure;

/**
 * @var Structure $structure
 */

?>

<h2>Listing des fiches de postes</h2>

<a
        <?php /** @see \Application\Controller\StructureController::extractionListingFichePosteAction() */ ?>
        href="<?php echo $this->url('structure/extraction/listing-fiche-poste', ['structure' => $structure->getId()], [], true); ?>"
   class="btn btn-primary action"
>
    <span class="icon csv"></span> Extraire au format CSV
</a>

<h2>Listing des missions spécifiques</h2>

<a
    <?php /** @see \Application\Controller\StructureController::extractionListingMissionSpecifiqueAction() */ ?>
        href="<?php echo $this->url('structure/extraction/listing-mission-specifique', ['structure' => $structure->getId()], [], true); ?>"
        class="btn btn-primary action"
>
    <span class="icon csv"></span> Extraire au format CSV
</a>