<?php

/**
 * @see \Application\Controller\StructureController::afficherAction()
 * @var Structure $structure
 * @var FichePoste[] $fichesCompletes
 * @var FichePoste[] $fichesIncompletes
 */

use Application\Entity\Db\FichePoste;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\FichePostePrivileges;

$canVoirFichePoste          = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AFFICHER));
$canAjouterFichePoste       = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_AJOUTER));
$canModifierFichePoste      = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_MODIFIER));
$canHistoriserFichePoste    = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_HISTORISER));
$canDetruireFichePoste      = $this->isAllowed(FichePostePrivileges::getResourceId(FichePostePrivileges::FICHEPOSTE_DETRUIRE));
?>

<?php echo $this->portenote('StructureController::indexAction()>Fiche', '', []); ?>

<h2>
    Fiches de postes complètes
    <span class="badge">
            <?php echo count($fichesCompletes); ?>
        </span>
</h2>

<?php echo $this->fichesPostesAsArray($fichesCompletes); ?>

<h2>
    Fiches de postes incomplètes
    <span class="badge">
            <?php echo count($fichesIncompletes); ?>
        </span>
</h2>

<?php echo $this->fichesPostesAsArray($fichesIncompletes); ?>

