<?php

/**
 * @var Structure $structure
 * @var AgentMissionSpecifique[] $missions
 */

use Application\Entity\Db\AgentMissionSpecifique;
use Application\Entity\Db\Structure;
use Application\Provider\Privilege\MissionspecifiquePrivileges;

//TODO et les assertions qui vont bien : gestionnaire de la bonne structure pour les modifications

$canVoirAffectation         = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_AFFECTATION_AFFICHER));
$canAjouterAffectation      = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_AFFECTATION_AJOUTER));
$canModifierAffectation     = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_AFFECTATION_MODIFIER));
$canHistoriserAffectation   = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_AFFECTATION_HISTORISER));
$canDetruireAffectation     = $this->isAllowed(MissionspecifiquePrivileges::getResourceId(MissionspecifiquePrivileges::MISSIONSPECIFIQUE_AFFECTATION_DETRUIRE));
?>

<div class="row">
    <div class="col-md-8">
        <h2>
            Missions spécifiques
            <span class="badge">
                <?php echo count($missions); ?>
            </span>
        </h2>
    </div>
    <div class="col-md-4">
        <?php if ($canAjouterAffectation) : ?>
            <br/>
            <a
                <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::ajouterAction() */ ?>
                href="<?php echo $this->url('mission-specifique/affectation/ajouter', [], ["query" => ['structure' => $structure->getId()]], true); ?>"
                class="btn btn-primary action ajax-modal"
                data-event="modification"
            >
                <span class="icon ajouter"></span>
                Ajouter une mission spécifique
            </a>
        <?php endif; ?>
    </div>
</div>

<table class="datatable table table-condensed">
    <thead>
        <tr>
            <th> Agent </th>
            <th> Structure </th>
            <th> Mission </th>
            <th> Volume horaire </th>
            <th class="cell-action"> Action </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($missions as $mission) : ?>
            <tr <?php echo ($mission->estHistorise())?'class="historise"':''; ?>>
                <td> <?php echo $mission->getAgent()->getDenomination(); ?> </td>
                <td> <?php echo $mission->getStructure()->getLibelleLong(); ?> </td>
                <td> <?php echo $mission->getMission()->getLibelle(); ?> </td>
                <td>
                    <?php if ($mission->getDecharge() !== null): ?>
                        <?php echo $mission->getDecharge(); ?> h.
                    <?php else : ?>
                        Aucune
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($canVoirAffectation) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::afficherAction() */?>
                            href="<?php echo $this->url('mission-specifique/affectation/afficher', ['affectation' => $mission->getId()], [], true); ?>"
                            class="ajax-modal"
                        >
                            <span class="icon voir" data-toggle='tooltip'  data-html='true' title="Afficher l'affectation"></span></a>
                    <?php endif; ?>
                    <?php if ($canModifierAffectation) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::modifierAction() */?>
                            href="<?php echo $this->url('mission-specifique/affectation/modifier', ['affectation' => $mission->getId()], ["query" => ['structure' => $structure->getId()]], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                        >
                            <span class="icon editer" data-toggle='tooltip'  data-html='true' title="Modifier l'affectation"></span></a>
                    <?php endif; ?>
                    <?php if ($canHistoriserAffectation) : ?>
                        <?php if ($mission->estNonHistorise()) : ?>
                            <a
                                <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::historiserAction() */?>
                                    href="<?php echo $this->url('mission-specifique/affectation/historiser', ['affectation' => $mission->getId()], ["query" => ["retour" => $this->url('structure/afficher', ['structure' => $structure->getId()], [], true)]], true); ?>"
                            >
                                <span class="icon historiser" data-toggle='tooltip'  data-html='true' title="Historiser l'affectation"></span></a>
                        <?php else : ?>
                            <a
                                <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::restaurerAction() */?>
                                href="<?php echo $this->url('mission-specifique/affectation/restaurer', ['affectation' => $mission->getId()], ["query" => ["retour" => $this->url('structure/afficher', ['structure' => $structure->getId()], [], true)]], true); ?>"
                            >
                                <span class="icon restaurer" data-toggle='tooltip'  data-html='true' title="Restaurer l'affectation"></span></a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($canDetruireAffectation) : ?>
                        <a
                            <?php /** @see \Application\Controller\MissionSpecifiqueAffectationController::detruireAction() */?>
                            href="<?php echo $this->url('mission-specifique/affectation/detruire', ['affectation' => $mission->getId()], [], true); ?>"
                            class="ajax-modal"
                            data-event="modification"
                        >
                            <span class="icon detruire" data-toggle='tooltip'  data-html='true' title="Supprimer l'affectation"></span></a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>