<?php

/**
 * @var Structure $structure
 * @var Structure[] $filles
 */

use Application\Entity\Db\Structure;
use Application\Provider\Privilege\StructurePrivileges;

$canEditerDescription   = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_DESCRIPTION);
$canEditerGestionnaire  = $this->isAllowed($structure, StructurePrivileges::STRUCTURE_GESTIONNAIRE);
?>

<div class="row">

    <div class="col-md-6">
        <h2>
            Description
            <?php if ($canEditerDescription) : ?>
                <a
                    <?php /** @see \Application\Controller\StructureController::editerDescriptionAction() */ ?>
                    href="<?php echo $this->url('structure/editer-description', ['structure' => $structure->getId()], [], true); ?>"
                    class="ajax-modal"
                    data-event="modification"
                >
                    <span class="icon editer" data-toggle="tooltip" data-html="true"
                          title="Modifier la description de la structure <span class='structure'><?php echo $structure->getLibelleLong(); ?></span>">
                    </span></a>
            <?php endif; ?>
        </h2>
        <?php if ($structure->getDescription()) : ?>
            <?php echo $structure->getDescription(); ?>
        <?php else : ?>
            <span class="probleme"> <span class="icon attention"></span> Aucune description. </span>
        <?php endif; ?>
    </div>

    <div class="col-md-6">
        <h2>
            Gestionnaires
            <span class="badge"><?php echo count($structure->getGestionnaires()); ?></span>
            <?php if ($canEditerGestionnaire) : ?>
                <a
                    <?php /** @see \Application\Controller\StructureController::ajouterGestionnaireAction() */ ?>
                    href="<?php echo $this->url('structure/ajouter-gestionnaire', ['structure' => $structure->getId()], [], true); ?>"
                    class="ajax-modal"
                    data-event="modification"
                >
                    <span class="icon editer" data-toggle="tooltip" data-html="true"
                          title="Ajouter un gestionnaire à la structure <span class='structure'><?php echo $structure->getLibelleLong(); ?></span>">
                    </span></a>
            <?php endif; ?>
        </h2>
        <ul>
            <?php foreach ($structure->getGestionnaires() as $gestionnaire) : ?>
                <li>
                    <?php echo $gestionnaire->getDisplayName(); ?>
                    <?php if ($canEditerGestionnaire) : ?>
                        <a
                            <?php /** @see \Application\Controller\StructureController::retirerGestionnaireAction() */ ?>
                            href="<?php echo $this->url('structure/retirer-gestionnaire', ['structure' => $structure->getId(), 'gestionnaire' => $gestionnaire->getId()], [], true); ?>"
                        >
                            <span class="icon detruire"  data-toggle="tooltip" data-html="true"
                                  title="Supprimer la gestion de structure <span class='structure'><?php echo $structure->getLibelleLong(); ?></span> au gestionnaire <span class='user'><?php echo $gestionnaire->getDisplayName(); ?></span>">
                            </span></a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>

        <h2> Structure mère </h2>
        <?php if ($structure->getParent() !== null) :?>
            <ul>
                <li>
                    <a href="<?php echo $this->url('structure/afficher', ['structure' => $structure->getParent()->getId()], [] , true); ?> ">
                        <?php echo $structure->getParent()->getLibelleCourt(); ?>
                        -
                        <?php echo $structure->getParent()->getLibelleLong(); ?>
                    </a></li>
            </ul>
        <?php else : ?>
            Aucune structure mère
        <?php endif; ?>
        <h2>
            Structures filles
            <span class="badge">
                    <?php echo count($filles); ?>
                </span>
        </h2>
        <ul>
            <?php foreach ($filles as $enfant) : ?>
                <li>
                    <a href="<?php echo $this->url('structure/afficher', ['structure' => $enfant->getId()], [] , true); ?> ">
                        <?php echo $enfant->getLibelleCourt(); ?>
                        -
                        <?php echo $enfant->getLibelleLong(); ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>