<?php

/**
 * @see CompetenceController::afficherCompetenceTypeAction()
 *
 * @var CompetenceType $type
 */
use Element\Entity\Db\CompetenceType;

$utilisateur = ($type->getHistoModificateur()?:$type->getHistoCreateur());
$date = ($type->getHistoModification()?:$type->getHistoCreation());
?>

<dl class="dl-horizontal">
    <dt> Libellé </dt>
    <dd> <?php echo $type->getLibelle(); ?> </dd>
    <dt> Modificateur </dt>
    <dd> <?php echo $utilisateur->getDisplayName() ; ?> le <?php echo $date->format('d/m/Y à H:m:s'); ?> </dd>
    <dt> Compétences associées </dt>
    <dd>
        <span class="badge"> <?php echo count($type->getCompetences()); ?></span>
        <ul>
            <?php foreach ($type->getCompetences() as $competence) : ?>
                <li> <?php echo $competence->getLibelle(); ?> </li>
            <?php endforeach; ?>
        </ul>
    </dd>
</dl>
