<?php

/**
 * @see \Element\Controller\CompetenceTypeController::indexAction()
 * @var CompetenceType[] $types;
 */

use Element\Entity\Db\CompetenceType;
use Element\Provider\Privilege\CompetencePrivileges;
use Element\Provider\Privilege\CompetencethemePrivileges;
use Element\Provider\Privilege\CompetencetypePrivileges;

$this->headTitle("Liste des types de compétence");

$canCompetenceIndex = $this->isAllowed(CompetencePrivileges::getResourceId(CompetencePrivileges::COMPETENCE_INDEX));
$canCompetenceThemeIndex = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencethemePrivileges::COMPETENCETHEME_INDEX));

$canAfficher = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencetypePrivileges::COMPETENCETYPE_AFFICHER));
$canAjouter  = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencetypePrivileges::COMPETENCETYPE_AJOUTER));
$canModifier = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencetypePrivileges::COMPETENCETYPE_MODIFIER));
$canHistoriser = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencetypePrivileges::COMPETENCETYPE_HISTORISER));
$canDetruire = $this->isAllowed(CompetencethemePrivileges::getResourceId(CompetencetypePrivileges::COMPETENCETYPE_EFFACER));

$canAction = ($canAfficher OR $canModifier OR $canHistoriser OR $canDetruire);

?>

<h1 class="page-header">
    Liste des types de compétence
</h1>


<div class="row">
    <div class="col-md-6">
        <?php if ($canAjouter) : ?>
            <?php /** @see \Element\Controller\CompetenceTypeController::ajouterAction() */ ?>
            <a href="<?php echo $this->url('element/competence-type/ajouter', [], [], true); ?>"
               class="btn btn-primary ajax-modal" data-event="modification">
                <span class="icon icon-ajouter"></span>
                Ajouter un type
            </a>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <?php if ($canCompetenceIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence', [], [], true); ?>" class="btn btn-secondary">
                <span class="icon acceder"></span>
                Accéder aux compétences</a>
        <?php endif; ?>

        <?php if ($canCompetenceThemeIndex) : ?>
            <?php /** @see \Element\Controller\CompetenceThemeController::indexAction() */ ?>
            <a href="<?php echo $this->url('element/competence-theme', [], [], true); ?>" class="btn btn-secondary">
                <span class="icon acceder"></span>
                Accéder aux thèmes</a>
        <?php endif; ?>
    </div>
</div>


<table class="datatable table table-condensed table-hover">
    <thead>
    <tr>
        <th> Libellé </th>
        <th> #Compétence </th>
        <th> Ordre </th>
        <th class="action"> Action </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($types as $type) : ?>
        <tr class="<?php if ($type->estHistorise()) echo " historise "; ?>">
            <td> <?php echo $type->getLibelle(); ?> </td>
            <td> <?php echo count($type->getCompetences()); ?> </td>
            <td> <?php echo $type->getOrdre(); ?> </td>
            <?php if ($canAction) : ?>
            <td class="action">
                <?php if ($canAfficher) : ?>
                    <?php /** @see \Element\Controller\CompetenceTypeController::afficherAction() */ ?>
                    <a href="<?php echo $this->url('element/competence-type/afficher', ['competence-type' => $type->getId()], [], true); ?>"
                       class="ajax-modal">
                        <span class="icon icon-voir"></span>
                        Afficher
                    </a>
                <?php endif; ?>
                <?php if ($canModifier) : ?>
                    <br>
                    <?php /** @see \Element\Controller\CompetenceTypeController::modifierAction() */ ?>
                    <a href="<?php echo $this->url('element/competence-type/modifier', ['competence-type' => $type->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="icon icon-editer"></span>
                        Modifier
                    </a>
                <?php endif; ?>
                <?php if ($canHistoriser): ?>
                    <br>
                    <?php if($type->estNonHistorise()) : ?>
                        <?php /** @see \Element\Controller\CompetenceTypeController::historiserAction() */ ?>
                        <a href="<?php echo $this->url('element/competence-type/historiser', ['competence-type' => $type->getId()], [], true); ?>">
                            <span class="icon icon-historiser"></span>
                            Historiser
                        </a>
                    <?php else : ?>
                        <?php /** @see \Element\Controller\CompetenceTypeController::restaurerAction() */ ?>
                        <a href="<?php echo $this->url('element/competence-type/restaurer', ['competence-type' => $type->getId()], [], true); ?>">
                            <span class="icon icon-restaurer"></span>
                            Restaurer
                        </a>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($canDetruire) : ?>
                    <br>
                    <?php /** @see \Element\Controller\CompetenceTypeController::detruireAction() */ ?>
                    <a href="<?php echo $this->url('element/competence-type/detruire', ['competence-type' => $type->getId()], [], true); ?>"
                       class="ajax-modal" data-event="modification">
                        <span class="text-danger">
                            <span class="icon icon-retirer"></span>
                            Supprimer
                        </span>
                    </a>
                <?php endif; ?>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<script>
    $(function() {
        $("body").on("modification", function (event) {
            event.div.modal('hide');
            window.location.reload();
        });
    });
</script>