<?php

/**
 * @var string $title
 * @var string $text
 * @var ?string $retour
 */

?>

<div class="alert alert-danger">
    <p class="lead">
        <?php echo $text; ?>
    </p>
    <?php if ($retour !== null) : ?>
        <a href="<?php echo $retour; ?>" class="btn btn-secondary">
            <span class="icon icon-retour"></span>
            Retour en arrière
        </a>
    <?php endif; ?>
</div>

