<?php

/**
 * @see \Formation\Controller\ProjetPersonnelController::indexAction()
 * @var string $lien
 * @var string $texte
 */

$this->headTitle("Mon projet d'évolution professionnelle");
?>

<h1 class="page-header">
    Mon projet d'évolution professionnelle
</h1>

<p class="lead">
    <?php echo $texte; ?>
</p>

<a href="<?php echo $lien; ?>"
   class="btn btn-primary" target="_blank">
    <span class="icon icon-dossier"></span>
    Accéder à l'intranet
</a>

